### ISSUE TITLE
Site names with spaces and special characters fail

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1000]
**Steps to reproduce**
1. Create site from Pantheon and give it a name with spaces and special characters (something like "WEIRD NAME!@!!")
1. Site will appear to create correctly (including site create success message showing up in the console), but in actuality a great deal of sadness has occurred on the backend.

**Tech Details**

lib/util/domain.js: Look for function modKebabCase (and variable kebabMe). This happens on input in the CLI, so that's why the GUI can't get joy.

Using this validation in the front end will give us happiness.

**Comment by pirog** [comment]
@reynoldsalec we prob want to toLowerCase the result as well as per the issue ezenwa had
