### ISSUE TITLE
Allow closing sidebar by clicking outside of it

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1003]
We had to disable this behavior in the sidebar, since when we submitted the Pantheon Authentication form and changed state in the sidebar, it caused the sidebar to close. The exit button still works.

I think this *might* be resolved by simply specifying the ui-view area to enact the state change in specifically...unsure.

**Comment by reynoldsalec** [comment]
Initial theory didn't seem to work on this (gave the sidebar an explicit view name and enabled the autohide property for the sidebar). Will fiddle with a little bit more, but don't think it's too valuable.

**Comment by pirog** [comment]
BACKLOG THAT SHIT!

**Comment by reynoldsalec** [comment]
Ok, stopping propagation of the click event seemed to be the ultimate answer here, which is fine since we aren't reacting on it for submitting the Pantheon authentication form anyway.
