### ISSUE TITLE
Make the GUI interface resizable/responsive

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1004]
This issue is definitely for down the road, but _might_ be DCNOLA applicable.

**Scoping Questions**

- What range of display devices will people be using Kalabox on?
- What are reasons people would _want_ to have a "big screen" version of Kalabox? If they have a bunch of sites? If they want to show off the screenshots from those sites to people? Retina cinematic screens?
- Think about tiny laptop screens (probably our smallest device right now): what could run Kalabox and how?

**Comment by paucku** [comment]
I don't see reason for Kalabox's GUI to not be responsive.
