### ISSUE TITLE
Better document how pulling from pantheon backups works

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#1011]
I'm not sure if this is by design or if it's a bug, so bare with me. I tried searching for a related issue, but didn't seem to find anything, so my apologies if this has already been addressed.

On machine A: I did a ```kbox push``` to update my pantheon dev site. 

When I went to pantheon's dev URL everything seemed to work properly. 

Then on machine B: I did a ```kbox pull```

I select the "dev" database. Then I get asked "Create a new DB backup? (y/N)"  

If I keep it as the default value, of _N_, then it appears the database that gets downloaded from Pantheon to machine B, is out-of-date.   However if I select _Y_, it appears to download the changes I made onto machine B. 

As it turns out it appears if a DB backup is not being made on pantheon, then the DB that gets pulled is not the current DB on pantheon, but rather the most recently backed up version of the DB on pantheon.  

This seems odd and counter-intuitive, but could potentially make sense for some people (e.g. multiple developers calling kbox pull will get the exact same db to work with). My question is, is this by design or is something wrong?   

And if it is by design, there probably should be some clarifications about this in the documentation.  My assumption would be that ```kbox push``` would push the latest version and ```kbox pull``` would retrieve the latest version. 

I had lost some DB changes a couple weeks ago, and couldn't figure out what had happened until now, so at the very least an explanation of this process during the ```kbox pull``` screen and on the Kalabox/Pantheon integration README would go a long way.

**Comment by pirog** [comment]
This is by design. Unless you tell it otherwise it will pull the latest backup. For very large sites pulling directly from mysql takes a very very long time.

**Comment by WidgetsBurritos** [comment]
Okay. That definitely makes sense. I don't know if that's clearly explained though and could result in data-loss.  Any chance we can get this further elaborated in either the app, or on the Kalabox Pantheon App README to avoid confusion?

**Comment by WidgetsBurritos** [comment]
And thank you, by the way, for putting up with all my stupid questions. :-)

**Comment by pirog** [comment]
+1 for documentation improvements.

**Comment by pirog** [comment]
@WidgetsBurritos so thinking about this do you think better inline documentation might be the way to do here? Aka instead of

```
? Which database do you want to use? (Use arrow keys)
❯ dev 
  test 
  live 
```

Something like 

```
? Which database backup do you want to use? (Use arrow keys)
❯ dev 
  test 
  live 
```

**Comment by WidgetsBurritos** [comment]
I think what you did there is fine.   

But then on the step that asks `Create a new DB backup? (y/N)`, maybe instead of that, ask something like this: `Retrieve latest DB instead of most recent backup? (y/N)`

Then on the README with the Pantheon instructions (i.e. https://github.com/kalabox/kalabox-app-pantheon/blob/v0.11/README.md), under the "Pulling from Pantheon" section, put something like this:

> You can refresh your local code and even your database and files by running kbox pull from inside of your Pantheon app.
> 
> Important:  To avoid slow pulls on larger sites, Kalabox pulls from Pantheon's database backups, instead of the active database. If you would like to retrieve the most recent version of your database, you will need to indicate `y` when asked `Retrieve latest DB instead of most recent backup? (y/N)` or use the --newbackup flag.

**Comment by pirog** [comment]
@WidgetsBurritos thanks! yeah that is WAY better then what i had. :)

**Comment by WidgetsBurritos** [comment]
@pirog Okay cool.   Glad that still makes sense.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/tree/improveDocz

**Comment by WidgetsBurritos** [comment]
Looks good. Thanks.

**Comment by pirog** [comment]
No... Thank you!!!

**Comment by WidgetsBurritos** [comment]
You're welcome

**Comment by WidgetsBurritos** [comment]
Hate to reopen an old issue, but I've just noticed it's not completely fixed. 

When you run `kbox create pantheon` and download an app from pantheon the first time, it doesn't ask whether or not you want to pull from the latest backup or the active DB; it just auto-downloads from the backup.  Since this is a first impression given to the users, it's probably best that feature is offered upon setup as well, as I wouldn't necessarily think a separate `kbox pull` step would be necessary.

**Comment by pirog** [comment]
@WidgetsBurritos i think in the latest v0.12 pantheon app this is indeed fixed https://github.com/kalabox/kalabox-app-pantheon/blob/v0.12/app/plugins/kalabox-plugin-pantheon/lib/tasks.js#L97

**Comment by WidgetsBurritos** [comment]
I'm currently running `0.12.0-alpha.18` and it didn't ask me. Or if it did, I completely spaced out on it.  I can try running it again to double check.

**Comment by pirog** [comment]
if you are using a pre-12-existing app it might have the older code still in it

**Comment by WidgetsBurritos** [comment]
Anything in particular I should look for to correct it?

**Comment by WidgetsBurritos** [comment]
And if it works for everybody else, then it's a non-issue.   It's just not asking me in mine, so I thought I'd bring it up just in case.

**Comment by pirog** [comment]
My guess is if you install a new app it should prompt you the way you expect. If this doesn't happen then we have an issue.

**Comment by pirog** [comment]
How did you install the 0.12.0-alpha.18? did you use the new installer?

**Comment by WidgetsBurritos** [comment]
Yes. And I even compiled it myself from the latest source code following the instructions in the README.

`
$ docker-machine create -d virtualbox installer
$ eval "$(docker-machine env installer)"
$ make osx
`

And then ran the dmg installer inside the dist folder. 

Then I immediately did a `kbox create pantheon` and was not asked to pull from the latest DB.   It auto pulled from the last backup.

**Comment by pirog** [comment]
oh i see what you are saying. `kbox create pantheon` currently doesn't give you that option. its only in `kbox pull`

i would open a new ticket with a feature request for that

**Comment by WidgetsBurritos** [comment]
Okay.  Will do.
