### ISSUE TITLE
dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects

### ISSUE THREAD

**Issue by bsmirnov** [kalabox/kalabox#1030]
info: INSTALL =>  -- Step 14/18 --
info: INSTALL =>  Pulling images...
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/boris/.kalabox/downloads/kalabox/kalabox-1.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.2)...
info: DOCKER-COMPOSE =>  v0.11.2: Pulling from kalabox/proxy
Pulling dns (kalabox/dns:v0.11.2)...
info: DOCKER-COMPOSE =>  Digest: sha256:73defbd5a009a234da98e1ed3ab896eab8a8a014cc2cfacc33199de5bedf6498
Status: Image is up to date for kalabox/proxy:v0.11.2
info: DOCKER-COMPOSE =>  Pulling repository docker.io/kalabox/dns
ERROR: Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/dns/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
info: DOCKER-COMPOSE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/boris/.kalabox/downloads/kalabox/kalabox-2.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.2)...
info: DOCKER-COMPOSE =>  Pulling repository docker.io/kalabox/proxy
ERROR: Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
info: DOCKER-COMPOSE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/boris/.kalabox/downloads/kalabox/kalabox-3.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.2)...
info: DOCKER-COMPOSE =>  Pulling repository docker.io/kalabox/proxy
ERROR: Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
info: DOCKER-COMPOSE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/boris/.kalabox/downloads/kalabox/kalabox-4.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.2)...
info: DOCKER-COMPOSE =>  Pulling repository docker.io/kalabox/proxy
ERROR: Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
info: DOCKER-COMPOSE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/boris/.kalabox/downloads/kalabox/kalabox-5.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.2)...
info: DOCKER-COMPOSE =>  Pulling repository docker.io/kalabox/proxy
ERROR: Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
info: DOCKER-COMPOSE =>  Run exited with code: 1
info: INSTALL =>  VError: Failed after 5 retries. {"max":5,"backoff":500}: code1err:more:Pulling repository docker.io/kalabox/proxy

info: INSTALL =>  -- INSTALL FAILURE. --

I tried to delete Kalabox2 folder in .kalabox and rerun but it happens again.

**Comment by pirog** [comment]
Hey @bsmirnov i think this is probably the same underlying issue as in #900 which is a sad and long outstanding virtualbox bug that you can read about [here](http://stackoverflow.com/questions/24060099/how-to-fix-dockers-error-pulling-image-too-many-redirects-failures-while-pu) and [here](https://github.com/docker/distribution/issues/1292).

If you'd like to try some potential workarounds try these out.

```
# Run through the installer until it fails on the redirect
kbox update 

# SSH into the VM
~/.kalabox/bin/docker-machine ssh Kalabox2

# Use google dns (or openDNS at 208.67.222.222)
sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf

# Exit the virtual machine
exit

# Try to complete the install
kbox update
```


```

**Comment by bsmirnov** [comment]
@pirog This worked thank you.

**Comment by pirog** [comment]
awesome! I think we will be able to roll a fix for this into the next release.

**Comment by pirog** [comment]
@bsmirnov i rolled i new release of the kalabox boot2docker iso that should have a backup dns server in it
https://github.com/kalabox/kalabox-iso/releases/tag/v0.11.3

we will roll this out in our v0.11.3 release but you should be able to just download and replace the kalabox.iso

```
~/.kalabox/bin/docker-machine stop Kalabox2
cd ~/.docker/machine/machines/Kalabox2
rm boot2docker.iso
curl -L https://github.com/kalabox/kalabox-iso/releases/download/v0.11.3/kalabox.iso > boot2docker.iso
```
