### ISSUE TITLE
Better error message for unsupported versions of linux

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1033]
Error Error running step: {"name":"services-kalabox-admin","description":"Queuing up services admin commands...","deps":[],"subscribes":["core-run-admin-commands"],"first":false,"last":false,"all":{"darwin":null,"win32":null},"isStep":true}: Cannot call method 'replace' of undefined 
    /usr/local/bin/plugins/kalabox-services-kalabox/lib/util.js.jx:232:52 getResolverPkgName
    /usr/local/bin/plugins/kalabox-services-kalabox/lib/util.js.jx:253:30 getResolverPkgPath
    /usr/local/bin/plugins/kalabox-services-kalabox/lib/util.js.jx:263:15 getResolverPkgInstall
    /usr/local/bin/plugins/kalabox-services-kalabox/lib/install.js.jx:124:41 none
    /usr/local/bin/plugins/kalabox-services-kalabox/lib/install.js.jx:122:8 all.linux
    /usr/local/bin/lib/install/framework.js.jx:451:17 none
    /usr/local/bin/lib/install/framework.js.jx:449:30 none
    /usr/local/bin/lib/install/framework.js.jx:441:29 each.then.events.emit.state
    /usr/local/bin/lib/install/framework.js.jx:431:22 none
    /usr/local/bin/lib/install.js.jx:176:7 none
    /usr/local/bin/lib/install.js.jx:166:20 none
    /usr/local/bin/lib/install.js.jx:165:4 exports.run
    /usr/local/bin/lib/engine.js.jx:99:26 none
    /usr/local/bin/lib/engine.js.jx:95:6 verifyProviderInstalled
    /usr/local/bin/lib/engine.js.jx:204:10 verifyProviderIsReady
    /usr/local/bin/lib/engine.js.jx:329:10 exports.list
    /usr/local/bin/lib/app.js.jx:302:34 none
    /usr/local/bin/lib/app.js.jx:301:4 exports.cleanup
    /usr/local/bin/lib/create.js.jx:354:23 try.then.then.then.then.then.sysRoot
    node.js:803:1 _tickCallback
    /usr/local/bin/lib/create.js.jx:353:6 createApp
    /usr/local/bin/lib/create.js.jx:495:16 completed
    /usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10 onCompletion
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12 Rx.AnonymousObserver.AnonymousObserver.completed
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14 Rx.internals.AbstractObserver.AbstractObserver.onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29 tryCatcher
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56 completed
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14 Rx.internals.AbstractObserver.AbstractObserver.onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65 onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29 tryCatcher
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56 completed
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14 Rx.internals.AbstractObserver.AbstractObserver.onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29 tryCatcher
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56 completed
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14 Rx.internals.AbstractObserver.AbstractObserver.onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65 onCompleted
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29 tryCatcher
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56 completed
    /usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14 Rx.internals.AbstractObserver.AbstractObserver.onCompleted

**Comment by pirog** [comment]
For now I think we might want to just throw an error if the linux flavor
does not return debian or fedora

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/pull/1037

**Comment by rileysaurus** [comment]
Merged.
