### ISSUE TITLE
Feature request: behat integration

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1034]
It would be awesome to have behat integration, especially since the [Behat Drupal Extension](https://www.drupal.org/project/drupalextension) can't really do any of its magic unless it is using the "Drupal" driver, which requires behat to be running on the server that is hosting Drupal.

**Comment by pirog** [comment]
I believe in the 0.11.3 release you'll have access to `kbox composer` as a tool that ships with kalabox so you probably could easily install and use behat if you wanted. 

I'm not completely sure whether its something we would support out of the box although we're open to it if there is considerable demand. 

In the meantime i would suggest using something like travis for automated testing.

**Comment by ptmkenny** [comment]
Ok thanks.  I'll definitely try it out when 0.11.3 releases and contribute back some documentation if I get it working.

There may not be much demand now, but it could pick up considerably if [the behat tests get finished for D8 core](https://www.drupal.org/node/2232271)

**Comment by pirog** [comment]
@ptmkenny have you tried this out at all using the new `kbox composer` command?

**Comment by ptmkenny** [comment]
@pirog Actually I got stuck with a Pantheon/Behat interoperability problem:
https://github.com/drush-ops/drush/issues/1166

The fix/workaround is simple-- set date.timezone in cli php.ini-- but it hasn't been decided whether to do this in Drush itself yet.

**Comment by pirog** [comment]
@ptmkenny im going to close this. the approach here is going to be a "behat" plugin similar to our wraith one. we should be rolling that out in a few weeks with corresponding blog post

**Comment by leevh** [comment]
@ptmkenny did you ever get behat to work with the drupal driver on kbox?  @pirog Is the behat plugin still in the plan at all?  thanks!

**Comment by pirog** [comment]
@leevh def still planning to do this but its more medium term on our roadmap. would love for someone else to get there first. HEre is a good example of how to write a plugin https://github.com/kalabox/wraith

**Comment by leevh** [comment]
Hey @pirog, I've been fumbling through this trying to adapt the wraith plugin to behat.  Up against an issue I thought I'd ask about.  Behat requires database settings in the settings.php file, (a relevant post here mentions the issue hits Acquia DD as well https://www.drupal.org/node/2271009 ).  Is there any obvious way a plugin could output that info into the settings.php file?

**Comment by pirog** [comment]
@leevh super cool!

Can you give me an example of what you would want to add to settings.php? 

I'm also wondering whether it would work for a pantheon site if you injected `PRESSFLOW_SETTINGS` into the behat container like we do for terminus/drush.

**Comment by leevh** [comment]
@pirog sorry for the delay in getting back, what behat expects in the settings.php is just the vanilla D7 database connection array 

`$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'drupaldb',
  'username' => 'username',
  'password' => 'secret',
  'host' => 'localhost',
);`

If its not there, it will give you:

> [Drupal\Exception\BootstrapException]
  Missing database setting, verify the database configuration in settings.php.

based on what you said, I'm thinking maybe I can inject those settings like terminus, and then add them, run behat, and remove them from the settings.php all from my entrypoint script.  Just spit-balling at this point. :)

**Comment by pirog** [comment]
@leevh no worries. 

yeah i think you can def inject the `PRESSFLOW_SETTINGS` envvar to set up the DB connection. You could also just have a default `settings.php file` with the relevant connection info stored in `$_ENV` and just volume mount that directly into the correct location in the behat container.

**Comment by leevh** [comment]
@pirog, I've got a working version of this here: https://github.com/leevh/kalabox-plugin-behat , tests passing here: https://travis-ci.org/leevh/kalabox-plugin-behat

I'm still really unsure about the way I did various things, but mostly the custom code I put in the lib/events.js file.  I wanted to move some files around etc after install and it worked there so I left it.  I've also never coded in nodejs before, but that will be painfully obvious. 

Anyhow, I'm going to start using this in our gitlab CI scripts, but would love any suggestions, issues, patches etc from anyone.  Also if you want to rewrite, or move this code in the kalabox account, I'm open to whatever.  Thanks again for your guidance!

**Comment by pirog** [comment]
@leevh this is super cool! 

Do you have any interest in writing a short blog about how to use this that we could feature on our site?

**Comment by leevh** [comment]
@pirog for sure :)  Hopefully I'll have some time next week to write something, just let me know how I should supply it to you.  cheers

**Comment by pirog** [comment]
@leevh the easiest way to do so would be by submitting a PR over at https://github.com/thinktandem/tandem with a MD of your article. Doesn't need to be perfect as we can def do some editing and cleanup on our end.

Here are some good examples:
https://github.com/thinktandem/tandem/tree/master/src/content/articles

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
