### ISSUE TITLE
Drush unrecoverable error

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#1042]
On a very fresh install of a pantheon app on kbox-0.11.2 drush does not work at all:

```
kbox drush
info: COMPOSE =>  0=--project-name, 1=csi, 2=--file, 3=/Users/gremy/kalabox/apps/csi/kalabox-compose.yml, 4=--file, 5=/Users/gremy/kalabox/apps/csi/kalabox-cli.yml, 6=--file, 7=/Users/gremy/kalabox/apps/csi/kalabox-cli.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false
Drush command terminated abnormally due to an unrecoverable error.   [error]
```

**Comment by pirog** [comment]
"drush does not work at all" is a pretty big claim and im pretty sure its wrong.

**Comment by gremy** [comment]
I mean I cannot run any drush command

**Comment by pirog** [comment]
What im getting at is post a better and more concise issue along the lines of 
https://github.com/kalabox/kalabox/wiki/Circle-of-Trust-Testing-Guide#2-clear-replicable-issues-are-solid-gold

if i cant replicate an issue i cant really help you

**Comment by pirog** [comment]
It looks like this was just bad logic in settings.php
