### ISSUE TITLE
GUI needs to prompt for Pantheon re-authentication

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1044]
**Steps to reproduce:**

1. Authenticate with Pantheon (if you haven't already).
2. Go to Pantheon and change your password credentials.
3. Log back into Kalabox and attempt to see your sites for the Pantheon account which you changed the credentials on. Nothing should happen.

**Fix**
When this happens, we should remove the account from "Exisiting accounts" and display an error:

"Your Pantheon account is no longer authenticated. Please add it again."

**Comment by pirog** [comment]
@reynoldsalec something worth doing for alpha3? if so move it into that sprint.

**Comment by reynoldsalec** [comment]
Verified that this is still an issue.

On failure to produce sites from $scope.provider.refresh() in providerClick, I should catch the error, remove the Pantheon provider from $root.providers, and display the error message.

**Comment by reynoldsalec** [comment]
Pull request submitted.
