### ISSUE TITLE
set up api.kalabox.io

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1050]

**Comment by reynoldsalec** [comment]
Switched over all the kalabox.me domains to Cloudflare and pointed them all at the corresponding subdomains on kalabox.io.

Moved all the original DNS records we were using on kalabox.me to the kalabox.io site on Cloudflare.

Working on getting the routing for api/coverage working with the kalabox.io domain name (think that's on the server/application level, not dns)

**Comment by reynoldsalec** [comment]
Ok, changed up the nginx rules to redirect traffic from api.kalabox.me to the .io, same with coverage.

Should be gravy now.
