### ISSUE TITLE
GUI - Pantheon auth fails

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1062]
im assuming this is because the account i am trying has a shload of sites

![screen shot 2016-02-19 at 5 50 16 pm](https://cloud.githubusercontent.com/assets/713424/13193673/41753d8a-d731-11e5-9ca4-f39c7b4222c4.png)

**Comment by pirog** [comment]
So even more weird. When i exit out and return i now have this

![screen shot 2016-02-19 at 5 51 58 pm](https://cloud.githubusercontent.com/assets/713424/13193680/87dec020-d731-11e5-978b-d226dffd576b.png)

If i click on the pantheon account it loads up all the sites for the creds that seemingly failed. i also seem to not be able to add anymore creds.

**Comment by labboy0276** [comment]
Hello!

I have 114 sites on Pantheon and it took about 95 seconds for the site list to show up after I clicked my email.  Seemed like at first it didnt work, but then they magically appeared.

That is all.
