### ISSUE TITLE
GUI:  Install fails when pulling images

### ISSUE THREAD

**Issue by rvtraveller** [kalabox/kalabox#1068]
Environment:  Windows 10
Kalabox UI pulled from v0.11 branch; latest commit is 77a5b11
Kalabox (non-UI) was previously installed but removed using the Uninstall script
Virtualbox was uninstalled

Repro:
1.  Launch the Kalabox UI using `grunt build`
2.  When the GUI opens, click the button to start the installer
3.  Watch the installer until it gets to the point of "Pulling images"
4.  Observe error message.

Unfortunately, the error message prints in the smallest of small alert boxes on Windows which makes everything past the first 50 characters or so unreadable (with no way to scroll).

Additional details:

I troubleshot this issue and identified that running `docker-machine env Kalabox2` produced an error message about SSL certificate validation.  Additionally, visiting `https://10.13.37.100:2736` in my browser produced the error `ssl_error_bad_cert_alert` along with a more useful error message about the server not being able to verify my client certificate.

I ended up running `docker-machine regenerate-certs Kalabox2` which properly added a server.pem file to `.docker\machine\machines\Kalabox2` (along with other cert related files such as a key) and was successfully able to get past this step of the installer.

**Comment by pirog** [comment]
@rvtraveller glad you were able to find a workaround for this. 

Can you provide some additional details 

1. Any chance you were not able to uninstall completely and still had old certs lying around?
2. Similarly, were there old certs there generally and any reason they might be there?
3. Any chance you didnt have teh SSH util in your path? Can you tell us the path to Git Bash. #1064 
4. When you ran the regen command what shell did you use?

**Comment by rvtraveller** [comment]
1.  Boot2Docker was still installed and that's one of the things that initially tipped me off to the cert issue.
2.  There were no certs in the `.docker/machine/machines/Kalabox2` folder.  I manually copied over the Boot2Docker ones which didn't work but did aid in the debugging process.
3.  SSH is in the path as well as Git Bash.  When I get back to my other computer I'll pull the path to Git Bash.
4.  Windows command prompt (albeit, with a bunch of Unix utilities ported over for `ls` and the like).

**Comment by pirog** [comment]
@rvtraveller so we are rolling new native installers for KBOX in 0.12.x and they will be  explicitly running regenerate-certs after a start to make sure things are OK.
