### ISSUE TITLE
Consider moving site add modal into the sidebar

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1071]

**Comment by reynoldsalec** [comment]
I made this the default way of adding stock apps in #1075. This task should be to switch out the modals for this method on the Pantheon apps.

**Comment by reynoldsalec** [comment]
I'm running into the same issue here that I was seeing in #1140: when handling a Pantheon provider object in Angular, the fact that provider.sites includes site objects that have provider as children (beginning of infinite recursion) throws an error for a circular reference.

To avoid this, I had to remove sites from the provider:

```
delete provider.sites
```

I think that's probably introducing further issues, but need to verify.

**Comment by pirog** [comment]
I would def talk talk to Riley about this

On Thursday, April 7, 2016, Alec Reynolds <notifications@github.com> wrote:

> I'm running into the same issue here that I was seeing in #1140
> <https://github.com/kalabox/kalabox/issues/1140>: when handling a
> Pantheon provider object in Angular, the fact that provider.sites includes
> site objects that have provider as children (beginning of infinite
> recursion) throws an error for a circular reference.
>
> To avoid this, I had to remove sites from the provider:
>
> delete provider.sites
>
> I think that's probably introducing further issues, but need to verify.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1071#issuecomment-207021919>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc
