### ISSUE TITLE
Link to files directory missing

### ISSUE THREAD

**Issue by jpsalter** [kalabox/kalabox#1084]
A fresh install threw a git check out error. Running `git checkout -f HEAD` pulled the codebase.

But then... the files directory, although present, is not "connected" to Drupal - it cannot see files

Also, files pull was incomplete. Repeated `kbox pull` requests pulled more files but did not fix the the error. 

Repeated `kbox rebuild` and `kbox restart` also fail to clear the missing `files` directory.

**Comment by pirog** [comment]
@jpsalter can you provide some more information about the git error you got, what version you are using, what OS, etc?

**Comment by jpsalter** [comment]
OS 10.11.3 / kbox version 0.11.3

**Comment by jpsalter** [comment]
After running `git checkout -f HEAD` this message appeared:

016-03-02 13:01:38.961 xcodebuild[1061:72344] [MT] PluginLoading: Skipping plug-in at path '/Users/{user}/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ODPHPTools.xcplugin' because it is not compatible with this version of Xcode.
Your branch is up-to-date with 'origin/master'.

Could it be that this error started the problem?

**Comment by pirog** [comment]
its possible. we also recommend using `kbox git` instead of your local git since we can't really control much of how you have that set up.
