### ISSUE TITLE
A kalabox app cannot curl itself with `curl whatever.kbox`

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#1090]
Occasionally I see PHP errors like this on my kalabox site:

> Warning: file_get_contents(http://greenpawup.kbox/sites/default/files/js/wysiwyg/wysiwyg_tinymce_VxxRIlcaFmzHlghU8SsOGCZd5TC_PCxyhQAlqydMALE.js): failed to open stream: Connection refused in _locale_parse_js_file() (line 1488 of /code/includes/locale.inc).

I had assumed it was a programming error on my end, but now I'm thinking it may be an issue on kalabox.  When I log into the the terminal and I use a basic `curl` command to test the connection, I am able to connect to external sites, but when I try to connect to my hostname, it fails:

```
Davids-MacBook-Pro:greenpawup davids$ kbox terminal
Using php 5.5.24
rm: cannot remove `/root/.phpbrew/php/php-5.5.24/var/db/apc.ini': No such file or directory
root@greenpawup:/# curl -sSf http://www.google.com > /dev/null
root@greenpawup:/# curl -sSf http://greenpawup.kbox > /dev/null
curl: (7) couldn't connect to host
```
FYI, in case you're not familiar: That combination of `curl` flags, indicate that if it connects properly, output nothing, and if it fails, output an error. So in the example above, the google address returned no result, because it connected and the kalabox address returned an error because it couldn't connect.  Normally I'd leave the flags out, but to keep large chunks of HTML from distracting, I figured it best to include them. 

I would guess this is probably what is happening from the perspective of the nginx container as well, so that is why I am seeing the error above. 

I'm able to replicate the error by placing this inside a custom Drupal module called "mymodule" (basically tries to load a resource I definitely know exists directly via URL on the nginx server prior to processing the page):
```
function mymodule_preprocess_page(&$vars) {
  file_get_contents('http://greenpawup.kbox/sites/all/themes/greenpawup/logo.png');
}
```

This produces the following error:
```
Warning: file_get_contents(http://greenpawup.kbox/sites/all/themes/greenpawup/logo.png): failed to open stream: Connection refused in mymodule_preprocess_page() (line 4 of /code/sites/all/modules/mymodule/includes/page.inc).
```

Looking at my hosts files, I definitely see a definition for it: 

```
root@greenpawup:/# cat /etc/hosts | grep greenpawup.kbox
172.17.0.10	greenpawup.kbox greenpawup
```

Further more I am able to ping by hostname, so I don't believe the issue to be related to a host lookup failure: 
```
root@greenpawup:/etc# ping -w 3 greenpawup.kbox
PING greenpawup.kbox (172.17.0.10): 48 data bytes
56 bytes from 172.17.0.10: icmp_seq=0 ttl=64 time=0.044 ms
56 bytes from 172.17.0.10: icmp_seq=1 ttl=64 time=0.067 ms
56 bytes from 172.17.0.10: icmp_seq=2 ttl=64 time=0.065 ms
--- greenpawup.kbox ping statistics ---
4 packets transmitted, 3 packets received, 25% packet loss
round-trip min/avg/max/stddev = 0.044/0.059/0.067/0.000 ms
```

Alternatively if I ssh directly into the docker machine, I am able to connect to the host. 
```
Davids-MacBook-Pro:greenpawup davids$ ~/.kalabox/bin/docker-machine ssh Kalabox2
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.10.1, build master : a427f69 - Sat Feb 13 00:32:00 UTC 2016
Docker version 1.10.1, build 9e83765
docker@Kalabox2:~$ curl -sSf http://www.google.com > /dev/null
docker@Kalabox2:~$ curl -sSf http://greenpawup.kbox > /dev/null
```

I am running kalabox 0.11.3 on Mac OS X (El Capitan).  I will continue researching it, but want to see if you have any advice on how to correct this. 

Thank you

**Comment by pirog** [comment]
Funny you point this out because i was actually dealing with something similar when working on our generic drupal app. You might want to try something like this 

```yaml
appserver:
  ...
  hostname: $KALABOX_APP_CONFIG_NAME.$KALABOX_APP_CONFIG_DOMAIN
  ...
```

I think we have the hostname set incorrectly on pantheon apps. This issue also manifests in the drupal Status Report

**Comment by WidgetsBurritos** [comment]
Which file are you referring to?  kalabox.yml?

**Comment by pirog** [comment]
kalabox-compose.yml

you might need to do a `kbox rebuild` for the changes to propagate

**Comment by WidgetsBurritos** [comment]
Hmm tried it once and it didn't work.  Let me make sure I did it right.  Hold on.

**Comment by pirog** [comment]
i would def be interested to see if that works. i *think* it should but im not positive for pantheon. It works on the stock drupal app which hasnt been released yet but the code for which is over here
https://github.com/kalabox/kalabox-app-php

**Comment by WidgetsBurritos** [comment]
Yeah that didn't work.  I just commented out the old one and replaced it with the below information.  Is that what you meant?  
```
appserver:
  ...
  hostname: $KALABOX_APP_CONFIG_NAME.$KALABOX_APP_CONFIG_DOMAIN
  # hostname: $KALABOX_APP_HOSTNAME
  ports:
    - "8888"
    - "444"
  ...
```

**Comment by pirog** [comment]
hmmm yeah... 

so i actually think i know what the problem is now but what is the use case for running curl inside the container?

i think the issue is when you "terminal" into the appserver you aren't actually attaching to the appserver. instead you're spinning up an identical container to the appserver... which doesn't actually have a webserver running (since you are running bash on the container instead of nginx) which would explain the behavior you are getting.

**Comment by WidgetsBurritos** [comment]
Well I only terminal's into the appserver because I could replicate the error in there, so I figured it might be connected.   But really the issue seems to be whenever the appserver tries to call a file using the remote address.   That still doesn't work.

**Comment by pirog** [comment]
Got it. 

Are you getting a related error reported in your drupal Status Report?

**Comment by WidgetsBurritos** [comment]
I see this error in my status report:

```
HTTP request status	Fails
Your system or network configuration does not allow Drupal to access web pages, resulting in reduced functionality. This could be due to your webserver configuration or PHP settings, and should be resolved in order to download information about available updates, fetch aggregator feeds, sign in via OpenID, or use other network-dependent services. If you are certain that Drupal can access web pages but you are still seeing this message, you may add $conf['drupal_http_request_fails'] = FALSE; to the bottom of your settings.php file.
```

**Comment by pirog** [comment]
I think that is the same underlying issue as what you are seeing although for whatever reason the hostname setting works on the generic drupal app but not on pantheon.

**Comment by WidgetsBurritos** [comment]
hmm.  okay.  I'll play with a few things and see if I can figure it out.

**Comment by pirog** [comment]
Sounds good. We are still all hands working on getting the GUI up but as soon as we are good there i think i can look into this more.

**Comment by WidgetsBurritos** [comment]
No worries.  It's not a major error. More of a minor annoyance.  I just figured I'd point it out.

**Comment by WidgetsBurritos** [comment]
So I don't think the hostname is actually the issue. 

```
Davids-MacBook-Pro:greenpawup davids$ kbox env | grep KALABOX_APP_CONFIG_NAME
KALABOX_APP_CONFIG_NAME=greenpawup
Davids-MacBook-Pro:greenpawup davids$ kbox env | grep KALABOX_APP_CONFIG_DOMAIN
KALABOX_APP_CONFIG_DOMAIN=kbox
Davids-MacBook-Pro:greenpawup davids$ kbox env | grep KALABOX_APP_HOSTNAME
KALABOX_APP_HOSTNAME=greenpawup.kbox
```

All those variables seem correct.   And in my `kalabox-compose.yml` file, I explicity set the variable to the host name (no variables at all):

```
appserver:
  ...
  hostname: greenpawup.kbox
  # hostname: $KALABOX_APP_CONFIG_NAME.$KALABOX_APP_CONFIG_DOMAIN
  # hostname: $KALABOX_APP_HOSTNAME
  ports:
    - "8888"
    - "444"
  ...
```

This still doesn't seem to work. I'm wondering if there's a routing issue somewhere. Or maybe an internal firewall or something. I didn't see iptables or anything like that anywhere on there, but I don't know this linux distribution very well so I could just be looking in the wrong place.

**Comment by WidgetsBurritos** [comment]
Okay so that one WYSIWYG/TinyMCE bug may be unrelated.  I just go the same bug on pantheon, so that may be a slightly separate issue.   I'll research that further on my end. 

> Warning: file_get_contents(http://dev-greenpawup.pantheon.io/sites/default/files/js/wysiwyg/wysiwyg_tinymce_VxxRIlcaFmzHlghU8SsOGCZd5TC_PCxyhQAlqydMALE.js): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in _locale_parse_js_file() (line 1488 of /srv/bindings/c060cab382dd4bbca5feefa327cc7d8a/code/includes/locale.inc).

**Comment by WidgetsBurritos** [comment]
Well actually I take that back.  The kalabox issue gave me "failed to open stream: Connection refused in _locale_parse_js_file() " while pantheon gave me "401 Unauthorized in _locale_parse_js_file()".  

So there is definitely a distinction between Kalabox and Pantheon.

**Comment by pirog** [comment]
We DO try to emulate the pantheon environment so if its not working on Pantheon it shouldn't work on kalabox either. That said... different errors seems like a wtf

**Comment by WidgetsBurritos** [comment]
Yeah I think the error on pantheon is a permissions issue on my end.   The error on kalabox seems to be a connection issue.  I think the easiest way to test it is just by explicitly calling file_get_contents on an existing file using the full Drupal site url.

**Comment by pirog** [comment]
So i *think* this might be the same issue as https://github.com/kalabox/kalabox/issues/994 which we have a solution for and will be implementing in a week or so

**Comment by WidgetsBurritos** [comment]
Okay. Cool. Let me know if you need me to test anything.

**Comment by WidgetsBurritos** [comment]
So on the chance this isn't related to #994, I've done a little bit more research.  I went ahead and installed the full docker engine on my machine, instead of just the docker-machine and docker-compose binaries that come with Kalabox. From there I was able to get a shell directly in my container, and then I compared the results to what I get from my kalabox terminal. 

```
davids@me:[...kalabox/apps/greenpawup]$ eval $(docker-machine env Kalabox2)
davids@me:[...kalabox/apps/greenpawup]$ docker exec -i -t greenpawup_appserver_1 bash
root@greenpawup:/# grep '172.17' /etc/hosts 
172.17.0.6      db_1 17e679628d90 greenpawup_db_1
172.17.0.5      redis_1 d8aa97035357 greenpawup_redis_1
172.17.0.7      greenpawup_solr_1 510e0e5f8f5d
172.17.0.7      solr 510e0e5f8f5d greenpawup_solr_1
172.17.0.7      solr_1 510e0e5f8f5d greenpawup_solr_1
172.17.0.6      database 17e679628d90 greenpawup_db_1
172.17.0.6      greenpawup_db_1 17e679628d90
172.17.0.5      greenpawup_redis_1 d8aa97035357
172.17.0.5      redis d8aa97035357 greenpawup_redis_1
172.17.0.8      greenpawup.kbox greenpawup
```


Now compare that to what I get in my standard terminal:

```
davids@me:[...kalabox/apps/greenpawup]$ kbox terminal
root@greenpawup:/# grep '172.17' /etc/hosts
172.17.0.6	database 17e679628d90 greenpawup_db_1
172.17.0.5	greenpawup_redis_1 d8aa97035357
172.17.0.5	redis d8aa97035357 greenpawup_redis_1
172.17.0.6	db_1 17e679628d90 greenpawup_db_1
172.17.0.6	greenpawup_db_1 17e679628d90
172.17.0.8	appserver greenpawup greenpawup_appserver_1
172.17.0.8	appserver_1 greenpawup greenpawup_appserver_1
172.17.0.8	greenpawup_appserver_1 greenpawup
172.17.0.7	greenpawup_solr_1 510e0e5f8f5d
172.17.0.5	redis_1 d8aa97035357 greenpawup_redis_1
172.17.0.7	solr 510e0e5f8f5d greenpawup_solr_1
172.17.0.7	solr_1 510e0e5f8f5d greenpawup_solr_1
172.17.0.10	greenpawup.kbox greenpawup
```

What seemed notable to me, was the discrepancy in the IP address for `greenpawup.kbox`.  Those appear to be the IP addresses of those particular containers. So, sorta like a localhost reference there (although `curl http://greenpawup.kbox` doesn't work in either container.) 

What did seem to work for me though was temporarily changing the IP address of greenpawup.kbox to the public-facing address:

```
# 172.17.0.10	greenpawup.kbox greenpawup
10.13.37.100	greenpawup.kbox greenpawup
```

This is obviously not an optimal solution, so I reverted the hosts file back to what it was originally, but this got me thinking about the routes, and remembering that docker uses port mapping. 

So I examined the nginx configuration:

```
root@greenpawup:/etc/nginx/sites-enabled# head -n 3 /etc/nginx/sites-enabled/default 
server {
  listen 8888 default_server;
  listen 444 ssl;
```

So there I see that nginx is running on port 8888. So in my container I try this instead:

`curl http://greenpawup.kbox:8888` and voilà, it works!  So that is the problem. Port 80/443 are not available from the appserver container.  It wants port 8888/444.

So I added port 80/443 to the `config/nginx/drupal.conf` file: 
 
```
server {
  listen 8888 default_server;
  listen 80 default_server;
  listen 444 ssl;
  listen 443 ssl;
```

And then I rebuilt and restarted my kalabox instance, get a bash shell inside my container again and run `curl http://greenpawup.kbox/` and it works perfectly. 

I would imagine we would need to do the same thing in all the other config/nginx/*.conf files as well.

**Comment by pirog** [comment]
So i think getting the hostname to point to the proxy will help with the resolution issue. 

Getting a chance to look at this in greater detail... What is the reason for using something like `file_get_contents()` vs the drupal api version? Why URI vs path/schema?

**Comment by WidgetsBurritos** [comment]
Well the main reason I even noticed it was because of the wysiwyg module (not anything custom on my end): 

> file_get_contents(http://greenpawup.kbox/sites/default/files/js/wysiwyg/wysiwyg_tinymce_VxxRIlcaFmzHlghU8SsOGCZd5TC_PCxyhQAlqydMALE.js): failed to open stream: Connection refused in _locale_parse_js_file() (line 1488 of /code/includes/locale.inc).

So yes, I could potentially research that module and propose a fix, but I imagine this is not the only module to do something like this, especially when it seems like a solveable problem.

**Comment by pirog** [comment]
ah ha! i see. thanks for that example since that is a pretty compelling reason i think.

I'm going to move this into the alpha3 sprint to see if there is something better we can do on the kalabox side. 

In the meantime i think using your nginx workaround is the preferred resolution.

**Comment by pirog** [comment]
also thanks again for all your awesome feedback @WidgetsBurritos. its been such a pleasure to work the issues with you.

**Comment by WidgetsBurritos** [comment]
For testing purposes, assuming you have a D7 install with the devel module, you could do something like this in your theme's template.php file:

```
function THEME_preprocess_page(&$vars) {
  $url = url('<front>', array('absolute' => TRUE));
  $resp = drupal_http_request($url, $options = array(
    'method' => 'POST',
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
  ));
  dpm($resp);
}
```
Obviously, you'd have to replace THEME with your theme name and clear your cache.

**Comment by WidgetsBurritos** [comment]
You're welcome. I use Kalabox regularly as my dev environment and it's pretty damn awesome. So anything I can do to help make it better, I'm happy to do.

**Comment by WidgetsBurritos** [comment]
ack that originally code I gave you was wrong and might create an infinite loop.  Please hold while I fix. :-)

**Comment by WidgetsBurritos** [comment]
Okay I edited it above.  Make sure to include this portion inside your code: 
```
function THEME_preprocess_page(&$vars) {
  $query = drupal_get_query_parameters();
  if (isset($_GET['drupal_http_request'])) {
  ...
  }
}
```

and then just access it by adding `?drupal_http_request` to your url.

**Comment by WidgetsBurritos** [comment]
Sorry, don't mean to keep bombarding you with notifications (I'm done after this). Just in case you need some screenshots to compare the dpm output of the version that works (i.e. listeners added to nginx), vs the version that doesn't work: 

![screen shot 2016-03-23 at 4 42 06 pm](https://cloud.githubusercontent.com/assets/5263371/14001857/3f3824b6-f116-11e5-9397-2a52b59080ee.png)
![screen shot 2016-03-23 at 4 42 11 pm](https://cloud.githubusercontent.com/assets/5263371/14001856/3f37f93c-f116-11e5-9549-517aa66ba034.png)

**Comment by pirog** [comment]
My heart and soul are fortified to handle mass notification. I def
appreciate the clarity you provide.

**Comment by WidgetsBurritos** [comment]
:+1:
