### ISSUE TITLE
Insert site connection info into the GUI

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1091]
@pirog has commands in Kalabox CLI that display connection info for MySQL etc, we should expose those in the GUI.

**Comment by donkoller** [comment]
Hey, Alec,

Is the CLI 0.11 stable enough to use on a Windows 10 PC? We need for a server for a conference we will be at in about 8 weeks.
I have to install my own app, though as we don’t use Pantheon.

Is the GUI version available to me  to try out? You said after Sandcamp…..?

Regards,
Don



 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by reynoldsalec** [comment]
@pirog we touched on this last week, but I think we'll need a standardized way of accessing services for all app types to really make this work.

Once we have that, all the other groundwork is there for presenting the connection info.
