### ISSUE TITLE
Get kalabox-installer to build and deploy

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1099]
Use travis to build and deploy dev and production releases 

- [ ] Cross compile using our docker build process
- [ ] Dev releases pull down latest versions of kalabox-gui and kalabox-cli
- [ ] Prod versions pull down indicated tags
- [ ] Deploy dev to S3
- [ ] Deploy prod to github releases (with uninstall scripts)

**Comment by reynoldsalec** [comment]
@pirog I added README/LICENSE/TERMS to the installer project, so looking at a DMG that also packages those items should be here as well or on a new card.
