### ISSUE TITLE
git checkout on pantheon create fails if .stfolder is already in repository

### ISSUE THREAD

**Issue by jpsalter** [kalabox/kalabox#1102]
We get the following error and an incomplete install:
```
error: Untracked working tree file '.stfolder' would be overwritten by merge.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```
Removing `.stfolder` from our repository fixes the error.
Would it be possible to perform the checkout first and then add the .stfolder file if missing?

**Comment by pirog** [comment]
that is exactly what we do. see https://github.com/kalabox/kalabox/blob/v0.11/plugins/kalabox-cli/dockerfiles/cli/kgit

its probably best to just not commit that file to your repo

**Comment by jpsalter** [comment]
I agree. But, if you’re not paying attention the file can get committed. Then, the next kbox create will break.

**Comment by pirog** [comment]
@jpsalter thought about this some more and i think the best thing we can do without directly messing with the users code is to post some wiki/docs about it. 

We could also always ignore those files on git add and commits but i feel like that is an assumption we shouldnt make since the user might need these files in non-kalabox repos.

**Comment by imorale2** [comment]
Hi - I am having the same issue, I accidentally committed the .stfolder file and now even if I delete it for the repo is always reappears and I can't get any apps to work. I have uninstalled and installed kalabox and tried all different options. Is there any solution to this?

Thanks!

**Comment by pirog** [comment]
As indicated above, the solution is to not commit the file. If you have already committed it you might want to make sure you remove it from your repo before trying to pull down from kalabox again.

After that you are going to make sure you add these to your `.gitignore` file. 

```
# SYNCTHING #
#############
.stfolder
.stignore
```

Long term we are dropping syncthing as soon as the new native docker for max/windows are stable.

**Comment by pirog** [comment]
Closing in favor of #1295

**Comment by pirog** [comment]
This should no longer be an issue in our new releases since we are no longer using syncthing. You should still def remove these files from your repo though.
