### ISSUE TITLE
Prepackaged images for installers

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1115]
### Feature goals

1. Include an `images.tar.gz` with the installer so we don't need to pull initial images from the internet
2. Automatically import any images in `images.tar.gz` during install

**Comment by reynoldsalec** [comment]
@heddn we'll probably be taking a look at this for NYCamp.

**Comment by heddn** [comment]
Oh, that would be wonderful.

**Comment by pirog** [comment]
Don't think we will be able to do this before NoLa but would love to get this in for subsequent camps a la NYC camp.
