### ISSUE TITLE
Website deployment

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1117]
- Automate on push to master deployment to the website
- See if we can get this onto Docker Cloud

**Comment by reynoldsalec** [comment]
Website is now on Docker Cloud, but I need to have it dynamically build and update on push of new content.

Also curious on how I should handle the DNS settings; pointing a CNAME to the address given to the container (or to a load balancer) seems fragile, as those addresses change whenever the container is rebuilt. Didn't immediately see any docs on that.

**Comment by pirog** [comment]
Are you pointing to an IP? I think they have generic subdomains for
particular services that might remain consistent? If not it's possible the
underlying providers i.e. DO or AWS might have something more stable we can
use

On Thursday, March 24, 2016, Alec Reynolds <notifications@github.com> wrote:

> Website is now on Docker Cloud, but I need to have it dynamically build
> and update on push of new content.
>
> Also curious on how I should handle the DNS settings; pointing a CNAME to
> the address given to the container (or to a load balancer) seems fragile,
> as those addresses change whenever the container is rebuilt. Didn't
> immediately see any docs on that.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1117#issuecomment-200982407>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by reynoldsalec** [comment]
Right now I have an A record pointing to the IP @pirog for the bare domain and a CNAME for the www.

It looks like most people just point A records to the IP. I'm going to setup a haproxy container and modify the DNS records to get that going.

http://docker.grandvillericks.com/haproxy-docker-tutum/
