### ISSUE TITLE
GUI - Pulling Files only also pulls DB

### ISSUE THREAD

**Issue by jpmcneal** [kalabox/kalabox#1118]
To reproduce:

1. Create a node on your local environment, and make note of the nid
2. Click Actions,Pull
3. Select Database, No
4. Select Files, Yes
5. Click Submit
6. Visit the /node/[nid-from-step-1]

**Comment by pirog** [comment]
Does the node get wiped out?

**Comment by jpmcneal** [comment]
Yes.

**Comment by pirog** [comment]
@jpmcneal i can confirm that this does happen. 

I can also confirm that this only happens on the GUI. So im going to assign this to @reynoldsalec for now.

**Comment by pirog** [comment]
Ok. So the issue here is that the GUI is returning the string `"false"` instead of the boolean `false`.
