### ISSUE TITLE
Site Status Polling Doesn't Work

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1119]
@joshkoenig reports that, after starting a site, it shows no indications on the GUI of being spun up.

I'm guessing this is an issue with the siteStates factory or simply digest not being run to update the state on the GUI.

Working to see if I can replicate.

**Comment by reynoldsalec** [comment]
Confirmed this issue with another user. Stock spin-up.

**Comment by reynoldsalec** [comment]
Another thing to check out: it looks like when you hit start twice on an app, it doesn't work.

**Comment by reynoldsalec** [comment]
Ok, after looking at this some more I don't think it's a GUI issue.

I managed to replicate by doing a spin-up on a bare 10.11 virtual machine. After creating a site via the GUI (installed through the packager currently available in kalabox.tar.gz in AWS), the site state was shown as not running in both the GUI and the CLI (running "kbox list").

Took a snapshot of an app at that point that @pirog might look at next week. Going to dive a little deeper and see if I can see anything obvious.

**Comment by reynoldsalec** [comment]
On my local (where I could more actively debug), it does seem like there's some sort of fundamental issue getting the container list from kalabox-engine-docker, producing the "Error querying docker for list of containers.".

Wasn't able to confirm that on the virtual machine (Ted) however.

**Comment by pirog** [comment]
This seems to happens when you have a hyphen in your appname.
