### ISSUE TITLE
Fade the screenshot to white on the bottom

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1120]
Consider this to blend the screenshot.

**Comment by pirog** [comment]
@reynoldsalec alpha3 or icebox? only you can decide.

**Comment by reynoldsalec** [comment]
Checked this out; the following works:
```
-webkit-mask-image: -webkit-gradient(linear, left 95%, left bottom, from(rgba(0,0,0,.9)), to(rgba(0,0,0,0)));
```

But I'm not sure I like the effect that's produced on the screenshots I have:

![screen shot 2016-03-30 at 4 56 00 pm](https://cloud.githubusercontent.com/assets/1153738/14161417/6ab75b5c-f698-11e5-899a-0c5811140cdf.png)

![screen shot 2016-03-30 at 4 55 49 pm](https://cloud.githubusercontent.com/assets/1153738/14161420/6f515d34-f698-11e5-9497-ee5240bade48.png)

@pirog any opinions?
