### ISSUE TITLE
kbox update after Version 0.12.2 install

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1122]
install kalabox Version 0.12.2 (0.12.2) - works

pull down a site from pantheon - works

use terminal to navigate to apps "code" folder

run any kbox command and i am asked to run 'kbox update'

run 'kbox update' nothing happens and the kbox 'help' is displayed in terminal:

Usage: kbox <command> [-- <options>]
Change to an app directory for additional app specific commands. Run `kbox list` to get a list of your apps.

Global commands that can be run from anywhere
  config           Display the kbox configuration.
  create       
      drupal7      Creates a drupal7 app
      drupal8      Creates a drupal8 app
      pantheon     Creates a Pantheon app.
      wordpress    Creates a wordpress app
  env              Print Kalabox environmental vars.
  list             Display list of apps.
  version          Display the kbox version.

Options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]

**Comment by pirog** [comment]
yoyo,

so im guessing you have another `kbox` installed somewhere. can you do a `which kbox` in a terminal?

**Comment by break9** [comment]
looks like the one from the CLI
/usr/local/bin/kbox

**Comment by pirog** [comment]
yeah that looks right... except that version doesn't/shouldn't have a `kbox update` function. Can you do a `kbox version` on it?

**Comment by break9** [comment]
no

in fact i just wiped it all and reinstalled with no luck. same issue after successfull install

**Comment by pirog** [comment]
does `kbox version` give you an error or just nothing?

**Comment by break9** [comment]
nothing

**Comment by break9** [comment]
so i uninstalled again

first with the uninstall.sh

then the additional steps from your post https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox

this time it works as expected

**Comment by pirog** [comment]
huzzah! glad to hear it

**Comment by break9** [comment]
thanks doooooood : )

**Comment by break9** [comment]
btw looking good!!!!!!!

**Comment by pirog** [comment]
yeah we think its pretty good for the alpha1 release :)
