### ISSUE TITLE
drush pm-uninstall needs a higher bootstrap level to run

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1123]
Im trying to run the drush pmu command  and am getting this response.

Command pm-uninstall needs a higher bootstrap level to run - you will
need to invoke drush from a more functional Drupal environment to run
this command.

any suggestions?

**Comment by pirog** [comment]
what is the exact command you are using?

**Comment by break9** [comment]
$ kbox drush pmu context

Command pm-uninstall needs a higher bootstrap level to run - you will
need to invoke drush from a more functional Drupal environment to run this command.
The drush command 'pmu context' could not be executed.               
Could not find a Drupal settings.php file at sites/default/settings.php.

**Comment by pirog** [comment]
just copy over the default settings.php to settings.php. i dont think drush can run, at least pre drupal8, without one.

**Comment by break9** [comment]
nailed it. : )
