### ISSUE TITLE
Duplicate app name checking

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1124]
Currently we don't check if a user suggests an app name that already exists in the GUI, leaving us vulnerable to errors.

Dynamically handling this in the app create dialogue would be beneficial.

**Comment by pirog** [comment]
So i *think* the kbox libs throw an error for duplicate app name creation. might just need to get it to show up as a warning in the GUI? 

@reynoldsalec what are you thinking re: timing on this ticket? going to backlog for now.
