### ISSUE TITLE
400 Errors on SolR Sometimes

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1128]
OK

It is a little odd to reproduce, but usually this is how it goes:

I have an app in my kalabox, that i built a few days ago.  It has been started and stopped probably a few times.  I go in an notice SolR is kicking back a 400 error after a kbox start on an existing app.

If I do a kbox rebuild && kbox restart, it almost always fixes the error.  Sometimes I have to do an additional kbox restart.  It is almost like the SolR container gets "stuck".

**Comment by pirog** [comment]
Do you get a message with the 400?

**Comment by pirog** [comment]
I think #653 should fix this too
