### ISSUE TITLE
GUI push/pull does not work; kbox run from terminal asks for update

### ISSUE THREAD

**Issue by 17thColossus** [kalabox/kalabox#1131]
Push and pull issued from GUI remain stuck indefinitely. Trying to run any command from terminal (e.g.:  kbox drush) results in a request to issue the "kbox update" command, which appears to not be available anymore in v0.12.0-alpha2.
I had previous Kalabox CLI version installed, which I wiped using the uninstall.sh script.

**Comment by pirog** [comment]
I'm not sure how you installed or uninstalled but the latest version of
0.12.x does not have an update command. I would make sure you don't have
another version installed somewhere in your path that is interfering.

**Comment by 17thColossus** [comment]
I used the uninstall.sh script provided along with the 0.12.x package before installing the GUI, but apparently it left something in my system.
However, yesterday I ran both that script and the uninstall-darwin.sh script for 0.11.x versions and managed, after many attempts (that I later found to be related to the fact that the scripts did not manage to delete the Kalabox2 VM), to get Kalabox GUI up and running again.
