### ISSUE TITLE
GUI - Clicking "Start" doesn't always change the power button

### ISSUE THREAD

**Issue by jpmcneal** [kalabox/kalabox#1132]
For one of my apps (a D8 Pantheon site) clicking the power button works as intended: the app starts, the button turns green, and hovering over the button reveals the text "Stop."

For  a different app (a D7 Pantheon site) clicking the power button does not work as intended: the app starts; however, the button stays black and hovering over the button reveals the text "Start."

**Comment by reynoldsalec** [comment]
Thanks for opening this up @jpmcneal. This should be resolved by #1119 + #1127 

Perhaps you could confirm if the D7 app had a hyphen in its given name?

**Comment by jpmcneal** [comment]
Sure thing! As a matter of fact, the D7 app does does contain a hyphen.

**Comment by reynoldsalec** [comment]
Great, seeing as it does have a hyphen I think this confirms this as a duplicate, so look out for that new release!
