### ISSUE TITLE
connection mode SFTP instead of GIT

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1133]
if the pantheon connection mode is set to SFTP and you pull down a site with kalabox-gui, only a non-descript container error is thrown when it tries to spin up. it took me a minute to figure out what was happening.

**Comment by pirog** [comment]
Hmmm. Should be able to git clone regardless of the connection mode.

Any additional details?

On Tuesday, March 15, 2016, break9 <notifications@github.com> wrote:

> if the pantheon connection mode is set to SFTP and you pull down a site
> with kalabox-gui, only a non-descript container error is thrown when it
> tries to spin up. it took me a minute to figure out what was happening.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1133>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by break9** [comment]
yeah, i thought the same so i: 

deleted the Kalabox app
changed the connection mode back to SFTP
tried again and failed

i repeated the test after restarting kalabox, each time i completely removed the app and installed new.

nothing worked until i switched the connection mode back to GIT

the app name was break9 not sure if that matters

**Comment by break9** [comment]
the weird part is..... The app i was working on last week was set to SFTP and everything worked fine? not sure if some config has changed i the last few days

**Comment by reynoldsalec** [comment]
I didn't experience this when testing on the latest development build, so either this is resolved or there is an app specific issue going on.

@break9 would it be possible for you to share the app in question to my Pantheon account (both my Kalabox email or my Kalamuna email work)?

**Comment by break9** [comment]
Done.

shared with your kalamuna acct.

it's a vanilla panopoly install.

**Comment by break9** [comment]
I will delete from kbox and try again then report back

**Comment by break9** [comment]
worked : )
