### ISSUE TITLE
0.12.x - kbox git commit with spaces fails

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1137]
As the title says, in my commit message I use spaces like normal = failed:

```
john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m "Fix up doc blocks"
error: pathspec 'up' did not match any file(s) known to git.
error: pathspec 'doc' did not match any file(s) known to git.
error: pathspec 'blocks' did not match any file(s) known to git.
john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m "Fix-up-doc-blocks"
[products 080c8a0] Fix-up-doc-blocks
 2 files changed, 19 insertions(+), 9 deletions(-)
```

Is it similar to this:
https://github.com/kalabox/kalabox/issues/896

**Comment by pirog** [comment]
Try doing it with single quotes for now

On Wednesday, March 16, 2016, John Ouellet <notifications@github.com> wrote:

> As the title says, in my commit message I use spaces like normal = failed:
>
> john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m "Fix up doc blocks"
> error: pathspec 'up' did not match any file(s) known to git.
> error: pathspec 'doc' did not match any file(s) known to git.
> error: pathspec 'blocks' did not match any file(s) known to git.
> john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m "Fix-up-doc-blocks"
> [products 080c8a0] Fix-up-doc-blocks
>  2 files changed, 19 insertions(+), 9 deletions(-)
>
> Is it similar to this:
> #896 <https://github.com/kalabox/kalabox/issues/896>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1137>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by labboy0276** [comment]
same thing:

```
john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git add -A
john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m 'Fix up doc blocks'
error: pathspec 'up' did not match any file(s) known to git.
error: pathspec 'doc' did not match any file(s) known to git.
error: pathspec 'blocks' did not match any file(s) known to git.
john@kalamuna:~/kalabox/apps/csi-america/code$ kbox git commit -m 'Fix-up-doc-blocks'
[products 554edf8] Fix-up-doc-blocks
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by reynoldsalec** [comment]
Same error occurs on Mac.

**Comment by reynoldsalec** [comment]
Still seeing this issue on my machine. I'll make sure I can replicate it both with my dev build (directly from the project code) and from the packaged version, but might be worth looking at tomorrow in person @pirog.
