### ISSUE TITLE
CLI-created apps lack screenshots

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1138]
We should at the least give them a default screenshot.

**Comment by pirog** [comment]
I think we probably want to do this for the alpha2 release. Seems like the easiest thing for now would be to drop a screenshot into the default app skeleton over at https://github.com/kalabox/kalabox-app-php/tree/v0.12/app

@reynoldsalec unless i am missing something here and this is harder than i think i am going to add this to the current sprint. If you think its better for next sprint then just reassign.
