### ISSUE TITLE
Can GUI 'pull' have same options as in the CLI?

### ISSUE THREAD

**Issue by miller2676** [kalabox/kalabox#1140]
When using the CLI we have the option of pulling the database and files from the environment of our choice, but when using the GUI the choice is not available. I assume it is then pulling from dev. Was this by design? Or can we have the same options we get in the CLI?

**Comment by pirog** [comment]
I def think this is a feature we can add pretty easily. 

Not by design, just wanted to get a GUI out to people fast so its lighter on the feature set. 

Are their other areas in the GUI that could be benefited by similar-in-cli options? @miller2676

**Comment by miller2676** [comment]
@pirog — I haven't thought of anything else yet, but i'll make a request if I do. Thanks.
