### ISSUE TITLE
Hyper-V enabled and/or VT-x not installed results in silent install forever, GUI "loading" screen seems to hang 4eva

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1141]
linux and osx are nice and snappy

**Comment by halofx** [comment]
What is considered forever? I have been giving up after 20 minutes of staring at the loading screen.

**Comment by pirog** [comment]
This is just to get the actual GUI to launch which seems to happen somewhere in the 5 to 30 seconds range. If you have the loading screen and your VM is off that should take only a few minutes. If it takes longer than that you probably have another issue. 

What windows are you on?

**Comment by halofx** [comment]
Win 8.1 Pro. I do have Hyper-V also installed. I have tried it with Hyper-V running, and with the service shut completely off.

**Comment by pirog** [comment]
How did you install kalabox? If you open up virtualbox do you see the Kalabox2 VM in there?

**Comment by halofx** [comment]
I downloaded the .12 alpha from the link in my email, and installed from the desktop. The install went fine, I took all the defaults, which was everything.

There are no VMs in Virtualbox.

When I launch Kalabox one background process starts immediately in Task Manager, but the GUI Loading Screen doesn't show up for another 20 seconds. When the Loading Screen does show, an App process starts, the first background processes goes idle, and 2 more background processes fire up. The app process bounces between idle and a 2-3% cpu, the 2 new processes bounce around 5% for a couple minutes and then cycle between idle and 3-4% cpu usage.

The processes start out using about 8MB for the App, and the Background processes start about 12MB, 55MB & 12MB. After a couple minutes they trickle down to 4.7MB for the app, and 4.0MB, 29.3MB & 9.9MB for the background processes, and don't change.

**Comment by pirog** [comment]
If you don't have a VM in VirtualBox then that explains what you are seeing. There should be relevant logs in your users temp directory. I think they have something like `Setup` in the filenames.

```
cd %TEMP%
```

One obvious thing is whether you have VT-x enabled or not. 
https://kalabox.freshdesk.com/solution/articles/14000006306-installing-on-windows

If you do i would definitely scope the setup logs and see if you can find any relevant errors.

**Comment by pirog** [comment]
@halofx was nice enough to walk me through this and here are general steps to replicate although i'm not 100% sure hyper-v is a relevant factor or not

1. Enable Hyper-V (and/or turn VT-x off in the BIOS)
2. Install Kalabox 
3. Open up VirtualBox (you should **not** see a Kalabox2 VM)
4. Download and run the (engine script)[https://raw.githubusercontent.com/kalabox/kalabox/v0.12/windows/engine.bat] manually.
5. This may fail complaining about hyper-v being installed. 
6. If it does then edit engine.bat above to replace the docker-machine line with this 

  ```
:: If the Kalabox2 VM does not exist then create it
:: @todo: handle errors?
"%VBOXMANAGE%" list vms | findstr "%VM%"
IF %ERRORLEVEL% NEQ 0 (

  "%DOCKER_MACHINE%" create -d virtualbox ^
    --virtualbox-memory 2048 ^
    --virtualbox-disk-size "%VB_DISK%" ^
    --virtualbox-hostonly-cidr 10.13.37.1/24 ^
    --virtualbox-host-dns-resolver ^
    --virtualbox-dns-proxy ^
    --virtualbox-no-vtx-check ^
    --engine-opt dns=172.17.0.1 ^
    --engine-opt dns=208.67.222.222 ^
    "%VM%"

)
  ```

**Comment by halofx** [comment]
It looks like a possible cause could be a naming convention issue. At some point Intel switched from calling its virtualization technology from "Intel VT" to "VT-X". Perhaps Virtualbox is looking for VT-x specifically, and not acknowledging the older naming convention?

https://www.thomas-krenn.com/en/wiki/Overview_of_the_Intel_VT_Virtualization_Features

**Comment by pirog** [comment]
We've added some better docs over at http://docs.kalabox.io. We have **some** documentation around this issue but we should probably edit the docs to link here as well.

**Comment by jon-nunan** [comment]
RE: the install forever part.  I have some Unix command equivalents installed in my PATH.  One of these is a command called 'Yes' (https://en.wikipedia.org/wiki/Yes_(Unix)).  When running engine.bat I must have hit one of the ` || Yes ` conditionals and set that off.  No ones fault but my own, but thought I'd mention it in case someone else hits it.  (You can just rename the `Yes` command to something else for the install to fix)

**Comment by pirog** [comment]
@jon-nunan this issue is specifically about VT-x, do you mind opening a separate ticket with your above comment?
