### ISSUE TITLE
xdebug on linux

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1143]

**Comment by labboy0276** [comment]
Workaround in the interim is this:

1. look at your phpinfo and grab the up address from HTTP_X_REAL_IP (should be 10.13.37.100).
2. in your kalabox-compose.yml have the appserver build locally.
3. in your APPROOT/dockerfiles/pantheon-appserver/bashrc change the ip address on about line 50 for xdebug.remote_host = to the ip address in 1
4. kbox rebuild && kbox start

you have xdebug again now, woot
