### ISSUE TITLE
Error: image kalabox/pantheon-redis not found

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1144]
Hello!

0.11.3 Here, seems the pantheon-redis image is gone from docker? 

```
Pulling redis (kalabox/pantheon-redis:v0.11.3)...
ERROR: Error: image kalabox/pantheon-redis not found
code1err:more:Pulling repository docker.io/kalabox/pantheon-redis

VError: code1err:more:Pulling repository docker.io/kalabox/pantheon-redis
```

**Comment by labboy0276** [comment]
Also note, this is only happening on kbox rebuild.  Site worked fine on create.

**Comment by pirog** [comment]
It's recommended you update to 0.12

On Friday, March 18, 2016, John Ouellet <notifications@github.com> wrote:

> Also note, this is only happening on kbox rebuild. Site worked fine on
> create.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1144#issuecomment-198380096>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by labboy0276** [comment]
and so it shall be
