### ISSUE TITLE
Creating site fails on 0.12.0-alpha.7

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#1146]
`Failed after 5 retries. {"max":5,"backoff":500}: VError: code: 1err:Pulling redis (kalabox/pantheon-redis:v0.11.3)...
Pulling repository docker.io/kalabox/pantheon-redis
Error: image kalabox/pantheon-redis not found`

**Comment by pirog** [comment]
you arent going to be able to use 0.11.x apps on 0.12.x. how are you installing 0.12.x? we havent released installer pkgs yet.

**Comment by jdleonard** [comment]
I received an email with a keycode to download the installer

**Comment by jdleonard** [comment]
To clarify, the site appears in the GUI after receiving the error, but the error is seen again when running "kbox pull" via the GUI or CLI.

**Comment by pirog** [comment]
we should be releasing an updated installer sometime early next week.
