### ISSUE TITLE
Ability to cancel site install 

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#1151]
I set up a new site, and It's ready to go, but pulling down files takes fore-eeeever... and maybe what I need to do doesn't rely so much on "all the files" ... it would be great to have a cancel button.

**Comment by madeofpeople** [comment]
Or "ok stop pulling files" button.

**Comment by pirog** [comment]
I think there is already another ticket for this?

**Comment by pirog** [comment]
@madeofpeople i think #1154 is close enough to this and id like to consolidate feedback. i would def go over there and post your *deepest desires.*

**Comment by madeofpeople** [comment]
So i don’t see 1154 as covering the same ground.

I dont want more options, I jsut want to be like “ok give me back control of the GUI because i dont want all the files”

As far as I know the way this is implemented in the CLI is via ctrl+c 

But do what you think is best.

**Comment by pirog** [comment]
I mean you can close the GUI at anytime if you want something like Ctrl-c

**Comment by labboy0276** [comment]
I usually do ctrl+c on sites with uber sadness levels of files.  Then start the app and rsync the rest of the files later, etc

**Comment by madeofpeople** [comment]
OK let me offer a better use case. 


I'm on three new projects.

I go to my gui and I add one.
Oh no its got a uuuuge amount of files. 

But I dont want to wait, I want to add site #2 or go and start another app up so I can work on that while I wait.

So it would be inconvenient to close the GUI.

But it would be cool to either have all that synching not take over the whole app, or be able to say "OK you've done enough, I'd like to go back to my sites list"

Is it prohibitive to have the synching happen in the BG while the GUI is active? I could see that being so.etching that doesn't get sorted for a long while, just thought I'd log it as a potential enhancement.


On March 23, 2016 10:04:48 PM EDT, Mike Pirog <notifications@github.com> wrote:
>I mean you can close the GUI at anytime if you want something like
>Ctrl-c
>
>On Wednesday, March 23, 2016, Thiago de Mello Bueno <
>notifications@github.com> wrote:
>
>> So i don’t see 1154 as covering the same ground.
>>
>> I dont want more options, I jsut want to be like “ok give me back
>control
>> of the GUI because i dont want all the files”
>>
>> As far as I know the way this is implemented in the CLI is via ctrl+c
>>
>> But do what you think is best.
>>
>>
>> > On Mar 23, 2016, at 5:31 PM, Mike Pirog <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>> >
>> > @madeofpeople <https://github.com/madeofpeople> i think #1154 <
>> https://github.com/kalabox/kalabox/issues/1154> is close enough to
>this
>> and id like to consolidate feedback. i would def go over there and
>post
>> your deepest desires.
>> >
>> > —
>> > You are receiving this because you were mentioned.
>> > Reply to this email directly or view it on GitHub <
>>
>https://github.com/kalabox/kalabox/issues/1151#issuecomment-200551885>
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/kalabox/kalabox/issues/1151#issuecomment-200613102>
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/kalabox/kalabox/issues/1151#issuecomment-200614400

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pirog** [comment]
Right now we have to "single thread" app actions on the GUI for technical
reasons. As soon as we switch this over so we can "multi-thread" on the GUI
you won't ever lose access to the GUI. See #1150

For now, If you want to run multiple app actions at once we recommend you
use the CLI. Also for now, if you don't want to wait for the files i would
just kill the process on the CLI when its pulling files  and then restart
the app. You can then do a `kbox pull` in another process to rsync files in
the background.

**Comment by madeofpeople** [comment]
Thumbsup!
