### ISSUE TITLE
Give `kbox create pantheon` more options a la `kbox pull`

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#1154]
Per the discussion here- kalabox/kalabox#1011: 

`kbox pull` currently offers the option of downloading the latest DB instead of the most recent backup:

> Retrieve latest DB instead of most recent backup? (y/N) (y/N)

This same feature does not appear in `kbox create pantheon`, which may confuse new users using Kalabox for the first time, or worse, could potentially overwrite something in their database if they run `kbox push` at a later time.

**Comment by pirog** [comment]
I def think it would be good to add this and other `kbox pull` options to `kbox create`. 

I'd prefer to not add a bunch of extra questions to the create process. Would you be OK with some sort  `--createnew-db` flag or do you think its very important for this to be an interactive option in the GUI and CLI? 

Here are some other options create options that might be helpful 

1. Choose to not pull files
2. Choose to not pull database?

Anything else that might be useful to config on a create you can think of?

**Comment by WidgetsBurritos** [comment]
Well what I will say is that to me it's a bit counter-intuitive that it pulls directly from a backup rather than the active db, although I definitely understand the reasoning for it. 

I'd imagine as new users start using kalabox, there will probably be people not reading directions, and will gloss over the whole "downloads from backup instead of active db", which is why I think it would be important to sorta idiot-proof it (and I use the term *idiot* with loving affection). Otherwise, you may get a lot of people with support requests saying "This isn't working!", or people that might just give up on using Kalabox because it appears unreliable to them.

Alternatively, if you don't want to bog down the create process with a bunch of questions, what would your thoughts about changing the default from downloading from backup to downloading from active, and then providing a flag that could be added to indicate to download from backup. 

I'd imagine that yes, you probably have a bunch of people already used to doing it without, but it seems easier to teach the people who need it from a backup, than it would be to fix data-loss because someone downloaded from a backup and then ran `kbox push`. 

That's just my opinion, so take from it whatever you will.

**Comment by WidgetsBurritos** [comment]
As far as the other two options, --no-files and --no-database flags would probably be sufficient in my mind.  Once again, those seem like special cases, not default behavior, so if they need it, give them a flag.

**Comment by pirog** [comment]
I definitely think figuring out the default action for the DB is tricky. There are a lot of tradeoffs to different user segments depending on what you do. Here are some of the obvious ones

1. **Directly importing from the pantheon database** - this is just INCREDIBLY slow and might be a non-starter for people with larger database although you WILL get the most up to date content
2. **Creating a new backup and then pulling that down** - Even creating a new backup this is probably faster then 1 but would similarly be really slow for larger databases although you would get the most up to date content. 
3. **Pulling the latest backup (current default)** - Anyone who doesnt do regular backups or pushes their DB directly (which is obviously not ideal development practice) is going to probably be confused. 

Out of the above i dont think there is really a best "default" action that works for most people here. Number 2 is probably the best but i doubt pantheon wants kalabox to be creation a shload of backups on their platform. You could mix and match solutions by checking for backup sizes and how recent backups are but i think that would ultimately be more confusing.

**Comment by WidgetsBurritos** [comment]
With that being the case then, it's probably best to prompt.  I know adding the extra steps in the initial create may be less than ideal, but most people only have to do it once for a project, so I don't think they would get too hung up on it. 

Also, it might be worth placing a warning on `kbox push`, and encourage them to use `kbox git` instead to commit and push their changes.

**Comment by pirog** [comment]
Yeah i think im with you. Do the best to inform the user and let them make the choice that is best for them.

**Comment by WidgetsBurritos** [comment]
Perhaps also, upon create it could create a *default* setting for their application. So whenever they run `kbox pull` in the future it would auto-apply their default setting, unless they use flags to indicate otherwise.

**Comment by pirog** [comment]
i think UX wise that would be ok but i also dont want to our users to be creating tons and tons of backups on pantheon.

**Comment by pirog** [comment]
I think what i am going to do here is benchmark a few uses cases so we can at least verify some of our assumptions about the ways we can get the DB.

**Comment by WidgetsBurritos** [comment]
Good point.  That's probably a good strategy.

**Comment by pirog** [comment]
I'm going to investigate whether we can just pull directly from dev without a backup. There must be some ways to speed that up.

**Comment by WidgetsBurritos** [comment]
I've never actually used it before, so I don't know if it would actually work in this use case, but maybe via `mysqldiff`? 

https://dev.mysql.com/doc/mysql-utilities/1.5/en/mysqldiff.html

**Comment by pirog** [comment]
So the "most recent database" part of this should be resolved by https://github.com/kalabox/kalabox-app-pantheon/pull/120

We are going to pull the DB directly vs getting a backup so it should be the most up to date

**Comment by WidgetsBurritos** [comment]
Okay cool. Are you still going to have an option to pull from a backup though?

**Comment by pirog** [comment]
wasn't planning on it, for the DB anyway. if you are looking to roll with
other DBs i think multidev probably makes the most sense to get things
siloed. of course you can also import backups yourself.

**Comment by WidgetsBurritos** [comment]
I wasn't. Was asking mainly out of curiosity. 

Did you find a way to speed the process up? Just kinda glanced over the diff's and see it's drush-based now. Does that affect WordPress support at all?

Once again, just questions out of curiosity. So feel free to ignore them if you're busy. :-)

**Comment by pirog** [comment]
It shouldn't. 

I was initially thinking of using `mysqldump` as the lowest common denominator but looking at how `drush sql-dump` works, esp in combination with pantheon aliases that seemed ideal. `sql-dump` is more or less just a wrapper to set up an ssh-tunnel and then do `mysqldump`. it doesn't require your site be bootstrapped at all so your site can be completely borked and it should still work. The performance of doing the tunnel and then piping to stdout vs just doing a straight remote mysqldump is like 7 seconds vs 70 seconds for a fresh D7 db.

**Comment by pirog** [comment]
Still going to add `no-db` and `no-files` options though!

**Comment by WidgetsBurritos** [comment]
Oh wow! That's a major improvement, and also good to know whenever I need to do SQL dumps for any other reason.

**Comment by WidgetsBurritos** [comment]
Just another thought, and perhaps I should open a separate feature request for this, but figured since this was still open I'd ask here.  

Since you're using `drush sql-dump` for the pull now, it would be nice to have a `--skip-common` option, that would allow us to skip common tables (such as cache, sessions, history, and watchdog), by running `drush sql-dump --structure-tables-key=common` instead.   

I don't necessarily need all those when I pull down a copy of my database, and could help expedite the dump even further.

If you need more info about the process see these links: 
- [example.drushrc.php](http://www.drupalcontrib.org/api/drupal/contributions!drush!examples!example.drushrc.php/7)
- [Faster Database Backups via Drush](http://www.metaltoad.com/blog/faster-database-backups-drush-plus-capistrano-integration)

**Comment by pirog** [comment]
I would open another ticket. I agree that we don't need to and shouldn't
pull all the tables.

**Comment by WidgetsBurritos** [comment]
Alright. Done.

**Comment by pirog** [comment]
Awesome! Thanks!

**Comment by pirog** [comment]
So here are the new options we would add to `kbox create pantheon`

```
PIROBOOK2:apps pirog$ kbox.dev create pantheon -- -h
Options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
  --email        Pantheon dashboard email.                              [string]
  --password     Pantheon dashboard password.                           [string]
  --site         Pantheon site machine name.                            [string]
  --env          Pantheon site environment.                             [string]
  --name         The name of your app.                                  [string]
  --no-files     Skip pulling my files directory.                      [boolean]
  --no-db        Skip pulling my database.                             [boolean]
  --dir          Creates the app in this directory. Defaults to CWD.    [string]
  --from         Local path to override app skeleton (be careful with this)
                                                                        [string]
```

**Comment by WidgetsBurritos** [comment]
I think this looks good.

**Comment by pirog** [comment]
And related issue to get this into the gui #1197

**Comment by rtblair** [comment]
Did these flags get added?
