### ISSUE TITLE
Linux 0.12.x kbox rebuild process hangs on cleaning up when doing a local build

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1155]
Hello!

As the title states, the cleaning up process hangs for a long time sometimes.  Here is how to try and replicate:

- I pulled down a client site.
- changed the redis.conf so this works on alpha1
- added the github version of the appserver files
- changed the bashrc to point the ip address for xdebug
- and changed the compose file to build local

Then did a kbox rebuild.  I sat there for almost 30 minutes to no avail.  I did this:

```
export DOCKER_HOST=tcp://10.13.37.100:2375
/usr/share/kalabox/bin/docker ps --all
```

I then saw these failed build containers:
```
21b616ba4806        ae2d23f18b95                                 "/bin/sh -c 'cd /tmp "   4 days ago          Exited (2) 4 days ago                                                                                              nostalgic_heisenberg
4f563d5611f5        86413bd31c05                                 "/bin/sh -c 'cd /tmp "   4 days ago          Exited (2) 4 days ago                                                                                              insane_jepsen
6f1324186feb        86413bd31c05                                 "/bin/sh -c 'cd /tmp "   4 days ago          Exited (2) 4 days ago   
```

I removed them and did a kbox rebuild and it worked....

**Comment by pirog** [comment]
Hmmm yeah this definitely seems like a bug to me. Let me try to replicate. Going to add into v0.12.0-alpha3 for now.

**Comment by pirog** [comment]
@labboy0276 are you just getting this on rebuild or do other commands seem to fail as well?

**Comment by labboy0276** [comment]
@pirog it seemed to happen just on rebuild

**Comment by pirog** [comment]
@labboy0276 did you just get it for that one app or did it block other apps?

**Comment by labboy0276** [comment]
@pirog just the one csi app

**Comment by pirog** [comment]
k awesome, thanks
