### ISSUE TITLE
Where is latest kbox version?

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1156]
Hi guys, my kbox 0.11.3 is still working but I see there is a new version announced, also the UI seems to be nearly ready?  I do not have an access key where do I obtain one?  Also you removed the links to the installer files in the readme :O is there a different way to upgrade now?

**Comment by pirog** [comment]
hey @macronomicus we are doing a closed round of alpha testing right now before we release more generally in the github. but if you go to kalabox.io you should be able to sign up an access code. 

we are doing a targeted/random release to a subset on monday and then probably to the whole list the week after, followed by a public release the week after. unless, of course we discover some big flaws on the way :)

**Comment by macronomicus** [comment]
oh ok awesome! Ill go sign up asap, meanwhile 0.11.3 still works for my few pantheon sites until the time comes to upgrade.  Cheers and congrats on the progress!

**Comment by pirog** [comment]
thanks so much! we are very excited to finally get this thing out!
