### ISSUE TITLE
Improve docker event stream wrapper

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1160]
Right now we track the `docker event` status of the appserver for GUI state changes. 

It would be better if state changes were not coupled to a specific (and potentially non-existent) service but rather if we started cleverly named containers at the correct times ie `appname_started_1` that would then immediately destroy themselves.

It would be easy to create a GUI plugin in core that could spin up these junk containers using our events system and then alter the GUI to listen for them.

**Comment by reynoldsalec** [comment]
Once app is started up, a token container is created and once it is stopped it is stopped as the last container. It will be destroyed along with the other containers.

The container runs the whole time right now.

Protractor tests are the last outstanding task.
