### ISSUE TITLE
pulling site in alpha8 doesn't pull latest version

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1161]
I uninstalled kalabox to install the latest alpha8.

When i pulled down a site it pulls the very first commit in pantheon  and not the current state of the site.

**Comment by pirog** [comment]
what do you mean by "very first commit"? the earliest commit or the one that shows up at the top of the pantehon dashboard? or something else?

**Comment by break9** [comment]
sorry,

when i pulled the site and i view the local version it is the completely vanilla install. it is pulling the very first commit made on pantheon by pantheon.

**Comment by pirog** [comment]
is this a multidev or normal dev branch?

**Comment by break9** [comment]
normal brach --dev

**Comment by pirog** [comment]
are you pulling a site that you had already created before you upgraded?

**Comment by break9** [comment]
yes but i completely deleted all before installing the new kbox

**Comment by pirog** [comment]
its possible that the old app persisted although i think the uninstall in the dmg should wipe everything. 

what you are describing is definitely very peculiar though since we just do a normal `git clone` and then `git checkout master` for the dev branch. have you tried doing a `git status` or `git pull` or `git log` on your codebase to see what it does?

**Comment by break9** [comment]
i deleted the site, threw it away, and am re-installing via kbox. i will try that once it is downloaded.

**Comment by pirog** [comment]
sounds good.

**Comment by break9** [comment]
git status - code is up to date.
appears to be a DB issue?

**Comment by pirog** [comment]
so its going to pull from the latest backup you have not what is currently in the DB although you should get an option to create a new backup and use that on `kbox pull` although not on `kbox create`

coincidently we are actually discussing this over at #1154

**Comment by break9** [comment]
that makes sense!!!! thanks
