### ISSUE TITLE
Where are the PHP and solr error logs?

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1169]
I'm trying to find my site's PHP error log and I can't locate it.  According to phpinfo(), error_log is set to /src/logs/php-error.log, but when I use **kbox terminal** to ssh into my machine there is no logs directory in /src, even though I've had quite a few PHP errors.

Also, is there any way to get access to the Solr logs?

kbox 0.12.0-alpha.18 on OS X

**Comment by pirog** [comment]
I think these are both two very valid points. I think i'm going to create tickets for both of them but for a little more detail here

1. We should probably share our logs back out so they accessible without having to go into the container
2. `kbox terminal` actually will drop you into another container that is the same as the appserver running your site, however, it is not actually the same as the appserver itself ... which does make it somewhat pointless in a lot of ways. We should get this so it drops you straight into the appserver.

**Comment by pirog** [comment]
See:

* Expose logs #1175
* `kbox terminal` shell into actual appserver #1174

**Comment by yumyo** [comment]
So to recap, how to look at php, mysql and other error logs?

**Comment by pirog** [comment]
best bet is to exec directly into your container and read the relevant logs there. future releases will get log s exposed to the outside and we will have better docs around this.

**Comment by yumyo** [comment]
thank you @pirog but I got no Docker knowledge and so, no idea how to 

> exec directly into your container

**Comment by pirog** [comment]
@yumyo i posted help for you in another issue
https://github.com/kalabox/kalabox/issues/185#issuecomment-226854542

**Comment by yumyo** [comment]
great, thank you @pirog

**Comment by reynoldsalec** [comment]
Another solution for this: create a "logs" folder in the your Kalabox app's root directory:

cd ~/.kalabox/apps/myapp
mkdir logs
kbox restart (if already running)

**Comment by yumyo** [comment]
Is this still working on Kalabox 2.1.2 ?

Got no logs inside my logs folder under my app root.

**Comment by pirog** [comment]
Should be! That said i think your best bet is to look at the "docker logs" section in our troubleshooting docs. you can get a lot of mileage out of these commands and they are not app or service specific 
http://docs.kalabox.io/en/v2.1/troubleshooting/#accessing-logs
