### ISSUE TITLE
Sites show as unstarted in GUI - Kalabox setup on non-standard IP

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1172]
My sites no longer show up as started in the GUI. The image is greyed out and the links are non-operable, but if I manually type in the URL of the site, it is in fact running. "kbox list" on the command line also shows their status as running.

I received the following error:

```
/Users/alec/workspace/kalabox/kalabox-cli/node_modules/bluebird/js/main/captured_trace.js:479 Unhandled rejection VError: Error listening to docker events.: Hostname/IP doesn't match certificate's altnames: "IP: 10.13.37.100 is not in the cert's list: 10.13.37.104"
```

**The Problem**

A number of issues can appear if your Kalabox2 VM IP strays from 10.13.37.100. To check your VM's IP, run:

```
~/.kalabox/bin/docker-machine ip Kalabox2
```

**Workaround**

1. Uninstall Kalabox
2. Make sure ALL Virtual Box machines you may have are off before installing Kalabox. 
3. Re-install Kalabox
4. Check IP.

My Kalabox IP has been incrementing by one after several reinstalls. It appears this is due to a default Docker Toolbox-installed VM having been running during the reinstalls. After uninstalling and reinstalling with the other VM turned off, my Kalabox2 VM returns to 10.13.37.100 IP.

**Longer-term Solution**

In the longer-term, we may want to invest time in making Kalabox flexible to handle multiple IPs. It appears to be close to this goal, although this error and a similar error with the Redis container...

```
Uncaught Error: Redis connection to 10.13.37.100:8160 failed - connect ECONNREFUSED 10.13.37.100:8160
```

...seem to indicate that work still remains to be done.

**Comment by reynoldsalec** [comment]
Created FAQ article: https://kalabox.freshdesk.com/solution/articles/14000010221-i-start-my-sites-but-they-never-show-up-as-started-

**Comment by pirog** [comment]
There are two things we need to do to get true dynamic IP support

1. We need service containers to rebuild so they get the correct IP
2. We need to `docker-machine regenerate-certs`

**Comment by pirog** [comment]
I also think running through the installer again will reset all the IPs correctly.
