### ISSUE TITLE
KALABOX_ENGINE_REMOTE_IP is coming across as undefined on linux

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1173]
Hello!

My XDebug was not firing, so I ran kbox env and saw that the remote ip is undefined:

KALABOX_VERSION=0.12.0-alpha.19
KALABOX_ENGINE_IP=10.13.37.100
KALABOX_ENGINE_REMOTE_IP=undefined

Thoughts?

**Comment by labboy0276** [comment]
FYI

I set REMOTE_IP: 10.13.37.100 in kalabox-compose.yml did a rebuild and XDebug workz fine.

**Comment by pirog** [comment]
You should also be able to do the following to work around this

```bash
# POSIX
export KALABOX_ENGINE_REMOTE_IP=10.13.37.100

#WINDOZE
set KALABOX_ENGINE_REMOTE_IP=10.13.37.100
```
