### ISSUE TITLE
Provide in-app documentation on how to expose `/var/log` to the outside for services

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1175]
This way users can see their log files without having to get into the container. This would be very useful and would mitigate a lot of requests for support for people who did custom things

**Comment by AubreyR** [comment]
Hello @pirog .  I am trying to figure out how to access my PHP logs, and this is the closest thing I could find on how to do that.  Where exactly does "in-app documentation" reside?

**Comment by pirog** [comment]
@AubreyR we are going to automount pantheon logs but ive added a few places in teh docs on how to manually explore logs in other scenarios
