### ISSUE TITLE
Unable to add new site from UI

### ISSUE THREAD

**Issue by fluxsauce** [kalabox/kalabox#1176]
Fresh install; added Pantheon Credentials, then attempted to add a site:

> `expecting an array, a promise or a thenable`

![kalabox-addnewsite](https://cloud.githubusercontent.com/assets/976391/14127228/20d837b8-f5cb-11e5-82a7-a9ce09bf5bea.gif)

**Comment by pirog** [comment]
thats definitely not good :(

are you able to add this site through the cli with success or some thing?

**Comment by fluxsauce** [comment]
Same error:

```bash
jon@wsmv-dh0qtk1 ~ $ kbox
expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

TypeError: expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

    at process._tickCallback (node.js:917:13)
```

**Comment by pirog** [comment]
just on a normal `kbox`?

Is it possible that you have old kalabox cli stuff from a very old `npm install -g kalabox`

**Comment by pirog** [comment]
also there should be logs in `~/.kalabox/logs` that might help at least point us in the right direction.

**Comment by fluxsauce** [comment]
Well, damn, this looks self-inflicted. Good call, doing some housecleaning...

```bash
jon@wsmv-dh0qtk1 ~ $ npm list -g | ggrep kalabox
├─┬ kalabox@0.8.3
npm ERR! extraneous: kalabox-app-backdrop@0.8.1 /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-backdrop
npm ERR! extraneous: kalabox-app-drupal@0.8.1 /usr/local/lib/node_modules/kalabox/node_modules/kalabox-app-drupal
npm ERR! extraneous: kalabox-engine-docker@0.8.1 /usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker
npm ERR! extraneous: kalabox-services-kalabox@0.8.2 /usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox
│ ├── kalabox-app-backdrop@0.8.1 extraneous
│ ├── kalabox-app-drupal@0.8.1 extraneous
│ ├── kalabox-engine-docker@0.8.1 extraneous
│ ├─┬ kalabox-metrics-rest@0.1.0
│ ├── kalabox-services-kalabox@0.8.2 extraneous
```

**Comment by pirog** [comment]
im *guessing* that is probably the issue. def let me know. you might need to restart the ui to get the correct files to load although im not positive on that.

im apprehensive to do any pre-emptive house cleaning during an install even if its just to remove our old stuff. presumably this issue would only impact a very small subset of users.

**Comment by fluxsauce** [comment]
I think the problem is between the keyboard and the chair on this. Sorry about that, thanks for the prompt troubleshooting!

**Comment by fluxsauce** [comment]
Yeah, that was it. I ripped out a bunch of old node stuff and manually deleted a few directories and that sorted it.

![screen shot 2016-03-29 at 9 09 46 pm](https://cloud.githubusercontent.com/assets/976391/14131689/9675363e-f5f2-11e5-9e68-38147709e1d8.png)

**Comment by pirog** [comment]
awesome + whew. almost had a stroke when i saw that first error. 

that said, there are plenty of bugs to find so please post anything you deem worthy.

**Comment by fluxsauce** [comment]
![screen shot 2016-03-29 at 9 36 25 pm](https://cloud.githubusercontent.com/assets/976391/14132070/4f7cebce-f5f6-11e5-8e74-01c1b3cb82ee.png)

It's up and running!

**Comment by fluxsauce** [comment]
> almost had a stroke when i saw that first error

Sincere apologies. So far so good...
