### ISSUE TITLE
better UX around specifying the site name in `kbox create`

### ISSUE THREAD

**Issue by fluxsauce** [kalabox/kalabox#1177]
* Click "Add new site"
* Name Your App:
    * Expected: Default to Pantheon site name
    * Actual: `(Blank)`
* Which environment?
    * Expected: Default to Dev environment
    * Actual: `-- Select Environment --`

**Comment by pirog** [comment]
Thanks for this! We are focusing on the rest of the critical issues and ramping up our testing for alpha3 but this is a great candidate for alpha4!

**Comment by pirog** [comment]
@reynoldsalec i believe you are unblocked on #1258 now
