### ISSUE TITLE
DB not created

### ISSUE THREAD

**Issue by baroneddy** [kalabox/kalabox#1181]
Hi there,

First time trying Kalabox (0.12.11) and I am running into a problem with my DB. When I add a new Drupal7 site, I don't have any DB created. When a go to my app url, I am prompted to configure drupal install, and I am asked to enter the DB infos. I try to use the info that Kalabox is giving in "Connection info" me but it keeps returning me:
`Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] Connection refused.`

Am I doing something wrong?

Thanks for your help!

Ed

**Comment by pirog** [comment]
if you run `kbox services` inside your app directory on the CLI you will see internal connection info for you r database. We will add this to the gui soon but it is different than the connection info on the GUI which is how to access the DB from a third party tool like sequelpro.

For ease the connection info should be

```yaml
name: drupal
user: drupal
password: drupal
host: database
port: 3306
```

**Comment by baroneddy** [comment]
That works! Thanks a lot :+1:
