### ISSUE TITLE
Add an easy way to flush the redis cache, ie a `kbox redis` command

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1183]
Lets find a fun way to use the reds-cli so we can flush the redis cache easily.

**Comment by pirog** [comment]
I dont think we will be able to get to this until we are beta but +1

**Comment by pirog** [comment]
In the meantime. if you have a workaround re: manual flush please post it here!

**Comment by labboy0276** [comment]
+1 Would be great to have this since I am having an issue with a site an need to flush redis manually.

**Comment by pirog** [comment]
@labboy0276 what is the command you actually want to run?

**Comment by labboy0276** [comment]
flushall within the redis-cli
