### ISSUE TITLE
XHProf Plugin

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1184]
XDebug support is awesome, but it would be great to have XHProf support too.  [drupal.org](https://www.drupal.org/node/946182) has some instructions, but it would be great to have the step "kbox start" as an alternative, especially because [Acquia supports XHProf](https://docs.acquia.com/articles/using-xhprof-evaluate-code-performance) out of the box, but Pantheon does not.

**Comment by pirog** [comment]
I agree this would be great but im not sure we will be able to get to this until we've gone beta with the core product.

**Comment by ptmkenny** [comment]
Cool I certainly understand.

Long-term, it would be awesome if Kalabox, when using it as a local dev environment for Pantheon, could do all the things that Pantheon can do + the debugging stuff that Pantheon can't (like Xdebug, which it does already, and XHProf and other things in the future).

**Comment by pirog** [comment]
What additional things would you like to see?

**Comment by reynoldsalec** [comment]
Blackfire would be an complimentary or replacement feature; I know DrupalVM provides both.

**Comment by bradchesney79** [comment]
...Blackfire is an analysis tool and not so much a debugging tool for anyone not interested in leaving to find out what it does. Xdebug does both debugging (very popular) and analysis (most people don't even know it is built in as well). Blackfire is trying to improve the overlapping proficiencies of itself and Xdebug. So, that you will use their product for analysis instead of Xdebug. FWIW

**Comment by pirog** [comment]
This is a good candidate for our new plugin architecture

**Comment by ccharlton** [comment]
XHProf +1,000

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
