### ISSUE TITLE
a little mistake in uninstalling instructions

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#1185]
on this page -
https://kalabox.freshdesk.com/support/solutions/articles/14000006362-uninstalling-on-windows

it currently says -
Open Programs and Features by clicking the Start button, clicking Control Panel, clicking Programs, and then clicking Programs and Features.

instead I think it should be -
Open Programs and Features by clicking the Start button, clicking Control Panel, clicking Programs and Features. Then click on Uninstall a program.

**Comment by pirog** [comment]
thanks @shaal. i made the change in the wiki although we should be sure that this is consistent across windows versions.
