### ISSUE TITLE
OSX Uninstall instructions no longer accurate

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox#1187]
Following: https://kalabox.freshdesk.com/support/solutions/articles/14000006361-uninstalling-on-osx

Was running this to remove before installing the GUI alpha and I assume it's because this shell script isn't in my path, perhaps we need to update the instructions to indicate where this needs to run from?

```
dustinleblanc@Dustins-MacBook-Pro ~
  % sudo kalabox-uninstall.sh
Password:
sudo: kalabox-uninstall.sh: command not found
```

**Comment by pirog** [comment]
@dustinleblanc if you had the VERY VERY early alpha (which we only gave out to maybe 25 people) then this is true. That said maybe we should update to reflect that you can run the `uninstall.tool` packaged with the dmg

**Comment by Steve-A-Orr** [comment]
I agree with the alteration of the documentation and **emphasize the importance**. Not only is there a broken link in the Mac install content, but when you actually find the Uninstall instructions, they are not correct--especially if you've installed the CLI tool. Luckily, I was persistent and stumbled on @dustinblanc issue with the answer from @pirog. Thank you very much for the clue about the uninstall tool.

**Comment by reynoldsalec** [comment]
@Steve-A-Orr thanks for the report and apologies for the broken link, do the uninstall directions for Mac now reflect the correct process?

http://support.kalabox.io/support/solutions/articles/14000006361-uninstalling-on-osx

**Comment by Steve-A-Orr** [comment]
No, they do not. From what I hear, you're supposed to run the
"uninstall.tool" script.

**Comment by dustinleblanc** [comment]
It seems to work fine now, only issue it seems is if you have the old CLI
pre-alpha version (as I did when coming to this page). Later versions
worked beautifully.
