### ISSUE TITLE
Error dispatching event listeners [post-create-app]: Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox#1188]
![](https://i.imgur.com/oaRAHaI.png)

Happened when trying to spin up a brand new install of Drupal 8 via the UI

**Comment by pirog** [comment]
Yeah this can happen when you mix pantheon apps with "normal" drupal apps.

Good news is that https://github.com/kalabox/kalabox/issues/1150 which is
slated for alpha3 should resolve all issues like this.

**Comment by pirog** [comment]
This is def resolved in the soon to be released alpha3 so closing this out
