### ISSUE TITLE
Livereload documentation

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1192]
We have a pathway for using livereload via kbox npm, we should test and document that.

**Comment by pi-ron** [comment]
@reynoldsalec Anywhere on the web that mentions livereload setup?  Can't find much apart from this https://github.com/thinktandem/tandem/issues/28

**Comment by reynoldsalec** [comment]
@pi-ron with 2.1.0 I think using browser-sync would work pretty well now that we have faster filesharing. I'd watch the compiled CSS file and introduce a [reloadDelay](https://browsersync.io/docs/options#option-reloadDelay) time so it doesn't try the reload immediately.

In the past we were going to suggest people run browser-sync inside of the virtualized environment and we still might work on a plugin or other feature to help do this, but I'd be interested to see how running it from the host environment works.

If you get something setup that works well, definitely would love docs and/or a blog post so others can benefit from your genius!

**Comment by pi-ron** [comment]
@reynoldsalec Thanks for the feedback.  So to confirm, I would setup browsersync on my local environment and run it locally, not through `kbox ...`?

**Comment by reynoldsalec** [comment]
Yes @pi-ron after talking with @pirog we both think this will be the easiest path for folks going forward. I know it's certainly less intimidating for me as a developer :)

**Comment by pi-ron** [comment]
Ok would that mean I compile styles etc. locally too, or with kbox?

**Comment by pirog** [comment]
Yeah at this point I think the file sharing stuff is good enough in 2.1.x
where you can use 'grunt' instead of 'Kbox grunt'. We are waiting for more
feedback but we might even remove the front end tooling stuff in the near
future.

**Comment by reynoldsalec** [comment]
@pi-ron referenced this example gulpfile.js which has a working config for browser-sync:

https://gist.github.com/kurtschlatzer/262cbf8bb4d83d82d6792e1ba4f8bd82#file-gulpfile-js-L37

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
