### ISSUE TITLE
Kalabox Drupa 8 config has fallen behind what Pantheon is doing

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1193]
Hello!

I put many things in this ticket as a FYI.

I spun out a couple different sites to double check, but the errors are all the same.  It seems it isn't picking up any $_ENV settings any longer as seen below.  So it is failing at numerous points, no /tmp folder detected, no hash salt, etc.  I ran this with XDebug and captured the settings so you can see they are there (I am not pasting them all):

```
$_ENV = array[26]
  $_ENV['PANTHEON_SITE'] = (string) UUID
  $_ENV['PANTHEON_ENVIRONMENT'] = (string) kalabox
  $_ENV['PANTHEON_BINDING'] = (bool) 0
  $_ENV['DB_HOST'] = (string) database
  $_ENV['DB_PORT'] = (string) 3306
  $_ENV['DB_USER'] = (string) pantheon
  $_ENV['DB_PASSWORD'] = <string>
  $_ENV['DB_NAME'] = (string) pantheon
  $_ENV['CACHE_HOST'] = (string) redis
  $_ENV['CACHE_PORT'] = (string) 8161
  $_ENV['CACHE_PASSWORD'] = <string>
  $_ENV['PANTHEON_INDEX_PORT'] = (string) 449
  $_ENV['PANTHEON_INDEX_HOST'] = (string) solr
```

I am able to get past the hash salt issue by manually copying the actual string hash salt and putting it in settings.php.  When I use XDEBUG, it is going to my pantheon and local settings and adding the settings, config, etc, nit sure why it isnt appying them though.  Then I thunk well, its cause I am not on VB anymore and it can;t see the Pantheon settings per this:

```

Type	php
Date	Sunday, April 3, 2016 - 10:09
User	admin
Location	http://d8-oop.kbox/admin?q=admin
Referrer	http://d8-oop.kbox/user/1
Message	Warning: file_put_contents(temporary://filezJOrgh): failed to open stream: "Drupal\Core\StreamWrapper\TemporaryStream::stream_open" call failed in file_unmanaged_save_data() (line 888 of /code/core/includes/file.inc).
Severity	Warning
Hostname	10.13.37.100
Operations	
```

```
john@kalamuna:~/.kalabox/apps/d8-oop$ kbox drush cr
exception 'RuntimeException' with message 'Missing                   [error]
$settings['hash_salt'] in settings.php.' in
/code/core/lib/Drupal/Core/Site/Settings.php:145
Stack trace:
#0 /code/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47):
Drupal\Core\Site\Settings::getHashSalt()
#1 /code/core/includes/utility.inc(32):
Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
#2 phar:///usr/local/bin/drush/commands/core/cache.drush.inc(291):
drupal_rebuild(Object(Composer\Autoload\ClassLoader),
Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: drush_cache_rebuild()
#4 phar:///usr/local/bin/drush/includes/command.inc(366):
call_user_func_array('drush_cache_reb...', Array)
#5 phar:///usr/local/bin/drush/includes/command.inc(217):
_drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 phar:///usr/local/bin/drush/includes/command.inc(185):
call_user_func_array('drush_command', Array)
#8 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#9 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 phar:///usr/local/bin/drush/includes/startup.inc(321):
drush_main()
#11 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#13 {main}
john@kalamuna:~/.kalabox/apps/d8-oop$ kbox drush --version
 Drush Version   :  8.0.5 

john@kalamuna:~/.kalabox/apps/d8-oop$ 
```

So I made a local.settings.php and added this:

```
$settings['hash_salt'] = $_SERVER['DRUPAL_HASH_SALT'];
$config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';

$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;

$settings['rebuild_access'] = TRUE;
```

And everything worked just fine....

Thoughts on this, should we be building out a local,settings.php for people on Linux, etc?

**Comment by pirog** [comment]
This is a non-pantheon app? Still not exactly clear on how to replicate

On Sunday, April 3, 2016, John Ouellet <notifications@github.com> wrote:

> Hello!
>
> I put many things in this ticket as a FYI.
>
> I spun out a couple different sites to double check, but the errors are
> all the same. It seems it isn't picking up any $_ENV settings any longer as
> seen below. So it is failing at numerous points, no /tmp folder detected,
> no hash salt, etc. I ran this with XDebug and captured the settings so you
> can see they are there (I am not pasting them all):
>
> $_ENV = array[26]
>   $_ENV['PANTHEON_SITE'] = (string) UUID
>   $_ENV['PANTHEON_ENVIRONMENT'] = (string) kalabox
>   $_ENV['PANTHEON_BINDING'] = (bool) 0
>   $_ENV['DB_HOST'] = (string) database
>   $_ENV['DB_PORT'] = (string) 3306
>   $_ENV['DB_USER'] = (string) pantheon
>   $_ENV['DB_PASSWORD'] = <string>
>   $_ENV['DB_NAME'] = (string) pantheon
>   $_ENV['CACHE_HOST'] = (string) redis
>   $_ENV['CACHE_PORT'] = (string) 8161
>   $_ENV['CACHE_PASSWORD'] = <string>
>   $_ENV['PANTHEON_INDEX_PORT'] = (string) 449
>   $_ENV['PANTHEON_INDEX_HOST'] = (string) solr
>
> I am able to get past the hash salt issue by manually copying the actual
> string hash salt and putting it in settings.php. When I use XDEBUG, it is
> going to my pantheon and local settings and adding the settings, config,
> etc, nit sure why it isnt appying them though. Then I thunk well, its cause
> I am not on VB anymore and it can;t see the Pantheon settings per this:
>
>
> Type    php
> Date    Sunday, April 3, 2016 - 10:09
> User    admin
> Location    http://d8-oop.kbox/admin?q=admin
> Referrer    http://d8-oop.kbox/user/1
> Message Warning: file_put_contents(temporary://filezJOrgh): failed to open stream: "Drupal\Core\StreamWrapper\TemporaryStream::stream_open" call failed in file_unmanaged_save_data() (line 888 of /code/core/includes/file.inc).
> Severity    Warning
> Hostname    10.13.37.100
> Operations
>
> john@kalamuna:~/.kalabox/apps/d8-oop$ kbox drush cr
> exception 'RuntimeException' with message 'Missing                   [error]
> $settings['hash_salt'] in settings.php.' in
> /code/core/lib/Drupal/Core/Site/Settings.php:145
> Stack trace:
> #0 /code/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47):
> Drupal\Core\Site\Settings::getHashSalt()
> #1 /code/core/includes/utility.inc(32):
> Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
> #2 phar:///usr/local/bin/drush/commands/core/cache.drush.inc(291):
> drupal_rebuild(Object(Composer\Autoload\ClassLoader),
> Object(Symfony\Component\HttpFoundation\Request))
> #3 [internal function]: drush_cache_rebuild()
> #4 phar:///usr/local/bin/drush/includes/command.inc(366):
> call_user_func_array('drush_cache_reb...', Array)
> #5 phar:///usr/local/bin/drush/includes/command.inc(217):
> _drush_invoke_hooks(Array, Array)
> #6 [internal function]: drush_command()
> #7 phar:///usr/local/bin/drush/includes/command.inc(185):
> call_user_func_array('drush_command', Array)
> #8 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
> drush_dispatch(Array)
> #9 phar:///usr/local/bin/drush/includes/preflight.inc(66):
> Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #10 phar:///usr/local/bin/drush/includes/startup.inc(321):
> drush_main()
> #11 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
> #12 /usr/local/bin/drush(10): require('phar:///usr/loc...')
> #13 {main}
> john@kalamuna:~/.kalabox/apps/d8-oop$ kbox drush --version
>  Drush Version   :  8.0.5
>
> john@kalamuna:~/.kalabox/apps/d8-oop$
>
> So I made a local.settings.php and added this:
>
> $settings['hash_salt'] = $_SERVER['DRUPAL_HASH_SALT'];
> $config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';
>
> $config['system.performance']['css']['preprocess'] = FALSE;
> $config['system.performance']['js']['preprocess'] = FALSE;
>
> $settings['rebuild_access'] = TRUE;
>
> And everything worked just fine....
>
> Thoughts on this, should we be building out a local,settings.php for
> people on Linux, etc?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1193>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by labboy0276** [comment]
Negative, steps to replicate (sorry):

0. Be on Linux Version
1. spin out a new d8 site on Pantheon / use an existing d8 site
2. kbox create pantheon
3.  try a kbox drush cr or open the site in the browser, you will see what I laid out above

**Comment by labboy0276** [comment]
I am also starting the app obviously after create

**Comment by pirog** [comment]
I don't see this. It works as expected for me.

**Comment by labboy0276** [comment]
odd.  oh well. i have a work around anyway.

**Comment by labboy0276** [comment]
FYI, this is on a fresh install of kalabox 0.12 

```
john@kalamuna:~/.kalabox/apps$ kbox create pantheon
? Choose a Pantheon account. john@kalamuna.com
? Which site? d8-oop
? Which environment? dev
? What will you call this monster you have created: d8-oop
Creating.
Cleaning up.
Running pre create tasks.
Creating app structure.
Downloading: [0.2%] ...box-app-pantheon/tarball/v0.12.0-alpha.8
Configuring app.
Starting engine.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Sharing code.
Starting containers.
Creating d8oop_redis_1
Creating d8oop_data_1
Creating d8oop_solr_1
Creating d8oop_db_1
Creating d8oop_appserver_1
Creating d8oop_edge_1
Creating d8oop_cli_1
Creating d8oop_terminus_1
Running post start tasks.
Running post create tasks.
Pulling screenshot.
Downloading: [60.9%] ...3a3a-6fd9-4d49-96e6-edc56f9c207e_dev.png
Pulling code.
Cloning into '.'...
Warning: Permanently added '[codeserver.dev.85c23a3a-6fd9-4d49-96e6-edc56f9c207e.drush.in]:2222,[166.78.241.209]:2222' (RSA) to the list of known hosts.
remote: Counting objects: 36618, done.
remote: Compressing objects: 100% (18587/18587), done.
remote: Total 36618 (delta 15611), reused 36607 (delta 15605)
Receiving objects: 100% (36618/36618), 22.91 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (15611/15611), done.
Checking connectivity... done.
Pulling database.
Pulling files.
files_dev/php/twig/fdeb2524_form.html.twig_e0b082b2f5d07534ec73b4673a8b8aceb9e9dd5878f7fa0855f13edbe8cae4f1/.htaccess
files_dev/php/twig/fdeb2524_form.html.twig_e0b082b2f5d07534ec73b4673a8b8aceb9e9dd5878f7fa0855f13edbe8cae4f1/52ad70c42853e5e8d0b4c077ab79909872370b995b06f49c4a138fadf4bdc17b.php
files_dev/php/twig/fdeb2524_block--system-branding-block.html.twig_3d2f89eb5c91c9b350409f43b7f4b24c36f3c5e9746b04f76c92f285737bee6a/.htaccess
files_dev/php/twig/fdeb2524_block.html.twig_45ac5c0ff3b3ca3e2b651ee34c95cc0dc358a50e8d2d314a96eddc4d87abf09d/.htaccess
files_dev/php/twig/fdeb2524_block.html.twig_45ac5c0ff3b3ca3e2b651ee34c95cc0dc358a50e8d2d314a96eddc4d87abf09d/cbf7d5403738b0a44fbd1699a974922b7e621e664d61e290b0c70120e9016559.php
files_dev/php/twig/fdeb2524_block--system-branding-block.html.twig_3d2f89eb5c91c9b350409f43b7f4b24c36f3c5e9746b04f76c92f285737bee6a/a9d1d3e8019c01d6d7eb4773004312f4045370d8c06f2d3e9026e963035ed917.php
files_dev/php/twig/fdeb2524_form-element.html.twig_9dca4e9f3f3ea0a3ae10c9e28668168e23d1c429bf95ff8d2a32e97741daa90d/.htaccess
files_dev/php/twig/fdeb2524_page-title.html.twig_00e1de4fd92a777a6ce4325ea2099fd396056afacb5156eeb4698d84b7580e3c/366d7225b60b36c06aa41ca0187d5b5ce121de746bd5a1d25930b99345d805e4.php
files_dev/php/twig/fdeb2524_region.html.twig_55568057a24a411de41ef6cfb43f1a39c42827f1db340d4fd6500b836ea34ab1/.htaccess
files_dev/php/twig/fdeb2524_block.html.twig_b1f2f34769edd9275961b9ee0d259e0ebf15d8127220d01f83fa087921cc59c9/.htaccess
files_dev/php/twig/.htaccess
files_dev/php/twig/fdeb2524_form-element-label.html.twig_ff1bc685f9dac0ba2e01915e7bb3fa7b23b69c84775822c541db3a85a47accc9/.htaccess
files_dev/php/twig/fdeb2524_status-messages.html.twig_3249d02957087de4a87a01b6852369cb65431c209d749f01a9bb885cbd6b0696/27b0c8e8eac28727ba34a12179f609f6048ef079cd01b68eee9bbf87e076b0ef.php
files_dev/.htaccess
files_dev/php/twig/fdeb2524_input.html.twig_c501c912de0f232634fcbc22abcd23370d1b5d2641404e989f36f3a17c9e0920/.htaccess
files_dev/php/twig/fdeb2524_html.html.twig_4dc29ce9c877fcff3a5581c7d75f99feab6afb63b1780f767a716f13c8521ffe/.htaccess
files_dev/php/twig/fdeb2524_html.html.twig_4dc29ce9c877fcff3a5581c7d75f99feab6afb63b1780f767a716f13c8521ffe/9b0fe9e015f49a63a6d1f95f957ae8f4a37f3e7e42beda6a188e48baf4317c3a.php
files_dev/php/twig/fdeb2524_status-messages.html.twig_3249d02957087de4a87a01b6852369cb65431c209d749f01a9bb885cbd6b0696/.htaccess
files_dev/php/twig/fdeb2524_block--system-messages-block.html.twig_c83396eab445384b8902aedac4f996519286dbd0713950e69724e48e379b3289/.htaccess
files_dev/php/twig/fdeb2524_menu-local-task.html.twig_ea052fc935e97a7abd0d1a23608ca1808f53eb148a64fc821bc1b3049c383c35/.htaccess
files_dev/php/twig/fdeb2524_container.html.twig_3f735dd52cfca4da5579e610b1f061183f2d76ebb247de40fecefda99db2f847/.htaccess
files_dev/private/.htaccess
files_dev/php/twig/fdeb2524_input.html.twig_c501c912de0f232634fcbc22abcd23370d1b5d2641404e989f36f3a17c9e0920/12bd18dcf761e6611add8a9e70ebfe5744ace7b3115fa49dce216b7b51a61c18.php
files_dev/php/twig/fdeb2524_block--system-messages-block.html.twig_c83396eab445384b8902aedac4f996519286dbd0713950e69724e48e379b3289/33bf6de1a2c9c9c2074750ae923c7e9606f2ddbaac3607d97021c545366c4a79.php
files_dev/php/twig/fdeb2524_page-title.html.twig_00e1de4fd92a777a6ce4325ea2099fd396056afacb5156eeb4698d84b7580e3c/.htaccess
files_dev/php/twig/fdeb2524_menu-local-task.html.twig_ea052fc935e97a7abd0d1a23608ca1808f53eb148a64fc821bc1b3049c383c35/079e62584aecca036cce9a45c1e63c449b2c9bf768c7ff84c18c36ad84da90d0.php
files_dev/php/twig/fdeb2524_form-element-label.html.twig_ff1bc685f9dac0ba2e01915e7bb3fa7b23b69c84775822c541db3a85a47accc9/6bd110750b676ebed5a3c60c2276a2b6edc362ff285cda1f6ffa74a2a57476ef.php
files_dev/php/twig/fdeb2524_menu-local-tasks.html.twig_df2cc8fa73baeb1f3392a276826f84e26b7eb169d2629f9ade1fe5447339adf8/.htaccess
files_dev/php/twig/fdeb2524_page.html.twig_a3df4e90a9d687e0159455d99b73ccd2a5a8d3aabe40d0f525a38008d0a3ad91/.htaccess
files_dev/php/twig/fdeb2524_region.html.twig_55568057a24a411de41ef6cfb43f1a39c42827f1db340d4fd6500b836ea34ab1/4232a2345e65194cd8270d5b55049e1cbaa68be236914f877ffed81e527f517a.php
files_dev/php/twig/fdeb2524_menu-local-tasks.html.twig_df2cc8fa73baeb1f3392a276826f84e26b7eb169d2629f9ade1fe5447339adf8/2ba27e1ad76862630d2360be1c0b970953deb417bfbc8e769442aacb0c65bee6.php
files_dev/php/twig/fdeb2524_form-element.html.twig_9dca4e9f3f3ea0a3ae10c9e28668168e23d1c429bf95ff8d2a32e97741daa90d/0a5a30a2e8e269b36e8a1f4c2a7ef76f8f149157687f6b6a58140467df00d9b7.php
files_dev/php/twig/fdeb2524_block.html.twig_b1f2f34769edd9275961b9ee0d259e0ebf15d8127220d01f83fa087921cc59c9/bc83eb64d341a636687ea1809dfcb1471ce352e995ff1386beb329816c08e9c1.php
files_dev/php/twig/fdeb2524_container.html.twig_3f735dd52cfca4da5579e610b1f061183f2d76ebb247de40fecefda99db2f847/40ed82b48ecaa5a3d0cece2c25bf22cbfde310e9e4cab4be7edd2897540dd176.php
files_dev/php/twig/fdeb2524_page.html.twig_a3df4e90a9d687e0159455d99b73ccd2a5a8d3aabe40d0f525a38008d0a3ad91/ff7aa24485e360e209f82ace88e09e37f727220e9bd67cf14a457d100239b35d.php
files_dev/.htaccess
files_dev/skipped.log
###############################################################
                                                               
                    BOOMSHAKALAKA!                             
                                                               
  Your app has started up correctly. Here are some vitals:     
                                                               
  URL: http(s)://d8-oop.kbox
  LOCATION: /home/john/.kalabox/apps/d8-oop
                                                               
###############################################################
john@kalamuna:~/.kalabox/apps$ cd d8-oop
john@kalamuna:~/.kalabox/apps/d8-oop$ kbox start
Starting.
Cleaning up.
Running pre start tasks.
Sharing code.
Starting containers.
d8oop_redis_1 is up-to-date
Starting d8oop_data_1
d8oop_solr_1 is up-to-date
d8oop_db_1 is up-to-date
d8oop_appserver_1 is up-to-date
d8oop_edge_1 is up-to-date
Starting d8oop_cli_1
Starting d8oop_terminus_1
Running post start tasks.
###############################################################
                                                               
                    BOOMSHAKALAKA!                             
                                                               
  Your app has started up correctly. Here are some vitals:     
                                                               
  URL: http(s)://d8-oop.kbox
  LOCATION: /home/john/.kalabox/apps/d8-oop
                                                               
###############################################################
john@kalamuna:~/.kalabox/apps/d8-oop$ kbox drush cr
exception 'RuntimeException' with message 'Missing                   [error]
$settings['hash_salt'] in settings.php.' in
/code/core/lib/Drupal/Core/Site/Settings.php:145
Stack trace:
#0 /code/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47):
Drupal\Core\Site\Settings::getHashSalt()
#1 /code/core/includes/utility.inc(32):
Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
#2 phar:///usr/local/bin/drush/commands/core/cache.drush.inc(291):
drupal_rebuild(Object(Composer\Autoload\ClassLoader),
Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: drush_cache_rebuild()
#4 phar:///usr/local/bin/drush/includes/command.inc(366):
call_user_func_array('drush_cache_reb...', Array)
#5 phar:///usr/local/bin/drush/includes/command.inc(217):
_drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 phar:///usr/local/bin/drush/includes/command.inc(185):
call_user_func_array('drush_command', Array)
#8 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#9 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 phar:///usr/local/bin/drush/includes/startup.inc(321):
drush_main()
#11 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#13 {main}
john@kalamuna:~/.kalabox/apps/d8-oop$ kbox version
0.12.0-alpha.19
```

**Comment by pirog** [comment]
Ok, i am able to replicate this but dont think it has anything to do with linux.

**Comment by reynoldsalec** [comment]
@labboy0276's fix from his original comment got me past the original error, but once my environmental variables were setup I received new errors regarding missing a table 'pantheon.key_value' in the DB:

```
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or[error]
view not found: 1146 Table 'pantheon.key_value' doesn't exist' in
/code/core/lib/Drupal/Core/Database/Statement.php:64
```

```
Next exception 'Drupal\Core\Database\DatabaseExceptionWrapper' with
message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table
'pantheon.key_value' doesn't exist: DELETE FROM {key_value} 
WHERE  (name IN  (:db_condition_placeholder_0)) AND (collection =
:db_condition_placeholder_1); Array
(
    [:db_condition_placeholder_0] => drupal_css_cache_files
    [:db_condition_placeholder_1] => state
)
' in /code/core/lib/Drupal/Core/Database/Connection.php:676
```

**Comment by pirog** [comment]
@reynoldsalec this looks more like just a normal drupal problem than kalabox related. you sure you have your db?

**Comment by reynoldsalec** [comment]
Damn you quick @pirog, was just checking that and realized it's empty, so...D'OH!

**Comment by pirog** [comment]
I think this is also happening for chaz over at https://github.com/kalabox/kalabox/issues/1204

**Comment by labboy0276** [comment]
If you follow the code with XDEBUG @reynoldsalec it seems that it just isnt applying any of the ENV vars in the pantheon settings file.  Not 100% sure why.  However, since you added the local settings file, i would add the pantheon settings in the local file that they use to grab the db connection and see if that wins it.

**Comment by pirog** [comment]
Checking this out now! Standby

**Comment by pirog** [comment]
Ok so here are the few things i can tell are going on @labboy0276 @reynoldsalec 

1. Environment loads correctly for the appserver but not for drush (this resolves the HASH_SALT issue)

> current (untested on D7/wordpress/backdrop) workaround https://github.com/kalabox/kalabox-app-pantheon/commit/6b64dfc6b3e01656ba08ad92009595a37c286c5c

2. CSS files not loading correctly, this seems to be a function of three (possibly related things) 
  a. inability to write aggregated CSS files
  b. incorrect location of aggregated CSS files
  c. MIME type fail #1204 

> current workaround: disable CSS/JS aggregation

**Comment by pirog** [comment]
Ok. as a temporary workaround for 2 above you will want to use the rest of the branch and do a `kbox rebuild` for now. 
https://github.com/kalabox/kalabox-app-pantheon/compare/1193-d8Fixes

You may need to also `kbox drush cr/rr` after the site spins up which leads me too

There are two other things we should address for this

1. #1164 (auto `drush rr` after a pull)
2. Get `PANTHEON_DATABASE_STATE` into the ENV correctly
