### ISSUE TITLE
Alter GUI to handle multi-app actionz and then do some basic tests

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1194]
### @reynoldsalec 

- [x] Let's remove the blocking screen to some sort of app card progress thing

### @rileysaurus 

- [ ] ~~Let's pipe the status messages into the notification center~~ #1210

**Comment by reynoldsalec** [comment]
@rileysaurus I've gotten rid of the general overlay and replaced it with a loading indicator on the sites.

I'm guessing you'll be adding data to ui.sites on what site action is currently being performed; when we do that, we can display the action (Starting/Stopping/etc) when the loading indicator is active.

Not 100% happy with how the loading indicator looks, but I think that's an issue for later. Handing over to you @rileysaurus.

**Comment by pirog** [comment]
@reynoldsalec DO THE TESTING OF ALL THE THINGS before you merge
