### ISSUE TITLE
Add `kbox fork` to clone an existing kalabox app

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#1196]
Not sure if this is a feature request, or perhaps just needing a recommendation on how you guys would handle this situation, but here's what I'd like to be able to do:  

I'd like to have a command like `kbox fork` or `kbox branch` that essentially would fork my entire project into a separate kalabox app (file structure, database, docker files, config files, etc). 

Basically, it could work similar to pantheon's multidev but on kalabox itself.  The reason for that instead of just using pantheon's multidev, is it could work for the pantheon-based app, but it could also work for non-pantheon apps as well (made through `kbox create drupal7`, `kbox create drupal8`, `kbox create wordpress`).  It could also work for developers who don't have access to pantheon's multidev environment, due to the pricing requirements to gain access to that feature.

Some example use cases: 

- I want to test a module inside my specific site, to make sure it works with other modules I have.  Along the way, I decide to scrap it. I'd rather not have to worry about incomplete uninstall scripts, or data that may have changed as a result of introducing a poorly coded, or incompatible, module into my system. 

- Changing the kalabox-compose.yml files, or other files outside of the approot/code directory. Those directories by default don't have any version control on them (or, if they do I don't know about it and would be happy to know how you do that). 

I could do backups/restore, but it'd be cool if we could just quickly clone and test. I dunno if it would even need to be ability to merge any of these changes back into the original app, but that would be cool too.  

So instead of only having just `http://myapp.kbox`, also have `http://myapp-fork1.kbox`, `http://myapp-fork2.kbox.com`, etc. 

Obviously running a bunch of forks simultaneously on one system would be a bad idea as far as system resources go, so that might need to be thought through a little bit more, but just wanted to put this on the table and see what you thought about it.

**Comment by pirog** [comment]
@WidgetsBurritos so this is an interesting proposal and here are my initial thoughts on it.

  > This feature is a *big* feature 

  > `kbox fork` plus Pantheon multidev seems like it would be pretty confusing.
  
  > Without multidev you can still pull the same dev environment multiple times and just use naming conventions to get multidev-like-functionality ie `dev-master`, `dev-feature2` Of course you would have to create and switch branches manually. Does this not get you pretty close to what you would want?

> A lot of what you are describing seems better suited for a CI environment like Travis or a canonical "integration" branch which, on pantheon anyway, would be the dev branch. 

> Because we are using containers i think you can probably run a bunch of forks simultaneously and be ok unlike if this were with multiple VMs

> So, you CAN actually put the entire app directory under version control and throw it up on github if you want. This is useful if you have a custom app that diverges from stock or pantheon apps. Then someone else can pull it down and run `kbox start` on it and it should load up and show in the GUI.

All this said, i think there are a few things in here that could be useful individual features such as 

1. Exporting and importing sites/backup/databases
2. Easier modification and control of app files like `kalabox-compose.yml`

**Comment by WidgetsBurritos** [comment]
Yeah I have no doubt this is a large feature. I just figured I'd throw it out there. 
Those are some good pointers.  I'll look em over and see what works for me.  

Apart from that, I do think those two features would be good features to add.

**Comment by pirog** [comment]
To clarify by "those two features" do you mean 

> 1. Exporting and importing sites/backup/databases
> 2. Easier modification and control of app files like kalabox-compose.yml

?

**Comment by WidgetsBurritos** [comment]
Yeah sorry.  I was working on multiple things so I probably wasn't being as clear as I needed to be
