### ISSUE TITLE
Syncthing sync interval is being set to 3600, causing it to appear to be broken

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#1199]
This is a hard one to reproduce on my end, so not sure what can actually be done about it, unless the log files can give you enough context.  

Every once in a while syncthing just stops syncing. I can't exactly pinpoint anything in particular that causes it to happen.  I usually notice when `kbox git commit` tells me there aren't any changes when I know there should be. 

The `syncthing-stderr.log` has nothing in it. 

Here is some hopefully relevant info from `syncthing-stdout.log`:

> [GEJLA] 13:07:02 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
> [GEJLA] 13:07:02 INFO: Local discovery (broadcast writer): write udp4: network is down
> [GEJLA] 13:08:02 INFO: Restarting
> [GEJLA] 13:08:02 OK: Exiting
> [monitor] 13:08:02 INFO: Syncthing exited: exit status 3
> [monitor] 13:08:03 INFO: Starting syncthing
> [GEJLA] 13:08:04 INFO: syncthing v0.11.26 "Aluminium Ant" (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-10-02 06:08:07 UTC
> [GEJLA] 13:08:04 INFO: My ID: GEJLAYA-YGXGC2Y-J3FFUGO-VUHE6NI-OXNAM6F-ZAEFEAA-JBLHZXY-DQ7XZQN
> [GEJLA] 13:08:04 INFO: Database block cache capacity 65536 KiB
> [GEJLA] 13:08:05 OK: Ready to synchronize greenpawup (read-write)
> [GEJLA] 13:08:05 INFO: Starting web GUI on http://0.0.0.0:60008/
> [GEJLA] 13:08:05 INFO: Starting local discovery announcements
> [GEJLA] 13:08:05 INFO: Device GEJLAYA-YGXGC2Y-J3FFUGO-VUHE6NI-OXNAM6F-ZAEFEAA-JBLHZXY-DQ7XZQN is "Davids-MacBook-Pro.local" at [dynamic]
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 is "SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7" at [10.13.37.100]
> [GEJLA] 13:08:05 INFO: API listening on [::]:60008
> [GEJLA] 13:08:05 INFO: Established secure connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 at 10.13.37.1:60515-10.13.37.100:22000
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 client is "syncthing v0.11.26"
> [GEJLA] 13:08:05 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 name is "bdb37ebc48df"
> [GEJLA] 13:08:11 INFO: Completed initial scan (rw) of folder greenpawup
> [GEJLA] 13:08:15 INFO: No UPnP device detected
> [GEJLA] 13:26:20 INFO: Connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 closed: read tcp 10.13.37.100:22000: connection reset by peer
> [GEJLA] 13:26:36 INFO: Established secure connection to SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 at 10.13.37.1:61036-10.13.37.100:22000
> [GEJLA] 13:26:36 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 client is "syncthing v0.11.26"
> [GEJLA] 13:26:36 INFO: Device SOBIINK-IS2QZRK-KA23NPY-BUE6XRG-ZYUQ363-HXM2JEB-YPDNVQK-YGLIUQ7 name is "bdb37ebc48df"

I'm pretty sure `13:26` was around the time it stopped working, but I don't know for sure, as it took me a few minutes to discover it was no longer syncing. 

I'm currently running: `0.12.0-alpha.18`

I've also attached some lines from the `kalabox.log` file from around that time period, if that provides any additional context. (Note: my GMT offset is -5 hours as I'm in CDT)

Fortunately, If I run `kbox restart` everything goes back to normal, so I have a solution, but just figured I'd make you aware of it.

**Comment by WidgetsBurritos** [comment]
Sorry I uploaded the wrong portion of the log file. This should be the correct part. 
[kbox.txt](https://github.com/kalabox/kalabox/files/205167/kbox.txt)

**Comment by WidgetsBurritos** [comment]
This might be related to #998 and/or #1149, so I'm gonna close this and move my comments elsewhere.

**Comment by WidgetsBurritos** [comment]
Per @pirog in #1149, this is actually a separate issue, so I'm reopening this issue, and copying in the necessary resources. 

It appears the rescan interval is randomly getting set to "3600" instead of "2" which it should be.  

<img width="578" alt="screen shot 2016-04-10 at 12 43 01 am" src="https://cloud.githubusercontent.com/assets/5263371/14408331/d5e23f1c-feb5-11e5-9460-fe8870d324c0.png">

<img width="1188" alt="screen shot 2016-04-10 at 12 46 15 am" src="https://cloud.githubusercontent.com/assets/5263371/14408333/d5e73f94-feb5-11e5-98aa-18ee843d9871.png">

**Comment by pirog** [comment]
So given tradeoffs lets do something like this

- [ ] Hardcode the sync intervals to 2 seconds
- [ ] Keep the old code to revisit at some point
