### ISSUE TITLE
GUI - Possible problem pulling large files directory on `kbox create pantheon`

### ISSUE THREAD

**Issue by jpmcneal** [kalabox/kalabox#1203]
When I created a new site today via the GUI, I got a 500 error after visiting the URL. I poked around a bit and noticed that my files folder was empty. I then stopped the app and did a ```kbox pull``` on the command line. Here's my output:
> jp@JPs-MacBook-Pro:~/.kalabox/apps/nameofmyapp$ kbox pull
? Which database backup do you want to use? dev
? Retrieve latest DB instead of most recent backup? (y/N) No
? Which files do you want to use? dev
Pulling screenshot.
Downloading: [13.1%] ...4320-53a6-7cc8-c0f9-133a29b85f2b_dev.png
Pulling code.
Cloning into '.'...
Warning: Permanently added '[codeserver.dev.b5c64320-53a6-7cc8-c0f9-133a29b85f2b.drush.in]:2222,[192.237.160.102]:2222' (RSA) to the list of known hosts.
remote: Counting objects: 312149, done.
remote: Compressing objects: 100% (65553/65553), done.
remote: Total 312149 (delta 215728), reused 310569 (delta 214836)
Receiving objects: 100% (312149/312149), 91.35 MiB | 3.81 MiB/s, done.
Resolving deltas: 100% (215728/215728), done.
Checking connectivity... done.
Pulling database.
Pulling files.
tar: can't open '-C': No such file or directory

I found a workaround by simply downloading the files manually from Pantheon and putting them in ```~/.kalabox/apps/nameofmyapp/files```

The files folder is pretty big (2.31 GB) ... maybe something errors out if there are a ton of files?

**Comment by jpmcneal** [comment]
Update: I created another site and it worked fine. The files are much smaller (207.2 MB) but I'll try to see if there's anything else different on the site that's failing.

**Comment by pirog** [comment]
@jpmcneal yeah i would def try the bigger site again (or another big site) and see if you can replicate. Let me know if you can and maybe you can share the site with me so i can try to troubleshoot it.

**Comment by jpmcneal** [comment]
I destroyed and recreated the app. This time I got an OSX error that my disk space was running low. Perhaps I just ran out of space the first time.

I'll try to clean up some disk space, upgrading the latest alpha, and try again. If that doesn't work then I'll look into sharing the project with you.

**Comment by labboy0276** [comment]
As a FYI, on alpha 3, there is this option now:
```
kbox create pantheon -- --nofiles
```

It creates the site with no files, which is nice.

**Comment by jpmcneal** [comment]
Sweet, thanks @labboy0276! I use stage_file_proxy so that will save me a ton of disk space.

**Comment by pirog** [comment]
Not sure if this is replicable yet so whomever tackles this should def start by trying to pull a large files/DB and see what happens.

**Comment by pirog** [comment]
No worries. 

So sounds like this might be a performance related issue re: the gui?

**Comment by pirog** [comment]
@jpmcneal 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!
