### ISSUE TITLE
Incorrect MIME Type on D8 aggregated stylesheet

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1204]
![unnamed](https://cloud.githubusercontent.com/assets/1153738/14328125/37a13808-fbea-11e5-86dd-ce82386b0f68.png)

**Steps to Replicate**

- Create stock D8 app in Pantheon
- Pull down in Kalabox

I wasn't able to replicate due to other environmental variable handling issues (described by @labboy0276 in #1193).

@chazchumley any other details?

**Comment by chazchumley** [comment]
I just tried a new site and now I get the following:

The website encountered an unexpected error. Please try again later.
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pantheon.router' doesn't exist: SELECT name, route FROM {router} WHERE name IN ( :names__0 ); Array ( [:names__0] => system.404 ) in Drupal\Core\Routing\RouteProvider->preLoadRoutes() (line 213 of core/lib/Drupal/Core/Routing/RouteProvider.php).

**Comment by pirog** [comment]
@chazchumley did you go through the install workflow on pantheon? For right now i think you an active DB on pantheon first.

**Comment by chazchumley** [comment]
@pirog Yes i Followed these steps.

1) spin up new site on Pantheon
2) click on the development site and continued installing - http://dev-f1-test.pantheonsite.io/
3) added initial commit message in Pantheon dashboard and switched into git mode
4) opened Kalabox and pulled down site

Got that error message locally

5) Repulled files and database using Kalabox

Same error

**Comment by pirog** [comment]
Hmmm weird. Its possible its not auto-creating a db backup for you. 

I would hold off on further Pantheon D8 investigations until we can get this sorted out + some better testing.

**Comment by reynoldsalec** [comment]
@pirog confirmed that a DB Backup wasn't created on Pantheon for my site and that creating a DB backup and pulling it got the site going (along with the changes in #1193.

**Comment by pirog** [comment]
Sweet. the DB BACKUP thing should be resolved by https://github.com/kalabox/kalabox/issues/745
