### ISSUE TITLE
`cgroup-lite` may not exist in Debian PPAz

### ISSUE THREAD

**Issue by mlncn** [kalabox/kalabox#1206]
I know, i know, but Ubuntu was my closest option.  I'm on Debian Mint LMBE 2 Cinnamon 64-bit, and i got:  "Error: Dependency is not satisfiable: cgroup-lite"

With full Lintian output:

> E: kalabox: unstripped-binary-or-object usr/lib/libnss_resolver.so.2
> W: kalabox: hardening-no-relro usr/lib/libnss_resolver.so.2
> E: kalabox: unstripped-binary-or-object usr/local/bin/kbox
> E: kalabox: embedded-library usr/local/bin/kbox: openssl
> E: kalabox: embedded-library usr/local/bin/kbox: zlib
> E: kalabox: embedded-library usr/local/bin/kbox: sqlite
> W: kalabox: hardening-no-relro usr/local/bin/kbox
> E: kalabox: arch-dependent-file-in-usr-share usr/share/kalabox/bin/docker
> E: kalabox: unstripped-binary-or-object usr/share/kalabox/bin/docker
> E: kalabox: embedded-library usr/share/kalabox/bin/docker: sqlite
> E: kalabox: statically-linked-binary usr/share/kalabox/bin/docker
> E: kalabox: arch-dependent-file-in-usr-share usr/share/kalabox/bin/docker-compose
> W: kalabox: hardening-no-relro usr/share/kalabox/bin/docker-compose
> E: kalabox: arch-dependent-file-in-usr-share usr/share/kalabox/gui/Kalabox/Kalabox
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: openssl
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: srtp
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: libpng
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: zlib
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: libxml2
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: libjpeg
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/Kalabox: sqlite
> E: kalabox: arch-dependent-file-in-usr-share usr/share/kalabox/gui/Kalabox/libffmpegsumo.so
> E: kalabox: unstripped-binary-or-object usr/share/kalabox/gui/Kalabox/libffmpegsumo.so
> E: kalabox: embedded-library usr/share/kalabox/gui/Kalabox/libffmpegsumo.so: libavutil
> E: kalabox: missing-dependency-on-libc needed by usr/lib/libnss_resolver.so.2 and 4 others
> E: kalabox: no-copyright-file
> W: kalabox: description-synopsis-starts-with-article
> E: kalabox: extended-description-is-empty
> W: kalabox: unknown-section default
> W: kalabox: non-standard-file-perm etc/default/kalabox 0664 != 0644
> E: kalabox: non-standard-file-permissions-for-etc-init.d-script etc/init.d/kalabox 0775 != 0755
> W: kalabox: non-standard-executable-perm etc/init.d/kalabox 0775 != 0755
> W: kalabox: non-standard-file-perm etc/init/kalabox.conf 0664 != 0644
> W: kalabox: non-standard-file-perm lib/systemd/system/kalabox.service 0664 != 0644
> E: kalabox: dir-in-usr-local usr/local/bin/
> E: kalabox: file-in-usr-local usr/local/bin/kbox
> W: kalabox: file-in-unusual-dir usr/local/bin/kbox
> W: kalabox: non-standard-file-perm usr/share/applications/kalabox-ui.desktop 0664 != 0644
> W: kalabox: extra-license-file usr/share/kalabox/docs/LICENSE.md
> W: kalabox: non-standard-file-perm usr/share/kalabox/docs/LICENSE.md 0664 != 0644
> W: kalabox: non-standard-file-perm usr/share/kalabox/docs/README.md 0664 != 0644
> W: kalabox: non-standard-file-perm usr/share/kalabox/docs/TERMS.md 0664 != 0644
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/icudtl.dat 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/libffmpegsumo.so 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/am.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ar.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/bg.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/bn.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ca.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/cs.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/da.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/de.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/el.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/en-GB.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/en-US.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/es-419.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/es.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/et.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/fa.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/fi.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/fil.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/fr.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/gu.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/hi.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/hr.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/hu.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/id.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/it.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/iw.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ja.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/kn.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ko.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/lt.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/lv.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ml.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/mr.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ms.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/nl.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/no.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/pl.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/pt-BR.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/pt-PT.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ro.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ru.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/sk.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/sl.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/sr.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/sv.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/sw.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/ta.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/te.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/th.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/tr.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/uk.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/vi.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/zh-CN.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/locales/zh-TW.pak 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/gui/Kalabox/nw.pak 0775 != 0755
> W: kalabox: non-standard-file-perm usr/share/kalabox/kalabox.png 0664 != 0644
> W: kalabox: non-standard-executable-perm usr/share/kalabox/scripts/bridgeup 0775 != 0755
> W: kalabox: non-standard-executable-perm usr/share/kalabox/scripts/daemonup 0775 != 0755
> E: kalabox: postrm-contains-additional-updaterc.d-calls etc/init.d/kalabox
> W: kalabox: script-in-etc-init.d-not-registered-via-update-rc.d etc/init.d/kalabox
> W: kalabox: file-missing-in-md5sums usr/share/doc/kalabox/changelog.Debian.gz
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/it.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/hi.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/mr.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/fa.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/id.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/fil.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/kn.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/es.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ta.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/am.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/tr.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/el.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/sl.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/iw.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/da.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/zh-CN.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/et.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/bg.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ml.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/es-419.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/hr.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/nw.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ko.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/zh-TW.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/sw.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/bn.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/pt-BR.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/sk.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/lt.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/hu.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/te.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/pl.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/th.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/vi.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/uk.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/fr.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/sr.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ro.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/sv.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/gu.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/nl.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ja.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ms.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ru.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/fi.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/cs.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/icudtl.dat
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/pt-PT.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/en-GB.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/en-US.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ca.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/no.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/lv.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/de.pak
> W: kalabox: executable-not-elf-or-script usr/share/kalabox/gui/Kalabox/locales/ar.pak
> W: kalabox: maintainer-script-empty preinst
> W: kalabox: maintainer-script-ignores-errors preinst
> W: kalabox: command-with-path-in-maintainer-script postinst:13 /sbin/initctl
> E: kalabox: sharedobject-in-library-directory-missing-soname usr/lib/libnss_resolver.so.2
> E: kalabox: shlib-with-executable-bit usr/share/kalabox/gui/Kalabox/libffmpegsumo.so 0775
> W: kalabox: maintainer-script-calls-systemctl prerm:11
> W: kalabox: maintainer-script-calls-systemctl prerm:12
> W: kalabox: maintainer-script-calls-systemctl postinst:20
> W: kalabox: maintainer-script-calls-systemctl postinst:21
> 
> Lintian finished with exit status 1

**Comment by pirog** [comment]
Should still work on Ubuntu. What version do you have?

**Comment by pirog** [comment]
@mlncn Do you know what the equivalent package for `cgroup-lite` is for your OS? 

We can definitely add a check to make sure its checking for the correct dep if you are using debian PPAz

**Comment by mlncn** [comment]
Not sure but i have this:

cgroup-tools 0.41-6

"Control Groups (cgroups) provide a mechanism for aggregating/partitioning sets of tasks, and all their future children, into hierarchical groups with specialized behaviour.

libcgroup allows one to manipulate, control, administrate and monitor cgroups and the associated controllers."

Homepage: http://libcg.sourceforge.net/

Looks like Docker itself had this problem: https://github.com/docker/docker/issues/2990
Note that [cgroup-tools](https://packages.debian.org/jessie/mips/cgroup-tools) replaces [cgroup-bin](https://packages.debian.org/jessie/mips/cgroup-bin) by Debian 8.

And if some init scripts are used, that seems to be something that cgroup-lite has but cgroup-bin, at any rate, did not have, and will have to be provided for: http://stackoverflow.com/a/21412154/1028376
