### ISSUE TITLE
GUI - Push/Pull always includes DB and Files?

### ISSUE THREAD

**Issue by JQTNguyen** [kalabox/kalabox#1207]
Whenever I do a GUI Push/Pull, it always seems to include DB and Files, even if I specify that it shouldn't.  

I'm not sure if this is just something that the GUI always "has" to display (i.e.: it runs a check of "DB yes/no?", and shows a message about DB being pushed/pulled regardless of the selected option), but in the case of Files, it does appear to be the case that it's always pushing/pulling, as the GUI always hangs there, and displays a message of pushing/pulling Files for hours.

The site in question that I'm working on has, like, 10GB of Files, so it's totes obvious when it's happening... X_x

**Comment by pirog** [comment]
@JQTNguyen thanks for the feedback here. This issue actually should be resolved in the latest version. 

We are also including some new options on create to mitigate the pull craziness 
![image](https://cloud.githubusercontent.com/assets/713424/14405322/005b4dd0-fe41-11e5-9b69-4de4ba2095f1.png)
