### ISSUE TITLE
Unable to destroy apps when errors occur

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1212]
When an app isn't installed correctly or otherwise encounters an error that is unrecoverable, it's often impossible to uninstall the app.

Investigating the app destruction process and finding if there are ways we could shortcut it to create a very basic "force" destroy function would be helpful when users encounter these types of scenarios, so at least they have an option.

Such a function would...

- Destroy any containers related to the app (perhaps just a name-based search could be done?)
- Delete the app from the app registry

Need for this is definitely debatable; but I think this could be handy when people have legacy apps that can no longer function with core changes.

**Comment by pirog** [comment]
This might tie in well to some sort of force remove/force cancel feature
that i think @madeofpeople created an issue for somewhere
