### ISSUE TITLE
Point legacy links to kalabox.io

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1217]
We have quite a few references to older Kalabox resources that are out-of-date. Pointing people to the correct resources will be very important to prevent confusion when googling for help.

- [x] Pages on Kalawiki
- [ ] Legacy blog posts by Kalamuna?
- [ ] Comment on posts or contact anyone who has done legacy posts in the past to provide new site links.

**Comment by pirog** [comment]
@reynoldsalec is this done? if so, please cloze.

**Comment by reynoldsalec** [comment]
We should give it another once-over @pirog, but did update the Kalawiki and did a quick review of the other items.
