### ISSUE TITLE
Create a failing test for "multiple host only adapter" issue on OSX and see if docker-machine 0.7 resolves it

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1220]

**Comment by reynoldsalec** [comment]
Our hope is that the new release of docker-machine may resolve this issue.

**Comment by pirog** [comment]
If not i think there are things we can do to get around this.

**Comment by pirog** [comment]
- [ ] Let's create an additional issue if we require more work here.

**Comment by pirog** [comment]
Ok i can def make a test that fails for this. Its very stubbed out for now but the gist is this

```bash
#
# Check that we can install Kalabox when there are duplicate
# host only adapters.
#
# See: https://github.com/kalabox/kalabox/issues/1220
#
@test "Install Kalabox with duplicate host-only adapters" {

  # Spec it out
  vboxmanage hostonlyif create
  vboxmanage hostonlyif create
  vboxmanage hostonlyif ipconfig --ip 10.76.34.2 --netmask 255.255.255.0 vboxnet3
  vboxmanage hostonlyif ipconfig --ip 10.76.34.2 --netmask 255.255.255.0 vboxnet4

  # Run our uninstaller first just in case
  kbox-uninstall

  # Run the install
  kbox-install

  # Verify the install
  kbox-verify-install

}
```

**Comment by pirog** [comment]
Here is the actual test 
https://github.com/kalabox/kalabox/commit/2fb166d95a4da2518f74e35414b93ea913bbc371

**Comment by pirog** [comment]
@reynoldsalec i can recreate this but sadly upgrading `docker-machine` `0.7.0.` does not resolve the issue.

Further, and also more sadly, because this happens when *ANY* adapter has a duplicate i dont think we can take action on our end like we could have if the issue were just our `10.13.37.1` adapter having a duplicate.

Maybe the best thing to do here is documentation in the troubleshooting section? 

Because this issue was tied to wrapping the installer testing framework, im going to backlog this issue
and create another issue that deals with that and the above documentation

**Comment by pirog** [comment]
Here is the issue for finishing installer framework
https://github.com/kalabox/kalabox/issues/1267

Here is the issue for documenting the HOA 
https://github.com/kalabox/kalabox/issues/1268
