### ISSUE TITLE
Files not pulled on app create  in v 0.12.11

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1225]
Using the latest alpha gui, when i pull a site for the first time from Pantheon to create the app the files are not pulled. 

.kalabox/apps/myappname/files

however, if i run a pull from the kbox gui after app creation the files are downloaded and available as expected.

**Comment by jpmcneal** [comment]
@break9 How large is your files folder? If it's 2GB (ish) it may be the same as  #1203.

**Comment by break9** [comment]
just a small logo.jpg file

**Comment by break9** [comment]
seems to be resolved in alpha 3

**Comment by break9** [comment]
fixed cannot reproduce

**Comment by break9** [comment]
this appears to be back in the kalabox BETA, at least for me.

**Comment by break9** [comment]
this happened after Installed BETA and launched kalabox. When i restarted kalabox and downloaded apps the files were downloaded as expected.
