### ISSUE TITLE
Internal DB Connection Info for Stock Apps

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1230]
The connection info modal currently shows connection strings to connect to the DB from outside the containerized environment.

We've now added connection string info to the CLI core for connecting to the DB container inside the containerized environment. This is important in the case of stock D7 apps, since stock Drupal 7 doesn't allow for setting DB connection info via environmental variables. In these cases, the user needs to know the internal DB credentials so the appserver may contact the db container.

- [ ] Add info into the connection modal
- [ ] Add documentation on difference between internal/external data
- [ ] Add documentation on spinning up stop D7, D8, Wordpress, and Backdrop apps.

**Comment by reynoldsalec** [comment]
![screen shot 2016-04-25 at 12 05 11 am](https://cloud.githubusercontent.com/assets/1153738/14776163/6d591914-0a79-11e6-9092-3cb18f4d2357.png)

We'll want to do break this info out of the modal soon, getting pretty convoluted. Suggestions on wording are also welcome @pirog.

**Comment by pirog** [comment]
Just adding `internal` or `external` before these things might help. I know a few providers, namely media temple, that list their stuff this way.

definitely +1 on figuring out a better way to display this stuff, seems like a good place for site detail cards?
