### ISSUE TITLE
Error in file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/sidebar/sidebar.js:219

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1231]
## Error in Kalabox

**Error** in **file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/sidebar/sidebar.js:219**
Cannot read property 'toLowerCase' of undefined

[View on Bugsnag](https://bugsnag.com/kalabox/kalabox/errors/570d3d5106f61908ebb60cb7?event_id=570d464027f6e6053631c4e6)

## Stacktrace

    file:///Applications/Kalabox.app/Contents/Resources/app.nw/src/modules/sidebar/sidebar.js:219 - none

[View full stacktrace](https://bugsnag.com/kalabox/kalabox/errors/570d3d5106f61908ebb60cb7?event_id=570d464027f6e6053631c4e6)

**Comment by reynoldsalec** [comment]
The issue here is no validation to ensure a name has been chosen for the Pantheon app. Related to #1177

**Comment by pirog** [comment]
Closing as duplicate of #1177
