### ISSUE TITLE
Recreating an app using the name of a previously deleted app can cause 500 internal server error

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1232]
create app from Pantheon. app installs without error. view local site in browser and i get the nginx 500 internal server error

**Comment by rovo79** [comment]
I'm having the same issue.

**Comment by pirog** [comment]
Is this effecting all your sites or just one?

On Tuesday, April 12, 2016, Robert Dean <notifications@github.com> wrote:

> I'm having the same issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1232#issuecomment-209193795>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by break9** [comment]
i deleted the app **completely** from the .kalabox/app folder re-created it and now it is working.

**Comment by pirog** [comment]
Hmm ok. I wonder if the issue here is recreating a site that already existed without first removing that site from the filesystem?

**Comment by jdleonard** [comment]
I also ran into this upon installing alpha3 (0.12.0-alpha.22) on top of alpha2. Uninstalling and re-installing alpha3 resolved the issue for me.

**Comment by pirog** [comment]
Is everyone who is getting this getting this from a previously installed kalabox?

**Comment by rovo79** [comment]
I had it installed a long time ago(over a year ago), but had uninstalled it. It seemed like there had been a lot of updates to it recently, so I figured I'd give it another try.

**Comment by break9** [comment]
i installed from the previous version

**Comment by pirog** [comment]
@rovo79 were you able to resolve these issues after wiping the previous version and reinstalling?

**Comment by break9** [comment]
only by renaming the app

**Comment by reynoldsalec** [comment]
Proposed solution is deleting the entire app directory on app destroy.

In the past there were permission issues that made this difficult, but now we should be able to do this. @rileysaurus will investigate to see if that's possible by...

1. Spin up a stock D8 site
2. Insert DB credentials
2. After you've inserted DB credentials in the Drupal installation process, Drupal should write settings.php. In the past, permissions around this file have presented issues with removing the directory.
3. Try deleting the app. See if the directory can be removed.

Only other question is if people expect the app directory to still be around, but it seems the dominant expectation has been that the entire app directory should be deleted.

**Comment by rovo79** [comment]
I do have it working now. Now I’m struggling to get Gulp and BrowserSync to work with it. Struggling to set the correct Host/Proxy.

Also, I might be mistaking this, but it seems to be very demanding on my MacBook Pro.

**Comment by rileysaurus** [comment]
@reynoldsalec @pirog I'm able to recreate this problem, and Mike was correct that everything in the folder is owned by the host user, however settings.php and the folders it's in have read only permissions.

So we could 'chmod -R +w <dir>' then rim raf the directory to get this to work.

**Comment by pirog** [comment]
@rovo79 i would create another issue re: gulp if you think that is appropriate

**Comment by thiagodemellobueno** [comment]
@rovo79 - I was wondering if you ever resolved your gulp issues?
Were trying to get it up and running with grunt (same same) but having some issues re: proxies as well.

**Comment by pirog** [comment]
CReating this placeholder metaissue for people to land on re: front end dev
https://github.com/kalabox/kalabox/issues/1573

**Comment by rovo79** [comment]
@thiagodemellobueno unfortunately I did not. I've just gone for a vanilla local dev environment.

**Comment by shawnmmatthews** [comment]
Hey all, has anyone figured out the proxy issues with gulp/grunt yet? I'm trying to get browsersync running as part of my gulp tasks, but am striking out left and right. My proxied mysite.kbox at mysite.kbox:3000 or browsersync's 172.17.0.17:3000 fails to resolve. 

PS excellent work on Kalabox Latest Dev @pirog. The Docker for Mac version runs circles around the earlier 2.* versions

**Comment by pirog** [comment]
@shawnmmatthews hoping to get a blog post out about using this stuff soon. 

thanks! we think its a lot better too!
