### ISSUE TITLE
Kalabox Drush No Drupal site found

### ISSUE THREAD

**Issue by rovo79** [kalabox/kalabox#1234]
Hello,

I imported a Drupal 7 site from my Pantheon environment, and named the Kalabox app _mobile_.

I'm having trouble running Drush commands from within:
/.kalabox/apps/mobile/code/

When I try to run _drush updb_, I receive this error:
No Drupal site found, only 'drush' cache was cleared. 

Should my Drupal settings.php DB connection match what Kalabox says for the DB Connection Info? I've updated settings.php to match this but still not working. I'm thinking Drush might be having trouble with the /.kalabox/ path?

Results of Drush Status:
Drupal version         :  7.41                                            
 Site URI               :  http://default                                  
 Database driver        :  mysql                                           
 Database hostname      :  mobile.kbox                                     
 Database port          :  32792                                           
 Database username      :  pantheon                                        
 Database name          :  pantheon                                        
 PHP executable         :  /usr/local/bin/php                              
 PHP configuration      :  /usr/local/etc/php/5.5/php.ini                  
 PHP OS                 :  Darwin                                          
 Drush script           :  /usr/local/Cellar/drush/7.0.0/libexec/drush.php 
 Drush version          :  7.0.0                                           
 Drush temp directory   :  /tmp                                            
 Drush configuration    :                                                  
 Drush alias files      :  /Users/rob/.drush/pantheon.aliases.drushrc.php  
 Drupal root            :  /Users/rob/.kalabox/apps/mobile/code            
 Site path              :  sites/default               

Kalabox DB Connection Info:
Host: mobile.kbox
Username: pantheon
Password: pantheon
Port: 32792
DB Name: pantheon

Greatly appreciate any help. 
Thanks

**Comment by pirog** [comment]
are you running `drush` or `kbox drush`?

**Comment by rovo79** [comment]
I’m running ‘drush’.

**Comment by pirog** [comment]
If you want to use your local drush you will likely need to set up your own
alias files or specify correct DB creds in settings.php.

It is recommended to use the tools we ship with kalabox or `kbox drush` in
this case. If you go inside your app directory and run `kbox` you'll see a
list of these.

**Comment by rovo79** [comment]
That was it, missed the part on using 'box drush'.

**Comment by pirog** [comment]
Awesome! We should def provide better documentation around how to use the
built in `kbox` commands

**Comment by rovo79** [comment]
Thanks for the rescue!

**Comment by rovo79** [comment]
This might need to be a separate issue, but now I can't run 'box drush' successfully because of a constant Redis Class error?
PHP Fatal error:  Class 'Redis' not found in /code/sites/all/modules/redis/lib/Redis/Client/PhpRedis.php on line 9

I've disabled and uninstalled the Redis module, and still the error comes up.

**Comment by pirog** [comment]
This is a separate issue and likely not something to do with Kalabox since
it is specific to your Drupal site.

Usually redis config is set in your settings.php file so I would
investigate there first.

**Comment by rovo79** [comment]
Thank you! 

That was it actually. I had forgotten Redis was set in the settings.php. I was thinking the IF Environment would keep it from being an issue.

**Comment by pirog** [comment]
Makes sense.

For a little more background. If you are pulling from Pantheon we are
actually setting up a PANTHEON LIKE environment locally for you to use. So
everything local should work the same as it does on Pantheon INCLUDING any
usage of PANTHEON's ENVVARS.

**Comment by craigandtammy** [comment]
I am actually getting the error while using the kbox prefix command

Craigs-rMacBookPro-8:code craigbertrand$ kbox drush cc all
No Drupal site found, only 'drush' cache was cleared.                                                                                      [warning]
Craigs-rMacBookPro-8:code craigbertrand$ pwd
/Users/craigbertrand/.kalabox/apps/agile/code

**Comment by pirog** [comment]
two important things to consider there

1. I'm not `positive` that `drush cc all` is a thing in Drush 8/Drupal 8
2. If your site does not have a `settings.php` drush is not going to work. If you run `kbox drush status` it will definitely give you some details on your situation. 

Beyond that we test drush pretty thoroughly so the *most likely* scenario is that there is something wrong with the way your drupal site is set up. IF YOU DO NOT THINK THIS IS THE CASE please add steps to replicate.

**Comment by craigandtammy** [comment]
Yeah it was the settings.php thing. I assumed pantheon did not use that file since they didn't put it in?

Thanks for the help.

I am now looking on pantheon to see if I need to ignore that new settings.php file with drupal 7 or send it back up to pantheon.
https://pantheon.io/docs/settings-php/
Seems like it is suggested, not sure why they don't add it when they set up the site.

**Comment by pirog** [comment]
Might be worth opening up an issue on their end. I suspect they have a good
reason for it. Similarly it would be great for DRUSH to not require it if
it doesnt need it.

**Comment by craigandtammy** [comment]
I appreciate the help.

kalabunga dude!

Really loving kalabox!
