### ISSUE TITLE
Local sites in browser display newly created app only

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1235]
1. open kalabox application on mac. needs to have an existing kbox app (app A). 
**do not start the existing (app A) kbox app.** 
2. create (download) a new pantheon app (app B).  - works
3. click on the newly created app (app B) thumbnail in kbox gui to visit local site. (works)
4. start the existing app (app A) via kbox gui. (appears to work??)
5. click on the app (app A) thumbnail to visit the local site. (URL is correct but app B is displayed)

if the apps exist when you start kalabox, then you start each app, they behave as expected.

**Comment by pirog** [comment]
@rileysaurus lets just try to see if we can recreate this and if we can lets bump to backlog for next sprint.

**Comment by rileysaurus** [comment]
@pirog I'm not able to recreate this. Tried using two pantheon apps, two stock drupal apps, and even one of each, but was not able to recreate.

**Comment by pirog** [comment]
Sounds good @rileysaurus, i'll backlog this and move it out of the sprint until we get more info

**Comment by rileysaurus** [comment]
I was able to recreate this on Windows 10 using a pantheon site and a stock drupal8 site. Restarting the pantheon site caused the issue to go away.
