### ISSUE TITLE
Set up testing framework and instructions for `kalabox_cli*` projects

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1238]
### General checklist

- [x] Get testing framework running correctly in TRAVIS
- [x] Get testing framework to run locally if its easy. If not, create an issue. 
- [x] Write a few example tests
- [x] Add documentation to CONTRIBUTION.md about where tests live, what kinds of tests we use, links to relevant documentation, instructions on submitting a test, how to run tests (https://github.com/pantheon-systems/terminus/blob/master/CONTRIBUTING.md for inspiration)
- [x] Providing routing back to kalabox/kalabox (document in README where to go)

### Testing framework specific stuff

- [x] Set up mocha framework
- [x] Clean up old tests directory

### Prioritize these unit tests
```
decode.riley(**require
**promise
init
**app

**util/asyncEvents
**util/serializer
util/docker/containerName -> ?
util/domain
util/download NaN bug
util/internet
util/log -> ?
**util/shell
**util/yaml

core/config
##core/deps
core/env
##core/events -> ?
##core/tasks)
```

**Comment by rileysaurus** [comment]
- [ ] -Make sure Promise.map isn't used incorrectly anywhere.
