### ISSUE TITLE
Set up testing framework and instructions for `kalabox_gui*` projects

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1240]
### General Checklist

- [ ] Get testing framework running correctly in TRAVIS
- [x] Get testing framework to run locally if its easy. If not, create an issue. 
- [ ] Write a few example tests
- [x] Add documentation to CONTRIBUTION.md about where tests live, what kinds of tests we use, links to relevant documentation, instructions on submitting a test, how to run tests (https://github.com/pantheon-systems/terminus/blob/master/CONTRIBUTING.md for inspiration)
- [ ] Providing routing back to kalabox/kalabox (document in README where to go)

### Specifically

- [x] Use protractor 
- [ ] Write a test to break the "no default name" (lowercase not defined error) when you create a pantheon site in the GUI

### Helpful things

Protractor setup on NW.js:
https://github.com/nwjs/nw.js/issues/2229
https://github.com/kalabox/kalabox-ui/issues/66

Get kalabox installed in CI:
https://github.com/kalabox/kalabox-app-pantheon/blob/v0.12/ci/travis-ci.sh (the GUI is somewhere in `/usr/share/kalabox`)

**Comment by reynoldsalec** [comment]
- [ ] add to current task to install webdriver
- [ ] figure out error finding chrome binary

**Comment by reynoldsalec** [comment]
@pirog + @rileysaurus 

Ok, running `grunt e2e` should work on your local Mac.

I haven't tried this on Travis, but I think we should be very close to having this work there as well. I believe the Linux binary paths in platform.json should be correct.

Note that the second test in dashboard.spec.js is written incorrectly and will fail.

Biggest failing: right now after tests have run the nw.js app will remain open. I was playing with something like this:

```
  browser.executeAsyncScript(function() {
    var appController = angular.element(document.body)
    .controller();
    console.log(appController);
    appController.quit();
  });
```

In the test to kill it, but now that I'm thinking about it I almost wonder if there'd be an easier way in the Grunt process, so we could be sure to kill the app after all tests are done running.

Hopefully this at least helps get a jumpstart on things, if you don't have time to get to furthering this I'll finish it up this weekend.

**Comment by pirog** [comment]
@reynoldsalec i updated the docs with some common copy we are using in the other repos.

I *think* its probably ok to wrap the rest of this up as part of specific issue we do next week if you dont have time to get back on it before then.
