### ISSUE TITLE
DB not pulled in v 0.12.14

### ISSUE THREAD

**Issue by break9** [kalabox/kalabox#1243]
when i run the action "pull" from the kbox gui for one of my pantheon apps with the option to pull the DB and the files, no errors are thrown but the DB is not updated.

I tried without creating a backup on pantheon and after creating a backup on pantheon.

**Comment by pirog** [comment]
What did you change on the dev site that you expected to see locally after
the pull?

**Comment by break9** [comment]
i added data to some panels

**Comment by pirog** [comment]
config or content change? something that could require a cache clear?

**Comment by break9** [comment]
content and content. tried several cache clears, no luck.

**Comment by pirog** [comment]
are you getting this on every site?

**Comment by break9** [comment]
no, unique to one site, so far

**Comment by break9** [comment]
when i ran `kbox pull` via the CLI for that app it updated as expected

**Comment by pirog** [comment]
Good to know. 

So in summary: Happens on some sites and only when pulling through GUI?

**Comment by break9** [comment]
i think it is because the site i was testing, existed in the Alpha 2. the other sites i tested (that worked) were never installed in alpha 2.
