### ISSUE TITLE
Error removing host "Kalabox2": open /var/root/.docker/machine/machines/Kalabox2/config.json: permission denied

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1244]
- Version: Kalabox 0.12 alpha3 on Mac OS X
- Previous Kbox?: All users have had previous versions of Kalabox installed.
- Project: kalabox (installer)
- Expected Behavior: To completely uninstall the previous Kalabox2 virtual machine
- Actual Behavior: 

Upon running uninstall.tool, produced error "Error removing host "Kalabox2": open /var/root/.docker/machine/machines/Kalabox2/config.json: permission denied". 

Attempts to install Kalabox after this error produced an error in install.log:

```
Apr 12 14:55:26 sticky-iMac installd[459]: ./postinstall: Host does not exist: "Kalabox2"
Apr 12 14:55:26 sticky-iMac installd[459]: ./postinstall: Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Apr 12 14:55:26 sticky-iMac installd[459]: ./postinstall: Host does not exist: "Kalabox2"
Apr 12 14:55:26 sticky-iMac installd[459]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.myLMWN/Scripts/io.kalabox.pkg.services.Sp8oeo
Apr 12 14:55:27 sticky-iMac installd[459]: ./postinstall: Host does not exist: "Kalabox2"
Apr 12 14:55:27 sticky-iMac installd[459]: ./postinstall: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
Apr 12 14:55:27 sticky-iMac installd[459]: ./postinstall: You might need to run `eval "$(docker-machine env default)"`
Apr 12 14:55:27 sticky-iMac installd[459]: ./postinstall: Something went wrong installing core Docker images
```

- Reproduce: I have been unable to reproduce, but both @worxco and @chhavi have experienced it.
- Documentation: We should add an FAQ on how to manually delete the Kalabox2 VM, but ideally finding a more fool-proof solution in the script will be the best resolution.

**Comment by pirog** [comment]
closing in favor of #1361
