### ISSUE TITLE
{userdocs} points to something other than like C:\Users\USERNAME\My Documents

### ISSUE THREAD

**Issue by ar-jan** [kalabox/kalabox#1245]
I'm trying out Kalabox for the first time, but I haven't got very far yet.

The installer download page mentions Win8+, but the [knowledge base](https://kalabox.freshdesk.com/support/solutions/articles/14000006306-installing-on-windows) says "Windows 7 and up".

- I'm on Windows 7 Enterprise SP1 - is this supported?
- I've installed Kalabox from the latest kalabox-v0.12.0-alpha.3.exe, to C:\Programs\Kalabox
- The installation completed without problems. When I first started the GUI from the shortcut on my desktop (to C:\Programs\Kalabox\Kalabox.exe), I got something like "Oops, it looks like you haven't installed Kalabox. After a restart I did not get this message, but just a screen saying "Loading" which goes on for many minutes. It doesn't look like anything was actually happening.
- `kbox version` from CLI gives 0.12.0-alpha.22
- `kbox create drupal8` gives the error below.

Anything else I can try, or things I could report?

> E:\>kbox create drupal8
> ? What will you call this monster you have created: d8
> Creating.
> Cleaning up.
> Cannot read property 'AuthOptions' of undefined
> TypeError: Cannot read property 'AuthOptions' of undefined
>     at C:\Programs\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\mac
> hine.js.jx:264:34
> From previous event:
>     at Object.getEngineConfig [as engineConfig] (C:\Programs\Kalabox\bin\plugins
> \kalabox-engine-docker\provider\docker\machine.js.jx:261:6)
>     at C:\Programs\Kalabox\bin\lib\engine.js.jx:57:23
> From previous event:
>     at C:\Programs\Kalabox\bin\lib\engine.js.jx:54:6
> From previous event:
>     at exports.provider (C:\Programs\Kalabox\bin\lib\engine.js.jx:52:4)
>     at verifyProviderInstalled (C:\Programs\Kalabox\bin\lib\engine.js.jx:108:12)
> 
>     at verifyProviderIsReady (C:\Programs\Kalabox\bin\lib\engine.js.jx:219:10)
>     at Object.exports.list (C:\Programs\Kalabox\bin\lib\engine.js.jx:354:10)
>     at C:\Programs\Kalabox\bin\lib\app.js.jx:429:34
> From previous event:
>     at Object.exports.cleanup (C:\Programs\Kalabox\bin\lib\app.js.jx:428:4)
>     at C:\Programs\Kalabox\bin\lib\create.js.jx:363:23
>     at process._tickCallback (node.js:917:13)
> From previous event:
>     at createApp (C:\Programs\Kalabox\bin\lib\create.js.jx:361:6)
>     at PromptUI.completed (C:\Programs\Kalabox\bin\lib\create.js.jx:497:16)
>     at PromptUI.onCompletion (C:\Programs\Kalabox\bin\node_modules\inquirer\lib\
> ui\prompt.js.jx:68:10)
>     at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Pr
> ograms\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx:1792:12)
>     at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onComple
> ted (C:\Programs\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.jx
> :1729:14)
>     at AnonymousObserver.tryCatcher (C:\Programs\Kalabox\bin\node_modules\inquir
> er\node_modules\rx\dist\rx.js.jx:566:29)
>     at AutoDetachObserverPrototype.completed (C:\Programs\Kalabox\bin\node_modul
> es\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
>     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
> eted (C:\Programs\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.j
> x:1729:14)
>     at InnerObserver.onCompleted (C:\Programs\Kalabox\bin\node_modules\inquirer\
> node_modules\rx\dist\rx.js.jx:3424:65)
>     at InnerObserver.tryCatcher (C:\Programs\Kalabox\bin\node_modules\inquirer\n
> ode_modules\rx\dist\rx.js.jx:566:29)
>     at AutoDetachObserverPrototype.completed (C:\Programs\Kalabox\bin\node_modul
> es\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
>     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
> eted (C:\Programs\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.j
> x:1729:14)
>     at AutoDetachObserver.tryCatcher (C:\Programs\Kalabox\bin\node_modules\inqui
> rer\node_modules\rx\dist\rx.js.jx:566:29)
>     at AutoDetachObserverPrototype.completed (C:\Programs\Kalabox\bin\node_modul
> es\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
>     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
> eted (C:\Programs\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.j
> x:1729:14)
>     at InnerObserver.onCompleted (C:\Programs\Kalabox\bin\node_modules\inquirer\
> node_modules\rx\dist\rx.js.jx:3424:65)
>     at InnerObserver.tryCatcher (C:\Programs\Kalabox\bin\node_modules\inquirer\n
> ode_modules\rx\dist\rx.js.jx:566:29)
>     at AutoDetachObserverPrototype.completed (C:\Programs\Kalabox\bin\node_modul
> es\inquirer\node_modules\rx\dist\rx.js.jx:5287:56)
>     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompl
> eted (C:\Programs\Kalabox\bin\node_modules\inquirer\node_modules\rx\dist\rx.js.j
> x:1729:14)

**Comment by pirog** [comment]
We do test on windows 7 professional and those tests all pass. do you know what differences there might be between that and Enterprise SP1?

As far as i can tell based on this it looks like the Kalabox VM is not being installed correctly. Can you verify that VirtualBox is installed and that it has a VM called Kalabox2 in it?

**Comment by ar-jan** [comment]
That's good to know. Virtualbox was installed together with Kalabox and it runs fine, but there are no VMs in it at all. I didn't see any errors during installation, though.

I don't know what exactly the differences are between Windows 7 Pro and Enterprise. Not sure if matters, I rather would've expected problems with e.g. network settings.

**Comment by pirog** [comment]
Interesting. That is definitely peculiar esp since the installer should have failed without the VM. 

I would try running the installer again. Afterwards there should be installer log files in your `TEMP` directory. I think the log files look something like `Setup.xxx`.

If you want to post those up here we can give them the ole look-see.

**Comment by ar-jan** [comment]
It looks like it may have something to do with permissions, and/or the fact that I'm on a domain network. (I do have local administrative privileges to install software).

Virtualbox expects the VMs in `C:\Users\myname\VirtualBox VMs`, but that folder does not exist.

I didn't find any logs for Kalabox (not in the install dir, or in `.kalabox` in the home dir). Any idea where they should be?

In `c:\Users\myname\.VirtualBox\VBoxSVC.log` I did find this:

> VirtualBox COM Server 5.0.16 r105871 win.amd64 (Mar  4 2016 16:28:58) release log
> 00:00:00.015600 main     Log opened 2016-04-20T08:49:58.050816000Z
> 00:00:00.015600 main     Build Type: release
> 00:00:00.015600 main     OS Product: Windows 7
> 00:00:00.015600 main     OS Release: 6.1.7601
> 00:00:00.015600 main     OS Service Pack: 1
> 00:00:00.031200 main     DMI Product Name: OptiPlex 9020
> 00:00:00.031200 main     DMI Product Version: 01
> 00:00:00.031200 main     Host RAM: 16289MB total, 13294MB available
> 00:00:00.031200 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
> 00:00:00.031200 main     Process ID: 1128
> 00:00:00.031200 main     Package type: WINDOWS_64BITS_GENERIC
> 00:00:00.031200          Home directory: 'C:\Users\myname/.VirtualBox'
> 00:00:00.031200          Installed Drivers:
> 00:00:00.031200            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 5.0.16.5871)
> 00:00:00.031200            C:\Windows\system32\DRIVERS\VBoxDrv.sys (Version: 5.0.16.5871)
> 00:00:00.031200            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 5.0.16.5871)
> 00:00:00.031200            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 5.0.16.5871)
> 00:00:00.046800          Loading settings file "C:\Users\myname/.VirtualBox\VirtualBox.xml" with version "1.12-windows"
> 00:00:00.187200          HostDnsMonitor: old information
> 00:00:00.187200            no server entries
> 00:00:00.187200            no search string entries
> 00:00:00.187200            no domain set
> 00:00:00.187200          HostDnsMonitor: new information
> 00:00:00.187200            server 1: 111.222.1.10
> 00:00:00.187200            server 2: 111.222.1.11
> 00:00:00.187200            search string 1: SUB.example.com
> 00:00:00.187200            search string 2: sub.example.com
> 00:00:00.187200            domain: SUB.example.com
> 00:00:00.187200          HostDnsMonitorProxy::notify
> 00:00:00.218400          VD: VDInit finished
> 00:00:16.042841 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0

(111.222.1.10 and 111.222.1.11 are the DNS servers of the Domain network).

**Comment by pirog** [comment]
@ar-jan the setup logs should be in your `TEMP` folder. This can differ per installation but if you open up a terminal and type `echo %TEMP%` i think it should spit out the location.

**Comment by ar-jan** [comment]
Oops, I missed that in your previous comment. [Here](https://gist.github.com/ar-jan/bea3ed743af8793393676ad6770001b7) are is the latest log. I had uninstalled Kalabox after previous installs (of the same version).

**Comment by pirog** [comment]
Hmm @ar-jan, i dont actually see anything useful in the log. 

It almost looks like Kalabox is not running the post install scripts to set up your VM but i am not sure why that would be. This is kind of annoying but you could try running our setup scripts directly and see what happens or if you get any relevant feedback.

To start, here is the script to set up the VM. I am pretty sure you want to run it as a regular user and not as an administrator. 
https://github.com/kalabox/kalabox/blob/v0.12/windows/engine.bat

That reminds me, are you running the install as an admin? If you open VB as an Admin do you see the Kalabox2 VM that way?

**Comment by ar-jan** [comment]
There was no difference opening VirtualBox as admin or not.

I tried the engine.bat, and I get `Docker Machine is not installed. Please re-run the Kalabox installer and try again.`

So I looked at the environment variables. I noticed that the KALABOX_INSTALL_PATH was listed as `\\NAS02\arjan\My Documents\..\.kalabox\bin`. Probably no difference, but I changed it to `\\NAS02\arjan\.kalabox\bin`. Is this the expected location (this is my home dir, on a network share), or should it be in the chosen install location? The Kalabox executable is in C:\Programs\Kalabox\bin.

I then added "\\NAS02\arjan\.kalabox\bin" to the PATH env.variable. Now `docker-machine` works from the command prompt, but the installer still returns the same message `Docker Machine is not installed`.

**Comment by pirog** [comment]
Hmmm interesting. This seems somewhat related to #1186. 

For all intents and purposes `\\NAS02\arjan\My Documents\..\.kalabox\bin` should be the same as `\\NAS02\arjan\.kalabox\bin`. I think the bigger issue might be that your home folder is on a network drive and kalabox is having trouble resolving that, specifically the `%USERPROFILE%` env. Is this set on your end?

**Comment by ar-jan** [comment]
The Windows installation and network environment are all managed by the IT department. Is there a specific configuration setting I could check for?

**Comment by pirog** [comment]
@ar-jan im not super familiar with how windows machines are deployed and configured in this way but my best *guess* is you would want to ask what the path is to your user's home folder.

**Comment by ar-jan** [comment]
`echo %USERPROFILE%` gives `C:\Users\arjan`, whereas the installer somehow uses the network location (which *is* indeed the location for e.g. %HOMEDRIVE%, and contains e.g. the MyDocuments folder). `C:\Users\arjan\.kalabox` did contain `logs` and `pantheon` folder, so it seems different (parts of) the programs use different environment variables, maybe? 

In any case, I tried just copying the contents of `\\NAS02\arjan\.kalabox` to `C:\Users\arjan\.kalabox`, and changed the KALABOX_INSTALL_PATH variable to that location as well. Next the engine.bat did run successfully, and I can now start Kalabox and create a (local) site.

**Comment by ar-jan** [comment]
Hm, still some problems left. Perhaps these are more general, but I didn't find an existing issue, it could also be related to the previous install problems.

First, when Kalabox ran correctly, I created a local D8 site from the Kalabox UI. This was succesful, except when I tried to visit it, I got "Server not found". After reading some other issues about similar problems, I tried closing everything and restarting.

After rebooting and starting Kalabox again, trying to enable the site gives `"Failed after 5 retries. {"max":5,"backoff":500}: : code: 1err:open C:\Users\arjan\.docker\machine\machines\Kalabox2\config.json: The system cannot find the file specified.`.

Trying to delete the site gives the same error, as does creating a new site.

**Comment by pirog** [comment]
@ar-jan ok that is really helpful and means this issue is very closely related to #1186 and likely also replicable. 

Regarding your [second comment](https://github.com/kalabox/kalabox/issues/1245#issuecomment-219732450) my guess is that your workaround is not working 100%. It might be best to focus on the issue in this issue focus. 

That said, what browser were you using to try and look at your site? I know that i've had problems with Edge.
