### ISSUE TITLE
uninstall.tool has to be renamed to uninstall.sh on Mac?

### ISSUE THREAD

**Issue by aristomenis** [kalabox/kalabox#1246]
Don't know if this came up already, so apologize if redundant, but for myself personally, on this latest download, I had to rename the included uninstall.tool to uninstall.sh to get it to work on my Mac (OSX El Capiton 10.11.14).

That's about all I got at the moment!

**Comment by aristomenis** [comment]
PS: Link for "uninstallation directions" on this page...

https://kalabox.freshdesk.com/support/solutions/articles/14000006360-installing-on-osx

... ends up on page that does not exist.

**Comment by pirog** [comment]
@aristomenis i think the link is fixed now.

re: script. I can't replicate that. Are you running it via a terminal or some other way?

**Comment by aristomenis** [comment]
Was running via terminal. Wouldn't work until I renamed the file to a .sh suffix. Maybe trippy setup on my end or something.

--
Aristomenis Capogeannis
about.me/capogeannis

**Comment by pirog** [comment]
Ok. I think we are going to 

- [ ] Rename this to .sh
- [ ] Update docs to reflect change

**Comment by pirog** [comment]
PR: https://github.com/kalabox/kalabox/pull/1316
