### ISSUE TITLE
make sure Promise.map with concurrency of 1 is not used anywhere incorrectly

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1249]
Make sure promise.map with concurrency of 1 is not used anywhere incorrectly. In this case it's better to use Promise.each so the ordering is going to be upheld.

**Comment by pirog** [comment]
@rileysaurus what are the consequences of not changing this?

**Comment by rileysaurus** [comment]
No instances of this being uses wrong found. @pirog RE: previous ping, Promise.map with a concurrency of 1 doesn't execute in guaranteed order, however Promise.each does.
