### ISSUE TITLE
Cannot add a Pantheon site: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by davidneedham** [kalabox/kalabox#1251]
I just wiped my computer and installed OS X 10.11.4 from scratch. I installed the latest Kalabox UI (Version 0.12.14) and my usual apps.

1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
5. DANGER WILL ROBINSON with the error "`Cannot read property 'toLowerCase' of undefined`".

I tried this for several sites, using different environments. I restarted Kalabox completely and tried again. This error still happens every time.

Does this bug prevent you from using Kalabox? YES

**Comment by pirog** [comment]
Hey David,

You need to give your site a name in the create form. It's the field at the
top. This happens when you do not.

**Comment by davidneedham** [comment]
Ah, right on. Not sure how I missed that!

In that case, consider this a request for documentation, or request for an error message that is more helpful. I did a search in the knowledge base for this error but it didn't find anything.

**Comment by pirog** [comment]
bad UX on our part :)

see for more things:
https://github.com/kalabox/kalabox/issues/1177
https://github.com/kalabox/kalabox/issues/1231

**Comment by amklose** [comment]
Perhaps when you go to add a site from Pantheon, the app name could default to whatever it is in Pantheon. Then the user would have the option to change it before clicking Submit.

I usually end up calling my app the same as it's named in Pantheon so this would be a shortcut and it would prevent people from getting the "toLowerCase" error mentioned above.

**Comment by reynoldsalec** [comment]
Thanks for the suggestion @amklose, we'll be implementing something similar to that in https://github.com/kalabox/kalabox/issues/1258
