### ISSUE TITLE
Create Documentation For Stock and Pantheon Apps

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1254]
**Please explain the reason for this feature request or enhancement**

As a developer, I want to have step-by-step instructions to easily install apps associated with Pantheon and ones that are not associated with Pantheon.

Documentation should bridge most the gap here, although more inline-queues (like separating the Pantheon/Stock apps in the GUI) could be helpful.

This is important to make sure everyone's first 10 minutes with Kalabox is a seamless experience.

**Comment by pirog** [comment]
As part of this lets change the readmes for all our projects on github so they link to external docs instead of providing potentially conflicting documentation. The docker projects all do a good job of this 

https://github.com/docker/machine
