### ISSUE TITLE
Implement app specific status message on backend

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1255]
Feature/Enhancement Request
===========================

Please explain the reason for this feature request or enhancement

> We want to display better progress to the user re: app actions

Please provide some detail on how Kalabox can help solve this problem

- [x] Increment progress by a reasonable/small amount when app receives a status message
- [x] We need to attach the status class to the app object and use that
- [x] Figure out how to handle stdout trolling re: app specificity 
- [x] Make sure progress goes to 100% for 1 - 2 seconds
- [x] Smooth out status messages so they are readable for 1 - 2 seconds

Why do you think it is important Kalabox include this new feature or enhancement?

> Because the people have a right to know WTFIGO

**Comment by rileysaurus** [comment]
Reopened to make improvements.
