### ISSUE TITLE
Implement app specific status message on frontend

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1256]
Feature/Enhancement Request
===========================

Please explain the reason for this feature request or enhancement

> We want to display better progress to the user re: app actions

Please provide some detail on how Kalabox can help solve this problem

- [ ] Switch the throbber to include some sort of progress indicator. 
- [ ] Display a truncated status message with a tooltip that contains the entire message

Why do you think it is important Kalabox include this new feature or enhancement?

> Because the people have a right to know WTFIGO

**Comment by rileysaurus** [comment]
This is now unblocked by [#1255]. Site objects will now have site.status and site.progress values.

- site.status is a string
- site.progress is a number between 0 and 1
