### ISSUE TITLE
Run drush and receive "Class 'Redis' not found in redis/lib/Redis/Client/PhpRedis.php on line 9"

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1259]
Bug Report
==========

**Tell us about your setup**

Kalabox v0.12.0-alpha3 on Mac OS

**Tell us about your bug**

Every time a Drush command is run, I receive the error "Fatal error: Class 'Redis' not found in /code/sites/all/modules/contrib/redis/lib/Redis/Client/PhpRedis.php on line 9"

After investigating it looks like that php5-redis isn't installed on the drush container, so when it bootstraps the PhpRedis.php client, it doesn't have access to the necessary php extension.

**Recreate the bug.**

1. Start GUI
2. Pull a Pantheon site w/Redis config setup
3. Try running `kbox drush status`

**Tell us more**

Quickfix was detailed in https://github.com/kalabox/kalabox-internal-issues/issues/45#issuecomment-211555185

The real fix will be to make sure the canonical drush container (or one of its upstreams) is updated to include the appropriate redis extension: 

- https://github.com/RobLoach/drush-docker
- https://hub.docker.com/r/drush/drush/

**Comment by reynoldsalec** [comment]
@pirog is following up with @robloach about upstream fixes for this issue. He will update this issue as we make progress.

**Comment by reynoldsalec** [comment]
Addressing in the drush-docker project: https://github.com/RobLoach/drush-docker/issues/22

**Comment by pirog** [comment]
@reynoldsalec do we want to move this into the current sprint?

**Comment by Mchampsee** [comment]
The quickfix link above goes to a page not found. Running into the same issue. Is there a way to remove redis from the local project? Turning the module off doesn't fix it.

**Comment by pirog** [comment]
You'll want to comment out relevant redis config in settings.php for now
