### ISSUE TITLE
"Loading" screen during GUI spin up is a little vague

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1260]
Feature/Enhancement Request
===========================

**Please explain the reason for this feature request or enhancement**

Expectations around Loading screen are not clear

**Please provide some detail on how Kalabox can help solve this problem**

Instead of "Loading" maybe say something like "Looks like the Kalabox engine is down... give us a few minutes to boot it up..."

**Why do you think it is important Kalabox include this new feature or enhancement?**

Because knowledge is power

**Comment by reynoldsalec** [comment]
https://github.com/kalabox/kalabox-ui/pull/215
