### ISSUE TITLE
Improve kalabox/cli to enable more powerful workflows

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1263]
**Story**

As a PHP developer with a workflow that includes npm-powered build tools, I want to be able to easily run my build workflow using Kalabox's containerized virtual environment so I don't need to worry about local dependency issues for myself and my teammates.

First step is making sure basic build workflows are easily installable via #1261 

Second step is giving power users more flexibility to include custom dependencies via #1174

**Comment by pirog** [comment]
@reynoldsalec it might be worth noting in relevant documentation somewhere that the *ideal* situation is for the developer to get `npm install` (or analogous install mechanism) to bring down all their needed dependencies but that this is not always possible for all things. 

### Examples:

**1. `npm install` requires some low level dep for a `node-gyp` build**

> Is a good candidate for either direct CLI inclusion or for customization via the Dockerfile

**2. `grunt test` requires the `nw` binary to run

> Is a good candidate for installation via `npm install`

**Comment by reynoldsalec** [comment]
@pirog made a reminder to improve this documentation: #1292

**Comment by pirog** [comment]
Awesome! thanks
