### ISSUE TITLE
Document how to workaround installs that fail because of a duplicate host only adapter

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1268]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

> v0.12.x+

What operating system are you using?

> All

Have you previously installed Kalabox? If so, what version?

> No

**Tell us about your bug**

Give a brief description of what happened

> https://github.com/docker/toolbox/issues/391

Can you recreate this bug?

> Yes
Please detail the steps we can take to replicate this bug. Be as detailed as possible.

>  https://github.com/kalabox/kalabox/blob/1220-testingPlusHOA/test/darwin/hoa.bats

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> Example: Yes

Does this bug prevent you from using Kalabox?

> Example: No

**Comment by pirog** [comment]
Another thing to consider here is whether we can print a message to the user during install that directs them to the correct documentation?

**Comment by reynoldsalec** [comment]
@pirog this work out?

**Comment by pirog** [comment]
certainly seems quite sufficient for now. we can def go over all the current docs in our doc meeting on thursday.
