### ISSUE TITLE
GUI picking up .DS_Store as a Pantheon account?

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1270]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

> Version 0.12.14

What operating system are you using?

> OSX El Capitan 10.11.4

Have you previously installed Kalabox? If so, what version?

> Yes, Alpha 2

**Tell us about your bug**

Give a brief description of what happened

> I just noticed in the GUI when I go to add an app from Pantheon, it's picking up the .DS_Store file as a separate Pantheon account. This is a file that OSX adds automatically. When I click on the .DS_Store pantheon link, I get an error message that says "Authentication failed. Please re-authenticate you Pantheon account."

Can you recreate this bug?

> Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 0. Be on a Mac and ensure that there's a .DS_Store file created in your ~/.kalabox directory
> 1. Started up GUI
> 2. Clicked on Add Site button on the right
> 3. .DS_Store shows up as a Pantheon account at the bottom of the list

<img width="233" alt="screenshot 2016-04-21 13 34 03" src="https://cloud.githubusercontent.com/assets/756265/14720385/d566c372-07c6-11e6-879d-6a0545fc8c46.png">

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> No

Does this bug prevent you from using Kalabox?

> No

**Comment by pirog** [comment]
LOL. thats great.

Any good sites in that account?

**Comment by pirog** [comment]
So let's just filter out all sessions that aren't email addresses for this.
