### ISSUE TITLE
UI regularly crashing on Ubuntu

### ISSUE THREAD

**Issue by leevh** [kalabox/kalabox#1271]
Bug Report
==========

What version of Kalabox are you using?

> v0.12.0-alpha3

What operating system are you using?

> Ubuntu 15.10 and 16.04

Have you previously installed Kalabox? If so, what version?

> Yes, 0.11.3

**Tell us about your bug**

Give a brief description of what happened

> Kalabox GUI randomly and regularly crashes, just closing down.  All sites remain working.  When GUI is restarted, all sites appear offline.  You can "start" them (although they are still running) and after a couple tries usually they will show as online and then its business as usual until next crash.  This is affecting my colleague as well.  Syslog said the following (which I assume is kbox related):

> daemonup[1988]: time="2016-04-22T14:17:06.329139778-07:00" level=debug msg="Client disconnected, stop sending events"

> I could provide any info from the apport crash report, just not sure what portions would be useful.  

Can you recreate this bug?

> No, seems random, mostly when not interacting with the GUI

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> No

Does this bug prevent you from using Kalabox?

> No

**Comment by pirog** [comment]
Hmmm we test on 14.04 and haven't seen this. 

Are there any obvious differences between 14.04 and what you are running that could cause this? Are you running any additional software or services that might interfere with how Kalabox is running?

**Comment by pirog** [comment]
@leevh this seems to work ok for me on 16.04

**Comment by leevh** [comment]
No longer an issue on beta1, closing.  thanks!!
