### ISSUE TITLE
Kalabox menu item does not show up in LXDE or XFCE desktop environments

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1272]
**bug fix**

**installer**

Setup:

What version of Kalabox are you using? v0.12.0-alpha3

What operating system are you using? LXLE 14.04 (fork of Ubuntu Trusty with LXDE)

Have you previously installed Kalabox? No

Bug:

Kalabox menu item does not show up in LXDE or XFCE desktop environments

Can you recreate this bug? Yes

Could better documentation have prevented this issue? No

Does this bug prevent you from using Kalabox? No

**Comment by uberhacker** [comment]
This bug can be fixed by editing /usr/share/applications/kalabox-ui.desktop and commenting or removing the OnlyShowIn=GNOME;Unity; line.  I propose this line be removed in future versions the installer.  It doesn't make much sense to limit, correct?  Also, my intuition told me to first look in the Programming category to find the Kalabox menu item.  It wouldn't hurt to add it under the Internet category also, right?  This can be accomplished as follows:

 Change the `Categories=Utility;` line to `Categories=Development;Network;Utility;` in /usr/share/applications/kalabox-ui.desktop.

**Comment by pirog** [comment]
+1 to these changes as well. 

I'm not sure what the initial reason was for restricting to GNOME only.

**Comment by bradchesney79** [comment]
KDE checking in... hope the fix is sufficient.

**Comment by pirog** [comment]
Awesome! Thanks for the contrib! Merged!
