### ISSUE TITLE
Prompt to stop apache or nginx service if using port 80 during installation?

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1273]
**bug fix**

**installer**

Setup:

What version of Kalabox are you using? v0.12.0-alpha3

What operating system are you using? LXLE 14.04 (fork of Ubuntu Trusty with LXDE)

Have you previously installed Kalabox? No

Bug:

Would it make sense to prompt to stop the apache or nginx service if using port 80 before attempting the installation to prevent corruption?

Can you recreate this bug? Yes

Could better documentation have prevented this issue? No, it's mentioned in the docs but you know...

Does this bug prevent you from using Kalabox? No

**Comment by pirog** [comment]
Yeah i think this is a good call. Just to be clear you are proposing something like 

1. Before installation on NIX run a check to see if port 80 is in use
2. Warn user they cannot continue until they unbind 80
3. Possibly link to relevant documentation?

**Comment by uberhacker** [comment]
@pirog: Exactly what I was suggesting.  If they are not wanting to stop services running on port 80, then just abort the installation.  BTW, excellent work on this new release.  It is A LOT better than the previous release.

**Comment by pirog** [comment]
Thanks Ed! We are hoping alpha4 will be a similar leap forward!

**Comment by uberhacker** [comment]
I would like to add an additional note on this issue.  It would also be nice if Kalabox is already installed and you currently have a service running on port 80 and you try and launch a site if it could prompt to stop the service in this scenario as well.  Just a thought.

**Comment by AubreyR** [comment]
Would be nice to be able to set Kalabox up on a non-default port like 8080, then could run nginx and kbox side-by-side.  Probably a way to do this but it's not obvious to me at the moment.

**Comment by pirog** [comment]
We dont install these during install anymore. THey get spun up on first run now. You will still get an error but its a little more obvious and we've added a section to our docs about this
