### ISSUE TITLE
Issues with app testing

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1275]
As a developer on kalabox-app-pantheon, I want to make sure that I don't have to restart builds due to erroneous failures.

Three major problems:

1. Sometimes third-party dependencies aren't available when building images (like the appserver) and the build fails. 

  - Suggested solution: try building the image multiple times (bash retry, see kalabox-installer linux/network/bridgeup) 

2. Create tasks hang indefinitely, producing the "Build times out because no output was received" error

3. Random tasks hang indefinitely, producing the "Build times out because no output was received" error

  - Initial create site seems to fail most often + checking the state of containers after initial create (particularly on Wordpress)
  - Try putting in a sleep in the "after" function for BATS

**Comment by reynoldsalec** [comment]
@pirog may take this over as part of his other issues.

**Comment by pirog** [comment]
@reynoldsalec ive done a lot of work on this re: my other tasks so im going to assign this to myself
