### ISSUE TITLE
Replicate issue: Stock apps don't show progress or status messages

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1276]
Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha3 on MacOSX w/previous installs

**Tell us about your bug**

1. Pull down a stock Drupal App

2. Stop it. Restart Kalabox.

3. Try starting the stock Drupal app.

You should see no status messages or progress bar (at least until the last "completing" task).

**Comment by rileysaurus** [comment]
I'm unable to recreate this condition, I suggest we move it to the back log until we can recreate it on more than one setup.

**Comment by reynoldsalec** [comment]
@rileysaurus is going to take a look at this in a VM

- [ ] Roll back troubleshooting on 1256 branch
- [ ] Disable Travis e2e temporarily
- [ ] See if you can recreate issue on VM

**Comment by rileysaurus** [comment]
I'm not able to recreate this on an OSX VM either. For now until proven otherwise I think it might be isolated to Alec's machine.

**Comment by pirog** [comment]
+1 on backlogging until we have more evidence/*reasons to believe*

**Comment by reynoldsalec** [comment]
Ok, @pirog and I appear to be able to recreate the root of this issue with the following steps:

1. Start creation of a Pantheon app
2. Start creation of a stock app

Stock app will not show any progress steps beyond "Creating..."

If you leave it long enough, it will complete successfully.

It could be that this is the product of trying two simultaneous site creates, irregardless of type.

**Comment by pirog** [comment]
Let's loop back around on this after #1310 is resolved. THere is a good chance this might be the same underlying issue.
