### ISSUE TITLE
Browser can't find website

### ISSUE THREAD

**Issue by jjmonterey** [kalabox/kalabox#1277]
Bug Report
==========

What version of Kalabox are you using?

 v0.12.0-alpha.3

Windows 10 home i7 quad core 8gb memory

Have you previously installed Kalabox? If so, what version?

No

Installed Kalabox Installed a Backdrop pull from Pantheon and a Backdrop instance not from Pantheon,  Was able to power each separately, but browser could not find site.

Can you recreate this bug?

> Yes

Uninstalled Kalabox, VirtualBox, and Git for Windows and deleted all associated folders. Reinstalled Kalabox and per issue 1172 ran cmd docker-machine ip kalabox2 and returned the proper ip 10.13.37.100  (see CMD Kalabox.jpg)  See also other images

![cmd kalabox](https://cloud.githubusercontent.com/assets/5239865/14806308/cc6aea2e-0b3f-11e6-9086-4827c639f448.jpg)

1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
5 .Instance powered up but could not connect in browser

Could better documentation have prevented this issue? if so what should we change?

 Don't Know

Does this bug prevent you from using Kalabox?

Yes at least on Windows 10

![kbox_ui](https://cloud.githubusercontent.com/assets/5239865/14806310/d37057f0-0b3f-11e6-8604-531b08764fbf.jpg)
![vbox](https://cloud.githubusercontent.com/assets/5239865/14806311/d5f704b0-0b3f-11e6-81ed-750a790567a8.jpg)

**Comment by jjmonterey** [comment]
Solved the issue with Backdrop. I assumed Kalabox would write the User,Password, and database info into the settings.php file but when I looked the default out of box demo format: ($database = 'mysql://user:pass@localhost/database_name';) was unchanged. Substituting the generated user, password, and database name from the "connection info" the connection succeeded.

**Comment by pirog** [comment]
This should work out of the box unless you've altered something.

On Tuesday, April 26, 2016, Jon <notifications@github.com> wrote:

> Solved the issue with Backdrop. I assumed Kalabox would write the
> User,Password, and database info into the settings.php file but when I
> looked the default out of box demo format: ($database =
> 'mysql://user:pass@localhost/database_name';) was unchanged. Substituting
> the generated user, password, and database name from the "connection info"
> the connection succeeded.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1277#issuecomment-214682829>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc
