### ISSUE TITLE
Installing additional tooling options like drupal console, yoeman, etc

### ISSUE THREAD

**Issue by jdelon02** [kalabox/kalabox#1278]
Version: v0.12.0-alpha22

OS: OSX 10.10.5

Hello, 

I am trying to leverage kalabox to spin up a basic Drupal 8 site.  I have used both the cli, and the gui to do so successfully (and thanks for that!!!).  However, once I have the site running, I want to use certain tools, some of which kbox says it already can run.  For example, I wanted to install drupal console using composer, but I received this error when I tried to run "drupal generate:module" from within ~/.kalabox/app/thissite (on the host machine):

[PDOException]  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodena
  me nor servname provided, or not known

If I then type "kbox terminal" I am ssh'ed in as root (to the docker machine).  However, typing composer/drush/npm/oranythingelseicouldthinkof returns a command not found for all of those commands.  I am wondering if I am doing something wrong, or is your wrapper not actually installing those tools so that they can then be used from within the machine?  I tried to install composer as the local user(root in this case), but if I then exit the terminal, go back to the host machine, and kbox terminal into the machine again, it no longer appears to be installed, and cannot be run.  Not sure what is going on.  Being able to use tools like npm/node/bower is going to be awesome, but not being able to even run composer from within the machine seems sort of strange, and not being able to use drupal console for a D8 site either from within the kbox terminal, or using a wrapper command, will make things more difficult.  

Overall, I am much impressed, and I am sure I am doing something incorrectly.  Kalabox runs much faster than the vagrant machine that I spent hours creating the scripts for... not sure how I feel about that... and I think it will be awesome for the team of devs that I am a part of once the kinks are worked out!

Thanks,

Jeremy

**Comment by Mchampsee** [comment]
The typical means of using these tools is via command line on the host system. So for instance, to use drush, type in:
`kbox drush dl views`

**Comment by jdelon02** [comment]
Right, and drush seems to work fine using the kbox command.  My issue was with trying to use drupal console, which I installed via composer, but cannot run any commands once installed.  I tried using "kbox drupal generate:module", but that does not work.  I then thought that maybe I would have to ssh in, but once I do, none of the commands that are available using the kbox wrapper are available to me.  I cannot  use drush, composer, or any other commands that I tried.  If I install them, they are available; but once I log out of the ssh connection, then try to go back in, again using kbox terminal, they have all disappeared.  So, how do I run drupal console commands?

**Comment by jdelon02** [comment]
The bigger question is really: "how do I run commands using tools I have installed using the kbox wrapper?"  For instance, I can use kbox composer to install Drupal console, but cannot run any commands.  I can install Yeoman using kbox npm install yo, but cannot run any commands once I do.

**Comment by labboy0276** [comment]
Drupal Console does not ship with Kalabox yet.  It is in the queues to do as such. 

If you run kbox services, your can grab the DB connection and manually configure Drupal Console I believe.  I have not done this yet myself, but it seems plausible.  

A workaround I usually do is just use Drupal Consoles quick start outside of kalabox:

```
drupal chain --file=~/.console/chain/quick-start.yml
drupal site:new drupal8.dev 
```

So if you need to use generate or other commands you can do this quickly.  Then just move the modules into your Kalabox project.  It's one extra step, but quick and painless.

**Comment by pirog** [comment]
We are going to deprecated `kbox terminal` in future releases because it doesn't quite do what we had hoped and is ultimately more confusing/frustrating than helpful.

We also *do* plan to support drupal console out of the box some time soon. 

That said there is one big thing we need to address better that is implied in this issue and i've changed the title to reflect that. Here are some relevant todos:

1. How do users add additional tooling commands to their builds?

  * Adding/modifying cmd dockerfiles (#1174)
  * Adding additional commands (better documentation at  https://kalabox.freshdesk.com/solution/articles/14000005137-core-plugins)

2. How do users install tools like `yoemen` or `drupal console` using preexisting things like `kbox npm` or `kbox composer`

  * See #1280

**Comment by pirog** [comment]
I've converted this to en epic and added the relevant issues

**Comment by bwood** [comment]
I think this issue goes here...?  

I need to use drush extensions like registry-rebuild and module-builder with my kbox apps.  1) Do I install these for `kbox drush`? If so, how?  2) Or is it better to get the drush installed on my host OS talking to my kbox apps? 

Option 2 would be nice.  Is it possible to define drush aliases on my host os for the kbox apps?  (It would be really nice if ~/.drush/kbox.aliases.drushrc.php were updated when I creete a new site.)  I tried to start manually like this:

```
$ kbox drush sa @self
$aliases["self"] = array (
  'root' => '/var/www/html',
  'uri' => 'http://default',
);
```
but that output is not too helpful.  I  guess I could piece this all together by looking for the info in `kbox services`. But doing that for every new app is pretty time-consuming.

Let me know if there's already a ticket that covers this.  The drush info in the wiki doesn't touch on this.

**Comment by pirog** [comment]
Yeah i think this is the correct place to put this Im also going to create a placeholder issue for drush related things (#1298). 

@bwood i would definitely check out #1298 and see if the documentation there actually works. If it doesn't then this is a bug. I also *think* `kbox drush rr` works already for pantheon apps.
