### ISSUE TITLE
provision error

### ISSUE THREAD

**Issue by chasingmaxwell** [kalabox/kalabox#128]
Following the "Developer Install" instructions, I get the following error when running `kbox provision`:

```
STEP [11] -- Setting up B2D CLI goodness....
fs.js:638
  return binding.rename(pathModule._makeLong(oldPath),
                 ^
Error: EXDEV, cross-device link not permitted '/home/peter/.kalabox/downloads/boot2docker-v1.4.1-linux-amd64'
    at Error (native)
    at Object.fs.renameSync (fs.js:638:18)
    at /home/peter/workspace/kalabox/plugins/kalabox_install/installer-linux.js:533:12
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:610:21
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:249:17
    at iterate (/home/peter/workspace/kalabox/node_modules/async/lib/async.js:149:13)
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:160:25
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:251:21
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:615:34
    at /home/peter/workspace/kalabox/plugins/kalabox_install/installer-linux.js:518:13
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:254:17
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:157:25
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:251:21
    at /home/peter/workspace/kalabox/node_modules/async/lib/async.js:615:34
    at Socket.<anonymous> (/home/peter/workspace/kalabox/plugins/kalabox_install/installer-linux.js:503:17)
    at Socket.emit (events.js:129:20)
```

I'm on Ubuntu 14.04. Seems like it might be related to [this](http://stackoverflow.com/questions/12196163/node-js-fs-rename-doesnt-work) or [this](http://stackoverflow.com/questions/4568689/how-do-i-move-file-a-to-a-different-partition-or-device-in-node-js).

**Comment by pirog** [comment]
Interesting. Check this out over here:
https://github.com/kalabox/kalabox-issues/issues/302

Might be worth reopening?

**Comment by pirog** [comment]
@chasingmaxwell closing this in favor of https://github.com/kalabox/kalabox-issues/issues/302

will push a branch soon to fix this

**Comment by chasingmaxwell** [comment]
Sounds good! Sorry for opening a redundant issue. I didn't see that one.

**Comment by pirog** [comment]
no worries. slightly different and was previously closed but just trying to
consolidate for other peoples.


On Fri, Mar 13, 2015 at 1:05 PM, Peter Sieg <notifications@github.com>
wrote:

> Sounds good! Sorry for opening a redundant issue. I didn't see that one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/128#issuecomment-79322487>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
