### ISSUE TITLE
kalabox with backdrop and drush extension needs wget for `drush dl`.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/kalabox#1284]
Hello.  Great job on kalabox.

I'm using kalabox to run a backdrop site and drush is working 😄 .

However for `drush dl` to work it requires `wget` can you install `wget` on kalabox?

```
geoff@gspmbp kdrop $ kbox version
0.12.0-alpha.22
```

```
geoff@gspmbp kdrop $ kbox drush dl webform
sh: 1: wget: not found
unzip:  cannot find or open /var/www/html/modules/webform.zip, /var/www/html/modules/webform.zip.zip or /var/www/html/modules/webform.zip.ZIP.
rm: cannot remove '/var/www/html/modules/webform.zip': No such file or directory

	 Error:  Project webform could not be found.
```

thanks,
~Geoff

**Comment by pirog** [comment]
Should be easy enough to add this to our drush container.

**Comment by pirog** [comment]
Weird, i actually can't even get this far now. Wondering if a regression was introduced or something changes upstream. 

```bash
kbox drush status
Drush command terminated abnormally due to an unrecoverable error.   [error]
```

**Comment by pirog** [comment]
Ok, reason for above was that i hadn't gone through the install profile. 

@serundeputy, is the above the expected behavior? Do you want me to open a ticket for this on https://github.com/backdrop-contrib/drush?

**Comment by pirog** [comment]
Ok, this should be fixed upstream in https://github.com/RobLoach/docker-composer/pull/66. As soon as the images rebuild you should be able to run `kbox rebuild` inside your app to get the updates.

Going to also get a test in for this although it requires some setup until https://github.com/backdrop-contrib/drush/issues/34 is GTG

**Comment by pirog** [comment]
PR: https://github.com/kalabox/kalabox-app-php/pull/30
