### ISSUE TITLE
Improve instructions in Connection Info window

### ISSUE THREAD

**Issue by bwood** [kalabox/kalabox#1286]
**Tell us about your setup**

What version of Kalabox are you using?

> 0.12.0-alpha.22

What operating system are you using?

> MacOS El Cap

Have you previously installed Kalabox? If so, what version?

> No

Feature/Enhancement Request
===========================

Please explain the reason for this feature request or enhancement

> I was confused about the database connection parameters to use when installing drupal.

Please provide some detail on how Kalabox can help solve this problem

>  When you click connection info from the gear item on the kalabox dashboard it could provide two sets of connection info. 

On the left it might say:  *I want connect to mysql from the command line of my host OS.* Here you'd have the current connection info that this window shows.

On the right it might say: *I want the database connection info to use when installing drupal (or manually editing settings.php.)  Here you'd provide the connection info found in `kbox services`.

**Comment by pirog** [comment]
Hey @bwood!

We've actually got another issue tracking this which we'd love to get your feedback on. Going to link to that and close this as a dup. See #1230
