### ISSUE TITLE
kbox drush uli should return the correct hostname

### ISSUE THREAD

**Issue by bwood** [kalabox/kalabox#1287]
What version of Kalabox are you using?

> 0.12.0-alpha.22

```
$ kbox drush uli
http://default/user/reset/1/1461797516/61RFE_kc_3PelKDfG0359AVcpjqJJJUv7l4Ux150fP0/login
```

This url has to be manually edited before it will work.

**Comment by pirog** [comment]
Good catch here!

**Comment by pirog** [comment]
PANTHEON APP PR: https://github.com/kalabox/kalabox-app-pantheon/pull/141
