### ISSUE TITLE
Add a Site should detect upstreamids available in the the user's Pantheon organization

### ISSUE THREAD

**Issue by bwood** [kalabox/kalabox#1296]
```
$ kbox version
0.12.0-alpha.22
```
Feature/Enhancement Request
===========================

I searched on "pantheon" and "upstream" and didn't find a ticket. If there is one, can you point me to it.

If we were to adopt kbox here at Berkeley this would be a required feature: The ability to specify a upstreamid available in the user's organization when adding a new site.

```
$ terminus help sites create
##NAME
    terminus sites create

##DESCRIPTION
    Create a new site

##SYNOPSIS
    [--site=<site>] [--name=<name>] [--label=<label>] [--upstream=<upstreamid>] [--org=<id>]

##OPTIONS
    --site=<site>
        Name of the site to create (machine-readable)
    --name=<name>
        (deprecated) use --site instead
    --label=<label>
        Label for the site
    --upstream=<upstreamid>
        Specify the upstream upstream to use
    --org=<id>
        UUID of organization into which to add this site
```

**Comment by pirog** [comment]
@bwood, as you can imagine we would love to get Berkeley adoption! 

That said i'm not exactly sure what this feature request entails. Could you be more specific? Maybe a use case or user story?

Do you just want to have some metadata on the kalabox side about the upstream or do you want to create a "fresh" site (ie not pulling down an existing site) on kalabox using some designated upstream?

**Comment by jserrao** [comment]
@pirog - I'm really liking Kalabox so far - this feature would be a nice one. I think @bwood is probably looking for new site creation using an organization upstream as the basis for the new site (probably OpenBerkeley). I have my own custom WP stack I like to start with, same idea.

**Comment by pirog** [comment]
ok awesome. glad you like it so far! we are getting there!

if you have a custom upstream that is on pantheon i think the recommended and easiest approach is to just spin up the custom upstream on pantheon and then pull it down on kalabox.

if you have a custom upstream that is NOT on pantheon, this is something we hope to address with our kalabox pro offering in a month or so
http://www.kalabox.io/kalabox-pro

**Comment by jserrao** [comment]
@pirog - yeah that's exactly what I did. Not a big deal in my workflow, more like a nice-to-have feature.

**Comment by pirog** [comment]
@jserrao i feel you. we are definitely still working hard to get things as stable as possible but after that we will have time for all the nice-to-haves :)
