### ISSUE TITLE
Pantheon apps don't provide internal_connection_info

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1305]
Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha4 on ubuntu 14.04

**Tell us about your bug**

While testing alpha 4 it was noticed on the GUI that some sites have empty database credentials on the connection info modal screen

1. Started up GUI
2. Pull / install sites
3. Click on connection info for each site
4. Observe some of the sites database credentials being blank

**Comment by reynoldsalec** [comment]
This only occurs for Pantheon sites, since they don't have the same service. Just pushed a fix directly to the v0.12.0 branch of kalabox-ui.

Changing the title to address the issue that Pantheon apps don't provide internal_connection_info.
