### ISSUE TITLE
gui sidebar allows an already existing site that contains a dash to be created again

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1306]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha4 on ubuntu 14.04

**Tell us about your bug**

while testing alpha4 release I noticed that the sidebar allowed me to create a site that's name contains a dash that already exists.

1. Add a site with a dash in the name on the gui
2. Add a site with the same name again
3. Observe the first site being overwritten by the second site

**Comment by reynoldsalec** [comment]
@rileysaurus does the first site complete creation before trying to create the second site?

I know with existing sites (with or without dashes) I receive a validation error upon submitting the form:

![screen shot 2016-05-01 at 2 26 56 pm](https://cloud.githubusercontent.com/assets/1153738/14944479/c4994ec2-0fa8-11e6-97b8-db7fb6f740ed.png)

**Comment by rileysaurus** [comment]
https://github.com/kalabox/kalabox-cli/pull/41
