### ISSUE TITLE
Research switching to docker event stream for image pull data

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1307]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

> Example: v0.12.0-alpha4

What operating system are you using?

> Windows 10

Have you previously installed Kalabox? If so, what version?

>

**Tell us about your bug**

Give a brief description of what happened

> Creating a site for the first time in the gui on windows does not display messages for pulling of each image like it does on the other os's.

Can you recreate this bug?

> Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Started up GUI on a fresh install on windows
> 2. Create a site for the first time and observe the app status messages

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> Example: No

Does this bug prevent you from using Kalabox?

> Example: No

**Comment by rileysaurus** [comment]
A good solution would be monitoring the docker event stream for image create events.

**Comment by pirog** [comment]
- [ ] Research docker event stream
- [ ] Create a feature request if above seems doable
- [ ] Make sure feature request includes some fairly comprehensive implementation details
