### ISSUE TITLE
Error while removing dir: C:\Users\kalabox\.kalabox\apps\drupal8: EPERM: operation not permitted, unlink 'C:\Users\kalabox\.kalabox\apps\drupal8\code\.stfolder'

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1309]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

> v0.12.0-alpha4

What operating system are you using?

> Windows 10

Have you previously installed Kalabox? If so, what version?

>

**Tell us about your bug**

Give a brief description of what happened

> While testing removal of an app in the alpha4 gui, I got the following error - Error while removing dir: C:\Users\kalabox\.kalabox\apps\drupal8: EPERM: operation not permitted, unlink 'C:\Users\kalabox\.kalabox\apps\drupal8\code\.stfolder'.

Can you recreate this bug?

> Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

> 1. Started up GUI
> 2. Create any site
> 3. Destroy site and observe error

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> Example: No

Does this bug prevent you from using Kalabox?

> Example: No

**Comment by pirog** [comment]
I also have experienced this. It happened when i tried to remove a site that errored out mid-create. @rileysaurus are those really the steps to replicate?

**Comment by Soundvessel** [comment]
I get [that error too](https://github.com/kalabox/kalabox/issues/1331#issue-153496537) with Beta 1 and Alpha 3 when trying to remove a failed app setup

**Comment by pirog** [comment]
I think this should happen regardless of the state of the app but it only seems to happen on windows. 

That said, i **think** this is non-critical, meaning you can safely close the error and proceed as normal.

**Comment by pirog** [comment]
This should be resolved in the forthcoming v0.13.x since we stopped using syncthing
