### ISSUE TITLE
RESEARCH WHY: parallel site creation from a fresh install hangs and destroys the first site creation that was initiated

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#1310]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

> v0.12.0-alpha4

What operating system are you using?

> osx 10.9 & ubuntu 14.04

Have you previously installed Kalabox? If so, what version?

>

**Tell us about your bug**

Give a brief description of what happened

> Parallel site creation from a fresh install hangs and destroys the first site creation that was initiated. Parallel site creation after initial pulling of docker images seems to work.

Can you recreate this bug?

> Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

> 1. Perform a fresh install
> 2. Launch the GUI
> 3. Create site a, then right away create site b
> 4. Site a will start to pull docker images, but at some point will become destroyed, and site b creation will hang

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> Example: No

Does this bug prevent you from using Kalabox?

> Example: No

**Comment by pirog** [comment]
Let's do some initial research on this first

- [ ] Is this a regression from v0.12.0-alpha.3?
- [ ] Can we target a specific commit where this regression happens?

Some likely things that may have caused this?

- [ ] The token container
- [ ] Cleanup method
- [ ] Wiping the app's code on a destroy

@rileysaurus, try to get some intel on the above so we have a clearer path towards resolution.

**Comment by rileysaurus** [comment]
I am unable to recreate with alpha4 or alpha3.

**Comment by pirog** [comment]
![image](https://cloud.githubusercontent.com/assets/713424/14969373/da74829c-1076-11e6-8274-ad82ce689b50.png)?

**Comment by reynoldsalec** [comment]
@pirog or @reynoldsalec should try to recreate this if possible.
