### ISSUE TITLE
Loading screen never disappears (Error bringing machine up.: Failed after 5 retries)

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1314]
Bug Report
==========

**Tell us about your setup**

v0.12.0-alpha4 on MacOS X. With previous installs, but all correctly uninstalled.

**Tell us about your bug**

1. Start Kalabox
2. Loading screen appears
3. Loading screen doesn't go away. Check VirtualBox and the Kalabox2 VM is present and started correctly. After pressing F12 to look at the console, I see an error:

```
Error bringing machine up.: Failed after 5 retries
```

Multiple people have recreated this issue.

This would probably prevent me from using Kalabox if I didn't know what the issue was.

**Workaround**

If I quit out of Kalabox after I'm sure the VM is up and restart it, the apps show up as normal.

**Comment by magbicaleman** [comment]
@reynoldsalec I did not see the following error;
```
Error bringing machine up.: Failed after 5 retries
```

I am seeing the following

![screen shot 2016-05-03 at 11 19 21 am](https://cloud.githubusercontent.com/assets/735039/14996062/103d0a0a-1146-11e6-8e38-039d54be8f2b.png)

![screen shot 2016-05-03 at 3 45 34 pm](https://cloud.githubusercontent.com/assets/735039/14996072/19020ad2-1146-11e6-9698-540ec14d3587.png)

**Comment by magbicaleman** [comment]
I got it to get past the loading screen. Removed all my boot2docker stuff, removed all my docker, and removed all the kalablox, then reinstalled docker (latest), and reinstall kalabox (latest, ran the uninstall script from the /usr/local/bin/).

**Comment by Soundvessel** [comment]
Similar issue with Windows 10. Had to manually delete the `.docker` directory in my `C:\Users`.

**Comment by rileysaurus** [comment]
This is a regression introduced by the pre-loading of sites in the initialization. A race condition exists where engine.up is called twice in parallel and only one of the calls can be successful.

I've solved this by lazy loading the object used to pre-load the sites. See pull request. https://github.com/kalabox/kalabox-ui/pull/214

This fix will be in the next release.

**Comment by dolceficante** [comment]
Any idea of when a next release will be available for this fix?  It seems that alpha 4 is the latest download on the releases page.

**Comment by labboy0276** [comment]
Hello,

beta1 was released over a month ago:

https://github.com/kalabox/kalabox/releases

**Comment by dolceficante** [comment]
Thanks for pointing that out.  With that version I get the error Cannot read property 'git_url' of undefined on OSX 10.11.4 El Capitan.  I read elsewhere that this was fixed in the alpha version.  Any pointers to where there is a distro that works on OSX?  Thanks for your help

**Comment by pirog** [comment]
@dolceficante that issue was fixed but if you are using older apps they might still have the version of terminus causing that error. 

When you upgrade your version its a good practice to also rebuild your apps.

**Comment by jmevalentin** [comment]
I just downloaded and am having this issue. I'm on a Mac running 10.9.5, and yes I know that's outdated, but issues with newer versions have prevented my upgrading. I had Docker installed, but just uninstalled it and tried Kalabox installation again, but no change. I need this for a critical project to be completed today, so I really need the assist. I've also go t virtualbox to run other VMs, but nothing's running now. Please advise.

**Comment by pirog** [comment]
Try using the cli

**Comment by jmevalentin** [comment]
I can't eve start up the gui. Can I download an existing pantheon repo via the command line? I thought the commands were for creating a new pantheon repo.

**Comment by pirog** [comment]
Yup. Check out the documentation!

**Comment by jmevalentin** [comment]
Turned out my Docker wasn't compatible and I couldn't upgrade on my older OSX, so had to do an upgrade. Oh well, time to grow up. At least kalabox works now. Thanks!!

**Comment by reynoldsalec** [comment]
A ha, glad to know you found a solution @jmevalentin.
