### ISSUE TITLE
Show message that app is blocked from pulling images until previously created app finishes

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1320]
Feature/Enhancement Request
===========================

**Story/Description**
As a Kalabox user who wants to pull multiple sites at the same time, I want clear feedback on the status of my app creations so I know how long they will take and if an error has occurred.

When I see that one of my apps is stuck on "Creating...", I'm afraid it's broken.

**Suggested Solutions**

We discovered in #1276  that pulling images is serialized by docker, so we can only pull one app at a time.

- [ ] When two or more apps are being created, on the blocked one display a message "Waiting for previous app creation to finish" instead of "Creating..." until it can download images.

![kalabox](https://cloud.githubusercontent.com/assets/1153738/15033312/3ddb34d6-121e-11e6-82cf-5379082adc1c.png)

**Comment by rileysaurus** [comment]
https://github.com/kalabox/kalabox-ui/pull/216
