### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by martinjacob** [kalabox/kalabox#1324]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

Kalabox Installer
version 0.12.0-beta.1

What operating system are you using?
OSX El Capitan

Have you previously installed Kalabox? If so, what version?
Yes, can't remember the version

**Tell us about your bug**

The installation fail (see: http://take.ms/iGWiF)

Can you recreate this bug?

Yes, everytime I try to install it. I've run the uninsltaler with Sudo each time I tried.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Run the uninstaller with sudo
> 2. Start installer
> 3. Get the message : http://take.ms/iGWiF

Does this bug prevent you from using Kalabox?

Yes

**Comment by pirog** [comment]
Hey @martinjacob check out https://kalabox.freshdesk.com/solution/articles/14000023077-my-installation-failed-now-what-can-i-do- which has some common install fail tips.

You can also check out the installer logs at `/var/log/install.log` which might indicate where things went wrong. 

If either of these help please let us know!

**Comment by martinjacob** [comment]
It worked,

Thanks.

Sorry I couldn't find this page...

**Comment by pirog** [comment]
No worries! Glad you were able to resolve. 

I assume the issue was the multiple-host only adapter?

**Comment by martinjacob** [comment]
Yes.
