### ISSUE TITLE
Linux beta1 - DB download takes a long time

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1325]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

v0.12.0-beta1

What operating system are you using?

Xubuntu 14.04

Have you previously installed Kalabox? If so, what version?

Yes, all

**Tell us about your bug**

Give a brief description of what happened

Use kbox create and spin out a site.  DB download takes a really long time, a 36MB DB took 42 mins to download.

Can you recreate this bug?

Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. kbox create pantheon and select site
2. wait
3. go have a snack, its gonna be a minute

**Comment by pirog** [comment]
Thanks for the report @labboy0276. I'll try to replicate this and get back to you.

**Comment by pirog** [comment]
@labboy0276 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!
