### ISSUE TITLE
Missing php-ldap

### ISSUE THREAD

**Issue by dearmond** [kalabox/kalabox#1328]
Feature/Enhancement Request
===========================

Please explain the reason for this feature request or enhancement

> I need to query LDAP in my Drupal sites

Please provide some detail on how Kalabox can help solve this problem

> Build PHP "--with-ldap"

Why do you think it is important Kalabox include this new feature or enhancement?

> To maintain server parity with Pantheon. Also because a lot of sites use it.

**Comment by pirog** [comment]
@dearmond +1 

Definitely will try to get this in for the next release.
