### ISSUE TITLE
Database pull doesn't seem to work, Drush/Console_Table Error

### ISSUE THREAD

**Issue by Swingline0** [kalabox/kalabox#1329]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

0.12.16

What operating system are you using?

OSX 10.11.4

Have you previously installed Kalabox? If so, what version?

Nope

**Tell us about your bug**

Pulling a Pantheon database using GUI or CLI seems to fail. 

The following error is output when performing the pull from the CLI: (Site ID omitted intentionally)

```
➜ kbox pull
? Pull database from which environment? live
? Pull files from which environment? Do not pull files
Pulling screenshot.
Downloading: [9.4%] ...XXXX_dev.png
Pulling code.
Warning: Permanently added '[codeserver.dev.XXXX.drush.in]:2222,[166.78.239.12]:2222' (RSA) to the list of known hosts.
From ssh://codeserver.dev.XXXX.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Pulling database.
Warning: Permanently added '[appserver.live.XXXX.drush.in]:2222,[104.130.220.217]:2222' (RSA) to the list of known hosts.
Drush needs to download a library from                                   [error]
http://download.pear.php.net/package/Console_Table-1.1.3.tgz in order
to function, and the attempt to download this file automatically
failed because you do not have permission to write to the library
directory /opt/drush5/lib. To continue you will need to manually
download the package from
http://download.pear.php.net/package/Console_Table-1.1.3.tgz, extract
it, and copy the directory into your /opt/drush5/lib directory.
```

The GUI doesn't show any particular errors in Devtools or otherwise however the pantheon table in the mariadb container remains empty. 

Can you recreate this bug?

> Yes

1. `cd` to a Wordpress/Pantheon project directory
2. `kbox pull`
3. Select a pantheon database
4. Error above is output

Results: 
- When the site is accessed from the browser, the initial Wordpress setup screen is displayed, suggesting the database has not been populated
- Accessing the mariadb container, the `pantheon` table appears to be empty

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

No

Does this bug prevent you from using Kalabox?

Yes

**Comment by pirog** [comment]
So i did some research on this one and it might be worth refactoring your issue a bit @Swingline0 if you can corroborate this.

So, pulling from both live and test seems to work as expected for me. **HOWEVER**, i was able to replicate this when pulling from a site where the test/live environments either do not exist yet or do not have an active database. 

@Swingline0 can you confirm/deny that your live environment actually exists and/or has an active database in it?

**Comment by Swingline0** [comment]
Hey @pirog,

Hmm... Yeah, this site definitely has all three dev/test/live environments up and running, I elected to pull the live database because it's already in production.

My colleague here at the office is experiencing the same issue with the same site so perhaps it's specific to this particular app's configuration?

**Comment by pirog** [comment]
Hmmm, very weird then. I am definitely able to pull sites in production so we need to find the delta here. Are you getting this on ALL your sites or just this one? 

What is definitely interesting is `/opt/drush5/lib/` does not exist on Kalabox. I assume this exists on Pantheon so i'm wondering if you guys have some pantheon specific workflow triggers in place?

Another possibility here, which might explain why im getting this on sites without live sites, is that you have some sort of drush policy on the live site that stops us from accessing the database. This could be an actual drush policy file or maybe some logic inside of settings.php.

As a workaround in the interim you could try cloning your `live` db to `test` or `dev` and then pulling from there.

**Comment by Swingline0** [comment]
Thanks @pirog  -- Alllright so this is definitely weird.

We've only got a single site on Pantheon so I created an additional site to test with. What rocks is that I was able pull its `dev` environment without issue!

Unfortunately, this isn't the case with my actual app. It doesn't seem to make a difference which environment I pull-- they all wind up with the same output as the above error. 

I'm not aware of any specific drush policies that would be in place however I wasn't the dev to set this project up originally and it has, in fact, passed through quite a few hands before mine. Do you have any suggestions for how I might troubleshoot this?

**Comment by pirog** [comment]
Hmmm yeah that kind of makes me think this might just be something particular to the set up of this app in particular (read: not necessarily a problem with kalabox)

I think the most obvious things to look for are

1. Custom logic in settings.php which might lock out attempts to pull the DB
2. Custom drush files (particularly a policy file https://raw.githubusercontent.com/drush-ops/drush/master/examples/policy.drush.inc)
3. Any pantheon quicksilver config which likely is in a file called `pantheon.yml` in your webroot

**Comment by magbicaleman** [comment]
I'm starting on a personal project, that is currently `sandbox` mode on Pantheon. After getting Kalabox working, I started to notice it was not pulling the database. This was a new site setup today on Pantheon. 

```
? Pull database from which environment? dev
? Pull files from which environment? dev
Pulling screenshot.
Downloading: [30.4%] ...5b87-ce9b-4ddf-bf32-90857db56325_dev.png
Pulling code.
Warning: Permanently added '[codeserver.dev.cb8e5b87-ce9b-4ddf-bf32-90857db56325.drush.in]:2222,[166.78.239.12]:2222' (RSA) to the list of known hosts.
From ssh://codeserver.dev.cb8e5b87-ce9b-4ddf-bf32-90857db56325.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Pulling database.
Warning: Permanently added '[appserver.dev.cb8e5b87-ce9b-4ddf-bf32-90857db56325.drush.in]:2222,[162.209.95.100]:2222' (RSA) to the list of known hosts.
Drush needs to download a library from                                   [error]
http://download.pear.php.net/package/Console_Table-1.1.3.tgz in order
to function, and the attempt to download this file automatically
failed because you do not have permission to write to the library
directory /opt/drush5/lib. To continue you will need to manually
download the package from
http://download.pear.php.net/package/Console_Table-1.1.3.tgz, extract
it, and copy the directory into your /opt/drush5/lib directory.
Pulling files.
Warning: Permanently added '[appserver.dev.cb8e5b87-ce9b-4ddf-bf32-90857db56325.drush.in]:2222,[162.209.95.100]:2222' (RSA) to the list of known hosts.
receiving incremental file list

sent 141 bytes  received 32 bytes  31.45 bytes/sec
total size is 0  speedup is 0.00
```

**Comment by pirog** [comment]
@magbicaleman just to be 100%, do you *definitely* have a DB for that pantheon site? IE have you gone through the actual site install process (ie clicking on the site and doing the normal first-time setup) on pantheon?

**Comment by magbicaleman** [comment]
@pirog originally, that why I added to this issue. I had created a site on pantheon, created an account, logged in...etc. When kalabox application pulled the site, locally it kept asking to install wordpress. 

I deleted my Pantheon sites, removed Kalabox with the uninstall.sh, and created a new site on Pantheon, and re-installed and pulled that site. Currently it worked perfectly, the only issue now it's not having permission to update plugin.

**Comment by mustela** [comment]
Having the same issue here, the website have the 3 environments in pantheon and they are all working correctly. 

```
$ kbox pull
? Pull database from which environment? dev
? Pull files from which environment? Do not pull files
Pulling screenshot.
Downloading: [100%] ...8df5-2c43-4cda-8431-95d86f6fdf20_dev.png
Pulling code.
Warning: Permanently added '[codeserver.dev.cb0.drush.in]:2222,[166.78.239.4]:2222' (RSA) to the list of known hosts.
From ssh://codeserver.dev.cb618df5-2c43-4cda-8431-95d86f6fdf20.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Pulling database.
Warning: Permanently added '[appserver.dev.cb6d86f6fdf20.drush.in]:2222,[192.237.244.56]:2222' (RSA) to the list of known hosts.
Drush needs to download a library from                                   [error]
http://download.pear.php.net/package/Console_Table-1.1.3.tgz in order
to function, and the attempt to download this file automatically
failed because you do not have permission to write to the library
directory /opt/drush5/lib. To continue you will need to manually
download the package from
http://download.pear.php.net/package/Console_Table-1.1.3.tgz, extract
it, and copy the directory into your /opt/drush5/lib directory.
```

**Comment by mustela** [comment]
I just tried creating new websites, and they seems to be working just fine. But not the existing one. 

If it helps, the site that isn't working, came from a migration using the pantheon wp migration plugin.

**Comment by pirog** [comment]
Interesting. Are all the sites that are failing for people wordpress sites?

**Comment by elconejito** [comment]
Chiming in with a "me too". Error message at the bottom.

This is a wordpress site, only dev environment has been created, it's in sandbox. The site on pantheon has gone through it's setup/install screens and has some data in it already. This is the first installation of Kalabox on this machine. This is the first site I've tried to pull down, although there are many in our account. The GUI doesn't announce any errors, I only looked at the command line after coming here looking to see if there was an existing issue.

```
? Pull database from which environment? dev
? Pull files from which environment? Do not pull files
Pulling screenshot.
Downloading: [100%] REDACTED_dev.png
Pulling code.
Warning: Permanently added 'REDACTED' (RSA) to the list of known hosts.
From REDACTED/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Pulling database.
Warning: Permanently added 'REDACTED' (RSA) to the list of known hosts.
Drush needs to download a library from                                   [error]
http://download.pear.php.net/package/Console_Table-1.1.3.tgz in order
to function, and the attempt to download this file automatically
failed because you do not have permission to write to the library
directory /opt/drush5/lib. To continue you will need to manually
download the package from
http://download.pear.php.net/package/Console_Table-1.1.3.tgz, extract
it, and copy the directory into your /opt/drush5/lib directory.
```

**Comment by mustela** [comment]
@pirog happy to give you access to my repo if you can't replicate the issue.

**Comment by wonkeythemonkey** [comment]
Adding my voice to users experiencing the same problem. Things were working fine on my first attempt at pulling a Pantheon Wordpress site. Then I destroyed that particular app, and when I tried to recreate it I got exactly the error message described above.

**Comment by mustela** [comment]
Guys is there any workaround to this or anything? Its quick critical actually. 

Thanks!

**Comment by pirog** [comment]
@mustela 
You could try importing the database manually. And yes @mustela if you add me to your site i will be more than happy to look into this. It's hard for us to fix anything we can't replicate on our end. I don't think i can look into it until later next week as we are busy trying to roll out our 0.13.x version but once we do that i'd be more than happy to investigate. 

I am mike at kalabox.io if you want to add me.

**Comment by elconejito** [comment]
@pirog i tried importing manually and it didn't work. Maybe i'm doing it wrong? Here's the commands I ran from the app folder ~/.kalabox/apps/sitename:

I ran this to export the db. This is the way I usually export the db (minus the kbox part). I get the command from the "Connection Info" dropdown in the Pantheon dashboard.
```
kbox mysqldump -u pantheon -p#### -h dbserver.dev.####.drush.in -P ##### pantheon > sitename.sql
```
Then I run this to import
```
kbox mysql pantheon < sitename.sql
```

It looks like it didn't do anything at all. No error message though.

**Comment by wonkeythemonkey** [comment]
It just occurred to me: why is it that my Wordpress app is using drush at all?

**Comment by pirog** [comment]
Its just to pull the database from pantheon. We use the drush alias as a
wrapper to make an SSH connection.

**Comment by mustela** [comment]
If it helps, same error on `v0.13.0-alpha.1`

```
Drush needs to download a library from                                   [error]
http://download.pear.php.net/package/Console_Table-1.1.3.tgz in order
to function, and the attempt to download this file automatically
failed because you do not have permission to write to the library
directory /opt/drush5/lib. To continue you will need to manually
download the package from
http://download.pear.php.net/package/Console_Table-1.1.3.tgz, extract
it, and copy the directory into your /opt/drush5/lib directory.
Pulling files.
tar: can't open '-C': No such file or directory
###############################################################
```

**Comment by pirog** [comment]
Not surprising since the focus of the 12 -> 13 bump was mostly for these three major items:

1. Make development easier to churn out releases faster
2. Improve the reliability of the installer
3. Documentation

That said once we are wrapped up with the official move to 13 we should be able to fix things and pump out new releases much much faster.

**Comment by kurtschlatzer** [comment]
In the same boat. Thought I was losing my mind.

@pirog - adding you to our team so you can poke around if you want.

**Comment by pirog** [comment]
Alright! Finally investigating this. Will let you guys know if i find anything.

**Comment by pirog** [comment]
So short answer is you need to update the version of drush pantheon is using with your site to drush8
https://pantheon.io/docs/drush-versions/

Good news is this is something we can check for and configure automatically on our end so we this should be fixed in our next release.

**Comment by pirog** [comment]
Hmmm, even after switching to drush8 i am still getting a drush5 error so this makes me think that there is something going on on the pantheon end. Going to confer with them.

**Comment by kurtschlatzer** [comment]
Thanks for the updates, Mike!

**Comment by pirog** [comment]
Sure thing, i'm continuing to investigate. Also looks like the site that i have that works is using drush5 so there must be something different between that drush and the drush you guys have even though they are the same version. 

I'm guessing that pantheon just does not maintain drush for wordpress sites (which makes sense) so we might need to switch our database import to use a more robust method.

**Comment by pirog** [comment]
So the immediate resolution we have is to switch WordPress to import the DB via a direct `mysqldump` vs `drush sql-connect && drush sql-dump`. The downside of this is that the former does not run through an SSH tunnel so the import speed is considerably slower than with drush. 

Sadly, without a change on the Pantheon end i don't think there is much we can do. That said we can certainly encourage them to do one of the following

1. Resolve this issue by updating their older WordPress sites to run a working Drush. 
2. Allow `mysqldump` to be run via a SSH tunnel against a pantheon `appserver` container.

**Comment by kurtschlatzer** [comment]
This is great progress and I thank you for your efforts. At least I know where to focus attention as I pass this along to Pantheon.

**Comment by pirog** [comment]
Sure thing. At the very least we will have something that works in the next
version, even if its a bit slow.

**Comment by pirog** [comment]
This will be resolved in the next version!

**Comment by kurtschlatzer** [comment]
@pirog - Thanks Mike, it's workin' like a boss.

**Comment by pirog** [comment]
@kurtschlatzer awesome and glad to hear it. 

@joshkoenig that would be great and looking forward to that.
