### ISSUE TITLE
boot2docker DNS trouble, remove legacy DNS engine options

### ISSUE THREAD

**Issue by Swingline0** [kalabox/kalabox#1330]
Bug Report
==========

**Tell us about your setup**

0.12.16

What operating system are you using?

OSX 10.11.4

Have you previously installed Kalabox? If so, what version?

No

**Tell us about your bug**

This is a followup on an issue I identified while working through #1318. I just wanted to report back my findings...

I spent some time yesterday struggling to understand why I was unable to pull any sites from pantheon. While I had internet access, all the various processes required to pull a pantheon site (screenshot, git clone, database, rsync) were failing as if there were no connectivity. 

After troubleshooting the issue I found that I could ping out to google from my host os and the boot2docker vm however the individual containers could not. They could, however, ping IP addresses directly.

Finally, we tracked this down to an issue in which my office apparently blocks the use of outside DNS servers. Thus, as Kalabox's docker configuration is setup to use OpenDNS, the containers were unable to resolve domains. 

For our immediate purposes, we were able to resolve the issue by...
1. SSH into Kalabox's boot2docker instance
2. `sudo vi /var/lib/boot2docker/profile` 
3. Remove the following lines:
   `--dns=172.17.0.1`
   `--dns=208.67.222.222`
   `--dns=208.67.220.220`
4. `sudo /etc/init.d/docker restart`

It looks like this configuration is set during Kalabox's install [here](https://github.com/kalabox/kalabox/blob/14bd841a21925ca2c916e3fa945f85ff1dcf85c6/osx/mpkg/engine.pkg/Scripts/postinstall#L42-L44) however I suspect there would be remifications for doing this across the board.

Can you recreate this bug?

1. Install Kalabox
2. Go to work (where DNS restrictions are imposed)
3. Authenticate Kalabox with my pantheon account
4. Attempt to pull a site from pantheon

**Comment by pirog** [comment]
This is great research. Thanks a bunch @Swingline0.

So it looks like docker uses google dns by default (http://odino.org/cannot-connect-to-the-internet-from-your-docker-containers/). Do you know if your office blocks these?

**Comment by Swingline0** [comment]
So while I can ping respective IPs of Google and OpenDNS, setting them as my DNS servers winds up breaking my connectivity. It seems that the containers deal with the same.

After removing the DNS servers from boot2docker's profile and restarting docker, the containers inherit the company's internal DNS server.

**Comment by pirog** [comment]
Makes sense since the internal rule is probably just blocking services on port 53.

I *think* I am comfortable making this change. Might be worth rolling two versions for the next release in case people **NEED** us to specify the servers although i think the two most likely scenarios here are

1. Containers inherit internal DNS
2. Containers use `8.8.8.8/8.8.4.4`

**Comment by Swingline0** [comment]
Sounds about right. 

What I really want to know is if there is a situation where containers inheriting from the host OS would ever be a bad thing (for Kalabox's use case). If we were dealing with actual deployments, I could see a reason for it but in the scope of a local development solution, it seems like whatever works for the host OS would be good enough for the containers.

**Comment by pirog** [comment]
I am pretty sure there *WAS* an issue like this locally in earlier versions of B2D/Machine which is why we were manually putting in the DNS. 

However, i think since the introduction of `--virtualbox-host-dns-resolver` and `--virtualbox-dns-proxy` for `docker-machine` the DNS should all get set up and inherited correctly.

**Comment by Swingline0** [comment]
Ahh that makes sense.

**Comment by pirog** [comment]
@Swingline0 going to move this into the backlog so we can address it in the beta2 sprint.

**Comment by Swingline0** [comment]
Sweet! Thanks!

**Comment by pirog** [comment]
Gonna reopen this until we have a fix for it :)
