### ISSUE TITLE
Custom modules not being uploaded

### ISSUE THREAD

**Issue by baroneddy** [kalabox/kalabox#1339]
Kbox version: v0.12.0-beta1 on El Capitan.
Previous usage: second time installing Kbox but first time really starting to use it.

Hi there,
I am currently migrating a site to Pantheon and I plan on using Kalabox for local dev. I absolutely love it (except the very high CPU usage of syncthing and VBoxHeadless :( ). I am running into an issue with my custom module and I am wondering if this is a normal behaviour or not.

- I create a new D7 site on Pantheon
- Imported it with Kalabox
- Added all my custom modules, themes and database (everything works on my local)
- Push everything to my Pantheon site

No error during the push, takes some time, and when it is done, I check my Pantheon files, and all my custom modules are not imported. All the contrib are here, but the customs only has a empty folder.

We are 2 and we both have the same behaviour (2 different Pantheon site, both on El Capitan). I didn't see anyone else having the issue so I am starting to wonder if it is a normal behaviour. If not, I am happy to give any more info that can help.

Thanks,

Ed

**Comment by baroneddy** [comment]
My guess is that theses modules where previously on git and contains a .git file.

**Comment by baroneddy** [comment]
I removed my .git files and re-create my site and it was well updated. Problem was on my end, sorry for that!

**Comment by pirog** [comment]
no worries!
