### ISSUE TITLE
/etc/resolver/kbox causing >1min page loads for local dev sites (not on kalabox).

### ISSUE THREAD

**Issue by serundeputy** [kalabox/kalabox#1342]
@pirog here is the DNS issue I was telling you about at DrupalCon NOLA.

>1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.

  I searched I did not see a related issue.

>2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).

  I'm not sure I have access to the tags or I can't find it.

> 3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

> **Tell us about your setup**

Mac OSX 10.11.4
```
geoff@gspmbp drupal (2703329/use_path_on_403_404_system_settings_form) $ uname -a
Darwin gspmbp.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

Local apache, php and homebrew mysql 5.5.44.

> What is your Kalabox version and operating system?

```
geoff@gspmbp drupal (2703329/use_path_on_403_404_system_settings_form) $ kbox version
0.12.0-alpha.22
```

> Have you previously installed Kalabox? If so, what version?

  No.

> **Tell us about your bug**

Page loads exceed 1min for my local VHosts on local apache.  If I comment out the setting in `/etc/resolver/kbox` the page loads get back to ~500ms

**Comment by pirog** [comment]
@serundeputy awesome! this is really helpful. 

Does this *ONLY* happen when using native mac local dev or does it seem to happen using other local dev tools a la vagrant/mamp?

**Comment by serundeputy** [comment]
@pirog I don't have vagrant or mamp and if I recall correctly the page loads were fine on kalabox itself, but when I switched to a local native mac VHost the page loads exceeded 1min and went back to normal when commenting out the line in `/etc/resolver/kbox`

thanks!

**Comment by pirog** [comment]
@serundeputy thats makes sense re: `.kbox` domains but still puzzled re: local domains. 

On native mac what domains are set up in your vhosts? Just `localhost`? or something else?

**Comment by serundeputy** [comment]
@pirog I have a bunch of domains most of them do not have extensions at all like:
Vhosts:

  * website-one
  * website-two
  

Some are like `blah-blah.dev` or `blah-blah.org.dev`, but most are just `blah-blah`.

thanks,
~Geoff

**Comment by pirog** [comment]
ahhh ok. that *might* make a little more sense. Is the lag you get the same regardless of whether you use the `.dev` or not?

**Comment by pirog** [comment]
@serundeputy i would try this out on the new beta3 and see if it resolves the issue. reopen if not!
