### ISSUE TITLE
Installation Failure on Mac when BASH is not the default shell. 

### ISSUE THREAD

**Issue by rossluebe** [kalabox/kalabox#1343]
**What is your Kalabox version and operating system?**
v0.12.0-beta.1 on OS X 10.11.4

**Have you previously installed Kalabox? If so, what version?**
No

**Give a brief description of what happened, including any error messages that appeared.**
Near the completion of the Kalabox installer, an installation failed message comes up without much in the way of an explanation or a solution (see attached). I've removed unused 'Host-only Adapters' as outlined [here](http://support.kalabox.io/support/solutions/articles/14000023077-my-installation-failed-now-what-can-i-do-) and I'm still getting this error.

![screen shot 2016-05-13 at 11 57 24 am](https://cloud.githubusercontent.com/assets/5075626/15254533/45def62a-1905-11e6-95cb-408088b2db29.png)

After the failed installed message, Kalabox is still added to my application folder. When I open the app it never gets past the 'Starting the Kalabox engine…' message.

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**
I'm not sure what is different about my system that could be causing this issue, I do have around 25 VirtualBoxes on my computer. The issue persist regardless if I'm using VirtualBox 4.3.36 or 5.0.20.

**Could better documentation have prevented this issue? if so what should we change?**
Perhaps this is possible, but I couldn't find it in the documentation, but it would be nice if there was a method for installing on Mac through terminal so that the error message was more apparent.

**Does this bug prevent you from using Kalabox?**
Yes

**Comment by pirog** [comment]
@rossluebe interesting. the host-only adapter issue accounts for maybe 95% of our installation errors on mac so its def valuable to get, presumably, another one. 

after you go through the install there should be a log file of the failure in `/var/log/install.log`. Can you either send that along to us or scour it for relevant error messages? 

from what you are describing it seems like the Kalabox2 VM just never gets installed.

**Comment by rossluebe** [comment]
@pirog Thanks for getting back to me. Here is where the install seems to go haywire:
`May 16 15:31:36 Ross-Luebe-iMac installd[415]: ./postinstall: Docker Machine is not installed. Please re-run the Kalabox Installer and try again.`
`May 16 15:31:36 Ross-Luebe-iMac install_monitor[604]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr`
`May 16 15:31:36 Ross-Luebe-iMac installd[415]: PackageKit: releasing backupd`
`May 16 15:31:36 Ross-Luebe-iMac installd[415]: PackageKit: allow user idle system sleep`
`May 16 15:31:36 Ross-Luebe-iMac installd[415]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “KalaboxInstaller.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#engine.pkg, PKInstallPackageIdentifier=io.kalabox.pkg.engine, NSLocalizedDescription=An error occurred while running scripts from the package “KalaboxInstaller.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cKalaboxInstaller.pkg\U201d.";
	    NSURL = "file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#engine.pkg";
	    PKInstallPackageIdentifier = "io.kalabox.pkg.engine";
	}`

**Comment by pirog** [comment]
oh very weird. the `docker-machine` install we do is VERY basic. IE We just move it from the package to`~/.kalabox/bin`. Is that directory empty? Does your home directory exist in a non-standard location?

**Comment by rossluebe** [comment]
`~/.kalabox/bin` is empty and my home directory is in the standard location, but your comment lead me to believe that is my shell might be at the root of the problem. I use `fish` instead of `bash`. I switched my default shell back to bash and the install went through without problem.

Not sure if this is really a bug for your team to pursuit, so close at your discretion and thanks @pirog for helping me figure out the root of the issue!

**Comment by pirog** [comment]
a ha! Makes sense. 

Maybe we can modify this so it forces the use of BASH for the install scripts. Are you installing on the command line or are you installing by double clicking on the pkg? 

I'll keep this open for now until we have a satisfactory pathway forward.

**Comment by rossluebe** [comment]
I was double clicking the pkg file to install.

**Comment by pirog** [comment]
k thx!

**Comment by schutzsmith** [comment]
I'm also having the same issue. Did anyone find a fix? Could we not install via CLI instead?

**Comment by pirog** [comment]
@schutzsmith, are you using `fish` as well?

**Comment by schutzsmith** [comment]
I'm using zsh and ohmyzsh if that makes a difference.

**Comment by pirog** [comment]
Good to know. Did switching your default shell to BASH resolve the issue as a workaround?

I think we just need to explicitly run the postinstall scripts through bash and this shouldn't be an issue.

**Comment by pi-ron** [comment]
+1 Also can't install the latest version, using zsh and ohmyzsh

**Comment by pirog** [comment]
@pi-ron you have installed it successfully before though right? or not with the new installer?

**Comment by kurtschlatzer** [comment]
Using zsh, having this issue. Installed before. Cleared all traces before I installed the latest update.

**Comment by kurtschlatzer** [comment]
@pirog 

Using zsh. install.log snippet from where it goes off the rails for me attached. Hope it helps!

[install-log-snippet.txt](https://github.com/kalabox/kalabox/files/378782/install-log-snippet.txt)

**Comment by pirog** [comment]
So after looking at a few of the logs posted i'm not 100% convinced everyone here is getting install failure because they have a non-bash default shell. I would definitely make sure you are doing the uninstall correctly before you reinstall. This is documented over here http://docs.kalabox.io/en/stable/users/updating/#purge-updating

I also saw one log that seemed to have the classic Duplicate Host Only adapter problem, which is a VB bug that you can workaround using http://docs.kalabox.io/en/stable/troubleshooting/#resolving-duplicate-host-only-adapters

**Comment by loganmaro** [comment]
I'm having a similar issue, except the install appears to work. The application is unable to be opened, shows up with the default application logo, and there's no .kalabox folder made, but it does create a virtual machine. I've attached the text from the log on another computer I'm trying it on right here: [kalabox.txt](https://github.com/kalabox/kalabox/files/385031/kalabox.txt). Thanks!

**Comment by pirog** [comment]
@loganmaro .kalabox isnt created until its needed which is not necessarily right after install. are you able to run any `kbox` commands on the terminal? have you also checked out this https://github.com/kalabox/kalabox/issues/1477 re GUI?

**Comment by pirog** [comment]
So trying this out now with both `fish` and `zsh/ohmyzsh` as default shells and i'll let you know what i discover!

**Comment by pirog** [comment]
So re: `fish` as default shell

This seems to work for me. I am able to install and then pull down a site from Pantheon via the CLI without an issue. I think anyone who was having a problem should do a couple of things

1. Consult the [uninstall docs](http://docs.kalabox.io/en/stable/users/uninstall/) and purge their system completely. 
2. Reinstall using the latest version (v0.13.0-beta.2 at time of writing, beta.3 should be out in a few days if you want to wait for that)

**Comment by pirog** [comment]
Ditto on `zsh` based shells. Going to close this and recommend people try the steps above in previous comment.

**Comment by neilgee** [comment]
Failed link in the [common install issues](http://docs.kalabox.io/en/stable/users/install/#common-installation-issues) for OSX - 
Duplicate host only adapter

**Comment by pirog** [comment]
http://docs.kalabox.io/en/stable/troubleshooting/#resolving-duplicate-host-only-adapters

**Comment by pirog** [comment]
@neilgee fixed the broken docs links, thanks for reporting that!
https://github.com/kalabox/kalabox/commit/1ce662d38799603a9c3a63c16ebf875523603dca
