### ISSUE TITLE
Pantheon authentication UX should be more obvious

### ISSUE THREAD

**Issue by dolceficante** [kalabox/kalabox#1344]
# Bug Report

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox 0.12.0-beta - OSX El Captain - 10.11.4

Have you previously installed Kalabox? If so, what version? 

No

**Tell us about your bug**

I try to connect the Pantheon account, it authenticates, but then nothing happens

http://cl.ly/080e2G2a3Z3r

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Started up GUI
> 2. Provided pantheon creditials in sidebar
> 3. Nothing happened

**Tell us more**

Could better documentation have prevented this issue? if so what should we change? No

Does this bug prevent you from using Kalabox? Yes

**Comment by pirog** [comment]
Click on your email in the sidebar!

On Friday, May 13, 2016, dolceficante <notifications@github.com> wrote:

> Bug Report
>
> *Tell us about your setup*
>
> What is your Kalabox version and operating system?
>
> Kalabox 0.12.0-beta - OSX El Captain - 10.11.4
>
> Have you previously installed Kalabox? If so, what version?
>
> No
>
> *Tell us about your bug*
>
> I try to connect the Pantheon account, it authenticates, but then nothing
> happens
>
> http://cl.ly/080e2G2a3Z3r
>
> Please detail the steps we can take to replicate this bug. Be as detailed
> as possible.
>
>
>    1. Started up GUI
>    2. Provided pantheon creditials in sidebar
>    3. Nothing happened
>
> *Tell us more*
>
> Could better documentation have prevented this issue? if so what should we
> change? No
>
> Does this bug prevent you from using Kalabox? Yes
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1344>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by dolceficante** [comment]
I'm such an idiot :)  Closed.  Here's some suggestions to make this more obvious to dummies like me:  1: some type of message that I logged in and have a connected account, 2: something to visually break up the slide nav, like maybe a section heading for connected accounts.  Thanks for the quick response!

**Comment by pirog** [comment]
Thanks @dolceficante, 

Going to reopen this ticket so your suggestion doesn't get lost!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
