### ISSUE TITLE
[feature request]Create Git repo for new sites

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1345]
# Feature/Enhancement Request

As a Kalabox user who works with Drupal/BackDrop/WordPress sites, I want the option to create a git repo when creating a new site from scratch, because I can then track changes as I go along, be able to generate patches to core, etc.

Please provide some detail on how Kalabox can help solve this problem

Either do so by default or include a command line option.

**Comment by pirog** [comment]
@Mchampsee i can see this being helpful. +1

In the meantime can you not just do a `kbox git init` inside the code directory?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
