### ISSUE TITLE
[installer] [bug fix] Skip GUI install on Ubuntu Servers

### ISSUE THREAD

**Issue by charlesrussell** [kalabox/kalabox#1346]
Environment: Ubuntu 14.04 Server, no GUI
Installation fails with: **"which xdg-desktop-menu**
Logging shows xdg-desktop-menu="" - which is the case on Server installation.

Please skip this check, and state at end of installer that GUI installation wasn't installed.

I worked around this issue by:
    touch /usr/local/bin/xdg-desktop-menu
    apt-get install -f

Installation completed with out incident, and I was able to create a functioning site.

**Comment by pirog** [comment]
@charlesrussell good to know. 

Should be easy enough to replicate this on 14.04 server. This would also probably help us with our testing.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
