### ISSUE TITLE
Problems switching back to DEV after merging MULTIDEV work

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1347]
Bug Report
==========

this is from @danitabowman

1. Spin up a multidev site on Kalabox
2. Do some work on that site and push it up
3. Merge that multidev branch into dev
4. Delete the multidev branch on Pantheon
5. Delete the multidev branch on Kalabox (including destroying box to remove all traces of the multidev branch site)
6. Pull down the DEV branch from Pantheon to Kalabox
7. Kbox site won’t open so check code and none there
8. Run kbox git status and see weirdness (deleted code files)
9. Run kbox git reset —hard HEAD and site code files restored, site opens with no problem

**Comment by dsquaredb** [comment]
Any progress on this issue? I have run in to additional problems when trying to work with multidev. At the moment, I am no longer able to use Kalabox because I can't spin up a dev site that has an active multidev branch. I totally deleted the branch off Kalabox before trying to install the dev version, but my code will not download at all. I tried spinning up the dev site with CLI instead of GUI and the following message: 

```
error: Untracked working tree file '.stfolder' would be overwritten by merge.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

But when I try to run a git command, I get this message:

`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by pirog** [comment]
Not yet :( 

That said the issue you are describing in that comment is documented over at https://github.com/kalabox/kalabox/issues/1102. You should follow the resolution there and in the next release it should not be an issue anymore.

**Comment by dsquaredb** [comment]
Thanks for the reply.

I did find #1102 while trying to resolve the problem. But on a whim, I restarted the GUI and saw it had my dev site created. I used the Terminal from there, did git status, saw the deleted files like before, and did the reset and all works wonderfully again. All it took was creating, then killing my apps about 20 times. :)

Only problem I have now is one I have seen issues about - GUI just hangs up after a while but app keeps working. Have to force close the GUI and start it again.

Thanks for all your hard work on Kalabox. Despite a few frustrations here and there, it helps my workflow.

**Comment by pirog** [comment]
The GUI hanging issue should be resolved in our next release. Thanks for your support and patience. 

Making a good local development environment is a tough but we're slowly getting there!

**Comment by pirog** [comment]
@dsquaredb 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!

**Comment by dsquaredb** [comment]
Thanks for the update. I will install the update and check it out.

**Comment by dsquaredb** [comment]
Testing on this latest version is going well. Haven’t run into any problems yet. One unexpected improvement - Kbox used to really consume resources on my MacBook Pro and make the fan run constantly when I used it. I even added memory to see if it was just my laptop, but it only helped a little.  I’m not seeing the same strain on my laptop with the latest version.

**Comment by pirog** [comment]
yes! We removed syncthing as our sharing solution in favor of unison which greatly reduced the resource requirements of the product. you can read more about that over here http://docs.kalabox.io/en/stable/users/config/#sharing
