### ISSUE TITLE
WHERE IS EVERYTHING!?!?!  :D

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1348]
Sorry I couldn't resist with the title haha!  ...Its the error code :D
**setup**
v0.12.0-beta1 on Windows 10 Professional
I've previously installed Kalabox v0.09 thru v0.11 but did several rounds of cleaning out old installs.

**Tell us about your bug**
The UI was taking very long to complete tasks & not moving all files, so I decided to switch to kbox CLI so I could see errors etc.

When running kbox command line tools I get a bunch of errors though everything seems to be fully functional.  I get this error a ton, between each command sometimes several.
```
                 WHERE IS EVERYTHING!?!?!
 Cannot detect a working Kalabox environment!
```
When running kbox create/push/pull it totally works but I get the following error and need to enter my password.
```
Permissions 0777 for '/user/.ssh/pantheon.kalabox.id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/user/.ssh/pantheon.kalabox.id_rsa": bad permissions
```
Does this bug prevent you from using Kalabox?
No, but I imagine it might stop others from pushing forward, its working so Im not complaining! hahaa, im sure you might be aware of these errors but I didnt see anything in the existing issues .

**Comment by macronomicus** [comment]
I dont see a way for me to add labels, sorry I must not have permissions, or im not figuring it out lol.

**Comment by pirog** [comment]
I *think* this might be the same thing or closely related to what is happening in https://github.com/kalabox/kalabox/issues/1338

**Comment by macronomicus** [comment]
Potentially though he seems to be getting a lot more errors, perhaps both are related to some old kbox cruft hanging around?  Whats nice for me is nothing crashes and i am able to create/push/pull.

**Comment by pirog** [comment]
Do you get the same behavior if you try to pull with the GUI?

**Comment by macronomicus** [comment]
It still works though it goes very slowly in UI, and I killed the win process once or twice not realizing it was just going slower than normal, eventually I left it sit and it did complete. But since then ive been using only CLI for the most part

**Comment by pirog** [comment]
got it. good to know.

**Comment by macronomicus** [comment]
Ok so it seems to have worsened a touch over time, I found two suspect things, I remember when installing kalabox, the last step when you check Show folder, it goes to My Documents instead of the right folder, and in the Environment Variables, it sets install path as the wrong thing too.
C:\Users\Joshua\documents\.kalabox\bin
instead of 
C:\Users\Joshua\.kalabox\bin 
which is where its really installed.
Obviously kalabox knows where its installed since it mostly works but this seems to be a potential area of the issue no?

Now its broken though, im not able to run Drush commands all fail, and when push/pull the database doesnt go anymore, with a drush failure at the end.

So im going to wipe kalabox out again, are there any sticky areas in Windows I should focus to remove things, registry etc etc? 

I want to do a nice clean install again and see if maybe it wasnt cruft from previous installs, although ive installed the beta1 about 4 times now, I even tried installing on top yesterday (without uninstall) which still left everything in the same state.

Let me know if there are any logs or specific things I can give you if it could.

**Comment by pirog** [comment]
I think there are a couple bigger issues we still need to test and account for on windows for the beta2 release. 

I dont think the my documents thing is a big issue, just bad and unclear UX that we should remove. 

There was #1358 which might be what was borking your stuff re drush and push/pull. We are definitely hoping to get windows much more stable in this next release.

**Comment by macronomicus** [comment]
I may have had other system issues, I was finding many system oddities.  For one this system had been upgraded to each version since windows 7 lol, I was long overdue for a fresh clean install.  Im going to install kalabox tonight and see how it goes, I suspect it will have a lot less issues being that every other odd issue I had on the system is gone with all my other apps.

**Comment by macronomicus** [comment]
yeah so far zero issues :D yay!  It could have been a combination of too many old kalabox upgrades, and windows upgrades, everything ive tested has been perfect and this is on 0.12.0-beta.1 so its not including your recent fix that was just announced.

**Comment by macronomicus** [comment]
I still get the " WHERE IS EVERYTHING!?!?!" warnings when running kbox CLI tho they are all working AFAICT.

I wonder if its related to the install path being wrong?  Seems even on a fresh install the Environment variable for install_path is 
`C:\Users\someone\Documents\..\.kalabox\bin`
Is that correct?

**Comment by pirog** [comment]
That is correct although i think we should do something better than that. 

Big thing here is we just need better test coverage on Windows to track some of these regressions.

**Comment by macronomicus** [comment]
yea, I will try and pass on anything I suss out in my use, so far I am able to use everything in spite of the few errors, so I am happy.    :)

**Comment by pirog** [comment]
@macronomicus awesome! we are definitely hoping to roll out a lot of fixes in this next release.

**Comment by macronomicus** [comment]
While everything is mostly working it seems to become crufty over time.  So I did a fresh install again to see how much of a difference that would make, it does relieve many issues but I still get the "Where is Everything?" messages in th CLI, and the UI keeps hanging up on pushing files stage, when I use CLI it does push but it prompts for password at last stage saying permissions are too open for the id_rsa file.

I wish there was more I could do to help suss things out, but looking at the issue cue it seems you've already found most if not all of the issues for the next release.  Best of luck to you!  :)

**Comment by pirog** [comment]
You've helped a ton! Thanks so much!
