### ISSUE TITLE
Unable to update or install plugins/themes, pantheon tmp directory does not exist

### ISSUE THREAD

**Issue by magbicaleman** [kalabox/kalabox#1349]
Bug Report
==========

What is your Kalabox version and operating system?

- Version 0.12.16 (0.12.16) on Mac OS x10.11 Beta (15A278b)

Have you previously installed Kalabox? If so, what version?

- Yes, but removed and reinstall

Give a brief description of what happened, including any error messages that appeared.

- After pulling Pantheon site successfully, I wanted to install `Jetpack` plugin, but got the following error.

> Downloading install package from https://downloads.wordpress.org/plugin/jetpack.4.0.2.zip…

> Warning: unlink(/srv/bindings//tmp/jetpack.4.0.2-974Fmq.tmp): No such file or directory in /code/wp-admin/includes/file.php on line 493 Call Stack: 0.0001 258944 1. {main}() /code/wp-admin/update.php:0 0.5364 3121408 2. Plugin_Upgrader->install() /code/wp-admin/update.php:137 0.5366 3130936 3. WP_Upgrader->run() /code/wp-admin/includes/class-wp-upgrader.php:924 0.5371 3171256 4. WP_Upgrader->download_package() /code/wp-admin/includes/class-wp-upgrader.php:673 0.5371 3163368 5. download_url() /code/wp-admin/includes/class-wp-upgrader.php:248 0.5755 3166704 6. unlink() /code/wp-admin/includes/file.php:493
Download failed. Destination directory for file streaming does not exist or is not writable.

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
@magbicaleman thanks for the bug report here. This looks pretty replicable so let me give it a try and ill report back.

Are you just using a vanilla wordpress site?

**Comment by magbicaleman** [comment]
@pirog correct, I'm echo-ing `WP_TEMP_DIR` and the result currently is `/srv/bindings//tmp`

**Comment by pirog** [comment]
ok awesome. I bet we just need to define `WP_TEMP_DIR` to something a little more kalabox friendly ie `/tmp`

**Comment by magbicaleman** [comment]
```php
   // In the wp-config.php
if ( defined( 'PANTHEON_BINDING' ) ):
  define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
endif;

    // In an mu plugin to output constants
    var_dump(PANTHEON_BINDING); // bool(false)
    var_dump(defined('WP_TEMP_DIR')); // bool(true)
    var_dump(WP_TEMP_DIR); // string(18) "/srv/bindings//tmp"
```

**Comment by pirog** [comment]
ok, so maybe what we actually want to do is provide a `tmp` dir at `/srv/bindings/UUID/tmp` since we define some of these same things.

**Comment by magbicaleman** [comment]
Alright after dumping the `$_ENV` the top key and values are the following;

```
array(26) {
  'PANTHEON_SITE' =>
  string(4) "UUID"
  'PANTHEON_ENVIRONMENT' =>
  string(7) "kalabox"
  'PANTHEON_BINDING' =>
  bool(false)
```

Is the `PANTHEON_BINDING` suppose to hold an integer? 

I've also changed the code to

```php
if ( defined( 'PANTHEON_BINDING' ) ):
  // define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
  define( 'WP_TEMP_DIR', '/srv/bindings/UUID/tmp');
endif;
```

**Comment by pirog** [comment]
@magbicaleman so right now i think it is empty but we probably want it to hold the SITE ID. AS an immediate workaround i would do something like this

```php
/*
 * You might also want to have a conditional here that checks whether the PANTHEON_ENV is kalabox 
 * or otherwise and define WP_TEMP_DIR in this way
 *   Kalabox => define( 'WP_TEMP_DIR', '/tmp');
 *   Pantheon => define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
 * /
if ( defined( 'PANTHEON_BINDING' ) ):
  define( 'WP_TEMP_DIR', '/tmp');
endif;
```

And long term we want to do something that works both on Pantheon and Kalabox.

**Comment by magbicaleman** [comment]
@pirog perfect, that works.

**Comment by coccoinomane** [comment]
Hi!

My Wordpress Website in Kalabox (v0.12.16 on OSX 10.11.4) is bound to Pantheon, and I incurred in the same issue as @magbicaleman when installing plugins. I solved the issue by replacing:

```php
    if ( defined( 'PANTHEON_BINDING' ) ):
        define( 'WP_TEMP_DIR', sprintf( '/srv/bindings/%s/tmp', PANTHEON_BINDING ) );
    endif;
```

in `wp-config.php` with 

```php
    if ( defined( 'PANTHEON_BINDING' ) ):
        define( 'WP_TEMP_DIR', '/tmp');
    endif;
```

Is this the correct way to fix this bug?

Thank you!
Guido

**Comment by pirog** [comment]
@coccoinomane yeah that looks like a good workaround for now. we will have this fixed in upcoming releases.

**Comment by pirog** [comment]
Fix for this should be in next release!
