### ISSUE TITLE
kbox services not showing connection info - Linux beta1

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1351]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Xubuntu 14.04 

Have you previously installed Kalabox? If so, what version?

Kalabox v0.12.0-beta1

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

kbox services no longer displays the DB connection info

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

I started the app and ran kbox services, this is the output:

```
john@kalamuna:~/.kalabox/apps/csi-cloud/code$ kbox services
[
  {
    "name": "edge",
    "project": "csicloud",
    "url": [
      "http://edge.csi-cloud.kbox",
      "https://edge.csi-cloud.kbox"
    ]
  },
  {
    "name": "appserver",
    "project": "csicloud",
    "url": [
      "http://csi-cloud.kbox",
      "https://csi-cloud.kbox"
    ]
  },
  {
    "name": "token",
    "project": "csicloud"
  }
]
```

I also ran kbox rebuild && kbox restart and I get the same output as above.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Not sure

Does this bug prevent you from using Kalabox?

Kind of

**Comment by pirog** [comment]
I'm not able to replicate this on multiple linux distros. are you still getting this?

**Comment by labboy0276** [comment]
I am, anything I can get you to help find the cause?

**Comment by pirog** [comment]
Maybe we can do a hangout sometime soon to investigate this a bit more. I suspect there is something weird in your setup but it might be common to other linux users as well.

**Comment by labboy0276** [comment]
for some ungodly reason, this works now:

```
john@kalamuna:~/.kalabox/apps/sinberbest$ kbox services
[
  {
    "name": "token",
    "project": "sinberbest"
  },
  {
    "name": "edge",
    "project": "sinberbest",
    "url": [
      "http://edge.sinberbest.kbox",
      "https://edge.sinberbest.kbox"
    ]
  },
  {
    "name": "appserver",
    "project": "sinberbest",
    "url": [
      "http://sinberbest.kbox",
      "https://sinberbest.kbox"
    ]
  },
  {
    "name": "db",
    "project": "sinberbest",
    "external_connection_info": {
      "database": "pantheon",
      "user": "pantheon",
      "password": "pantheon",
      "host": "sinberbest.kbox",
      "port": "32768"
    }
  },
  {
    "name": "redis",
    "project": "sinberbest"
  }
]
```

Weird...  I will just close this and blame it on the gremlins.

**Comment by AubreyR** [comment]
@pirog I am having this same issue for one of my **Pantheon sandbox sites**.  I have wiped and recreated the site and still the same issue persists.  Identical behaviour to the issue above.

I am running Ubuntu 16.04 Xenial
Kalabox v0.12.0-beta1 (previously installed alpha3)

I put it down for the weekend hoping it would go away like @labboy0276 but it's still doing it.  I can get most of the connection info using `kbox mysql` but I can't get the port number.

**Comment by pirog** [comment]
I've tried to replicate this on a bunch of different linux OS but have been unable to do so as of yet.

**Comment by AubreyR** [comment]
We can do teamviewer or something if you think it would give you some more information.

**Comment by pirog** [comment]
I'm down to do that. that said, i *did* already do this with @labboy0276 and i'm not exactly sure what else could be gained.

**Comment by pirog** [comment]
So as a workaround for now you can do something like this which seems to work

```bash
# Linux
cd /to/my/app
export DOCKER_HOST=tcp://10.13.37.100:2375
/usr/share/kalabox/bin/docker ps --all | grep MYAPPNAMEWITHOUTHYPHENS_db_1

02b9bd352ef2        mariadb:5.5                                 "docker-entrypoint.sh"   7 days ago          Up 2 days                     0.0.0.0:32793->3306/tcp                                                           aubreytest_db_1

The database port is the the number after the 0.0.0.0
```

**Comment by pirog** [comment]
@labboy0276 @AubreyR was finally able to replicate this. It looks like the same underlying issue as in #1429

**Comment by AubreyR** [comment]
@pirog Excellent news.  So I should be able to fix it by manually removing those entries from the app registry?  Or is there a way to rebuild it automatically?  Or will this be something we can see coming down the road?  Thanks Mike for the hard work, Kalabox just keeps getting better and better.

**Comment by AubreyR** [comment]
@pirog I checked my local installs and this doesn't appear to be the case for me (I have three apps installed and three corresponding apps in the registry) and it's still giving me truncated output for `kbox services`. :(

**Comment by AubreyR** [comment]
I managed to get output on one of my installed kboxes (the most recently installed one, one that I didn't create and was pulled from an older live site that existed before I started working here), but not the other two :/  Very strange.

**Comment by pirog** [comment]
so by same underlying issue i dont meant that they are in fact the same issue just that it looks like the same bug results in both issues.

what appears to be happening is we are sometimes getting a truncated list of containers for a given app.

**Comment by pirog** [comment]
This should be fixed on the latest dev release once it is autobuilt. Will be in the 0.13.0-alpha.2 as well.
