### ISSUE TITLE
File sync takes 3 to 30 mississippis

### ISSUE THREAD

**Issue by derekderaps** [kalabox/kalabox#1352]
As a Kalabox user who works with Drupal sites that have custom code, I want the site to reflect my changes immediately (<1 mississippis) when I update custom code because I don't like waiting.

Kalabox Version: 0.12.16
OS X El Capitan
Mid 2015, 2.5 GHz i7, 16 GB, no video card

**Comment by pirog** [comment]
@derekderaps i definitely feel you loud and clear on this and as we discussed i wish there was a more tenable option than syncthing. We definitely are hopeful the new docker betas can figure out some sexy way to help get file sharing to be more "native" like on linux.

What is the average sync time you are experiencing? When you had the large 30 second sync were you updating multiple files or was it a small trivial change?

**Comment by derekderaps** [comment]
Average was about 5 seconds or so. I figured there was something just wrong with my local, didn't realize there was that much of a lag with SyncThing. Not a huge deal, just wanted to keep my commitment to post issues as they arise :) Thanks for the explanation, duderino!

**Comment by pirog** [comment]
yup! definitely appreciated. 

5 seconds seems on the upper bound of things, i think i generally get about 1-2 seconds, but either way the solution itself is not ideal and i cant wait to replace it.
