### ISSUE TITLE
Suggest workflow for Pantheon sites with alternate repo

### ISSUE THREAD

**Issue by derekderaps** [kalabox/kalabox#1353]
As a Kalabox user who uses CI to build and push code from GitHub to Pantheon, I want the option to specify an alternate repo when I pull a Pantheon site into Kalabox because I want to develop against the actual GitHub repo.

**Comment by pirog** [comment]
@derekderaps this is a feature we plan on adding as part of our Kalabox Pro product
http://www.kalabox.io/kalabox-pro

In the meantime it probably makes the most sense to just use git directly to satify your custom workflow needs

**Comment by derekderaps** [comment]
Makes sense. For now I just renamed the pantheon git remote to `pantheon` and then added our GitHub version as `origin`. Thanks again, broseph!
