### ISSUE TITLE
Add global CLI option to run targeted kbox commands from anywhere

### ISSUE THREAD

**Issue by derekderaps** [kalabox/kalabox#1355]
As a Kalabox user who works on many Drupal sites at once, I want to run kbox CLI commands against any site even when I am not in that site's app directory because I am lazy.

I'm picturing something à la `terminus --site=my-site`

**Comment by pirog** [comment]
@derekderaps i appreciate you and your honesty here.

Sadly, i dont think this is something we can easily support. The design principle here is that your tooling should be tied to your app. So maybe APPA requires terminus and node 0.12.x but APPB requires the platform.sh cli and node 4.2.x. 

There "might" be a way to easily add global tooling options but i think this would end up being REALLY confusing. 

For now i think any "global" options should be left to the user ie installing terminus locally.

**Comment by derekderaps** [comment]
Sorry, I don't think I was clear. I don't want to use kbox to run terminus or whatevs. I was just using terminus as an example of a tool that let's you run commands from any present-working-directory. So, for example:

1. I'm heads down coding on something.
1. Client pings me and says their site, `some-site`, is foobar'd.
1. I can tell its just the cache needs rebuilding.
1. So I want to be able to run:

        kbox --app=some-site drush cc all

  instead of

        cd ~/.kalabox/apps/some-site && drush cc all

Make sense? Thanks, cowboy.

**Comment by macronomicus** [comment]
cant you just use the drush -l  to target any site? 
`kbox drush -l somesite.kbox cr`

**Comment by macronomicus** [comment]
besides kbox wouldnt be on your live server anyhow lol... youd have to run terminus commands to do live server stuff

**Comment by derekderaps** [comment]
@macronomicus: Doh! You're right, that was a silly example. The idea still stands, though: Would be nice to be able to run `kbox` commands on any of my apps, regardless of my terminal's pwd.

**Comment by pirog** [comment]
@derekderaps so this is already *kinda supported* in so far as you can use the form `kbox APPNAME ARG` to target a particular app. That said i think there is a bug that currently prevents this from working for `kbox` commands but it *should* work on app actions like `kbox appname restart`.

Here is the link to the underlying issue
https://github.com/kalabox/kalabox/issues/1221

going to close this in favor of that. feel free to reopen if i am missing the mark and this is not what you are describing to me.

**Comment by derekderaps** [comment]
lol yes that's exactly what I was looking for. Prolly I can't read too well. Thanks yo!

**Comment by pirog** [comment]
eh, our issue organization and documentation are currently shit so i dont blame you :)
