### ISSUE TITLE
Login to Pantheon fails silently when using strong passwords

### ISSUE THREAD

**Issue by davidhwang** [kalabox/kalabox#1356]
Bug Report
==========

_What is your Kalabox version and operating system?_

Kalbox 0.12.16, Mac OS X 10.11.5

_Have you previously installed Kalabox? If so, what version?_

No, never installed Kalabox before, ever.

_Give a brief description of what happened, including any error messages that appeared._

Logging into Pantheon account when using a strong password fails silently. 

_Please detail the steps we can take to replicate this bug. Be as detailed as possible._

- Install Kalabox build from .pkg file
- Click 'Pantheon' under **Add Account**
- Input Pantheon credentials, including a 20-character strong password with numbers & punctuation symbols. 
- Watch login process fail silently, returning you to Kalabox home screen, without Pantheon sites. 

_Does this bug prevent you from using Kalabox?_

Yes.

**Comment by conantp** [comment]
I thought this was happening to me as well, then I realized the Pantheon account shows up at the bottom of the right hand menu.

**Comment by davidhwang** [comment]
Wow, that is one totally almost imperceptible UX affordance. 

Okay, closing this as not-a-bug.

**Comment by pirog** [comment]
+1 on UX improvements here. got a ticket tracking this already
https://github.com/kalabox/kalabox/issues/1344
