### ISSUE TITLE
error during create while pulling database: "Cannot link to a non running container"

### ISSUE THREAD

**Issue by pjleonard37** [kalabox/kalabox#1358]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

kbox: 0.12.0-beta.1
osx: 10.11.4

Have you previously installed Kalabox? If so, what version?

no

Give a brief description of what happened, including any error messages that appeared.

during initial pull from pantheon:

> Failed after 5 retries. {"max":5,"backoff":500}: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /upenngrasp_db_1 AS /upenngrasp_terminus_run_35/database
> 
> Error: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /upenngrasp_db_1 AS /upenngrasp_terminus_run_35/database
> 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. download kalabox package
2. authenticate to pantheon
3. pull site, including files and db (via gui) -- error here.
4. try again to pull site, including files and db (via kbox terminal) -- same error.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

document how to do the pull manually in order to isolate the issue.

Does this bug prevent you from using Kalabox?

yes

**Comment by gremy** [comment]
+1 I have the same problem

**Comment by RobLoach** [comment]
Same here on EECS....

```
Linux 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
Pulling screenshot.
Pulling code.
Failed after 5 retries. {"max":5,"backoff":500}: VError: code: 1err:Starting eecs_data_1
Starting eecs_db_1
Cannot start container b340d363456c356db8bfb28c12f75256d8b38c4d96a5e57a13a4c50ee4e3d52f: Cannot link to a non running container: /eecs_db_1 AS /eecs_terminus_run_10/database

Error: VError: code: 1err:Starting eecs_data_1
Starting eecs_db_1
Cannot start container b340d363456c356db8bfb28c12f75256d8b38c4d96a5e57a13a4c50ee4e3d52f: Cannot link to a non running container: /eecs_db_1 AS /eecs_terminus_run_10/database

    at /home/rob/Documents/kbox-test/eecs/plugins/kalabox-plugin-pantheon/lib/terminus.js:130:17
From previous event:
    at /home/rob/Documents/kbox-test/eecs/plugins/kalabox-plugin-pantheon/lib/terminus.js:127:13
    at /usr/local/bin/lib/promise.js.jx:53:16
From previous event:
    at rec (/usr/local/bin/lib/promise.js.jx:52:25)
    at /usr/local/bin/lib/promise.js.jx:64:20
    at process._tickCallback (node.js:917:13)
```

**Comment by gremy** [comment]
Tried again on a fresh project on OSX, running into the same problem. (Project: stamp)

```
Pulling database.
Warning: Permanently added '[appserver.dev.6006bc87-6bcf-46e3-80c2-bc10e68bcd4f.drush.in]:2222,[104.130.221.181]:2222' (RSA) to the list of known hosts.
mysql --database=pantheon --host=dbserver.dev.6006bc87-6bcf-46e3-80c2-bc10e68bcd4f.drush.in --port=16610 --user=pantheon --password=aad0d0cae1024b31ba54369d0b5572a6
ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (113)
Pulling files.
Failed after 5 retries. {"max":5,"backoff":500}: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /stamp_db_1 AS /stamp_terminus_run_6/database

Error: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /stamp_db_1 AS /stamp_terminus_run_6/database

    at /Users/gremy/.kalabox/apps/stamp/plugins/kalabox-plugin-pantheon/lib/terminus.js:130:17
From previous event:
    at /Users/gremy/.kalabox/apps/stamp/plugins/kalabox-plugin-pantheon/lib/terminus.js:127:13
    at /usr/local/bin/lib/promise.js.jx:53:16
From previous event:
    at rec (/usr/local/bin/lib/promise.js.jx:52:25)
    at /usr/local/bin/lib/promise.js.jx:64:20
    at process._tickCallback (node.js:917:13)
```

**Comment by pirog** [comment]
You probably don't want to post MySQL connection info in GitHub

On Thursday, May 19, 2016, Emanuel Greucean <notifications@github.com>
wrote:

> Tried again on a fresh project on OSX, running into the same problem.
> (Project: stamp)
>
> Pulling database.
> Warning: Permanently added '[appserver.dev.6006bc87-6bcf-46e3-80c2-bc10e68bcd4f.drush.in]:2222,[104.130.221.181]:2222' (RSA) to the list of known hosts.
> mysql --database=pantheon --host=dbserver.dev.6006bc87-6bcf-46e3-80c2-bc10e68bcd4f.drush.in --port=16610 --user=pantheon --password=aad0d0cae1024b31ba54369d0b5572a6
> ERROR 2003 (HY000): Can't connect to MySQL server on 'database' (113)
> Pulling files.
> Failed after 5 retries. {"max":5,"backoff":500}: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /stamp_db_1 AS /stamp_terminus_run_6/database
>
> Error: Error: HTTP code is 500 which indicates error: server error - Cannot link to a non running container: /stamp_db_1 AS /stamp_terminus_run_6/database
>
>     at /Users/gremy/.kalabox/apps/stamp/plugins/kalabox-plugin-pantheon/lib/terminus.js:130:17
> From previous event:
>     at /Users/gremy/.kalabox/apps/stamp/plugins/kalabox-plugin-pantheon/lib/terminus.js:127:13
>     at /usr/local/bin/lib/promise.js.jx:53:16
> From previous event:
>     at rec (/usr/local/bin/lib/promise.js.jx:52:25)
>     at /usr/local/bin/lib/promise.js.jx:64:20
>     at process._tickCallback (node.js:917:13)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1358#issuecomment-220402013>
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by gremy** [comment]
@pirog right, fixed

**Comment by RobLoach** [comment]
Might want to fix in your comment too, @pirog :+1: .

**Comment by pirog** [comment]
?

**Comment by gremy** [comment]
you have a "Quote" as a reply to my  comment, which contains my unedited old comment.

**Comment by possiBri** [comment]
Getting same error here on a fresh install (after uninstalling beta8) on Mac 10.10.5

**Comment by pirog** [comment]
So sadly this was a breaking change introduced upstream in the mariadb image
https://github.com/docker-library/mariadb/commit/cc686f56875aa84d135bb89de6ca50385211bdab

**Comment by pirog** [comment]
As a workaround for now you can edit `/conf/mysql/my.cnf` so that the user is now `mysql`

```bash
#
# The MySQL database server configuration file for Kalabox
#

[mysqld]
#
# * Basic Settings
#
# Data is stored in a volume on the db container /sql
user = mysql
datadir = /var/lib/mysql
default-storage-engine = innodb

#
# Instead of skip-networking the default is now to listen only on
# localhost which is more compatible and is not less secure.
bind-address = 0.0.0.0
#
# * Fine Tuning
#
key_buffer    = 384M
max_allowed_packet  = 32M
thread_stack    = 400K
thread_cache_size       = 8
# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched
myisam-recover         = BACKUP
#max_connections        = 100
#table_cache            = 64
#thread_concurrency     = 10
read_rnd_buffer_size = 8M
myisam_sort_buffer_size = 64M
table_open_cache = 512
sort_buffer_size = 2M
read_buffer_size = 2M

#
# * Query Cache Configuration
#
query_cache_limit = 1M
query_cache_size = 64M
#
# * Logging and Replication
#
# Both location gets rotated by the cronjob.
# Be aware that this log type is a performance killer.
# As of 5.1 you can enable the log at runtime!
#general_log_file        = /src/.kalabox/log/mysql.log
#general_log             = 1
#
# Error logging goes to syslog due to /etc/mysql/conf.d/mysqld_safe_syslog.cnf.
#
# Here you can see queries with especially long duration
#log_slow_queries = /var/log/mysql/mysql-slow.log
#long_query_time = 2
#log-queries-not-using-indexes
#
# The following can be used as easy to replay backup logs or for replication.
# note: if you are setting up a replication slave, see README.Debian about
#       other settings you may need to change.
#server-id    = 1
#log_bin      = /src/.kalabox/log/mysql-bin.log
expire_logs_days = 10
max_binlog_size = 100M
#binlog_do_db   = include_database_name
#binlog_ignore_db = include_database_name
#
# * InnoDB
#
# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
# Read the manual for more InnoDB related options. There are many!
#
# Uncomment the following if you are using InnoDB tables
#innodb_data_file_path = ibdata1:2000M;ibdata2:10M:autoextend
#innodb_log_group_home_dir = C:\mysql\data/
# You can set .._buffer_pool_size up to 50 - 80 %
# of RAM but beware of setting memory usage too high
#innodb_buffer_pool_size = 384M
#innodb_additional_mem_pool_size = 20M
# Set .._log_file_size to 25 % of buffer pool size
#innodb_log_file_size = 100M
#innodb_log_buffer_size = 8M
innodb_flush_log_at_trx_commit = 0
#innodb_lock_wait_timeout = 50
innodb_buffer_pool_size = 384M
innodb_log_buffer_size  = 4M
innodb_file_per_table   = 1
innodb_open_files       = 256
innodb_io_capacity      = 512
innodb_flush_method     = O_DIRECT
innodb_thread_concurrency = 8
innodb_lock_wait_timeout = 120
#
# * Security Features
#
# Read the manual, too, if you want chroot!
# chroot = /var/lib/mysql/
#
# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".
#
# ssl-ca=/etc/mysql/cacert.pem
# ssl-cert=/etc/mysql/server-cert.pem
# ssl-key=/etc/mysql/server-key.pem

[mysqldump]
quick
quote-names
max_allowed_packet  = 32M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer = 384M
key_buffer_size = 256M
sort_buffer_size = 256M
read_buffer = 2M
write_buffer = 2M

```

And then 

```
cd /path/to/my/app
kbox restart
kbox pull
```

**Comment by pirog** [comment]
Ok everyone! I've fixed this upstream over in our pantheon app
https://github.com/kalabox/kalabox-app-pantheon/commit/801335f147569f6203df0e54257ed707bf83f96e

I would delete any previous apps that had this issue and then try recreating them. This seems to resolve the issue.

**Comment by macronomicus** [comment]
Nice! wow you guys are fast, looking forward to testing this :)
Cheers!

**Comment by pirog** [comment]
thanks @macronomicus

**Comment by richyumul** [comment]
Hi  - I'm still running into this issue, and a 

kbox destroy  +
kbox create

didn't change anything.  Is there a step that I'm missing?

Thanks
Rich

**Comment by richyumul** [comment]
I'm not really sure;  it seems that a reboot resovled the issue for me.

When I looked at the processes (when I was getting the error), there were 2
syncthing processes running, that appeared to be non responsive.  I'm not
sure if that might be related?

On Thu, Jul 7, 2016 at 12:02 PM, Mike Pirog <notifications@github.com>
wrote:

> @richyumul <https://github.com/richyumul> when you recreate does it pull
> down the new image or seem to just use the one that is already there?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1358#issuecomment-231175513>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCtfRalnK3Ymhf3TefiFtqstYroRIkSks5qTU1BgaJpZM4IiZ-P>
> .
>



-- 
Rich Yumul
rmy@sagetree.net
Sage Tree Solutions
http://www.sagetree.net
