### ISSUE TITLE
kbox rebuild fails for curl phantomjs 2.1.1 with a 403 forbidden (can't fix)(workaround)

### ISSUE THREAD

**Issue by bradchesney79** [kalabox/kalabox#1359]
Bug Report
==========

What is your Kalabox version and operating system?

N/A

Have you previously installed Kalabox? If so, what version?

v0.12 beta1

**Tell us about your bug**

So, after a quantity of installs/rebuilds Amazon will begin to send you a 403 error instead of phantomjs-2.1.1... as detailed here [https://github.com/ariya/phantomjs/issues/13962](https://github.com/ariya/phantomjs/issues/13962)

WORKAROUND:
Upload the phantomjs bzipped archive somewhere else and modify your {{kbox-name}}/dockerfiles/pantheon-appserver/Dockerfile for the curl to match.

I am using:

https://github.com/bradchesney79/phantomjs-2.1.1-aws-failure-mirror/raw/master/phantomjs-2.1.1-linux-x86_64.tar.bz2

Could better documentation have prevented this issue? if so what should we change?
Not really, maybe. 

Does this bug prevent you from using Kalabox?
Yes, it blocks kbox rebuild.

Maybe kalabox might host this file instead of relying on the phantomjs server resources that fail... or maybe script a failover to other equivalent hosted resources in case of 403... Meh. Few people will have this problem, me and whoever is banging on a crummy inherited Pantheon app. But, can't fix/won't fix is fine as long as this workaround is discoverable.

**Comment by bradchesney79** [comment]
Upon further reading there is an npm mirror on github that already exists:
[https://github.com/Medium/phantomjs/releases/tag/v2.1.1](https://github.com/Medium/phantomjs/releases/tag/v2.1.1)

and consequently:
[https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2](https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2)

There were some grumblings that were talked about. [https://github.com/ariya/phantomjs/issues/13953](https://github.com/ariya/phantomjs/issues/13953)

Interesting to see people talking about development vs. distribution... Never occurs to you until it affects you kind of thing.

**Comment by pirog** [comment]
@bradchesney79 i saw the github release version you mentioned above. Maybe we should update the dockerfile to pull from there instead? 

I don't think this is going to impact anyone but the most hardcore developers but seems like an easy enough, and testable enough change.
