### ISSUE TITLE
Installing Kalabox on windows with a user folder that is not in `C:\Users`

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1362]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v0.12.0-beta1 on Windows 10 Professional 64-bit

Have you previously installed Kalabox? If so, what version?

I've installed a few previous versions, none of which I could get working properly. I have since gone through the uninstallation steps before installing the latest version to try and ensure starting from a clean slate.

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

Install completed successfully, but there's no Kalabox VM created, the GUI just continuously says it's starting the Kalabox engine, and the CLI errors out trying to create a site with the following:

"TypeError: Cannot read property 'AuthOptions' of undefined
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docker\machine.js.jx:264:34"

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Install Kalabox with all default options from the latest 0.12-beta1 installer
2. Try to run Kalabox GUI or try to set up a new site using the CLI

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Possibly, will know more once I know what's actually wrong.

Does this bug prevent you from using Kalabox?

Yes.

My assumption is an old Kalabox installation (or attempted uninstallation) set my system to some state that the Kalabox installer can't detect or recover from. But I'm unsure how to troubleshoot further. 

Here's the latest setup log:
[Setup Log 2016-05-20 #005.txt](https://github.com/kalabox/kalabox/files/275392/Setup.Log.2016-05-20.005.txt)

**Comment by bmcclure** [comment]
I think this might somehow be related to the location of %HOMEPATH% on my computer.

%HOMEPATH% itself returns C:\Users\bmcclure, and that's where, for example, the old uninstaller .bat looks for the directory. It's also where I would expect it to be, given all the similar dot-directories in C:\Users\bmcclure.

However, I've moved the location of my profile folders such as Documents and Downloads to D:\bmcclure\Documents, etc. When installing Kalabox, the installer is putting .kalabox under D:\bmcclure\.kalabox. Incidentally, Docker Machine also seems to have installed a .docker folder under D:\bmcclure\ the same way.

Then when running Kalabox, it creates C:\Users\bmcclure\.kalabox and adds "logs" and "pantheon" directories there. This makes me think that Kalabox likely is not looking in the right place half of the time, and could be the cause of my issues.

**Comment by bmcclure** [comment]
I think I've got a workaround in place.

I manually moved D:\bmcclure\\.kalabox to C:\Users\bmcclure\\.kalabox and then re-ran the installer.

The installer again put everything under D:\, however since I already had the files in the right directory, the installer took a lot longer and actually set up the environment, and I can now use the GUI properly.

I'm running into another issue now trying to clone a site with Kalabox, but I don't think it's related, so this can probably be closed.

**Comment by gremy** [comment]
When I tried installing on Windows I had the same problem. I also have my profile folders moved to D:.

**Comment by pirog** [comment]
Sadly because of a restriction currently imposed on us by docker i dont think we can support user folders that are not in `C:\Users`

**Comment by pirog** [comment]
Here is a related issue https://github.com/kalabox/kalabox/issues/1266

**Comment by bmcclure** [comment]
@pirog That makes sense, but what I don't get is why it thinks my user folder is D:\bmcclure when everything else on my system seems to know that it's C:\Users\bmcclure. Even though I've got my Documents, Downloads, etc. folders located on D, my user profile folder itself is still C:\Users\bmcclure, so I don't understand why Docker and Kalabox are the only two apps I have that are trying to use D:\bmcclure as the location.

After manually moving over the .kalabox folder and then reinstalling, it's been working slightly better, but I still can't get any sites pulled down and just get a fairly constant stream of errors the entire time I'm trying to. I can't figure out if that's related to it still trying to use the wrong folder for some things or not, however.

**Comment by pirog** [comment]
@bmcclure i think the reason for that misidentification is likely because of
#1186 and #1245 which we are slated to fix in the upcoming release

**Comment by pirog** [comment]
Going ot close this in favor of #1245
