### ISSUE TITLE
Cannot start container ... : Cannot link to a non running container: ... on FRESH INSTALL

### ISSUE THREAD

**Issue by AubreyR** [kalabox/kalabox#1363]
Bug Report
==========

**What is your Kalabox version and operating system?**

v0.12.0-alpha22 on Ubuntu 16.04 LTD

**Have you previously installed Kalabox? If so, what version?**

Yes, I've installed Kalabox v0.12.0-beta1

**Tell us about your bug**

I started with a fresh OS install.  I attempted to install the latest version Kalabox v0.12.0-beta1, and it failed miserably (php errors).  Two of my co-workers said they were successfully running alpha22, so they gave me the .deb file for that package.  I removed the beta1 version using apt, and manually removed the .kalabox folder from my home directory.  I also downloaded and ran an older uninstall script I found on the kalabox github.  Then, I installed the alpha version, and when I attempt to create a pantheon app, I receive the following message:

`Running post start tasks.
Running post create tasks.
Pulling screenshot.
Pulling code.
Failed after 5 retries. {"max":5,"backoff":500}: VError: code: 1err:Starting aubreyviu_data_1
Starting aubreyviu_db_1
Cannot start container 939269bd406354562c5e395bc64a476a84b98e5725d4fe78869afc4cba9df66e: Cannot link to a non running container: /aubreyviu_db_1 AS /aubreyviu_terminus_run_20/database

Error: VError: code: 1err:Starting aubreyviu_data_1
Starting aubreyviu_db_1
Cannot start container 939269bd406354562c5e395bc64a476a84b98e5725d4fe78869afc4cba9df66e: Cannot link to a non running container: /aubreyviu_db_1 AS /aubreyviu_terminus_run_20/database

    at /home/aubrey/kbox/aubrey-viu/plugins/kalabox-plugin-pantheon/lib/terminus.js:130:17
From previous event:
    at /home/aubrey/kbox/aubrey-viu/plugins/kalabox-plugin-pantheon/lib/terminus.js:127:13
    at /usr/local/bin/lib/promise.js.jx:53:16
From previous event:
    at rec (/usr/local/bin/lib/promise.js.jx:52:25)
    at /usr/local/bin/lib/promise.js.jx:64:20
    at process._tickCallback (node.js:917:13)
`

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

After the installation steps described above
Run `kbox create pantheon` from the CL and attempted to pull down a pantheon site

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Please have a universal sanitization script, that will cleanly remove all previous versions of kalabox.
Links to version-specific uninstall scripts.

Does this bug prevent you from using Kalabox?

Yes.  This is my first experience with Kalabox.  It looks promising and I require it for work, but it seems to me that there are absolutely no versions of Kalabox out there that I can find and successfully install.

**Comment by pirog** [comment]
Hey @AubreyR,

This looks like #1358 which *should* be resolved now.

That said we definitely run and test beta1 on 16.04 pretty thoroughly and we actually aren't a php based product so if you are getting php errors it could indicate something wrong with your drupal installation. 

`apt-get` should reliably uninstall Kalabox at least as of beta1. I would also definitely post the php errors you are seeing with beta1.
