### ISSUE TITLE
Make "Dev" Default Environment When Creating/Pulling/Pushing a Site

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1365]
Feature/Enhancement Request
===========================

**User Story**

As a Kalabox user who creates sites often and doesn't always read the form, it'd save me time for the default environment to be "Dev", since many of my sites I create (or push to) don't have multi-dev environments.

**Solution**

Make "Dev" the default environment on these forms.

**Comment by pirog** [comment]
👍
