### ISSUE TITLE
External Access for * through Host Bridge

### ISSUE THREAD

**Issue by mael5trom** [kalabox/kalabox#1367]
I've spent time time tinkering with scripts, but each time I end up reverting my changes.

How do we go about exposing ports to 0.0.0.0 rather than 127.0.0.1.  I'd like to setup kalabox in a hosted docker solution and provide dev's to environments as needed to facilitate workflow needs in our systems.

Thanks,

**Comment by pirog** [comment]
This is not one of the supported use cases of Kalabox at this time. 

That said, i *think* all you need to do this is change the port settings in your kalabox-compose.yml for the relevant services. These are just docker compose files so you should check the documentation over there. 

You may also need to disable the kalabox services plugin which handles setting local `.kbox` domains. These domains are routed via the kalabox proxy container which binds to 80 on 0.0.0.0 so you will likely need to remove that container as well.
