### ISSUE TITLE
Error checking out code during "kbox create"

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1370]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v0.12.0-beta1 on Windows 10 Professional 64-bit

Have you previously installed Kalabox? If so, what version?

Yes, all alpha versions, but they've since been uninstalled fully.

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

When trying to clone a new site from Pantheon, while checking out the code an error is received:

```
Resolving deltas: 100% (24791/24791), done.
Checking connectivity... done.
error: Untracked working tree file '.stfolder' would be overwritten by merge.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

1. Start a command prompt window
2. cd to location where the project should be created
3. Run "kbox create pantheon" and select the right site and environment
4. Wait a while
5. Error comes up while cloning the repository

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

I'm not sure at this point.

Does this bug prevent you from using Kalabox?

I think so. I have a few other issues, but this seems to prevent a site from being created properly.

**Comment by bmcclure** [comment]
Is this simply because I don't have .stfolder in the app's .gitignore prior to trying to clone it down with kbox?

**Comment by pirog** [comment]
Yes. I think committing the `.st*` files to your repo can cause problems.

**Comment by bmcclure** [comment]
That did turn out to be the issue--we had accidentally committed the .stfolder file, so then future attempts to clone the site with kbox resulted in that error.

Not a bug in kalabox then, so I think this can be closed.

It does seem like it could be made clearer within the application that .st* (or whatever the recommended line is) should be added to the .gitignore file when cloning a site (perhaps it could just check if it's in the file and spit out a notice at the end if it's not).

Thanks for your assistance with this!

**Comment by pirog** [comment]
@bmcclure agreed this could be clearer and i do think there is an open issue to document this. ahhh yes #1295

**Comment by pirog** [comment]
Good news here is that we've removed syncthing in forthcoming stable 0.13 releases so this should no longer be an issue!
