### ISSUE TITLE
Uninstall should stop running Docker processes and remove Docker images

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1372]
Bug Report
==========

What is your Kalabox version and operating system?

`kalabox-v0.12.0-beta.1`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Have you previously installed Kalabox? **Yes, most recent alpha and beta versions**

Give a brief description of what happened, including any error messages that appeared.

**If you just remove the package, ie. `$ sudo dpkg -P kalabox`, the Docker images remain.  In general, this method won't remove anything other than the package itself anyway so maybe an uninstaller script would be better?  Maybe adding more operations in https://github.com/kalabox/kalabox/blob/v0.12/linux/scripts/postrm would do the trick?**

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

**Just running the postrm script is not thorough enough of an uninstall.**

Could better documentation have prevented this issue? if so what should we change?

**Yes, adding full uninstall instructions in the documentation would help.  This is not necessarily intended as "I want to uninstall Kalabox and never use it again" but rather, "I want to uninstall Kalabox so I can start with a clean slate". :)**

Does this bug prevent you from using Kalabox? **No**

**Comment by pirog** [comment]
@uberhacker if you do the uninstall with `--purge` do you get the desired functionality? maybe we should have that happen by default?

**Comment by pirog** [comment]
@uberhacker what version are you using? If looks like this is supposed to happen already on uninstall vai the `prerm` script https://github.com/kalabox/kalabox/blob/v0.12/linux/scripts/prerm

```bash

#!/bin/bash

set -e
set -u

# We are probably on systemd?
if [ -d /run/systemd/system ]; then
  if ! { [ -x "$(which systemctl)" ] && "$(which systemctl)" version 2>/dev/null; }; then
    systemctl stop kalabox.service 2>/dev/null || true
    systemctl disable kalabox.service 2>/dev/null || true
  fi
else
  service kalabox stop 2>/dev/null || true
fi

# Wait until the process is killed
while [ -f /usr/share/kalabox/docker.pid ]; do
  echo "Waiting for process to end..."
  sleep 1
done

# Remove other docker files
rm -rf /usr/share/kalabox/docker.*
```

**Comment by pirog** [comment]
Another thing is there a difference when you uninstall with `-P` vs `-r`?

**Comment by uberhacker** [comment]
@pirog: Sorry, not sure how to use the --purge option.  Are you referring to the kbox cli command?  But yeah, I think purging by default makes sense.  By not doing it, there is the potential where several sites could take up a huge amount of disk space with all the containers each site needs.  Whenever I uninstall an app, I always expect the uninstaller to remove all residue.  One of my pet peaves. :)

**Comment by uberhacker** [comment]
@pirog: So it does look like `sudo apt-get remove kalabox` also removes the images.  However, if I leave the GUI open and run this command, it doesn't close the session and remove site instances.  Also, it doesn't look like there is any difference between `sudo apt-get remove kalabox` and `sudo apt-get purge kalabox`.  Maybe `sudo apt-get purge kalabox` can/should completely uninstall everything including any running Kalabox GUI sessions and site instances?

**Comment by pirog** [comment]
As far as I know this is what happens. At least it does for me.

Does it only not remove everything if the GUI is open?

**Comment by uberhacker** [comment]
It stops the site instance but doesn't remove it.

**Comment by pirog** [comment]
It should delete the entire docker instance.

**Comment by uberhacker** [comment]
It does delete all the Docker containers with the exception of the site
instance.  You still can see the site instance in the GUI after you install
again.

On Mon, May 30, 2016 at 12:22 AM, Mike Pirog <notifications@github.com>
wrote:

> It should delete the entire docker instance.
>
> On Sunday, May 29, 2016, Ed Reel <notifications@github.com> wrote:
>
> > It stops the site instance but doesn't remove it.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/1372#issuecomment-222400064>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAri0AxM-srgCX7WeK_8DwEmlO1mvfJOks5qGktdgaJpZM4Im7nU
> >
>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1372#issuecomment-222413560>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXraerhqcS-uY4QGjHdrod5YwMs-4Yxks5qGnQCgaJpZM4Im7nU>
> .
>



-- 
"God gave us two ears and one mouth to remind us we should listen twice as
much as we talk."

**Comment by pirog** [comment]
OK got it! I think we might be crossing terminology a bit here :)

So just to summarize what we want to do here is

1. Make sure any running processes are killed in the pre-remove step. This is likely the GUI but could be the CLI as well
2. Make sure any GUI/CLI config is deleted
3. Continue with current uninstall process

**Comment by jserrao** [comment]
I noticed when I uninstalled the .dmg for OSX it left the hidden .kalabox directory in my `users\username` directory, complete with my test site in there.

**Comment by pirog** [comment]
Thanks @jserrao. Good to know.
