### ISSUE TITLE
kbox env command has incorrect description

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1373]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

*Kalabox 0.12.0-beta.1 - Mac OS X 10.11.5*

Have you previously installed Kalabox? If so, what version?

*Yes, previous alphas and the beta*

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

*Running `kbox` to get a list of commands gives the wrong description for the `kbox env` command.*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> 1. Type `kbox`
> 2. Hit enter
> 3. Read descriptions
> 4. Be confused

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

*Yes, please either change the description for the `env` command, or change the env command to `restart` which is what I'm assuming goes with that description.*

Does this bug prevent you from using Kalabox?

*Nope*

![image](https://cloud.githubusercontent.com/assets/756265/15557853/485ee438-229b-11e6-99c2-365c95dfaf71.png)

**Comment by pirog** [comment]
nice catch! thanks!
