### ISSUE TITLE
Syncthing continuously uses a lot of CPU, explore alternatives

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1374]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v0.12.0-beta1 on Windows 10 Professional 64-bit

Have you previously installed Kalabox? If so, what version?

Yes, all prior alpha releases.

**Tell us about your bug**

After installing Kalabox and cloning one site from Pantheon (which I haven't gotten working in Kalabox yet, but exists none-the-less), syncthing started using a bunch of CPU. It's been a few hours now, and syncthing is chewing up between 10 and 20% CPU continuously (on a quad-core i7 with 8 logical cores).

I don't know if this is a bug with Kalabox or not, but it doesn't seem desirable and I didn't find any other issues directly related to this (though syncthing's CPU usage was mentioned in a few other issues).

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Create a site from Pantheon using the CLI
2. Monitor running processes and watch syncthing's CPU usage

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Possibly, but it's too early to tell. Maybe I just did something wrong, or maybe it's a bug with syncthing and not Kalabox.

Does this bug prevent you from using Kalabox?

No.

**Comment by cwahlfeldt** [comment]
This is happening to me as well - syncthing is using nearly 300% cpu.

**Comment by pirog** [comment]
syncthing is pretty resource intensive. we hope to switch it out for "native" file sharing once docker beta resolves that issue on their end.

**Comment by mainiak** [comment]
@pirog, what issue has 'docker beta' to resolve? Can you please explain a little bit?

**Comment by pirog** [comment]
https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076

**Comment by mainiak** [comment]
@pirog thanks!

**Comment by pirog** [comment]
Sure thing. We don't anticipate that docker will imrpove this for at least a few months. In the meantime we are likely going to offer an alternative to syncthing in our first official 0.13.x release.

**Comment by pirog** [comment]
Having done rough prototyping we are considering replacing syncthing with unison for OSX and Windows. Here is a branch tracking that
https://github.com/kalabox/kalabox/tree/1374-unisonFS

**Comment by mainiak** [comment]
@pirog, I'm glad that you are removing syncthing, because during our security internal office audit we have found that syncthing (within Kalabox) is listening with its administration without password on all interfeces - as you can see [here](https://github.com/kalabox/kalabox/blob/8231345e3d8bd6b7f2fe245bf04fc4a278d4e1f6/plugins/kalabox-sharing/dockerfiles/syncthing/config.xml)

**Comment by pirog** [comment]
Doubt that is much an actual security issue but i hear you.

**Comment by macronomicus** [comment]
Nice, It seems much faster now, everything is improved and better in this release.

One issue with unison tho, I am getting all .tmp file & folder names inside the /code directory
.unison.sites.09e750e3a87ca3e27f3e5081efb83981.unison.tmp
.unison.mytheme.info.yml.09e250e3a87ca3e27f3e4081efb83981.unison.tmp

Im on version 0.13.0-beta.2 
windows 10pro

**Comment by pirog** [comment]
those should only show up during the initial sync. have you tried recreating the app? 

i would also open another issue for it since this thread is about syncthing.
