### ISSUE TITLE
Get `kbox up` and `kbox down` to work on linux, change description of commands

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1375]
Bug Report
==========

What is your Kalabox version and operating system?
**`kalabox-0.12.0-beta.1`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```**

Have you previously installed Kalabox? **Latest versions of both alpha and beta releases**

Give a brief description of what happened, including any error messages that appeared.

**If I close Kalabox, the Docker processes remain active.**

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

**Start a site from the UI.  Open a Terminal session.  Close Kalabox.  Return to the Terminal session and type `$ docker ps`.  You should see the processes of the previously running site.**

Does this bug prevent you from using Kalabox? **No**

**Comment by pirog** [comment]
What do you mean by "closing" Kalabox? Exiting the GUI or something else?

**Comment by uberhacker** [comment]
Yes, I meant closing the GUI.  I'm thinking the expected behavior is all running containers should be stopped.  If you stop any site in the GUI, it looks like allontainers for that site close except the dns container.  Not sure why that container remains open.  If you manually stop the dns container, it won't start again when you start the site.  In order to get it working again, I needed to uninstall and reinstall Kalabox.

**Comment by pirog** [comment]
@uberhacker DNS container issue should be resolved, at least with respect to autostarting it when needed.

**Comment by uberhacker** [comment]
@pirog: Awesome, TY!

**Comment by pirog** [comment]
Sure thing! Going to keep this open until we figure out how to resolve the actual issue posted

**Comment by pirog** [comment]
@uberhacker so the main issue here is if we do this via the GUI it will require a password prompt since `service kalabox stop` requires `sudo`. 

On the command line with `kbox up` and `kbox down` that seems reasonable to me but prompting for a password every time you stop the GUI seems... bad to me.
