### ISSUE TITLE
Panda Free AntiVirus on Windows 10 detects Kalabox as infected

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1379]
What are you guys embedding inside the installer? :-P

![infected](https://cloud.githubusercontent.com/assets/387945/15590448/82a6902e-235d-11e6-872b-9f89681a3c59.png)

**Comment by pirog** [comment]
STEAL ALL YOUR DATAZ!

**Comment by uberhacker** [comment]
Oh no!  I've been PWNED!

**Comment by pirog** [comment]
Transparent open source software is definitely the best way to PWN! The closer we are to danger the farther we are from harm!

**Comment by uberhacker** [comment]
Agreed but you gotta wonder what is triggering the false positive in Panda.

**Comment by pirog** [comment]
I'm guessing it's the fact that the app is not currently signed. There is an issue that addresses this.

**Comment by bradchesney79** [comment]
For a modestly ridiculous sum I will personally sign the software. Just meet me with the payment on the tarmac before I fly off to my undisclosed compound in central america. Better give me your social security number, bank account info, and a short list of your favorite go-to passwords just in case though... I'm like this with the Panda guys. :dancers:

**Comment by pirog** [comment]
@bradchesney79 how *modest* are we talking here?

**Comment by bradchesney79** [comment]
(It was a comment of levity-- you don't want me to sign your software. My signature on your software would only placate the clueless and confuse the people that know better. I'm not even sure the cert I was given to use is still valid. Aaand, it only matters for Windows users. All that being said...)

*little finger to corner of mouth*

"One million dollars."

(And if I'm wasting your time by replying, I should also give a reminder to send me a bill. You've got to have burned through the five hours by now...)

**Comment by pirog** [comment]
Going to close this in favor of #1334 which is the underlying problem
