### ISSUE TITLE
Fix Protractor Tests on Travis

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1380]
Bug Report
==========

**Tell us about your bug**

Currently the following Protractor tests do not work on Travis and had to be removed:

- app has connection info
- throws an error when trying to use duplicate app name with a hyphen'
- throws an error when trying to use duplicate app name
- initialize module tests should have initialize text

To replicate this, simply...

1. git revert 4fe50c09ab8b751720c8585cecd8a5b7472f38c4 and 7f2b649fb4cd59b5c41261cd908a55511755fff9

2. Push to a separate feature branch and kalabox-ui travis tests will fail in protractor

**Comment by pirog** [comment]
@reynoldsalec doing some house cleaning and going to close this since i feel like it is covered elsewhere
