### ISSUE TITLE
Pantheon DEV URL redirect's to local .kbox domain

### ISSUE THREAD

**Issue by erok415** [kalabox/kalabox#1381]
**Tell us about your setup**

What is your Kalabox version and operating system?
Mac OS El Capitan, v10.11.2

**Tell us about your bug**
This is happening on two separate local environments. Once I've installed Kalabox on my local and have made a code change...any code change...and I've pushed the code up to Pantheon, the following happens.

When I navigate to the Pantheon DEV URL, I'm forwarded to my local .kbox domain. Any clue why this is happening.
Erik

**Comment by pirog** [comment]
There is nothing in Kalabox that would cause this to happen. We don't add any code to your site or hijack DNS requests.

**Comment by pirog** [comment]
hey @erok415 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!
