### ISSUE TITLE
Opening modals in GUI causes error "Warning: a promise was created in a handler but was not returned from it"

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1382]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v0.12.0-beta2 on Mac OSX

Have you previously installed Kalabox? If so, what version?

Yes (all recent releases).

**Tell us about your bug**

1. Start up GUI
2. Start a pantheon site.
3. Click on "Connection Info", "Pull Site", or "Push Site"
4. You should receive an error in the console:

```
Warning: a promise was created in a handler but was not returned from it
```

**Tell us more**

This isn't a show-stopper bug, but it is probably also related to the incredible lag some pop-up modals have before they show up.

Steps for resolution:

- [ ] Resolve error (probably something to do with the way promises are being executed with the uibModal open) 
- [ ] If that doesn't solve the performance issue, investigate that for recommendations on a further issue

**Comment by pirog** [comment]
@reynoldsalec as far as i can tell here this is just an option bluebird sets when you are in dev mode. i dont think these should show up in production.
