### ISSUE TITLE
Where is the wiki ?

### ISSUE THREAD

**Issue by martic** [kalabox/kalabox#1385]
I see issues referring to the wiki https://github.com/kalabox/kalabox/wiki

Has it been removed? or is it private ?

**Comment by bradchesney79** [comment]
If it helps, documentation is something that many of the kalabox team made scrunchy faces & grumblings about-- we may be bearing witness to kalabox documentation 2.0 in progress.

**Comment by labboy0276** [comment]
There is a couple places that point to the docs:

http://www.kalabox.io/

Also on the github page here: https://github.com/kalabox/kalabox#kalabox Last line.

Here is the link:
http://support.kalabox.io/support/solutions

It is still a work in progress but that is where the wiki went.

**Comment by martic** [comment]
Thanks I saw all those, but some of the issues referred to the wiki, so I thought I was missing out on some useful info.
I've had issues installing on one of my PC's (both actually but one sort of works had to use Hosts file) and I was trying to find correct way to uninstall a very early version that I gave up on. I think I have it correct but now getting same as #1386 & #1387.

**Comment by pirog** [comment]
Yes! We know our docs leave a lot to be desired but we are working on it!
