### ISSUE TITLE
[bug fix] Unable to activate Solr Power

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1388]
```
Kalabox Version 0.12.16 (0.12.16) on Mac OSX 10.11.5 (15F34)
Solr Power 0.3.0 -  WordPress 4.5.2
I've never installed Kalabox before.
```

**Issue brief description:**

Is not possible to activate the [**Solr Power**](https://github.com/pantheon-systems/solr-power) Pantheon WordPress Plugin. 

**Detailed steps:**

1. Installing "Solr Power" via Composer
2. Click on "activate"
3. Get the error `Submitting the schema failed with the message`

The issue seems related to the `SOLR_PATH` constant check here:

 [https://github.com/pantheon-systems/solr-power/blob/12abfec7fb9d2d783971320f8596404368e1d082/includes/class-solrpower-api.php#L103](https://github.com/pantheon-systems/solr-power/blob/12abfec7fb9d2d783971320f8596404368e1d082/includes/class-solrpower-api.php#L103)

and here:

[https://github.com/pantheon-systems/solr-power/blob/c482736045f93e19ae19de3de0b9df7dce0b9b4c/includes/class-solrpower.php#L39](https://github.com/pantheon-systems/solr-power/blob/c482736045f93e19ae19de3de0b9df7dce0b9b4c/includes/class-solrpower.php#L39)

**Additional Note:**

The same code has been pushed to the DEV Environment on Pantheon. Plugin activated and working.

**Sadly, issue prevents Solr testing and usage inside Kalabox.**

**Comment by pirog** [comment]
@yumyo good to know. We haven't tested out SOLR support for anything besides drupal 7 at this point but we certainly would like to support this at some point.

**Comment by pirog** [comment]
Going to close this in favor of #1364
