### ISSUE TITLE
Please exclude Windows files and directories in the Linux package

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1389]
I've noticed Windows files and directories exist after installing kalabox-v0.12.0-beta.1.deb in Ubuntu.  I'm trying to get away from Windows "bloat". ;)

Sample of files greater than 50M:
```
52M	/home/ed/kalabox-ui/dist/kalabox-ui-win64-v0.12.14.zip
59M	/home/ed/kalabox-ui/cache/0.12.3/win64/nw.exe
67M	/home/ed/kalabox-ui/nw/Kalabox/win64/Kalabox.exe
```

**Comment by pirog** [comment]
@uberhacker there is nothing in the deb package that installs to this location. I'm pretty sure its actually not allowed for a deb package to put something in $HOME. 

It looks like you might have cloned down the kalabox-ui project at some point and then run `grunt build` or `grunt pkg`?

**Comment by uberhacker** [comment]
@pirog: You are right.  Silly me.  I did clone the repo.  My bad.  Sorry to waste your time.  Thanks
