### ISSUE TITLE
Consistent Version Numbers

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1390]
Feature/Enhancement Request
===========================

Not sure if this should be considered a feature request or a bug....the version numbers are presented differently depending on how you access them. On a Mac, when I type `kbox version`, it returns 0.12.0-beta.1. However, when I go into the GUI and click about, it says version 0.12.16.

**Comment by pirog** [comment]
I *think* the only version that is different between all the components is the GUI version and this is because NWJS does not allow us to use pre-release conventions :(

**Comment by Mchampsee** [comment]
Then what about making the command line and file name be 0.12.16-beta.1?

**Comment by pirog** [comment]
I think that would be *MORE* confusing? As soon as we are out of beta this will be more manageable. 

That said as long as the CLI and GUI are separate projects i think its not horrible they have different version numbers. Particularly i would hate to be in a position where we need to roll a trivial (read only version bump) release of the GUI or the CLI just to maintain parity.

**Comment by Mchampsee** [comment]
Fair enough.
