### ISSUE TITLE
Problem with pantheon SSH keys

### ISSUE THREAD

**Issue by coccoinomane** [kalabox/kalabox#1392]
Hello!

I use Kalabox v0.12.16 on OSX 10.11.4; I installed Kalabox via DMG. This is my first installation of Kalabox.

As soon as the installation process ended, I added a Pantheon website via the Kalabox App. However, the installer hung up for an hour on "Pulling Code", with no network activity.

I removed the container thus created and tried again using the command line: `kbox create pantheon`; you can find the output of the command [here](https://github.com/kalabox/kalabox/files/299005/kbox_create_log.txt). During the process I had to type my Pantheon password three times, as Kalabox could not find my ssh keys:

```
Warning: Permanently added '[appserver.dev.a5258019-b2bd-4c28-b74a-2311d5282c3c.drush.in]:2222,[104.130.221.192]:2222' (RSA) to the list of known hosts.
no such identity: /user/.ssh/pantheon.kalabox.id_rsa: No such file or directory
```

It seems that Kalabox is looking for my ssh keys in `/user/.ssh/` rather than in `/Users/coccoinomane/.ssh/`, where the `pantheon.kalabox.id_rsa` public and private keys are contained.

After inserting my password three times, kbox gave me the BOOMSHAKALAKA message, and the container correctly showed up in the GUI. The code folder however was empty, and the website was a plain Wordpress installation without any of the content I had on Pantheon.

Thank you for your attention!
Cheers,
Guido

**Comment by pirog** [comment]
`/user/.ssh/pantheon.kalabox.id_rsa` is the location inside of the container. It *should* map your local `$HOME` to `/user` inside of the container. 

Do you have a non-standard set up of your local `$HOME` directory?

**Comment by coccoinomane** [comment]
Hi! Sorry for the late reply. No, I do not have anything unusual going on for my `$HOME`. Please let me know if there is anything I can do to help :-)

**Comment by pirog** [comment]
@coccoinomane hmmm very strange. definitely have not seen this pop up on mac ever. do you have any weird permissions for ~/.ssh that might impact the sharing?

**Comment by pirog** [comment]
@coccoinomane 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!
