### ISSUE TITLE
apps folder deleted when you run the uninstall script

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1394]
This is to move over a conversation with @pirog.

When you run the uninstall script, it deletes the entire `~/.kalabox` directory. The GUI by default installs newly created sites into the `~/.kalabox/apps` folder which would delete those sites upon uninstall. Conclusion was to:

1. Install relevant "system" files in more appropriate locations, on OSX this would probably be the application bundle itself
2. Give the user a choice of where to install the app but have it default to something like ~/kalaboxapps.

**Comment by pirog** [comment]
awesome! thanks for moving this over @Mchampsee

**Comment by pirog** [comment]
So we've bundled most of the dependencies on OSX directly into the Kalabox.app which means we don't need to touch `~/.kalabox` anymore on an uninstall. 
See https://github.com/kalabox/kalabox/pull/1411
