### ISSUE TITLE
Call to undefined function mysql_connect() when attempting to use wp-cli

### ISSUE THREAD

**Issue by cwahlfeldt** [kalabox/kalabox#1397]
Bug Report
==========

**Tell us about your setup**

Kalabox Version : 0.12.0-beta.1
OS              : Mac OSX 10.11.5

**Have you previously installed Kalabox? If so, what version?**

This is the only version of Kalabox that I've installed.

**Tell us about your bug**

Created a wordpress site on pantheon and pulled it down to my local machine with kalabox (kbox create pantheon). WP-CLI doesnt work and throws the following error when attempting `kbox wp`

    PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /code/wp-includes/wp-db.php:1522
    Stack trace:
    #0 /code/wp-includes/wp-db.php(658): wpdb->db_connect()
    #1 /code/wp-includes/load.php(371): wpdb->__construct('pantheon', 'pantheon', 'pantheon', 'database:3306')
    #2 phar:///usr/local/bin/wp/php/wp-settings-cli.php(100): require_wp_db()
    #3 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(807): require('phar:///usr/loc...')
    #4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(755): WP_CLI\Runner->load_wordpress()
    #5 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
    #6 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
    #7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
    #8 {main}
      thrown in /code/wp-includes/wp-db.php on line 1522
    Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /code/wp-includes/wp-db.php:1522
    Stack trace:
    #0 /code/wp-includes/wp-db.php(658): wpdb->db_connect()
    #1 /code/wp-includes/load.php(371): wpdb->__construct('pantheon', 'pantheon', 'pantheon', 'database:3306')
    #2 phar:///usr/local/bin/wp/php/wp-settings-cli.php(100): require_wp_db()
    #3 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(807): require('phar:///usr/loc...')
    #4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(755): WP_CLI\Runner->load_wordpress()
    #5 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
    #6 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
    #7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
    #8 {main}
      thrown in /code/wp-includes/wp-db.php on line 1522

**Replicate**

> 1. Create a pantheon wordpress site.
> 2. Pull down to local computer with kalabox (`kbox create pantheon`)
> 3. Make sure site is up and running (`kbox start` if needed)
> 4. Run `kbox wp` and get error

**Tell us more**

May have something to do with the PHP version or PHP CLI version?
http://stackoverflow.com/questions/34579099/fatal-error-uncaught-error-call-to-undefined-function-mysql-connect

**Does this bug prevent you from using Kalabox?**

Not entirely but it puts a big dent in my workflow.

**Comment by pirog** [comment]
My guess is similar. Probably running php7 in the wpi-cli container because its the default version of the base image. 

This is the same root issue as #1369

**Comment by cwahlfeldt** [comment]
So maybe the next version will support php 5.5 with wp-cli?

**Comment by pirog** [comment]
Thats the idea

**Comment by yumyo** [comment]
+1

**Comment by mustela** [comment]
Looking forward to see that new version coming! Since having the same issue with wp-cli :)

**Comment by pirog** [comment]
This should be resolved in the NOT YET OFFICIAL 0.13.x release

**Comment by irakligeek** [comment]
Did anyone have a fix for this? I am unable to use wp-cli because of the fatal error:
call to undefined function mysql_connect(). I am using it on windows MAMP and wp-cli uses the same version of php as MAMP. Any advice?
