### ISSUE TITLE
Gulp workflow not updating app & `kbox gulp` not working?

### ISSUE THREAD

**Issue by cwahlfeldt** [kalabox/kalabox#1398]
# Bug Report

**Tell us about your setup**

Kalabox Version : 0.12.0-beta.1
OS              : Mac OSX 10.11.5

**Have you previously installed Kalabox? If so, what version?**

This is the only version of Kalabox that I've installed.

**Tell us about your bug**

Using Sage (https://roots.io/sage/) as the theme starter kit - I ran npm install, bower install, and gulp locally. I then ran gulp watch locally and the assets were built locally but wouldnt update the site at all. Are they not syncing correctly? I get the following error when running the `kbox gulp` command while in the themes directory.

`~/.kalabox/apps/nogle-properties/code/wp-content/themes/nogle-sage   master  kbox gulp`

```
/code/wp-content/themes/nogle-sage/node_modules/node-sass/lib/index.js:14
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding /code/wp-content/themes/nogle-sage/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/code/wp-content/themes/nogle-sage/node_modules/node-sass/lib/index.js:14:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/code/wp-content/themes/nogle-sage/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:409:26)
```

**Replicate**

> 1. Create a pantheon wordpress site.
> 2. Pull down to local computer with kalabox (`kbox create pantheon`)
> 3. Make sure site is up and running (`kbox start` if needed)
> 4. `cd ~/.kalabox/apps/[wp_sitename]/code/wp-content/themes/ && git clone https://github.com/roots/sage.git` then `cd sage`
> 5. `sudo npm install`
> 6. `bower install`
> 7. `gulp`
> 8. `gulp watch` - creates assets and uses browsersync settings located in `./assets/manifest.json`
> 9. `ctrl c` and attempt to 'kbox gulp' or `kbox gulp watch`.

**Tell us more**

It seems that the containers assets are not being built or are not being built fast enough? Syncthing starts draining my CPU to 200+ % when using `gulp watch` locally. I didnt think that was even possible.

**Does this bug prevent you from using Kalabox?**

Yes at least for wordpress right now.

**Comment by pirog** [comment]
@cwahlfeldt this is an area that needs a lot more help re: docs but i think there are a few things here

1. You probably want to use either exclusively `kbox` tooling or `local` tooling. If you use `kbox` then the stuff should get built directly inside of the containers (thus being immediately available) and then synced out to your machine. 

```
kbox npm install
kbox bower install
kbox gulp
```

2. I'm not sure we've got `gulp watch` working correctly yet. But if you are using it locally then it might take a second for syncthing to get all the new assets. Once docker beta has better native file sharing this hopefully wont be a problem.

Unrelated: generally you don't want to be using `sudo` with `npm install
`https://blog.explosionpills.com/dont-use-sudo-with-npm/

**Comment by cwahlfeldt** [comment]
when running `kbox npm install` for the first time, I get the following errors: https://gist.github.com/cwahlfeldt/f5330dd99a817b466c61e7b6b49d278c

**Comment by pirog** [comment]
Looks like your package.json contains some native build dependencies that we don't currently ship with the npm container. We would have to add those in. Do you know what the actual packages are that you need?

`autoreconf` seems like an obvious one, do you know of others?

**Comment by cwahlfeldt** [comment]
Heres the package.json - https://github.com/roots/sage/blob/master/package.json. Python2 was mentioned in the logs. Is there anyway to shell into the containers environment? `kbox terminal` doesn't work.

**Comment by pirog** [comment]
imagemin-pngcrush is the thing it complains about so i would look in there.

python should definitely be in container already. looks like its failing on a different dep.
