### ISSUE TITLE
Error: /.ssh/pantheon.kalabox.id_rsa.pub (Connecting via SSH Key)

### ISSUE THREAD

**Issue by drzambr** [kalabox/kalabox#1401]
Hi Kalabox,

Running Kalabox v0.12.0-beta1 -- on Mac OS X, Mavericks

I am trying to connect to a Pantheon account from Kalabox and it seems that Kalabox sees the account. But in the middle of the connection attempt, the process hangs or times out and I receive the following error message:

---**Generated Error Message**---

**_Danger Will Robinson!_**

_**Error dispatching event listeners [post-create-configure]: ENOENT: no such file or directory, open '/Users/ [home directory] /.ssh/pantheon.kalabox.id_rsa.pub'**_

---**End of Error Message**---

I am able to connect successfully to the Pantheon account from a terminal/command line, using 'git' and with the generated SSH key (for Pantheon access). The public SSH key is currently stored in the standard path '_/Users/ [home directory]/.ssh/id_rsa.pub_'.

It seems that when I attempt to connect to the Pantheon account Kalabox is looking for the 'id_rsa.pub' key under a different name (pantheon.kalabox.id_rsa.pub) other than the standard name (id_rsa.pub).

How may I go about resolving this issue?

Many thanks.
Dean

**Comment by pirog** [comment]
We generate SSH keys for you and they should live in `~/.ssh`. Do you not see any there?

**Comment by drzambr** [comment]
I do not see Kalabox-specific SSH keys in the ~/.ssh directory. I only see the standard SSH keys that I generated and installed. Might it be to a permission problem or is there a way to manually generate them?

**Comment by pirog** [comment]
Hmmm yeah weird. Kalabox should generate them when you login to Pantheon. What do you have for perms and ownership on `~/.ssh`?

And yeah if you just manually create them with `ssh-keygen` and give them the names `pantheon.kalabox.id_rsa.pub` and `pantheon.kalabox.id_rsa` i * think* it should start to work. 

Definitely more curious as to why they are not getting generated though.

**Comment by pirog** [comment]
Going to close this in favor of #1392
