### ISSUE TITLE
Better support and documentation on working with non-Pantheon sites

### ISSUE THREAD

**Issue by ironsizide** [kalabox/kalabox#1402]
Setup: v0.12.0-beta1 on OSX 10.11.3, I tried alpha4 but could never get it to quite work.

**Feature/Enhancement Request**
As a Kalabox user who often has to work with sites that aren't on Pantheon and would like to use a common local dev environment, I would like the site setup to be more consistency between pulling a Pantheon site down and spooling up a new Drupal 7/8 site.

**Background**
I've developed a technique for working with non-Pantheon Drupal sites in Kalabox. My technique is thus:
1. Start up a new Drupal 7 site in Kalabox (or Drupal 8 if you're lucky enough)
2. Once spooled up and active (green power icon in Kalabox UI), click on site icon to start install script (automatically brought up in your default browser).
3. Install the site (This is only to let Kalabox setup the database user, database, and settings file as placeholders automatically for you.)
   - Snags: The settings file has incorrect permissions. Install script with report it can't write to the file.
     Solution: Set the file permissions to 777 ([sudo] chmod 777 [filename]).
   - Snags: Install script asks for DB settings - what are they?
     Solution: The proper DB settings can be found by clicking on the gear icon for the site in the Kalabox UI
     - Choose the Connection info item
     - Enter the info on the right side of the pop up, opening the advanced tab in Drupal to enter the host name
       (incidentally, the left column info will get you hooked up to the DB in Sequel Pro).
4. Delete the existing code in ~/.kalabox/apps/[name you chose]/code after the install script is completed.
5. Clone the code repo from bitbucket into the app's directory (~/.kalabox/apps/[name you chose]/code).
6. Export the site's DB (drush sql-dump --result-file=[insert name here]) (if desired, use the compression flags).
7. Copy the SQL locally (scp works well).
8. Import the sql file (in the app's directory): kbox drush sql-cli < [name of SQL file]
   - Snags: SQL file isn't executed completely.
     Solution: Use Sequel Pro to import the file manually. 
     - Connect to the database using the info described in 3.b.ii above.
     - Select all of the existing tables and delete them.
     - File > Import... and choose the file to import.
     - If the variables table exists after the import is complete, you should be golden.
9. Download files directory manually if desired.

Site should now work!

**However, the Problem**
I was having endless trouble getting XDebug to work with non-Pantheon sites. I could have sworn it was working at one point - and it turns out it had - just only with Pantheon sites. As it turns out, new local-first sites are spun up in a completely different manner than sites pulled from Pantheon. New sites are very bare-bones - no xdebug, no redis, no solr, no varnish. Additionally, the site is using apache instead of nginx.

For me, the biggest issue is no xdebug. But I would love to see better options through the GUI to pick and choose how the base machine image is set up. Apache or NginX? Xdebug? Barring that, and option to use the Pantheon machine image (plugin?) over the base php one would be great. Anything that would let me use XDebug with the same ease would make me happy.

In the meantime I suppose I will look more closely at the kalabox.yml and kalabox-compose.yml files and see what I can cobble together for a revised technique.

**Comment by pirog** [comment]
@ironsizide 

Great write up here. Eventually would be great to get these in our new docs once those are up. 

We plan on offering a pointy-clicky way of installing a bunch of services and extensions as part of our kalabox pro product but are a few months away from that.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
