### ISSUE TITLE
GUI unresponsive after about an hour

### ISSUE THREAD

**Issue by devkinetic** [kalabox/kalabox#1403]
v0.12.16 on OSX El Capitan

As simple as it states. After a while I can no longer use the GUI, it just sits there in whatever state it was in last I used it. The docker containers keep running, but the only way to get functionality back is to:

- Force close the app
- Start it again
- Gracefuly close the app
- Start it up

This will work until it eventually will freeze again, and the process must be repeated.

**Comment by pirog** [comment]
Hey @devkinetic i think we've got a few other tickets similar to this so i would def look for those.

That said this should be resolved in the next release.

**Comment by mustela** [comment]
Hey there! 

Having the same issue here. Is there any estimated date for the next release?

Thanks you and thanks for the great app you are building!

**Comment by macronomicus** [comment]
Yeah, I have found on windows at least its best to use the cli and not the app, the app hangs up when the passkey fails.  If you look through the issues cue here you can see they've noticed most if not all of whats up and are working on it.  

I hope Pantheon folks throw Kalabox some love!  It makes Pantheon even more awesome than it is already. :)

**Comment by pirog** [comment]
WE CERTAINLY ARE WORKING ON IT! :)
