### ISSUE TITLE
Blank site: KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT variable is not set

### ISSUE THREAD

**Issue by imorale2** [kalabox/kalabox#1404]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Macbook, El Capitan 10.11.5

Have you previously installed Kalabox? If so, what version?

Kalabox Version 0.12.16 (0.12.16)

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

I get a blank screen on the browser everytime I pull a site. The code is there and thumbnail image and the service is on. I have tried uninstalling/installing kalabox, deleting, pulling the app.

![screen shot 2016-06-22 at 10 56 17 am](https://cloud.githubusercontent.com/assets/8496687/16281021/343e1acc-3877-11e6-949d-aff7f5caec2b.png)

When I try kbox rebuild I get the following error:

WARNING: The KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_INDEX_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_ENVIRONMENT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_LOGGED_IN_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CACHE_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_CLI_WORKING_DIR variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_ROOT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_NAME variable is not set. Defaulting to a blank string.

Does this bug prevent you from using Kalabox?

Yes I practically can't use the app at all.

**Comment by pirog** [comment]
Thanks for the report here. It looks like your SSH key is not being automatically set up so that is troubling.

**Comment by pirog** [comment]
The WARNING here is not an issue. Regarding the SSH key, going ot close this in favor of #1392
