### ISSUE TITLE
kbox drush fails with GID 1001 does not exist

### ISSUE THREAD

**Issue by quietone1** [kalabox/kalabox#1421]
This is my first attempt to use kalabox and I find that 'kbox drush' fails with an error that GID 1001 does not exit. On my system my user account has uid:gid of 1001:1001. 

```
me@minasithil:~/.kalabox/apps/d81$ kbox drush --version
adduser: The GID 1001 does not exist.
me@minasithil:~/.kalabox/apps/d81$ su root
Password:
root@minasithil:/home/me/.kalabox/apps/d81# kbox drush --version
adduser: Warning: The home directory `/home/0' does not belong to the user you are currently creating.
 Drush Version   :  8.1.2
root@minasithil:/home/me/.kalabox/apps/d81# su other
other@minasithil:/home/me/.kalabox/apps/d81$ kbox drush --version
 Drush Version   :  8.1.2
```
Other that modifying my uid::gid, is there any other way to get around this?

kbox 0.12.0-beta.1 on Debian Jessie

**Comment by pirog** [comment]
#1253

**Comment by quietone1** [comment]
I have updated the issue according to #1254 but there are no tags because I can't enter any.
Please reopen.

**Comment by pirog** [comment]
@quietone1 i think its safe to keep this closed since #1253 is already open and appears to be a duplicate of this issue. please correct me if i am wrong.

**Comment by quietone1** [comment]
@pirog, my apologies. Clearly I missed that while searching.

**Comment by pirog** [comment]
@quietone1 no problem. just trying to keep our queue as tidy as possible so we can best resolve issues and handle correspondence.
