### ISSUE TITLE
Support docs on website give invalid SysV / Upstart commands

### ISSUE THREAD

**Issue by kmbremner** [kalabox/kalabox#1428]
On this page:
http://support.kalabox.io/support/solutions/articles/14000006360-installing

> sudo kalabox service start
> sudo kalabox service stop
> sudo kalabox service status
> sudo kalabox service restart

Should be:
> sudo service kalabox start
> sudo service kalabox stop
> sudo service kalabox status
> sudo service kalabox restart

**Comment by pirog** [comment]
Coincidently we are rebooting our docs right now and i have just made this change! thanks a bunch
https://github.com/kalabox/kalabox/commit/89c0185388f7b7a35f06f71942d9088fbaaea66f
