### ISSUE TITLE
[feature] xip.io support

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1430]
Add [xip.io](http://xip.io/) support for local multi-device testing.

**Comment by yumyo** [comment]
Hi, any planned release date for this feature?

**Comment by pirog** [comment]
@yumyo no.

1. We are focusing on stability improvements going into our official release
2. We are going to need more than one person requesting a feature to add it. 

that said, if you are interested in doing visual regression testing on multiple devices you can check out our still experimental wraith plugin.
https://github.com/kalabox/kalabox-plugin-wraith

**Comment by yumyo** [comment]
thanks very much for clarifying @pirog 

Personally I think that nowadays and looking to the future this feature is a must, at least to my workflow but probably in any shared team producing web sites. Regression tests are good but I see them more as a companion than as replacement for real device testing. The latter could be performed via the remote Dev or Stage server but is highly inefficient, especially in an initial development context. 
After googling a bit, xip.io support in Docker doesn't look that hard but I got no proper knowledge to really say so. I could just hope more people will subscribe to this feature. 
At this stage I can't see any other option for me than switching back to Vagrant. However, I'll keep following your developments to see how Kalabox will eventually evolve. Keep up the good work.

**Comment by pirog** [comment]
@yumyo you've got to do what's best for you. hopefully more people support this
