### ISSUE TITLE
Syncthing on Mac OS X 10.9.5: Cannot Authenticate on Syncthing page after upgrade

### ISSUE THREAD

**Issue by drzambr** [kalabox/kalabox#1432]
Hi,

I have Kalabox-0.12.0-beta.1 running on Mac OS X (Mavericks or OS X: 10.9.5). 
I was experiencing trouble with syncthing; my website on my Firefox browser is not updating after I perform code edits. The original website before the changes, remain.

I accessed the syncthing and I receive a message to update the version. After the upgrade, I can no longer access syncthing. When I try to access the site, I receive a message to enter a username and password (for authentication). I tried entering different logins and passwords but to no avail.

My questions are the following:
1. Is there a way to resolve this authentication issue?
2. If not, is there a way to reinstall only the syncthing plugin, without the need to uninstall and remove the entire Kalabox app or more importantly, the 'code' directory? 

It took me a while to get other components, like Grunt, to work with the files in the directory and I would prefer to not (remove or even touch) the code directory unless it is absolutely necessary.  

Many thanks,
Dean

**Comment by pirog** [comment]
Kalabox only works with the version of syncthing that we install so upgrading is going to break the integration. 

Manually reinstalling just syncthing is possible but it will be much easier to just reinstall kalabox entirely.

All that said we are actually going to drop a new release sometime next week. This new release gets rid of syncthing completely so you might just want to wait for that.

**Comment by drzambr** [comment]
Thanks for the feedback. I will wait and install the new release when it is rolled out this coming week.
