### ISSUE TITLE
[v0.13.0-alpha.1] Apps are not longer being created under /apps

### ISSUE THREAD

**Issue by mustela** [kalabox/kalabox#1433]
Using `v0.13.0-alpha.1` when creating an app from pantheon, it is not longer being created under `~/.kalabox/apps/` but under `~/.kalabox` which is complicated to work with.

So not sure if it is a bug, a configuration issue, or on purpose.

Thanks

**Comment by pirog** [comment]
V0.13 Alpha1 is a prerelease and we don't recommend using it at this point
but thanks for posting this

On Monday, July 4, 2016, Emiliano Jankowski <notifications@github.com>
wrote:

> Using v0.13.0-alpha.1 when creating an app from pantheon, it is not
> longer being created under ~/.kalabox/apps/ but under ~/.kalabox which is
> complicated to work with.
>
> So not sure if it is a bug, a configuration issue, or on purpose.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kalabox/kalabox/issues/1433>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAri0CNydM8TzvF5RMWpPLYXjPExEcVhks5qSV4NgaJpZM4JEnUG>
> .
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by mustela** [comment]
Yes I know, but didn't see this issue reported :)

Feel free to close if you already have it in your list

**Comment by pirog** [comment]
GOT IT! Just doing the due diligence on our end :)

Thanks so much for all your feedback. It really helps a lot.

**Comment by pirog** [comment]
Moved this into the backlog for investigation

**Comment by pirog** [comment]
@mustela 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!

**Comment by mustela** [comment]
Thanks a lot @pirog will take a look!
