### ISSUE TITLE
Container command '/src/local/scripts/php-fpm.sh' not found or does not exist.

### ISSUE THREAD

**Issue by sandipsclarion** [kalabox/kalabox#1437]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
 v0.12.0-beta1 on Windows 8.1 Eternprise*
64 Bit 
DockerToolbox-1.11.2

Have you previously installed Kalabox? If so, what version?

Yes, I've installed kalabox-v0.12.0-beta.1*

**Tell us about your bug**

I am trying to use docker project with kalabox.
my docker repo structure is as per screenshot
![codeace-folder-structure](https://cloud.githubusercontent.com/assets/16461960/16677834/6c0e88ba-448e-11e6-905a-3dd51bb4baa7.png)

**when i enter to api directory and run the command kbox start, some process is working, but after some time it shows me an error as per below**

![kbox-start-codeace](https://cloud.githubusercontent.com/assets/16461960/16677852/9283fb56-448e-11e6-9f6e-f34bb43b30da.png)

![codeace-error](https://cloud.githubusercontent.com/assets/16461960/16677855/9836191c-448e-11e6-9d0b-10f0684ab1a5.png)

**i have mention this path in kalabox-compose-override.yml file as per below**

![kalabox-compose-codeace](https://cloud.githubusercontent.com/assets/16461960/16677873/b08367b8-448e-11e6-9e98-879ca44ce4f0.png)

**as per the screen shot there is file is exist but why this is error coming.Please help me.
I stuck here from 1 week.**

**Comment by pirog** [comment]
@sandipsclarion what is the full path to your project? Projects must live somewhere inside of `C:\Users`

**Comment by sandipsclarion** [comment]
@pirog 
C:/Users/user/codeace-docker

**Comment by pirog** [comment]
@sandipsclarion i was able to replicate this although it was on the latest 0.13.x release.

**Comment by pirog** [comment]
So, at least for me, this seems to be an issue around the scripts having Windows line endings instead of Unix ones. 

As a workaround manually changing the line endings back to unix seems to fix the issue for me. That said we definitely need to figure out why this is happening.

**Comment by sandipsclarion** [comment]
@pirog 

"As a workaround manually changing the line endings back to Unix seems to fix the issue for me. That said we definitely need to figure out why this is happening."


Please let me know, exactly  how to make this line ending changes for windows.

**Comment by pirog** [comment]
@sandipsclarion changing line endings is going to depend on a lot of things, such as the editor you use to edit code. i would recommend googling with the particulars of your set up.

that said the files you need to edit are the scripts inside of the `config/script` directory in your app. You can also edit the broader plugin that creates the apps (so that the initial create completes without an error) which on windows should be something like `C:\Program Files\Kalabox\plugins\kalabox-app-pantheon\app\config\scripts`

**Comment by pirog** [comment]
This will be fixed in our next release.
