### ISSUE TITLE
Add php5.6 and php7 support

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1438]
Pantheon is now rolling out PHP 5.6/7 support via terminus.  It would be great if we could do the same in kalabox using terminus so that we can use xdebug and so forth to debug php7 issues.

I tried running this command:

kbox terminus site set-php-version

But got this error:

PHP Warning:  unlink(/home/1000/.terminus/cache/session): Device or resource busy in phar:///usr/local/bin/terminus/php/Terminus/Caches/FileCache.php on line 200

I'm running kbox beta 1 on OS X El Capitan.

**Comment by pirog** [comment]
This seems like two separate issues? 

On the php5.6 and 7 front we are down to support these things but are currently focusing on machine token integration as our next big feature.

For `kbox terminus site set-php-version` are you using this to try and set your kalabox app's php version or a remote pantheon site's version? I would open another ticket with that particular issue.

**Comment by ptmkenny** [comment]
Related issue on `terminus site set-php-version`: #1444

**Comment by joshkoenig** [comment]
This is now managed in `pantheon.yml` so it shouldn't be more transparent to manage.

**Comment by pirog** [comment]
@joshkoenig awesome! although to clarify for kalabox users, the `pantheon.yml` file will **only impact your pantheon environments** and can not be used to change your local kalabox settings.

That said/at some point it might be worth getting kalabox to read the same file `pantheon.yml` for locally relevant settings (php version, nested doc root, etc). Right now this stuff is stored in our own `kalabox.yml` file which for non-pantheon local envs is fine and straightforward but could be confusing for local pantheon envs.

**Comment by joshkoenig** [comment]
That's correct. Right now it would be odd to expect `pantheon.yml` to do anything to Kalabox.

However, it would be smart for us to try and evolve the kalabox app in that direction. More site configuration is going into `yml` soon. Next up is local drush version.

**Comment by joshkoenig** [comment]
@pirog what's the current thinking on how to support elements of the environment that are configurable like this? There are currently different dockerfiles for 5.3 and 5.5 but I'm not sure how they're chosen.

**Comment by pirog** [comment]
So we have a config section for each pantheon app that you can read about here
http://pantheon.kalabox.io/en/stable/users/config/#pantheon

Since all of our stuff is containerized by version it would be pretty easy to add things like drush version along with other things that you guys plan to make configurable to the user via `pantheon.yml` or other mechanism.

Seems like long term what we would want to do is 
1. troll the pantheon platform to make sure the local config still matches 
2. allow a `pantheon.yml` file to override/replace/something the kalabox config
