### ISSUE TITLE
`kbox create pantheon` Wordpress site not pulling correctly and install page showing

### ISSUE THREAD

**Issue by cwahlfeldt** [kalabox/kalabox#1448]
Bug Report
==========

**Tell us about your setup**

Kalabox Version : 0.13.0-alpha.1-10-gd589bc0
OS                      : Mac OSX 10.11.5

**Have you previously installed Kalabox? If so, what version?**

I have installed 0.12.0 beta 1 but went through the uninstallation process without any issues.

**Tell us about your bug**

When creating a Wordpress site from pantheon, the pull process doesn't seem to be working correctly. When trying to access the site after its been created I encounter the Wordpress install page. I have attempted to rebuild the site using `kbox rebuild` without any avail.

**Replicate**

> 1. Create a pantheon Wordpress site
> 2. Pull down to local computer with kalabox (`kbox create pantheon`)
> 3. Make sure site is up and running (`kbox start` if needed)
> 4. Attempt to access the site only to find the Wordpress install screen
> 

**Tell us more**

It seems as though the database doesn't get pulled down, or at all. 

**Does this bug prevent you from using Kalabox?**

Yes, for wordpress.

**Comment by pirog** [comment]
@cwahlfeldt i assume that you've actually gone the WP install on Pantheon?

**Comment by cwahlfeldt** [comment]
Yes the site has already gone through the initial install

**Comment by cwahlfeldt** [comment]
Here it is in all its glory - hosted on pantheon http://www.mckenziewagner.com/

**Comment by pirog** [comment]
@cwahlfeldt do you get any kind of error reported or does it seem to fail silently? 

YES! SO MUCH GLORY!

**Comment by cwahlfeldt** [comment]
lol

Its failing silently from my understanding. Are there any logs I should be looking at?

**Comment by pirog** [comment]
http://docs.kalabox.io/en/stable/troubleshooting/ might avail you

**Comment by cwahlfeldt** [comment]
oooo is this new? looks nice!

**Comment by pirog** [comment]
fresh off the press. its a little rough still but WAY better than what we had before.

**Comment by cwahlfeldt** [comment]
I dont know if this will even help but I cant really decipher these logs myself. https://gist.githubusercontent.com/cwahlfeldt/95411a158acaafade2d989072e3ed516/raw/ffa0fb3ca4885af71a3aac9f53c8049ad660e285/.log

**Comment by pirog** [comment]
lol yeah, the logs are not the easiest to read. i'd also make sure there is no sensitive data in there like mysql connection strings. So when we pull the site DB these are the commands we run

```bash
kbox drush @pantheon.mw-responsive.dev sql-connect
kbox drush @pantheon.mw-responsive.dev sql-dump
kbox mysql -u $DB_USER p$DB_PASSWORD -h $DB_HOST $DB_NAME
```

I would go into the site you pulled down and try to run the first two `kbox drush` commands and see if they give you any errors at all. Note that while you have a WP site these drush commands should still work. That said, it might be worth exploring a `wp-cli` based implementation although, being primarily a drupal user, i am less clear on how to do that. Any help there would be appreciated.

**Comment by pirog** [comment]
@cwahlfeldt 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!
