### ISSUE TITLE
Remove `kalabox-ui` plugin (token containers) and see if we can just use `kbox.app.list` and start stop events.

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1451]

**Comment by reynoldsalec** [comment]
It appears that listening directly to kbox events in the GUI should work fine. Made some initial progress. Site start/stop seem to be very reliable, and the siteStatus events are displaying fine on all actions.

Need to review:

- Site screenshot loading (could be related to #1439).
- Start state after create doesn't work.
- Destroy errors?

**Comment by pirog** [comment]
@reynoldsalec awesome. very excited to make GUI state changes more reliable.
