### ISSUE TITLE
Kill freshdesk and move everything over to RTD

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1457]
* Handle redirects
* Link Kalabox.io main `docs` nav to `docs.kalabox.io`

**Comment by reynoldsalec** [comment]
Created a project to automate the process of inserting Read the Docs redirects:

https://github.com/reynoldsalec/rtd-redirects

Redirects have been inserted and we have a spreadsheet of existing paths. After checking paths, I'm going to shut down Freshdesk.

**Comment by reynoldsalec** [comment]
Redirects look good, downgraded us to the Freshdesk free plan and switched over the domain.
