### ISSUE TITLE
link to supported http protocol in error modal

### ISSUE THREAD

**Issue by andrewmallis** [kalabox/kalabox#1459]
on  fresh uninstall/install of v0.12.16
I had some trouble stopping my app from the GUI.
The error modal was triggered. 

```$ kbox stop``` did it for me in the end.

I noticed in and clicked through to the wiki

----
<img width="622" alt="kalabox" src="https://cloud.githubusercontent.com/assets/249362/16789002/601e39a0-485e-11e6-9383-af125f2015dc.png">

----

https://support.kalabox.io/support/solutions

however the browser throws an SSL warning. 

Suggest linking to http://support.kalabox.io/support/solutions

**Comment by pirog** [comment]
@reynoldsalec might want to add this to your pass on GUI things. Do we want to link directly to the new http://docs.kalabox.io?

**Comment by reynoldsalec** [comment]
We need to also update the links on the hipache 500 pages.

**Comment by reynoldsalec** [comment]
@pirog I think we'll need to tag another hipache build on Docker hub to get the hipache links live, but otherwise deployed this work.

**Comment by pirog** [comment]
Word. So error modal in GUI is fixed plus you edited the hipache code?

**Comment by reynoldsalec** [comment]
Yep @pirog
