### ISSUE TITLE
v0.12.0-beta.1.dmg is timing out on mount

### ISSUE THREAD

**Issue by rtblair** [kalabox/kalabox#1461]
I'm trying to install v0.12.0-beta.1 on Mac OS 10 X Yosemite; when I try to mount the disk image downloaded from the release page (https://github.com/kalabox/kalabox/releases/tag/v0.12.0-beta.1), I get an error about a timeout. 

I have not installed Kalabox in the past. My machine is a fairly powerful Macbook Pro.

**Comment by pirog** [comment]
haven't seen this before. are you able to mount other images?

**Comment by rtblair** [comment]
Yes. All the time.

**Comment by pirog** [comment]
Do you get an actual error message when you try to mount it that you can post here?

**Comment by rtblair** [comment]
Closing this out. I'm pretty sure it was just a local issue that was arising from app store installs that were hung up. Sorry for the trouble, and thanks for being so responsive!
