### ISSUE TITLE
Pantheon APP never installs properly; GIT deleting everything after initial site pull. Reverting to last commit restores files but themes are broken

### ISSUE THREAD

**Issue by mbader** [kalabox/kalabox#1464]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
0.12.16
OS X Yosemite 10.10.5

Have you previously installed Kalabox? If so, what version?
no

**Tell us about your bug**

Created a Drupal 8 app from Pantheon. Site imported and started with a 500 server error. Found that the entire code directory was empty. Looked at the git history and apparently GIT deleted everything after initial install. Reverted to the last commit which fixed the 500 error, however the site has no CSS formatting and the Drupal Public files are all missing. have tried clearing/rebuilding cache multiple times; Actually have tried this entire process multiple times - always the same result. App is completely unusable

Does this bug prevent you from using Kalabox?

Yes

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

*Example: As a Kalabox user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how Kalabox can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by pirog** [comment]
@mbader i think these issues are resolved in the latest development release. 

By pantheon app i assume you just mean just drupal8 sites?

**Comment by mbader** [comment]
Yes that is correct, I'm trying to run a Pantheon Drupal 8 site environment. I am running the latest release as far as I can tell (0.12.0 beta 1)?

**Comment by pirog** [comment]
@mbader that is the latest stable release. I believe the issues you are experiencing will be resolved in the upcoming release which we hope to put out in a few days.

**Comment by pirog** [comment]
Hey @mbader 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)

If the issue persists please reopen this (or submit a new) issue!

**Comment by mbader** [comment]
Thanks @pirog , I tried installing 0.13.0-beta.2 this morning and the app wont run at all after installation. Kalabox.app is in Applications, however I get "The application Kalabox.app can't be opened". Kalabox also won't show up in spotlight.

**Comment by pirog** [comment]
@mbader were you able to get this to work using the workaround posted in https://github.com/kalabox/kalabox/issues/1477#issuecomment-234587432 ?
