### ISSUE TITLE
v0.12.0-BETA1 Fatal Error: Call to undefined function drush_startup() on line 115 [bug]

### ISSUE THREAD

**Issue by Senpai** [kalabox/kalabox#1467]
I found no open issues containing "drush_startup", so I'm opening this new [bug].

Bug Report
==========

**Tell us about your setup**

Mac OS 10.11.5 with a fully uninstalled (including all manual steps) + fresh install of Kbox v0.12.0-BETA1

**Have you previously installed Kalabox? If so, what version?**

ALL THE VERSIONS. ;)

**Tell us about your bug**

Upon creation of a Pantheon app which is cloning an existing, working Pantheon DEV site, I experience the following error when running commands such as 'kbox pull' or a 'kbox drush help':

```
_kbox drush help_
PHP Warning:  include(/code/includes/startup.inc): failed to open stream: No such file or directory in /code/drush on line 113
PHP Warning:  include(): Failed opening '/code/includes/startup.inc' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /code/drush on line 113
PHP Fatal error:  Call to undefined function drush_startup() in /code/drush on line 115
```

Now, my command line drush _outside of_ a Pantheon app's .kalabox/APPNAME/code/ directory, such as .kalabox/APPNAME/ works just fine, and is reporting as v8.0.3. Inside it, however, it also predictably fails any and all drush commands because of the missing file.

**Does this bug prevent you from using Kalabox?**

Yes, it's a full stop on using this beta version until drush contains the missing "/code/includes/startup.inc" file.

**Comment by pirog** [comment]
@Senpai this generally works for me although im trying a drupal7 site. What are you using? I have a suspicion that maybe you have a local `composer.json` that installs `drush` locally and kbox is trying to find that instead of the one we ship with.

**Comment by Senpai** [comment]
@pirog Yeah, this one's a D7 site. And I do have Composer, although my local copy of Drush is installed via Homebrew.

The relevant lines of code in kbox's drush file are looking for __DIR__ . /includes/startup.inc which does not exist in this particular Pantheon app's code/ directory, and no amount of 'kbox destroy' + 'kbox create pantheon' will cause it to be there.

I'm tempted to try and manually install the version of Drush that 12.0-BETA1 ships with and see if I can make it run, but for the moment, I thought you'd want to know about this bug.

I also wonder if I should try replicating this problem using v 13.0-ALPHA1... but then I'd probably have to uninstall v12 all over again this week. :)

**Comment by pirog** [comment]
@Senpai , Your local install of `drush` shouldn't interfere. 

Do you see any `drush` related stuff in the `composer.json`? 

AFAIK we don't look for or require `/includes/startup.in` at least not in `/code`. We also don't put `drush` at `/code/drush` which seems to be the entrypoint for the command that is being run. My guess here is that for whatever reason our `drush` thinks there is a `drush` stored inside your code repo and is trying to invoke that instead of ours, except that it hasn't been installed because we haven't run `composer install`. 

If you run `kbox composer install` from your code directory it might get you going although i haven't played around much with using composer in this way with kalabox yet so no clue what that is going to do for you.

**Comment by pirog** [comment]
@Senpai also, if its possible to add me to your site that would be the best way to try and replicate! not sure if that is doable or not.

**Comment by Senpai** [comment]
@pirog Can't add you to this one, it's an active client site. But! What I could try is creating a Pantheon App using a freshly spun up Pantheon sandbox in order to see if it's the Kbox or my localhost vs. this particular Pantheon site?

**Comment by pirog** [comment]
That would be awesome.

We run a bunch of tests on vanilla versions of D7, D8 and Backdrop so those
all check out. If you try vanilla D7 then we at least we can probably guess
there is some interaction between your local setup and KBOX.

**Comment by Senpai** [comment]
So as I'm spinning up this new virgin D7 site to test things out, and I'm staring at the problem site's codebase, it occurs to me that, "When have I *ever* seen a copy of Drupal core with a drush file at the root of it!?"

NEVER.

Aaaand the new site's spun up and it's working fine. Kalabox isn't putting a randomly broken drushy thing into place during the app build process, this drush problem seems to be baked into this problem site's codebase! DOH!

Not a bug after all, well at least not in Kalabox. :) It's certainly a bug in this problem site's codebase though, and I'd sure like to know who put that file in there!

Closing this one as solved, and opening up a can of git blame.

**Comment by pirog** [comment]
DRUSH BINARIES IN THE GIT REPO!? WE DONT NEED NO DRUSH STINKIN BINARIES IN
THE GIT REPO!

**Comment by Senpai** [comment]
Hehe, parting thought from line 11 of the offending file:

/**
* - Never copy this script to your site root. Copy examples/drush instead.
**/

The irony is thick.
