### ISSUE TITLE
Actions -> Push -> Push Database To - Not Working?

### ISSUE THREAD

**Issue by bgonz** [kalabox/kalabox#1470]
Hi all - I am using Kalabox 0.12.16

I was hoping to use the feature of pushing the local Kalabox DB up to Pantheon DEV environment DB. 

- I created a new Drupal 7 site on Pantheon
- Added the new site to Kalabox (+Add site -> Click my Pantheon Acccount -> Shows List of my sites -> Choose new site)
- After kalabox clones/spinsup site -> View site in local browser
- I log into Kalabox D7 site
- Modules -> Disable Overlay Module (this was just a simple test - this could have been anything)

Now to push the Kalabox Database up to Pantheon - I tried:
Kalabox UI => Actions -> Push -> Push Database To -> Development Environment
- Added a Commit message "DB Push test"
- For "Push Files to" -> "I'm Good! (Don't Push My Files")

--- result

- Pantheon reads the commit on the Code Log
- The DEV environment Database did not get updated :(

Am I missing something?

Many thanks for your time.

**Comment by pirog** [comment]
Probably a stupid question but i assume you flushed the cache on pantheon?

**Comment by bgonz** [comment]
Never stupid Mike - but indeed - I did... and just to ensure - I did it again just now.

No Love.

Is it supposed to Upload my Kbox DB to the DEV on Pantheon? I assumed so by the UI - and you did not exactly tell me I was wrong - so there is hope!

**Comment by bgonz** [comment]
Well - I just did another one - this time a slew of kbox drush dl modules -> enabled them as well.

Then git commit.

Then back the Kbox UI (the UI was frozen - but I will save that for another issue) - after force quitting/starting/etc - Used the GUI to PUSH

- I saw Pantheon update
- Logged out of the site
- logged back in
- boOm!

Thanks Mike and Kalabox family.

**Comment by pirog** [comment]
Awesome! 

Re: UI we def fixed the frozen behavior you experienced and should roll that out in our next release which HOPEFULLY should be in the next few days.
