### ISSUE TITLE
GUI Freezes after viewing Popup Modals

### ISSUE THREAD

**Issue by bgonz** [kalabox/kalabox#1473]
I thought maybe this was just a one off bug, but indeed - I can replicate pretty consistently.

I am using Kalabox for light use at this point.
- New Spinup of site from Pantheon
- View the Connection Info from "Actions"
- The Info shows up in a Modal like info box
- If I leave Kalabox GUI to go work -> then come back about 10 mins later 
- I cannot close the Modal Info window

In fact - lets say I highlight the Port Number for DB - when I return to the GUI after the 10 mins -> I cannot click around the modal, select anything else.

I am forced to simple use Teminal -> kbox stop -> then force quite the app alltogether because quitting does not seem to change the GUI

**Comment by pirog** [comment]
Hey @bgonz 

I think this has been resolved in our hot off the press release. Check that out over at
https://github.com/kalabox/kalabox/releases/tag/v0.13.0-beta.2 (we haven't updated the download on kalabox.io yet) and def read the docs on how to [update your kalabox](http://docs.kalabox.io/en/stable/users/updating/)
