### ISSUE TITLE
Support other shells on Windows besides `cmd.exe`

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1475]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Beta 2 (downloaded from github on 7/21/16) on Windows 10 Home

*Example: v0.12.0-beta1 on Windows 8.1 Professional*

Have you previously installed Kalabox? If so, what version?
Had previous installed and removed alpha version (not sure which release)

**Tell us about your bug**

kbox up gives this error messages in terminal window:

$ kbox up
Unhandled rejection VError: Error bringing machine up.: Failed after 5 retries.                                                 {"max":5,"backoff":500}: EINVAL, invalid argument
    at C:\Program Files\Kalabox\bin\plugins\kalabox-engine-docker\provider\docke                                                r\machine.js.jx:74:13

It appears that the plugins directory is under Kalabox and not under Kalabox\bin

Virtualbox manager is installed and I can start Kalabox2 from there. I'm not sure whether this is anything else to test after that.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Started terminal (git bash)
2. cd .. (to get to c:\Users)
3. kbox up
4. Error as above

Just typing kbox gives me:

Usage: kbox.exe <command> [-- <options>]

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
do you get the same behavior using `cmd.exe` instead of `git bash`?

**Comment by jsibley2** [comment]
Thank you. I needed to use the Windows command prompt.

Now:
kbox gives me a list of commands
kbox up seems to work
kbox create pantheon gives me the prompts and I get through the prompts, then get:
Creating.
Cleaning up.
Creating app structure.
undefined
undefined

**Comment by pirog** [comment]
@jsibley2 can you open a separate issue for that? im going to change this to a feature request to support other shells beyond cmd.exe

**Comment by pirog** [comment]
also it might be useful to run that command again with the debug flag so you can get some more feedback on the issue you are having

```
kbox create pantheon -- -d
```

**Comment by pirog** [comment]
@jsibley2 so i am investigating this a little more and it looks like generally CYGWIN/MINGW64 shells don't play nice with Node (which is the language we write kalabox in)
https://github.com/nodejs/node/issues/3006

It looks like there are some workaround there though. I'm going to try a new other popular Windows shells out and see how they work. Either way i hope to provide greater support or at least recommend a shell for people to use.

**Comment by pirog** [comment]
Yeah @jsibley2, i think doing anything here is going to be a non-trivial amount of effort so i am going to bump the estimate here and move to the next sprint.

**Comment by jsibley2** [comment]
Not an issue for me, really. I'm fine with command.exe, just didn't know I had to use it.

**Comment by pirog** [comment]
@jsibley2 good to hear. I suspect other people are the same which is why im going to backlog this issue and save it for a rainy day. I will at least update our docs to make `cmd.exe` required.

**Comment by pirog** [comment]
Yeah AFAICT the facts in https://github.com/kalabox/kalabox/issues/1475#issuecomment-237379563 prevent us from supporting this
