### ISSUE TITLE
The application “Kalabox” can’t be opened

### ISSUE THREAD

**Issue by nc2-jordansmith** [kalabox/kalabox#1477]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Kalabox v0.130-beta.2 on MacBook Pro OSX 10.10

Have you previously installed Kalabox? If so, what version?
Yes: Kalabox v0.12.0-beta.1(which I fully uninstalled using uninstall script)

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.
I installed it normally, but it won't open.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
1) I install the new version v0.13.0-beta.2 and it gives the "The installation was successful" notice. 
2) I click to open the Kalabox Application as on previous version.
3) It pops up with the message: "The application “Kalabox” can’t be opened."

**Tell us more**

I can still install and run v0.12.0-beta.1 perfectly fine. However, I was hoping the new version would have fixed the issue with pulling a WP site.

**Comment by pirog** [comment]
Hmmm, we've got maybe 50 current active users using the new version on OSX so im not exactly sure what could be going on here. Have you looked at something like this?
http://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

**Comment by nc2-jordansmith** [comment]
Doing that now brings up "Kalabox quit unexpectedly". Clicking the Reopen button does not open the application.

**Comment by nc2-jordansmith** [comment]
Also, when you say the "new version on OSX", do you mean 10.10 or 10.11?

**Comment by pirog** [comment]
79 active OSX users running 0.13.0-beta.2 today. The breakdown is 21 on 10.10 and the rest on 10.11

**Comment by pirog** [comment]
Just for my own sanity I tried to install this in a clean 10.10 VM and it worked as expected :(

**Comment by nc2-jordansmith** [comment]
Ok, yeah. I just checked it out on my home computer (MacBook Pro running 10.10.5) and it's working perfectly. I have no clue as to why my work computer is failing, but I'll look into it and post here what I find out. Let me know if you want me to test anything specific.

Also, I can confirm that the latest (v0.13.0-beta.2) is pulling WP properly now. Thanks for that fix.

**Comment by pirog** [comment]
Sure thing and def let me know what you find out on the other machine so we
can put in a fix if it's something on our end!!!

**Comment by magbicaleman** [comment]
@pirog I'm getting the following when I try to open the GUI

![image](https://cloud.githubusercontent.com/assets/735039/17057975/b4d01916-4feb-11e6-9981-7df2bb9ee160.png)

**Comment by nc2-jordansmith** [comment]
Ok, I found some help on a few other Apps' help sites and got it working. Here's what I did:

1.) Downloaded Kalabox (v0.13.0-beta.2) and ran the normal install.
2.) Clicked and tried to open Kalabox, but got that "can't be opened" message.
3.) Open Terminal, entered `sudo su` (and entered MacBook password)
4.) Then entered `chmod -R 755 /Applications/Kalabox.app/`
5.) Clicked to open Kalabox and it opened. (I've been able to Pull, Edit, and Push commits to my WP site.)

NOTES:
- I had to delete my previously pulled WP site since it was returning a 500 error page.
- I'm thinking it might be a permissions issue within the MacBook. It worked without issue on my personal MacBook (where I'm the only user), but it had issues with my office MacBook (where I'm set up as a secondary Admin.)

**Comment by rbertolette** [comment]
Not to question your sanity... :-)
I've got the same issue.
osX 10.10.5, MacBook Pro (Retina, 15-inch, Late 2013), 2.3 GHz Intel Core i7, 16 GB 1600 MHz DDR3

I've been using 0.12.0-beta.1 wanted to upgrade so 

- I moved the files folder of one app to a new location, and created a new empty files folder where it was
- ran the uninstall.sh from the kalabox-v0.12.0-beta.1.dmg (had to do this as sudo
- ran the install script from the kalabox-v0.13.0-beta.2.dmg got the same "The installation was successful" notice. 

When I tried to run kalabox from double-clicking the icon I got the same message: "The application “Kalabox” can’t be opened."

I was able to run kbox status from the command line. 

As a sanity check, I ran the uninstall.sh from the kalabox-v0.13.0-beta.2.dmg, restarted my mac, then installed again as usual from the kalabox-v0.13.0-beta.2.dmg. Again "The installation was successful" but double-clicking the icon got "The application “Kalabox” can’t be opened."

However, selecting Get Info from the Kalabox app icon showed staff & everyone had Read only permissions. Above them was a row showing Fetching... as the user, with Reed & Write permission. (Gotta believe that's a hint.)

I tried adding myself as another user with Reed & Write permission. Same result when launching the Kalabox icon. I removed the Fetching... row. Same result.

I ended up starting over, running the uninstall.sh from the kalabox-v0.13.0-beta.2.dmg, installing from the kalabox-v0.12.0-beta.1.dmg. Then I reinstalled as usual. I'm able to run from the command line as expected.

Looks like nc2-jordansmith has a comment above to fix the Kalabox.app.

**Comment by dalehgeist** [comment]
Same issue. @nc2-jordansmith solution worked for me to open the GUI. (I should note that I was unable to run the uninstall because docker could not locate the app.) It seems to be running fine now.

**Comment by mbader** [comment]
Same issue here. OSX 10.10.5

**Comment by pirog** [comment]
Great and super helpful feedback from everyone on this issue. 

This is 100% on our side and seems easily resolvable. Going to mark this high priority and will roll a new release once fixes.
