### ISSUE TITLE
F12 working to show console when starting the gui in Windows?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1479]
When starting Kalabox in Windows 10 home (beta 2 updated version released in PM of 7/21) and pressing F12, a window appears but it doesn't show any of the steps being performed. The window that comes up says Chrome devtools. Is that what is supposed to be invoked by F12?

Starting the Kalabox engine doesn't seem to complete. It just keeps running until I close its window.

I had previously downloaded the earlier beta 2 and ran the Windows uninstaller before installing what I hope is the new version from github.

This is after the GUI installation is supposed to be fixed.

Thanks.

**Comment by jsibley2** [comment]
Am I seeing the correct window after pressing F12, but without any log info, or am I seeing the wrong window?

If I am seeing the wrong window due to Chrome, could there be an alternate way to pull up the diagnostic info while using the GUI?

Thanks.

**Comment by pirog** [comment]
yup you are supposed to get chrome dev tools which does contain a console.

**Comment by jsibley2** [comment]
So, if F12 shows a console without any info while creating a Drupal 7 or Pantheon instance, isn't that still a problem?

Thanks.

**Comment by pirog** [comment]
it could be but its not necessarily a problem. Windows handles STDOUT differently than unix in this context. Is your kalabox.log file empty?

**Comment by jsibley2** [comment]
No, there is a kalabox.log file that isn't empty.

**Comment by pirog** [comment]
Good! Then you are at least getting some debug logs you can look at in the event the dev tools console is not working.
