### ISSUE TITLE
Unison sync bug, directories & files in /code all named as .tmp

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1484]
Bug Report
==========
version 0.13.0-beta.2 - windows 10pro

**Have you previously installed Kalabox? If so, what version?** Yes, most of them

**Tell us about your bug**
 I am getting all .tmp file & folder names inside the /code directory
.unison.sites.09e750e3a87ca3e27f3e5081efb83981.unison.tmp
.unison.mytheme.info.yml.09e250e3a87ca3e27f3e4081efb83981.unison.tmp

**Does this bug prevent you from using Kalabox?**
Yes, cannot access /code directory from main os

I have tried rebuilding, also deleting the site and making it over, with the same issue.  It seems to only effect the /code directory and everything inside, all the other folders have correct file & folder names.  Ive noticed if I change the file names to the exact original they work, but its thousands of things to rename.

**Comment by AaronFeledy** [comment]
I am having the same issue. Also on Windows 10. From what I gather, unison will transfer a file with a temporary filename then rename it to the proper name once the transfer is complete. It seems it successfully completes the transfer, but does not rename the file. This appears to be happening with every file. Every file and folder in the code directory is named .unison.FILENAME.********.unison.tmp. I've pulled some apps down from pantheon as well as created new apps. This happens with all of them.

I did some googling and found that disabling antivirus might help with this issue. It did not help in my case.

I'd check the unison logs for errors, but I'm not sure where they are located.

**Comment by pirog** [comment]
So i am definitely getting this on Windows too. I *think* we just need to add a few extra unison options to get this to behave on Windows. Going to bump this to a high priority issue and we will cut a new release as soon as it is resolved. 

@AaronFeledy i would check out the docs for help with scoping the logs. http://docs.kalabox.io/en/stable/troubleshooting/

**Comment by macronomicus** [comment]
Just tested the updates on beta3, seems to be in working order for me here :)  Thanks man!  
It took a few minutes to download the files do my host os after launching a site, but once in they all had completed,they have the proper name and works perfect.  
Much better performance than syncthing by far!
Cheers!

**Comment by pirog** [comment]
huzzah! and agreed. i would def encourage you to read more about the file sharing in our docs since there are some good tips there to speed things up
http://docs.kalabox.io/en/stable/users/config/#sharing

**Comment by macronomicus** [comment]
Sweet, thanks for everything man! Ill check the docs now.
