### ISSUE TITLE
General pass on low hanging GUI improvements

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1489]
There are a few areas that changed and the GUI does not have great UX around them now

1. Getting list of environments on Pantheon when you select a site
2. Getting the connection info in the modal popup
3. Initially creating a site

**Comment by joshkoenig** [comment]
One idea would be to have a general purpose GUI mechanism that indicates "communication with the cloud is happening". I've seen a lot of apps do this by changing the cursor — going all the way back to the original MacOS idiom of turning the arrow into a watch when you hit save.

You could potentially have this naively driven off whatever wraps back-and-forth with Pantheon (or any other provider), as the need to have background IO block certain things will probably pop up in all kinds of contexts.

**Comment by reynoldsalec** [comment]
Addressed 1/2, might want to talk a little more about point 3 to determine the best way to handle it, could...

- insert a new event
- display a "waiting" symbol after hitting submit on the form and only closing the sidebar once the app appears
- insert a dummy site element into the array of sites displayed on the main dashboard until real site data is displayed

**Comment by pirog** [comment]
@reynoldsalec looking at the code i think we probably want to create a new `pre-create` event and  inject a dummy or barebones (ie the the protoapp) in the sites array until we get the full app instance after the configure step is done.
