### ISSUE TITLE
GUI is not displaying any information in the app-specific Site URLs section

### ISSUE THREAD

**Issue by Senpai** [kalabox/kalabox#1492]
Bug Report
==========

**Tell us about your setup**

OS X 10.11.6 running Kalabox v0.13.0-BETA2.

**Tell us about your bug**

GUI missing information about "Site URLs"; Same behavior across five pantheon apps. Annotated screenshot attached.

<img width="350" alt="screenshot_kalabox_site_urls_info_missing_v0-13-0-beta2" src="https://cloud.githubusercontent.com/assets/303339/17155317/712a78ae-5339-11e6-8cb2-54501530bf07.png">

*Does this bug prevent you from using Kalabox?*

Nope. It's still functional as long as you can deduce your localhost url as being the name of the pantheon app + a .kbox at the end. :)

**Comment by pirog** [comment]
nice catch @Senpai. going to backlog this and ping @reynoldsalec on it

**Comment by pirog** [comment]
@Senpai should be in the next release
![screen shot 2016-08-04 at 5 41 23 pm](https://cloud.githubusercontent.com/assets/713424/17423815/cd36ae52-5a72-11e6-84fc-16e139dcbc86.png)
