### ISSUE TITLE
Kalabox.io download page goes to 504 gateway timeout

### ISSUE THREAD

**Issue by potentialcoder** [kalabox/kalabox#1494]
After filling the form at http://www.kalabox.io/download  i see this https://nimbus.everhelper.me/client/notes/share/533580/empvlaxvtk3c3rcnvtbm.

Is there any other way to get Kalabox?

**Comment by pirog** [comment]
@potentialcoder i cant replicate this although but clicking on download after completing the form seems to hang indefinitely. Perhaps @reynoldsalec has some insight here. 

In the meantime you can grab the new release on github https://github.com/kalabox/kalabox/releases

**Comment by reynoldsalec** [comment]
Ok, looks like I've tracked down the issue here and should be resolved, thanks for pointing this out @potentialcoder!
