### ISSUE TITLE
push/pull misses files

### ISSUE THREAD

**Issue by chrisbohnsack** [kalabox/kalabox#1498]
Bug Report
==========

Hi there. When pushing multiple files Kalabox seems to randomly miss new files added to /files directory. Performing the push a second and third time (depending on how many files were missed) seems to resolve the issue. Similarly when pulling a site, the first attempt seems to miss files in the /files directory. Repeating the pull seems to resolve the issue.

I'm running Kalabox 13.0-beta.3 (0.13.0-beta.3) on Mac OSX 10.11.6. 

I had previously installed 12.0-beta and recall having the same issue on pull (did not notice it on push).

The issue is difficult to repeat as it does not always occur, however each time it has occurred with files that were added to the site via the web interface, for example:

1. With a Drupal installation, create a content type with a image upload function
2. Create several nodes and upload images to them.
3. Push files via Kalabox
4. Check dev install to see if images were uploaded

In one instance the file missed was a PDF file uploaded via CKeditor. That time there was only two PDF files, it was the first file that was missed (if sorting by file name), it was the second file added by time stamp.

**Comment by pirog** [comment]
@chrisbohnsack wow that is very strange. does this happen on all your sites?

**Comment by chrisbohnsack** [comment]
This is the only site I have with Pantheon (so far anyway).

**Comment by pirog** [comment]
@chrisbohnsack i think this shuold be resolved in the latest rc2. please reopen if that is not the case
