### ISSUE TITLE
Beta 3 apps report Beta 2 version

### ISSUE THREAD

**Issue by richyumul** [kalabox/kalabox#1503]
This may be a cosmetic thing, but it's confusing...

Bug Report
==========

**Tell us about your setup**
What is your Kalabox version and operating system?
0.13.0-beta.3 on OSX 10.11.6

Have you previously installed Kalabox? If so, what version?

Yes, 0.13.0-beta.2

**Tell us about your bug**

I uninstalled beta 2, and then installed beta 3.  I also moved my old beta 2 apps into a backup directory.

I did a 'kbox create pantheon' on some of the projects that I'm working on.

When I do a 'kbox list', the apps report a version of 0.13.0-beta.2

I don't know if this is a cosmetic thing, but it doesn't instill confidence....

Does this bug prevent you from using Kalabox?

No, but I'm just hoping it's a cosmetic thing.  The apps were pulled down from Pantheon without any troubles.

**Comment by pirog** [comment]
@richyumul please read the documentation. 

the pantheon/php apps are not necessarily the same version as kalabox. you can think about them the same way you think about node and npm modules.
