### ISSUE TITLE
Issue with / workaround for DNS set in router?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1508]
I realized that the DNS setting in my router might be conflicting with kalabox and causing problems.

I use a DNS service (unlocator) that allows me to watch tv from other countries. I use it by putting their DNS server info into the WAN settings.

This may have contributed to (caused?) the issues I was having with timing out during the kalabox installation (it succeeded when I used my office router that doesn't have this setup).

I'm thinking that it may also be related to what seems to be a conflict, at least from time to time, between kalabox and access to the internet.

If I have VirtualBox Host-Only Network and/or VirtualBox Host-Only Network #2 enabled, pinging or using tracert using website names is either slow or fails quickly with a message like:

Ping request could not find host comcast.com. Please check the name and try again.

If I disable both, internet access appears normal, but that doesn't work for kalabox.

Is there some way to configure things so that I can keep the DNS settings I have in my router without any DNS issues with Kalabox or the internet?

**Comment by jsibley2** [comment]
I'm going to make it easier by getting a second router for the smart dns setup. I will go forward with a simpler router setup for kalabox and everything other that doesn't need the smart dns setup.

**Comment by pirog** [comment]
@jsibley2 we do not do anything strange in our DNS handling and it is a fairly common VB setup. 

Basically all DNS requests inside the Kalabox engine are going to use the upstream DNS servers that your host has set. In custom or manual set ups like yours the onus is on the user to set things up correctly to work with kalabox. unfortunately there isnt a lot we can really do on our end and i dont think we can reliably get into the business of messing with the users upstream servers.
