### ISSUE TITLE
Possible to install dig in kalabox in virtualbox?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1509]
I'm wondering whether dig might help me better understand dns issues that seem to be continuing.

Is there a way to install it within the kalabox2 container? Alternatively, is there a better solution for using dig?

**Comment by pirog** [comment]
@jsibley2 there is no "kalabox2 container". have you read the docs on the engine? that might be helpful to  you
http://docs.kalabox.io/en/stable/general/engine/
