### ISSUE TITLE
FR: Manually refresh pantheon sites list in GUI

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#1510]
As a Kalabox user who has just been added to a Pantheon site as Team Member, I need to be able to manually refresh the sites list in Kalabox.

*Example: Place a refresh icon button to the right of site filter input.*

**Comment by pirog** [comment]
Great request. We should definitely do that. 

In the meantime i think if you reauth your token this should be a good workaround

**Comment by pirog** [comment]
@pi-ron should be fixed in the next release!

**Comment by pi-ron** [comment]
👍
