### ISSUE TITLE
Clearing Site Cache After PHP Error Backtrace

### ISSUE THREAD

**Issue by bgonz** [kalabox/kalabox#1511]
This is not really bug - but more of a usage clarification.

I am using the latest kalabox: v0.13.0-beta.3

- in general I am new to Kalabox environment so this is more of a learning curve issue

I had a problem in my code where the PHP was incorrect in my loop, which caused PHP to fail. My local browser: website_name.kbox -> partially renders the page then shows a Backtrace log (about 10 lines).

This is great! It helped me find the problematic loop - so I removed the entire snippet of PHP code and saved my work (using PHPStorm by Jetbrains). I figured I could now safely refresh the page and render the entire page (minus the chunk of code for my loop). 

I was wrong. The backtrace was still there - and still referenced the same line of code that had been removed.

- I refreshed Chrome Browser 3-8 times (using cmd + shft + R)
- I used: kbox drush cc all
- I verified Chrome Dev tools was open (with settings defaulting to Not-Cache when Dev tools open)
- I verified Drupal Performance Settings did not have ANY caching or aggregation of JS or CSS

If this was on Pantheon - I would maybe try and "clear cache" from Admin Dashboard -> Varnish Cache

Eventually I just waited about 2 minutes and after another random refresh -> the page rendered as expected. 

I could reproduce every time I wanted to break PHP.

Is this happening because of some sort of Kbox Varnish? Is there a way to make this process more streamlined - no cache - clear cache?

On another note - I am really trying hard to integrate Kalabox into our little studio development process but I need a little guidance from time to time (such as this) - is there a Slack channel or anything where people can ask questions or share ideas?

Thanks for such a rad app! Keep it up Mike and crew!

**Comment by pirog** [comment]
@bgonz if you have a very large code repo sometimes code sharing can take a second to propagate over to your containers. There are ways to optimize your sync in these cases. Have you looked at those at all?
http://docs.kalabox.io/en/stable/users/config/#sharing

We also do have a varnish instance for pantheon apps you can tests against but it should not route through there by default
http://pantheon.kalabox.io/en/stable/users/services/#edge

If this does not resolve your issue please reopen
