### ISSUE TITLE
Network connections in Windows

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1513]
Kalabox2 seems to use VirtualBox Host-Only Network #2.

Does VirtualBox Host-Only Network (without a number) serve a purpose in a standard Kalabox installation? If so, what is its purpose?

Also, you have asked  about bridged connections from time to time. Is there a reason to have a bridged connection in a standard Kalabox installation?

Thank you

**Comment by pirog** [comment]
@jsibley2 VirtualBox sets up a default HON when you install it. I would not recommend removing that. I also would not recommend using bridge mode. 

I would also encourage you to read the VirtualBox documentation for questions of this nature. We do not significantly alter the defaults that VB sets.
