### ISSUE TITLE
Pushing files goes to wrong site!

### ISSUE THREAD

**Issue by chrisbohnsack** [kalabox/kalabox#1515]
Bug Report
==========

Mac OSX 10.11.6
v0.13.0-beta.3

I've been using Kalabox to push database and files up to dev on site A, recently I started a second site B on Pantheon and pulled it down to local using Kalabox. Since creating site B, trying to push site A now only pushes to site B on Pantheon. Logging into Panthon control panel confirms pushes from site A are going to site B.

**Comment by chrisbohnsack** [comment]
UPDATE: I was able to push to site A again by destroying site B from Kalabox, then quiting Kalabox and restarting, then repeat the push.

**Comment by pirog** [comment]
@chrisbohnsack does this only happen through the kalabox GUI? can you try doing it with the CLI and see what you get?

**Comment by chrisbohnsack** [comment]
Hi @pirog, It was on the GUI that I had the problem, I didn't test it on CLI (apologies, I'm not as comfortable with CLI) and I'm under the gun on another project this week -so it might be some time before I can test it again.

**Comment by pirog** [comment]
@chrisbohnsack no worries! def let me know what happens when you have the time to test the CLI. I'll try to reproduce this as soon as i get through the other issues weve already slated for this sprint.

**Comment by pirog** [comment]
@chrisbohnsack i think this also should be fixed in the latest RC2. please reopen if not.
