### ISSUE TITLE
Kalabox website

### ISSUE THREAD

**Issue by chrisbohnsack** [kalabox/kalabox#1516]
I just thought I'd try to let someone know that the Kalabox website links to support do not work in Firefox. Proper HTML syntax is to use a <form> method to submit a button, although it would be nice if Firefox just treated your <a> like a normal link. Anyway, hope this helps.

**Comment by pirog** [comment]
@reynoldsalec might need to hotfix this one?

**Comment by reynoldsalec** [comment]
Thanks @chrisbohnsack, updated that on the site.
