### ISSUE TITLE
Recommended way to connect local editor to kalabox Pantheon drupal site

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1520]
I have a feeling that this is a basic question, but I have tried to search the documentation and didn't find an answer. So, I apologize.

Previously, I used Phpstorm directly with Pantheon to review and edit modules on Pantheon.

Using Kalabox, do I treat my site as a remote site and, if so, what sort of connection do I use and what are the proper credentials?

My goal is to use xdebug and I'm thinking that if I set up my connection appropriately in kalabox, that should work. Is that correct?

Also, until there are instructions that are specific for each IDE, I'm hoping that a generic explanation would help to get started.

**Comment by pirog** [comment]
@jsibley2 you are going to need to look at the documentation for your IDE on how to set it up. We use all the default settings. We do discuss it a bit in our Pantheon docs
http://pantheon.kalabox.io/en/stable/users/tooling/#xdebug
