### ISSUE TITLE
Kalabox beta4 prerelease Pantheon site pull not working

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1531]
Ran windows remove programs to uninstall kalabox

Received notice that parts of kalabox might still remain

Saw that program files\kalabox\bin\docker-machine had not been removed

Deleted the kalabox directory manually (required adminstrator access, which might be the issue).

Also, when I try to pull down my Pantheon drupal installation, I click on submit and there is no indication that anything is happening. Nothing appears to happen after clicking submit (other than going back to the kalabox gui screen).

**Comment by pirog** [comment]
hey @jsibley2, beta4 is not official yet. are you on the mailing list? if so we are going to email everyone when it is official.

**Comment by pirog** [comment]
@jsibley2 the release that is posted now should be the official one. also note that there actually is some lag time from when you submit a pantheon app for creation to it showing up in the gui dashboard. it should not be more than 5-30 seconds depending on your computer. this is a known issue #1489
