### ISSUE TITLE
SFTP and/or SSH from local client?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1534]
Is it possible to use SFTP and/or SSH from a local host (e.g., Putty, WinSCP) to a Pantheon appserver in Kalabox? If so, what is required?

Thanks.

**Comment by pirog** [comment]
yes, although im not sure why you would want to do that. it is also not a use case we support or encourage. have you actually read our documentation? if not i would highly encourage you to do that before posting other issues. 

just to clarify, github issues are to report bugs and suggest features. if you are looking for dedicated support or training, we do offer plans for that.
