### ISSUE TITLE
Forbidden You don't have permission to access / on this server. Apache/2.4.10 (Debian) Server at 123.kbox Port 80

### ISSUE THREAD

**Issue by NicholasBracey** [kalabox/kalabox#1538]
0.13.0-beta.4 on Ubuntu 14.04.5 LTS

After a successful kbox create drupal8 I point my browser to the url created but get 
'Forbidden

You don't have permission to access / on this server.
Apache/2.4.10 (Debian) Server at test123.kbox Port 80'

![screenshot from 2016-08-10 11 20 15](https://cloud.githubusercontent.com/assets/14128111/17550358/8172a34e-5eec-11e6-98eb-3c8139472f6d.png)

I am using the kalabox cli

Any help would be greatly appreciated

**Comment by pirog** [comment]
@NicholasBracey just tried this on 14.04 and can't replicate. Site shows as expected. 

In what directory are you running the create command?

**Comment by NicholasBracey** [comment]
` ⚓  ~/w/projects  master ⚑  pwd
/home/nick/workspace/projects
 ⚓  ~/w/projects  master ⚑  la
total 20K
drwxrwxr-x  5 nick nick 4.0K Aug 10 11:11 ./
drwxrwxr-x 12 nick nick 4.0K Jul  6 17:55 ../
drwxrwxr-x  5 nick nick 4.0K Jul 21 15:15 drude-d8-testing/
drwxr-xr-x  8 nick nick 4.0K Aug 10 11:11 test123/
drwxrwxr-x  3 nick nick 4.0K Jul 22 16:51 vuejs/
`

Thanks for quick reply

**Comment by NicholasBracey** [comment]
⚓  ~/w/projects  master ⚑  pwd
/home/nick/workspace/projects
 
⚓  ~/w/projects  master ⚑  la
total 20K
drwxrwxr-x  5 nick nick 4.0K Aug 10 11:11 ./
drwxrwxr-x 12 nick nick 4.0K Jul  6 17:55 ../
drwxrwxr-x  5 nick nick 4.0K Jul 21 15:15 drude-d8-testing/
drwxr-xr-x  8 nick nick 4.0K Aug 10 11:11 test123/
drwxrwxr-x  3 nick nick 4.0K Jul 22 16:51 vuejs/
 ⚓  ~/w/projects  master ⚑

**Comment by pirog** [comment]
Do you see the d8 codebase in `test123/code`?

**Comment by NicholasBracey** [comment]
⚓  ~/w/p/test123  master ⚑  cd code/sites/default/files/
 ⚓  ~/w/p/t/c/s/d/files  master ⚑  la
total 8.0K
drwxr-xr-x 2 root root 4.0K Aug 10 11:11 ./
drwxr-xr-x 3 nick nick 4.0K Aug 10 11:11 ../

Heres my problem I guess.. Can I just change the permissions, or will this cause problems later down the line?

**Comment by pirog** [comment]
@NicholasBracey that is just your files directory, do you actually see the application codebase?

You can change the permissions, i think as long as they are are the normal drupal permissions that is fine. They should be this by default so im not clear what happened here. It could be related to #1253, what do you get when you run `id`?

**Comment by NicholasBracey** [comment]
@pirog I cannot see the application code base.

 ⚓  ~/w/p/t/c/s/d/files  master ⚑  id
uid=1000(nick) gid=1000(nick) groups=1000(nick),4(adm),24(cdrom),27(sudo),30(dip),33(www-data),46(plugdev),108(lpadmin),125(sambashare),999(docker)

**Comment by pirog** [comment]
@NicholasBracey so you don't have anything in `code` except for that files directory?

Have you tried another `kbox create drupal8`? at all? it's possible that operation just didn't complete or you lost internet or something.

**Comment by NicholasBracey** [comment]
@pirog I had a unsuccessful kbox create drupal 8 as something was hogging my port 80. Cleared port 80 and it worked.. I will destroy and recreate and post the code. Might give you an idea.

**Comment by NicholasBracey** [comment]
@pirog  output -

⚓  ~/w/p/test123  master ⚑  kbox destroy
###############################################################
                                                               
        WARNING! DESTRUCTION IMMINENT FOR APP TEST123     
                                                               
  This command will remove all the containers needed to run    
  your app such as services, containers, databases, caches     
  indeces, etc. Your app's code WILL ALSO BE DESTROYED        
  locally at /home/nick/workspace/projects/test123                                  
                                                               
###############################################################
? So, are you still prepared to DESTROY? Yes
Destroying.
Running pre destroy tasks.
Stopping.
Stopping.
Cleaning up.
Running pre stop tasks.
Stopping containers.
Stopping test123_appserver_1 ... done
Stopping test123_db_1 ... done
Running post stop tasks.
Uninstalling.
Removing test123_drush_1 ... done
Removing test123_appserver_1 ... done
Removing test123_cli_1 ... done
Removing test123_db_1 ... done
Removing test123_data_1 ... done
Running post destroy tasks.
###############################################################
                                                               
                 DESTRUCTION COMPLETE                          
                                                               
###############################################################
Removing files.
 ⚓  ~/w/p/test123  ls
 ⚓  ~/w/p/test123  cd /home/nick/workspace/projects
 ⚓  ~/w/projects  master ⚑  kbox create drupal8
? What will you call this monster you have created: testtest123dummytest123
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Creating testtest123dummytest123_data_1
Creating testtest123dummytest123_db_1
Creating testtest123dummytest123_cli_1
Creating testtest123dummytest123_appserver_1
Creating testtest123dummytest123_drush_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Running post create tasks.
###############################################################
                                                               
                    BOOMSHAKALAKA!                             
                                                               
  Your app has started up correctly. Here are some vitals:     
                                                               
  URL: http(s)://testtest123dummytest123.kbox
  LOCATION: /home/nick/workspace/projects/testtest123dummytest123
                                                               
###############################################################
 
⚓  ~/w/projects  master ⚑  kbox list
{
  "name": "testtest123dummytest123",
  "url": "http://testtest123dummytest123.kbox",
  "type": "php",
  "version": "0.13.0-beta.2",
  "location": "/home/nick/workspace/projects/testtest123dummytest123",
  "running": true
}


Still getting 403 when going to http://testtest123dummytest123.kbox.

Not seeing the code base either.

**Comment by pirog** [comment]
@NicholasBracey the codebase not showing up is why you are getting the 403. I haven't been able to replicate this at all :(

**Comment by timclifford** [comment]
I had this problem. I destroyed my app and then changed vhosts apache2 and mysql ports locally to something other than 80(apache) and 3306 (mysql). Then I temporarily stopped apache and mysql services. Then I ran kbox create drupal8 again and it worked. Not sure if that helps your exact issue but worked for me.
