### ISSUE TITLE
kbox up stopped working

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1541]
I am running beta4 on Windows 10 professional.

Everything had been working, then I started having the problem below. I suspect something didn't close properly after a force close?

The GUI seems to hang when starting, so I tried "kbox up".

I get this message:

Error bringing machine up.: Failed after 5 retries. {"max":5,"backoff":500}: : code1err:more:Starting "Kalabox2"...

VError: Failed after 5 retries. {"max":5,"backoff":500}: : code1err:more:Starting "Kalabox2"...

    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:70:17
    at process._tickCallback (node.js:917:13)

Running with -v, it looks like it gets through "inspect" and "status", then fails with "start".

How should I fix this?

Thanks.

**Comment by pirog** [comment]
@jsibley2 follow the instructions no how to access the engine directly and then run the following command and see what it says.

```bash
%DOCKER_MACHINE% start Kalabox2
```

**Comment by jsibley2** [comment]
It says "machine does not exist"

Also, in the documentation in the link above, it says:

# You might want to consider adding this to your PATH variable
set DOCKER_MACHINE="C:\Program Files\Kalabox\bin\docker-machine-exe"

I think it is a typo and should be ".exe", not "-exe", right?

Thanks.

**Comment by pirog** [comment]
Yeah, should be a `.exe` good catch on the typo. 

When you change to `.exe` that does it still say the machine does not exist?

**Comment by jsibley2** [comment]
yes, it does

**Comment by pirog** [comment]
If you open up VirtualBox do you see the Kalabox2 VM?

**Comment by jsibley2** [comment]
And docker-machine ls shows:

NAME       ACTIVE   DRIVER       STATE   URL   SWARM   DOCKER    ERRORS
Kalabox2   -        virtualbox   Error                 Unknown   machine does not exist

**Comment by pirog** [comment]
Is it possible you deleted the `~\.docker` directory? That is what contains the `docker-machine` configuration for the Kalabox2 VM.

**Comment by jsibley2** [comment]
Virtualbox shows "inaccessible" for Kalabox2 with this error message:

Runtime error opening 'C:\Users\Jonathan\.docker\machine\machines\Kalabox2\Kalabox2\Kalabox2.vbox' for reading: -102(File not found.).
F:\tinderbox\win-5.0\src\VBox\Main\src-server\MachineImpl.cpp[740] (long __cdecl Machine::i_registeredInit(void)).
Result Code: 
E_FAIL (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}

**Comment by pirog** [comment]
Is it possible you deleted that file? We do not directly touch that directory in any way so i don't think this is something that Kalabox could have done.

**Comment by jsibley2** [comment]
Here is .docker\machine\machines\Kalabox2:

![image](https://cloud.githubusercontent.com/assets/6576953/17628314/d2c79a64-6082-11e6-9beb-def7490d1781.png)

And here is .docker\machine\machines\Kalabox2\Kalabox2:

![image](https://cloud.githubusercontent.com/assets/6576953/17628355/f8d0da04-6082-11e6-8b3d-b8a718704a6a.png)

**Comment by pirog** [comment]
Yup looks like the VM file itself is just gone.

**Comment by jsibley2** [comment]
Could it be that I aborted just before the VM was rewritten, since I had Kalabox2.vbox-prev and Kalabox2.vbox-tmp?

I renamed Kalabox2.vbox-tmp to Kalabox2.vbox, went to my app directory, and kbox start worked.

I seem to be back in business.

**Comment by pirog** [comment]
That would make sense to me. 

Again, there is nothing in the Kalabox code that directly messes with that stuff so i think it would require some action on the users end.
