### ISSUE TITLE
beta4 - Linux - drush dl requires sudo password now?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1545]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

beta4 & Ubuntu 16.04

Have you previously installed Kalabox? If so, what version?

Yes, all

**Tell us about your bug**

I purged and installed beta4 this am.  When trying to use drush to download some fun modules, it asks me for my sudo pw now.  Odd, but here:

```
john@kalamuna:~/.kalabox/apps/dlab/code$ kbox drush dl afb --dev
[sudo] password for john: 
Project afb (7.x-1.x-dev) downloaded to                              [success]
/code/sites/all/modules/contrib/afb.
```

And when I enabled and dloaded another fun module set:
```
john@kalamuna:~/.kalabox/apps/dlab/code$ kbox drush en devel search_krumo -y
[sudo] password for john: 
search_krumo was not found.                                          [warning]
The following projects provide some or all of the extensions not     [ok]
found:
search_krumo
Would you like to download them? (y/n): y
Project search_krumo (7.x-1.6) downloaded to                         [success]
/code/sites/all/modules/contrib/search_krumo.
The following extensions will be enabled: devel, search_krumo
Do you really want to continue? (y/n): y
search_krumo was enabled successfully.                               [ok]
devel was enabled successfully.                                      [ok]
devel defines the following permissions: access devel information, execute php code, switch users
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

Try and use kbox drush dl to grab a module.  The end.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using Kalabox?
No

**Comment by pirog** [comment]
This is because of the same issue in https://github.com/kalabox/kalabox/issues/1539
