### ISSUE TITLE
Kbox generally running slow

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1547]
I'm posting this at the urging of @pirog...

Bug Report
==========

**Tell us about your setup**

0.13.0-beta.4 on OS X 10.11.3

Have you previously installed Kalabox? If so, what version?

all previous betas as well as many of the releases prior. I have made a point of running the uninstall script, though many of those have had the same issues.

**Tell us about your bug**

My Kalabox generally runs slow. My machine is a mid-2010, though with an SSD and 16GB of RAM. Most of my applications run just fine. Some of the things I've seen:

-Starting up Kalabox and getting a site not found when going to the site on a browser, then followed by a 503 error and some times up to 5 minutes before the site comes up (which is an improvement from prior versions where it could take up to 15 minutes).
-File syncing running slow. At the best of times, it's relatively instantaneous (maybe 2-3 seconds). However, it has also been much much slower. 10-15 seconds is normal. There was one time where it hadn't synced for 10 minutes. I restarted kalabox and it still hadn't synced. I went off did other things and came back to the window after some time and it finally had synced (though I may have run grunt in the host which may explain that one).

Once the site is up, clicking page to page is not blazingly fast, but generally quick enough.

Could better documentation have prevented this issue? if so what should we change?
Perhaps, if there are specific things that could be set to make kalabox run faster.

Does this bug prevent you from using Kalabox?
At times, it does.

**Comment by pirog** [comment]
@Mchampsee for clarification... when you say mid-2010 do you mean in the middle of the year 2010 or in the middle of 2010's decade? 

Wow. that is extremely slow. I'd be interested to hear if other people with older machines are having the same issue. I know that for my mid 2015 MBP it usually takes a few seconds for the site to show up after a start. Page loads are generally instantaneous for a stock D7 site. Syncing is generally instantaneous as well, especially having optimized the config for each app. 

Please keep in mind that Kalabox is basically a PaaS emulator and fully containerized development environment so its a little more complicated (and resource intensive) then running something like slack so we do actually require a modern machine 
http://docs.kalabox.io/en/stable/general/sysreq/

**Comment by Mchampsee** [comment]
Thats middle of the year 2010 (i.e. 6 years old). I have a laptop of the same vintage that Kalabox runs much quicker on which is the odd thing.

**Comment by pirog** [comment]
@Mchampsee weird. Any obvious diff between the two machines?

**Comment by Mchampsee** [comment]
@pirog - Can't think of much. They are the same OS version and have a lot of the same apps installed. The slower machine has Creative Suite 6 on it, though I generally don't have one of those apps running while running Kalabox. The only other thing that I can think of is that I did a fresh install of 10.11 on the faster machine while the slower machine was upgraded for 10.10. Once 10.12 gets released and seems stable, I plan to do a fresh install of it on the slower machine to see if that fixes it.

**Comment by pirog** [comment]
@Mchampsee yeah def please let me know how that goes! seems really weird you would get such drastic performance diffs between the two machines... and an even further diff from what im running. older machine should def be slower but i feel like they should not be THAT slow.

**Comment by Mchampsee** [comment]
I'll post any other insights I find into this issue..

**Comment by dsquaredb** [comment]
@pirog I've also got a somewhat older MacBook Pro (late 2011) and I am experiencing slow page loads and slow response when I start an app. But I am having a real problem with syncing changes. When I make a css change, it sometimes takes close to a minute before those changes show up. I clear caches multiple times before it ever syncs. This really slows my workflow down when I am working on theming. Several times I thought I had not applied css to something, redid it another way, still didn't work, and then the site synced and my original change displayed. When I install a new module or update a feature, and then do git status, those changes don't show in terminal for 20-30. I wasn't seeing these things in previous versions of Kalabox, just with the latest one.

**Comment by pirog** [comment]
@dsquaredb please check out the docs re: syncing http://docs.kalabox.io/en/stable/users/config/#sharing

**Comment by AmyJuneH** [comment]
@pirog I am having similar issues with my machine, 2012.  Long load times, timing out for uli, etc.  Sometimes KB will load up in an instance, but other times it could take up to 30 minutes for it to retrieve a site from Pantheon to my local machine.

**Comment by pirog** [comment]
@AmyJuneH 30 minutes to pull a site from pantheon can be fairly standard esp if you have slower internet (ie the kalamuna office) and the site is fairly large.

It's hard to specifically say re page load times since that could be any number of things ie HUGE sites are obviously going to be slower than Drupal 7 by itself. Older computers are going to be faster than new ones. A decent (although not universal) rule of thumb is that a stock drupal7 site should load in less than a second. 

I'm not sure what you mean by "timing out for the uli" but if you are getting actual errors from kalabox about things timing out that is likely something on our end that requires fixing. I think there are a few issues open already to this effect. 

All of that said, and to other users who end up on this issue, the tech we are using is pretty cutting edge so having a newish and powerful computer (ie the last few years) will avail you.

**Comment by Mchampsee** [comment]
One thing that would be immensely helpful would be some means of verifying sync status. Even something as simple as terminal access so that one could verify for certain what got over and what hasn't yet.

**Comment by pirog** [comment]
@Mchampsee these means already exist
http://docs.kalabox.io/en/stable/troubleshooting/#docker-logs

You will want to check the logs for `appname_unison_1`, you also can look at the instructions for container logs and mount your logs back out to the host to avoid having to muck around on the terminal

**Comment by AmyJuneH** [comment]
I have discovered that closing all of my programs and re-starting my computer will bring new life and speed to KBox.  The science is not perfect, but it appears that after 3 or 4 sleep cycles on my Mac, the Kbox start to slow and load times are in the minutes for simple tasks, including 'git status'...but once I do a re-start, things seem to go quickly.
I will be installing SSD drive in the mac with in the next dew weeks and will update on this thread how the performance differs.

**Comment by Mchampsee** [comment]
RC1 has made a huge difference. Syncs are pretty much instantaneous. The "Waiting for site to be ready." is a nice touch and the sites are definitely spinning up faster. Nice work!

**Comment by pirog** [comment]
@Mchampsee that is great to hear! although we didn't change anything with the syncing so that is a bit surprising. we'll take it though!

thanks!

**Comment by AmyJuneH** [comment]
The problems I was having with slow downloads and commands timing out have been resolved with using a new computer equipped with a SSD drive.
I am having other issues with delay in coding updating showing up in my local environment, but I will be writing an issue regarding this in the next couple of days.

**Comment by pirog** [comment]
awesome!

for the slow code sync i would def encourage you to read the documentation
and look around the issue queue as this issue has definitely been discussed
at length.

**Comment by AmyJuneH** [comment]
thanks, I actually have been doing that.  Still have some things to read and do, but, as I am not very technical, sometimes it is hard to wade through the steps that would be best appropriate for my needs.  And do I have to make these changes on a per App basis?

**Comment by pirog** [comment]
@AmyJuneH yes. each app has its own `kalabox.yml` config file and that is what you will want to edit to optimize your sharing. you will also need to restart. 

i've seen a couple stock sharing configs floating around the kalamuna #dev-collab channel that might be a good starting point.

**Comment by ahimsauzi** [comment]
For what it's worth, changing the default kalabox.yml on the root of my project from the default `'data:/code'` to `'web:/usr/share/nginx/html'` really helped boost page load on my MacBook Air.
