### ISSUE TITLE
Unable to export config with Drush

### ISSUE THREAD

**Issue by abea** [kalabox/kalabox#1550]
# Bug Report

Kalabox version: 0.13.0-beta.3
OS: OS X 10.11.6
Have you previously installed Kalabox? Yes. 0.11, I think but cleared it all out extensively to install 0.13.

**Tell us about your bug**
Tried to export config management to the codebase with `drush cex`. I keep getting errors referring to not being able to create or set permissions on `sites/default/config/`. I created the directory manually and set permissions to 666. I then removed my `/config/` directory when the errors got more extensive.

Latest error:

``` bash
exception 'Drupal\Core\Config\StorageException' with message 'Failed [error]
to create config directory sites/default/config' in
/code/core/lib/Drupal/Core/Config/FileStorage.php:72
Stack trace:
#0 /code/core/lib/Drupal/Core/Config/FileStorage.php(132):
Drupal\Core\Config\FileStorage->ensureStorage()
#1 phar:///usr/local/bin/drush/commands/core/config.drush.inc(481):
Drupal\Core\Config\FileStorage->write('automated_cron....', Array)
#2 phar:///usr/local/bin/drush/commands/core/config.drush.inc(410):
_drush_config_export('sync', 'sites/default/c...', false)
#3 [internal function]: drush_config_export()
#4 phar:///usr/local/bin/drush/includes/command.inc(366):
call_user_func_array('drush_config_ex...', Array)
#5 phar:///usr/local/bin/drush/includes/command.inc(217):
_drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 phar:///usr/local/bin/drush/includes/command.inc(185):
call_user_func_array('drush_command', Array)
#8 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#9 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 phar:///usr/local/bin/drush/includes/startup.inc(321):
drush_main()
#11 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#12 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#13 {main}
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
5. Ran `kbox drush cex` from the app's `/code/` directory.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Not sure.

Does this bug prevent you from using Kalabox?
Not otherwise, though it dissuades me from doing so if given the choice.

**Comment by pirog** [comment]
@abea it looks like there are actually a whole slew of issues relating to `kbox COMMAND ARGUMENTS` erroring because of permission problems.

**Comment by abea** [comment]
So it's probably due to file permissions in our codebase? I was afraid of that. If that's the case please feel free to close.

**Comment by pirog** [comment]
@abea its possible but could also be an issue on our end. I'll def ping back here when ive had time to try to replicate.

**Comment by abea** [comment]
No longer using Kalabox so don't want to clutter up queue with this since there's no other reports.
