### ISSUE TITLE
[bug fix] The Mac installer is reporting "Installation Failed"

### ISSUE THREAD

**Issue by mattalexx** [kalabox/kalabox#1552]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

kalabox-v0.13.0-beta.4.dmg on Mac - OS X Capitan 10.11.6 (15G31)

Have you previously installed Kalabox? If so, what version?

Installer error, so not installed.

**Tell us about your bug**

1. Started installer and followed the step normally.
1. On the Summary step, some time after the "Running package scripts..." message, I got "The install failed:

<img width="639" alt="screen shot 2016-08-29 at 3 10 32 pm" src="https://cloud.githubusercontent.com/assets/250466/18066194/eab16998-6dfc-11e6-8e7c-4a9fc1d67784.png">

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

No

Does this bug prevent you from using Kalabox?

Yes

Log file: [Installer Log 29-Aug-2016.txt](https://github.com/kalabox/kalabox/files/443398/Installer.Log.29-Aug-2016.txt)

**Comment by pirog** [comment]
@mattalexx i would check out https://github.com/kalabox/kalabox/issues/1526 since that thread seems to have a good deal of pointers and workarounds to people having install issues.
