### ISSUE TITLE
Create Drupal 7 site doesn't setup database

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1562]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

v0.12.0-Beta4 on OS X 10.11.6

Have you previously installed Kalabox? If so, what version?

all betas as well as prior releases

**Tell us about your bug**

Type into command line `kbox create drupal7`
Create site and then surf to kbox site
Go through install screens. Once you get to database it asks for DB name, username, password, etc. which I don't see in any of the yml files or entering `kbox config`. Entering any config yields an error message `Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.`

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
If the DB credentials are easily accessible that would help.

Does this bug prevent you from using Kalabox?

yes

**Comment by pirog** [comment]
@Mchampsee `kbox services` will give you the DB credentials. Highly recommend reading the documentation.

**Comment by Mchampsee** [comment]
Sorry about that. I did KBox config and didn't see anything and completely forgot about KBox services
