### ISSUE TITLE
yes.exe in PATH can cause installer to hang on windows 

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1564]
What is your Kalabox version and operating system?
0.13.0 RC1 Windows 10 Professional Anniversary Edition

Have you previously installed Kalabox? If so, what version?
Yes, several previous versions, although couldn't get the most recent beta to work

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

Ran initial installer after deleting all visible remnants of Virtualbox and Kalabox. As with previous beta, installer hangs during "activating engine". There is now way to cancel or close the installer other than task manager, but VBoxSVC.log is created quite soon after the "starting the engine" message. As previously, engine.bat is downloaded, but there is no services.bat

This is from VBoxSVC.log:

00:00:00.237505          HostDnsMonitor: old information
00:00:00.237505            no server entries
00:00:00.237505            no domain set
00:00:00.237505            no search string entries
00:00:00.237505          HostDnsMonitor: new information
00:00:00.237505            server 1: 192.168.1.1
00:00:00.237505            no domain set
00:00:00.237505            no search string entries
00:00:00.237505          HostDnsMonitorProxy::notify
00:00:00.284364          Support driver version mismatch: DriverVersion=0x240000 ClientVersion=0x260000 rc=VERR_VERSION_MISMATCH
00:00:00.284364          VD: VDInit finished
00:00:00.300006          VirtualBox: object created
00:00:05.302777 main     VirtualBox: object deletion starts
00:00:05.302777 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:00:05.302777 main     VirtualBox: object deleted

It looks like things go wrong with the driver version mismatch. Any idea what do do about this?

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

Download latest installer from kalabox.io
Run installer

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Doesn't appear to be a documentation issue unless additional steps are required, such as changing the Windows registry. Couldn't the installer catch major errors that will get in the way of installation and end more gracefully, perhaps with a message?

Does this bug prevent you from using Kalabox?
Yes

**Comment by jsibley2** [comment]
It is possible that I hadn't rebooted between uninstalling virtualbox and starting the kalabox installation. I think that might be necessary.

Trying again, after uninstalling kalabox and virtualbox, removing appropriate directories, rebooting, and running the kalabox installer as administrator (in cast that helped), I get:

00:00:00.207147          HostDnsMonitor: new information
00:00:00.207147            server 1: 192.168.1.1
00:00:00.207147            no domain set
00:00:00.207147            no search string entries
00:00:00.207147          HostDnsMonitorProxy::notify
00:00:00.272659          VD: VDInit finished
00:00:00.272659          VirtualBox: object created
00:00:05.299390 main     VirtualBox: object deletion starts
00:00:05.299390 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={0169423f-46b4-cde9-91af-1e9d5b6cd945} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:00:05.299390 main     VirtualBox: object deleted

So, I don't get the mismatch error, but I still get the access denied error and installation seems to halt at the same place, with the installer window still showing "activating engine".

Also, I tried running engine.bat (seems to work, but requires cntl-c to stop a scrolling list of "y"), copying over services.bat and dns.bat (not present yet from the installation), and running them.

This gives me a kalabox2 engine that can be started and stopped, but kbox create drupal7 seems to fail. kbox create drupal7 gives me:

? What will you call this monster you have created: d7test2
info: Creating.
Creating.
info: Cleaning up.
Cleaning up.
verbose: KALABOX ENGINE ==> Running ["inspect"]
verbose: KALABOX ENGINE ==> Running ["status"]
verbose: KALABOX ENGINE ==> Running ["C:\\Program Files\\Kalabox\\bin\\docker-machine.exe","C:\\Program Files\\Kalabox\\bin\\docker-machine.exe","ssh","Kalabox2","sudo","/etc/init.d/docker","status"]
info: Creating app structure.
Creating app structure.
undefined
undefined
error:  errno=50, code=EPERM, path=C:\Program Files\Kalabox\d7test2

I'm guessing that there are some missing steps in my attempt to install things manually?

**Comment by bmcclure** [comment]
On Kalabox 0.13 RC1 on Windows, I've discovered what causes the installer to hang indefinitely when starting the engine for me. There is a process running, yes.exe, and when I manually run engine.bat I just see an indefinite stream of "y" being output on the screen. It seems like something has perhaps been called with a bad parameter or something, but it just continually outputs "y" until I end the yes.exe process or Ctrl+C, then it moves on and supposedly succeeds.

However, I've been troubleshooting all weekend and I've been unable to get RC1 working on my machine, possibly unrelated to this issue (I've added comments to a couple of other issues), but that makes it difficult to be able to reliably troubleshoot this issue further.

**Comment by jsibley2** [comment]
Has anyone been successful with Windows 10 with this release? Any helpful ideas?

**Comment by pirog** [comment]
@jsibley2 are you having the same issues described by @bmcclure?
@bmcclure what are you installing to get `yes.exe` in the `PATH`?

Can definitely understand the frustration. Getting Kalabox to work on Windows reliably has definitely been a unique set of challenges. 

That all said we did not make any changes to the Windows installer between beta4 and rc1 so if beta4 worked then rc1 should probably work as well. Furthermore we are able to install RC1 on our test windows boxes (Win7, Win8.1 Win10) and pull down a bunch of sites. 

Getting greater clarity on the difference between our test boxes (these are all clean installs of Windows) and what you guys are running would be helpful (ie @bmcclure pointing out `yes.exe` being an issue). If we can't replicate it's hard for us to fix.

**Comment by jsibley2** [comment]
I believe that I am having the same issue, or something similar.

The initial installer seems to fail with an error (based on the timestamp of the log file), while the installer window remains open and can only be closed by using task manager. I'm not sure if this is the same.

If I run engine.bat after this, I get the continuous lines of "y" that I believe @bmcclure describes. I have used cntl-c to stop this. I don't know if it comes from yes.exe, but that sounds reasonable. I assume that it gets called somewhere in the installer?

I think it would be helpful for testing if there were some of these enhancements:
check for as many potentially pre-existing files and directories that can get in the way, as possible and provide a notice (similar to kalabox directory exists, do you want to continue?)
make sure that files that could be used for manual installation or downloaded earlier in the process (at least services.bat and dns.bat
provide more information, at least for now, on screen during the early steps of installation (or provide a debug version of the installer for those who wish to use it)
close the installation screen with an error message if the log file is written without successful completion

There are so many variations of what each of us might already have installed that I think that being able to zoom in on exactly what errors we are getting might be easier than comparing setups and guessing what might be significant.

Also, could there be an installation path that starts with a working Virtualbox (not installed with the kalabox installer) and goes on from that point?

**Comment by jsibley2** [comment]
In case it helps, it looks like I have 2 different versions of yes.exe on my computer.

In Program Files\Git\usr\bin it is dated 5/28/15 and is 28 kb
In Users\Jonathan\windrush\bin it is dated 5/20/15 and is 20 kb

Perhaps the installation is using the wrong version of yes.exe and/or other utilities?

**Comment by pirog** [comment]
@jsibley2 thanks for the feedback here. to address your specific points

1. we are definitely down to try and check for things that could prevent the install from succeeding but cannot do so until we know what those things are.
2. `services.bat` and `dns.bat` are dropped into `C:\Program Files\Kalabox` as the first part of the installer so those should be there to run manually if you want. If not these files are available in the github repo https://github.com/kalabox/kalabox/tree/v0.13/installer/win32
3. All the installer activity is already logged and im not 100% sure what else innosetup can do in terms of logging. i think generally getting more feedback here would be helpful though.
4. If the install program freezes (Ie is not responding) i dont know what we can do at that point. certainly would be good to fix things so it doesnt get to that point in the first place.

So i've tried installing kalabox with two different versions of `yes.exe` in the path and everything installs correctly for me :( 

@bmcclure how confident are you that `yes.exe` is the thing that ails you here?

**Comment by bmcclure** [comment]
@pirog I'm very confident of the symptom, but not 100% certain of the root cause.

Additionally, I've realized that yes.exe does not hang every single time--sometimes the installer completes successfully and I haven't been able to figure out what the difference is. I've been doing so many different things to try and troubleshoot all of my Kalabox issues, which may or may not be related to each other, so it's been hard to try and figure out all of the variables.

However, at least 80-90% of the times I run the installer, when it hangs on Activating Engine, both the installer and yes.exe are using about the same amount of CPU consistently until the install eventually fails (or until I kill yes.exe).

This matches up exactly with the same symptoms I get when running `engine.bat` directly, and in that case I have a console window to confirm what's happening in the output: A never-ending stream of "y" continually scrolls past the screen very quickly until I kill yes.exe, at which point whatever step it was on ends and it moves on to the next step and then completes without further issue.

If this matters, the two yes.exe files I have on my system are for Vagrant and Cygwin. Here's the version that's running for me:

```
λ yes.exe --version
yes (GNU coreutils) 8.25
Packaged by Cygwin (8.25-3)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by pirog** [comment]
@bmcclure awesome. 

i think im going to see if we can just re script the installer without `yes` and i'll post that up here for you guys to try out.

**Comment by jsibley2** [comment]
@bmcclure do you always get to the point where services.bat is downloaded or are you having to download it manually,at least sometimes?

**Comment by pirog** [comment]
@jsibley2 just to clarify here, we **DO NOT DOWNLOAD** any external dependencies ie `services.bat`. These are all packaged with the installer executable you download and then extracted to the the install directory **AS THE FIRST STEP** of the installer.

There isn't an obvious reason why `engine.bat` would extract but not `services.bat` but it possible that 

1. Your install consistently fails mid-extract (which it doesn't seem to do based on your above)
2. You have some sort of security settings or program which is not allowing the extraction of certain kinds of scripts.  (also seems unlikely)

I def have not seen this happen to anyone else, @bmcclure do you get anything like this at all?

**Comment by pirog** [comment]
@bmcclure yes! although i think you should still get `services.bat/dns.bat` even if `engine.bat` fails. However, if `engine.bat` freezes the installer and you kill it mid-install then you are going to get what @jsibley2 describes. 

also, correction, i **THOUGHT** we loaded up the bat files as part of the entire kalabox payload but we do load them separately, specifically to take advantage of the `AfterInstall`

**Comment by pirog** [comment]
Ok so this should be the new `engine.bat` script that does not hang because of the yes binary

```
@ECHO OFF
SETLOCAL
CLS

:: All praise BAT files
::
:: Kalabox Engine Script.
::
:: Copyright (C) 2016 Kalabox Inc
::

:: Load in some env
SET DOCKER_MACHINE=%~dp0bin\docker-machine.exe
SET VBOXMANAGE=%ProgramFiles%\Oracle\VirtualBox\VBoxManage.exe
SET VM=Kalabox2

echo %DOCKER_MACHINE%
echo %VBOXMANAGE%

:: Check to see if DOCKER MACHINE is actually installed
IF NOT EXIST "%DOCKER_MACHINE%" (
  ECHO "Docker Machine is not installed. Please re-run the Kalabox Installer and try again."
  EXIT /B 1
)

:: CHeck to see if VBMANAGE is actually installed
IF NOT EXIST "%VBOXMANAGE%" (
  ECHO "VirtualBox is not installed. Please re-run the Kalabox Installer and try again."
  EXIT /B 1
)

:: Get the free disk space in MB
wmic logicaldisk where (caption = "%SystemDrive%") get freespace>"%TEMP%\free.tmp"
FOR /F %%A in ('TYPE "%TEMP%\free.tmp"') DO (SET free=%%A)
SET FREE_DISK=%free:~0,-6%

:: Set an upperbound to the VB disk at 150GB, 2TB is the VMDK MAX
:: @todo: add a KALABOX_DISK_SPACE to customize this?
IF %FREE_DISK% GTR 150000 (
  SET VB_DISK=150000
) ELSE (
  SET VB_DISK=%FREE_DISK%
)

:: If the Kalabox2 VM does not exist then create it
:: @todo: handle errors?
"%VBOXMANAGE%" list vms | findstr "%VM%"
IF %ERRORLEVEL% NEQ 0 (

  :: Do a basic check to make sure we clear out the filth
  "%DOCKER_MACHINE%" rm -f "%VM%"
  RD /S /Q "%USERPROFILE%/.docker/machine/machines/%VM%"

  :: Create the machine
  "%DOCKER_MACHINE%" create -d virtualbox ^
    --virtualbox-memory 2048 ^
    --virtualbox-disk-size "%VB_DISK%" ^
    --virtualbox-hostonly-cidr 10.13.37.1/24 ^
    "%VM%"

)

:: If the machine is not running start it up and regenerate certs
"%DOCKER_MACHINE%" status "%VM%" | findstr Running
IF %ERRORLEVEL% NEQ 0 (
  "%DOCKER_MACHINE%" start "%VM%"
  ECHO y | "%DOCKER_MACHINE%" regenerate-certs "%VM%"
)
```

**Comment by pirog** [comment]
OK i've got a PR in for this that removes `yes` and also adds a little more help to the installer aka

1. It will throw an error if any of the scripts fails
2. It will report the exit code status in the innosetup log

i think that is probably the best we can do for now without doing a pretty big rewrite of teh scripts to get them to interact with innosetup better
