### ISSUE TITLE
Uninstall on Linux does not remove docker.exec and docker.graph

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1565]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

v0.13.0-rc1 and Ubuntu 16.04

Have you previously installed Kalabox? If so, what version?

Yes all

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

Seeing this again as it was in #1358 

```
john@kalamuna:~/.kalabox/apps$ kbox create pantheon -- --nofiles
? Choose a Pantheon account: john@kalamuna.com
? Which site? cuesa7
? Which environment? header
? What will you call this monster you have created: cuesa7
Creating.
Cleaning up.
Creating app structure.
Configuring app.
Running pre create tasks.
Starting app.
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Creating cuesa7_redis_1
Creating cuesa7_data_1
Creating cuesa7_solr_1
Creating cuesa7_db_1
Creating cuesa7_appserver_1
Creating cuesa7_cli_1
Creating cuesa7_terminus_1
Creating cuesa7_web_1
Creating cuesa7_edge_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Running post create tasks.
Failed after 5 retries. {"max":5,"backoff":500}: Starting cuesa7_redis_1
Starting cuesa7_data_1
Starting cuesa7_db_1
Cannot start container d67b16b8f3ef836ac802fb6bb02206bf519bf1dc1f1a27d94ad94a46f12d428f: Cannot link to a non running container: /cuesa7_db_1 AS /cuesa7_terminus_run_5/cuesa7_db_1

VError: Starting cuesa7_redis_1
Starting cuesa7_data_1
Starting cuesa7_db_1
Cannot start container d67b16b8f3ef836ac802fb6bb02206bf519bf1dc1f1a27d94ad94a46f12d428f: Cannot link to a non running container: /cuesa7_db_1 AS /cuesa7_terminus_run_5/cuesa7_db_1

    at buildVerror (/usr/share/kalabox/bin/lib/util/shell.js.jx:52:10)
    at /usr/share/kalabox/bin/lib/util/shell.js.jx:90:16
    at /usr/share/kalabox/bin/node_modules/shelljs/src/exec.js.jx:166:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Process.ChildProcess._handle.onexit (child_process.js:839:5)
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

Complete pruge of beta4, install rc1, restarted.  Tried twice to install an app, got the error above.  

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using Kalabox?
Yes

**Comment by labboy0276** [comment]
I noticed on purge again that the /usr/share/kalabox was not removed using 

```
sudo dpkg --purge kalabox
```

So I manually removed it, reinstalled kalabox and that resolved the issue.

**Comment by pirog** [comment]
#1358 is unrelated. How did you uninstall/purge to being with? We don't remove `/usr/share/kalabox` by default since this will kill all your apps if you are only trying to upgrade.

**Comment by labboy0276** [comment]
Hello!

I purged via:
```
sudo dpkg --purge kalabox
```

**Comment by pirog** [comment]
@labboy0276 so it looks like `/usr/share/kalabox` is mostly removed with the exception of `docker.exec` and `docker.graph` so i think we just need to make sure we remove those as well.

**Comment by pirog** [comment]
@labboy0276 for the future i think its recommended to just update your package (as opposed to purging and then reinstalling). 

If you are going to remove or purge with the intention of reinstalling it probably makes sense to make sure you destroy all your apps first otherwise you are going to have orphaned containers between reinstalls.
