### ISSUE TITLE
Creating kbox site from existing D8 pantheon site does not work well.

### ISSUE THREAD

**Issue by jdelon02** [kalabox/kalabox#1566]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Mac osx Yosemite (10.10.5)

Have you previously installed Kalabox? If so, what version?
I have had kalabox since v11, and upgrade whenever a new release comes out.  I am currently running the latest release candidate - Version 0.13.0-rc.1 (0.13.0-rc.1)

**Tell us about your bug**

I am trying to create a Drupal 8 site from an existing Pantheon site (also D8).  This issue only occurs for me when I pull D8 sites down.

> 1. Started up GUI
> 2. Clicked on my Pantheon account in the sidebar
> 3. Selected an existing Drupal 8 site and an environment (any environment)
> 4. Kept the default options and pressed submit
> 5. Then, after the site is "created" and running (according to the gui), I cd into the directory.  At that point, half of the folders/files that should be in the repo are simply not there.  
> 6. I try to do a git fetch; git pull from the command line, and the response is "up to date".
> 7. I try to do a pull from the gui, and it runs.  A few more folders/files show up.
> 8. Wash... Rinse... Repeat... until the code shows as complete...

I have had to repeat this step as many as 7 times before the code seems to be completely there.  This is a major issue, since this process takes as long as 20 minutes, and cannot be predicted in any way.  

The really odd thing about this is that the site will load in the browser, and appears to be complete, even when files/folders are still missing.  I mean, no theme folder, and the site loads fine on the screen.  No sites/default folder, and the site loads fine...  Etc...

Could better documentation have prevented this issue? if so what should we change?
No, I think this is something else.

Does this bug prevent you from using Kalabox?
Yes - It takes 20 some minutes to pull code down after kalabox reports that the site has been created.

Feature/Enhancement Request
===========================

**Comment by pirog** [comment]
@jdelon02 if your site is loading in the browser then you definitely have your code. 

i think what you are probably describing is the syncing that happens between your code inside the containers in the VM and the code on your host. There are various issues here and our documentation (http://docs.kalabox.io/en/stable/users/config/#sharing) on how to optimize this process. 

The tl;dr there is if your computer is older/slow and you have A LOT of files in your repo this initial sync can take a bit although 20 minutes is VERY long, usually its max a few minutes.

**Comment by jdelon02** [comment]
One issue that I see when I read the documentation you shared is that all of the optimization seems to be on a "per app" basis.   If I want to apply, for example, the exclusion of node_modules/vendor/etc... from all apps created/synced; what file would I edit to have that apply globally?  Is it the one in the Application folder (on osx), or is there a local yml file that overrides if it is in the .kalabox root?  Where do I go to apply that change across the board.  If it is on a per-project basis, then there is really no way to exclude those files ahead of the initial code pull, since they would already be in the pantheon repo, and kalabox would simply automatically pull them down when I use the GUI.

**Comment by pirog** [comment]
@jdelon02 it is all on a per-app basis. Due to the architecture we use this is unlikely to change. 

How large is your git repo? Do you have any cruft in your git history (read: large static assets that should not be checked into your repo)? 

We've benchmarked with a lot of fairly large client projects (git repo is ~300ishMB) and it never takes more than a few minutes to do the initial sync. Then we switch over to an optimized sync config if needed.
