### ISSUE TITLE
Kalabox CLI Database Port information

### ISSUE THREAD

**Issue by bgonz** [kalabox/kalabox#1568]
The Database port number changes every time I run 'kbox start'
- this is fine

But how do I get the Database Environment Port # using the CLI?
I can easily get this using the GUI -> Connection Info

I thought it would be 'kbox env' - but I could not find it. I even used the GUI -> to get the Connection Info -> then did a Find in terminal for that port # but found nothing.

**Comment by labboy0276** [comment]
kbox services

**Comment by bgonz** [comment]
Thanks - @labboy0276

That was it!

I really did read the docs - honestly - a ton. Its all habit forming at this point. Much appreciated!

**Comment by pirog** [comment]
@bgonz anything that could be improved in the docs to make this most clear?
