### ISSUE TITLE
Authentication Failed Notice Appearing Erroniously

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1569]
I happen to have a large number of sites, and when fetching the list I get this warning:

> Authentication failed. Please re-authenticate your Pantheon account.

However, the list does complete and I can move on and add sites. 

`kbox create pantheon` has no problem listing the sites.

**Comment by pirog** [comment]
@reynoldsalec im less familiar with the GUI code but seems like this could be responsible
https://github.com/kalabox/kalabox/blob/v0.13/src/modules/guiEngine/providers.js#L76

Good news is that i think most users will not have as many sites as @joshkoenig so immediate user impact should be lower. That said this could also impact users with slower internet connections.

**Comment by reynoldsalec** [comment]
Ok, removed the timeout both on initial authentication of an account and on site refresh. I invalidated one of my machine tokens to see what would happen if an error occurred during authentication and the correct error message showed up, so I think simply removing those timeouts and relying on the lower-level Kalabox commands to deliver an error when a connection issue or authentication issue occurs is a good solution.
