### ISSUE TITLE
GUI Hangs When Clicking "Pull" Action

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1570]
The `Pull` action for a site causes the GUI to hang, likely because it's requesting an environment list from Pantheon. However, unlike on the `Connection Info` action, there's no status info.

Also, it only ever gives me the dev environment as an option. Is that correct?

**Comment by pirog** [comment]
@reynoldsalec ive merged this in

**Comment by pirog** [comment]
@reynoldsalec actually, on second thought maybe we want to also remove the buttons here?
![screen shot 2016-09-09 at 12 45 49 pm](https://cloud.githubusercontent.com/assets/713424/18400574/5b90e940-768b-11e6-8b6e-3a0b04048530.png)

**Comment by reynoldsalec** [comment]
Thanks for pointing that out @pirog, resolved.
