### ISSUE TITLE
Broken Screenshot

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1571]
I'm seeing a broken screenshot (broken image) for a recently fetched site. Is there a way to refresh that?

![screen shot 2016-09-09 at 9 46 23 am](https://cloud.githubusercontent.com/assets/143186/18395184/4bd67be6-7672-11e6-88d0-89246ecd947e.png)

**Comment by pirog** [comment]
@joshkoenig i am **pretty sure** that every time you do a pull it should try to grab the screenshot. We also should have a fallback (the pantheon unicorn) for pantheon sites if there is no screenshot. 
Not sure if this is a regression or just something funky with that site. You mind sharing that site with me?

**Comment by joshkoenig** [comment]
Added you to the site.

**Comment by pirog** [comment]
@joshkoenig yeah i can replicate this but not exactly sure why this is happening yet. The screenshot definitely exists and is in the place we would expect it.

**Comment by pirog** [comment]
So looks like Kalabox is pulling from a potentially legacy domain
http://s3.amazonaws.com/pantheon-screenshots/ ? 

@joshkoenig what is the best way for us to stay up to speed with where to get the screenshots? 

For now i guess we can round robin the possible hosts.

**Comment by joshkoenig** [comment]
Let me ask the eng team where the best place is. I know we moved to cloudfront to speed things up not too long ago.

**Comment by joshkoenig** [comment]
Looks like the answer is now https://s3.amazonaws.com/pantheon-screenshots-v2 - eg:

https://s3.amazonaws.com/pantheon-screenshots-v2/live/3ecd4d40-bdf2-4e52-a519-7e697ecdfe20.jpg

or https://dsvtten8xijg8.cloudfront.net/

**Comment by pirog** [comment]
Awesome. Should be easy to switch this out.
