### ISSUE TITLE
Pull (also push?) Operation Doesn't Show Status

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1574]
When I do a "Pull" operation, it doesn't show me status messages like it did while I was setting up the new local site instance. This could be challenging if the pull takes a lot of time (e.g. there's a lot of data). 

I just have this:

![screen shot 2016-09-09 at 1 13 45 pm](https://cloud.githubusercontent.com/assets/143186/18401482/6e5796ce-768f-11e6-8bb8-d6fb18a1b43b.png)

Until it completes at the end.

**Comment by pirog** [comment]
@joshkoenig hmm yeah that is no good. could be a regression. @reynoldsalec might know more.
