### ISSUE TITLE
Single commands to create, or some way to script kalabox builds?

### ISSUE THREAD

**Issue by leevh** [kalabox/kalabox#1576]
Searched documentation and issue queue, my apologies if I missed it.  I'm looking for a way to easily script the creating of a kbox/pantheon site for use in CI.  

Something like 

> kbox create pantheon my@email.com my-pantheon-site dev

Rather than the (awesome) interactive method.  Is there something like this?

As a follow up to this, I can't seem to find if there is a way to create a kbox drupal app from an existing codebase.  For example, if I could clone my code base into "project/code" and then create a D7 app out of that, that would be pretty useful.   I could probably work around this with a few scripted commands though.

**Comment by pirog** [comment]
@leevh this is in the documentation depending on the app you want to create. see 
http://pantheon.kalabox.io/en/stable/users/cli/
http://php.kalabox.io/en/stable/users/cli/

We do not currently offer a way to import a site. A scripted worfklow to do something like that (for D7 in this example) would be 

1. Create D7 site
2. Remove stock D7 codebase
3. Clone your upstream repo
4. Grab and relevant DB/FILES
5. Drush clear caches

**Comment by leevh** [comment]
Awesome, thanks @pirog , sorry I somehow missed that!  

Just a quick aside question, have you ever ran kbox inside a docker container?  I wanted to try using kbox  as part of a dockerized build environment, but then I realized it would be docker-in-docker.  I'll give it a shot, just curious.  thanks again

**Comment by pirog** [comment]
@leevh i have not and i'm not exactly clear why you would do that? 

you can do docker-inside-of-docker afaik though.

**Comment by leevh** [comment]
@pirog Well I guess if you wanted to package up a totally portable build environment, you'd want all your tools in the docker image:  kbox, phantomjs, selenium etc.   Maybe I'm over thinking it.  Anyways, thanks again for your help :+1:

**Comment by pirog** [comment]
@leevh i think this is more or less what kalabox already does? 

if you wanted to add additonal tools youd probably want them in their own containers/images and then you could add them to your apps `kalabox-compose.yml` (which is just a docker compose file). Or you could build a plugin like we did to add `wraith` to a kalabox app
https://github.com/kalabox/wraith

either way let me know how it goes. def curious to see how people are using this stuff!
