### ISSUE TITLE
Make VirtualBox installation optional if already installed

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1584]
Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

As a user who works with a large number of virtual environments on my local machine, I want the option to not re-install VirtualBox every time I install Kalabox.

I've had VirtualBox installed for years and have always kept it updated myself. Certain versions have quirks on Windows, and the VirtualBox installer is sometimes disruptive (it can disconnect active connections when it resets the network, and I want control over when that happens). I'm allowed to uncheck Git for Windows in the Kalabox installer since I've already got Git installed, so I'd like to be able to do something similar with VirtualBox.

Please provide some detail on how Kalabox can help solve this problem

It would help if either (a) the checkbox wasn't grayed out so I could choose to not re-install VirtualBox, or (b) there was some logic in the installer to determine if a high enough version of VirtualBox is already installed and allow to skip re-installation if so.

**Comment by pirog** [comment]
@bmcclure decided to remove VB for all 2.1.x+ versions!
