### ISSUE TITLE
Possible issue with kbox destroy

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1585]
I don't know if this is inevitable, but when using kbox destroy from an app's directory, there are a series of error messages about being unable to remove the directory (I assume because one is in it?)

The directory and files then need to be removed manually, I believe.

**Comment by pirog** [comment]
@jsibley2 can you post the actual error(s)? Or the kinds of apps you are removing? Actual steps to replicate?

Pretty hard to help without any of those things.

**Comment by jsibley2** [comment]
No problem.


                    BOOMSHAKALAKA!

  Your app has started up correctly. Here are some vitals:

  URL: http(s)://d7test.kbox
  LOCATION: C:\Users\Jonathan\d7test

###############################################################

C:\Users\Jonathan>cd d7test

C:\Users\Jonathan\d7test>kbox destroy
###############################################################

        WARNING! DESTRUCTION IMMINENT FOR APP D7TEST

  This command will remove all the containers needed to run
  your app such as services, containers, databases, caches
  indeces, etc. Your app's code WILL ALSO BE DESTROYED
  locally at C:\Users\Jonathan\d7test

###############################################################
? So, are you still prepared to DESTROY? (y/N) y
? So, are you still prepared to DESTROY? Yes
Destroying.
Running pre destroy tasks.
Stopping.
Stopping.
Cleaning up.
Running pre stop tasks.
Stopping containers.
Stopping d7test_appserver_1 ...
Stopping d7test_db_1 ...
Stopping d7test_unison_1 ...
[1BRunning post stop tasks. doneone
Uninstalling.
Removing d7test_cli_1 ...
Removing d7test_appserver_1 ...
Removing d7test_drush_1 ...
Removing d7test_db_1 ...
Removing d7test_unison_1 ...
Removing d7test_data_1 ...
[4BRunning post destroy tasks.edone
###############################################################

                 DESTRUCTION COMPLETE

###############################################################
Removing files.
Error while removing dir: C:\Users\Jonathan\d7test: EBUSY, rmdir 'C:\Users\Jonathan\d7test'
Error: EBUSY, rmdir 'C:\Users\Jonathan\d7test'

**Comment by pirog** [comment]
@jsibley2 thanks! that is certainly much more helpful. i definitely have not seen this show up in our tests or in my somewhat casual use on windows but at least we have something to look out for now.

in the meantime, i would just make sure you manually remove the files. Alternatively you can try a few things

1. Delete the app from a different directory with `kbox APPNAME destroy` 
2. Delete from the GUI

As you noted, Windows is pretty fickle with what it lets you do on the file system so if you have this resource open elsewhere a la a text editor or explorer window then the error you get would make sense.
