### ISSUE TITLE
Site create on GUI shows no messages between "Creating..." and "Pulling Images", goes blank seemingly randomly

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1586]
# Bug Report

**Tell us about your setup**

v0.13.0-RC2 on Mac OS

Installed after a complete uninstall.

**Tell us about your bug**

On pulling a Pantheon app, the app first shows a "Creating..." status message, then goes blank for a period of time (5+ seconds) until the first Docker container images start pulling.

**Comment by pirog** [comment]
I **think** this **ONLY** happens for pantheon apps but i could be wrong

**Comment by aaronlutze** [comment]
I had a similar issue, and posted this [https://github.com/kalabox/kalabox/issues/1630](url). Here is my result:

Ok, so the pulling of files 'fixed' itself after the second site was setup. I am not sure if it was just stuck, or, if setting up a 2nd site magically fixed this.

Perhaps try importing a second site from pantheon to see if it fixes it for you.

**Comment by reynoldsalec** [comment]
Ok, I think I see the issue that was causing this. The dummy app inserted into the DOM has a status of "Creating...", but when it's replaced by the real app object, the status attribute takes a bit to refresh.

To fix, I've set the real app object's initial status state to "Creating..." to make the process seamless.

**Comment by bfriel** [comment]
Hi there, I had the exact same experience that aaronlutze posted about back in September. Just downloaded Kalabox 2.1.3 on OX 10.11.6 -- got stuck repeatedly on "Pulling Files" until I simultaneously imported a second site as per his suggestion. 

Everything works fine now, just wanted to share my experience. Thanks for the great work!
