### ISSUE TITLE
GUI based push/pull no longer work on RC2

### ISSUE THREAD

**Issue by aristomenis** [kalabox/kalabox#1587]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
**kalabox-v0.13.0-rc.2.dmb on Mac OS X El Capitan 10.11.6**

Have you previously installed Kalabox? If so, what version?
**Yes, I've installed Kalabox RC1**

**Tell us about your bug**

Trying to use the Pull option for DB and Files via the GUI and it does not seem to end up doing anything.  I see the following in the kalabox.log:

**TypeError: app.pull is not a function**

I tried uninstalling and reinstalling a couple times, but still same result.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

**1. Started up GUI
2. Chose Pull for DB and Files from Dev environment
... Also tried via start GUI, power on site, then Pull**

Does this bug prevent you from using Kalabox?

**No. At the moment I'm continuing to use Kalabox via updating DB and Files manually / programmatically.**

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

**As a Kalabox user who loves moving fast watching my Drupal cape flow in the wind as I dance from cloud to cloud, I find it a smidgeon of an impedance in my enjoyment of said hobby that I must manually lift with my huge arms a myriad of databases and files - not to mention the impact it has on my poor, old back.  I relish the ability to do said task with merely the flick of a couple mouse buttons via the Kalabox GUI.**

Please provide some detail on how Kalabox can help solve this problem

**Ensure the GUI Pull option is working.**

**Comment by pirog** [comment]
@aristomenis please consult the release notes on upgrading. You need to make sure you remove apps you created on earlier kalabox versions. These apps will need to be recreated.

What you are experiencing is expected if you do not do this.

**Comment by aristomenis** [comment]
Hmm okay I misunderstood the FAQ then.  "Destroy app" ~ manually destroy any Drupal sites I've got in the prior Kalabox install?

**Comment by pirog** [comment]
yeah `site in dashboard = kalabox app`.

**Comment by aristomenis** [comment]
So, I...
- deleted my apps
- uninstalled kalabox
- reinstalled kalabox
- added back my app via pantheon creds

That pulled everything in great.

Then I...
- changed a db setting on my Pantheon dev site
- created a new db backup on Pantheon
- Did a pull via kalabox GUI

That took a bit, but end result was no DB change on the kalabox local.

Is there some special item I need to brute force uninstall manually?  For now though, I can delete app then add app back in and everything pulls in fine.

**Comment by pirog** [comment]
@aristomenis we don't pull the database backup so you dont need to do that step. it should pull directly from whatever environment you tell it to. 

so, i just tested this out and i also was unable to pull a site from the GUI. That said, this DOES seem to still work on the CLI so i would definitely give that a try as a workaround for now. 

I'm going to elevate this issue since this is very critical.

**Comment by aristomenis** [comment]
Sounds good. Thanks.

**Comment by pirog** [comment]
@aristomenis there is an RC3 release posted now that should resolve this. SORRY FOR THE REGRESSION!

**Comment by aristomenis** [comment]
Excellent. Thanks for all the work.
