### ISSUE TITLE
Occasionally kbox gets in bad state and starts returning exit code 255

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1591]
Using the latest Kalabox version (RC2) on Windows 10 Professional 64-bit, everything works great normally. Every once in a while (haven't yet pinpointed any consistency, it only happened once in the last 8 hours or so), kbox commands start returning "exit status 255"

For example:
```
λ kbox restart
Stopping.
Cleaning up.
exit status 255
exit status 255
```

`kbox down` has the same issue when this occurs. The only way I've been able to solve this problem so far is:
1. `docker-machine stop Kalabox2`
2. `kbox down` (which now succeeds once the VM is already stopped, I'm not even sure if this step is needed)
3. `kbox up`

I did a quick search but didn't come up with any other issues related to this. I don't have much time at the moment however and just wanted to get this documented, so I apologize if this is a duplicate.

**Comment by pirog** [comment]
I did add some comments to this issue earlier which look somewhat like this but still too early to tell
https://github.com/kalabox/kalabox/issues/1386

I think @jsibley2 experienced this as well. Is there any extra debug info in the log to help us drill down on this a bit?

**Comment by aangelinsf** [comment]
Seeing this, too.

**Comment by pirog** [comment]
@aangelinsf good to know. 

Do you have any idea on how to replicate this? 
Have you looked at the referenced issue https://github.com/kalabox/kalabox/issues/1386#issuecomment-247166876 above to see if that is what you are experiencing?

**Comment by aangelinsf** [comment]
Not yet...it's happened only once so far and that had me come here to see if there had been other reports. I had attempted a "kbox status" and got just "exit status 255."

If I think I can reproduce it I will update this issue.

**Comment by pirog** [comment]
@aangelinsf sounds good. hopefully ill have time to research this a bit later as well.

**Comment by pirog** [comment]
@bmcclure i think this should no longer be an issue if you are using the new 2.1 version that runs hyperV instead of virtualbox. since we've switched to that i think its safe to mark this as "will not fix"
