### ISSUE TITLE
Kalatheme issue: "The website encountered an unexpected error. Please try again later."

### ISSUE THREAD

**Issue by mollask** [kalabox/kalabox#1592]
I get this error when switching to the Kalatheme on Pantheon. 

"The website encountered an unexpected error. Please try again later."

I've loaded all the required modules into Drupal 8 listed on the Kalatheme for Drupal 7 page, that weren't added to D8 already - namely CTools, Panels, and the Layout Plugin. Everything else is now already in the base of Drupal 8. 
I loaded the Bootstrap theme.
I can switch back to any other theme including Bootstrap.

Bug Report
==========
System:
Pantheon Panopoly
kalatheme-8.x-5.x-dev

Never installed Kalatheme before. I have Kalabox, but not currently using.

I cannot currently use the theme.

**Comment by pirog** [comment]
@mollask maybe you meant for this to be over at the kalatheme queue?
https://github.com/drupalprojects/kalatheme

I dont think there is an official D8 release for kalatheme yet so YMMV if you are trying the dev release.

**Comment by mollask** [comment]
Hi Pirog. I found one on Drupal.org that loaded in D8. https://www.drupal.org/node/2752351. But I get the error listed above. I was hoping someone here would know what was up, as this is a dev version.

**Comment by pirog** [comment]
@mollask this is the issue queue for kala**box** not kala**theme**. Recommend you post on the kalatheme queue to get support for kalatheme
https://github.com/drupalprojects/kalatheme
