### ISSUE TITLE
Stucked at - Waiting for site to be ready on Pantheon App

### ISSUE THREAD

**Issue by welyanto** [kalabox/kalabox#1593]
1.  I don't see any topics related
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
0.13.0-rc.1 - Windows 10 Home Single Language

Have you previously installed Kalabox? If so, what version?
No

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.
I don't see any Error Message but i'm stucked at "Waiting for site to be ready" waiting for long time but nothing happens. Restart, Destroy, Rebuild, Re Pull still nothing happens, stucked at there.
additional Info: i'm already pull all the code & database from "Pantheon"
I see on "kbox list" where i can open at my browser but it's not working either

> Sorry, the page you are looking for is currently unavailable.
> Please try again later.
> If you are the system administrator of this resource then you should check the error log for details.
> Faithfully yours, nginx.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
> 1. open cmd
> 2. cd myapp
> 3. kbox start

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
@welyanto so Kalabox will wait for your site to return a site code of `200 OK` before it reports it as ready. However, i think you should still be able to hit the site in the browser while this is happening. Seems like that is not true for you? 

Bear in mind that the site might actually not be up and running yet if you do this eg you will get the `502` page. 

Additionally, is it possible that your site has an error or something that would actually cause a non-200 response code? 

Maybe we should change our check to be a little less strict so even if a site errors the user can get to the page.

**Comment by pirog** [comment]
@welyanto actually going to open this up a bit before we do our stable

**Comment by welyanto** [comment]
@pirog Thanks, i'm still trying to get this resolve also. i will keep updates whatever error i found/spot.
i don't have any error on my console at my Live site that can cause non-200 response code.
And yes i can't hit to open my site on my local while it saying "Waiting your site to be ready"

this is what showing after i'm waiting

```
C:\Users\welyanto\mscapelocal>kbox start
Starting.
Cleaning up.
Running pre start tasks.
Starting containers.
Starting mscapelocal_data_1
Starting mscapelocal_redis_1
Starting mscapelocal_db_1
Starting mscapelocal_web_1
mscapelocal_unison_1 is up-to-date
Starting mscapelocal_solr_1
Starting mscapelocal_cli_1
Starting mscapelocal_appserver_1
Starting mscapelocal_terminus_1
Starting mscapelocal_edge_1
Running post start tasks.
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
Waiting for site to be ready.
Unhandled rejection VError: Failed after 50 retries. {"max":50,"backoff":500}: getaddrinfo ENOTFOUND
    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:70:17
    at process._tickCallback (node.js:917:13)
```

**Comment by pirog** [comment]
@welyanto you can always try running the command as `kbox restart -- -d` to get more output that might help you debug. 

Can you confirm that you got your sites code pulled down from pantheon? can you confirm the kalabox proxy server is up and running (visit `something.kbox` in your non-edge browser, should get a 400/502)

**Comment by welyanto** [comment]
@pirog already do kbox restart -- -d
showing

```
Starting mscapelocal_data_1
Starting mscapelocal_redis_1
Starting mscapelocal_db_1
Starting mscapelocal_web_1
Starting mscapelocal_unison_1
Starting mscapelocal_solr_1
Starting mscapelocal_edge_1
Starting mscapelocal_cli_1
Starting mscapelocal_appserver_1
Starting mscapelocal_terminus_1
debug: SPAWN DOCKER-COMPOSE.EXE ==> Spawn exited with code: 0
debug: EVENTS ==> Emitting event [post-engine-start]. unknown
debug: EVENTS ==> No listeners [post-engine-start].
debug: EVENTS ==> Finished dispatching event listeners [post-engine-start].
info: Running post start tasks.
Running post start tasks.
debug: EVENTS ==> Emitting event [pre-engine-start]. unknown
debug: EVENTS ==> No listeners [pre-engine-start].
debug: EVENTS ==> Finished dispatching event listeners [pre-engine-start].
verbose: DOCKER COMPOSE ==> Running: ["--project-name","kalabox","--file","C:\\Users\\welyanto\\.kalabox\\downloads\\kalabox\\kalabox-3.yml","up","-d","dns","proxy"]
debug: SPAWN DOCKER-COMPOSE.EXE ==> Using C:\Program Files\Kalabox\bin\docker-compose.exe to run --project-name,kalabox,--file,C:\Users\welyanto\.kalabox\downloads\kalabox\kalabox-3.yml,up,-d,dns,proxy in collect mode with environment {"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\welyanto\\AppData\\Roaming","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","COMPUTERNAME":"WELYANTO","ComSpec":"C:\\WINDOWS\\system32\\cmd.exe","DOCKER_CERT_PATH":"C:\\Users\\welyanto\\.docker\\machine\\certs","DOCKER_HOST":"tcp://10.13.37.100:2376","DOCKER_MACHINE_NAME":"Kalabox2","DOCKER_TLS_VERIFY":"1","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","FPS_BROWSER_USER_PROFILE_STRING":"Default","FP_NO_HOST_CHECK":"NO","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\welyanto","INIT_CWD":"C:\\Users\\welyanto\\mscapelocal","KALABOX_APPS_ROOT":"C:\\Users\\welyanto\\.kalabox/apps","KALABOX_APP_REGISTRY":"C:\\Users\\welyanto\\.kalabox/appRegistry.json","KALABOX_CONFIG_SOURCES":"[\"C:\\\\Program Files\\\\Kalabox\\\\bin\\\\kalabox.yml\",\"C:\\\\Program Files\\\\Kalabox\\\\kalabox.yml\",\"DEFAULT_GLOBAL_CONFIG\",\"ENV_CONFIG\"]","KALABOX_DEV_MODE":"false","KALABOX_DOMAIN":"kbox","KALABOX_DOWNLOADS_ROOT":"C:\\Users\\welyanto\\.kalabox/downloads","KALABOX_ENGINE":"kalabox-engine-docker","KALABOX_ENGINE_GID":"50","KALABOX_ENGINE_HOME":"/c/Users/welyanto","KALABOX_ENGINE_ID":"1000","KALABOX_ENGINE_IP":"10.13.37.100","KALABOX_ENGINE_REMOTE_IP":"10.13.37.1","KALABOX_ENGINE_REPO":"kalabox","KALABOX_GLOBAL_PLUGINS":"[\"kalabox-core\",\"kalabox-cmd\",\"kalabox-services-kalabox\",\"kalabox-sharing\",\"kalabox-ui\",\"kalabox-app-pantheon\",\"kalabox-app-php\"]","KALABOX_HOME":"C:\\Users\\welyanto","KALABOX_IMG_VERSION":"latest","KALABOX_INSTALL_PATH":"C:\\Program Files\\Kalabox","KALABOX_IS_BINARY":"true","KALABOX_IS_NW":"false","KALABOX_LOG_LEVEL":"debug","KALABOX_LOG_LEVEL_CONSOLE":"none","KALABOX_LOG_ROOT":"C:\\Users\\welyanto\\.kalabox/logs","KALABOX_OS":"{\"type\":\"Windows_NT\",\"platform\":\"win32\",\"release\":\"6.3.9600\",\"arch\":\"x64\"}","KALABOX_SRC_ROOT":"C:\\Program Files\\Kalabox\\bin","KALABOX_STATS":"{\"report\":true,\"url\":\"http://stats-v2.kalabox.io\"}","KALABOX_SYS_CONF_ROOT":"C:\\Program Files\\Kalabox","KALABOX_SYS_PLUGIN_ROOT":"C:\\Program Files\\Kalabox","KALABOX_USER_CONF_ROOT":"C:\\Users\\welyanto\\.kalabox","KALABOX_USER_PLUGIN_ROOT":"C:\\Users\\welyanto\\.kalabox","KALABOX_VERSION":"0.13.0-rc.1","LOCALAPPDATA":"C:\\Users\\welyanto\\AppData\\Local","LOGONSERVER":"\\\\WELYANTO","NUMBER_OF_PROCESSORS":"8","OS":"Windows_NT","Path":"C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Kalabox\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\cURL\\bin;C:\\Users\\welyanto\\AppData\\Roaming\\npm;C:\\Program Files\\Kalabox\\bin;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 60 Stepping 3, GenuineIntel","PROCESSOR_LEVEL":"6","PROCESSOR_REVISION":"3c03","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","PROMPT":"$P$G","PSModulePath":"C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\","PUBLIC":"C:\\Users\\Public","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\WINDOWS","TEMP":"C:\\Users\\welyanto\\AppData\\Local\\Temp","TMP":"C:\\Users\\welyanto\\AppData\\Local\\Temp","USERDOMAIN":"Welyanto","USERDOMAIN_ROAMINGPROFILE":"Welyanto","USERNAME":"welyanto","USERPROFILE":"C:\\Users\\welyanto","VBOX_MSI_INSTALL_PATH":"C:\\Program Files\\Oracle\\VirtualBox\\","windir":"C:\\WINDOWS"}
kalabox_proxy_1 is up-to-date
kalabox_dns_1 is up-to-date
debug: SPAWN DOCKER-COMPOSE.EXE ==> Spawn exited with code: 0
debug: EVENTS ==> Emitting event [post-engine-start]. unknown
debug: EVENTS ==> No listeners [post-engine-start].
debug: EVENTS ==> Finished dispatching event listeners [post-engine-start].
debug: SERVICES PLUGIN ==> Configuring DNS for web services.
verbose: DOCKER COMPOSE ==> Running: ["--project-name","mscapelocal","--file","C:\\Users\\welyanto\\mscapelocal\\kalabox-compose.yml","--file","C:\\Users\\welyanto\\mscapelocal\\kalabox-cli.yml","--file","C:\\Users\\welyanto\\.kalabox\\downloads\\mscapelocal\\mscapelocal-2.yml","ps","-q","web"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-compose.exe,--project-name,mscapelocal,--file,C:\Users\welyanto\mscapelocal\kalabox-compose.yml,--file,C:\Users\welyanto\mscapelocal\kalabox-cli.yml,--file,C:\Users\welyanto\.kalabox\downloads\mscapelocal\mscapelocal-2.yml,ps,-q,web
debug: SHELL EXEC ==> Running command "2f93c5a06887f25ccfbfd4cad4024d0f8c86d2ce21a4297c9cf183c4abbfa61f\r\n"
debug: SERVICES PLUGIN ==> Connecting to redis on 10.13.37.100:8160
debug: SERVICES PLUGIN ==> Connecting to redis on 10.13.37.100:8160
debug: SERVICES PLUGIN ==> Setting DNS. frontend:http://mscapelocal.kbox => http://10.13.37.100:32779
debug: SERVICES PLUGIN ==> Setting DNS. frontend:https://mscapelocal.kbox => https://10.13.37.100:32780
debug: SERVICES PLUGIN ==> Configuring DNS for edge services.
verbose: DOCKER COMPOSE ==> Running: ["--project-name","mscapelocal","--file","C:\\Users\\welyanto\\mscapelocal\\kalabox-compose.yml","--file","C:\\Users\\welyanto\\mscapelocal\\kalabox-cli.yml","--file","C:\\Users\\welyanto\\.kalabox\\downloads\\mscapelocal\\mscapelocal-2.yml","ps","-q","edge"]
debug: SHELL EXEC ==> Running command C:\Program Files\Kalabox\bin\docker-compose.exe,--project-name,mscapelocal,--file,C:\Users\welyanto\mscapelocal\kalabox-compose.yml,--file,C:\Users\welyanto\mscapelocal\kalabox-cli.yml,--file,C:\Users\welyanto\.kalabox\downloads\mscapelocal\mscapelocal-2.yml,ps,-q,edge
debug: SHELL EXEC ==> Running command "d50c111de6546b422fe04c4599868b29f16e885f88c65b585505ac2d831bd14b\r\n"
debug: SERVICES PLUGIN ==> Connecting to redis on 10.13.37.100:8160
debug: SERVICES PLUGIN ==> Connecting to redis on 10.13.37.100:8160
debug: SERVICES PLUGIN ==> Setting DNS. frontend:http://edge.mscapelocal.kbox => http://10.13.37.100:32782
debug: SERVICES PLUGIN ==> Setting DNS. frontend:https://edge.mscapelocal.kbox => https://10.13.37.100:32781
debug: CORE PLUGIN ==> Checking to see if http://mscapelocal.kbox is ready.
info: Waiting for site to be ready.
Waiting for site to be ready.
debug: CORE PLUGIN ==> Checking to see if http://mscapelocal.kbox is ready.
debug: CORE PLUGIN ==> Checking to see if http://mscapelocal.kbox is ready.
debug: CORE PLUGIN ==> http://mscapelocal.kbox is now ready.
debug: EVENTS ==> Emitting event [app-started]. unknown
debug: EVENTS ==> No listeners [app-started].
debug: EVENTS ==> Finished dispatching event listeners [app-started].
```

- trying something.kbox it showing "Server Not Found - 404"
- Also yes i'm already trying over & over to repull the files & database from server, it successed but still can't fixed the "stucked waiting site to be ready" (http://prntscr.com/cjxmfi , http://prntscr.com/cjxmlr)

**Comment by blakehall** [comment]
I've seen the same issue with our Pantheon site. In our case I think it's because we're using the new nested docroot feature.

Perhaps support for that should be a separate issue, but I figured I'd at least mention it here in case it's a common denominator in your case.

**Comment by pirog** [comment]
yeah id def open up another ticket for that. would be good to ping some
pantheon people to get their eyes on this as well.

That said, we do actually support nested docroot but you need to change
some things around in the config
http://docs.kalabox.io/en/stable/users/config/#sharing

**Comment by pirog** [comment]
@blakehall opened up a ticket #1622 that should cover the nested docroot func which i think is the main thing causing 404's. 

Going to close this.

**Comment by welyanto** [comment]
Hi @pirog 
i do download the latest version of kalabox after it released.
uninstall the old ones and install the new ones..
delete old apps, create new apps, pull database & files new apps, kbox restart, kbox down, kbox up, kbox rebuild, kbox start, kbox pull again, restart again, and i'm still stucked at Waiting for site to be ready.
is there any related internet connection, or something? the error i got still same

![0000](https://cloud.githubusercontent.com/assets/4454872/19396707/ef9de2d0-9276-11e6-814f-2089b0f35d81.jpg)

i do check all files are there, i believe current site isn't on nested it's should on root.

**Comment by pirog** [comment]
@welyanto what happens when you try to visit your site in the browser? Are you experiencing #1657 ?

**Comment by welyanto** [comment]
showing server not found:
![server-not-found](https://cloud.githubusercontent.com/assets/4454872/19397660/545b1c8e-927b-11e6-82a5-8c750e5dd61c.jpg)

check testing.kbox also i don't see any moving clouds.

**Comment by macronomicus** [comment]
I was getting the same as welyanto today, its strange because it was working fine for days and then today it wouldn't connect anymore with the same ENOTFOUND.   I had to uninstall/reinstall kalabox and virtualbox to get the networking functioning again, I'll try and get better notes if it happens again, from what I can tell it was the same as Welyanto said happened to him.

Im on Windows 10 Pro

**Comment by macronomicus** [comment]
Ok it happened again in the app, and separately doing **kbox start**.  What fixed it was going to CLI and running  **kbox restart -- -d** I waited a while and it eventually passed after 24 checks
**debug: CORE PLUGIN ==> Checking to see if http://thesite.kbox is ready.**  

I was able to access the site from the given edge IP access on IP:32777 before the checks cleared, it seems the "Setting DNS. frontend"  was not refreshing at that point, in the app it never cleared, eventually giving ENOTFOUND error.

**Comment by pirog** [comment]
@macronomicus are you getting this just for a particular site or on every site?

**Comment by macronomicus** [comment]
It only seemed to happen on one d8 pantheon site, it was still barebones plus commerce mods, no additions to the settings.php  

I see you've recently added a new release though, so im going to dump this build and install kalabox-v2.1.0-rc.2 :)

**Comment by pirog** [comment]
Must be site specific then. Are you enforcing HTTPS?

**Comment by macronomicus** [comment]
No, not on that site, though I did have that issue with another site that was https.  My error for the same as OP resulted perhaps from errors increasing the load time.  Maybe the op has a similar issue?  Mine was errors with composer dependencies, it borked on pantheons end too and had to restore to backup lol :D  oops

**Comment by develCuy** [comment]
Similar issues: #1487 #1327 #651 #111

DNS/resolver issues repeat randomly. I guess this requires a more robust solution, a good check that warns users when resolver is not working and good troubleshooting docs.

Just my 2c.

**Comment by pirog** [comment]
@develCuy if you've got a better suggestion on how to reliably do this on Windows i am all ears!!!

That said we added some DNS changes in the 2.1 version that might help this.
