### ISSUE TITLE
RC2, Win10(home), "Waiting for site to be ready"

### ISSUE THREAD

**Issue by Picturina** [kalabox/kalabox#1594]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**
PC tower with modest internet access via our network, to be improved in a few days

What is your Kalabox version and operating system?
vRC2, Windows 10 home (gack!)

Have you previously installed Kalabox? If so, what version?
Yes, RC1, and before that the betas.

**Tell us about your bug**
Give a brief description of what happened, including any error messages that appeared.

Had two sites pulled into RC1 and working well.  A third would not pull no matter how many times I tried.  So I waited for RC2. 
1.  Once RC2 was installed, I tried the failed site again, and when it would not pull I deleted it from Kalabox.
2. Tried to start one of the two previously working sites. Now, instead of loading this site, RC2 freezes on "Waiting for site to be ready".  Eventually that messages drops, and I'm left with a greyed out thumbnail and the site is not started.  Tried 3 times with same result.
3. Shut down KB vRC2 (not forced close, so it takes a really long time)
4. Started KB vRC2 again and tried to start that previously working site again.
5. Hung up again on "Waiting for site to be ready"

**Tell us more**
Do I need to completely restart my computer after deleting a project?  This would be really unfortunate.

Does this bug prevent you from using Kalabox?
Yes, presently I've lost the little funcationality I had with RC1

Thanks,
Diane

**Comment by pirog** [comment]
@Picturina did you follow the release notes for upgrade to RC2? there was a breaking change introduced that requires a full uninstall (including all your old apps). 

Also please consult the issue queue before reporting an issue. Looks like this issue is already tracked over here
https://github.com/kalabox/kalabox/issues/1593

**Comment by Picturina** [comment]
Hi Mike,

On 2016-09-17 14:37, Mike Pirog wrote:

> @Picturina [1] did you follow the release notes for upgrade to RC2? there was a breaking change introduced that requires a full uninstall (including all your old apps). 
> 
> I THOUGHT I FOLLOWED THE INSTRUCTIONS, BUT I DID NOT SEE A FULL INSTALL RECOMMENDATION.... I GUESS I HAVE TO GO BACK AND LOOK DEEPER.  WILL THERE BE A DIRECT UPGRADE PROCESS FROM RC2 TO RC3? 
> 
> Also please consult the issue queue before reporting an issue. Looks like this issue is already tracked over here
> #1593 [2] 
> 
> -- 
> 
> IT LOOKED DIFFERENT TO ME, AS IT WAS RC1, WHEREAS  I WAS HITTING THE SNAG WITH RC2. 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/Picturina
[2] https://github.com/kalabox/kalabox/issues/1593
[3]
https://github.com/kalabox/kalabox/issues/1594#issuecomment-247809625
[4]
