### ISSUE TITLE
Kalabox Pull has different options in GUI vs. CLI

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1596]
Bug Report
==========

**Setup**

Kalabox 0.13.0-rc.2
Mac OS X El Capitan 10.11.6
Pantheon Drupal 8 site:
* Dev environment created
* Two multidevs created 
* Test and Live not set up yet

**Bug**

After adding the site via the Kalabox GUI, I went to pull the database/files. I wanted to pull from the "tony" multidev but the GUI only gave the option for "Development Environment" (I'm not sure if this refers to the environment for the master branch or the branch I have checked out in the code). If I use `kbox pull` from the CLI, I get different options. In this case, the options available are "tony" which is the branch I have checked out, "test" and "live" (which aren't set up yet). Is this the intended behavior? If so, why are they different?

If I add a new site to Kalabox, specifying the dev branch in the GUI, how would I switch my local environment to mirror one of the multidev environments on Pantheon?

Example from GUI:

![image](https://cloud.githubusercontent.com/assets/756265/18640941/04afbbec-7e60-11e6-823c-0fd61888f45c.png)

Example from CLI:

![image](https://cloud.githubusercontent.com/assets/756265/18641568/d595184a-7e62-11e6-8227-51c861d3243b.png)

**Comment by pirog** [comment]
@amklose pretty sure this was fixed in RC3.

**Comment by amklose** [comment]
@pirog So sorry! I read #1587 but I wasn't sure if this was caused by the same issue. Also, didn't know RC3 was available yet. http://www.kalabox.io/download currently gives you RC2

**Comment by pirog** [comment]
no worries! 

likely our bad on the download page but latest should always be posted on github as well 
https://github.com/kalabox/kalabox/releases
