### ISSUE TITLE
Can Kalabox Pro be used without SSH access? (SSHFS available)

### ISSUE THREAD

**Issue by PaulHoza** [kalabox/kalabox#1599]
I hope this is the place to post this, but I can't figure out anything better to get an answer to this.

Regarding Kalabox Pro "import/export sites from any hosting provider" features, (given lack of details available on how it works):

I'm currently trying to get used to the limitations of using Rackspace Cloud Sites (https://www.rackspace.com/cloud/sites) for my production environment. This is a hosted solution (maybe a tad too expensive) but I've needed to remove hosting/server management from my plate, so I'm giving this managed solution a try.  I really don't want to manage VPS/VM/dedicated servers anymore...but I sure do miss 'em!

They don't offer SSH login access (yuck), but do have SSHFS support, FTP access, and access to the databases through PHPMyAdmin, with MySQL (MariaDB 10.1, specifically) db's created through their web UI, and maybe via API, but I don't know about that stuff.)

My question is whether I'd be able to utilize Kalabox Pro to link into this setup and maybe (hopefully) have a way to pull my sites off their service, work on them and then re-sync thing back.. somehow? It seems that the database side of this equation will likely be the biggest rump-pain overall.

I've tried running Drush on an SSHFS-linked path, but it doesn't work very well, given how horribly slow it is, but also due to it disconnecting and interrupting some stuff here/there (sorry, trying to be brief, so no more details on that.)  I didn't succeed in doing an SQL sync the couple times I tried, but I will test again soon.

Anyway, I hope this poorly-formed question will help me learn more about the Pro features to see if they might solve my problems.  Additionally, it might lead to better documentation/marketing regarding using Kalabox for setups like this -- if it will work.

Thanks!

**Comment by pirog** [comment]
@PaulHoza yes we anticipate Pro being able to do exactly what you describe. That said Pro is not currently available and we do not have a release date planned at this time.

**Comment by PaulHoza** [comment]
Thank you. I have been eager to learn more and lately have been teetering on pre-buying Pro. I realize it's unclear the final features of Pro, but thank you for that feedback.

**Comment by pirog** [comment]
@PaulHoza best thing you can probably do is get on the kalabox mailing list. that is the best way to get updates on what we are doing. 

kalabox.io
