### ISSUE TITLE
Improve PHP app documentation to include how to access your database credentials

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1600]
2.0.0 on macOS 10.11.6 
New install

First time running for over a year, so everything is new again :-). Congratulations on the launch of 2.0.0!

But I've run into a snag.

==Steps==
1. Choose Drupal-8 and a fresh install. Containers spin up fine.
2. Drupal install asks for database name, username and password. Don't know what to give it here so I try "root" and <blank>. Doesn't work.
3. Remember seeing in the docs there's a way to see the db connection info. Select that.
4. Spin up Sequel Pro and give it connection info for the container's mysql including the 32768 port. Connects to container mysql fine.
5. Notice that there is a database there already called drupal.
6. Go back to Drupal install and give it drupal, drupal and drupal for the db name, username and password. Leave localhost and 3306 for the port.

==Result==

Drupal reports:
Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.

== Recommended documentation change ==

In the PHP App section (http://php.kalabox.io/en/stable/users/gui) the current instructions seem very confused. The first heading talks about PHP Apps but then proceeds to show how to pull a database and no reference to the credentials to put in. I think this section needs a good look over with guidance for database credentials when spinning up a new site.

Does this bug prevent you from using Kalabox?
yes, will look for a workaround after submitting this;  but "kbox drush sql-create" has already failed and I'll write up that issue next.

**Comment by pirog** [comment]
@aangelinsf in the connection info that pops up in the GUI you will want to use the internal connection info. (ie you got everything right except the host is `database`)

**Comment by aangelinsf** [comment]
Thanks for the quick reply, Mike. That did the trick.

That's not in the docs:
http://php.kalabox.io/en/stable/users/gui

The CLI docs don't look to be up to date for PHP Apps. The pages talks only about pulling for Pantheon.

**Comment by pirog** [comment]
Updated the title to reflect what should be done here

**Comment by aangelinsf** [comment]
Actually, the whole page needs a re-write, I think.

**Comment by pirog** [comment]
Open to suggestions on other things but the only thing that seems potentially unclear to me is the database info.

**Comment by aangelinsf** [comment]
Perhaps we're saying that same thing.

**Comment by pirog** [comment]
@aangelinsf ive updated the php docs to provide more clarity on using the db connection info
