### ISSUE TITLE
All versions of OS X change to macOS

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1602]
Apple is changing the name of its OS so all forms throughout the docs should change (Mac OS X,  OSX or OS X all go to macOS).

**Comment by pirog** [comment]
This would be a **GREAT** pull request :)

**Comment by aangelinsf** [comment]
@pirog Looks like the build failed but for a reason unrelated to this PR. Looks like it's happened before.

Please advise if I need to do something.

**Comment by pirog** [comment]
Yeah there is something weird about PRs coming from a non-kalabox fork but
since this is docs its probably safe to merge. Will review shortly.
