### ISSUE TITLE
Permission denied on first install with PHP App created via the gui

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1605]
Kalabox 2.0.0 on Windows 7 with 8GB ram

Have you previously installed Kalabox? If so, what version?
No

== Steps == 
1. Install Kalabox. Spin up a new PHP App using the GUI.
2. Click on (broken) gif.

== Result ==
Browser launches and shows 403 Permission denied error.

== Similar to ==
#1538
#1583 <-- similar title but not the same problem

[Old comment wasn't relevant.]

Does this bug prevent you from using Kalabox?
Yes, and looking for a workaround. First time running it on native Windows.

**Comment by aangelinsf** [comment]
I was wrong...the issue I was thinking of  (#1402) dealt with a different permission error (the settings.php file).

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
