### ISSUE TITLE
Documentation missing for how to ssh into PHP app

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1606]
While attempting to examine the apache configuration file to see why the GUI install of D8 is failing on Windows, I thought I would ssh into the VM to look at the config files.

Where I've looked:
1. The issue queue. Found  #1534, which doesn't answer the question and #185, which no longer works.
2. Typed "ssh" into documentation search field and got no results.
3. Used "ssh site:kalabox.io" but didn't see anything.

There appears to be no place that documents how to ssh in so that I can examine the apache configuration files. (Not really knowing the setup of Kalabox yet, I'm not even sure where I will find apache, but I figured the VM was a good place to start.)

**Comment by pirog** [comment]
Kalabox uses docker containers for pretty much everything so the concept of
"sshing" is not really a thing. That said you can get instructions on
accessing the VM and underlying docker containers here
http://docs.kalabox.io/en/stable/troubleshooting/

**Comment by aangelinsf** [comment]
FYI, that page does not come up with either ssh or SSH plugged into the search field.

**Comment by aangelinsf** [comment]
Have to pick this up next week.

**Comment by pirog** [comment]
Sounds good. Thanks for helping!
