### ISSUE TITLE
Documentation search does not work

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1607]
== Steps ==
1. Go to http://docs.kalabox.io/en/stable/
2. Enter any search term

== Results ==
Search results page comes up but there are never any results no matter what is typed in.

**Comment by pirog** [comment]
Good to know. We are using readthedocs.org so im not sure what needs to
happen there for search to work.

**Comment by reynoldsalec** [comment]
Potential work around to fix this issue: https://github.com/rtfd/readthedocs.org/issues/1088

**Comment by reynoldsalec** [comment]
Updated all the app documentation with the search fix detailed in the referenced issue on rtfd, we can reopen this if necessary.
