### ISSUE TITLE
Installation on Windows fails with "Engine activation failed!" error code 4.

### ISSUE THREAD

**Issue by LordPachelbel** [kalabox/kalabox#1610]
I'm trying to install Kalabox 2.0 on Windows 10 and it always fails near the end of the process with an error message stating "Engine activation failed!" At that point I have to exit the installer.

This might be relevant: when I tried installing an alpha release a while back I ran into issue #1141 because I'm using Hyper-V, and so I gave up trying to install it then.

Anyway, here's an excerpt from the setup log:

`2016-09-22 14:57:19.236   -- File entry --`
`2016-09-22 14:57:19.237   Dest filename: C:\Program Files\Kalabox\engine.bat`
`2016-09-22 14:57:19.237   Time stamp of our file: 2016-09-19 20:42:02.000`
`2016-09-22 14:57:19.237   Installing the file.`
`2016-09-22 14:57:19.243   Successfully installed the file.`
`2016-09-22 14:57:25.959   Engine activation failed with code 4`
`2016-09-22 14:57:25.959   Message box (OK):`
`                          Engine activation failed!`
`2016-09-22 14:58:44.729   User chose OK.`
`2016-09-22 14:58:44.729   Message box (Yes/No):`
`                          Setup is not complete. If you exit now, the program will not be installed.`
`                          `
`                          You may run Setup again at another time to complete the installation.`
`                          `
`                          Exit Setup?`
`2016-09-22 14:58:50.467   User chose Yes.`
`2016-09-22 14:58:50.467   -- File entry --`
`2016-09-22 14:58:50.467   Dest filename: C:\Program Files\Kalabox\services.bat`
`2016-09-22 14:58:50.467   Time stamp of our file: 2016-09-19 20:42:02.000`
`2016-09-22 14:58:50.467   Installing the file.`
`2016-09-22 14:58:50.473   User canceled the installation process.`
`2016-09-22 14:58:50.473   Rolling back changes.`
`2016-09-22 14:58:50.477   Starting the uninstallation process.`

I've attached the setup log. The error occurs on line 43899.
[Setup Log 2016-09-22 #001.txt](https://github.com/kalabox/kalabox/files/488291/Setup.Log.2016-09-22.001.txt)

**Comment by pirog** [comment]
Might be worth uninstalling and attempting to reinstall. Have you checked
out the docs re: troubleshooting? specifically the dup host only adapater?
http://docs.kalabox.io/en/stable/troubleshooting/

**Comment by LordPachelbel** [comment]
There was only one host adapter in VirtualBox but no virtual machines, so I removed the adapter. That didn't work.

Uninstalling/reinstalling everything  — not just Kalabox but VirtualBox, too — did not work, either.

I tried clicking Cancel when the installer asked if I wanted to exit, and that resulted in a couple more error messages that I also had to Cancel out of, but the installer finally ran to "completion," to use that term loosely. After that, Kalabox was not listed in VirtualBox and there was no .kalabox in my user directory, so I can't work around the problem by forcing the installer to finish.

**Comment by nickeblewis** [comment]
We've had the same issue here in our office, one Windows 10 machines installs it fine and it does have Hyper-V installed and active. However on my colleagues machine, also Win 10, he hits the same problem that you have had.

**Comment by RudyMartin** [comment]
Same problem here using Windows 8!

**Comment by jsibley2** [comment]
I wasn't sure whether to comment here or create a new thread.

I don't have hyper-v activated, am running Windows 10 professional anniversary edition, and was able to install without any problems. I ran the installer, then installed a Pantheon app using the GUI.

So far, things seem to be working. I have a question about the network connections that I'll ask in a new thread.

**Comment by nickeblewis** [comment]
Interesting to say that my Anniversary Edition of Windows 10 Pro does work. However on the other laptop we have it wouldn't install. That machine is also Windows 10 Pro and they both have Hyper-V enabled. Only one of them is the anniversary edition though?
Could that have a bearing on things?





On Sat, Sep 24, 2016 at 7:59 PM +0100, "jsibley2" <notifications@github.com> wrote:












I wasn't sure whether to comment here or create a new thread.



I don't have hyper-v activated, am running Windows 10 professional anniversary edition, and was able to install without any problems. I ran the installer, then installed a Pantheon app using the GUI.



So far, things seem to be working. I have a question about the network connections that I'll ask in a new thread.

**Comment by idpokute** [comment]
I have same problem..Did anyone solve this issue?

**Comment by pirog** [comment]
So for anyone having this issue here are the things you need to do to get more info on the underlying cause.


####  1. Verify that you are actually getting `Engine activation failed with code 4` 

Your setup log should be in `%TMP%`
https://github.com/kalabox/kalabox/issues/1610#issue-178713225

#### 2. Verify that do not have a duplicate host adapter
http://docs.kalabox.io/en/stable/troubleshooting/#resolving-duplicate-host-only-adapters

#### 3. Verify that you have `VT-x` enabled
http://docs.kalabox.io/en/stable/general/sysreq/#system-requirements

### 4. Run through the installer until it fails.

Run the installer through to the end. Don't choose to rollback if given that option. You can uninstall the borked install later.

### 5. Try to manually run the `engine.bat` init script

You should now have `engine.bat` file somewhere in `"C:\Program Files\Kalabox\engine.bat"` Verify that is true and note that you may have a different sysDrive like `D:\`. It is also possible that `engine.bat` is in a subdirectory. Anyway, please copy the path location. 

Open `cmd.exe`, **DO NOT OPEN AS AN ADMINISTRATOR** and try to run the script manually.

```batch
"C:\Program Files\Kalabox\engine.bat"
```

At some point this should fail and give some better details about the underlying issue. Please post that here!

**Comment by hugovk** [comment]
@pirog I've followed those steps (Kalabox 2.0.0, Windows 7) and step 5 gives:
```
C:\Program Files\Kalabox\bin\docker-machine.exe
C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
"Kalabox2" {f6e32342-c08b-4861-9a50-a64eb04be850}
Starting "Kalabox2"...
(Kalabox2) Check network to re-create if needed...
Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm Kalabox2 --type headless failed:
VBoxManage.exe: error: The virtual machine 'Kalabox2' has terminated unexpectedly during startup with exit code 1 (0x1).
  More details may be available in 'C:\Users\hugovk\.docker\machine\machines\Kalabox2\Kalabox2\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
OS type not recognized
```

**Comment by pirog** [comment]
Have you checked out this other log file the error mentioned?

**Comment by hugovk** [comment]
@pirog I've added it to my previous message.

**Comment by pirog** [comment]
@hugovk, sorry i should have been more clear. Did you actually read through the output you posted? 

Specifically 
`More details may be available in 'C:\Users\hugovk\.docker\machine\machines\Kalabox2\Kalabox2\Logs\VBoxHardening.log' 

Have you looked in **THAT** log file at all?

Just for a little background: We use `docker-machine` to install the needed VM for Kalabox to run and the output you are seeing above is being generated by that project. So it might be worthwhile googling some of the above error output in that context eg `OS type not recognized docker machine`.

**Comment by LordPachelbel** [comment]
@nickeblewis My computer has the Anniversary Update and Kalabox won't install.

@pirog Here's Docker's output:
```
C:\Program Files\Kalabox\bin\docker-machine.exe
C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
About to remove Kalabox2
Error removing host "Kalabox2": Host does not exist: "Kalabox2"
Can't remove "Kalabox2"
The system cannot find the path specified.
Running pre-create checks...
Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
Host does not exist: "Kalabox2"
Host does not exist: "Kalabox2"
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Host does not exist: "Kalabox2"
Host does not exist: "Kalabox2"
```
There's a workaround I'm going to try (when I have a chance — it requires rebooting the machine): https://derekgusoff.wordpress.com/2012/09/05/run-hyper-v-and-virtualbox-on-the-same-machine/

**Comment by hugovk** [comment]
@pirog I've added that log to the previous message. First error: 
`Error opening VBoxDrvStub:  STATUS_OBJECT_NAME_NOT_FOUND`

**Comment by pirog** [comment]
@LordPachelbel definitely will add the docs you recommended over at #1628. Kind of crappy that people are going to run into this and i dont think there is much we can do about it.

Good news is that once Docker for Windows gets more mature we can ditch VB for Hyper-V.

**Comment by pirog** [comment]
I've documented the stuff in this issue.
