### ISSUE TITLE
WordPress redirects (e.g. /wp-admin) are getting port 8888 added to url

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1612]
How to replicate:

1. Install a new WordPress site with Kalabox. 
2. Log out.
3. Visit `http://yoursite.kbox/wp-admin`

You'll be redirected to `http://yoursite.kbox:8888/wp-admin/` <-- note trailing slash. This is of course not reachable.

This might be internal to WP (I believe it naively handles `$_SERVER['SERVER_PORT']` in some cases) or could be part of the nginx config. Needs a little looking.

**Comment by joshkoenig** [comment]
The redirect that contains port `8888` doesn't have the "Powered by PHP" header, so I suspect this is nginx config.

Redirect from /wp-admin to /wp-admin/:

```
HTTP/1.1 301 Moved Permanently
server: nginx
date: Fri, 23 Sep 2016 16:26:08 GMT
content-type: text/html
content-length: 178
location: http://reluctantly-with-her.kbox:8888/wp-admin/
connection: close
x-pantheon-endpoint: kalabox
```

Redirect from /wp-admin/ to /wp-login.php:

```
cache-control:no-cache, must-revalidate, max-age=0
connection:close
content-type:text/html; charset=UTF-8
date:Fri, 23 Sep 2016 16:26:27 GMT
expires:Wed, 11 Jan 1984 05:00:00 GMT
location:http://reluctantly-with-her.kbox/wp-login.php?redirect_to=http%3A%2F%2Freluctantly-with-her.kbox%2Fwp-admin%2F&reauth=1
server:nginx
transfer-encoding:chunked
x-pantheon-endpoint:kalabox
x-powered-by:PHP/5.6.25
```

**Comment by kurtschlatzer** [comment]
Found this little snippet on StackOverflow:

> If you are using WordPress there should be 2 URLS in the database you have to change, there's a "siteurl" column and a "home" column that both need to be without the :8888

**Comment by pirog** [comment]
@joshkoenig @kurtschlatzer ok yeah i can definitely replicate this. Strange this hasn't been reported yet.

Is this what you all are getting?
`http://kalabox-wordpress.kbox/wp-admin/` -> `http://kalabox-wordpress.kbox/wp-login.php`
`http://kalabox-wordpress.kbox/wp-admin` -> `http://kalabox-wordpress.kbox:8888/http://kalabox-wordpress.kbox:8888/wp-admin/`

**Comment by pirog** [comment]
ok so looks like the issue here is we aren't using `port_in_redirect off;` in our `nginx.conf` for WordPress. 

You can temporarily workaround this by editing the `wordpress.conf` in your apps `config/nginx` directory so that the `server` block contains `port_in_redirect off;` eg

```bash
server {
  listen 8888 default_server;
  listen 444 ssl;

  server_name appserver;

  ssl_certificate           /certs/appserver.crt;
  ssl_certificate_key       /certs/appserver.key;
  ssl_verify_client         off;

  root /code;
  index index.html index.htm index.php;

  client_max_body_size 100M;
  port_in_redirect off;
...
```

@joshkoenig @ataylorme, do you guys know whether `port_in_redirect off;` should be in the `nginx.conf` for all the frameworks or just WordPress?

**Comment by pirog** [comment]
Looks like you guys do so NM!
