### ISSUE TITLE
Older apps can sometimes cause the GUI loading screen to hang indefinitely. 

### ISSUE THREAD

**Issue by Senpai** [kalabox/kalabox#1613]
# Bug Report

Environment: Mac Kalabox 2.0.0, upgraded from a fresh rc-2 install.

**Expected Results:** When I start up the Kalabox GUI, I expect to be presented with the "home screen" showing me my list of apps. 

**Actual Results:** The Kalabox GUI is endlessly stuck at the "Starting The Kalabox Engine" screen, cycling through all the slogans and catchphrases. (been looping like this for an hour now)

**Additional Details:** This bug does not prevent me from using Kalabox, because the command line is reporting as v2.0.0, Virtualbox is up and running just fine, browsing a site locally works, and I can perform any kbox operation via command line. Also, I just threw away the Kalabox.app v2.0.0 and performed a reinstall just to see if that was the problem, but the bug still exists.

I can't be sure this wasn't happening pre rc-2, though, cause it's been a little while since I've fired up the GUI. :) I wanted to show it off to some co-workers in the hopes that they'll adopt it.

Is there an error log specifically for the GIU that I could look at?

**Comment by Senpai** [comment]
Turns out I had an old hand-rolled app in there from "version": "0.13.0-alpha.1" when I was playing around with creating my own custom apps. Destroyed it, and kalabox.app starts up in like 2.59 seconds!

Who knew that an older, super simple webserver-only app could choke the GUI's startup!? Well, there ya go. We're back in business now!

Side thought: Do you think this might become a problem in the future after 2.1, 2.2, etc? I mean, the GUI should not fail to start up just because there's an older, unactivated app sitting around, right? Should we consider this a bug?

**Comment by pirog** [comment]
@Senpai yeah i think we should consider this a bug. 

I know that now that we are 2.0+ we are going to try to preserve backwards compatibility with the apps as much as possible. That said we should def inform the user that they need to recreate/update their legacy apps if breaking changes do occur instead of INFINITE GUI LOAD SCREEN.

**Comment by ehausen** [comment]
Getting this for the now brand new Kalabox 2.1.0
Used the 2.1.0 uninstaller. It removed kalabox but failed to uninstall docker for mac
Tried to run Uninstaller from kalabox-v0.13.0-beta.4.dmg, but it said that there is nothing to uninstall.

How can I  purge or clean stuff further to get Kalabox GUI running?

**Comment by ehausen** [comment]
Tried starting Docker (mac application). It said _BlueStacks_ app was causing problems. I uninstalled BlueStacks and restarted my machine. 

Still nothing when trying to run Kalabox GUI.

Tried starting Docker manually, then running Kalabox GUI. **This worked!**

**Comment by pirog** [comment]
@ehausen recommend you check out the docs for some more help on uninstall/install if you are running into issues.

**Comment by ic-ewoods** [comment]
I encountered this after setting up https://github.com/kalabox/kalabox-app-examples. The example app ran fine if I did `kbox start` in the dir (I could view the nginx start screen in a browser). Starting the Kalabox GUI would hang after that. 

I tried just stopping the example app. I tried a few shot-in-the-dark edits to kalabox.yml settings on `type` and `version` but had no success. Only thing that brought the GUI back was running `kbox destroy` in the app examples directory.

I was hoping to be able to simply cobble together another app that wasn't Drupal-based. It looks like I can if all I use is the CLI. But I had to learn through trial and error that the GUI not working was not actually an indication of a broader problem for Kalabox.

This was with Kalabox 2.1.3 on Docker 1.13 on macOS Sierra 10.12.3.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
