### ISSUE TITLE
Kalabox installer showing token string instead of version string

### ISSUE THREAD

**Issue by ccharlton** [kalabox/kalabox#1614]
macOS X version: 10.11.6
Kalabox installer version: 2.0

The 2.0 installer is displaying the version token (`%KBOX_VERSION%`) instead of the actual version string.

**Comment by pirog** [comment]
Where do you see this?

**Comment by ccharlton** [comment]
Steps:

1. Launch 2.0 installer.
1. Click "Continue", "Customize" -- version token appears there.

**Comment by pirog** [comment]
I assume this is not a blocking issue?

**Comment by ccharlton** [comment]
This is not blocking. I've posted a screenshot above for reference.

**Comment by pirog** [comment]
@ccharlton ok yeah i can def replicate this. Looks like somewhere along the way `%KBOX_VERSION %`was changed to `%KALABOX_VERSION%`.
