### ISSUE TITLE
Pushing code to Pantheon broken when git perms are borked

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#1615]
Trying to push code to Pantheon from a local environment and I'm not seeing my changes show up in the Pantheon dashboard. There are no errors in the Kalabox UI or in the log file that I can see.

**Comment by joshkoenig** [comment]
Here's the output from `kbox`:

```
joshk@steppinrazor outlandish-josh$ kbox push
? Tell us about your changes Going back to PHP 5.6 because 7.0 is too new
? Push database to which environment? Do not push the database
? Push files to which environment? Do not push the files
[2016-09-23 18:36:30] [info] Added SSH key from file /home/1000/keys/pantheon.kalabox.id_rsa.pub.
    file: '/home/1000/keys/pantheon.kalabox.id_rsa.pub'
Pushing code.
fatal: could not open '.git/COMMIT_EDITMSG': Permission denied
Warning: Permanently added '[codeserver.dev.3ecd4d40-bdf2-4e52-a519-7e697ecdfe20.drush.in]:2222,[23.253.221.225]:2222' (RSA) to the list of known hosts.
error: update_ref failed for ref 'refs/remotes/origin/master': Cannot update the ref 'refs/remotes/origin/master': unable to append to .git/logs/refs/remotes/origin/master: Permission denied
Everything up-to-date
```

**Comment by pirog** [comment]
Oh weird. Not clear why the permissions would be wonky here and our latest push tests are showing up in their respective pantheon dashboards.

We do map HOST perms to CONTAINER perms but generally this is pretty reliable. I think there are a few other issues open dealing with this mapping.

**Comment by joshkoenig** [comment]
Aha! So, here's an additional bit of information. I had made a commit in git and pushed to master by hand previously. I assumed this would "just work", but perhaps that screws up the permissions?

**Comment by pirog** [comment]
Hmmm i think it should "just work" but its certainly possible that this messes with the perms.

On the run today but i'll def try to replicate this later.

**Comment by joshkoenig** [comment]
Word. Definitely seems like there was a permissions problem. Tried deleting the site and it didn't remove the files in `~/.kalabox/apps`. Got this error in the "Alerts" notification box when trying to resync:

```

 Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.12/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E 
 VError: Error while removing dir: /Users/joshk/.kalabox/apps/outlandish-josh: Error changing permissions: dir=/Users/joshk/.kalabox/apps/outlandish-josh mode=700: ENOENT: no such file or directory, stat '/Users/joshk/.kalabox/apps/outlandish-josh/code/files' 
 Error: Looks like an app already exists at /Users/joshk/.kalabox/apps/outlandish-josh 
```

FWIW it was impossible to read that. Had to copy/paste into a text editor.

I'll see if I can replicate it now though.

**Comment by pirog** [comment]
@joshkoenig definitely let me know if you can replicate this!

**Comment by johnslay** [comment]
@joshkoenig I'm having the same issue. I just heard about Kalabox and downloaded it today and transferred a site we had on Pantheon over to local.

```
Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.12/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E 
```

I want to say everything was working fine until I went and changed some CSS and then I got the alert with that error above.

**Comment by pirog** [comment]
@johnslay can you detail the changes you made and what steps you seems to take before this happened?

**Comment by amklose** [comment]
@joshkoenig Did you by any chance change the `pluginconfig.pantheon.env` variable in kalabox.yml from what it was initially when you first pulled down the site?

I pulled the dev environment using the Kalabox GUI. Then I decided that I wanted to work in a multidev but `kbox pull` and `push` only listed the dev environment, test and live. I changed `pluginconfig.pantheon.env` in kalabox.yml to the multidev. Then the options for `kbox pull` and `push` listed that multidev, test and live.

I was able to pull and push the database and files to the multidev using the kbox command, but I kept getting that same error when it pushed the code:
```fatal: could not open '.git/COMMIT_EDITMSG': Permission denied```

When I switch it to point back to 'dev', I no longer get the error.

**Comment by joshkoenig** [comment]
I didn't fiddle that intentionally. But it's an interesting data-point.

**Comment by pirog** [comment]
oh very interesting @amklose! That definitely gives us something to work with.

Still not exactly clear how @joshkoenig arrived at this error but maybe that will become more clear after we play around a bit.

**Comment by pirog** [comment]
So i inadvertently ran into what i am guessing is the same root issue here while looking into something else. I think what is happening here at least for @joshkoenig (havent looked at how this relates to @amklose's report yet) is the something like the following

```bash
cd /path/to/app

# downloads project and shares it into the container
# however it ends up in the container as root
composer require someproject
```

So im guessing @joshkoenig is doing something like

```
git add .
# adds the git message put effectively "locks" all git operations used via `kbox` ie `kbox push`
git commit -m "whatever" 
```

I think there are a couple of things we can do here to mitigate this. 

1. Try to periodically correct mission critical permissions where appropriate
2. Offer some other kbox related entrypoint so users can fix their permissions eg `kbox . sudo chown -Rv code/.git`

**Comment by pirog** [comment]
Ok so replicating this is fairly straightforward although i didnt get a legit fatal error, just the print out about `fatal: could not open '.git/COMMIT_EDITMSG': Permission denied` and then a continuation and completion of the push as expected. That said here are the steps

```bash
# Create a site
kbox create pantheon -- --name=mysite

# CD into the code directory and add a file
cd mysite/code
touch something

# Add the file to git without `kbox git` and then try `kbox push
git add .
git commit
kbox push -- -d
```

```

**Comment by pirog** [comment]
OK so we've added some checks to make sure perms are good if you are alternating between `git` and `kbox git`.

@amklose, i looked into your use case a bit and for now i think it makes the most sense to not support changing the `env` in your apps `kalabox.yml`. There are just too many scenarios and edge cases to handle. If you don't want to follow the normal workflow ie pulling a kalabox env for each pantheon multidev that is totally reasonable but i think in those circumstances it makes the most sense for the user to handle the management of their git repo vs expecting kalabox to handle it.

**Comment by joshkoenig** [comment]
Awesome! You rock @pirog - that's exactly what I did. Just did the normal `git push`.
