### ISSUE TITLE
Network connections in Windows 10 Professional using v2.0

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1618]
After installing 2.0, I notice that I have 2 host connections - #4 and #5. Virtual box says that it is using adapter 1 (NAT) and that adapter 2 is using adapter #5

![image](https://cloud.githubusercontent.com/assets/6576953/18810601/9bdfdf72-8268-11e6-9d06-8597db1158a0.png)

If I look under settings in Virtualbox, it doesn't show a NAT adapter:

![image](https://cloud.githubusercontent.com/assets/6576953/18810607/d4f084f6-8268-11e6-9fab-2a48df40dd1a.png)

FWIW, here is what shows up in ipconfig /all for #4:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter #4
   Physical Address. . . . . . . . . : 0A-00-27-00-00-26
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::4598:76d1:1326:6b1d%38(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 638189607
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-65-76-5B-E8-B1-FC-F2-A7-3D
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Everything seems to be working so far, but I wondered whether I should disable my host connection #4 and was curious about the NAT setup.

**Comment by pirog** [comment]
I think it's best to leave things as they are esp if you are not
experiencing any issues.

**Comment by jsibley2** [comment]
I closed my laptop while my kalabox app was still open and when opened it up again, I couldn't access the internet due to DNS issues. This is under WIndows 10 Professional Anniversary Edition.

I tried ipconfig release, renew, flushdns and even that didn't work. I disabled my VirtualBox Host-Only Network #4 and that seemed to do the trick.

In case you can see something, here are the results of ipconfig /all when things weren't working:

Windows IP Configuration

   Host Name . . . . . . . . . . . . : Jonathans-pc
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter VirtualBox Host-Only Network #4:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter #4
   Physical Address. . . . . . . . . : 0A-00-27-00-00-26
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::4598:76d1:1326:6b1d%38(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 638189607
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-65-76-5B-E8-B1-FC-F2-A7-3D
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Hosted Network Virtual Adapter
   Physical Address. . . . . . . . . : EA-B1-FC-F2-A7-3D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : E8-B1-FC-F2-A7-3E
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wireless-N 7260
   Physical Address. . . . . . . . . : E8-B1-FC-F2-A7-3D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::d0cf:5c5:5405:3d5%21(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.132(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Sunday, September 25, 2016 9:44:31 AM
   Lease Expires . . . . . . . . . . : Monday, September 26, 2016 9:44:31 AM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 65581564
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-65-76-5B-E8-B1-FC-F2-A7-3D
   DNS Servers . . . . . . . . . . . : 192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{D25FBB7A-2FE4-42E0-B028-CE52D623999C}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{A6D670C0-475C-4E77-8520-751115A42128}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #3
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter isatap.{1F9A7951-2E60-4A35-B5A7-1F9902335654}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter #4
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter VirtualBox Host-Only Network #5:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter #5
   Physical Address. . . . . . . . . : 0A-00-27-00-00-2E
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::edb4:fa4e:cb7e:f1c4%46(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.13.37.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 772407335
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1D-65-76-5B-E8-B1-FC-F2-A7-3D
   DNS Servers . . . . . . . . . . . : 10.13.37.100
   NetBIOS over Tcpip. . . . . . . . : Enabled

**Comment by pirog** [comment]
VB adapter #4 is not used as part of Kalabox.

**Comment by pirog** [comment]
@jsibley2 do you know if your #4 VB Adapter was from a previous install and was something you had messed around with? These adapters can persist between uninstalls of virtualbox. 

So, Kalabox is going to install and configure the VB HOA adapter that exist at 10.13.37.1 and has a DNS server at 10.13.37.100. The other VB adapter is usually installed by default when you install VirtualBox. I would def recommend trolling through the VB queues to see if this is a bug on their end.

**Comment by jsibley2** [comment]
Just to check, I uninstalled Kalabox and Virtualbox, removed .kalabox and .virtualbox, and reinstalled.

After uninstalling everything, #4 and #5 HOA were gone.

After reinstallation (which worked smoothly again, thank you), both #4 and #5 were back. So, it would appear to be something leftover that I missed (e.g., windows registry) or something in the Kalabox / Virtualbox installation that is adding #4 in addition to #5.

**Comment by pirog** [comment]
@jsibley2 as noted previously: VirtualBox will install this #4 adapter by default. We will install adapter #5. This is the expected behavior. If you are having networking problems because of adapter #4 i would recommend you post an issue to virtualbox, not kalabox.

**Comment by jsibley2** [comment]
If the expected behavior is that Virtualbox will install adapter #4 and if that adapter, while enabled, can interfere with DNS lookups, I think it would be helpful to add to the documentation that this can / will happen - particularly if Kalabox always reinstalls Virtualbox during installation. I believe the documentation warns against unnecessary adapters, but I don't think it makes clear that one should expect this as a by-product of a normal installation.

Of course, if there is a way to avoid having the other adapter created during installation, that would seem to be even better.

**Comment by pirog** [comment]
This adapter should not interfere with DNS unless you've modified it to do
so.

Kalabox will only install VirtualBox if it needs to or there is an update.

I'm happy to document this but I want to see if other people are having
this issue besides you. I also don't want to document something that I'm
pretty sure is not true. Happy to be wrong there but I need to see
compelling steps on how to replicate this.

I also don't think it's particularly wise to remove VBs default
configuration, potentially breaking other VMs and networking that users
have.

**Comment by pirog** [comment]
For those using Win10 Pro+ with HyperV i would check out our experimental release and see if that helps 
https://github.com/kalabox/kalabox/releases/tag/v2.1.0-rc.1
