### ISSUE TITLE
Windows 7 and/or 8+ support?

### ISSUE THREAD

**Issue by arlinsandbulte** [kalabox/kalabox#1619]
The download link on the homepage says "Windows 8+"
System requirements in docs says "Windows 7" (at http://docs.kalabox.io/en/stable/general/sysreq/)

Which is it?

**Comment by pirog** [comment]
Should work on Windows 7 but probably won't be a great experience.

**Comment by pirog** [comment]
@arlinsandbulte i've updated kalabox.io to match the sys reqs in the docs ie Windows 7+. Should show up on our next deploy of kalabox.io.
