### ISSUE TITLE
CiviCRM (and potentially other things) needs `mysql` php extension. 

### ISSUE THREAD

**Issue by chrisdbarnett** [kalabox/kalabox#1620]
Bug Report
==========

**Tell us about your setup**
AMD Phenom (Octa Core) based desktop PC with 32GB RAM. 

What is your Kalabox version and operating system?
_2.0.0 on Windows 10 Professional_

Have you previously installed Kalabox? If so, what version?
_No_

1. Installed Kalabox
2. Started GUI
3. Added Panetheon account.
4. Clicked on Panetheon account and selected site, kicked off site pull from panetheon
5. Site is shown as ready. 
6. When visiting website in browser the following error message
![pantheon-error](https://cloud.githubusercontent.com/assets/150860/18811626/585ee86a-82ae-11e6-9712-c14f3b734f69.jpg)

The mysql error was: Unable to use the MySQL database because the MySQL extension for PHP is not installed. Check your <code>php.ini</code> to see how you can enable it..

8. 

Notifications in GUI shows a load of error messages,  
Please  see attached file : [notifications-errors.txt](https://github.com/kalabox/kalabox/files/491373/notifications-errors.txt)

Though these don't persist when the app is restarted so I guess they are related to the build / pull.

9.  

I'm pretty sure the php log suggested that it could not load mysql.so - but for some strange reason either the php error log file is now missing or I can't find it! 

Help! Thanks.

P.S. My apologies re labels - is there some kind of syntax to adding them?

**Comment by pirog** [comment]
@chrisdbarnett, weird. I'm pretty sure that extension should be installed. Assuming it must be since it works after you restart? 

I def have a few working drupal6 sites so i'd be interested in knowing what is different about yours. If you are comfortable (and able) adding me to that pantheon project i can def see if i can replicate this.

**Comment by chrisdbarnett** [comment]
@pirog - I'm afraid I can't - well not without some kind of NDA or some such legal paperwork changing hands to protect my sweet backside! 

What is quite frustrating is that it's not writing any PHP error log when it used to. Even if uninstall Kalabox, deleting the .kalabox directory and reinstall - there is no php error log and it's driving me potty. To be honest, there's nothing in the logs directory at all.

Is any of this related to issue #1608 ?

Also, I've asked Pantheon to have a look from the angle of #1608 

Some stats - the site has a DB of 250MB and the files amount to 4.7 GB - and yes, I've tried an initial pull without those files, but it didn't get me anywhere.

If I was to completely uninstall, what further steps can I take to clean up? Is deleting the .kalax directory and uninstalling Oracle Virtualbox enough?

Many Thanks, Chris.

**Comment by pirog** [comment]
@chrisdbarnett yeah no worries! as someone who also co-founded a drupal shop i know ALL about covering the ass. 

Where are you looking for the php logs? You might want to scan the troubleshooting docs if you havent already. Good tips on where to look around for stuff.
http://docs.kalabox.io/en/stable/troubleshooting/

Highly doubtful this is #1608. That issue is caused by the `framework` not being set on the Pantheon end and should pop up as an error almost immediately. 

Uninstalling might help but my suspicion is that this problem is the config of this particular drupal 6 site (and us not accounting for that use case yet) and not a wider problem with the kalabox install itself.  

Just to clarify... After you pull the site down and do a restart you are able to actually see the site correctly or did i misread that?

**Comment by chrisdbarnett** [comment]
@pirog Sadly, no - restarting doesn't help. I am familiar with docker so I have no problem poking around running containers and what not. 

Just to repeat, I did definitely see at some point an error message in the php logs saying that php couldn't load the mysql.so module.

Annoyingly, since I re-pulled the site - I can't get php logs for some reason.

How does php load the MySQL extension in the world of Kalabox?

Thanks.

**Comment by pirog** [comment]
@chrisdbarnett good to know re: docker. 

The source for the docker images for the pantheon appservers is over here
https://github.com/kalabox/kalabox-app-pantheon/tree/v2.0/app/dockerfiles/pantheon-appserver

is there any chance that you somehow switched or are overriding the default pantheon implementation re: db settings? ie mysql vs mysqli/pdo_mysql?

**Comment by chrisdbarnett** [comment]
Nope.

Things that could be different.

We are using CiviCRM
InnoDB is employed on most tables.
We are using Redis

I know this slapped onto the end of our settings.php

# $conf['pressflow_smart_start'] = TRUE;
$conf['cache_inc'] = 'sites/all/modules/cache_backport/cache.inc';
if (defined('PANTHEON_ENVIRONMENT')) {
  // Use Redis for caching.
  $conf['redis_client_interface'] = 'PhpRedis';
  $conf['cache_backends'][] = 'sites/all/modules/redis/redis.autoload.inc';
  $conf['cache_default_class'] = 'Redis_Cache';
  $conf['cache_prefix'] = array('default' => 'pantheon-redis');
  // Do not use Redis for cache_form (no performance difference).
  $conf['cache_class_cache_form'] = 'DrupalDatabaseCache';
  // Use Redis for Drupal locks (semaphore).
  $conf['lock_inc'] = 'sites/all/modules/redis/redis.lock.inc';

Thanks!

**Comment by pirog** [comment]
@chrisdbarnett it's possible the error you are getting is from CiviCRM (not drupal) which might need a different mysql PHP extension then the rest of Drupal. 

Best way to check that would be to cross references our mysql extensions with what pantheon is loading. Definitely down to add another one if that is the issue. 

We should support INNODB and REDIS out of the box so dont think that is the issue.

**Comment by chrisdbarnett** [comment]
@pirog - If you're right and if I was a betting man, I'd bet on you being right! ... it looks like my civicrm.settings.php would need to be updated with the correct settings.

That should not be a problem, but first, I think it's safest that I remove civicrm completely then see if that has an effect. 

I Will get back to you. Your help is much appreciated.

**Comment by pirog** [comment]
@chrisdbarnett ditto! We can't make it better without awesome feedback like this. 

It definitely looks like Pantheon uses both the `mysql and mysqli` extensions and Kalabox is only using `mysqli` so regardless of your findings we should sync those extensions up.

**Comment by chrisdbarnett** [comment]
Right. Well, CiviCRM is deffo using mysql but they have plans to migrate to mysqli

You would be saving me an awful amount of bother if you could run with mysqli as well - because upgrading CiviCRM isn't a 5-minute job - besides - I will want to simulate such an upgrade using Kalabox in the first place!

If I crudely removed all the civicrm modules, it didn't help it completely broke. 

I'll sleep on it! 

Thanks.

**Comment by pirog** [comment]
@chrisdbarnett i assume you mean run with `mysql` since we already run with `mysqli`? I think we should definitely support `mysql` if Pantheon does as well (which they do).

As someone who has both contributed to CiviCRM and wrote some of the initial code for the CiviCRM Pantheon integration i def understand the soul crushing experience which is a CiviCRM upgrade. 

I'm going to tentatively move this into our next sprint pending the results of your sleep-quest.

**Comment by chrisdbarnett** [comment]
@pirog 
If I remove CRM it doesn't get me anywhere. Is there some script that I can patch somewhere that will just install the mysql extension? Or is it as case of making my own version of one of your docker images AND changing a script to point to it?

I feel like a kid a Christmas with a really cool new toy ... and no batteries! 

Thanks.

**Comment by pirog** [comment]
@chrisdbarnett hmmm that is extremely weird then. That said, you can install the `mysql` extension in the normal docker way. Here are the instructions to get to a prompt where you can run docker commands
http://docs.kalabox.io/en/stable/general/engine/#engine-for-osxwin

My guess is you will want to do something like this once you are inside the VM to enable to mysql extension. Make sure the app is on first of course.

```bash
docker exec -i -t appname_appserver_1 bash
docker-php-ext-install mysql
```

**Comment by pirog** [comment]
@chrisdbarnett i opened a PR for this. 
https://github.com/kalabox/kalabox-app-pantheon/pull/172

Looks like `mysql` is deprecated in php 7

**Comment by pirog** [comment]
@chrisdbarnett another thing that could be the issue here is you have some code that is directly accessing the `mysql` extension instead of going through the preferred drupal version. 

IE `mysql_db_query` instead of `db_query`

**Comment by chrisdbarnett** [comment]
@pirog 
Thanks. I've installed the mysql extension is installed on the docker app container but the site is still being pulled from Pantheon ... and it's over 6GB. As fast as my connection is ... the throughput isn't that fast so it's going to be a few hours before I can see if the job is done.

Of course I'll simply switch the app off and on again to ensure PHP is all nicely reloaded.

Cheers.

**Comment by pirog** [comment]
@chrisdbarnett sounds good. I am going to merge the `mysql` extension stuff in anyway since we should be doing this. 

re: Hyper-V, we are going to switch over to the new Docker for Windows/Mac stuff as soon as their "native" file sharing is faster than NFS. Knowing a bit about the complexity of file sharing I honestly don't anticipate this being very soon.

We are upgrading our docker deps pretty regularly though.

**Comment by chrisdbarnett** [comment]
@pirog 
I'm pulling the site down from pantheon to local.

As I said, it's going to take some time. 

One thing I want to clear up.

sites/default/civicrm.settings.php - I will need to go in there and manually change the settings for the database? 

That being the case, what goes on with the normal settings.php for Drupal? Is that somehow overridden by Kalabox?

Sorry if all of this is real basic stuff- but as I far as I'm concerned, I set it all up ages ago and it's not like I've been working on loads of different Drupal websites over the last few years! 

Cheers.

**Comment by pirog** [comment]
@chrisdbarnett you shouldn't need to change any settings. Kalabox should handle your database settings (including civicrm settings) the same way Pantheon does ie automatically. 

You just need to install the correct extension.

**Comment by chrisdbarnett** [comment]
@pirog 

You might have a quick fix for this:

Error: Could not create directory: /srv/bindings/kalabox/files.
If you have moved an existing CiviCRM installation from one location or server to another there are several steps you will need to follow. They are detailed on this CiviCRM wiki page - http://wiki.civicrm.org/confluence/display/CRMDOC/Moving+an+Existing+Installation+to+a+New+Server+or+Location. A fix for the specific problem that caused this error message to be displayed is to set the value of the config_backend column in the civicrm_domain table to NULL. However we strongly recommend that you review and follow all the steps in that document.

**Comment by chrisdbarnett** [comment]
@pirog 
Good news is that now if I remove CiviCRM at least Drupal is working ... but with one error so far 👍

**Comment by chrisdbarnett** [comment]
@pirog 
Update - it's not letting me update the location of the files witihn Drupal - no matter what I enter it will always default back to  site/default/files

I've cheated by just copying files to there for now....but it will get messy! 

I need to know what it *really* should be updated to and how to get it to register the change. 

Other config pages are holding their changes, such as Site Information.

Thanks!

Chris.

**Comment by pirog** [comment]
Pantheon (and by extension our integration with pantheon) assumes your files should be in `sites/default/files` for a Drupal 6/7 site. 

This should all be set up for you when you pull down a site from Pantheon.  Behind the scenes we symlink this to `/media` in each container and `files` in your local app directory. This is also how pantheon works.

**Comment by chrisdbarnett** [comment]
@pirog 
Hold on! Without doing anything at all - just pulling my site down from Pantheon - I got the errors above that I told you about in this comment - https://github.com/kalabox/kalabox/issues/1620#issuecomment-249717930

I then visited mysite.kbox/admin/settings/file-system/

In there, it said the file directory is set to  site/default/files - which is obviously wrong and drupal was saying as much, highlighting it in red. What should I be changing the default file directory to on that configuration page?

Sorry for such basic questions, please appreciate that this particular thing isn't something I do every day. I move sites around quite rarely.

And I do bother to RTFM. Honest! :-D

Thanks.

**Comment by chrisdbarnett** [comment]
Ahhh right - all to do with this unison file thingy ... right ... never mind me ... more RTFM I guess. I believe I've mainly overcome the whole files thing .. only to bump into another CiviCRM issue. So I'll leave this one here as it is and if I need any help re CiviCRM ... I'll open another issue.

Thanks.

**Comment by herbdool** [comment]
@pirog In my case it was CiviCRM trying to use mysqli (4.7.x). I didn't try to enable mysql but mysqli, which worked:

```
docker exec -i -t appname_appserver_1 bash
docker-php-ext-install mysqli
```

A side note: CiviCRM 4.7 isn't quite ready for PHP 7. I think most of it will work but I'm not sure if CiviMail will. They've got a meta issue about it.
