### ISSUE TITLE
Support customizations in `pantheon.yml`

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1622]
Pantheon allows users to customize aspects of their per-site-experience with a `pantheon.yml` file. https://pantheon.io/docs/pantheon-yml/

As a Kalabox user i also want my local build to mimic these settings where applicable. It looks like Kalabox alread has the internal machinery to easily support the customization of the following things 
1. Drush Version
2. PHP Version
3. Custom (nested docroot) webroot

**Comment by jdleonard** [comment]
+1!

**Comment by gremy** [comment]
+1

**Comment by labboy0276** [comment]
+47

**Comment by pirog** [comment]
Will be happening soon!

We might even support some quicksilver hooks if you guys are rocking all the pro-tools

**Comment by scottfatbeehive** [comment]
+1

**Comment by scottfatbeehive** [comment]
Is it possible to provide instructions how to change the webroot via the config and/or nginx.conf files for the time being well this feature is under development?

**Comment by pirog** [comment]
@scottfatbeehive does that change to the `nginx` conf not give you the result that you want?

**Comment by scottfatbeehive** [comment]
@pirog Yes that seems to work but not knowing Kalabox I'm not sure if I'm going to be causing other issues by changing that, so I thought I'd ask in case there is a recommended way.

**Comment by pirog** [comment]
@scottfatbeehive nope! AFAIK, i think that should be a pretty safe change

**Comment by scottfatbeehive** [comment]
Thanks!

**Comment by gremy** [comment]
@pirog any news?

**Comment by jstoller** [comment]
See https://github.com/kalabox/kalabox/issues/1764 regarding nested docroot.

**Comment by pirog** [comment]
This is something that is going to happen and will be supported eventually. That said we are still waiting for some best practice dev patterns to emerge before we build out support. It's likely this will show up in our successor project _lando_.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
