### ISSUE TITLE
Problem with semi-installed Pantheon site

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1625]
After uninstalling everything (I think), and a seemingly successful kalabox installation, I tried to install my Pantheon app again using the GUI.

Although I am quite sure that I had deleted .kalabox and everything in it, the GUI gave me an error message (through the bell icon) that my app was already installed. After the GUI closed, I started it again and there is an icon for my Pantheon site but without a snapshot. The start button seems to work (it turns green) and doesn't give any error messages, but I get 500 internal server error if I try to pull up the website. If I try a fake name.kbox, I get the error 400, as expected.

I destroyed the Pantheon app in the GUI and created it again (also in the GUI) and it now works. However, I thought you might want to know what happened.

**Comment by pirog** [comment]
@jsibley2 his sounds like the expected behavior if you do not completely remove an app.
