### ISSUE TITLE
Redis connection failed EMFILE on start

### ISSUE THREAD

**Issue by dalin-** [kalabox/kalabox#1626]
# Bug Report

**Tell us about your setup**

What is your Kalabox version and operating system?
2.0.0

[output of `kbox env`](https://github.com/kalabox/kalabox/files/493719/kbox-env.txt)

Have you previously installed Kalabox? If so, what version?

Yes, some forgotten previous version.  But removed as per
http://docs.kalabox.io/en/stable/users/updating/#purge-updating

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

kbox start and kbox rebuild are both ending up with redis errors like this

```
Redis connection to 10.13.37.100:8160 failed - connect EMFILE
Error: Redis connection to 10.13.37.100:8160 failed - connect EMFILE
    at errnoException (net.js:837:11)
    at connect (net.js:707:19)
    at net.js:788:9
    at dns.js:49:18
    at process._tickCallback (node.js:917:13)
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

[output of `kbox start`](https://github.com/kalabox/kalabox/files/493738/kbox-start.txt)

Sometimes the site still comes up in the browser, sometimes it shows the Kalabox 502 error.

Initial research shows that node.js is out of file descriptors.  Seems to be something in Docker though as there's plenty in OSX:

```
sysctl kern.maxfiles
12288
sysctl kern.maxfilesperproc
10240
ulimit
unlimited
sudo ulimit
unlimited
```

Random Googling suggests trying
https://github.com/isaacs/node-graceful-fs
Though maybe there's just a leak somewhere. 

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Unknown.

Does this bug prevent you from using Kalabox?

sometimes.  Not quite sure yet what exact incantation needs to happen in order to get it to come up in the browser.

**Comment by pirog** [comment]
@dalin- i see that you have QUITE a few subdomains set up. I'm wondering if that is part of your issue.

**Comment by dalin-** [comment]
Taking out half of the subdomains does make the problems go away.  It seems strange though that this problem only affects one person on our team and not everyone.

**Comment by pirog** [comment]
@dalin- i assume the other members have the identical subdomain config with the user who is experiencing this issue? Any obvious differences for this user ie runs a different OS?
