### ISSUE TITLE
Add documentation that Kalabox can't be installed or used on Windows if Hyper-V is enabled

### ISSUE THREAD

**Issue by LordPachelbel** [kalabox/kalabox#1628]
On Windows, VirtualBox can't install or run 64-bit VMs when Hyper-V is enabled because only one hypervisor can run at a time, and Hyper-V is always running once it has been installed. There's a workaround involving selectively disabling Hyper-V for the next boot cycle and then rebooting; see https://github.com/kalabox/kalabox/issues/1610#issuecomment-249682133 for the specifics.

Please add documentation about this conflict and the workaround to
* http://docs.kalabox.io/en/stable/troubleshooting/
* http://docs.kalabox.io/en/stable/users/install/#common-installation-issues
* http://docs.kalabox.io/en/stable/users/install/#windows

**Comment by pirog** [comment]
@LordPachelbel this should be in the next payload of doc updates
