### ISSUE TITLE
Kalabox installer getting stuck and not installing on OSX 10.12

### ISSUE THREAD

**Issue by mkykode** [kalabox/kalabox#1629]
Bug Report
==========

What is your Kalabox version and operating system?

kalabox v2.0
OSX 10.12

Have you previously installed Kalabox? If so, what version?

No

Give a brief description of what happened, including any error messages that appeared.

The installer gets stuck on the last minute. I have homestead 5.3 with virtualbox 5.1.6. Nothing was running. I tried installing a few times, uninstalling everything and trying again. It always get stuck on the same spot. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

Not much to say. Turn on computer. 
Open Safari.
Download .dmg latest release.
Open instaler.
Gets stuck on the last minute.

Does this bug prevent you from using Kalabox?
Yes

**Comment by mkykode** [comment]
Resolved this by deleting any previously created ~/.docker folders

**Comment by pirog** [comment]
@mkykode how did you arrive at deleting that directory? Was it in our docs or someplace else?

Going to reopen since it might be a good doc update.

**Comment by azarzag** [comment]
I have a similar issue. In my case, im able to go through the installer, but once i run it kalabox never starts. It gets stuck on the "Starting the kalabox engine screen"

Kalabox version 2.0
Mac version 10.12
Previously working kalabox version 2.0-rc3

I've tried deleting the ~/.docker directory, after uninstalling kalabox, but it didnt make any difference.

**Comment by pirog** [comment]
@azarzag have you looked through the install logs at all to drill down on the error you are getting?

@mkykode i've added this to the troubleshooting section of our documentation. Thanks!

**Comment by mkykode** [comment]
@pirog No I didn't find it on the docs, I just guessed that maybe I had a previous installation of docker files that was conflicting.
