### ISSUE TITLE
Kalabox 2.0 stuck on Pulling Files from Pantheon in OSX 

### ISSUE THREAD

**Issue by aaronlutze** [kalabox/kalabox#1630]
HI there, just started using Kalabox and while importing my first site from Pantheon, it is stuck on "Pulling files". The program hasn't hung, I can still navigate, but the site being imported is no longer pulling. It's not a very big site either, and my internet connection is fast.

I am using Kalabox 2.0.0 on OSX 10.11.3. I have not previously installed Kalabox.

Steps to Replicate

1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit

This bug has not prevented me from using Kalabox, as I have been able to import another site successfully. Please see attached screenshot.

![screen shot 2016-09-28 at 9 24 18 am](https://cloud.githubusercontent.com/assets/22485099/18895531/abacf514-855d-11e6-9ffc-47dcca43c86a.png)

[pantheon][bug fix]

**Comment by aaronlutze** [comment]
Ok, so the pulling of files 'fixed' itself after the second site was setup. I am not sure if it was just stuck, or, if setting up a 2nd site magically fixed this.

**Comment by pirog** [comment]
@aaronlutze this sounds like the same behavior that is described in 
https://github.com/kalabox/kalabox/issues/1586

I think i'm going to close this and try to funnel people over there. You mind reposting over there?
