### ISSUE TITLE
Permission denied while running kbox git pull or kbox git push

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1634]
Bug Report
==========

Kalabox 2.0.0
Mac OS X 10.11.6

I mentioned this briefly in #1371 but I don't think it was related to that main issue, and it's still causing problems for me. 

If I try to run `kbox git pull` or `kbox git push`, I get the error:
```
error: cannot open .git/FETCH_HEAD: Permission denied
```

I recursively changed the permissions on /code/.git to 777 but I get the same error.

**Comment by pirog** [comment]
@amklose going to close this as a dup and link to the other issue on this
https://github.com/kalabox/kalabox/issues/1615

i would def post over there. i'd love to figure out why this is happening for some people.
