### ISSUE TITLE
No permission for web server on Windows 7

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1637]
Kalabox 2.0.0
Windows 7 Enterprise
First install

Does this bug prevent you from using Kalabox?
Yes

== STEPS ==
1. Install Kalabox and create a D8 app through the GUI.
2. Click on new app in GUI to continue the installation.

== RESULTS ==
1. Browser is messaged, window comes up with "Forbidden"

This does not happen on the Mac with 2.0.0.  — works like a charm there.

![image](https://cloud.githubusercontent.com/assets/194045/19009056/f5f1c9b0-8724-11e6-9e44-5880a94c2f7a.png)

**Comment by aangelinsf** [comment]
I'm learning my around and discovered this section in the apache2-foreground file:

```
# Do this so our mounted VB volumes work
# @todo: silent fail perm setting?
echo "Remapping apache permissions for VB sharing compat..."
usermod -u "$KALABOX_UID" www-data
groupmod -g "$KALABOX_GID" www-data || usermod -G staff www-data
chown -Rf www-data:www-data /var/www/html

```
The permissions on /var/www/html are 755 and the group is www-data. Parent (www) is owned by root...which should be all fine.

Not sure why it works perfectly on the Mac but not on Windows.

**Comment by pirog** [comment]
@aangelinsf so i **think** this generally happens when you can't pull your code correctly. Best place to look there is in the kalabox logs in `~/.kalabox/logs`. The most likely culprit is either your `ssh-key` not generating correctly or an issue resolving the pantheon git endpoint.

**Comment by aangelinsf** [comment]
Ok, I'll check that out, thx.
