### ISSUE TITLE
Actions performed with CLI do not reflect in GUI, eg `kbox start`

### ISSUE THREAD

**Issue by aangelinsf** [kalabox/kalabox#1638]
2.0.0 
On Windows 7 and macOS 10.12
First install

== Steps ==
1. Run an app from the GUI.
2. Drop down to the terminal and run 'kbox down'

== Results ==
GUI on/off button doesn't change and there is no way to refresh the interface to obtain the current status.

Does this bug prevent you from using Kalabox?
No

**Comment by pirog** [comment]
@aangelinsf currently the GUI and CLI do not communicate with one another so this is expected (and unfortunate) behavior. 

I **thought** we had an open issue about this but seem to have lost it.

**Comment by aangelinsf** [comment]
I figured...thought I would make an issue so it doesn't get lost.

**Comment by pirog** [comment]
yup! definitely appreciated!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
