### ISSUE TITLE
System intensive and does complete clean up on OS 10.10 Sierra

### ISSUE THREAD

**Issue by OddenCreative** [kalabox/kalabox#1639]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Version 2.0.0 (2.0.0) on Apple OS 10.10 Sierra

Have you previously installed Kalabox? If so, what version?
Clean install

**Tell us about your bug**

Came in and the system took 15 minutes to slowly awake and shut down

1. Turn on and only open Intellij and Kalabox
2. Fan turns on and stays on all day. (It doesn't when I'm exporting video)
3. VBoxHeadless 120-125% CPU Memory 1.27
VBoxSVC Real Memory 1.27GB, 3.73GB Virtual Memory, Private Memory 1.28GB
4. No bash services running
5. Shut down Kalabox
6. VBoxHeadless disappears, Bash replaces it with similar footprint

Have been able to repeat this 2/5 tests with just Kalabox.

**Comment by pirog** [comment]
@OddenCreative this can definitely happen. keep in mind that kalabox is essentially a PaaS emulator and does some pretty intensive operations to make sure your code is all synced up.

Generally you can avoid a lot of this by restricting your file sharing appropriately and only running the apps you need. This blog post might help you
http://www.thinktandem.io/blog/2016/09/29/how-my-agency-uses-kalabox-to-win-all-the-local/

Ultimately there isnt a ton we can do about this until docker provides a better way to handle file sharing :/
