### ISSUE TITLE
kalabox.deb file not compatible with debian i386

### ISSUE THREAD

**Issue by warrenryd** [kalabox/kalabox#1641]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

*v2.0.0 on Debian 8.6 i386

Have you previously installed Kalabox? If so, what version?

*no, trying to install for the first time

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

*The file kalabox-v2.0.0.deb file appears to have been built on an amd64 architecture.  It won't execute or decompress on i386 machine.

![kerr](https://cloud.githubusercontent.com/assets/16962769/19045682/61da5064-8957-11e6-9cab-5319b5c8ffc8.gif)

Same issue happens with kalabox-latest-dev.deb.  Is it possible to get an i386 compatible .deb file?  Or is Debian on i386 truly supported?

Thanks,

Warren

**Comment by pirog** [comment]
@warrenryd some of the underlying tech we use is not i386 compatible. :(

I've updated our docs to show an explicit x64 requirement.
