### ISSUE TITLE
URL pointing to prod instead of local environment

### ISSUE THREAD

**Issue by xmulot** [kalabox/kalabox#1643]
Hello, 

I am able to successfully install kalabox, link my pantheon account and even have a complete app running. You can see the installation log I have attached.
The bottom of the log tells me the installation was successful:
```

Your app has started up correctly. Here are some vitals:                                                                   
  URL: http(s)://localsandbox1.kbox
  LOCATION: /home/xav/localsandbox1
```
**But the URL redirects to my production environment!!**

I am wondering what I am missing so I can really use my local environment that is correctly installed.

Any ideas?

Thank you.

Env:
Unbuntu 16+ / Kalabox 2.0.0
[installation.txt](https://github.com/kalabox/kalabox/files/507171/installation.txt)

**Comment by pirog** [comment]
@xmulot the most likely scenario here is you guys have custom redirect logic set up in the `settings.php` for your app or elsewhere that is doing this. 

We do not do any redirects on our end.
