### ISSUE TITLE
Add Aegir support

### ISSUE THREAD

**Issue by cweagans** [kalabox/kalabox#1644]
As an Aegir user/admin, I'd like to be able to pull down a copy of a site hosted on my Aegir installation for local development purposes. I think it's reasonable to have to clone the codebase myself (since Aegir doesn't really have the concept of a version controlled site like Pantheon does), and then pull down a backup of the files and database from Aegir and set it up in the codebase that I cloned.

If we're dreaming big, I think it would be _really_ cool to have a "Develop this site locally with Kalabox" in the Aegir UI, and when I click it, Kalabox would be opened and start pulling down the site.

I am an Aegir comaintainer and I'm willing to build the server-side part of this if somebody can help with the Kalabox part of things.

**Comment by pirog** [comment]
@cweagans!!!

I would love to make this happen. Any chance you'll be at BadCamp?

**Comment by cweagans** [comment]
Not this year. I'll be on my honeymoon. :) Happy to connect after BADcamp, though!

**Comment by pirog** [comment]
CONGRATS! o0o0o0o0o0o 💍  0o0o0o0o0o 

i set up an alert to ping you back on this post-badcamp.

**Comment by cweagans** [comment]
Coolio. Looking forward to chatting!

**Comment by pirog** [comment]
Ditto! Enjoy the nuptial bliss!

**Comment by Steve-A-Orr** [comment]
I know of a number of people in the Higher Ed community, using Aegir, which might appreciate this type of "Develop locally with Kalabox" development process.

**Comment by pirog** [comment]
@Steve-A-Orr good to know and good timing because i am supposed to ping @cweagans back on this about now. 

@cweagans, you want to do some exploration on this sometime soon?

**Comment by cweagans** [comment]
Absolutely. Want to drop me an email and we can coordinate a time?  me@cweagans.net

**Comment by pirog** [comment]
@cweagans will do!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
