### ISSUE TITLE
Mac OSX Kalabox Window Not Draggable to Resize

### ISSUE THREAD

**Issue by alexfinnarn** [kalabox/kalabox#1646]
# Feature/Enhancement Request

**Please explain your request and its importance in the form of a user story.**

As a Kalabox user who runs Mac OSX, I want to be able to drag the Kalabox window and resize it in order to better see configuration options. 

**Please provide some detail on how Kalabox can help solve this problem**

I don't know how this works in an OS, but on the database configuration, in particular, I have to scroll around to see all of the information. I would think an option while creating the Mac OSX image could be checked to add the feature.

**Comment by Steve-A-Orr** [comment]
I can see what he is talking about...when I spin up Kalabox on a Mac, the window generated is not resizable. So, when I want to look at the "Connection Info" sub-window, a modal is created causing a vertical scroll-bar to appear on the Kalabox main window; this requires me to scroll down to see the database information. If I could resize the Kalabox main window, then I might avoid the scroll-down effort. 

IMO, certainly an enhancement, but not a requirement, as all information is currently accessible.

**Comment by reynoldsalec** [comment]
@alexfinnarn + @Steve-A-Orr 

It is a bit awkward; we've kept the window statically sized simply because we didn't want to worry too much about "responsive" behavior of the window. Certainly something we want to fix.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
