### ISSUE TITLE
Ability to add a custom upstream 

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1647]
As a developer i often desire to pull my upstream code from github. Right now i have to pull a site from a pantheon or spin up a stock app and then add remotes as needed. It would be great if there was an easy way to tell kalabox to use an upstream git repository instead of something else.

This would also be helpful for testing.

**Comment by Steve-A-Orr** [comment]
@pirog I'm interested in this too. For instance, I want to experiment with Lightning Distribution in Pantheon. I can only think to spin it up locally, using the old local Dev methods, then import it into Pantheon using their Migration features. I'd like to be able to do something more straight forward...point at distribution URL and click...hopefully within Kalabox tool.

What are your "add remotes as needed" steps, as they still sound shorter than mine?

**Comment by Steve-A-Orr** [comment]
@pirog Maybe you were referring to the process in #1402 write-up?

**Comment by pirog** [comment]
@Steve-A-Orr yeah i think the thinkng here is basically "give me some random git repo" and we will use that instead of the default (eg the pantheon git repo in the case of the pantheon app or vanilla drupal in the case of the php app)

#1402  and #381 also might be helpful

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
