### ISSUE TITLE
Kalabox config with front-end tools such as grunt

### ISSUE THREAD

**Issue by skye-va** [kalabox/kalabox#1649]
Bug Report
==========

**Tell us about your setup**
What is your Kalabox version and operating system?
v2.0.0 on Mac OS 10.11.6 El Capitan

Have you previously installed Kalabox? If so, what version?
Yes, I had installed Kalabox v1 prior to this. However, I recently uninstalled and fully deleted all folders/files before installing v2.

**Tell us about your bug**
I am having troubles with front-end tools, specifically grunt and kbox.
1. Open up Terminal
2. Run a grunt command locally, it builds/watches the files correctly. 
3. If I run the same command with 'kbox grunt' nothing is built. I was able to do a 'kbox npm install' so it's installed the node module dependencies (where does it install them, though?? I can't figure it out).

**Tell us more**
I would like more documentation for configuring front-end tools such as npm/grunt/bower.
Additionally, I don't know if this is related but I am having big caching troubles with refreshing changes -- it's like the connection has broken with syncing files.

Does this bug prevent you from using Kalabox?
Yes, I can't use my front-end tools properly :(

**Comment by pirog** [comment]
@skye-va have you looked at our documentation? i think a lot of these concerns are addressed there.

that said we do recognize that it can be a little tricky to use the front end tools and we plan to address this in the next few releases. this will include better documentation or some blog posts.

**Comment by skye-va** [comment]
@pirog yes, well I've read the http://docs.kalabox.io/en/stable/users/config/#tooling section. I'm 'sort of' able to get grunt to run tasks now (because I restricted the synced paths in my kalabox.yml), but it is still painfully slow. Is anyone else having this issue with grunt/gulp? 
The deployment/Pantheon process is so terrific but we are struggling with the local dev side.

**Comment by pirog** [comment]
@skye-va hoping to get some better docs and blog posts about the ideal way to do the front end stuff. Is there anyway you can share some specifics on your workflow ie what your grunttasks and commands look like and what you expect them to do?

**Comment by skye-va** [comment]
Well, I think we may have a handle on it so I won't waste your time. After running the same setup on another computer it was quite reasonably fast; so we determined it was my machine that couldn't handle the performance load with syncing. My ol' Mac is being retired. Thank you for keeping tabs on this thread though. @pirog 

I will say that using the module 'jit-grunt' instead of 'load-grunt-tasks' also vastly improved speed, if anyone is having a slow grunt workflow.

**Comment by pirog** [comment]
@skye-va good to know on both counts. 

About how old was your mac and what was its basic config? We are still trying to determine a reasonable "cut off" point for people with older machine.

**Comment by skye-va** [comment]
@pirog I was using a Mac mini server that was about 4-5 years old I believe. It has 8MB of RAM and I was running El Capitan. We had a technician look over it a couple weeks ago so it's quite ok as far as basic processes, but simply too old to cope I suppose.

I timed some kbox commands and for example: 'kbox git status' consistently took 30 seconds or more. 'kbox grunt watch' took around 60 seconds to see changes to a SASS file, and compile to CSS. 

On my brand new iMac, I have grunt compiling in 1 second or less which is lovely.

**Comment by pirog** [comment]
awesome! that sounds a lot closer to our benchmarks. 

Also somewhat exciting news. I am **pretty sure** we are going to release an experimental version of Kalabox sometime next week, along with v2.0.2 which uses the new "Docker for Mac" as the backend instead of docker-machine. 

One SUPER SUPER awesome consequence of this (beyond no more virtualbox) is that file sharing/syncing should "just work" now e.g no customization required in kalabox.yml, no massive resource usage.
