### ISSUE TITLE
civicrm.settings.php for CiviCrm on pantheon app 

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#1650]
I can't seem to figure out the proper settings for CiviCRM. We went through this about 1 year ago and resolved it with what is listed here: https://kalamuna.atlassian.net/wiki/pages/viewpage.action?pageId=42991622

it doesn't seem to work, has something changed since then that would render these settings incorrect? I disabled CiviCRM to make sure that it indeed was the issue. The app worked fine with CiviCRM disabled. 

Thanks

**Comment by pirog** [comment]
@yosefromano there is an open pull request against the CiviCRM Pantheon upstream to address this but it hasnt been merged in yet. 
https://github.com/herbdool/civicrm-starterkit-drops-7/pull/2

**Comment by yosefromano** [comment]
Are these settings supposed to work without any other configurations?
I tried using those settings and I'm still getting this error:

Error: Could not create directory: /srv/bindings/kalabox/files.
If you have moved an existing CiviCRM installation from one location or server to another there are several steps you will need to follow. They are detailed on this CiviCRM wiki page - http://wiki.civicrm.org/confluence/display/CRMDOC/Moving+an+Existing+Installation+to+a+New+Server+or+Location. A fix for the specific problem that caused this error message to be displayed is to set the value of the config_backend column in the civicrm_domain table to NULL. However we strongly recommend that you review and follow all the steps in that document.

**Comment by kreynen** [comment]
I turned that project over to @herbdool a few months ago.  I'm no longer working with CiviCRM, but I know Herb would appreciate any feedback / support.  There is a more active branch of the CiviCRM starter at https://github.com/herbdool/civicrm-starterkit-drops-7/tree/update, but I'm not what the best way to get involved in testing that on Pantheon or Kalabox.

**Comment by pirog** [comment]
@kreynen awesome to know! 
@herbdool would you accept a PR to help get CIVICRM to work out of the box on Kalabox?

**Comment by herbdool** [comment]
@pirog looks good to me. I'll merge it.

**Comment by pirog** [comment]
@herbdool awesome. i haven't tried those settings in a yearish so ill give them a test ride in a bit and report back over on your repo if something needs to change.

**Comment by pirog** [comment]
@yosefromano @herbdool the merged code seems to work but a few things seemed to have changed on our end so 'ill send up a PR for that in a sec

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/pull/180
