### ISSUE TITLE
Webgrind/profiling tool

### ISSUE THREAD

**Issue by mkykode** [kalabox/kalabox#1652]
Kalabox 2.0.1, MacOS Sierra, Pantheon, Wordpress setup

I read that kalabox comes with webgrind. Can someone tell me how to launch the profiler? I've set the config in php.ini 'xdebug.profiler_enable = 1'

**Comment by pirog** [comment]
@mkykode where did you read that?

we definitely ship the pantheon app with xdebug but AFAIK there is no webgrind support at this time.

**Comment by pirog** [comment]
giving this another title

**Comment by mkykode** [comment]
@pirog I see, sorry, I thought maybe the original version came with it. The original kickstarter threw me off.
https://www.kickstarter.com/projects/kalabox/kalabox-advanced-web-tools-for-the-people/description?lang=es

**Comment by pirog** [comment]
@mkykode no worries. there is a lot of somewhat dissonant material out there unfortunately. that said, we plan on making a profiling plugin at some point so its good to have this issue around.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
