### ISSUE TITLE
Install fails on Debian 8 with "Cannot start container"

### ISSUE THREAD

**Issue by quietone1** [kalabox/kalabox#1653]
**Tell us about your setup**
Fresh install of Debian 8 with GNOME desktop on a Dell laptop, 64 bit. The laptop is about 5yrs old but I'm just want to test drive kalabox before trying to add it my working laptop.

What is your Kalabox version and operating system?
kalabox-v2.0.1.deb on Debian 8
Debian 8

Have you previously installed Kalabox? If so, what version?
Yes, kbox 0.12.0-beta.1. But that was a different laptop and I was unable to use kalabox, #1253 #1421. I wanted to try again, this time adjusting my uid/gid as needed.

**Tell us about your bug**
Install fails with "ERROR: Cannot start container 5ffef7372e55954c8a7edcf215631644965a25bd1bf65355694d9e08c9faec3c: failed to create endpoint kalabox_proxy_1 on network bridge: Error starting userland proxy: listen tcp 10.13.37.100:80: bind: address already in use"

Here is the full output 
```
root# dpkg -i kalabox-v2.0.1.deb  > kalabox_install.txt
+ KALABOX_ROOT=/usr/share/kalabox
+ KALABOX_BIN=/usr/share/kalabox/bin
+ DOCKER_COMPOSE=/usr/share/kalabox/bin/docker-compose
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin
+ TERM=xterm
+ KALABOX_IP=10.13.37.100
+ chmod 755 -R /usr/share/kalabox
+ '[' -x /sbin/initctl ']'
+ command -v foo
+ '[' -d /run/systemd/system ']'
++ which systemctl
+ '[' -x /bin/systemctl ']'
++ which systemctl
+ /bin/systemctl version
+ systemctl start kalabox.service
+ systemctl enable kalabox.service
Synchronizing state for kalabox.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d kalabox defaults
Executing /usr/sbin/update-rc.d kalabox enable
+ '[' '!' -f /usr/share/kalabox/bin/docker-compose ']'
+ mkdir -p /var/log/kalabox/
+ DOCKER_HOST=tcp://10.13.37.100:2375
+ KALABOX_DOMAIN=kbox
+ KALABOX_ENGINE_IP=10.13.37.100
+ /usr/share/kalabox/bin/docker-compose -p kalabox -f /usr/share/kalabox/services/services.yml up -d --force-recreate
Pulling proxy (kalabox/proxy:stable)...
Creating kalabox_proxy_1
ERROR: Cannot start container 5ffef7372e55954c8a7edcf215631644965a25bd1bf65355694d9e08c9faec3c: failed to create endpoint kalabox_proxy_1 on network bridge: Error starting userland proxy: listen tcp 10.13.37.100:80: bind: address already in use
dpkg: error processing package kalabox (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 kalabox
root# 
```

**Tell us more**

A search for 'kalabox install fail' returns this link,  http://docs.kalabox.io/en/stable/users/install/ and on that page the link to 'minimum system and hardware requirements' is broken. I found the requirements at http://docs.kalabox.io/en/stable/general/sysreq/.

Does this bug prevent you from using Kalabox?
Yes.

**Comment by pirog** [comment]
@quietone1 have you checked out the issue queue or docuemntation at all? Pretty sure this is addressed in a few areas.
https://github.com/kalabox/kalabox/issues/1273
http://docs.kalabox.io/en/stable/users/install/#debianubuntu

**Comment by quietone1** [comment]
Ah, sorry to waste your time. Seems I can't see what is right in front of me.

**Comment by pirog** [comment]
@quietone1 lol. no worries. 

i'm also super guilty of not RTFM.
