### ISSUE TITLE
How can I publish a Kalabox Drupal site on a VPS?

### ISSUE THREAD

**Issue by Nitty-Gritty** [kalabox/kalabox#1658]
How can I publish sites built with Kalabox without using Pantheon?

Is there a recommended workflow to setup a VPS with the identical stack and site content used to build the Kalabox site?

A section in the documentation about publishing Kalabox builds on VPS would be very helpful.

I'm using Windows but can swap to Linux.

**Comment by pirog** [comment]
@Nitty-Gritty Kalabox is not currently meant as a deploy tool, the model for now is more "pull from" and less "push to". I also wouldn't recommend using our container specs in production. 

We do plan to offer some deploy features in the future but its far down the roadmap. For now your best bet is to export the assets of your site and then import them in the best way for the service you want. 

If you give me more details on your destination i can probably at least provide some more concrete steps.
