### ISSUE TITLE
Support for Magento

### ISSUE THREAD

**Issue by vladfr** [kalabox/kalabox#1661]
Since Kalabox ships with a php plugin, it would be great to run Magento as a new platform.
There's lots of things to be done but a shortlist to start could look like this:
- magento 1 stack
- magerun as tooling
- mage 2 stack
- `magento` cli as tooling
- easy import for existing DB
- share for media dir
- local.xml overrides

Any magento devs out there?

**Comment by pirog** [comment]
@vladfr i think this would be awesome. Here are a few comments to help people get started

* Definitely think we should start to separate the php app into particular frameworks, so magenta makes sense in its own app
* It is not yet possible to add GUI code to plugins, it needs to be added directly to the core project see #1393 
* It's worth checking out some of the other apps for examples. Volume sharing in override config files is a really easy way to customize things.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
