### ISSUE TITLE
Installation fails to start Docker for Mac

### ISSUE THREAD

**Issue by dsquaredb** [kalabox/kalabox#1664]
Setup: Older (Late 2011) MacBook Pro

Kalabox version and operating system: kalabox-v2.1.0-rc.1 on OS X 10.11.6

Have you previously installed Kalabox? If so, what version? Yes, multiple versions

**Tell us about your bug**

1. Installed the Kbox version above as an update successfully
2. GUI hung up when starting and never started. 
3. I uninstalled, then reinstalled and same problem, so cleaned out old apps and tried again. 
4. Viewed the kalabox.log and saw the last two lines of log were repeated several times. 
5. Looked at Accessing the Engine link on troubleshooting docs and took a chance on manually turning the engine on
6. Turned on D4M, started up Kbox GUI and it opened immediately. Was able to download a Pantheon site within a minute or two.

**Comment by pirog** [comment]
@dsquaredb good to know. can you share those last two log lines that were repeating. would also love to see your `/var/logs/install.log` if you dont mind sharing it!

**Comment by dsquaredb** [comment]
Here are the lines that were repeated 5 times and then nothing else:

{"level":"verbose","message":"KALABOX ENGINE ==> Running [\"start\"]","timestamp":"2016-10-17T17:56:46.184Z"}
{"level":"debug","message":"SHELL EXEC ==> Running command launchctl,start,com.docker.helper","timestamp":"2016-10-17T17:56:46.184Z”}

Attached today’s install.log (full file went back to April) :)

**Comment by pirog** [comment]
@dsquaredb those lines should be to launch docker for mac. it should try until it sees that the app is in a good state which is why it retries. you arent getting an error or anything at the end?

**Comment by dsquaredb** [comment]
No errors. The GUI just sitting there spitting out witty phrases. I left the first attempt running when I grabbed lunch thinking it would finish up and be waiting for me when I got back. 30 minutes later it was still spinning.

But once I turned on D4M manually, the GUI worked great. Downloaded one of my Pantheon sites really quickly.

**Comment by pirog** [comment]
hmm good to know. not exactly sure why that is happening but im glad we have an issue for it now.

**Comment by stevector** [comment]
I'm experiencing the same symptom. The Kalabox startup sequence loops without end:

<img width="717" alt="screen shot 2016-10-25 at 9 14 38 am" src="https://cloud.githubusercontent.com/assets/211029/19694278/8186a622-9a93-11e6-803b-7186dc319d75.png">

I have run the uninstaller multiple times and still experience this same issue.

No logs:

```
cat /var/logs/install.log
cat: /var/logs/install.log: No such file or directory
```

I'm running an early 2015 retina Macbook Pro with 10.11.6.

**Comment by ultimike** [comment]
I'm seeing the same thing - what's the best way to start Docker for Mac manually?

thanks,  
-mike

**Comment by dsquaredb** [comment]
I started Docker by going to Applications and click on boot2docker.app icon.

**Comment by pirog** [comment]
Should require just launching the "Docker.app" which you then can control through the top toolbar. 

We should be rolling a fix for this and the stable release of 2.1 later today.

**Comment by ultimike** [comment]
Roger that. That was easy (and a bit obvious!)

thanks,  
-mike

**Comment by stevector** [comment]
I didn't have Docker.app running when I first replied. I have it running now but I'm still seeing the same symptom of a Kalabox start-up process that doesn't complete.

**Comment by pirog** [comment]
@stevector what happens when you try to do something on the command line? 

its possible that older apps you created before upgrading (which need to be removed and recreated on a big upgrade like this) are mucking things up

**Comment by stevector** [comment]
```
 kbox    
	expecting an array or an iterable object but got [object Null]
TypeError: expecting an array or an iterable object but got [object Null]
    at process._tickCallback (node.js:917:13)
```

I did have a much older version of Kalabox installed about a year ago. I never got it working. But I've run the uninstaller.

**Comment by pirog** [comment]
i would check to see if you have any kalabox-y node modules in your global node modules directory. Might be worth scoping out ~/.kalabox/plugins as well.

**Comment by stevector** [comment]
I don't have a `~/.kalabox/plugins` directory.

```
➜  .kalabox cd ~/.kalabox
➜  .kalabox ls -al
total 24
drwxr-xr-x  11 stevepersch  staff   374 Oct 25 16:28 .
drwxr-xr-x+ 98 stevepersch  staff  3332 Oct 25 16:37 ..
-rw-r--r--   1 stevepersch  staff    36 Oct 25 16:28 .instance.id
drwxr-xr-x   5 stevepersch  staff   170 Sep 18  2015 .provider
-rw-r--r--   1 stevepersch  staff   116 Sep 18  2015 appRegistry.json
drwxr-xr-x   5 stevepersch  staff   170 Apr 12  2016 bin
drwxr-xr-x   5 stevepersch  staff   170 Sep 18  2015 downloads
drwxr-xr-x   5 stevepersch  staff   170 Sep  6 16:59 logs
-rw-r--r--   1 stevepersch  staff     4 Sep 18  2015 provisioned
drwxr-xr-x   5 stevepersch  staff   170 Apr 12  2016 services
drwxr-xr-x   3 stevepersch  staff   102 Sep 18  2015 syncthing
```

On the global front:

```
cd ~/.npm
➜  .npm ls -al | grep kala
drwxr-xr-x    4 stevepersch  staff    136 Dec 22  2015 kalabox
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-app-backdrop
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-app-drupal
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-app-pantheon
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-engine-docker
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-metrics-rest
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-plugin-dbenv
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-plugin-drush
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-plugin-git
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-plugin-php
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-plugin-rsync
drwxr-xr-x    3 stevepersch  staff    102 Sep 18  2015 kalabox-services-kalabox
drwxr-xr-x    3 stevepersch  staff    102 Dec 22  2015 kalabox-stats-client

```

Should those not be there?

**Comment by pirog** [comment]
thats good re: `~/.kalabox/plugins` that should only be there if you've attempted some custom kalabox dev.

WOW yeah you must have installed a VERY early version when we were still installing with `npm`. 

🔥  **PURGE ALL GLOBAL KALABOX MODULES WITH FIRE.** 🔥

**Comment by stevector** [comment]
`rm -r kalabox*`!!

Still getting errors :( 

```
kbox
expecting an array or an iterable object but got [object Null]
TypeError: expecting an array or an iterable object but got [object Null]
    at process._tickCallback (node.js:917:13)
```

**Comment by pirog** [comment]
not good. definitely guessing there might be additional old-version-cruft you need to clear out. 

Where is your `kbox` binary located? ie `which kbox` says what?

**Comment by stevector** [comment]
```
which kbox
/usr/local/bin/kbox
```

Where else might there be cruft? Can we update the uninstaller?

**Comment by pirog** [comment]
You should have a symlink in `/usr/local/bin` for `kbox`

```
kbox -> /Applications/Kalabox.app/Contents/MacOS/bin/kbox
```

Installer should have force overwritten this. 

We can definitely update the uninstaller but im guessing there are less than 5 people with this issue.

**Comment by stevector** [comment]
Ok, so this part is right?

```
ls -al /usr/local/bin | grep kbox
lrwxr-xr-x    1 root         admin        49 Oct 25 08:39 kbox -> /Applications/Kalabox.app/Contents/MacOS/bin/kbox
```

**Comment by pirog** [comment]
yup!

**Comment by iheijoushin** [comment]
I've been attempting a fresh install of Kalabox 2.0.1 on a MacBook Pro running macOS Sierra 10.12.1 (16B2555). Each time I attempt to install I get stuck at the following stage:

"Waiting for other installations to complete..."

Please let me know if there's a work-around to install Kalabox or where I can find any logs or additional details to assist fixing this issue for myself and others. Thanks!

**Comment by pirog** [comment]
@iheijoushin haven't seen that before and not to sound too obtuse but ... do you have other installations waiting to complete?

Also, this thread is for the 2.1.0 version so you might want to open another ticket.
