### ISSUE TITLE
"Cannot read property 'git_url' of undefined" when creating site from Pantheon

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1667]
This is Kalabox 2.1.0 RC2 on Windows 10.

I got past the issue I was having previously by mounting my shared drives (thanks for the assistance there!), then when it got a little further in the process it hung for a while after downloading the screenshot and then output:

```
Pulling code.
Cannot read property 'git_url' of undefined
TypeError: Cannot read property 'git_url' of undefined
    at C:\Users\bmcclure\.kalabox\apps\appname\plugins\kalabox-plugin-pantheon\lib\pull.js:92:47
```

I'll attempt to run with --debug and --verbose now to see if I get any more information, I'll post back if I uncover anything.

I'm not sure if this is related to #1318 or not as that was on the old VirtualBox version of Kalabox, but the error at least seems the same.

**Comment by bmcclure** [comment]
I ran it a second time, and something new came up before the error:

`[2016-10-18 21:22:55] [error] The provided machine token is not valid.`

I'm guessing a Pantheon authentication issue could be the cause of my reported issue, given this message. I ran `kbox terminus auth login` to try and re-authenticate, and it hung for a minute or two and then output:

```
λ kbox terminus auth login
[2016-10-18 21:30:05] [info] Cannot retrieve current Terminus version.
cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
    msg: 'cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'
[2016-10-18 21:30:05] [info] Found a machine token for "[my email address]".
    email: '[my email address]'
```

What's strange is it definitely seemed to take a long time to time out, even though it indicates 0 ms.

**Comment by pirog** [comment]
Hmmm yeah that is definitely weird. AFAIK there is no obvious problem with
authenticating with Pantheon at least on the Kalabox end.. This error looks
like it is coming from Terminus directly so im wondering if there is
something weird there.

**Comment by bmcclure** [comment]
@pirog Setting a fixed DNS server of 8.8.8.8 (the grayed out default) in the Docker settings instead of leaving it on Automatic fixed it so I can run `kbox terminus auth login` successfully, so I guess it was a DNS issue. Trying to destroy and create the site again now, will report back if that fixed everything.

**Comment by pirog** [comment]
@bmcclure oh very weird and sad... was hoping docker for windows was a little better with handling the insanity that is windows DNS

**Comment by bmcclure** [comment]
That did resolve my original posted issue and I got further now.

However, during code checkout I got `error: unable to create file vendor/caxy/php-htmldiff/demo/tablediffs.json (No such file or directory)` and the checkout failed. The rest of the process succeeded, although switching git branches failed since the working tree isn't in a good state. I'll try and troubleshoot this separately but just wanted to mention it.

Then after it finished pulling all the files, I got:

```
Fatal error: Class name must be a valid object or a string in /code/core/modules/field/src/FieldStorageConfigStorage.php on line 155
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Class name must be a valid object or a string in
/code/core/modules/field/src/FieldStorageConfigStorage.php, line 155
Waiting for site to be ready.
```

Then, it hung there for a long time (actually, it still is), and if I try to visit the site's .kbox domain I get a DNS error.

Definitely disappointing, I feel like this is similar to the previous DNS issues I was having (as you just alluded to I think). I see a Docker network in my Network Connections, but it's named "vEthernet (DockerNAT)" which makes me think it's maybe unrelated to the bridged adapter issue with Virtualbox.

**Comment by pirog** [comment]
@bmcclure so we are definitely using the same DNS handling code (with the new docker adapter) here as we did in 2.0.x plus the extra magic of docker for windows. do you know if you are running your own DNS server locally on 127.0.0.1:53? 

the rest of what you have here look like straight up php errors... i assume these are happening because of the incomplete checkout?
