### ISSUE TITLE
Shutting off 2.1.x engine on Windows is problematic, need to force close.

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1669]
If I start the GUI, then try to close it, even without starting an app, it seems like I need to use force close to close it, unless I'm not waiting long enough (5 minutes).

I have a Pantheon app, but hadn't started it, to see if that made closing Kalabox faster.

**Comment by pirog** [comment]
@jsibley2 this makes sense. I don't think we have a reliable way of shutting down docker for windows at this point so just force quit for now.
