### ISSUE TITLE
Provision fails at step 15

### ISSUE THREAD

**Issue by spazzwig** [kalabox/kalabox#167]
This may be related to #163 -- provision is failing at step 15. In this case the error indicates a DNS resolution issue however the URL resolves fine in curl/browser/etc.

```
info: -- Step 15/18 --
info: Installing your Syncthing image...
info: DOCKER => Pulling image. name=kalabox/syncthing:v0.6.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => DATA status=Pulling repository kalabox/syncthing
info: DOCKER => DATA message=Get https://index.docker.io/v1/repositories/kalabox/syncthing/images: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout, error=Get https://index.docker.io/v1/repositories/kalabox/syncthing/images: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout
info: DOCKER => Pulling image complete. name=kalabox/syncthing:v0.6.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: -- FAIL. --

Get https://index.docker.io/v1/repositories/kalabox/syncthing/images: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout
```

**Comment by pirog** [comment]
192.168.1.1:53 looks a little suspect to me.

can you paste in the results of `boot2docker --vm="Kalabox2" ip`

**Comment by spazzwig** [comment]
Sure thing:
```
% boot2docker --vm="Kalabox2" ip
10.13.37.42
```

**Comment by pirog** [comment]
Have you checked this out at all?
https://forums.docker.com/t/pulling-docker-images-i-o-timeout/740/2

def agree this seems DNSy but can't replicate as of yet.

**Comment by pirog** [comment]
This could also be cert related. You could try [uninstalling kbox](https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox) and then additionally deleting the id_boot2docker/id_boot2docker.pub in ~/.ssh before running provision again.

**Comment by spazzwig** [comment]
This was my first stop, thanks for pointing out the Docker thread. It gave me a hunch so I changed the DNS server setting in my router to OpenDNS (I was using a dnscrypt security/privacy setup) and provision worked fine. Either way this is a Docker registry or DNS server issue, everything is good here.

Thanks!

**Comment by spazzwig** [comment]
Great, look forward to the next version! Will it be announced on kalabox-friends?

**Comment by pirog** [comment]
Yes! Release is actually out but want to clean up some docs before
circulating.

On Thu, May 7, 2015 at 1:07 AM, Gabriel Crow <notifications@github.com>
wrote:

> Great, look forward to the next version! Will it be announced on
> kalabox-friends?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/167#issuecomment-99763461>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by Tigeda** [comment]
This may be related, I get this timeout error when running a `kbox install` on a fresh drupal app. (see last line).  The only difference I can think of since my last successful kbox install is that I'm connecting to the net via ethernet now, instead of WIFI.

```
Tims-iMac:quest-skills-for-life timdaff$ kbox install
info: DOCKER => Pulling image. name=kalabox/data:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => DATA status=Pulling repository kalabox/data
info: DOCKER => DATA message=Get https://index.docker.io/v1/repositories/kalabox/data/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout, error=Get https://index.docker.io/v1/repositories/kalabox/data/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
info: DOCKER => Pulling image complete. name=kalabox/data:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => Pulling image. name=kalabox/php-appserver:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => DATA status=Pulling repository kalabox/php-appserver
info: DOCKER => DATA message=Get https://index.docker.io/v1/repositories/kalabox/php-appserver/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout, error=Get https://index.docker.io/v1/repositories/kalabox/php-appserver/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
info: DOCKER => Pulling image complete. name=kalabox/php-appserver:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => Pulling image. name=kalabox/mariadb:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
info: DOCKER => DATA status=Pulling repository kalabox/mariadb
info: DOCKER => DATA message=Get https://index.docker.io/v1/repositories/kalabox/mariadb/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout, error=Get https://index.docker.io/v1/repositories/kalabox/mariadb/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
info: DOCKER => Pulling image complete. name=kalabox/mariadb:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
Get https://index.docker.io/v1/repositories/kalabox/data/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
```

```
Tims-iMac:quest-skills-for-life timdaff$ boot2docker --vm="Kalabox2" ip
10.13.37.42
```

**Comment by Tigeda** [comment]
Nope that didn't help unfortunately.

```
$ kbox create drupal
yada yada
$ cd test-drupal
$ kbox install
yada yada
info: DOCKER => Pulling image complete. name=kalabox/mariadb:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
Get https://index.docker.io/v1/repositories/kalabox/data/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
```

**Comment by bcauldwell** [comment]
Could be a few things.
1) - Docker registry had planned maintenance that should have completed
about 10 minutes ago.
2) - Virtual Box sometimes loses DNS and network connectivity when you
switch networks. Try either doing a kbox down and then do a kbox provision,
or if that doesn't work just open virtual box, powerdown the image, and
then close virtual box and a kbox provision.

On Sat, Jun 13, 2015 at 9:14 PM, Tigeda <notifications@github.com> wrote:

> Nope that didn't help unfortunately.
>
> $ kbox create drupal
> yada yada
> $ cd test-drupal
> $ kbox install
> yada yada
> info: DOCKER => Pulling image complete. name=kalabox/mariadb:v0.7.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
> Get https://index.docker.io/v1/repositories/kalabox/data/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/167#issuecomment-111780007>.
>



-- 
- Benjamin Cauldwell

**Comment by Tigeda** [comment]
`kbox provision` installs kbox?  I didn't want to do this step as I'm not sure of the implications on existing apps.

Rebooted comp, ran `kbox down` then `kbox up`, stepped into my app and ran `kbox install`, all worked OK!

Thanks

**Comment by bcauldwell** [comment]
Wonderful! Sounds like it was the virtual box losing it's network and not
being able to recover.

On Sat, Jun 13, 2015 at 9:28 PM, Tigeda <notifications@github.com> wrote:

> kbox provision installs kbox? I didn't want to do this step as I'm not
> sure of the implications on existing apps.
>
> Rebooted comp, ran kbox down then kbox up, stepped into my app and ran kbox
> install, all worked OK!
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/167#issuecomment-111780618>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell agreed and good to know that resolving the underlying VB connectivity issue would solve multiple issues.

**Comment by reynoldsalec** [comment]
Just noting that I received this error upon trying to rebuild an app, restarting kbox (the entire virtualbox) seemed to get everything working again, reinforces that this is probably a Virtualbox networking issue.
