### ISSUE TITLE
"Your environment or operation system isn't supported" when running drush after updating site

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1670]
I updated my Drupal 8 site on a Linux machine (Ubuntu 16.04) running Kalabox 2.1.0 RC2. Prior to updating the site today with composer, drush worked fine. Since then, I'm getting this error:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /code/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 /code/vendor/drush/drush/includes/environment.inc(641): Webmozart\PathUtil\Path::getHomeDirectory()
#1 /code/vendor/drush/drush/includes/preflight.inc(415): drush_server_home()
#2 /code/vendor/drush/drush/includes/preflight.inc(231): _drush_preflight_base_environment()
#3 /code/vendor/drush/drush/includes/preflight.inc(41): drush_preflight()
#4 /code/vendor/drush/drush/drush.php(12): drush_main()
#5 {main}
  thrown in /code/vendor/webmozart/path-util/src/Path.php on line 257

Fatal error: Uncaught exception 'RuntimeException' with message 'Your environment or operation system isn't supported' in /code/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 /code/vendor/drush/drush/includes/environment.inc(641): Webmozart\PathUtil\Path::getHomeDirectory()
#1 /code/vendor/drush/drush/includes/preflight.inc(415): drush_server_home()
#2 /code/vendor/drush/drush/includes/preflight.inc(231): _drush_preflight_base_environment()
#3 /code/vendor/drush/drush/includes/preflight.inc(41): drush_preflight()
#4 /code/vendor/drush/drush/drush.php(12): drush_main()
#5 {main}
  thrown in /code/vendor/webmozart/path-util/src/Path.php on line 257
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Uncaught exception 'RuntimeException' with message 'Your
environment or operation system isn't supported' in
/code/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 /code/vendor/drush/drush/includes/environment.inc(641):
Webmozart\PathUtil\Path::getHomeDirectory()
#1 /code/vendor/drush/drush/includes/preflight.inc(415):
drush_server_home()
#2 /code/vendor/drush/drush/includes/preflight.inc(231):
_drush_preflight_base_environment()
#3 /code/vendor/drush/drush/includes/preflight.inc(41):
drush_preflight()
#4 /code/vendor/drush/drush/drush.php(12): drush_main()
#5 {main}
  thrown in /code/vendor/webmozart/path-util/src/Path.php, line 257
```

Any idea what might cause this issue? Drush commands work fine on Pantheon via terminus.

**Comment by pirog** [comment]
So on this new version of Kalabox we will use the drush version that matches up with what is in the environment you pull  ... including the php version. So if you are using site-local drush its possible there is a mismatch here. 

Is it possible to share this site with me?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
