### ISSUE TITLE
Upgrade to mariaDB 10.0.5+ ?

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1671]
There is a huge number of ways of automating this task, however doing it with one click in Kalabox would be awesome.

**Comment by pirog** [comment]
Can you explain a little bit more what you mean here?

AFAIK you can already do this. What version are you on?

**Comment by yumyo** [comment]
Didn't realise it was there already! Great!!!

**Comment by yumyo** [comment]
@pirog I know is marginally related and I will open a new issue if is the case but just as a quick question, which version of mySql is included in Kalabox? I am getting `The used table type doesn't support FULLTEXT indexes` error trying to import DB from my Test env in Kalabox, both with wp-cli or Sequel Pro

**Comment by pirog** [comment]
@yumo it depends on what kind of app you are creating. pantheon apps use the version of mariadb that pantheon uses (maria 5.5) and the php apps use the latest version of mysql that is posted on the docker hub (looks like that is mysql 8 now).

**Comment by yumyo** [comment]
Hi @pirog thanks for the usual prompt reply. Have you had any experience in trying to convert all of the WordPress DB tables to InnoDB? 

I followed the Pantheon guide here [https://pantheon.io/docs/myisam-to-innodb/](https://pantheon.io/docs/myisam-to-innodb/) and everything seemed fine on DEV environment, however, importing the database back to Kalabox failed as well trying to do it via Sequel Pro. The reason seemed the same, `The used table type doesn't support FULLTEXT indexes` for the `wp_posts` table. 

I've dug a bit and found that MySql supports InnoDB FULLTEXT indexes starting from the 5.6.4 release and MariaDB from version 10.0.5 so, this is why I was wondering if there's any difference between the Pantheon environment and Kalabox. 

As you said, this seems not to be the case so I went back to MyISAM but I am still wondering the reason for the apparent difference.

**Comment by pirog** [comment]
@yumyo sounds like the most likely scenario is pantheon updated and we are still lagging behind. If you find out what version of maria they are running we can upgrade as well.

**Comment by yumyo** [comment]
Hi @pirog I've double checked through Sequel Pro and asking directly to Pantheon support, current Maria DB version in use is 10.0.23

**Comment by pirog** [comment]
@yumyo awesome! we bumped the version here for kalabox 2.1.0
https://github.com/kalabox/kalabox-app-pantheon/commit/e3821dfa7b9bc1ddcdb3331f6e53ff070b5a05ee
