### ISSUE TITLE
Windows 10 now has Ubuntu built in

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1672]
I see you've just switched to a hyper-v setup for win10 in kbox v2.1.0-rc.2 , im excited to try that new one, but have you tried to use the new built-in Ubuntu that's included in the recent win10 update?  Ive tried the install, it went ok for the most part but failed at pantheon create.
`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

No worries since I wasn't expecting it to work but Im curious if you investigated this any?

**Comment by pirog** [comment]
i havent and i dont think we plan to. ideally we want to provide a good experience on windows and are committed to doing that even though its not the easiest thing. 

i do think a few people have gotten this to work though and im not sure what would be different about this than normal ubuntu,

**Comment by macronomicus** [comment]
I thought potentially the kalabox ubuntu setup might work with only minimal needs for ubuntu on windows adjustments, windows does all the abstraction for ubuntu already, gives a full bash cli, merged networking and all the good stuff natively.

Besides that, Im using the new kbox version with hyper-v now and its excellent!

**Comment by pirog** [comment]
@macronomicus AFAIK some people have gotten this to work but i dont think its something we aim to officially support. 

GLAD TO HEAR RE: HYPERV! Are you having any issues there with resolving *.kbox addresses or your DNS in general? That seems to (still) be the big blocker for a lot of windows users.

**Comment by macronomicus** [comment]
Every now and then the networking does go out.  I found the solution is to shutdown kalabox and restart docker.  Im not sure why the net goes out though, seems random.   Just restarting the site or kalabox doesnt bring it back, only after restarting docker.

**Comment by pirog** [comment]
@macronomicus good to know. it would be great to find another solution for doing *.kbox DNS on windows since what we are doing now seems obviously not good enough. havent really seen any alternatives thus far though :(

**Comment by macronomicus** [comment]
Ill dig for errors next time it goes out, could be some clues, it was only rarely happening in the last few kalabox versions, but didnt bother much since a restart always brings it back.

**Comment by pirog** [comment]
awesome! any quality feedback on this specific issues would be great. 

My guess is that at some point windows determines that the kalabox DNS server should be used for ALL dns queries and that is when the whole thing fails.
