### ISSUE TITLE
Diffs have extra characters in them

### ISSUE THREAD

**Issue by Senpai** [kalabox/kalabox#1673]
# Bug Report

**Overview:**
The result of a diff has some unwanted, unexpected characters in it that makes the diff hard to read. It is presumed that this is because color support in the terminal is not present or working. This should be considered a regression bug.

**Environment:**
Kalabox 2.0.1 on Mac OS 10.12, freshly created Pantheon app.

**Steps To Reproduce:**
1. Perform a `kbox git diff filename.php` on a file that has changes.

**Expected Result:**
Should see output free of "[" or "[[m" characters.

**Actual Result:**
The output of a diff looks like

```
[[1mdiff --git a/sites/default/config/user.role.authenticated.yml b/sites/default/config/user.role.authenticated.yml[[m
[[1mindex 7eda143..b8a5422 100644[[m
[[1m--- a/sites/default/config/user.role.authenticated.yml[[m
[[1m+++ b/sites/default/config/user.role.authenticated.yml[[m
[[36m@@ -12,4 +12,3 @@[[m [[mpermissions:[[m
   - 'access content'[[m
   - 'use text format wysiwyg'[[m
   - 'restful get entity:node'[[m
[[31m-  - 'access in-place editing'[[m

~
~
~
~
~
~
~
~
~
~
~
~
~
standard input
```

**Comment by pirog** [comment]
@Senpai thanks much! will try to resolve this soon since it seems easy enough!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
