### ISSUE TITLE
How do i get php errors to display in kalabox?

### ISSUE THREAD

**Issue by rodriguezr2** [kalabox/kalabox#1675]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

kbox 2.0.1 on Mac OSX 10.10.5

Have you previously installed Kalabox? If so, what version?

No

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

Started GUI, 

Pulled Drupal 7 site from pantheon.

Started site environment

added the following to settings.php:

```
if (isset($_SERVER['KALABOX']) &&  $_SERVER['KALABOX'] === 'on') {
    error_reporting(-1);  // Have PHP complain about absolutely everything.
    $conf['error_level'] = 2;  // Show all messages on your screen
    ini_set('display_errors', TRUE);  // These lines give you content on WSOD pages.
    ini_set('display_startup_errors', TRUE);

    // Set some common desirable local vars.
    $conf['file_temporary_path'] = '/tmp';
    $conf['file_public_path'] = 'sites/default/files';
    $conf['file_private_path'] = 'sites/default/files/private';
    $conf['reroute_email_enable'] = 1;

    $conf['cache'] = 0;
    $conf['css_gzip_compression'] = FALSE;
    $conf['js_gzip_compression'] = FALSE;
    $conf['preprocess_css'] = 0;
    $conf['preprocess_js'] = 0;
    $conf['cron_last'] = '9999999999';
}
```
cleared cache using drush, restarted kbox

no errors appear, even when placing code outside of the if statement.

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using Kalabox?

no

**Comment by pirog** [comment]
@rodriguezr2 id read our documentation which discusses a few strategies on how to both access logs, change error reporting, and related topics.

**Comment by pirog** [comment]
I assume you've looked at the docs?

**Comment by rodriguezr2** [comment]
Is this the documentation?
http://docs.kalabox.io/en/stable/troubleshooting/
other wise no, i havent found it yet.

i'll keep looking later today. 

P.S. kalabox keeps disconnecting from mysql and after a while restarting kbox doesn't seem to work. should i open another issue?

**Comment by pirog** [comment]
@rodriguezr2 that is the core documentation. there are also docs for specific kinds of apps like pantheon and php.

i would only open an issue if you are sure this is not human error and youve checked out the fairly exhaustive amount of other issues and docs that are available.
