### ISSUE TITLE
Multitude of issues running kalabox on headless Centos 7 machine

### ISSUE THREAD

**Issue by pembo13** [kalabox/kalabox#1677]
I've been having a rough time getting Kalabox to run on CentOS 7.2.1511, with kalabox v2.0.1.

First, after getting the RPM installed, the service was running, and things seemed good. I switched to a regular user (I opened new putty session, and logged in as an unprivileged local user), and did `pip create pantheon`. However this failed while building the environment due to a missing "56" tag. I found the appropriate issue on here which explained support for PHP only went up to 5.5.

```
Pulling appserver (kalabox/pantheon-appserver:56)...
Pulling image kalabox/pantheon-appserver.
ERROR: Tag 56 not found in repository docker.io/kalabox/pantheon-appserver
```

I proceeded to edit kalabox.yml from "php: 56" to "php: 55", and attempted `kbox rebuild`. This timed out, repeatedly, apparently just trying to talk to the Kalabox service.

I attempted to `systemctl restart kalabox` and the service failed to terminate cleanly with several docker and XFS errors in /var/log/messages.

At this point, I have a massive "messages" log, and I'm really not sure how to proceed.

**Comment by pirog** [comment]
@pembo13 sounds like a networking issue to me since those tags and repos definitely exist and are used hundreds if not thousands of times a day. 

all that said i dont think we really envision kalabox being used in this sort of way. what is the sort of use case you are exploring by running it in centos headlessly?

**Comment by pembo13** [comment]
@pirog I'll try the process again, I haven't had intermittent networking issues before, but I'll report back.

I typically do my development on my Linux server to begin with, but to make better use of Pantheon, I'm trying to use Kalabox. The idea being to just SSH into the machine, and use the `kbox` command to create sites/apps from Pantheon, do the development, and push my changes back.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
