### ISSUE TITLE
Incorrect installation documentation for Centos/RedHat

### ISSUE THREAD

**Issue by pembo13** [kalabox/kalabox#1678]
Documentation: http://docs.kalabox.io/en/stable/users/install/

The current recommend instructions may only be accurate for Fedora. 

``` bash
sudo dnf update -y
sudo dnf install bridge-utils iptables cgroup-bin
sudo rpm -i kalabox.deb
```

On CentOS 7 (and I presume equivalent RHEL) the necessary commands are

``` bash
yum update -y
yum install bridge-utils iptables cgroup-bin
yum install kalabox-v2.0.1.rpm
```

And even with these commands, one gets the following warning/error:

```
warning: %post(kalabox-2.0.1-1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package kalabox-2.0.1-1.x86_64
```

To avoid this, one needs to use these commands instead:

``` bash
yum update -y
yum install bridge-utils iptables cgroup-bin xdg-utils
yum install kalabox-v2.0.1.rpm
```

It should also be noted, that a web server listening on all 443 TCP ports will cause an error as well on install:

```
Cannot start container cdd298fd09beed13564a12d74ca044403dd8a76db2d3b90bd2259e438f8fea21: failed to create endpoint kalabox_proxy_1 on network bridge: Error starting userland proxy: listen tcp 10.13.37.100:443: bind: address already in use
```

**Comment by pirog** [comment]
@pembo13 thanks for this. i've only ever run the RPM on fedora so its good to get some additional feedback from other RPM-y users.

**Comment by pembo13** [comment]
You are welcome.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
