### ISSUE TITLE
drush not installed into local Pantheon app with 2.1.0-rc2

### ISSUE THREAD

**Issue by joshuajabbour** [kalabox/kalabox#1681]
Bug Report
==========

**Tell us about your setup**

_What is your Kalabox version and operating system?_

kalabox 2.1.0-rc2
macOS 10.11.6
 
_Have you previously installed Kalabox? If so, what version?_

Yes, 2.0, but uninstalled before installing 2.1

**Tell us about your bug**

I pulled an app from Pantheon. Tried to run `kbox drush` and get `bash: drush: command not found`. Can't interact with site to do any development work without drush.

Everything else seems to work. The Drupal UI is usable (after I manually added my dns settings to /etc/hosts (which is another bug)). I just can't use drush, because it's not there. Terminus is usable, but can't find drush either.

_Does this bug prevent you from using Kalabox?_

Yes

**Comment by pirog** [comment]
@joshuajabbour been using this for a week or so and drush definitely seems to be there for me. its possible something changed upstream. are you sure you are using it from within the app you pulled?

you definitely should also not need to mess with `/etc/hosts` ... we don't even use this file for anything. if you didn't uninstall the older version its possible this messed with the handling of .kbox addresses.

**Comment by joshuajabbour** [comment]
Well, I am most definitely running other commands, and they work in context. I don't see the cli/drush docker container even running, so things are most definitely broken.

As for uninstalling breaking things, I used the provided script, so I'm not sure what to say there. This is definitely all barely working right now. If I get time, I'll reinstall from scratch, but I've already wasted a day on this. :/

**Comment by joshuajabbour** [comment]
Definitely still broken after a fresh install. The drush container is present, just failing:

![screenshot 2016-10-24 16 12 42](https://cloud.githubusercontent.com/assets/66879/19667282/d576c2a6-9a04-11e6-9408-4aab950eea29.png)

**Comment by pirog** [comment]
@joshuajabbour yeah i am guessing this is something upstream in the drush/drush:7-php5 image. In the meantime i'd switch to drush 8 in your kalabox.yml and `kbox rebuild` your app.

**Comment by pirog** [comment]
@joshuajabbour i can def confirm what you are getting here although only seems to be impacting drush7.

**Comment by pirog** [comment]
this ended up being on our end
https://github.com/kalabox/kalabox-app-pantheon/pull/184/files
