### ISSUE TITLE
Windows 7: Cannot start service web: oci runtime error. Shared drives issue?

### ISSUE THREAD

**Issue by tadhgpearson** [kalabox/kalabox#1684]
I'm running Kalabox v2.01  on Windows 7.

When I try to deploy my first app with

> kbox create pantheon

copying my existing pantheon dev environment, the deployment fails with the error

> ERROR: for web  Cannot start service web: oci runtime error: rootfs_linux.go:53: mounting "/mnt/sda1
> /var/lib/docker/aufs/mnt/07b53c0159cf660302c9496ea920e2c0a6572397bb0a23fe4a592260985066f8/etc/nginx/
> nginx.conf" to rootfs "/mnt/sda1/var/lib/docker/aufs/mnt/07b53c0159cf660302c9496ea920e2c0a6572397bb0
> a23fe4a592260985066f8" caused "not a directory"
> 
> ERROR: for terminus  Cannot start service terminus: oci runtime error: exec: "usermap": executable f
> ile not found in $PATH
> 
> ERROR: for appserver  Cannot start service appserver: oci runtime error: exec: "/src/config/scripts/
> php-fpm.sh": stat /src/config/scripts/php-fpm.sh: no such file or directory
> ←[31mERROR←[0m: Encountered errors while bringing up the project.

It looks like this is related to #1666 - which is resolved by setting up Shared Drives.
However, on Windows 7, this option does not appear to exist (presumably because Docker is not natively supported)

It seems possible to do this using the command line also, but I don't understand what the necessary configuration is, or indeed, if this will resolve the issue. How can I resolve this?

Full logs attached
[kbox-log.txt](https://github.com/kalabox/kalabox/files/551570/kbox-log.txt)

**Comment by pirog** [comment]
@tadhgpearson in 2.0.X we set up shared drives for you automatically however we can only share in `C:\Users`. So if you app is not install somewhere in there it is not going to work.

This is noted in the documentation.

**Comment by tadhgpearson** [comment]
Thank - I guess I didn't spot that part. I'll go for a re-install on C - I guess that should fix it!

**Comment by pirog** [comment]
@tadhgpearson assuming that is indeed your issue :)

I think you can actually install kalabox anywhere but you need to make sure you create your app inside of `C:\Users`.

**Comment by tadhgpearson** [comment]
Really? I can't remember how I set it up, but I had it installed on D:\bin and an environment variable related to Kalabox set to D:\bin, and it was putting everything on D.

With a clean re-install, and everything now on C:, it works correctly... until I run out of space on my SSD I guess :grin: 

Thank you very much for your help!

**Comment by pirog** [comment]
@tadhgpearson awesome! if you eventually end up on Win 10 Pro there is a lot more flex on where you can install things and what you can share into kalabox.
