### ISSUE TITLE
Installation fails or hangs on MacOS Sierra 10.12.1

### ISSUE THREAD

**Issue by dholtzman2** [kalabox/kalabox#1686]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Attempted to install 2.01 on iMac (Retina 5K, 27-inch, Late 2014) running MacOS Sierra 10.12.1

Have you previously installed Kalabox? If so, what version?

No

**Tell us about your bug**

Installation either failed with uninformative "Installation Failed" error or stalled indefinitely. (When installation stalled, I could not restart the computer without force quitting installd.)

I attempted every solution found in other issues. Ran uninstaller and restarted between installation attempts. Deleted .docker folder. Ran terminal commands from issue 1609. Re-downloaded installer.

Error messages from install log:
*****
Oct 25 16:20:59 iMac installd[366]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.J4nlTZ/Scripts/io.kalabox.pkg.kalabox.uRbdZA
Oct 25 16:21:03 iMac installd[366]: ./postinstall: Creating CA: /Users/doug/.docker/machine/certs/ca.pem
Oct 25 16:21:04 iMac installd[366]: ./postinstall: Creating client certificate: /Users/doug/.docker/machine/certs/cert.pem
Oct 25 16:21:04 iMac installd[366]: ./postinstall: Running pre-create checks...
Oct 25 16:21:04 iMac installd[366]: ./postinstall: (Kalabox2) Default Boot2Docker ISO is out-of-date, downloading the latest release...
Oct 25 16:21:06 iMac installd[366]: ./postinstall: Error with pre-create check: "Get https://api.github.com/repos/boot2docker/boot2docker/releases/latest: x509: certificate has expired or is not yet valid"
Oct 25 16:21:07 iMac installd[366]: ./postinstall: Host does not exist: "Kalabox2"
Oct 25 16:21:07 iMac installd[366]: ./postinstall: Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
Oct 25 16:21:07 iMac installd[366]: ./postinstall: Host does not exist: "Kalabox2"
Oct 25 16:21:08 --- last message repeated 1 time ---
Oct 25 16:21:08 iMac installd[366]: ./postinstall: TLS configuration is invalid - make sure your DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are set correctly.
Oct 25 16:21:08 iMac installd[366]: ./postinstall: You might need to run `eval "$(docker-machine env default)"`
Oct 25 16:21:08 iMac installd[366]: ./postinstall: Something went wrong installing core Docker images
Oct 25 16:21:08 iMac installd[366]: PackageKit: releasing backupd
Oct 25 16:21:08 iMac installd[366]: PackageKit: allow user idle system sleep
Oct 25 16:21:08 iMac installd[366]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “KalaboxInstaller.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg, PKInstallPackageIdentifier=io.kalabox.pkg.kalabox, NSLocalizedDescription=An error occurred while running scripts from the package “KalaboxInstaller.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cKalaboxInstaller.pkg\U201d.";
	    NSURL = "file://localhost/Volumes/Kalabox/KalaboxInstaller.pkg#kbox.pkg";
	    PKInstallPackageIdentifier = "io.kalabox.pkg.kalabox";
*****

Most recent hang (as opposed to failure) was on:

*****
Oct 25 15:31:56 iMac installd[339]: ./postinstall: (Kalabox2) Waiting for an IP...
*****

Does this bug prevent you from using Kalabox?

Yes.

**Comment by pirog** [comment]
@dholtzman2 looks like there was an issue introduced in macOS 10.12.1. We are in the middle of rolling a hotfix release for this. 
https://github.com/kalabox/kalabox/releases/tag/v2.0.2

**Comment by dholtzman2** [comment]
Unfortunately, the 2.02  installation is hanging for me at this point:
*****
Oct 25 17:23:05 iMac installd[354]: ./postinstall: (Kalabox2) Creating VirtualBox VM...
Oct 25 17:23:05 iMac installd[354]: ./postinstall: (Kalabox2) Creating SSH key...
Oct 25 17:23:40 iMac installd[354]: ./postinstall: (Kalabox2) Starting the VM...
Oct 25 17:23:40 iMac installd[354]: ./postinstall: (Kalabox2) Check network to re-create if needed...
*****
30 minutes so far.

**Comment by pirog** [comment]
sounds like you've probably got another issue then. i assume you've uninstalled the older version first?

**Comment by dholtzman2** [comment]
Yes. I'll force quit the installation and give it another try.

**Comment by pirog** [comment]
@dholtzman2 we are also in the process of rolling the 2.1 release which does not require VirtualBox and has no known issues with the breaking change in 10.12.1. Might be worth just waiting for that.

**Comment by dholtzman2** [comment]
I'll do that. Thanks.
