### ISSUE TITLE
DNS not resolving on *.kbox site on local setup (Ubuntu Desktop)

### ISSUE THREAD

**Issue by wesruv** [kalabox/kalabox#1687]
Tags: Pantheon, Bugfix

Bug Report
==========

What is your Kalabox version and operating system?
v2.0.1 Ubuntu Desktop 16.04

Have you previously installed Kalabox? If so, what version?
No

**Tell us about your bug**

I'm running Ubuntu Desktop 16.04 LTS
I have been using docker for my current projects (don't know if this can cause issues?)

I have:
* Downloaded Kalabox for Ubunto 14.04+
* Installed (seemed to go great)
* Linked Kalabox up to my Pantheon Account
* Synced to a fresh Backdrop CMS Kalabox site
* Seemed to work great!
* Clicked on the icon in the Kalabox app, launched the browser, and I got this error:
![image](https://cloud.githubusercontent.com/assets/5607236/19708819/6f9313cc-9aef-11e6-90ed-d0d2dd60566d.png)

**Comment by pirog** [comment]
@wesruv you might just need to restart your browser. 

To confirm the DNS is set up correctly you should see something like `nameserver 10.13.37.100:53` in `/etc/resolver/kbox`.

**Comment by wesruv** [comment]
Hah, you're very quick @pirog! Thanks that fixed it.

Ran into some new errors, but I think it's issues with Pantheon/BackdropCMS repo.

Thanks so much, digging Kalabox!

**Comment by pirog** [comment]
@wesruv right place at the right time :)

def feel free to post additional issues if you think its kalabox-related!
