### ISSUE TITLE
Too old terminus version prevents using machine token

### ISSUE THREAD

**Issue by ehausen** [kalabox/kalabox#1690]
Kalabox 2.1.0 On OS X Yosemite

If the terminus version is too low (I had 0.9.3) the Panteon machine token does not work and Kalabox GUI does not return error. Kalabox uses terminus behind the scenes so the authentication fails (return error with 404).

Updating terminus to fresh version fixed this. 

Suggestion for a fix: Kalabox should check terminus version and ask to update, if not required version.

**Comment by pirog** [comment]
@ehausen we use our own baked in version of terminus so unless you are using a kalabox app from a long long long time ago this should not be an issue. 

Can you give some more detail on how exactly you arrived here?
