### ISSUE TITLE
Make supplemental installation requirements more obvious on download page

### ISSUE THREAD

**Issue by wesruv** [kalabox/kalabox#1691]
# Bug Report

**Tell us about your setup**

What is your Kalabox version and operating system?
2.1.0 on Win10 x64 Pro

Have you previously installed Kalabox? If so, what version?
No, but I have reinstalled this one as part of debugging.

**Tell us about your bug**
First, this feels like a Docker issue, but I'm not sure where the logs are/how I can see more of what's going on under the covers.

I tried:
- Adding a Backdrop site from Pantheon
- Adding a Wordpress site from Pantheon
- Creating a Wordpress site locally

All three of these give a similar looking bug, but slightly different 'errors' (in one case I think it throws a warning).

Here's a video of me trying to add a Wordpress site from Pantheon:
https://goo.gl/fxiEWs

In each instance: 
- starts off looking nice, says Creating
- Text disappears fairly quickly and the tile looks grayed out
- then after about a minute an error or warning pops in the notifications area
- I let it sit around for about 20min and no change in status
- When I try to close kalabox it tells me it's trying and gives me the force quit button. I waited for ~10 min for the first time and then force quit

In the video I'm pulling a fresh WP site from Pantheon and the error reads:
Pulling repository docker.io/library/redis : Pulling repository docker.io/library/redis

I also got that with my Backdrop instance, and I think a similar, but not the same error when making a site locally.

Any clues on next steps?
Not sure, I tend not to use docker/vm's in Windows anymore, but I'm about to try and train fledgling devs and would prefer to use Kalabox than something more custom that I have to put a lot of work into.

Does this bug prevent you from using Kalabox?
For now, but it did work great for me in Linux! If only I could convince students to switch ... 😛

**Comment by charlotte-bone** [comment]
I have the same setup and am having the same issue too. I can't pull down any site from Pantheon or create a new site.

**Comment by pirog** [comment]
Do either of you guys know if you are behind a corporate firewall or have something weird setup with your DNS? This has been a somewhat recurrent issue on windows but we've had a hard time trying to lock down the cause.

**Comment by pirog** [comment]
Also, have either you tried to pull another site or retried at all?

**Comment by charlotte-bone** [comment]
So I just installed on my home laptop with the same setup as above and I'm still getting the same issue without any firewall. I can't pull any Pantheon site. The first time I pull from a site, it starts trying to pull everything and then after a while I get a warning appear in the warning box:

atest: Pulling from library/mysql
 Digest: sha256:35c9613263b6ecd9ad88e8f3e91fb5b764e623d4e40b0f999fe0f06e9c1d4754
 Status: Downloaded newer image for mysql:latest
 8: Pulling from library/drupal
 Digest: sha256:2ba24f49b886b230515a43b326b7bef3360f0f51360d5a24fdd491a1655e45bd
 Status: Downloaded newer image for drupal:8
 : latest: Pulling from library/mysql
 Digest: sha256:35c9613263b6ecd9ad88e8f3e91fb5b764e623d4e40b0f999fe0f06e9c1d4754
 Status: Downloaded newer image for mysql:latest
 8: Pulling from library/drupal
 Digest: sha256:2ba24f49b886b230515a43b326b7bef3360f0f51360d5a24fdd491a1655e45bd
 Status: Downloaded newer image for drupal:8

It then just freezes and won't proceed any further (I've left it running for a while). I then have to exit and reopen kalabox, the only thing I can then do is delete the site. However if I try to pull the site again I get the grey box shown in the video above, no error message, just grey. It's weird as there is obviously some data left over when destroying the site as it behaves differently depending of if I've tried to pull that site previously or not (it definitely deletes the data in the apps folder though).

I have tried creating new drupal 8, drupal 7, etc sites too and all have the same issue with the warning and then not proceeding any further.

![image](https://cloud.githubusercontent.com/assets/5568828/19820845/1c74ff5a-9d53-11e6-879a-711de313ed75.png)

Thanks,
Charlotte

**Comment by pirog** [comment]
Sad. This seems to happen on a good subset of Windows users and haven't been able to figure out exactly why. @charlotte-bone you are installing the 2.1.0 Kalabox?

If you open up `cmd.exe` and run `docker ps --all` does it list any containers? Can you try to pull something down with `docker pull redis`?

**Comment by charlotte-bone** [comment]
Yes, it seems to create containers for the sites:

![image](https://cloud.githubusercontent.com/assets/5568828/19821396/014aa0ce-9d56-11e6-8e1a-193a248dbbee.png)

It did run docker pull redis ok and downloaded, however it did seem to hang for a while once downloaded and required me to hit the enter key to get the message below.

![image](https://cloud.githubusercontent.com/assets/5568828/19821432/2bb4e36a-9d56-11e6-815f-4f82dfe58ae2.png)

**Comment by pirog** [comment]
huh, that interesting. I wonder if our error handling on the GUI side is just a little too sensitive. 

I would try pulling down a site using the kbox CLI and see if it gives you the same error.

**Comment by charlotte-bone** [comment]
No luck with the CLI either. It seems to fail starting up the containers:

![image](https://cloud.githubusercontent.com/assets/5568828/19821765/1eaf7430-9d58-11e6-9fbe-b170b970b6f8.png)

**Comment by pirog** [comment]
@charlotte-bone ok got it. this is actually more helpful. Did you do the manual set up shared drives step after the install? See: http://docs.kalabox.io/en/stable/users/install/#windows

I think that might be the issue here. If so i would remove all the apps you created already and try it again after you set up the folder sharing.

**Comment by charlotte-bone** [comment]
Brilliant, that does seem to be the issue with pulling. Thank you (and sorry for missing that!). I am however now stuck on 'waiting for site to be ready' now :(

**Comment by wesruv** [comment]
I also didn't share any drive, if that's a necessary step it'd be good to link to the docs from the download page, if they are linked I definitely missed it 😞 

I messed with a bunch of DNS and found that docker (east) seems to not be working, left a tweet https://twitter.com/wesruv/status/792471964048723969. 

After the shared hard drive and connecting to the work VPN (to get a different DNS) pulling down my Pantheon site is working (although it's taking a lot longer than it did in Ubuntu).

Creating a new site is not, but I'm pretty sure that's a docker server issue?

I can't say for sure what fixed pulling my Pantheon site, but it's working 😛 

Thanks for the help!

**Comment by pirog** [comment]
@wesruv yeah we def want to make that more obvious. I think a post install message with a link to relevant docs would be good.

@charlotte-bone it looks like there are a few open issues (with some workarounds) about the "waiting for site to load" screen. i would check those out.
https://github.com/kalabox/kalabox/issues/1688

**Comment by wesruv** [comment]
@pirog I swung back and looked at the download page, there is a link, but I ignored it because it was below the download link.

You folks clearly have excellent designers, but I thought I'd put in my 2 cents from my experience navigating the site:

### Current
![image](https://cloud.githubusercontent.com/assets/5607236/19861863/835786a8-9f64-11e6-9af4-dec00935141f.png)

### Suggestion 1
I think putting the download links in the download column would encourage reading
![image](https://cloud.githubusercontent.com/assets/5607236/19861888/9b49f552-9f64-11e6-83fe-15165ee55cfe.png)

### Suggestion 2
Like the previous, but with some zsazz. Make it more clear that these are steps (and I think it's purty) and make the call to action in two a button to make it more prominent:
![image](https://cloud.githubusercontent.com/assets/5607236/19862041/234324c4-9f65-11e6-8a5d-6721a01d0b8d.png)

Thanks so much for the help!

**Comment by pirog** [comment]
@wesruv i think these are great suggestions and def things we want to get into our 2.1.1 release.

@reynoldsalec how are you feeling about these?

**Comment by pirog** [comment]
@reynoldsalec ive updated our github download entrypoint to contain similar logic

**Comment by wesruv** [comment]
FWIW, for posterity, I fixed my Docker DNS issue where I wasn't able to run `docker hello-world` by:
1. Right clicking the whale in the notification area
2. Go to Settings
3. Go to Network
4. On that page there's a DNS Server setting, I set it to "Fixed" and used 8.8.8.8

Weird that that fixed it, in theory this computer should have been resolving DNS through 8.8.8.8 this whole time, not sure how Docker was getting tripped up.

**Comment by pirog** [comment]
@wesruv thats good to know. 

we are ripping out all our DNS handling on the next version so i'll be curious to see if that was part of the issue here. 

i def think we can add this to the docs for now. along with some other windows suggestions. 

ideally in the future docker for windows gives us a better way to configure some of these things.

**Comment by charlotte-bone** [comment]
@wesruv thank you, that solved my dns issue. It's all working now for me.

@pirog Thank you for helping to sort these issues out, it's a great application :)

**Comment by reynoldsalec** [comment]
Implementing your design @wesruv, do you happen to know what font you used for the numbers?

Thanks for contributing, like the UX suggestions!

**Comment by reynoldsalec** [comment]
@pirog FYI we'll launch these website changes next release.

**Comment by wesruv** [comment]
@reynoldsalec I was using Roboto Sans (Light) because it sort of looked like the font you used.

Cheers!

**Comment by wesruv** [comment]
@reynoldsalec on Windows the download page currently looks like this:
![image](https://cloud.githubusercontent.com/assets/5607236/20248018/6abac3cc-a9a9-11e6-8810-8c2c64286ff5.png)

In the CSS for the numbers I'm seeing:
`font-family: Helvetica Neue;`

Which Windows doesn't have 😛 I removed that rule in the inspector and it looked much more handsome:
![image](https://cloud.githubusercontent.com/assets/5607236/20248027/b14cbcc8-a9a9-11e6-9440-a8d93d2261ae.png)

**Comment by reynoldsalec** [comment]
Thanks @wesruv, just updated the site with that change so all Windows browsers can experience liberty and justice.
