### ISSUE TITLE
PHP.ini and Kalabox (e.g How to increase memory in WordPress?)

### ISSUE THREAD

**Issue by iheijoushin** [kalabox/kalabox#1692]
How on earth does one increase the amount of memory available to PHP within a Kalabox site (e.g edit php.ini)?

In MAMP/XAMPP or a live web server I could simply edit or create a php.ini file in the wp-admin/ directory and specify a larger allocation, however, Kalabox seems to ignore this file when I create it myself even after a restart.

 Next I attempted to manually "upload" the plugins, a method that would also work in MAMP/XAMP/live webserver to bypass a limit imposed by WordPress itself, but any files I manually copy to working directories seem to be ignored by WordPress Admin under Kalabox.

I must admit, I am at a loss. Kalabox does not seem to follow convention for how a normal WordPress installation operates on a real-world server or in other emulators like MAMP/XAMP and after reviewing the Kalabox documentation can find no mention of any alternate methods Kalabox uses to handle PHP memory or how it handles files manually added to working directories.

Steps to reproduce:
- Fresh install of Kalabox 2.1.0
- "Add a New Site" and select WordPress. Wait and launch upon completion.
- Attempt to upload a file/plugin/theme larger than 2MB

Any assistance is sincerely appreciated.

**Comment by pirog** [comment]
@iheijoushin i assume you are using the default Wordpress app and not the one provided by the Pantheon integration?

Just for a little more detail on the architecture and how things work.

We use docker containers for all of our services so in that way we actually ARE providing a pretty real-world on server example of how things work. That said, the "vanilla" apps for Drupal/Wordpress/Backdrop are purposefully very barebones at this point and they rely on some degree of knowledge on how docker and docker-compose work if you are going to try to customize them. 

Can you provide a little more detail about where you are editing your php.ini? and how exactly you are uploading this plugin.

**Comment by iheijoushin** [comment]
Hi Pirog,

Thanks for your reply. That is correct, I created a WordPress install using the "Add Site" function of Kalabox. I reviewed [your documentation](http://php.kalabox.io/en/v2.1/users/config/), but it does not seem to cover increasing memory. It sounds like this is handled by Docker - which I am not at all familiar with. In [reviewing similar reported issues](https://github.com/docker-library/wordpress/issues/10), does not officially support container quota support - but that one can work around that limitation by throwing in arguments in the *.yml files that Docker uses. Docker's way of doing things doesn't look that difficult to understand and I think I am able to likely fix the PHP memory issue.

But this raises other questions, such as after completing a project in Kalabox and running the 'grunt' command, what happens to all the custom arguments for Docker? Are the contents of the *.yml files dumped into corresponding files used by WordPress and a host? Or do they have to be manually created a second time, tested, and then staged?

The php.ini file is typically located in the root directory of the server (www/html) or in a root-level folder like conf or etc. However, WordPress in most situations will pull arguments from a php.ini fie located on the root level of the WordPress install which I unsuccessfully attempted in Kalabox.

Kalabox seems like a great tool, but perhaps is not ideally suited for WordPress projects that are not hosted on Pantheon.

**Comment by pirog** [comment]
@iheijoushin i definitely think a lot these things probably want to be addressed on the docker-image level so i would def encourage you to ping the guys over there.

As you are probably pretty well aware people do all sorts of things on top of "vanilla" WP installs so we give the barebones and its up to the user from there. I sort of agree with you that kalabox is a little difficult for "one size fits all" implementations of specific frameworks eg wordpress and is definitely better suited to emulating PaaS eg Pantheon where we can follow some pretty well defined rules about how everything should be handled eg php.ini. 

Re: `grunt` what does your default grunt command do?

**Comment by iheijoushin** [comment]
Hi pirog,

Thanks for replyin. I'll pop over to Docker for more details on that side of things.
