### ISSUE TITLE
v2.1.0 upgrade issues

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1695]
What is your Kalabox version and operating system?

**Kalabox v2.1.0** 
**Mac OSX 10.11.6**

Have you previously installed Kalabox? If so, what version?
**Kalabox v2.0.1**

I am trying to upgrade to Kalabox v2.1.0 (purge method) but with no luck so far. 
Kalabox and Docker App both installed with no problems (apparently).

The issue arose at the time of trying to install my Pantheon site. Kalabox GUI seemed completely stuck for more than 30 minutes. I tried installing and reinstalling Kalabox a couple of times, uninstalled VirtualBox, update Kitematic ... same result at each new attempt. 
In the end, I decided to let Kalabox try to install my site for an indefinite amount of time. It turned out the process is still going, at least according to the Kalabox GUI and log, but very very slowly. 
It is almost **4 hours and 18 minutes** now, and I am at "Pulling image kalabox/pantheon-appserver" ...

Any idea on what's wrong?

**Comment by pirog** [comment]
@yumyo when you do your initial pull its going to need to fetch a bunch of docker images (usually around 2GB total) so if you have a slow internet connection or are in a coffee shop or something that might explain what you are seeing.

**Comment by yumyo** [comment]
mmm, I am at the office, seeing no connection issues at the moment but hopefully, the process will complete and I'll report my findings back here ...

**Comment by pirog** [comment]
@yumyo yeah thats very weird then. i have moderately fast internet and it takes maybe 20 extra minutes for me to pull the initial images. that said, as long as the images seem to be pulling correctly im not sure what else this could be besides some sort of network or throttling issue.

**Comment by yumyo** [comment]
@pirog at some point I saw an error in the log. It seems like the whole process is dead now. I will let everything running till tomorrow anyway but I made a gist out of the Kalabox log if you want to have a look ... https://gist.github.com/yumyo/e743569581c5f374811dc5655e84848c#file-kalabox-log

**Comment by yumyo** [comment]
Nope, no luck, the process didn't complete. Same trying to create a new site from within Kalabox. Have to switch back to 2.0.1. Really hope we'll find a way to understand where the problem lies.

**Comment by pirog** [comment]
@yumyo this is all really helpful. FWIW i did some more investigation on DNS/docker/windows and similar to your own research i found a lot of results. I think there are a few things we can do to mitigate this a bit but ultimately it looks like there is still a decent amount of work that needs to happen at a lower level to really make this fly on windows like it does on macOS and Linux

**Comment by yumyo** [comment]
@pirog indeed. I am wondering if downloading the needed images separately could be a kind of temporary workaround for the slow download issue. 

About the `502` problem I am opening a new issue as it does not seem related this.

**Comment by pirog** [comment]
@yumyo i think this is going to be significantly better in our 2.1.1 release which we hope to roll out in a few days.
