### ISSUE TITLE
TypeError: Cannot read property 'com.docker.compose.project' of undefined

### ISSUE THREAD

**Issue by alberto56** [kalabox/kalabox#1699]
Newly installed 2.1.0 for Mac, tried to add my Drupal 8 site, getting this error.

Seems to hang at "Creating..." indefinitely.

![screen shot 2016-11-02 at 3 20 41 pm](https://cloud.githubusercontent.com/assets/808265/19943994/4317cc4e-a110-11e6-82c3-242747ad6cbd.png)

**Comment by pirog** [comment]
@alberto56 if you had a previous version of kalabox  you are going to want to make sure you've removed all previous apps and config

**Comment by alberto56** [comment]
Thanks @pirog, any idea where these are?

**Comment by pirog** [comment]
Usually they should all be in `~/.kalabox`. I would uninstall Kalabox, trash that dir and then try to reinstall. 

FWIW, we are going to make some changes in 2.1.1 to clean things up better in the uninstall script.

**Comment by alberto56** [comment]
Thanks, but I'm still having the issue. I did the following:

 * ran the Kalabox uninstall script and uninstalled everything including Docker.
 * ran the following commands:

    rm -rf ~/Library/Preferences/io.nwjs-builder.kalabox.plist 
    rm -rf ~/Library/Saved\ Application\ State/io.nwjs-builder.kalabox.savedState/
    rm -rf ~/.kalabox

 * restarted by computer 
 * tried with two separate Pantheon accounts.

Still getting the same problem. Still trying to figure it out.

**Comment by pirog** [comment]
@alberto56 one thing that you could try to do is uninstall the docker.app manually eg launch it -> preferences -> uninstall. Then launch it again and go through the setup. then try to launch and run kalabox.

**Comment by alberto56** [comment]
Thanks for your time @pirog, I have not had time to try the above, but here is what worked for me:

1. quit Kalabox

2. run these commands in the terminal

    rm -rf ~/Library/Application\ Support/kalabox/
    rm -rf ~/Library/Saved\ Application\ State/io.nwjs-builder.kalabox.savedState/
    rm -rf ~/Library/Preferences/io.nwjs-builder.kalabox.plist 
    rm -rf /Applications/Kalabox.app
    rm -rf ~/.docker/machine/machines/Kalabox2

3. install Kalabox **2.0.2 (not 2.1.0)**

I'll leave this issue open because the above is more of a workaround than a fix.

Some notes:

I am running Docker for Mac 1.12.1
I am running macOs Sierra 10.12.1

**Comment by alberto56** [comment]
FYI, the above does away with the offending error, but by problem may be elsewhere, because the system is still not working: the site is set up completely, but its screenshot is a broken image, and the site just hangs when I bring it up.
![screen shot 2016-11-02 at 5 21 10 pm](https://cloud.githubusercontent.com/assets/808265/19947977/db36b908-a120-11e6-89f4-db4c03db30b1.png)

**Comment by pirog** [comment]
@alberto56 do you already have something running on port 80/443? Kalabox needs these ports free to work.

**Comment by alberto56** [comment]
Thanks @pirog; the port was in use, and 2.0.2 now works for me.

**Comment by pirog** [comment]
@alberto56 good to know. we've made the port requirements more obvious in our documentation. would also def recommend at some point (maybe after we work out some of the kinks) you move to the 2.1.x version as it is significantly better and we are not support 2.0.x anymore

**Comment by kylebehse** [comment]
ERROR: VError: Failed after 5 retries. {"max":5,"backoff":500}: Error stopping container 2da63b5778152f663f237852156d47094103e1594539b50f420a39feba6ed61d.: Cannot read property 'com.docker.compose.project' of undefined 

I've got a similar problem and I'm unable to get kbox to create a project. If I do this command:
$ lsof -Pn -i4
I get:
com.docke 1155 kylebehse   24u  IPv4 0x84ad80083a4c1a29      0t0  TCP 127.0.0.1:8160 (LISTEN)
com.docke 1155 kylebehse   27u  IPv4 0x84ad80083a710c19      0t0  TCP 127.0.0.1:443 (LISTEN)
com.docke 1155 kylebehse   28u  IPv4 0x84ad80083a4c2321      0t0  TCP 127.0.0.1:80 (LISTEN)

So it looks like the ports were open and docker is now using them. Any thoughts? I would love to get this working. I'm on Mac OSX 10.12 and docker is 1.12.1.

**Comment by kylebehse** [comment]
FIXED:
Updated to Docker 1.12.3 and it started working.

**Comment by pirog** [comment]
@kylebehse good to know and we will be rolling with docker 1.12.3 in our 2.1.2 release.
