### ISSUE TITLE
Pantheon authentication expected behavior

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#1700]
This is probably not necessarily dependent on the operating system but when I authenticate with Pantheon, I'm thinking the expected procedure to login should be as follows:
```
1. Prompt for the Pantheon dashboard email address or just use it if it's already stored
2. Look in ~/.terminus/tokens/someuser\@somedomain.com (or other location where the token may be stored already)
3. Use that token to authenticate
4. If that doesn't work, go directly to the Create New Token page in the Pantheon dashboard if they're already logged in
5. If they're not logged in on the Pantheon dashboard, include instructions which explain how to navigate to Create New Token under the Account tab after logging in
6. Explain how the user should copy the new token and paste into the Machine Token text box in Kalabox to complete the authentication process
```

**Comment by pirog** [comment]
@uberhacker this seems pretty close to what we are already doing. What parts of this are different than the current workflow?

**Comment by uberhacker** [comment]
@pirog: I'm using Ubuntu Xenial and I already had a working token but received the Machine Token text box prompt first.  I'm thinking it should prompt for the email address first and use that to authenticate before presenting the Machine Token text box.

**Comment by pirog** [comment]
@uberhacker previously used tokens should show up in the kalabox GUI sidebar and in the CLI. Is that not happening for you?

**Comment by uberhacker** [comment]
Another thing I noticed was the `Get a new one` link under the Machine Token text box opens a blank page in the browser but I suppose this should probably be a separate issue.

**Comment by pirog** [comment]
hmmm im definitely not getting that behavior. Goes right to the pantheon dashboard create machine token page.

**Comment by uberhacker** [comment]
No, not sure where Kalabox stores existing tokens but I already had Terminus installed with a valid token and I'm thinking it should have used that instead of presenting the Machine Token text box.

**Comment by uberhacker** [comment]
I probably should have mentioned this is version 2.1.0.

**Comment by pirog** [comment]
@uberhacker yeah it should and as far as i can tell, at least for me, it does. We don't store them separately, we just read them directly from where terminus puts them.

**Comment by uberhacker** [comment]
Let me see if I can reproduce this behavior and I'll report back.

**Comment by uberhacker** [comment]
OK, the blank page redirect doesn't happen when I click on `Get a new one` but right after I click on `Pantheon` under `ADD ACCOUNT` in the main screen.

**Comment by pirog** [comment]
clicking on pantheon under add account should just open up that machine token sidebar dialog

**Comment by uberhacker** [comment]
I just uninstalled Kalabox and installed it again and now I cannot reproduce.  Weird.

**Comment by uberhacker** [comment]
OK, this behavior is repeatable.  If I click once on the `Get a new one` link, it opens to the Pantheon dashboard login page fine.  If I close the browser, Cancel and then click on `Pantheon` under `ADD ACCOUNT`, that's when it opens the blank browser window.

**Comment by wesruv** [comment]
FWIW, I haven't experienced these issues on Xenial.

I've definitely had it pick up machine tokens from previous installs.

**Comment by uberhacker** [comment]
Hey @wesruv: Thanks for the feedback.  I'm wondering if this is an issue only with fresh installs?  I noticed when I uninstalled, it left behind the ~/.kalabox and ~/.config/kalabox directories.  So technically, this is not a true thorough uninstall.  @pirog: Is there a compelling reason the config stuff is located in two different places?  Maybe the uninstall should prompt and give the option of removing the config directories along with everything else?  Of course, this prompt message should indicate in big bold letters with a warning that you will be removing existing sites along w/ removing the kalabox app.

**Comment by pirog** [comment]
@uberhacker AFAIK we don't put stuff in `~/.config/kalabox` so im not sure what that is all about. What do you actually have in there?

As of 2.1.1 we are removing all of `~/.kalabox` on uninstall.

**Comment by uberhacker** [comment]
@pirog: The `~/.config` directory is created as part of the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).  I didn't know about it myself until recently when I had some trouble with composer.  See the attached file for the contents of `~/.config/kalabox`.
[kalabox_config.txt](https://github.com/kalabox/kalabox/files/586573/kalabox_config.txt)

**Comment by pirog** [comment]
@uberhacker interesting. im guessing your system generates and manages this file so my inclination is not to mess with it.

**Comment by uberhacker** [comment]
@pirog: Well, having the `~/.config/kalabox` residue left over after an uninstall could potentially have unexpected results if Kalabox is ever reinstalled at a later time.  I imagine this is especially suspect if config directories get renamed or switched around on new releases.  It might be worth exploring to include it with the uninstall script.

**Comment by pirog** [comment]
@uberhacker i hear what you are saying but i feel like its a pretty bad idea and somewhat unscalable to be doing cleanup for other programs and its likely going to lead to more problems then it resolves. 

My reading of the XDG docs is that if we change stuff this is reflected in updated config on their end.

**Comment by uberhacker** [comment]
@pirog: You are probably safe just recursively deleting the `~/.config/kalabox` directory and leaving everything else intact.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
