### ISSUE TITLE
Ubuntu kbox CLI create Process - Minor bug

### ISSUE THREAD

**Issue by wesruv** [kalabox/kalabox#1702]
Tag: [bug fix]

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Kalabox 2.1.0 on Ubuntu 16

Have you previously installed Kalabox? If so, what version?
Yes, 2.0.1, and also testing the Windows version of 2.1.0

Give a brief description of what happened, including any error messages that appeared.
Using `kbox create pantheon`, went through the prompts, but on this box I wanted to have a specific name, so on the prompt:
`? What will you call this monster you have created:`

I started typing the name I wanted, messed up, and pressed backspace.

Each time I pressed backspace the current line in the terminal moved up one line and deleted the line above it. Just to see what it'd do I pressed backspace until I got to the top and it kept removing lines.

Not a big deal, just kind of weird, thought I'd report it.

**Comment by wesruv** [comment]
More on this... I'm creating another box to test something, created a local (not tied to Pantheon), on the "What do you want to call it" I typed out a name, then wanted to put a prefix on it, pressed 'Home' and started typing, each key I pressed after pressing Home removed made the current line in the terminal move up one and remove the one above it.

**Comment by pirog** [comment]
@wesruv we use the node module "inquirer" to do our CLI stuff. I'm guessing it would be more useful to post that over there then here.

**Comment by wesruv** [comment]
Ahh, the latest version of inquirer is `1.2.2`, looks like kalabox is using `^0.8.3`
https://github.com/kalabox/kalabox/blob/v2.1/package.json#L60

Don't feel comfortable putting the issue over there given that version difference.

**Comment by pirog** [comment]
Might be worth updating this issue to upgrade our version.
