### ISSUE TITLE
code 502 or ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1703]
What are your Kalabox version and operating system?

Kalabox v2.1.0
Mac OSX 10.11.6

Have you previously installed Kalabox? If so, what version?
Kalabox v2.0.1

Since I installed v2.1.0 I started experiencing unexpected `ERR_CONNECTION_REFUSED` while working or long `Site not yet ready with code 502`. I can't say if there are multiple conditions triggering the error but I discovered that `gulp watch` is definitely triggering it in my setup. 

I tried again to use `kbox npm install` and `kbox gulp` instead but I still get a number of errors with specific modules. Is there any workaround or is now mandatory to use them? The latter will involve going deep in fixing any issue that prevents them from working as expected. 

As an example this is the npm log I get at `kbox npm i`

```
fsevents@1.0.14 install /code/wp-content/themes/my_theme/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/code/wp-content/themes/my_theme/node_modules/fsevents/build'
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make: Leaving directory '/code/wp-content/themes/my_theme/node_modules/fsevents/build'

> gifsicle@3.0.4 postinstall /code/wp-content/themes/my_theme/node_modules/gifsicle
> node lib/install.js

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at /code/wp-content/themes/my_theme/node_modules/bin-check/index.js:22:12
    at /code/wp-content/themes/my_theme/node_modules/executable/index.js:27:4
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.4.20-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@3.0.4 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gifsicle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /code/wp-content/themes/my_theme/npm-debug.log
```

The first thing I can see is the need to update both Node and NPM as both appears to be too old. 

Kalabox versions:
**Node 4.6.1** (currently at 6.9.1)
**Npm 2.15.11** (currently at 4.0.1)

Also, this the list of devDependencies in package.json file. Pretty much the usual front-end stuff:
```
   "asset-builder": "^1.1.0",
    "del": "^1.2.1",
    "gulp": "^3.9.0",
    "browser-sync": "^2.8.2",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-changed": "^1.3.0",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-copy": "0.0.2",
    "gulp-cssnano": "^2.1.0",
    "gulp-download": "0.0.1",
    "gulp-flatten": "0.1.1",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^2.3.0",
    "gulp-jshint": "^1.11.2",
    "gulp-plumber": "^1.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^6.0.0",
    "gulp-sass": "^2.3.1",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.2.0",
    "imagemin-pngcrush": "^4.1.0",
    "jshint-stylish": "^2.0.1",
    "lazypipe": "^1.0.1",
    "merge-stream": "^1.0.0",
    "minimist": "^1.1.3",
    "node-sass": "^3.8.0",
    "run-sequence": "^1.1.2",
    "traverse": "^0.6.6",
    "wiredep": "^2.2.2"
```

Lastly, I am already ignoring my build folder (assets) as well as `node_modules` and `bower_components` in my **kalabox.yml** file:

```
      - Name wp-content/themes/my_theme/bower_components
      - Name wp-content/themes/my_theme/node_modules
      - Name wp-content/themes/my_theme/assets
```

**UPDATE (fix)**

The obvious suspect was the `browser-sync` module that I am not using anyway. Uninstalling it and removing any related reference in my `gulpfile.js` fix the issue with `gulp watch` for me.

**Comment by pirog** [comment]
@yumyo i've been able to use browser-sync successfully so not sure what the issue is there.

It's worth noting that in 2.1.x you no longer should need to ignore any directories like you had to in previous versions.

**Comment by yumyo** [comment]
@pirog I can replicate the behaviour and send you the log if needed. Otherwise, we can close the issue as I got no more problem since then. BTW, once I got it working, v.2.1 is such a massive improvement! Well done!

**Comment by pirog** [comment]
@yumyo thanks! we recognize the installer is a little fickle right now but this is pretty normal as we work out the kinks in the new system.
