### ISSUE TITLE
Failed after 5 retries. {"max":5,"backoff":500}: Bad response from Docker engine

### ISSUE THREAD

**Issue by NicholasEli** [kalabox/kalabox#1705]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

**1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.**
yes

Bug Report
==========

**Tell us about your setup**

**What is your Kalabox version and operating system?**
kbox 2.1.0
osx el captin

**Have you previously installed Kalabox? If so, what version?**
yes - not sure

**Tell us about your bug**
**When trying to import data base manually or trying to pull database from repo**
```
Failed after 5 retries. {"max":5,"backoff":500}: Bad response from Docker engine

VError: Bad response from Docker engine

    at buildVerror (/Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:52:10)
    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/util/shell.js.jx:90:16
    at /Applications/Kalabox.app/Contents/MacOS/bin/node_modules/shelljs/src/exec.js.jx:166:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:17)
    at maybeClose (child_process.js:773:16)
    at Socket.<anonymous> (child_process.js:994:11)
    at Socket.emit (events.js:82:17)
    at Pipe.close (net.js:422:12)

```
**Give a brief description of what happened, including any error messages that appeared.**
**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

> Example: 

> 1. Open Terminal
> 2. Go to directory of project inside .kalabox/apps folder
> 3. kbox start
> 4a. Pull database and code
>4b. Pull code, import database manaully
>5. Get listed error

**Comment by pirog** [comment]
@NicholasEli have you tried rebooting your Docker.app?
