### ISSUE TITLE
kbox git permission 'FETCH_HEAD' broke while using local git

### ISSUE THREAD

**Issue by spazzwig** [kalabox/kalabox#1706]
This resembles issue #1615, but the permission of .git/FETCH_HEAD broke instead.

Using Kalabox v2.1.0 on OS X El Capitan (10.11.6).

I created a new Pantheon app from dev env and made some local changes, then committed and pushed from local git. 

Noticed that kbox git was out of sync. While the local repo was clean, the kbox repo was stuck in a mixed state -- none of the local commits recorded, all the modifications tracked, some staged and some not.

Proceeded to reset the kbox git to its HEAD and then try updating from remote, received this permission error:
`error: cannot open .git/FETCH_HEAD: Permission denied`

I resolved things by resetting the kbox git to its HEAD, then repaired the permissions via `kbox . chown -R [user]:[group] code/.git` which allowed me to fetch the changes I had pushed from local git. FETCH_HEAD was the only file I saw with incorrect perms.

Based on the state I found the kbox git repo in -- the staged vs unstaged changes matched the state just prior to the first local commit -- it looks like the permission broke and things got out of sync when I created that first local commit. If I can find some time I will try recreating from scratch to determine steps to reproduce.

This was all over the CLI, GUI not launched.

**Comment by pirog** [comment]
@spazzwig weird, i thought we had just fixed something like this but I GUESS NOT.

**Comment by spazzwig** [comment]
Yeah, similar but different. I'll try finding some time today to reproduce and provide steps. 

It could have been related to a fault in unison; after fixing the perms I noticed that file sync had died entirely (resolved by restarting the app).

**Comment by amklose** [comment]
I think this was the issue I had in #1634

**Comment by pirog** [comment]
@amklose yeah same here although we fixed and tested that so im wondering what has changed here.

**Comment by defaria** [comment]
I am on Sierra 10.12.1

Myself and another co-worker is also having this issue. When pulling or pushing we are getting:

error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by pirog** [comment]
Good to know. We are hoping to resolve this as part of our 2.1.4 release. In the meantime i'd try some of the workarounds suggested above.

**Comment by amklose** [comment]
@pirog In the meantime while you're working on v2.1.4, is there a way that you would suggest to manually reset the git permissions so I can sync databases using `kbox pull` without seeing those git errors?

**Comment by pirog** [comment]
You can use `kbox . <cmd>` to run arbitrary commands inside the container
http://docs.kalabox.io/en/v2.1/users/cli/#cmd62

should be able to set permissions to what they need to be with that

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
