### ISSUE TITLE
Cleanup during Kbox Start destroys non-Kalabox containers

### ISSUE THREAD

**Issue by nikstoltzfus** [kalabox/kalabox#1708]
I'm guessing this was by design originally when Kalabox ran in its own Docker machine, but now that I'm using Docker for Mac, I've noticed this occurrence repeatedly — even after completely uninstalling Docker and Kalabox and reinstalling both. 

**Steps to reproduce:**

1. 'build', 'up -d', and 'start' non-Kalabox containers [I'm using docker-compose w/ another project]. 
2. 'docker ps' shows the the containers running.
3. 'kbox start' a Kalabox app
4. 'docker ps' doesn't show the containers running and 'docker ps -a' shows they've been completely destroyed. 

I tried to look through the source for a solution, but I'm not familiar enough w/ nodejs syntax to follow what's going on beyond the main 'start' function. 

My guess it that this is due to the logic in [app.js lines 551 - 571](https://github.com/kalabox/kalabox/blob/v2.1/lib/app.js#L551), which appears to grab the list of running containers and the list of Kalabox apps, filter out all the containers used by apps and destroy the rest. That much I think I get, but I'm not sure how to go about filtering out non-Kalabox apps too. 

Happy to do some legwork to guess and check, but I'd need some help building the app from the source. 

**My setup**

What is your Kalabox version and operating system?

- Mac OS 10.12.1 (16B2555)
- Kalabox 2.1.0
- Docker 1.12.1

Have you previously installed Kalabox? If so, what version?

Yes, several beta version and v2.0, but completely wiped all of them prior to upgrading to 2.1 and have wiped and reinstalled 2.1 a couple times.

**Comment by pirog** [comment]
@nikstoltzfus ick not good. Def very glad you pointed this out. Don't think i'll be able to get to this for a few days but def want to resolve it soon.

Have you checkout out the contrib guide in the docs on running via source? http://docs.kalabox.io/en/v2.1/developers/contrib/?

Let me know if that works. I'm happy to help walk you through the setup if needed.

**Comment by nikstoltzfus** [comment]
I had cloned the source repo, but my unfamiliarity w/ npm and grunt was holding me back. I think I landed on an outdated version of the contrib documentation page last night and was stuck. Looking through your linked page, I was able to setup the symlink to the source and successfully run 'kbox.dev'. 

I'll poke around at the app logic and see if I can figure out something that works for me and — if the stars majestically align — hopefully abstract it to resolve.

**Comment by pirog** [comment]
@nikstoltzfus would be awesome. at the least let us know any interesting things you discover.

**Comment by nikstoltzfus** [comment]
So commenting out lines  [app.js lines 570 - 572](https://github.com/kalabox/kalabox/blob/v2.1/lib/app.js#L570) does what I expected it to do and eliminates the destruction of my non-Kalabox containers, but I'm guessing it also prevents Kalabox from doing what it should normally be doing in terms of cleaning up any unused Kalabox containers.

From this point, I'm not sure what the best route is towards a fix. I'm guessing that there's good reason Kalabox is destroying non-app containers, but I'm also guessing that it was safer to do when everything was encapsulated in a docker-machine specific to Kalabox. 

Do Kbox app containers have a tag or some other shared identifier that could be used to check whether they should be destroyed. If so, a possible revised algorithm for cleanup:

* Get a list of all apps
* Filter out containers that are associated w/ a current app or don't have a tag identifying it as a Kalabox container
* Continue w/ stopping and destruction the filtered list that now doesn't include non-Kalabox containers.

If you think that would work, some pointers towards identifying the app containers using node would probably be helpful. I'm trying to bolster my node familiarity [coming from a pure JS background it's not as bad as I thought] but I'm still in the dark on the Promise concepts and other node specific features.

**Comment by pirog** [comment]
@nikstoltzfus so right now we do make some limited use of tagging via docker compose so we might be able to make use of that. Although i think its more likely we will want to add some generic "kalabox" tag for ALL our containers so we can easily sort out other containers. 

I think the best bet re: node and promises is to scope out the bluebird and lodash documentation since those encapsulate a lot of how we do things.

**Comment by pirog** [comment]
@nikstoltzfus im OTS on this issue right now. you have a good compose file i can use to replicate this?

**Comment by pirog** [comment]
OK using https://github.com/RobLoach/docker-compose-drupal i can def replicate this.

**Comment by pirog** [comment]
@nikstoltzfus i think this should get us back on the right path
https://github.com/kalabox/kalabox/pull/1719

**Comment by nikstoltzfus** [comment]
@pirog awesome! Sorry for the slow response. I was out and about all weekend and offline most of it. I saw the latest release includes the fix so I'm downloading and testing today.

Thanks!

**Comment by pirog** [comment]
No worries and def let me know if it resolves your issue.
