### ISSUE TITLE
Do PORT discovery and throw an error if we dont have the ports we need. Remove this from docs when appropriate.

### ISSUE THREAD

**Issue by KenWatts** [kalabox/kalabox#1710]
The documentation reads:
"Verify that your machine is not currently using ports 80, 443 and 8160."

Does "currently" mean "at the time of installation" or "during the period of using Kalabox"?

The reason for my question is that, as I've dug further into the port usage on my Windows 10 machine, I've discovered that there are a lot of programs and services using those ports, and some of those seem to be part of the windows system. 

And I've only been able to discover how to change the port they're using for a few of those.

**Comment by pirog** [comment]
@KenWatts it actually means that you can't run Kalabox while these ports are used by something else. You actually **should** be able to install it even if those ports are used. If you are running a Windows webserver or something else like WAMP then one of those things are likely binding to port 80 which means that we cannot.

I've amended the title of this issue to more accurately reflect what we should do on our end to detect this.

**Comment by pirog** [comment]
Not sure how this works on Windows but on macOS it seems like Kalabox is able to "take over" the ports it needs so i'm not 100% sure if we actually need to do this. Going to kick this to the future

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
