### ISSUE TITLE
CLI - kbox create name validation fails if name includes hyphen

### ISSUE THREAD

**Issue by amklose** [kalabox/kalabox#1711]
Bug Report
==========

Kalabox v2.1.1
macOS Sierra 10.12.1

I get stuck when trying to pull a site from Pantheon using `kbox create pantheon`. While trying to name the monster I have created, any value I enter **THAT INCLUDES A HYPHEN** produces the message `>> Please enter a valid value`, even if the default suggested name includes a hyphen.

**Steps to reproduce**

- run `kbox create pantheon`
- choose your Pantheon account
- chose a site
- choose an environment
- try naming the monster with a hyphen in the name

This was not an issue in previous versions of Kalabox and does not appear to be an issue if I pull the site using the GUI.

**Comment by Senpai** [comment]
Confirmed. Where one used to be able to just hit 'enter' and accept the Pantheon-provided site name, one now has to re-enter the Kalabox app's name without-hyphens.

And yes, I just used three hyphens in the preceding sentence.

**Comment by pirog** [comment]
Im guessing a lower level node dep changed here. This is def a regression though. Should be easy enough to fix.

**Comment by pirog** [comment]
This should end up in the latest dev and 2.1.2
