### ISSUE TITLE
Kalabox 2.1.1 wont uninstall

### ISSUE THREAD

**Issue by mbader** [kalabox/kalabox#1715]
Bug Report
==========

**Tell us about your setup**
What is your Kalabox version and operating system?
Kalabox 2.1.1
Mac OS 10.10.5

Have you previously installed Kalabox? If so, what version?
Yes - 2.0.0

**Tell us about your bug**
Deleted Apps and did a full uninstall of 2.0 in order to upgrade to 2.1.1
Installed 2.1.1, pulled a Pantheon App and the pull froze up on "Pulling Database". Waited 30 minutes and finally had to force close. Reopened and the app appeared but was badly broken. Deleted the app and tried to pull 2 more times with same result. Deleted the app and did a full uninstall and reinstall of 2.1.1, including removing Docker this time. Now when I try to pull my Pantheon app, I get a message "Error: Looks like an app already exists at /Users/mike/Kalabox/mega-tracks". Looked in the folder and there is no app there. Out of ideas and Kalabox is completely useless now.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Followed all uninstall documentation step by step

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
@mbader would try pulling the app again and giving it a different name. There was a regression in this latest release where hyphens in names are a bit wonky.

**Comment by mbader** [comment]
@pirog thanks - I was able to initiate a pull again by renaming the app as you suggested, however, it still hangs on the "Pulling Database" step (its been stuck there for over 30 minutes with no change)

**Comment by pirog** [comment]
@mbader how big is your database? If its large then 30 minutes is certainly a reasonable amount of time to grab it.

**Comment by mbader** [comment]
@pirog Its 1.3M. I didn't have any problems pulling/pushing updates prior to updating to 2.1.1. Is there a way to regress to an older version of Kalabox? And I also noticed that I get prompted to remove "Docker" when uninstalling; should I be removing that as well. I have no idea what that provides

**Comment by pirog** [comment]
@mbader you can definitely uninstall the new version and install the old version. It might also be worth looking through our docs. There is a good section on troubleshooting that might help you isolate your issue.

**Comment by mbader** [comment]
@pirog I tried to do a command line pull to see progress, and everything seems to work correctly until it tries to get the DB, where it will hang indefinitely after it runs the MYSQL command. Once you kill that query it moves on and pulls the files without issue.

**Comment by pirog** [comment]
@mbader it might be worth pinging pantheon on that specific site to see if there is anything weird about the mysql connection info we are grabbing via terminus.

**Comment by mbader** [comment]
@pirog Just submitted a ticket with Pantheon; will let you know as soon as I hear back. Thanks!

**Comment by pirog** [comment]
@mbader awesome! def curious to see what the deal is.

**Comment by mbader** [comment]
@pirog Found the dmg file for my 2.0.0 installation, uninstalled 2.1.1 along with Docker, and reinstalled 2.0.0 and was able to build the app with no problem. 

Prior to that we tried running import/table drop commands directly from the kbox mysql shell and none of them would ever complete, definitely seemed to be a conflict/issue going on there but no idea why. Im happy just having my dev environments back up, so will probably just wait another version or so and try to upgrade again. 

Thanks for your help!

**Comment by pirog** [comment]
@mbader hmmm yeah my best guess there then is probably a bug in the Docker for Mac beta which powers the backend now. I'd keep an eye out for our next version that updates that piece of Kalabox.

**Comment by pirog** [comment]
@mbader we will be upgrading to the latest Docker in the 2.1.2 as an FYI. Would be curious if that helps your situation at all.
