### ISSUE TITLE
What version is installed?

### ISSUE THREAD

**Issue by arlinsandbulte** [kalabox/kalabox#1716]
Is there any indication of what version of Kalabox is installed (Windows)
I could not find "About" or "Version Info" in the launcher window.
I could not find any version info in the readme files.
I finally found a version number in Add/Remove Programs in Control Panel.

Finding the currently installed Kalabox version should not be so hard.

**Comment by pirog** [comment]
@arlinsandbulte reading the documentation and seeing that there is a `kbox version` command should not be so hard.
