### ISSUE TITLE
Permission denied for file_put_contents() after manually editing Feature file. File syncing issue.

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#1717]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox 2.1.1 on OS X 10.11.6

Have you previously installed Kalabox? If so, what version?

Yes, all of them. Purge uninstalled before 2.1.1

**Tell us about your bug**

1. Manually edited a features .info file and a .feature.inc file
2. Tried to add new components to the feature from Features UI.
3. Got permission denied error:

`Permission denied in features_export_build_form_submit()` (Didn't note the full error, sorry)  
- Assuming this wraps file_put_contents()

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

1. Start up a D7 Kalabox site with features installed and a feature enabled
2. Manually modify any of the feature's files
3. Go to Features UI, recreate the feature, add a component that will add to/overwrite one of the files you edited (second thought, just edit the .info file!)
4. Experience the error.
5. Curse (optional)
6. Handball fix to colleague

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

**Does this bug prevent you from using Kalabox?**

No, figured out a workaround by removing the files I edited.  The site was then able to rewrite them without permissions issues.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
