### ISSUE TITLE
Views UI not loading

### ISSUE THREAD

**Issue by ultimike** [kalabox/kalabox#1722]
Oh Kalabox, I so much want to love you, but you keep pushing me away...

Bug Report
==========

What is your Kalabox version and operating system?

2.1.0 on MacOS Sierra, Docker for Mac 1.12.3.

Have you previously installed Kalabox? If so, what version?

Yes, beta 1 (if I recall correctly), but I completely removed it prior to installing 2.1.0.

**Tell us about your bug**

I pulled down an existing site from Pantheon, got the site up-and-running on my local. When I go to create a new view, no matter what I do, the main Views UI won't load. I get a 500 error (nothing loads) and my normally silent MacBook Air sounds like it's about to hover like a DJI Phantom 4. The Views UI loads normally on Pantheon dev/test/live.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

See above. Nothing tricky about it.

**Tell us more**

Does this bug prevent you from using Kalabox?

Pretty much, yes. At this point, I'm need to use an alternate local AMP stack to work on this site. :(

**Comment by pirog** [comment]
@ultimike if you want to share this site with me im more than happy to look at it but we've got lots of developers (including us) who are using the Views UI every day :( 

Are you getting this 500 error on other sites or on other pages?

**Comment by ultimike** [comment]
I'll have to ask the client. It's a site build that is in progress that I'm just started working on. I'll let you know.

thanks,  
-mike

**Comment by pirog** [comment]
@ultimike sounds good. a good test to do on your end is to just try the views ui out on another site. If its breaking across multiple sites then there is a good chance its Kalabox. If its only breaking on one site there is a good chance its something in the code specific to that app.

**Comment by ultimike** [comment]
@pirog Yeah, you're right - the Views UI loads fine on other local Kalabox sites. 

I still think it is Kalabox-related though, because the UI loads fine on Pantheon dev/test/live as well as in a different local AMP stack (with the same codebase and DB). 

Any other troubleshooting ideas?

My client is fine with you checking out the site (if that still makes sense), but you'll need to get me your email address (contact me via drupal.org/u/ultimike).

thanks,  
-mike

**Comment by pirog** [comment]
@ultimike yeah i think seeing the site and being able to replicate it myself is probably the most helpful for figuring out what the deal is.

mike at kalabox dot io

**Comment by ultimike** [comment]
@pirog - cool - you should be getting the invite shortly.

thanks,
-mike

**Comment by pirog** [comment]
@ultimike following up here. not sure i ever got an invite from you? can you confirm/deny?

**Comment by ultimike** [comment]
Yep - I sent you an invite - the project name is "Pantheon Think College".

thanks,
-mike

**Comment by pirog** [comment]
@ultimike ok i see it now. must have just missed the invite in the inbox.

**Comment by pirog** [comment]
@ultimike (this is using the `dev` branch, not the `develop`) branch but i am able to load the `views_ui`

![screen shot 2016-11-25 at 8 29 57 am](https://cloud.githubusercontent.com/assets/713424/20631049/7773c9a8-b2e9-11e6-9c53-c6f037e82b8e.png)

:/

**Comment by ultimike** [comment]
Does this include the add/edit page for a view?

Mike

**Comment by pirog** [comment]
Yes. Can post screenshots of that too if you want.

**Comment by ultimike** [comment]
Seems to be working now after a re-pull.
