### ISSUE TITLE
SSL protocol / record too long errors

### ISSUE THREAD

**Issue by dalin-** [kalabox/kalabox#1723]
Bug Report
==========

**Tell us about your setup**

2.1.1 on OSX 10.11
I've used, most versions since 0.8ish.  Faithfully purging on each upgrade.

**Tell us about your bug**

I already have 4 or 5 Pantheon sites running on 2.1.1 without issue.  Today I tried to add another one.  

If I attempt to access the edge container I get a generic HTTPS error:

> Secure Connection Failed
> The connection to localhost:32797 was interrupted while the page was loading.
> The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

If I attempt to directly access the web container I get a more useful error:

> Secure Connection Failed
> An error occurred during a connection to localhost:32795. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

Or in Chrome:

> This site can’t provide a secure connection
> localhost sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

I tried `kbox rebuild` but that didn't help.

**Tell us more**

Does this bug prevent you from using Kalabox?
Yes for this site.  But others work without issue.

**Comment by dalin-** [comment]
Nevermind.  This can be closed.

This is a result of trying to access the proxied port 80 over HTTPS.  If I instead go to the proxied 443 port over HTTPS everything works out fine.

**Comment by pirog** [comment]
lol yeah 80 over HTTPS is generally going to be like :suspect:
