### ISSUE TITLE
Consider changing Domain URL in WP databse when pushing site from local to Pantheon

### ISSUE THREAD

**Issue by wernerglinka** [kalabox/kalabox#1724]
I am using Kalabox/Pantheon to develop Wordpress sites. Kalabox is a huge improvements when compared with my previous dev setups. However, there is an inherent workflow problem with Wordpress in that the site domain URL is hard coded into the database. That results in the following workflow:

1. Push site from Kalabox to Pantheon
2. Make a database file with changed domain URL (e.g. https://wordpress.org/plugins/search-and-replace/)
3. Import said database to Pantheon

Steps 2 and 3 could be eliminated by adding search and replace functionality into the Kalabox Push. The UI is good as it is. One could just add a field in the Push modal window like **Change Domain URL to:** and then upon Submit change the URL before pushing the database to Pantheon.

**Comment by pirog** [comment]
@wernerglinka, this sounds like something we should consider doing. The panthoen docs and UX around this seem like a good starting point
https://pantheon.io/docs/wordpress-broken-links/

**Comment by wernerglinka** [comment]
This should really go both ways, push and pull. This would be the missing link to the perfect WP dev setup :-)

**Comment by pirog** [comment]
Did you close this by accident?

**Comment by wernerglinka** [comment]
Sorry I must have. Shoud I reopen?

**Comment by pirog** [comment]
Yup!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
