### ISSUE TITLE
Newly Conflicts with XAMPP on Port 80

### ISSUE THREAD

**Issue by Coufu** [kalabox/kalabox#1725]
I used to be able to use both XAMPP and Kalabox at the same time. I had my other sites and vhosts on XAMPP and then I had my test sites and Pantheon sites on Kalabox. They both used to work in harmony.

Now Kalabox shows "Error 400: Lost in the clouds?" whenever I try to access a local vhost that runs on XAMPP, even though the domain names are not conflicting.

**Comment by pirog** [comment]
Yup. You can't run these simultaneously anymore however it's fairly trivial
to turn kalabox or XAMPP off.

This is unlikely to change until the new docker provides an easy way for us
to better isolate our things.

**Comment by Coufu** [comment]
Ahhhhh okay. I was just playing around with it and found out that I did have to toggle them. Okay, not the answer I was hoping for because I work on multiple sites at a time. If only Kalabox supported an easier way to create a blank site (no CMS) with blank database, I wouldn't have to worry about XAMPP anymore.

**Comment by Coufu** [comment]
P.S. Thanks for your response!

**Comment by pirog** [comment]
It's in the roadmap!

**Comment by Coufu** [comment]
Sorry, I'm new here :(

**Comment by wildkatana** [comment]
I suspect this may be conflicting with Laravel Valet in the same way...

**Comment by wildkatana** [comment]
How do we disable one or the other manually?

**Comment by pirog** [comment]
If you close the Kalabox GUI or run `kbox poweroff` it will spin down all the kalabox containers. For Laravel vallet i'm guessing they have a similar command to spin down whatever service they run on port 80.
