### ISSUE TITLE
Creating ssh keys for remote servers and setting up aliases.drushrc.php - Documentation

### ISSUE THREAD

**Issue by shawnmmatthews** [kalabox/kalabox#1726]
Good morning,

On 2.1.0-rc.2 on Macos Sierra and 2.0.1 on Windows 7 I can't seem to locate any documentation regarding setting up ssh keys for remote servers.

I don't seem to see a .ssh folder in either with .kalabox folder or in my individual site installs. The only place I'm seeing an id_rsa key pair is in a folder at .kalabox/pantheon/keys. I'm trying to use an ssh key to rysnc/sqlsync from a remote host, and can't seem to find documentation. I have added an aliases.drushrc.php inside of the drush config folder, and it is correctly seeing the alias using "kbox drush site-alias", but no matter what I set under the 'ssh-options' I keep getting a "Host key verification failed".

Questions
1) Do I need to generate a new key? I added the pantheon public key to my list of accepted keys on the server.

2) Where should keys be stored? In the site specific folder, or in .kalabox?

3) Will ssh-options pick these up when using something like "kbox drush @example cc all". 

4) Does anything specific need to be done to the path on 'ssh-options' inside of aliases.drushrc.php because of this running in Docker?

Please let me know if I can provide any additional info!

Thanks for the help.
Shawn

**Comment by UltraBob** [comment]
What a coincidence, I was just trying to figure out a similar thing for allowing drush make to pull my private modules from a private git repo.

**Comment by UltraBob** [comment]
The answer may very well be there, but I didn't figure it out.

**Comment by pirog** [comment]
@shawnmmatthews @UltraBob i would think posting the public key from `~/.kalabox/pantheon/keys` to the remote server would be enough. That said you might be getting a failure on `StrictHostKeyChecking` which we set up specifically to whitelist pantheon only
https://github.com/kalabox/kalabox-app-pantheon/blob/v2.1/app/config/scripts/usermap.sh#L23
https://github.com/kalabox/kalabox-app-pantheon/blob/v2.1/app/config/scripts/usermap-cli.sh#L16

**Comment by shawnmmatthews** [comment]
@pirog Thanks for getting back to us, sorry for my delayed response. I got side tracked on another project. I just tried uploading the pantheon pub key to my remote server and it returned a 
```
Host key verification failed
```
when trying to run 
```
kbox drush @site-alias cc all
```
 just as a test. (I can confirm my alias file works fine locally.)

Eventually I'm hoping to use rsync and sql-sync to start working on some of our legacy sites.
Everything works great when using Pantheon, but I'd really love to use Kalabox for local dev on our normal non Pantheon racks.

Thanks again for all the help. I really appreciate it.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
