### ISSUE TITLE
Drupal 6, files folder coming across as site not sites

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1727]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

2.1.1 && Ubuntu 16.04

Have you previously installed Kalabox? If so, what version?

Yes all the versions.

**Tell us about your bug**

When I download a Drupal 6 site, the file folder in the DB is coming across as site not sites.  

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

Create the site
Look at the filepath in the files table in the DB.

Could better documentation have prevented this issue? if so what should we change?

N/A

Does this bug prevent you from using Kalabox?

No

**Comment by pirog** [comment]
Can def confirm this.
