### ISSUE TITLE
Document how to disable all caching related services

### ISSUE THREAD

**Issue by mccrodp** [kalabox/kalabox#1730]
Documentation Request
===========================

I am developing on a Pantheon site with the following containers/services:
data, db, appserver, edge, redis, solr, web

I am writing a module and the page callback defined in `hook_menu` is getting cached even though I have commented out and disabled the redis module and config manually. Drupal caches are also off.

What is the recommended method of developing modules when using environments pulled down off Pantheon for example? How can you easily turn off these services responsible for caching?

To get my code changes recognised I've to disable, uninstall and reinstall the module or enable/reenable the whole environment which is not development friendly. Any recommended solutions welcome...

In the case of redis there is an environment variable we use conditionally, this in turn is set via the Kalabox yml / Docker env variable: `$KALABOX_APP_X_X_ENVIRONMENT`. Where is this coming from? 

Just for context, I'm trying to allow redis config to be conditional, but cannot use `module_exists()` in the settings.php as the site is not bootstrapped yet - this part is more a Drupal specific question though, so please feel free to ignore that part if unsure.

Thank you!

**Comment by deborah-ufw** [comment]
I also have been unable to thoroughly disable cache. Have to use the Drupal 8 "clear caches" button even after following different steps for configuring Drupal 8 local dev (in Kbox) found around the web.

**Comment by pirog** [comment]
We do not do any special caching on Kalabox. Any settings you have set for Pantheon will pass through to what you have locally.

What would you like to see here that is outside of the normal recommendations expressed in the Drupal documentation for local dev?

@mccrodp i would check out the documentation on `hook_menu` https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7.x
It does its own set of special things re: caching

Further, we document the ENVVARS we set for Pantheon apps here
http://pantheon.kalabox.io/en/v2.1/users/services/#appserver
Would be pretty easy to turn redis off if `PANTHEON_ENVIRONMENT === kalabox`.

@deborah-ufw 
If you have to manually clear the cache to get changes to show then it necessarily means you have some sort of caching enabled.

**Comment by mccrodp** [comment]
@pirog, thanks for your reply and the advise for checking `PANTHEON_ENVIRONMENT === kalabox`, it may come in useful. Just need a mechanism to check for enabled/disabled status of modules before bootstrap in settings.php now 😛 Will keep researching that.

Actually, my bad explanation re : `hook_menu` code, what I mean is a `drupal_get_form` callback is used and that whole function is cached, which is the function I am editing and not seeing changes in the site served via Kalabox managed infra.

To put it bluntly, I like the way Kalabox sets up an replicates the exact environment, but if it is that involved to disable caching related services, which may include - data, db, appserver, edge, redis, solr, web, then the appeal for me using Kalabox lessens, it is just an extra layer getting in the way of development.

It took me a long while to disable redis successfully using the custom kalabox yaml and related config, to make a non breaking change to exclude redis. I'm not even sure what some of those other services I listed above are. 

It is great that we have the exact environment replicated if I need to debug something, but for module development / testing module updates, it just gets in the way at the moment. So, this is more a feature request issue to have a UI that would update this Kalabox config and turn off these currently unnecessary services.

Thanks for your help and suggestion.

**Comment by pirog** [comment]
@mccrodp like i said we dont do any caching directly on our end, we are only emulating PaaS environments locally so in the pantheon case redis is not used unless you've enabled it yourself, which it seems like you did.

**Comment by mccrodp** [comment]
@pirog yep, I understand that, but I'm talking about ease of disabling whole services / containers in Kalabox.

**Comment by pirog** [comment]
@mccrodp we don't have an easy way to do that because we aren't forcing you to use any of those services. eg You can have the redis or solr services running but if you dont set up drupal to use them then it doesnt matter.

What you probably want to do is to ONLY use redis in the environments that make sense (on pantheon presumably that would be live and test) and have it off on dev and kalabox. If you don't do this you are probably going to experience more dev pain than on Kalabox eg you won't see changes you need reflected on dev.

**Comment by pirog** [comment]
FWIW
https://kalamuna.atlassian.net/wiki/display/KALA/Redis+cache+configuration+on+Pantheon

**Comment by mccrodp** [comment]
@pirog - ok, no problem, just wondering if it would be something that might get onto your raodmap.

Appreciate the suggestion here, makes a lot of sense. I will mention it in here to admins on this project re: configuring redis, etc., see if we can make this change.

>ONLY use redis in the environments that make sense (on pantheon presumably that would be live and test) and have it off on dev and kalabox.

Thank you!

**Comment by pirog** [comment]
@mccrodp at some point we want to have a "build your own kalabox" sort of feature where you can mix and match the services you want. this might be something better for your specific and preferred dev workflow. 

for the PaaS integrations (aka just Pantheon for now) its def VERY important we provide an extension of their environments. it should feel like you've cloned their entire DEV env to your local.

**Comment by pirog** [comment]
@mccrodp @deborah-ufw this is not exactly the same as this issue but we are going to provide some documentation with some examples of local settings.php config you might want to consider to turn some obvious things off like css aggregation, drupal caching etc

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
