### ISSUE TITLE
Function not implemented (38)

### ISSUE THREAD

**Issue by defaria** [kalabox/kalabox#1731]
Using Kalabox 2.1.2
Mac OS Sierra 10.12.1

Everything was working fine until yesterday, I pushed via the UI and noticed that not all files were making to the Pantheon dev env. So I pushed via the terminal

kbox projectName push

I get the following error when trying to push the file and db

```
rsync: symlink "/srv/bindings/7ab42f855c9b4717b168360f0f5461d2/files/media" -> "/media" failed: Function not implemented (38)

sent 3,417 bytes  received 145 bytes  474.93 bytes/sec
total size is 14,936,418  speedup is 4,193.27
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

```

This seems to happen after "pushing files" is echoed in the terminal.
I have tried restarting Kalabox, the computer, and also switching from git to sftp to git in pantheon. I don't recall changing any settings, at least not on purpose.

Any ideas what's going on?

**Comment by pirog** [comment]
@defaria are you still getting this? i tried to do a pull/push on our test WordPress site and wasn't able to replicate. 

Pantheon had some downtime that might have been responsible for this.

**Comment by defaria** [comment]
Seems to have gone away on it's own. Might have been a pantheon issue as you mentioned.

**Comment by pirog** [comment]
I suspect that to be the case. Going to close this out for now.

**Comment by shawnmmatthews** [comment]
Running 2.1.0 rc (time to upgrade :))
Sierra 10.12.1

Just ran into this. Any idea if it's on Pantheon's end?

rsync: symlink "/srv/bindings/27516ceae33c47d3b2dd7a2f0eb2974e/files/media" -> "/media" failed: Function not implemented (38)

**Comment by amklose** [comment]
I'm also having this issue when pushing to a multidev. I don't think Pantheon is having any downtime currently.
