### ISSUE TITLE
unable to log in as admin on Kbox Drupal 8 site pulled from Pantheon

### ISSUE THREAD

**Issue by deborah-ufw** [kalabox/kalabox#1732]
Bug Report
==========

Setup: Max OS Sierra 10.12.1

Kalabox Version 2.1.2 (2.1.2) fresh install, no previous install

- Connected Kalabox to Pantheon account with Pantheon username, pw
- Used the Kalabox button to generate machine token
- Pulled Pantheon Drupal 8 site
   -- set up for SFTP
- Ran the site in Kbox
- initial state of the pulled site is that no one is logged in (can not access admin features)
- logged in as myself with my Drupal site credentials as set up in Pantheon

Login fails. Failed 5 times, then the Kbox site blocked me.

I am blocked to do local dev on the Kbox site.

**Comment by deborah-ufw** [comment]
Extra information - initially I had a Drupal 8 site that unexpectedly broke (a Drupal issue, not KBox). I had to delete the site on Pantheon and start over. This issue may have had to do with the fact that it was a 2nd instance of Drupal - something may have been cached.

**Comment by pirog** [comment]
@deborah-ufw we pull down the DB "as is" so your creds should be the same in both places. Keep in mind that we pull the DB from the DEV environment so you will want to use the creds you have there, not on the live site. You also can try to login via `kbox drush uli`
