### ISSUE TITLE
Incorrect Database Encoding when importing from Pantheon

### ISSUE THREAD

**Issue by justinffs** [kalabox/kalabox#1734]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========
**Tell us about your setup**
What is your Kalabox version and operating system?
MacOS Sierra
Kalabox 2.1.2
Pantheon

Have you previously installed Kalabox? If so, what version?
No

**Tell us about your bug**
Importing a site from Pantheon the database seems to be the wrong encoding and characters are showing as ?

**Comment by pirog** [comment]
AFAIK we don't change or alter the encoding. Can you give a little more info on how i could replicate this?

**Comment by justinffs** [comment]
Still looking into it.  Any suggestion where I would look to see what the mysqldump command is? and how the db is created initially?

**Comment by pirog** [comment]
The import cmd depends on a few things but usually its a drush dump that is piped directly into the local db. You can see some of the cmds here
https://github.com/kalabox/kalabox-app-pantheon/blob/v2.1/app/plugins/kalabox-plugin-pantheon/lib/cmd.js

For the initial DB setup we are just using a vanilla mariadb 10 image from docker
https://github.com/docker-library/mariadb/blob/2538af1bad7f05ac2c23dc6eb35e8cba6356fc43/10.1/Dockerfile

With some extra config 
https://github.com/kalabox/kalabox-app-pantheon/blob/v2.1/app/config/mysql/my.cnf

None of those things seem out of the ordinary to me but i def could be missing something

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
