### ISSUE TITLE
Document troublesome DNS/routers

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1736]
Bug Report
==========

**Tell us about your setup**

Kalabox v2.1.2 on Elementary OS (Running Ubuntu 16.04)

I've used almost every prior version, though I've done a clean uninstall.

**Tell us about your bug**

After upgrading to 2.1.2, Kalabox's DNS is no longer working for me in Ubuntu. I just get an NXDOMAIN response on any of my .kbox.site domains.

I've reproduced this several times so far.

1. Clean uninstall Kalabox (runs into issue where I need to manually remove all Kalabox's btrfs volumes to be able to remove the package, but then it works).
2. Install latest Kalabox version (2.1.2 was the start of this issue)
3. Clone any site down from Pantheon
4. Try to visit the site in browser (NXDOMAIN)

**Comment by bmcclure** [comment]
One strange thing I notice:

When I build/rebuild the site, it ends with:

`WARNING: CORE PLUGIN ==> Unexpected status code returned. This MAY be a problem. Check your site at http://mysite.kbox.host to verify. Restarting your app may help.`

Whereas the URL that seems to be correct, that the UI links to and everything, is http://mysite.kbox.site.

Is this just an inconsistency in how it reports the message, or is it something deeper than that?

**Comment by pirog** [comment]
We don't do anything with DNS at all anymore. The sites are resolved via
the internet now so unless you are offline we don't interfere with DNS

I'd make sure /etc/resolver/Kbox doesn't exist and

**Comment by bmcclure** [comment]
Tracked this down to an issue with OnHub routers--they are using "DNS rebinding protection" in dnsmasq, which seems to filter out certain IPs, such as local IPs.

**Comment by pirog** [comment]
@bmcclure im going to reopen this so we can document and maybe list some known offenders.

**Comment by pirog** [comment]
In the meantime you can following the "Working offline" instructions in the docs to get around this
http://docs.kalabox.io/en/v2.1/troubleshooting/
