### ISSUE TITLE
Application launcher icon not showing up in Elementary OS

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1737]
When using Elementary OS, the default desktop environment is Pantheon. Can you add "Pantheon" to the "OnlyShowIn" list in the kalabox.desktop file? Currently I need to manually do this after installing or upgrading Kalabox to get the icon to show up in my Applications list. Thanks!

**Comment by pirog** [comment]
@bmcclure seems easy enough to fix!
