### ISSUE TITLE
Extra steps needed for uninstalling Kalabox on Ubuntu/Elementary OS

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1738]
With the last several versions (at least since 2.1.0 I think, but that's just the first time I tried fully uninstalling on this OS) on Elementary OS Loki (Ubuntu 16.04), trying to run `sudo apt remove --purge kalabox` returns a large number of errors similar to the following:

`rm: cannot remove '/usr/share/kalabox/docker.graph/btrfs/subvolumes/7122f2c88be1514aaf3a72e7313b291236b8c0e5842db68b320a2615b46d6857': Operation not permitted`

I was able to get around this after getting that error by doing:

```
cd /usr/share/kalabox/docker.graph/btrfs/subvolumes
sudo btrfs subvolume delete *
sudo apt remove --purge kalabox
```

And it then uninstalls cleanly. I'm not sure if this is an indication of a larger issue with Kalabox's docker files not being cleaned up properly, or if this is actually a valid workaround.

**Comment by pirog** [comment]
hmmm weird, its possible kalabox does not FULLY shut down by the time that command is run.

**Comment by pirog** [comment]
@labboy0276 do you get this at all?

**Comment by bmcclure** [comment]
Should there be a large number of btrfs subvolumes in that directory if there are just a couple of kbox apps installed?

I always end up with a really large number of subvolumes that get that error when I try to fully uninstall Kalabox. That may be normal, but I just wanted to check, as if it's not, then perhaps `kbox destroy` isn't fully cleaning up its docker container volumes? That might explain why there's a bunch of volumes still created by the time apt tries to clean up the parent directory. But just a wild guess at this point.

**Comment by pirog** [comment]
@bmcclure i think its fairly normal and i **think** that is the expected behavior. My guess here is that we have a race condition of some sort where those volumes are in use or locked by a process that SHOULD be terminated by that point but is not

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
