### ISSUE TITLE
Kalabox 2.1.2+ UI reports .kbox.site as domain suffix

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1739]
On Ubuntu, when creating an app from the Kalabox UI it links me to http://app.kbox.site. The new correct domain, I think, should be http://app.kbox.host. Not sure if it's just reporting the name wrong in the link or if something deeper is wrong due to my separate ticket regarding DNS resolution not working for me.

**Comment by pirog** [comment]
@bmcclure definitely a bug! thanks!

**Comment by pirog** [comment]
@reynoldsalec any chance you can do this? I think we just need to check for the platform and suffix with `kbox.host` on linux and `kbox.site` for everything else.

**Comment by reynoldsalec** [comment]
Good catch! Yes, I'll take a look @pirog.

**Comment by pirog** [comment]
![image](https://cloud.githubusercontent.com/assets/713424/20808920/45bbfdf2-b7b9-11e6-804e-be3f3cbc40dd.png)

I DID NOT MAKE THIS. IT IS ALREADY ON GOOGLE IMAGE.

**Comment by reynoldsalec** [comment]
@pirog looked at this today and actually a bit confused. The GUI isn't doing anything special with the site URLs, tested that by hardcoding in the "Linux" case in lib/core/config.js and sure enough, that's what the GUI was showing as the app URL.

Since I don't have a way of testing this on Linux, you mind verifying to see if this is actually a problem?

**Comment by pirog** [comment]
@reynoldsalec yeah ill definitely check it out. 

@bmcclure can you clarify where you are seeing this link?

**Comment by bmcclure** [comment]
@pirog I don't **seem** to be having this issue anymore, though I have no idea what's changed now. Originally before I had the .host domain in my hosts file (to get around my router issue), that's when I noticed the Kalabox UI was sending me to http://site.kbox.site (In fact, that's the only reason I know about the .site suffix at all was UI was linking me there).

I don't think I'm running a different version of Kalabox now, and I'm still using Elementary OS Loki (Which runs on Ubuntu 16.04), so the only difference as far as I know is that the .host domain actually resolves now, where it wasn't resolving properly when I was noticing the UI linking me to the wrong domain.

I just double checked several times in different scenarios, and it's always linking me to the right site now as far as I can tell. I can't explain what changed, but it seems like this is working fine and can probably be closed out.

**Comment by pirog** [comment]
@bmcclure yeah very strange. given that @reynoldsalec couldnt replicate and i havent heard this from anyne else im going to close it out
