### ISSUE TITLE
Unexpected token “

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#174]
I used "kbox create drupal -- -is" to create a Drupal app. Additional attempts to create apps or run any kbox commands are now failing with the message:
```
Unexpected token “
```
And error log lines like:
```
{"level":"error","message":"Unexpected token “ SyntaxError: Unexpected token “\n    at Object.parse (native)\n    at /usr/local/lib/node_modules/kalabox/lib/app/discovery.js:102:29\n    at fs.js:334:14\n    at FSReqWrap.oncomplete (fs.js:95:15)","timestamp":"2015-05-11T02:29:13.377Z"}
```

The app name included a space if that matters.

**Comment by jdleonard** [comment]
Manually deleting the app's directory "solved" this problem, but I ran into others (too many to describe and resorted to uninstalling and reinstalling kalabox.

**Comment by pirog** [comment]
Might want to try again with the verbose flag `-- -v` help isolate the
issue.

that said, trying this with a space and seems to work ok... what are you
naming the app?

On Sun, May 10, 2015 at 8:04 PM, JD Leonard <notifications@github.com>
wrote:

> Manually deleting the app's directory "solved" this problem, but I ran
> into others (too many to describe and resorted to uninstalling and
> reinstalling kalabox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/174#issuecomment-100751646>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
yoyoyo. 

if you get time it would be great to see the kalabox.json that causes this to fail!

**Comment by jdleonard** [comment]
yoyo.

Sorry, that kalabox.json is no longer available. However, I just went through the process again from scratch and all is well.

**Comment by pirog** [comment]
oh nice!

any inkling on what may have caused the kalabox.json chaos?

**Comment by jdleonard** [comment]
I got nothing 



JD

**Comment by pirog** [comment]
word.
