### ISSUE TITLE
Fix the OSX window 'x' to close the window, not the program.

### ISSUE THREAD

**Issue by sarahp** [kalabox/kalabox#1745]
This may work as expected, but it breaks the typical workflow of OSX. Please change the 'x' (red dot) on the upper left of the window to just close the window, instead of shutting down the program. 

As nice as it is to have a chance to sip my coffee, this gets a little old after the first couple of times. Thanks!

**Comment by pirog** [comment]
@sarahp thanks! good feedback here. 

@reynoldsalec wondering if we are doing something different or if this is the default NWJS behavior.

**Comment by reynoldsalec** [comment]
@pirog taking a quick look at this in the NWJS docs I think this should be possible.

Right now we hook into the window's close event to run our shutdown functions. If we can find an equivalent event for the application quitting, should be a fairly trivial change.
