### ISSUE TITLE
Upgrading to 2.0.2

### ISSUE THREAD

**Issue by janetrimmer** [kalabox/kalabox#1747]
I'm on Windows 10 Home edition.

I've had Kalabox v.2.0.0 with Pantheon for a couple of months now. It has been working ok till today, when I started getting 'exit status 255' messages, even after restarting my computer.

I was advised by a guy at Pantheon to upgrade to Kalabox v.2.0.2 to resolve this issue. I cannot upgrade to v2.1.x as you can't install Hyper-v on Windows 10 Home.

The installation process has been going for over an hour, seeming to be stuck at 'Extracting files... Starting the proxy and dns services'. Is this normal? Should I start again?

**Comment by pirog** [comment]
@janetrimmer definitely not normal. You might benefit from following the purge instructions before you upgrade. 
http://docs.kalabox.io/en/v2.0/users/updating/#purge-updating

**Comment by robwatson-intechra** [comment]
As a follow-up, does Kalabox still have the issue of not being able to install on Windows 10 Home because of Hyper-V not being installable? It's not clear from this thread whether that's the case or if it was the OP's install needing to be purged. Thanks.

**Comment by pirog** [comment]
@robwatson-intechra kalabox 2.1.x requires Hyper-V, 2.0.x does not

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Comment by robwatson-intechra** [comment]
Me in June 2017: "I'll buy this iMac so I can use Kalabox easier than on a Windows machine and be able to work better with other contractors because Kalabox with its elegant GUI is so simple to get running."

Also me, now: "Lando? No more GUI? Back to command line? No more Kalabox updates?! #%&!"

*Sigh* I'll get used to it. Please tell me there's a GUI in the works. Even though I grew up writing Assembly, BASIC, and working on DOS command line, I have a terrible memory for command line syntax nowadays and prefer the speed and efficiency of a GUI whenever I can have it.

**Comment by pirog** [comment]
@robwatson-intechra i understand how you feel. Good news is:

1. A new iMac is going to help with dev beyond just using Kalabox
2. There is going to be a Lando based GUI with Kalabox-feature-parity in early 2018 (probably will have alpha/beta releases later this year)
3. We actually haven't updated Kalabox in a long time so this is more just during a de facto into a de jure. 
4. We are definitely still around to provide support for current users

That all said, a GUI is generally NEVER going to be as fast an efficient as a CLI tool so if you want speed and efficiency then learning the CLI is the way to go :)

**Comment by robwatson-intechra** [comment]
Thanks. By efficiency I mean the length of time it takes me to click a button on the interface (once it's loaded) is still muuuuch faster than the time it takes my goldfish brain to look up all the commands and parameters and try to remember how to do something. :)

**Comment by pirog** [comment]
haha, got it :)
