### ISSUE TITLE
UX Designer asking some dumb questions? Working on a toolchain for DesignOps

### ISSUE THREAD

**Issue by thedonquixotic** [kalabox/kalabox#1748]
Short Story: Would Kalabox be a flexible and simple solution for getting designers and non-technical people set up with a local development environment?

Long Story: I'm setting up an open knowledge-base focused on designers and non-technical users to get them up to speed at hackathons ASAP. Part of that is establishing a list of best practices and processes to help get people jumpstarted. Part of that is getting tools installed and everyone synced up. 

It took me 6 hours to get all my designers set up with github last hackathon I was at. GUI clients seem like a good idea for designers but they're actually pretty buggy and the process is so abstracted that sometimes it's hard for them to really understand what they're doing. They get confused on push versus pull, they have their projects saved all over the place, in non-standard ways. It was a mess. 

At work though we don't have that problem because we have Docker and AWS. Docker seems kind of intimidating to me though, and I want a locally based solution so that it can run peer to peer, or use Github and not have a proprietary service that costs money required. 

My understanding is that Kalabox could help with this? I could create a standardized environment, and then deploy it on Mac or Windows in such a way that once it's done unpacking everything, my designers and devs could get started on the project. Is this is correct understanding of Kalabox's functionality? 

And I see that it can do Drupal and stuff, which I want for my own purposes, but half the time I'm also working on VR projects in Unity, so support for that would also be desirable. Would these things be compatible?

**Comment by thedonquixotic** [comment]
Sooooo it turns out that this question is actually unnecessary because my work computer disables HyperV and since I'm hoping to roll out a solution for civic tech clubs specifically (and most government computers are probably going to have similar restrictions as mine) it looks like virtualization and therefore Kalabox won't work. But it looks real nice and I like ya'll's website! Good luck! @pirog

**Comment by pirog** [comment]
@thedonquixotic sad to hear that but not super surprising. It's hard to roll out tech like this on even moderately locked down computers because we need to set up some pretty low level stuff. 

Good luck to you as well!
