### ISSUE TITLE
Server log for Kalabox App

### ISSUE THREAD

**Issue by pvpham** [kalabox/kalabox#1749]
[**pantheon**]
[**documentation**]

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox V. 2.1.3 on Macbook Pro late 2011 OS X Sierra

Have you previously installed Kalabox? If so, what version?

- No.

Give a brief description of what happened, including any error messages that appeared.

- I'm trying to find the server logs for the web app that starts up using kalabox. Not the runtime logs provided by kalabox. Where can I look to find the server logs? 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Started up GUI
2. Started up web app
3. Clicked on web app
4. Interact with web app 

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

- If there was documentation then that would be awesome.  

Does this bug prevent you from using Kalabox?

- It does not, but it is keeping me from developing further.

**Comment by pirog** [comment]
The Docker Logs section in the docs is what you are going to want to use
http://docs.kalabox.io/en/v2.1/troubleshooting/#accessing-logs
