### ISSUE TITLE
Possible to use Limesurvey container alongside Pantheon Drupal

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1751]
I have installed Kalabox v2.1.3

Limesurvey is an opensource survey tool that can work with Drupal. I would like to use both locally, if possible, for testing.

The instructions for installing what seems to be the most popular container with Limesurvey say:

docker pull crramirez/limesurvey:latest
docker run -d --name limesurvey -p 80:80 crramirez/limesurvey:latest
Go to a browser and type http://localhost
Click Next until you reach the Database configuration screen
Then enter the following in the field:
Database type MySQL
Database location localhost
Database user root*
Database password
Database name limesurvey #Or whatever you like
Table prefix lime_ #Or whatever you like
You are ready to go.

Using port 80 and having the installation run from localhost, is there a way to avoid a conflict with Kalabox as it is currently set up? Is there a way I should be able to set up and run both my Drupal website and this Limesurvey container at the same time?

I'm sorry, but I don't know enough about this to know whether this is similar to issue #1725.

Thanks for any help.

**Comment by pirog** [comment]
@jsibley2 seems like the easiest thing to do here is just run limesurvey on a different port. 

```bash
docker run -d --name limesurvey -p 8080:80 crramirez/limesurvey:latest
```

That should bind the containers port `80` to `8080` on your localhost. Meaning you can access the service at `localhost:8080`

**Comment by pirog** [comment]
Going to add more documentation to clarify things like this

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
