### ISSUE TITLE
kbox services hasn't worked for a few versions now

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#1752]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

2.1.3 && Ubuntu 16.04 

Have you previously installed Kalabox? If so, what version?

Yes all the versions.

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

When I run kbox services, I get this:

```
john@kalamuna:~/Kalabox/huddle/code$ kbox services
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
"App is not running."
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

I have purged and reinstalled all sites, I still get the same error.  It has been this way for many versions for me.

**Comment by pirog** [comment]
Guessing this might be a linux thing cause im getting the expected results.
We also haven't changed how this works for a long time.

**Comment by labboy0276** [comment]
sadness

**Comment by herbdool** [comment]
Same Ubuntu version.

I had a 2.0.x version that was working and just tried 2.1.3. No luck. I get:

> Cannot link to a non running container: /abc_db_1 AS /abc_cli_1/abc_db_1

**Comment by pancho2jr** [comment]
Hi @labboy0276  , I think i have a work around. 

run this in the terminal . then try kbox services

export DOCKER_HOST=tcp://10.13.37.100:2375
export DOCKER=/usr/share/kalabox/bin/docker

**Comment by pancho2jr** [comment]
Hi @labboy0276 , I think i found a work around.

run in terminal 

export DOCKER_HOST=tcp://10.13.37.100:2375
export DOCKER=/usr/share/kalabox/bin/docker

After this run 

kbox services

**Comment by labboy0276** [comment]
Indeed, this work around makes it so it renders again

**Comment by pirog** [comment]
oh interesting.... kalabox should set these things when it runs a docker command. are you guys using other versions of docker that might be hijacking these?

**Comment by labboy0276** [comment]
john@kalamuna:~$ docker -v
Docker version 1.13.0, build 49bf474

**Comment by jameshiggins** [comment]
@pancho2jr this worked for me too, same version of ubuntu, thanks!

**Comment by meason** [comment]
On ubuntu 16.04 and kalabox 2.1.3 and the export commands don't work for me. :-(   Still get the "Cannot connect to the docker daemon".  It was working for quite a few hours but since then, it continues to get this message, even after shutdown / restart.  (On a VirtualBox VM)

**Comment by pirog** [comment]
@meason worth checking to verify you have a docker daemon running on `10.13.37.100`

**Comment by danielrose28** [comment]
I was also getting this message myself with ubuntu 16.04 and kbox version 2.1.3. I ran the export commands from above and it fixed it. Woot. Thanks @pancho2jr.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
