### ISSUE TITLE
  rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

### ISSUE THREAD

**Issue by defaria** [kalabox/kalabox#1753]
Using Kalabox 2.1.2 with Pantheon setup.
Max OS Sierra 10.12.1

When attempting to push from local to dev I get the following error:

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

Seems to be a permission issue, but I am not sure which file.
Full log:

Pushing database.
Pushing files.
Warning: Permanently added ...... ... (RSA) to the list of known hosts.
sending incremental file list
rsync: symlink "/srv/bindings/..../files/media" -> "/media" failed: Function not implemented (38)
2016/12/banner-1024x761.jpg
        183,523 100%   28.75MB/s    0:00:00 (xfr#1, to-chk=48/53)
2016/12/banner-150x150.jpg
          9,102 100%    1.09MB/s    0:00:00 (xfr#2, to-chk=47/53)
2016/12/banner-300x223.jpg
         22,288 100%    2.13MB/s    0:00:00 (xfr#3, to-chk=46/53)
2016/12/banner-768x571.jpg
        111,037 100%  206.94kB/s    0:00:00 (xfr#4, to-chk=45/53)
2016/12/banner.jpg
        679,608 100%  159.16kB/s    0:00:04 (xfr#5, to-chk=44/53)
2016/12/board-member-dr-george-wohlreich-150x150.png
         23,572 100%   36.25kB/s    0:00:00 (xfr#6, to-chk=43/53)
2016/12/board-member-dr-george-wohlreich.png
         78,040 100%   94.20kB/s    0:00:00 (xfr#7, to-chk=42/53)
2016/12/board-member-dr-michael-wittman-150x150.png
         38,175 100%   45.69kB/s    0:00:00 (xfr#8, to-chk=41/53)
2016/12/board-member-dr-michael-wittman.png
        144,197 100%  130.03kB/s    0:00:01 (xfr#9, to-chk=40/53)
2016/12/board-member-mr-robert-f-morris-150x150.png
         33,616 100%  220.32kB/s    0:00:00 (xfr#10, to-chk=39/53)
2016/12/board-member-mr-robert-f-morris.png
        114,370 100%  400.32kB/s    0:00:00 (xfr#11, to-chk=38/53)
2016/12/fellow-beverly-stuckwisch-150x150.jpg
          6,803 100%   23.31kB/s    0:00:00 (xfr#12, to-chk=37/53)
2016/12/fellow-beverly-stuckwisch-282x300.jpg
         17,327 100%   58.35kB/s    0:00:00 (xfr#13, to-chk=36/53)
2016/12/fellow-beverly-stuckwisch-768x816.jpg
         86,532 100%  189.05kB/s    0:00:00 (xfr#14, to-chk=35/53)
2016/12/fellow-beverly-stuckwisch.jpg
        184,316 100%  274.80kB/s    0:00:00 (xfr#15, to-chk=34/53)
2016/12/fellow-bio-cierra-atkinson-150x150.png
         36,806 100%   54.13kB/s    0:00:00 (xfr#16, to-chk=33/53)
2016/12/fellow-bio-cierra-atkinson.png
        133,870 100%  158.27kB/s    0:00:00 (xfr#17, to-chk=32/53)
2016/12/fellow-bio-jonathan-bower-150x150.png
         33,392 100%   35.87kB/s    0:00:00 (xfr#18, to-chk=31/53)
2016/12/fellow-bio-jonathan-bower.png
        124,717 100%  124.66kB/s    0:00:00 (xfr#19, to-chk=30/53)
2016/12/fellow-bio-tim-berto-150x150.png
         36,468 100%   34.15kB/s    0:00:01 (xfr#20, to-chk=29/53)
2016/12/fellow-bio-tim-berto.png
        141,437 100%  972.69kB/s    0:00:00 (xfr#21, to-chk=28/53)
2016/12/form-bg-1024x849.jpg
         36,574 100%  239.71kB/s    0:00:00 (xfr#22, to-chk=27/53)
2016/12/form-bg-150x150.jpg
          2,942 100%   19.03kB/s    0:00:00 (xfr#23, to-chk=26/53)
2016/12/form-bg-300x249.jpg
          6,092 100%   39.14kB/s    0:00:00 (xfr#24, to-chk=25/53)
2016/12/form-bg-768x636.jpg
         23,816 100%  151.02kB/s    0:00:00 (xfr#25, to-chk=24/53)
2016/12/form-bg.jpg
        110,955 100%  415.15kB/s    0:00:00 (xfr#26, to-chk=23/53)
2016/12/intro-letter-150x150.png
         36,028 100%  131.77kB/s    0:00:00 (xfr#27, to-chk=22/53)
2016/12/intro-letter-300x300.png
        115,089 100%  295.77kB/s    0:00:00 (xfr#28, to-chk=21/53)
2016/12/intro-letter.png
        171,146 100%  329.01kB/s    0:00:00 (xfr#29, to-chk=20/53)
2016/12/ksft-team-150x150.jpg
          8,650 100%   16.47kB/s    0:00:00 (xfr#30, to-chk=19/53)
2016/12/ksft-team-300x211.jpg
         17,607 100%   33.32kB/s    0:00:00 (xfr#31, to-chk=18/53)
2016/12/ksft-team-768x541.jpg
         71,751 100%  126.48kB/s    0:00:00 (xfr#32, to-chk=17/53)
2016/12/ksft-team.jpg
        174,898 100%  233.65kB/s    0:00:00 (xfr#33, to-chk=16/53)
2016/12/kstf-initiative-1024x640.jpg
        140,790 100%  174.92kB/s    0:00:00 (xfr#34, to-chk=15/53)
2016/12/kstf-initiative-150x150.jpg
          9,942 100%   12.27kB/s    0:00:00 (xfr#35, to-chk=14/53)
2016/12/kstf-initiative-2-1024x644.jpg
        135,000 100%  146.81kB/s    0:00:00 (xfr#36, to-chk=13/53)
2016/12/kstf-initiative-2-150x150.jpg
         10,043 100%   10.85kB/s    0:00:00 (xfr#37, to-chk=12/53)
2016/12/kstf-initiative-2-300x189.jpg
         20,670 100%   21.38kB/s    0:00:00 (xfr#38, to-chk=11/53)
2016/12/kstf-initiative-2-768x483.jpg
         85,453 100%   83.95kB/s    0:00:00 (xfr#39, to-chk=10/53)
2016/12/kstf-initiative-2.jpg
        452,822 100%  299.80kB/s    0:00:01 (xfr#40, to-chk=9/53)
2016/12/kstf-initiative-300x188.jpg
         21,276 100%   43.56kB/s    0:00:00 (xfr#41, to-chk=8/53)
2016/12/kstf-initiative-768x480.jpg
         88,646 100%  166.48kB/s    0:00:00 (xfr#42, to-chk=7/53)
2016/12/kstf-initiative.jpg
        629,939 100%  610.29kB/s    0:00:01 (xfr#43, to-chk=6/53)
2016/12/year-1999-150x150.png
         36,147 100%    5.75MB/s    0:00:00 (xfr#44, to-chk=5/53)
2016/12/year-1999.png
        124,565 100%    1.01MB/s    0:00:00 (xfr#45, to-chk=4/53)
2016/12/year-2002-150x150.png
         44,999 100%  357.27kB/s    0:00:00 (xfr#46, to-chk=3/53)
2016/12/year-2002.png
        161,380 100%  716.35kB/s    0:00:00 (xfr#47, to-chk=2/53)
2016/12/year-2010-150x150.png
         39,840 100%  143.04kB/s    0:00:00 (xfr#48, to-chk=1/53)
2016/12/year-2010.png
        116,315 100%  346.31kB/s    0:00:00 (xfr#49, to-chk=0/53)

sent 5,106,940 bytes  received 1,079 bytes  329,549.61 bytes/sec
total size is 5,132,577  speedup is 1.00
 
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

**Comment by pirog** [comment]
@defaria i've seen this happen intermittently. If you try to pull files again do you still get this?

**Comment by jserrao** [comment]
Got an almost identical issue, same kalabox version. Similarly, my files keep going through rsync error persists in dialog.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
