### ISSUE TITLE
German umlauts in Drupal Path lead to 502 lost in the cloud

### ISSUE THREAD

**Issue by spuky** [kalabox/kalabox#1754]
Bug Report
==========

Pantheon site on Kalbox Version 2.1.3 (2.1.3)

What is your Kalabox version and operating system?

Version 2.1.3 (2.1.3) OSX

the site was setup with Pathauto (in d8 rc days..) the german Frontpage had the Title
Feine Tischwäsche seit 1866

which lead to the path: 
/de/feine-tischwäsche-seit-1866

When kalabox_proxy_1 is accessing the page it is parsing the headers and giving the following error in the container log:

21 Dec 17:49:52 - (worker #178) pichler.kbox.site: backend #0 reported an error ({"bytesParsed":303,"code":"HPE_INVALID_HEADER_TOKEN"}) while handling request for /

The header did contain some Link tokens containing the full canonical path for the Page

Link: <http://localhost:32780/de/feine-tischwäsche-seit-1866>; rel="alternate"; hreflang="de"
Link: <http://localhost:32780/en/node/65>; rel="alternate"; hreflang="en"
Link: </de/feine-tischwäsche-seit-1866>; rel="canonical"
Link: </de/node/65>; rel="shortlink"
Link: </de/feine-tischwäsche-seit-1866>; rel="revision"

so the Headerparser used in node.js seems to be confused with those Headers... 

After changing the path to: /de/feine-tischwaesche-seit-1866
the Page was working in Kalabox...

**Comment by pirog** [comment]
@spuky thanks for adding this!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
