### ISSUE TITLE
Encoding issues when database charset missing

### ISSUE THREAD

**Issue by atrzyna** [kalabox/kalabox#1756]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system? 
Kalabox 2.1.3 on OS X El Capitan 10.11.6

Have you previously installed Kalabox? If so, what version? No

**Tell us about your bug**
When database charset is not set in wp-config.php, the site in kalabox has encoding issues. 

Could better documentation have prevented this issue? if so what should we change?
auto-inject the charset

**Comment by pirog** [comment]
@atrzyna thanks for getting this up on the queue. Here is the relevant Pantheon doc for reference
https://pantheon.io/docs/wp-config-php/

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
