### ISSUE TITLE
Additional close options for connection info dialog

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#1760]
Feature/Enhancement Request
===========================

**Please explain your request and its importance in the form of a user story.**

As a Kalabox user who works with Drupal sites that have large databases, sometimes I need to browse the database tables and need the connection info, however, I may also be a in a shit mood or be having a very bad day and I don't want to thank Kalabox for this information, so I should have an option such as 'Fine' or 'Ok, now piss off!' in addition to 'Got it, Thanks!'*

**Please provide some detail on how Kalabox can help solve this problem**

Add a button dropdown with an option for "Ok, now piss off!" to the Connection info dialog action button.

**Comment by pirog** [comment]
+1

Always happy to turn software into a stress reduction mechanism as well.
