### ISSUE TITLE
APCu extension, WP LCache?

### ISSUE THREAD

**Issue by joedooley** [kalabox/kalabox#1762]
Bug free! Just wondering if there is a way to install the APCu extension that's required by the WP LCache plugin? I didn't see anything in the docs. If this belongs in the Pantheon Kalabox repo let me know and I'll move it. Thanks in advance.

**Comment by pirog** [comment]
@joedooley good feature request. 

If you've got some docker experience you can set up your kalabox pantheon appserver (in kalabox-compose.yml) to build locally and then edit the Dockerfile to add in the apcu extension.

In the long term this is something we should bake directly into the appserver container.

**Comment by joedooley** [comment]
@pirog thanks for pointing me in the right direction. I'll give it a shot!

**Comment by pirog** [comment]
Sounds good!

We are planning to make some big changes in the next big release to make
this easier and more intuitive to extend.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
