### ISSUE TITLE
Docker eating disk space

### ISSUE THREAD

**Issue by pstevemichel** [kalabox/kalabox#1763]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?  Kalabox 2.1.1, MacOS Sierra 10.12.2, Docker 1.12.6 (14937)

Have you previously installed Kalabox? If so, what version? Yes, I had some of the betas.

The kalabox local site in question is an older one -- it was built, from file dates in ~/.kalabox -- last October. 

**Tell us about your bug**

Docker seems to be eating disk space when a kbox is running. 

When I came into work this morning, my MacBook Air, which had been sleeping all night, warned me that I was running low on disk space -- down to 9G. When I restarted the machine, disk space was back up to 22G. Then I started kalabox, and in Activity Monitor watched disk usage. I could see that com.docker.hyperkit was steadily writing to the drive, and watched it sink from about 22G free to about 17 in just an hour or so. This was on a kalabox site that was essentially idle.

Searches show lots of complaints about this re:Docker, on many different systems. Is there a way that Kalabox can ameliorate this? 

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Only if there is something I can do to stop this from happening!

Does this bug prevent you from using Kalabox?

I am not using it as I write, and it seems when I do use it, I'll need to make sure I shut it down every evening!

**Comment by pirog** [comment]
I think, sadly, our best bet is to probably wait for this to get fixed
upstream in Docker.

**Comment by pstevemichel** [comment]
Thanks, Mike. I figured that was the case, but thought it might be worth a try. I just put a sticky note on my monitor to shut down kalabox every evening.

**Comment by pstevemichel** [comment]
FWIW, the new Docker release I got this morning didn't fix the issue.

**Comment by pirog** [comment]
I assume you've investigated this on the various docker forums? looks like
there are a few workarounds people are using.

**Comment by JamesChevalier** [comment]
They're working on the fix [here](https://github.com/docker/for-mac/issues/371). If I understand correctly, the latest version of Docker for Mac (1.13 as of now) should clean up its disk usage on each system restart.
Keep an eye out, though, because Kalabox forcefully installs an older version of Docker. I had to reinstall Docker after installing Kalabox.

There are also a few relevant links in this related [StackOverflow question](http://stackoverflow.com/questions/39402363/how-do-you-get-around-the-size-limitation-of-docker-qcow2-in-the-docker-for-mac) that I created, as well.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
