### ISSUE TITLE
Database Pull not pulling on first try

### ISSUE THREAD

**Issue by miller2676** [kalabox/kalabox#1766]
Bug Fix
OSX 10.11.6
Kalabox 2.1.3
I've installed several other versions and always follow the install/uninstall instructions when upgrading. 

For existing Kalabox Pantheon sites I have to pull the database _at least_ two times for it to actually pull down a new copy of the database. It usually works after two times, but sometimes I have to restart the container, and in rare cases I've had to delete the app and recreate it. 

To be clear: Are we supposed to be able to pull while a site is running?

**Comment by pirog** [comment]
@miller2676 yes you can. what you are describing is not the default behavior. 

what database are you trying to get? dev, test, live, multidev? do you get anything on the first pull?

**Comment by pirog** [comment]
@miller2676 are you clearing up your caches after you pull the database?

**Comment by miller2676** [comment]
I haven't been every single time, but yes that is something I do frequently when trying to get it to work. And I usually clear twice in a row when doing this. Is that a required step for the default behavior? 

Also, so you have more info, two of the sites that this is happening on are not yet in production, so the live versions don't have all of the usual caching and css/js aggregation enabled yet.

**Comment by miller2676** [comment]
Update: I've been clearing cache each time and this is still happening.

**Comment by defaria** [comment]
I am having a similar issue. I am trying to pull the database from Test. I did it via terminal, kbox pull, and select database only. The program ends at "Pulling Database", after that I get the console back and nothing else is done. I guess the process is terminating early.

Version 2.1.2 (2.1.2)
Mac OS 10.12.2

**Comment by defaria** [comment]
This is what showed up in the alerts box when I ran it through the UI.

 Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.14/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E

**Comment by justinffs** [comment]
Having a similar issue, not sure how to troubleshoot this or provide more info.

**Comment by entrepreneur27** [comment]
I have a similar issue. I get the exact same error message as defaria above. In my case the database seems to get pulled OK. But the code is not getting updated. It shows the same versions of modules that it had a few days ago, even though I had updated them in Dev.

I am running Kalabox 2.1.3 on a Mac running 10.12.3. Same issue happened before I upgraded the Mac to Sierra when I was running prior OS X.

**Comment by pirog** [comment]
This issue is for the DB not being pulled correctly, if you arent seeing
the code pulled please open a new issue.

**Comment by entrepreneur27** [comment]
OK. But since I got the exact same error message, I thought that might shed some light on the problem for you.

**Comment by justinffs** [comment]
One issue that we had was with the role of the user.  It seems the developer role can not pull the database but there is not error or warning to let the user know.   Please note that we did also experience this issue with and Administrator level user as well.

**Comment by pirog** [comment]
Oh that's interesting. I'll def try to replicate this with diminished user
permissions

**Comment by klonos** [comment]
>OK. But since I got the exact same error message,

@entrepreneur27 I also got the very exact error while trying to spawn a D8 box. Filed a separate issue for it: #1784

**Comment by wallawe** [comment]
Having the same issue as well, are there any updates?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
