### ISSUE TITLE
Can't install Drupal 8 modules via the UI

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox#1767]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Ubuntu 16.10

Have you previously installed Kalabox? If so, what version?

Yes, all the versions!

**Tell us about your bug**

Attempting to install a module using the Drupal 8 UI errors. Go to /admin/modules/install and attempt to install any random Drupal 8 module and you get this:

```
An AJAX HTTP error occurred.
HTTP Result Code: 404
Debugging information follows.
Path: /core/authorize.php/core/authorize.php?batch=1&id=2&op=do_nojs&op=do
StatusText: Not Found
ResponseText: {"message":"No route found for \u0022POST \/core\/authorize.php\/core\/authorize.php\u0022 (from \u0022http:\/\/cornell-dustin.kbox.host\/core\/authorize.php?batch=1\u0026id=2\u0026op=start\u0022)"}
```

We ran into this on Pantheon too: https://github.com/pantheon-systems/drops-8/issues/102

Drupal 8's Nginx config had to updated, @greg-1-anderson may know more about the specifics of the fix.

Not really a need for a documentation fix, just an nginx config fix.

@pirog do you guys have a means for pulling separate Nginx configs for different 'frameworks' (d8, d7, wp)?

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/tree/v2.1/app/config/nginx

**Comment by greg-1-anderson** [comment]
The above error is a bug in Drupal core. It happens to be innocuous for Apache, because apache sees the path `core/authorize.php/core/authorize.php`, and it just calls `core/authorize.php`. Nginx, on the other hand, looks for a script at the literal path `core/authorize.php/core/authorize.php`, finds nothing and fails.

**Comment by greg-1-anderson** [comment]
I [wrote a blog post](https://pantheon.io/blog/update-your-nginx-config-drupal-8) about this.

**Comment by dustinleblanc** [comment]
@pirog I'm testing out tweaks to the drupal8.conf based on Greg's blog, if all goes well, that should resolve the issue this customer had.

**Comment by samuelmolinski** [comment]
This is a easy fix by added `rewrite ^/core/authorize.php/core/authorize.php(.*)$ /core/authorize.php$1;` to the config/nginx/drupal8.conf about line 16.  I would love to see something to address this added.

```
  root /code;
  index index.html index.htm index.php;
  port_in_redirect off;
  client_max_body_size 100M;

  rewrite ^/core/authorize.php/core/authorize.php(.*)$ /core/authorize.php$1;

  # No reading git files
  location ~ /\.git {
      deny all;
  }
```

**Comment by pirog** [comment]
@samuelmolinski thanks! we have a few big updates in the pipeline and it should include a fix for this!

**Comment by 88Anja88** [comment]
Thank you very much samuelmolinski  you are my hero.

I have  an installation with easy engine and two exiting wordpress installations. Then i decided to additionaly use a third installation with drual  which also used easy engine configuration files.

My solution was the following.
in /etc/nginx/sites-available/example.com i added your line 
`server {

    server_name frei-von-allerlei.de   www.frei-von-allerlei.de;

    access_log /var/log/nginx/frei-von-allerlei.de.access.log rt_cache;
    error_log /var/log/nginx/frei-von-allerlei.de.error.log;

    root /var/www/frei-von-allerlei.de/htdocs/drupal-8.3.2;

    index index.php index.html index.htm;

    include common/php7.conf;  
    
    rewrite ^/core/authorize.php/core/authorize.php(.*)$ /core/authorize.php$1;

    include common/locations-php7.conf;
    include /var/www/frei-von-allerlei.de/conf/nginx/*.conf;
}`

Bevor that i tried the solution from greg-1-anderson  but i was to generally for my installation.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
