### ISSUE TITLE
Local Solr configuration

### ISSUE THREAD

**Issue by ultimike** [kalabox/kalabox#1768]
When pulling a site down from Pantheon that is using Solr, are there any configuration changes that need to be done on local to get Solr to work? For example, does the Solr URI or any other settings need to be updated on local?

thanks,  
-mike

**Comment by pirog** [comment]
You will need to post your schema like you do on pantheon and then you
should be good to go.

**Comment by ultimike** [comment]
Hmm - ok - I just did that, but I'm stilling having an issue. 

Here's what my admin/config/search/search_api/server/dev_solr_server shows now:

![dev_solr_server___think_college](https://cloud.githubusercontent.com/assets/1727889/22379104/f6b171fc-e485-11e6-86e1-e335efb918a8.png)

I believe that all looks fine, correct? Should I be able to open http://appserver:8983/solr in a browser and see the Apache Solr admin page (it just times out...)?

Here's the index configuration page (admin/config/search/search_api/index/program_records_index): 

![program_records_index___think_college](https://cloud.githubusercontent.com/assets/1727889/22379165/32d48282-e486-11e6-96fd-d2ebaf923f36.png)

Again, I believe this is all good. However, when I go to "Index now", it quits quickly and I get the following in watchdog:

![details___think_college](https://cloud.githubusercontent.com/assets/1727889/22379222/65c2418e-e486-11e6-9b52-accedc9f0ec0.png)

Any ideas?

thanks,  
-mike

**Comment by pirog** [comment]
@ultimike, havent seen that one before. anyway to determine what these "important server tasks" are?

**Comment by ultimike** [comment]
I've tried - I haven't been able to...

Maybe I'll just re-pull it down and give it another shot...

-mike

**Comment by pirog** [comment]
My guess is that its not kalabox related but probably something specific to
your application. Should be easy to verify that by trying to index on a
different site.

**Comment by ultimike** [comment]
Heh - I re-pulled the site and now it works. Odd.
