### ISSUE TITLE
Using non-VirtualBox boot2docker image

### ISSUE THREAD

**Issue by wizonesolutions** [kalabox/kalabox#177]
So Parallels has `parallels/boot2docker`, but I can't figure out how Kalabox is actually communicating with it. The Parallels version probably doesn't use the `boot2docker` tool (@YungSang? @legal90?)...but it definitely has a Vagrant box and could export `DOCKER_HOST`. Can I make this work with Kalabox somehow?

**Comment by pirog** [comment]
Yeah i definitely think this is possible. If you have time at the con i'd be happy to hack on this a bit with you.

**Comment by legal90** [comment]
@wizonesolutions 
> The Parallels version probably doesn't use the boot2docker tool
You can the usage info for `parallels/boot2docker` box here: https://atlas.hashicorp.com/parallels/boxes/boot2docker/versions/1.6.0

Seems like the only you need now is just export `DOCKER_HOST` variable

**Comment by wizonesolutions** [comment]
@legal90 but does the `boot2docker` executable from Docker only rely on `DOCKER_HOST`? I got the impression it was using VirtualBox commands directly to control the VM.

**Comment by legal90** [comment]
@wizonesolutions 
> I got the impression it was using VirtualBox commands directly to control the VM.

Ah, yes, sure. That's why [`boot2docker-cli`](https://github.com/boot2docker/boot2docker-cli) it is going to be deprecated in favor of  [`docker/machine`](https://github.com/docker/machine) which is designed to support different platforms. Support of Parallels Desktop will be there soon:
https://github.com/docker/machine/pull/939

**Comment by wizonesolutions** [comment]
@pirog Maybe the real issue here is to jump ship and start using https://github.com/docker/machine, not `boot2docker`.

**Comment by pirog** [comment]
that's the plan :)

**Comment by wizonesolutions** [comment]
Cool, then no need for this issue

**Comment by pirog** [comment]
hoping to get up in the swarm and compose at some point as well
