### ISSUE TITLE
Proxy container is persists even when `kbox stop`ing your last app.

### ISSUE THREAD

**Issue by serundeputy** [kalabox/kalabox#1771]
Bug Report
==========

What is your Kalabox version and operating system?
  * Kalabox: 2.1.3
  * OS: macOS Siera 10.12.2

Have you previously installed Kalabox? If so, what version?
  * Not on this computer; fresh install of Kalabox 2.1.3

Proxy container is persistent.

* When you start Kalabox via GUI and start an app it starts a proxy container: `kalabox_proxy_1`
* Then shutdown Kalabox that stops the `kalabox_proxy_1` proxy container

* When you start an app via `kbox start` it starts the app containers including `kalabox_proxy_1`
* Stop the app via `kbox stop`
  * The proxy container is still running; you can see this via `docker ps`
  * This means if you try to use port 80 with a local stack you can not

You can get port 80 back for the local stack by shutting down docker itself or `docker stop <CONTAINER ID>`

Not terrible but a bit unexpected if you are running your apps via kbox start / kbox stop and not using the GUI.

We should have the `kbox stop` command check if it is the last/only kbox app running and if so shutdown the `kalabox_proxy_1` conatainer as well.

Could better documentation have prevented this issue? if so what should we change?
  * no

Does this bug prevent you from using Kalabox?
  * no

**Comment by spuky** [comment]
kbox poweroff 
is your friend... :-)

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
