### ISSUE TITLE
cURL error 28: Resolving timed out after 4540 milliseconds

### ISSUE THREAD

**Issue by joedooley** [kalabox/kalabox#1772]
I am getting timeouts on all of my local wp kbox installs. This only happens on the plugin page, the main wp-admin dashboard page, and anytime I try to add oembeds from Wistia/You Tube, etc. 

I've been hesitant to create an issue because this version of Kalabox has been so dependable and fast but I can't avoid the problem anymore as I need oembed support for a project.

Has anyone encountered the errors below with oembeds or in plugins at `/wp-admin/plugins.php`. Due to the timeouts it takes plugins about 30 seconds to load.

Below is system info and the error messages i'm getting. Thanks in advance.

wp-admin/plugins.php
![image](https://cloud.githubusercontent.com/assets/15069810/22492983/c257a96c-e7fa-11e6-8a1c-4961e90eecdc.png)

wp-admin/index.php
![image](https://cloud.githubusercontent.com/assets/15069810/22493063/68a7edcc-e7fb-11e6-82e6-01588141a81d.png)

Error when you add a supported oembed to the editor or a metabox
![image](https://cloud.githubusercontent.com/assets/15069810/22493004/e64c800e-e7fa-11e6-85a6-51977f0cc96a.png)

Environment Info: Problem occurs with php 5.6 or 7.
![image](https://cloud.githubusercontent.com/assets/15069810/22493029/28caaaa0-e7fb-11e6-9d78-3e0b3a2327e3.png)

![image](https://cloud.githubusercontent.com/assets/15069810/22493036/3a7bdab2-e7fb-11e6-823b-98423a64a015.png)

**Comment by pirog** [comment]
@joedooley i've seen some chatter about wordpress slowness using docker 0.12.6. might be worth upgrading to the latest docker and see if that resolves your issue. 

we will also be bundling this into our next release.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
