### ISSUE TITLE
Kalabox installation overwrites existing Docker installation

### ISSUE THREAD

**Issue by JamesChevalier** [kalabox/kalabox#1773]
Bug Report
==========

**Tell us about your setup**

**What is your Kalabox version and operating system?**
2.1.3 on Mac OS X 10.11.6 with Docker for Mac 1.13.0 (15072)

**Have you previously installed Kalabox? If so, what version?**
No, this is a new install of Kalabox 2.1.3

**Tell us about your bug**

**Give a brief description of what happened, including any error messages that appeared.**
I ran the Kalabox installer while Docker for Mac 1.13.0 was installed & running. A little while later, I tried to run `docker container ls -a`, and it responded by saying that `container` wasn't a valid command. When I opened the `About Docker` menu, it indicated that it was on version 1.12 (I don't recall the minor version number).
To resolve the issue, I reinstalled Docker for Mac 1.13

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**
1. Install Docker for Mac 1.13 [direct link](https://download.docker.com/mac/stable/Docker.dmg)
2. Run `docker --version`
3. Install Kalabox 2.1.3 [direct link](http://www.kalabox.io/download/kalabox?email=someone@somewhere.com&extension=dmg&version=2.1.3)
4. Run `docker --version`

**Tell us more**

**Could better documentation have prevented this issue? if so what should we change?**
Possibly. If the documentation noted that Docker would be overwritten, I could have been prepared for that. The documentation change could be that the [macOS steps](http://docs.kalabox.io/en/stable/users/install/#macos) include a note about Docker for Mac being overwritten.
I would prefer that the Kalabox installer checks for the existence of Docker for Mac, and skips installation if it's present.

**Does this bug prevent you from using Kalabox?**
No. I am able to reinstall Docker for Mac after installing Kalabox.

**Comment by spazzwig** [comment]
Agreed, skipping and/or messaging if Docker is already installed would be great.

In the meantime, if you use the customize option of the Kalabox package installer you can uncheck the docker package to skip including it in case you already have it installed or want to install it separately.

**Comment by JamesChevalier** [comment]
I'm not familiar with the customize option of the Kalabox installer. Is that mentioned in the [docs](http://docs.kalabox.io/en/stable/users/install/#macos) somewhere that I missed?

**Comment by spazzwig** [comment]
I don't believe it is in the docs, but it is a standard feature of MacOS package installers. After you start the installer there is an "Installation Type" step that is just before the install process is actually launched, there should be a button labeled "Customize":
![installer-standard](https://cloud.githubusercontent.com/assets/60990/22606596/4509e414-ea09-11e6-8107-ec3e8621144a.png)

Selecting that button will bring up the option to select which sub-packages of the overall install to include:
![installer-customize](https://cloud.githubusercontent.com/assets/60990/22606595/45069304-ea09-11e6-872a-4d2c24947777.png)

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
