### ISSUE TITLE
Symfony and Kalabox

### ISSUE THREAD

**Issue by burnsjeremy** [kalabox/kalabox#1775]
> Create a new issue and answer three questions to pass -
> 1. I did not see anything pertaining to just running normal Symfony apps in the docs nor the issues but if I missed it please forgive me (and this issue could self-destruct afterwards if I missed it.).**
> 2. I will tag the issue as a feature request and any other relevant tags I can find.
> 3. Feature Request.

Feature/Enhancement Request
===========================

**User Story:**
As a Kalabox user who works with Drupal 8 sites/application and Symfony applications (Hopefully not the only user that does this) it would be wonderful to use Kalabox to manage both. I would be able to spin up a Symfony application from the GUI like I do for Drupal sites with Kalabox since Kalabox is pretty kick butt and all.

**Ask:**
Place an option on the "add site" menu to create a Symfony application that does the same thing as the D8 option that gives a developer the Symfony framework for starting and managing local development easier.
_**Would probably want to add Symfony 2 and Symfony 3 to that menu or just give the option on the next prompt where you create your app name to choose your version (personally I like the latter but would take either since this feature is already going to save me time)._

**Reasoning:**
I figured that this would probably only involve adding the GUI options mentioned above and configuring some URLs to get the Symfony framework downloaded at first. That would be pretty easy to add since we know Symfony runs fine on Kalabox thanks to D8. However, later it could have more advanced options later using the Symfony CLI options like clearing the cache and a ton of other useful commands that come with the framework of course. I think that this would open up Kalabox to a larger audience also like the Pantheon additions with WP being included. I know the line has to be drawn somewhere as to who you are marketing your app and services for but you started with Drupal and Drupal is Symfony also :)

**Comment by burnsjeremy** [comment]
I lied on number 2 above, I cannot label issues so to the powers that be I'm sorry and please add a Feature label or whatever you think it needs, thanks!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
