### ISSUE TITLE
kalabox pull documentation issue

### ISSUE THREAD

**Issue by jserrao** [kalabox/kalabox#1776]
On http://pantheon.kalabox.io/en/latest/#pulling-from-pantheon, in the 'Important' note, there is mention of CLI prompt about getting asked whether you want to pull backup DB or current DB from an environment. Either the documentation is wrong (because I never see that) or the CLI has been updated and the docs are out of step with that.

Perhaps you have to flag `kbox pull` in some way to get the DB question but that isn't mentioned either.

**Comment by spuky** [comment]
I guess there is **some Issue with the latest path on that doku** site which seems to be mapping to:

http://pantheon.kalabox.io/en/v0.13.0-alpha.1/ (long time ago..)

http://pantheon.kalabox.io/en/stable/ 

is the place to go...

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
