### ISSUE TITLE
Major code change delay

### ISSUE THREAD

**Issue by TWGerard** [kalabox/kalabox#1778]
- Kalabox 2.1.3
- Mac OS X 10.10.5

I am having an issue with code changes not being reflected on my Kalabox site. I have read the [documentation](http://docs.kalabox.io/en/stable/users/config/#sharing) and am not sure if I am just misunderstanding it or if it simply is not working for me. My kalabox.yml file has only one sharing directive: share: 'data:/code', which is what I got when I cloned the site from Pantheon.

The severity of the delay between changing my code and seeing the changes on my site varies greatly. At its best it is less than a second, but that is still too slow for me as I am using `livereload` and the file has not been updated on the Kalabox local site before `livereload` requests it. At its worst, such as tonight, my code changes have been ignored by Kalabox for hours despite restarting Kalabox, Docker, and the entire computer.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
