### ISSUE TITLE
API Limit Exceeded on kbox provision

### ISSUE THREAD

**Issue by Drupal8Todd** [kalabox/kalabox#178]
After installing, on kbox provision I'm getting a failure on the API limit:

info: -- Step 15/19 --
info: Setting up and activating the engine...
info: B2D => Starting up...
info: B2D => Error while starting up. code: 1, msg: error in run: Failed to get latest release: Error getting releases: API rate limit exceeded for 66.78.233.141. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
 see 

info: -- FAIL. --

code: 1, msg: error in run: Failed to get latest release: Error getting releases: API rate limit exceeded for 66.78.233.141. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
 see

**Comment by pirog** [comment]
Looks like we exceeded the docker rate limit for the drupalcon conference
ip :(



On Tuesday, May 12, 2015, Drupal8Todd <notifications@github.com> wrote:

> After installing, on kbox provision I'm getting a failure on the API limit:
>
> info: -- Step 15/19 --
> info: Setting up and activating the engine...
> info: B2D => Starting up...
> info: B2D => Error while starting up. code: 1, msg: error in run: Failed
> to get latest release: Error getting releases: API rate limit exceeded for
> 66.78.233.141. (But here's the good news: Authenticated requests get a
> higher rate limit. Check out the documentation for more details.)
> see
>
> info: -- FAIL. --
>
> code: 1, msg: error in run: Failed to get latest release: Error getting
> releases: API rate limit exceeded for 66.78.233.141. (But here's the good
> news: Authenticated requests get a higher rate limit. Check out the
> documentation for more details.)
> see
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/178>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by bcauldwell** [comment]
@pirog any ideas how we can prevent this at the next event?

**Comment by pirog** [comment]
i don't see how unless we have our own endpoint that rotates IP addresses before it grabs stuff from docker. 

there might be a way to get an authenticated/trusted account that we could use for kalabox.
