### ISSUE TITLE
Xdebug Not Working with Atom and Kalabox

### ISSUE THREAD

**Issue by wluisi** [kalabox/kalabox#1781]
Trying to get Kalabox and Xdebug working with the Atom Code Editor. This is my setup:

Mac OS X El Capitan 10.11.6
Kalabox Version 2.1.3 [ only version of Kalabox installed on this cpu ]
Atom 1.14.1 (Latest version)
php-debug 0.2.4 (latest version, this is the goto Atom package for connecting to xdebug) [ https://atom.io/packages/php-debug ]

The setup I have here works flawlessly with MAMP and Acquia's Dev Desktop.

I've looked through the docs here to try and figure this out, but no luck:

https://github.com/kalabox/kalabox-app-pantheon/blob/v2.0/docs/users/tooling.md#xdebug

The closest I've gotten here is throwing in xdebug_break() into my code, so for example:

```
$nodes = entity_load('node', $nids);
xdebug_break();
```

I set $nodes as my watchpoint, and it does almost work. I'll get the node object data in my debugger in Atom, however two things then happen:

1. A duplicate of the php file I am debugging will open, but it will be completely blank.
2. Atom throws this error:

```
Error: spawn php ENOENT
Error: spawn php ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Using the native debugging tools in Atom provided by PHP Debug such as setting breakpoints just gets ignored. Only way to get a breakpoint is to hard code w/ xdebug_break().

"PHP Debug"/Atom doesn't offer the same config settings like PHP Storm or Sublime, but I can set the following:

```
"php-debug":
  {
    ServerPort: 9000
    PathMaps: [
      "remotepath;localpath"
      "/base/path/on/remote/system;/base/path/to/kbox-site"
    ]
  }
```

Any help would be much appreciated.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
