### ISSUE TITLE
Site Urls field is empty

### ISSUE THREAD

**Issue by idpokute** [kalabox/kalabox#1783]
What is your Kalabox version and operating system? 
2.1.3
windows10

Give a brief description of what happened, including any error messages that appeared.
When I add new site, everything is fine except Site URLs field. I tested 3 times and every time is the same result.
![blankurls](http://www.senna-design.com/wp-content/uploads/sites/12/2017/02/blank.jpg)
Thus I can't access the site. Can I set the urls manually?

**Comment by klonos** [comment]
This just happened to me when trying to spawn a WordPress site. Stopping and starting the box corrected the issue for me.

Mac OSX 10.12.3, kbox 2.1.3

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
