### ISSUE TITLE
Error: [ngModel:nonassign] 

### ISSUE THREAD

**Issue by klonos** [kalabox/kalabox#1784]
Bug Report
==========

What is your Kalabox version and operating system? 2.1.3 on Mac OSX 10.12.3

Have you previously installed Kalabox? If so, what version? Nope, fresh installation.

1. Started up the GUI
1. Spawned a D8 box
1. Got the connection info
1. Visited the URL
1. Installation screen showed up prompting to select language -> went with the default: English
1. Next screen prompted for selecting an installation profile -> wend with the default "Standard" profile.
1. Next screen asked for db name and credentials -> drupal/drupal/drupal
1. Got this error: Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.
1. Back in the GUI, there is a notice with this error:

```
Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.14/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E
```

I tried destroying the box and starting afresh and actually did that a couple of times. I would either get the above situation with the `Failed to connect to your database server.` error or another error about the files directory not being present.

PS: I was trying to create a D8, a D7, a Backdrop and a WP site simultaneously. The WP box fired up without any errors and the installation of the site was successful. The D7 and Backdrop boxes fired up without any errors, but they both throw a 403 "You don't have permission to access / on this server." message when trying to access the URL I get from the connection info in the GUI.

Does this bug prevent you from using Kalabox? Yes

**Comment by klonos** [comment]
...for the record, this error comes up soon as you try to access the connection info from the GUI. I just tried destroying the D7 box and recreating it (tried a couple of times and also quit Kalabox and restarted just to make sure) and I get the same error during installation:

```
ailed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory.
```

**Comment by pirog** [comment]
I'd check the other issues. In there you will see this is actually a false
negative eg not an actual error.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
