### ISSUE TITLE
"The installation has encountered an error." when installing Backdrop CMS

### ISSUE THREAD

**Issue by klonos** [kalabox/kalabox#1785]
Bug Report
==========

What is your Kalabox version and operating system? 2.1.3 on Mac OSX 10.12.3

Have you previously installed Kalabox? If so, what version? Nope, fresh installation.

1. Started up GUI
1. Created a Backdrop CMS box
1. Started the box, got the connection info off of the GUI
1. Started the installation.
1. Selected language, then I did not have to enter any db credentials 👍 
1. The installer started installing the required modules for the standard profile.
1. I got the following error:

```
The installation has encountered an error.
Please continue to the error page

An AJAX HTTP request terminated abnormally. Debugging information follows. Path: http://test-backdrop-site.kbox.site/core/install.php?langcode=en&profile=standard&id=1&op=do_nojs&op=do StatusText: error ResponseText: ReadyState: 0
```

The link to the error page was pointing to `http://test-backdrop-site.kbox.site/core/install.php?langcode=en&profile=standard&id=1&op=finished`

1. Clicked the link and installation proceeded to the "Configure your site" step. I entered site name, admin name, email and password and the installer finished. I looked at the site's recent log messages (`http://test-backdrop-site.kbox.site/admin/reports/dblog`), but there were no errors logged.

Does this bug prevent you from using Kalabox? Nope, just annoying and bad UX, that's all.

**Comment by pirog** [comment]
@klonos sounds like an issue for the backdrop queue?

**Comment by serundeputy** [comment]
Hello @klonos!

> Started up GUI
  * √
> Created a Backdrop CMS box
  * √
> Started the box, got the connection info off of the GUI
  * √
> Started the installation.
  * √
> Selected language, then I did not have to enter any db credentials 👍
  * Here I selected English √
The installed started installing the required modules for the standard profile.
> I got the following error:
  * I did not receive an error; installation went off without a hitch.

Anything different about my steps?  Looks like you selected `en` as well.

thanks,
~Geoff

**Comment by klonos** [comment]
Starting to believe that this was a memory limit or timeout issue. I had the same thing happen to me just a few minutes ago while giving a go at the [Restaurant](https://www.drupal.org/project/restaurant) distribution (that is Drupal; not Backdrop) over at simplytest.me: https://simplytest.me/project/restaurant (that is 3rd party; not Kalabox) ...might also be related to my crappy internet connection(?).

**Comment by klonos** [comment]
...seems that there was an issue for this over in d.org. Supposedly "fixed": https://www.drupal.org/node/1232416

> The following error is frequently run into with Drupal. Per [#215](https://www.drupal.org/node/1232416#comment-10242695), it does not apply to D8.

...since we forked from D7, I guess we've also inherited this problem 😞 I guess not much we can do and the "fix" in D8 is too vague 😞 😞

**Comment by klonos** [comment]
I'm closing this issue here, but @serundeputy do you think it'll be a good idea to file an issue over in the Backdrop core queue, or ignore till (if ever) it happens again?
