### ISSUE TITLE
Option to not include code when using kbox push/pull 

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1786]
Feature/Enhancement Request
===========================

Unsure if this is a feature request or support request....When doing kbox push or pull, you have the option of sending/receiving the database or files directory, however, the code gets pushed/pulled no matter what. In the push action, changes you haven't committed, get committed and pushed. There are many instances where you may only wish to push/pull the database and/or files.

Please provide some detail on how Kalabox can help solve this problem

You could prompt the user if they want the code moved when prompting for if the user wants the database or files moved. Another option would be to have a command line directive like --no-code

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
