### ISSUE TITLE
Cannot disable CSS or JS aggrigation in admin UI D8

### ISSUE THREAD

**Issue by macronomicus** [kalabox/kalabox#1788]
I've got a weird one! lol ...never seen this before.

Bug Report
==========
Latest KBOX Release on Windows 10 Pro
Have you previously installed Kalabox?  Yes, all of them.
Does this bug prevent you from using Kalabox?  No

The checkboxes on Performance Page (latest Drupal 8) are greyed out so you cant turn off JS or CSS aggregation, there is a warning that file system isnt setup, but it clearly is, and is working, its a symlink as you know, this may be whats throwing things off.

Does anyone else get this? 
I did find a workaround, using drush you can disable them.
```
kbox drush -y config-set system.performance css.preprocess 0
kbox drush -y config-set system.performance js.preprocess 0
```

**Comment by macronomicus** [comment]
Hmm.. this is likely related to the following issue which I also get the same prob.
#1740

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
