### ISSUE TITLE
Curl another kbox instance from within kbox.

### ISSUE THREAD

**Issue by shawnmmatthews** [kalabox/kalabox#1790]
I'm not sure if this falls under a bug or a feature request, but I'm not capable of using curl from within a Drupal8 or pantheon kbox instance.

I'm running macOS Sierra with 2.1.3.

From my native machine I can curl either site1.kbox.site or site2.kbox.site, but can't get them to curl one another. It always returns a 7 error.

cURL error 7: Failed to connect to site1.kbox.site port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 7: Failed to connect to edge.site1.kbox.site port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I've run into this same situation when trying to grab data internally from a webservice as well.

My current steps to reproduce are as follows.

Build two sites using kbox create pantheon.
Load the deploy suite and relaxed module. 
Set relaxed via the ui to curl information from site1.kbox.site from site2.kbox.site and fail due to a connection issue.

I've also noted that I fail with the same error when trying to just run kbox . curl http://site1.kbox.site from within either instance, but that I can curl either from my native environment.

I reviewed the issues log and didn't see anything that pertained to this exact issue.

I followed the advice of https://github.com/kalabox/kalabox/issues/1090 to see if any of the ports were that needed to be updated within config/nginx/drupal8.conf, but it didn't look related.

Any help would be greatly appreciated!

Best,
Shawn

**Comment by erikgoetze** [comment]
I am seeing the exact same issue, but on two Macs running El Capitan. Each one has a Pantheon app cloned recently and is running Kalabox 2.1.3. 

The Drupal site in question is running fine on both. 

I wouldn't normally care about curling from inside the app but I'm trying to use the Behat plugin for Kalabox and none of the tests work due to this error.

**Comment by pirog** [comment]
Two things to note here:

1. You need to use dockers `extra_hosts` compose option to make sure two compose projects are aware of one another
2. If you are curling over HTTPS you will need to make sure you handle the fact that kalabox certs are self signed

**Comment by kmoylan** [comment]
I am seeing a similar issue as originally stated but with just a single site.   I cannot curl a D8 site from within it's own kbox instance.  This make running behat tests impossible because behat utilized curl under the covers and I'm getting connection refused.

**A simple curl example**
> $ kbox . curl mysite.kbox.site
curl: (7) Failed to connect to mysite.kbox.site port 80: Connection refused

This is with kbox version 2.1.3 running on OSX El Capitan with a drupal site built from Pantheon.

**Comment by pirog** [comment]
@kmoylan did you take into account https://github.com/kalabox/kalabox/issues/1790#issuecomment-286595242? Note that your app might be set up to globally redirect traffic over `https`. Definitely could also just try pinging `localhost` for a sanity check.

**Comment by kmoylan** [comment]
I did look at #1790.  
I'm not using https.  
I added extra_hosts to my kalabox-compose.yml for the appserver and restarted  kbox, but didn't see the changes in /etc/hosts when I did
`$kbox . cat /etc/hosts`.  
Should I have added extra_hosts to another server?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
