### ISSUE TITLE
Unable to install Kalabox on Windows 10 virtualization error

### ISSUE THREAD

**Issue by SamStamport** [kalabox/kalabox#1791]
When Kalabox install gets to the point of installing Docker I get "Hardware assisted virtualization and data execution protection must be enabled in the BIOS." Virtualization is turned on in BIOS and in Win 10.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
