### ISSUE TITLE
Add SSL to Kalabox.io

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1792]
Bug Report
==========

Currently we don't have an SSL cert installed on kalabox.io...a professional project deserves better!

**Comment by wturnerharris** [comment]
+1 - even if it's only provided on paid subscriptions.

**Comment by wturnerharris** [comment]
@pirog - been watching this. Does this mean SSL is more reliable in kbox, or does this apply to lando?

**Comment by pirog** [comment]
@wturnerharris this issue was actually to get a cert up for our kalabox.io website. SSL is available out of the box for all lando apps though. 

It does require some set up if you are using some of our non-php start states eg node or ruby but it should be painless for php.
