### ISSUE TITLE
Error standing up new kalabox pantheon environment

### ISSUE THREAD

**Issue by oppodeldoc** [kalabox/kalabox#1793]
Bug Report
==========
**What is your Kalabox version and operating system?**
v2.1.3 running on Mac OSX El Capitan (10.11.6)
Running Docker for Mac 1.12.3

**Have you previously installed Kalabox? If so, what version?**
Nope

**Give a brief description of what happened, including any error messages that appeared.**
Trying to pull down a relatively massive WordPress multisite installation for the first time from Pantheon via the `kbox create pantheon` site, I get one strange warning whenever I run the kbox command but otherwise everything seems to pull properly:
```bash
WARNING: REQUIRE ==> OH NO! It looks like something is wrong with your kalabox-plugin-pantheon app named projectname. We recommended purging this app and reinstalling it. This should help get it back into the correct state.
```

Then, I get a series of errors after these lines:
```bash
Pulling image drush/drush.
Pulling image kalabox/pantheon-appserver.
```
Here's the error output:
```bash
ERROR: for web  Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/Users/XXXXXXX/XXXXXX/config/nginx/.conf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/df665dee9ae69f4269dc40d581b420dcf7ba1b8325897914efbfa14939b9d515\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/df665dee9ae69f4269dc40d581b420dcf7ba1b8325897914efbfa14939b9d515/etc/nginx/conf.d/default.conf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"

ERROR: for appserver  Image 'kalabox/pantheon-appserver:' not found

ERROR: for drush  Image 'drush/drush:' not found
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 62, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
compose.service.NoSuchImageError: Image 'kalabox/pantheon-appserver:' not found
docker-compose returned -1
```
I've tried completely re-installing, rolling back docker to earlier versions, etc. No dice. 

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**
This might be specific to our Pantheon project but all I did to reproduce this bug is run `kbox create pantheon`

**Does this bug prevent you from using Kalabox?**
Definitely.  All the services except nginx seem to be running after a `docker ps`:

```
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                     NAMES
fc6b6bcb86b3        mariadb:10.0                         "docker-entrypoint.sh"   11 minutes ago      Up 11 minutes       0.0.0.0:32770->3306/tcp   projectname_db_1
d2d3a6fb280d        kalabox/pantheon-solr:hyperion5000   "/bin/bash /start.sh"    11 minutes ago      Up 11 minutes       449/tcp                   projectname_solr_1
c2a80423e730        kalabox/unison:2.49                  "/run.sh"                11 minutes ago      Up 11 minutes                                 projectname_unison_1
6c469632f528        redis:2.8                            "docker-entrypoint.sh"   11 minutes ago      Up 11 minutes       6379/tcp                  projectname_redis_1
```

Thanks in advance for your help!

**Comment by oppodeldoc** [comment]
@pirog Update on this: I was able to get a Kalabox instance running on a totally different Pantheon project, but this one is still broken. There are a few major differences:
1. The broken project is much newer on Pantheon
2. The working project is a standard WordPress installation, the broken instance is a huge WP Multisite installation. 

Any insight here would be great, thanks!

**Comment by pirog** [comment]
@oppodeldoc on that first site it looks like maybe you had a borked install? have you made sure to purge any lingering folders for that app before reinstalling? also might be worth pulling again with a different name. Does that site use nested docroot? Currently do not support that feature.

**Comment by oppodeldoc** [comment]
Thanks for the response @pirog! I've tried doing this from two different machines from scratch, re-installing, etc. Still the same problem. The thing is, as soon as I run `kbox create pantheon` and I select the project in question, I get that error:
```
WARNING: REQUIRE ==> OH NO! It looks like something is wrong with your kalabox-plugin-pantheon app named projectname. We recommended purging this app and reinstalling it. This should help get it back into the correct state.
```
And it fails as before.  Can you clue me in as to what might cause that error message? There's no real helpful feedback that I can find, also searching issues has turned up nothing. Pantheon support said I should ping you guys about this...

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
