### ISSUE TITLE
Missing `NONCE_KEY` in environment variables for Pantheon sites

### ISSUE THREAD

**Issue by ataylorme** [kalabox/kalabox#1794]
[Pantheon's `wp-config.php`](https://github.com/pantheon-systems/WordPress/blob/master/wp-config.php#L61) makes use of `$_ENV['NONCE_KEY']`, which is undefined in Kalabox.

```
Notice: Undefined index: NONCE_KEY in /code/wp-config.php on line 138

Call Stack:
    0.0021     375344   1. {main}() /code/index.php:0
    0.0021     375632   2. require('/code/wp/wp-blog-header.php') /code/web/index.php:6
    0.0021     375984   3. require_once('/code/wp/wp-load.php') /code/web/wp/wp-blog-header.php:13
    0.0021     376920   4. require_once('/code/wp-config.php') /code/web/wp/wp-load.php:42
```

**Comment by ataylorme** [comment]
Copying `NONCE_SALT: $KALABOX_APP_PANTHEON_NONCE_SALT` to `NONCE_KEY: $KALABOX_APP_PANTHEON_NONCE_KEY` in `kalabox-compose.yml` and rebuilding didn't work. Neither did hard-coding a value for `NONCE_KEY` in `kalabox-compose.yml`.

**Comment by pirog** [comment]
@ataylorme which kalabox-compose.yml are you editing? AFAIK that should work but you need to make sure its in the correct kalabox-compose.yml eg the one in your app.

**Comment by ataylorme** [comment]
> that should work

Hard coding or using `$KALABOX_APP_PANTHEON_NONCE_KEY`?

> you need to make sure its in the correct kalabox-compose.yml eg the one in your app.

Yup, it's the one in my app.

**Comment by pirog** [comment]
@ataylorme i'd hardcode it for now just to make sure. After you rebuild i'd try doing a `docker inspect APPNAME_appserver_1` to see if that new ENVVAR shows up correctly.

**Comment by ataylorme** [comment]
Weird, I'm seeing

```
"NONCE_SALT=22bd78fb0918002a57eae392038346e1e41520469e3884e0af4cac7b0f9042c3",
"KALABOX=ON",                "DRUPAL_HASH_SALT=fad5cfeb464e3cb6d2a72bfe290d84e25478753824970a9455f5cb350a9f8183",
"PANTHEON_SITE_NAME=pantheon-wp-best-practices",
"NONCE_KEY=D-dl.FGjx#KXkX-huzf 1!J?#bR7^+17us{@c7xd~T-uD;+>fPA8V5]h_aYO?on6",
```

with `docker inspect pantheonwpbestpractices_appserver_1` but it's still showing undefined as a notice.

I'm sure I'll be able to get my local going just wanted to give you a heads up about the missing definition for future versions of Kalabox.

**Comment by pirog** [comment]
how are you trying to grab it on the php side?

**Comment by ataylorme** [comment]
The Pantheon `wp-config.php` does `define('NONCE_KEY', $_ENV['NONCE_KEY']);`

With it hard-coded in `kalabox-compose.yml` it's showing up in the docker inspect but not in the `$_ENV` global on the PHP side.

**Comment by pirog** [comment]
@ataylorme there is a `prepend.php` in your app's `config/php` folder that might be worth looking at!

**Comment by ataylorme** [comment]
Thanks @pirog - adding it to `config/php/prepend.php`, along with the above, did the trick

**Comment by pirog** [comment]
@ataylorme awesome! will be great to get this bundled into the product eventually

**Comment by pirog** [comment]
**Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!**
