### ISSUE TITLE
Email doesn't work

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#1795]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox 2.1.3 on Mac OS X 10.12.3

Have you previously installed Kalabox? If so, what version?

Most of the prior versions.

**Tell us about your bug**

For a Pantheon Drupal 7 site, I get an error when the site attempts to send an email. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1)kbox create pantheon for a D7 site
2)Go to foo.kbox.site/user/password and enter a username
3)You will see a Drupal error message "Unable to send e-mail. Contact the site administrator if the problem persists." The log shows 2 errors saying "Error sending e-mail (from xxx@yyy.com to zzz@hhh.com). Installing the SMTP module doesn't appear to help.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using Kalabox?
Not completely

**Comment by ckng** [comment]
Same issue with D8.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
