### ISSUE TITLE
The dependency "engineConfig" was NOT found!

### ISSUE THREAD

**Issue by lmakarov** [kalabox/kalabox#180]
I'm getting an error message after a fresh install of kalabox: `The dependency "engineConfig" was NOT found!`

Steps:

```
$ npm install kalabox -g
$ kbox create drupal
? What will this app be called: my-drupal-app
? What major version of drupal: 7
? Php version? 5.5.24
? Major Drush version? 7
? Git username? ...
? Git email? ...
...
App instantiated! Run kbox install and kbox start inside your app
$ cd my-drupal-app
$ kbox install
The dependency "engineConfig" was NOT found!
```

System information:
* OSX 10.10.3
* nodejs v0.10.30
* npm v1.4.23

**Comment by pirog** [comment]
You need to run kbox provision after the npm install and before the kbox
create

On Tuesday, May 19, 2015, Leonid Makarov <notifications@github.com> wrote:

> I'm getting an error message after a fresh install of kalabox: The
> dependency "engineConfig" was NOT found!
>
> Steps:
>
> $ npm install kalabox -g
> $ kbox create drupal
> ? What will this app be called: my-drupal-app
> ? What major version of drupal: 7
> ? Php version? 5.5.24
> ? Major Drush version? 7
> ? Git username? ...
> ? Git email? ...
> ...
> App instantiated! Run kbox install and kbox start inside your app
> $ cd my-drupal-app
> $ kbox install
> The dependency "engineConfig" was NOT found!
>
> System information:
>
>    - OSX 10.10.3
>    - nodejs v0.10.30
>    - npm v1.4.23
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/180>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by lmakarov** [comment]
Yep, just figured it out after re-reading the docs... Thanks!

**Comment by cleaver** [comment]
Just a note... I had run `kbox provision` and still received this error. I was on flakey airport wifi at the time, but I ran the provision again and it works.

**Comment by pirog** [comment]
Good to know. Likely just had an interrupted DL if you were on WTFWIFI.

`kbox provision` also actually functions as a global update command. So you
should be able to do `npm install -g kalabox` to get new codes and then
another `kbox provision` to update syncthing, your container images, etc.

On Tue, May 19, 2015 at 8:30 AM, Cleaver Barnes <notifications@github.com>
wrote:

> Just a note... I had run kbox provision and still received this error. I
> was on flakey airport wifi at the time, but I ran the provision again and
> it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/180#issuecomment-103552877>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
