### ISSUE TITLE
UX Improvement: Hover cursor should not be pointer for inactive sites

### ISSUE THREAD

**Issue by acobster** [kalabox/kalabox#1800]
As a Kalabox user working on multiple sites at any given time, I want the hover cursor for inactive (not running) sites to reinforce the fact that the such sites aren't running.

For example, when I first start Kalabox, no sites are running. Hovering over any of them results in a pointer cursor, which I instinctively associate with the site being clickable/browsable. I would expect inactive sites to instead have the `default` or `not-allowed` cursor.

**Comment by pirog** [comment]
@acobster interesting. i *think* i know what you are saying but maybe you can post up a screenshot?

**Comment by acobster** [comment]
Sure!

![Kalabox screenshot](http://i.imgur.com/jXIHIEn.png)

**Comment by pirog** [comment]
@acobster perfect! thanks much!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
