### ISSUE TITLE
Creating sites from Pantheon gets stuck at the database step and almost never works

### ISSUE THREAD

**Issue by kamkejj** [kalabox/kalabox#1802]
The info I have to start with is sparse, but hopefully someone will be able to help me with the info to get debugging data to post and possibly figure out why I can almost never create a working Pantheon site. Any help with getting this figured out is appreciated.

OS: macOS Sierra 10.12.4
Computer: mid 2015 iMac with 32 GB Ram
Kalabox: 2.1.3
Docker: Community Edition Version 17.03.1-ce-mac5 (16048)
Channel: stable
b18e2a50cc

I know there are other issues that seem to be similar to mine, but haven't found any resolutions that fix my issues. 

Steps with command line:
1. Run kbox create pantheon
2. choose my site
3. Pulls the screenshot
4. Pulls the code
5. Pulling Database
6. Hangs on Pulling Database

No error messages.

If I leave it for several hours it doesn't seemingly doesn't make any progress and sits at this step. I eventually have to close the terminal. If go back back and do a `kbox pull` the same thing happens by getting stuck on the Pulling Database step. This is the main issue I'm having with Kalabox. Very rarely I can get some site to pull and work, but when a site fails at the database step it always fails at this step and never works.

What do I need to run to get debugging info or logging info to post here?

Thanks

**Comment by kamkejj** [comment]
Got this error when creating a site from Pantheon running
`kbox create pantheon -- --verbose --debug`

`debug: EVENTS ==> Error dispatching event listeners [pre-create-configure]: Failed after 5 retries. {"max":5,"backoff":500}: Not found.

Error dispatching event listeners [pre-create-configure]: Failed after 5 retries. {"max":5,"backoff":500}: Not found.

VError: Failed after 5 retries. {"max":5,"backoff":500}: Not found.

    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/promise.js.jx:70:17
    at process._tickCallback (node.js:917:13)
error:  VError: Error dispatching event listeners [pre-create-configure]: Failed after 5 retries. {"max":5,"backoff":500}: Not found.

    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/core/events.js.jx:150:11
    at process._tickCallback (node.js:917:13)
debug: METRICS ==> Reporting. action=error, message=Error dispatching event listeners [pre-create-configure]: Failed after 5 retries. {"max":5,"backoff":500}: Not found.
, stack=VError: Failed after 5 retries. {"max":5,"backoff":500}: Not found.

    at /Applications/Kalabox.app/Contents/MacOS/bin/lib/promise.js.jx:70:17
    at process._tickCallback (node.js:917:13), tags=[], mode=cli, devMode=false, version=2.1.3, type=Darwin, platform=darwin, release=16.5.0, arch=x64, nodeVersion=v0.10.40, created=2017-05-08T20:12:05.691Z`

**Comment by kamkejj** [comment]
Ran this again `kbox create pantheon -- --verbose --debug` with no errors I can see, but only a few of the database tables actually imported.

**Comment by kamkejj** [comment]
Ran `kbox pull` and pulled only the database. Finished with
`debug: SHELL EXEC ==> Running command "goodwayd8_terminus_run_2\n"
Cache rebuild complete.                                              [ok]
debug: EVENTS ==> Emitting event [post-engine-run]. unknown
debug: EVENTS ==> No listeners [post-engine-run].
debug: EVENTS ==> Finished dispatching event listeners [post-engine-run].`

There are still missing tables in the database. For what ever reason it's not actually pulling the database or times out or something.

**Comment by pirog** [comment]
@kamkejj id exam your kbox logs and see if you can find the exact point where the db pull command happens and if there is any worthwhile output there

**Comment by rickmanelius** [comment]
FWIW, I get something similar when going through the GUI. Installed kbox 2.1.3, opened up the app, created a new site, and getting the "VError: Failed after 5 retries. {"max":5,"backoff":500}:" message.

**Comment by kamkejj** [comment]
@pirog I'll have to figure out where the logs are.

**Comment by pirog** [comment]
@kamkejj http://docs.kalabox.io/en/v2.1/troubleshooting/

**Comment by kamkejj** [comment]
@pirog The log after running kbox create pantheon -- --debug

I don't know what to look to determine what's useful.

[kbox-create-log.txt](https://github.com/kalabox/kalabox/files/1053518/kbox-create-log.txt)

**Comment by kamkejj** [comment]
Also only about a quarter of the database tables actually imported.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
