### ISSUE TITLE
am I able to connect to WebEnabled with this tool?  kbox version 2.1.3 on Ubuntu 16.04 connecting to other staging sites beside Pantheon

### ISSUE THREAD

**Issue by fndtn357** [kalabox/kalabox#1803]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

*Example: v0.12.0-beta1 on Windows 8.1 Professional*

Have you previously installed Kalabox? If so, what version?

*Example: Yes, I've installed Kalabox v0.12.0-alpha4*

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

*Example: I tried to create a pantheon site but got a `LowerCase` not defined exception*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

> 1. Started up GUI
> 2. Clicked on my Pantheon account in the sidebar
> 3. Selected a site and an environment
> 4. Kept the default create options and pressed submit

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Does this bug prevent you from using Kalabox?

Feature/Enhancement Request
===========================

Please explain your request and its importance in the form of a user story.

*Example: As a Kalabox user who works with Drupal sites that have large databases, I want the option to exclude unnecessary database tables from being pulled when I update my site because I want faster "site pull" actions.*

Please provide some detail on how Kalabox can help solve this problem

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Comment by fndtn357** [comment]
kbox version 2.1.3 on Ubuntu 16.04
connecting to other staging sites beside Pantheon

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
