### ISSUE TITLE
Cannot pull the DB from Pantheon VIP sites

### ISSUE THREAD

**Issue by dalin-** [kalabox/kalabox#1804]
Pantheon has additional security in place for sites on the VIP tier.  MySQL must use a TLS connection with the server.  
https://pantheon.io/docs/ssh-tunnels/#create-secure-connection-to-mysql-using-tls

Without this in place, you get the following error:

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Got error: 2003: "Can't connect to MySQL server on 'dbserver.dev.badd' at line 1
```

I tried to patch `module.exports.mysqlDumpCmd()` to add the `--ssl` flag, but this must not be the right place to do this.  When I run `kbox pull` The command printed to the screen is:
`mysql --user=pantheon --password=[redacted] --database=pantheon --host=dbserver.dev.[redacted].drush.in --port=[redacted]`
Which does not match what's in that method.

**Comment by pirog** [comment]
@dalin- i think its because that command is being generated with drush and what you are using is the fallback command. either way i think we need to get the spec from pantheon on how this works so we can support it.
