### ISSUE TITLE
Updating Docker to 17.03.1-ce-win10 Breaks Kalabox Functionality

### ISSUE THREAD

**Issue by AaronFeledy** [kalabox/kalabox#1805]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

2.1.3 on Windows 10 Pro

**Tell us about your bug**

Today, Docker prompted me to update to 17.03.1-ce-win10 (11972). This update is described as containing a hotfix that "Fixes a security issue related to Docker Daemon exposure on tcp://127.0.0.1:2375 (exposing daemon on tcp, is now an opt-in feature)." This hotfix seems to block Kalabox's main communication channel with Docker causing ECONNREFUSED errors when executing kbox commands or using the GUI to interact with an app.

The workaround is to enable the new option "_Expose daemon on tcp://localhost:2375 without TLS_" that exists in the Docker settings dialog under the _General_ tab. Doing so will allow Kalabox to successfully interact with Docker.

**Comment by pirog** [comment]
I'm hoping all we will need to do here is switch the engine settings for win to a secure channel
https://github.com/kalabox/kalabox/blob/v2.1/plugins/kalabox-engine-docker/provider/docker/engine.js#L221

**Comment by hades200082** [comment]
Same issue here on fresh install of Kalabox on Windows 10.

**Comment by pirog** [comment]
We've added support for the secure channel to our successor project "lando"
https://github.com/kalabox/lando/blob/master/lib/daemon.js#L211

Until that is out the door, we recommend people use the workaround posted by @AaronFeledy

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
