### ISSUE TITLE
View Kalabox site from different machine on local network?

### ISSUE THREAD

**Issue by LordPachelbel** [kalabox/kalabox#1807]
I'd like to run a Kalabox site on my machine and let people view it from within our local network.

In Hyper-V I see that Docker's virtual network switch (called DockerNAT) is set to "Internal only." I can't change its connection type to "External network" because my ethernet adapter is already assigned to another virtual network switch that is used by other VMs on my machine.

To do what I want, is it as simple changing a setting in Docker or in the Kalabox container to use that other virtual network switch? If so, where is that stuff configured?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
