### ISSUE TITLE
HTTP request took too long to complete; consider setting COMPOSE_HTTP_TIMEOUT to a higher value

### ISSUE THREAD

**Issue by skye-va** [kalabox/kalabox#1809]
What is your Kalabox version and operating system?
v2.13, Mac OS Sierra

Have you previously installed Kalabox? If so, what version?
Yes, v2

1. Tried to start/restart app (kbox restart)
2. Got repeated timeouts:

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

```

Does this bug prevent you from using Kalabox?
Yes, can't start site

Feature/Enhancement Request
===========================

As a Kalabox user, I would like to know where and how I can set COMPOSE_HTTP_TIMEOUT to a higher value.

I have looked through the documentation but can't figure out where this would go.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
