### ISSUE TITLE
ECONNREFUSED 127.0.0.1:2375

### ISSUE THREAD

**Issue by travisbutterfield** [kalabox/kalabox#1810]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
bug fix, pantheon, php
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Kalabox version 2.1.3. Windows 10 Enterprise version 1607 (OS Build 14393.447)

Have you previously installed Kalabox? If so, what version?
No

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

I have tried several times to connect to a site on Pantheon and keep getting the following error message: "VError: Failed after 5 retries. {"max":5,"backoff":500}: Error querying docker for list of containers.: connect ECONNREFUSED 127.0.0.1:2375."

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Started up GUI
2. Clicked on the Add New Site box with the plus sign
3. Selected my Pantheon account in sidebar
4. Waited for the list to refresh
5. Clicked on any of the sites listed
6. Waited while Kalabox contacted Pantheon
7. Left all options at the default values (pulling Dev code, files, and database)
8. Clicked Submit
9. Waited about 5 or 10 seconds while the new box said "Creating"
10. Clicked on the error notification icon
11. Read the error message: " VError: Failed after 5 retries. {"max":5,"backoff":500}: Error querying docker for list of containers.: connect ECONNREFUSED 127.0.0.1:2375"
12. Waited several minutes to see if somehow Kalabox might resolve the error and connect. 
13. Clicked on the X at the top right to exit the application, as it seems to be permanently stuck at the "Creating" stage.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Possibly. It seems to be some kind of configuration mismatch, possibly with the port number? Or maybe a firewall or proxy problem? The error message is kind of vague, so I'm not sure how to troubleshoot it. I have restarted Kalabox, Docker, and my computer several times while troubleshooting. Perhaps some documentation about how to make Kalabox (or Docker?) able to access a localhost server might be useful, because it seems like that's where the error is happening. 

Does this bug prevent you from using Kalabox?
Yes

**Comment by not-original** [comment]
Was about to post the exact same issue.  Windows 10 Pro, fresh install of Kalabox and Docker, connected to Pantheon just fine, selected a site to pull down, and received the notification error:

VError: Failed after 5 retries. {"max":5,"backoff":500}: Error querying docker for list of containers.: connect ECONNREFUSED 127.0.0.1:2375

The 'adding site' continues to spin with no result.  Tried rebooting several times, as well as turning off firewall, but no joy. 

Any help at all appreciated.

**Comment by not-original** [comment]
So, reading another issue:
https://github.com/kalabox/kalabox/issues/1805

I saw that if you go to docker general settings, and check
Expose daemon on tcp://localhost:2375 without TLS

Then it appears to connect.  However, I continue to get the error:
VError: Failed after 5 retries. {"max":5,"backoff":500}:

I have tried starting/restarting docker several times, and still can not get my files to pull down from Pantheon.

**Comment by not-original** [comment]
More follow up, tried installing through CLI, and found that the error is:

Starting kalabox_proxy_1
ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint kalabox_proxy_1 (db2d95c388bd7603f1bc9e600459e05045277b888d7dd7b56df540b0964ee48a): Error starting userland proxy: Bind for 127.0.0.1:80: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.
Starting kalabox_proxy_1 (etc, tries 5 times and then fails).

So not sure where to set permissions to allow my system to start the kalabox_proxy

**Comment by not-original** [comment]
OK, so I found my issue.  Maybe it will help others. 

I had Windows IIS installed for some other sites I develop.  This was using/tied into port 80 localhost.  I changed it in IIS to 8080, and then could finally connect and pull down my code/files using Docker/Kalabox. 

In addition, in Docker I also changed to the google proxy (8.8.8.8) -- since I wasn't able to do the docker hello-world until I made that change. 

So, hoping that might help! Good luck.

**Comment by travisbutterfield** [comment]
> I saw that if you go to docker general settings, and check
Expose daemon on tcp://localhost:2375 without TLS

Not-original's comment referenced above did the trick for me. Thanks for the help! :-)

**Comment by travisbutterfield** [comment]
Although, I'm not super happy about having to make my computer less secure in order to get things to work... Hopefully Docker will figure out a better way of doing things so that it will work in a more secure environment.

**Comment by pirog** [comment]
@travisbutterfield versions of lando (https://github.com/kalabox/lando), which is kalaboxs successor project, will connect on windows via a socket which is pretty secure. 

all that said, we are talking about how your computer talks to itself here so while security is nice it might not be as bad as you think.
