### ISSUE TITLE
Client version is too old

### ISSUE THREAD

**Issue by wickedurge** [kalabox/kalabox#1811]
Please complete the following steps. **The more steps you complete the more
likely we are to address your issue!**

1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate.
2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

kalabox 2.1.3 on Windows 10 Pro

Have you previously installed Kalabox? If so, what version?

No

**Tell us about your bug**

1. Opened GUI
2. Clicked on pantheon account
3. Selected site
4. Started site
5. Ran through 'starting', 'starting containers', etc. Then stopped abruptly.
6. Tried starting through kbox CLI
7. Ran ``kbox sitename start``
8. Error message; ``ERROR: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version``

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Perhaps. I don't believe I've missed anything from the documentation. 

Does this bug prevent you from using Kalabox?
Yes. I can't start my local environment so kalabox if of no value right now. Which is a bummer, because I'm super excited about using it.

**Comment by pirog** [comment]
@wickedurge i'd check out the kalabox successor project, https://github.com/kalabox/lando, getting pretty close to a cli beta and works well with the latest docker for windows.

if you want to continue working with kalabox im guessing youll need to use the version of docker for windows that ships with kalabox vs the latest one.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
