### ISSUE TITLE
Local Site Won't Update With File Changes

### ISSUE THREAD

**Issue by dwalsh289** [kalabox/kalabox#1812]
Currently developing on a wordpress site locally through Kalabox. It has been great, but it stopped using the new files I'm changing to style the site, bricking the whole operation. Any changes to fix something in the files are not reflected in browser upon refresh or hard refresh/empty cache. 

It seemed to occur around when I missed a git push by a colleague and needed to do some git stuff to fix the issue I made for myself. The site hasn't been the same since. Currently, the files are all squared up with the remote version and it is pulling/pushing the correct, new information without problem. This has been accomplished since migrating to the command line git anyway, the options > push pull doesnt work at all either. 

It's strange and frustrating making changes and seeing them up on the remote version via pantheon but not being reflected in the local one through kalabox. I am working in the correct root directory. 

Has anyone had this issue before? I didn't see anything similar using the search bar.

**Comment by pirog** [comment]
@dwalsh289 if you are having issues with file syncing i'd check out the kalabox successor project https://github.com/kalabox/lando, a few weeks away from a beta but has significant improvements in file sharing/syncing

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
