### ISSUE TITLE
Where to download 2.0 version of Kalabox?

### ISSUE THREAD

**Issue by slefevre** [kalabox/kalabox#1817]
I'm a contractor at a new position. The workstations at this place are running Windows 7. I am looking at installing Kalabox, and the current version, v2.1.3, seems to have Windows 10 as a requirement. (HyperV only seems to be supported in Windows 10 https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v )

The current installation instructions indicate that earlier version support older systems (http://docs.kalabox.io/en/stable/general/sysreq/) I found instructions for Kalabox v2.0 which says it's compatible with Windows 7. http://docs.kalabox.io/en/v2.0/general/sysreq/ . But, the download link only seems to offer the current version. 

Where can I download earlier versions of Kalabox?

**Comment by justinffs** [comment]
https://github.com/kalabox/kalabox/releases/tag/v2.0.0

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
