### ISSUE TITLE
Broken link to website in Ubuntu Software installer

### ISSUE THREAD

**Issue by chrowe** [kalabox/kalabox#1818]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
Kalabox 2.1.3 on Ubuntu 17.04

Have you previously installed Kalabox? If so, what version?
No

**Tell us about your bug**

The "Website" button in the Ubuntu Software installer GUI links to https://www.kalabox.io/ (ssl/tls) which is a dead link. I assume the best fix here is to enable https on the site. 

It looks like this is set at https://github.com/kalabox/kalabox/blob/v2.1/scripts/env.sh#L11 if https ins not desired.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
No

Does this bug prevent you from using Kalabox?
No

**Comment by pirog** [comment]
@chrowe good to know. def would take a PR on fixing this
https://github.com/kalabox/kalabox/blob/v2.1/scripts/env.sh#L11 (probably just want to make it `https://kalabox.io` for now

Also, if you are interested in helping out on Lando, probably want to do the same over ther eas well
https://github.com/kalabox/lando/blob/master/scripts/env.sh#L11 (probably want to use `https://docs.lndo.io` over there for now

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
