### ISSUE TITLE
Start project with 'composer create-project'

### ISSUE THREAD

**Issue by chrowe** [kalabox/kalabox#1821]
Feature/Enhancement Request
===========================

As a developer starting a new project, I want to use composer to create my project based on a distribution like https://www.drupal.org/project/lightning or https://github.com/zivtech/bear so that I can use their recommended installation instructions

I know I can do this manually now by running `composer create-project` and then following steps like https://github.com/kalabox/kalabox/issues/1402 or https://github.com/kalamuna/kalastack/wiki/Usage-Importing-a-preexisting-Drupal-Site but it would be nice if there was a way to just run on the command line via with a `kbox` command in place of `kbox create drupal8`

**Comment by pirog** [comment]
@chrowe we are not taking feature requests for kalabox anymore... that said, lots of work happening on the kalabox successor project over at https://github.com/kalabox/lando including lots of consideration about how to use composer-based workflows. beta release with lots of docs within the next week or so. if you are in the kalabox slack group feel free to join the #lando channel. 
https://slackpass.io/kalabox

id generally ignore any docs you read on any kalamuna related sites, they are likely WAY out of date
