### ISSUE TITLE
Missing environment variable & certificate when bulk indexing Pantheon Solr.

### ISSUE THREAD

**Issue by mindgrub-jcorrao** [kalabox/kalabox#1822]
1. Please review the [current list of issues](https://github.com/kalabox/kalabox/issues) to make sure you are not submitting a duplicate. 

_I have reviewed the issues tracker and could not find this specific issue when searching the text and related pieces of my issue. If I missed something, then feel free to close/delete this ticket and apologies in advance._

2. Please tag your issue appropriately. Please review the [tagging criteria](https://github.com/kalabox/kalabox/blob/HEAD/CONTRIBUTING.md).
3. Based on the issue type tag selected above please fill in the relevant section below.

_bug fix, pantheon_

Bug Report
==========
**Tell us about your setup**
_Installed Kalabox, pulled an existing Professional tier site via the "add site" button in Kalabox. I am specifically working based off of a multidev environment of this site._

What is your Kalabox version and operating system?
_I am running Kalabox 2.1.3 on Mac OS Sierra._

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

_Utilizing the Search API Solr module in conjunction with Pantheon search causes an error during reindexing._
```
Notice: Undefined index: HOME in pantheon_apachesolr_certs_dir() (line 173 of /code/modules/pantheon/pantheon_apachesolr/pantheon_apachesolr.module).
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Have `apachesolr`, `pantheon_apachesolr`, `search_api `, and `search_api_solr` installed.
2. Post an Apache 3.x schema to Solr from within Kbox
3. Have a basic server/index set up, then go to `/admin/config/search/search_api/index/NAME_OF_INDEX`
4. Queue/delete all items for indexing, then run "Index Now" to trigger the reindexing bulk operation.
5. Each page/chunk of the bulk operation fires the error I quoted above.

**Tell us more**

* The function in the error is looking for an environment variable: `$_ENV['HOME']`, which does not seem to ever be defined in perpend.php or any of the settings.php files in my project.
* Also, it is looking in that HOME path for a `binding.pem` file, which is not located anywhere in the files in the KBox setup.

**Could better documentation have prevented this issue? if so what should we change?**

_If pulling a PEM file, or any form of manual definition of $\_ENV['HOME'] is needed, then documentation (Referenced in the Pantheon Solr section) would be useful._

**Does this bug prevent you from using Kalabox?**

_It does not prevent reindexing oddly enough, but it still seems like something is missing that shouldn't be in terms of the errors being logged._

**Comment by pirog** [comment]
@mindgrub-jcorrao a php notice is not really an error so im sure this is probably fine esp if you are able to index. 

we've also provided `HOME` in our successor project lando. might also be worth posting an issue in the pantheon upstream since they should probably check for the existence of `HOME` in the code over there.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
