### ISSUE TITLE
Drupal 8 page redirect loop

### ISSUE THREAD

**Issue by jlly-crs** [kalabox/kalabox#1823]
Bug Report
==========

What is your Kalabox version and operating system?
2.1.3 on Windows 10 Pro

Have you previously installed Kalabox? If so, what version?
Yes, same version

**Tell us about your bug**

1. GUI was running, two other sites currently up.
2. Clicked on my Pantheon account in the sidebar
3. Selected the site and an environment
4. Kept the default create options and pressed submit
5. Got this error on site creation at some point:  Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.14/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E
6. Navigate to new site, home page renders properly.
7. Tried to navigate to login page for local site, the browser returns: ERR_TOO_MANY_REDIRECTS, and the URL is: http://mysite.kbox.site/user/login?q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login&q=user/login

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Not sure, if there's something I need to do besides the standard flow for a Pantheon Drupal 8 site and logging on to the standard login page I'm not aware of it, but maybe that's the problem.

Does this bug prevent you from using Kalabox?

For this case-use, yes, other sites (Drupal 7 for the others running right now) are continuing to behave normally.

**Comment by jlly-crs** [comment]
Okay, follow-up, it's not specifically the login page. Content pages I know exist in the site are resulting in the same behavior, with the URL parameters repeating as well.

**Comment by stephencross** [comment]
I'm having the same issue.  Any resolution?

**Comment by MichaelRobertson93** [comment]
I had a similar problem for a while, but my old supervisor found that replacing: 
`  location @cleanurl {
      rewrite ^/(.*)$ /index.php?q=$1  last;
  }`

with:
`  location @cleanurl {
      rewrite ^/(.*)$ /index.php  last;
  }`

On line 82 of _/config/nginx/drupal8.conf_ found to fix it.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Comment by ezenko** [comment]
Can confirm that the comment from Sep 7 fixes this.
