### ISSUE TITLE
Kbox rebuild fails after trying to change php to 70 in local with Pantheon plugin.

### ISSUE THREAD

**Issue by mkykode** [kalabox/kalabox#1824]
Bug Report
==========

What is your Kalabox version and operating system?
Version 2.1.3  Mac OS 10.12.5

Have you previously installed Kalabox? If so, what version?
2.0

Give a brief description of what happened, including any error messages that appeared.
Ever since pantheon did the update to php7 by default, if I try to change the kalabox.yml to php 70 the kbox rebuild fails and I get this error:
WARNING: CORE PLUGIN ==> Unexpected status code returned. This MAY be a problem. Check your site to verify. Restarting your app may help. 

I try to restart either in UI or terminal and all I get is:
Error 502: Lost in the clouds?
Your Kalabox application is currently not responding. Try running "kbox start" first :)
and kbox start does not help.

To make it work again I have to delete the box and re-download from pantheon. I can never get it to change to php7.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
1. Download fresh copy of pantheon site.
2. Change php to 70 in kalabox.yml.
3. In terminal do kbox rebuild.
4. CORE PLUGIN error.

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
@mkykode kalabox is going to use whatever version of php your pantheon site uses. are you sure you've switched the relevant dev or multidev enviornments to php 7 on the pantheon end?

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
