### ISSUE TITLE
 VError: Failed after 5 retries. {"max":5,"backoff":500}:

### ISSUE THREAD

**Issue by justanotheramateur** [kalabox/kalabox#1826]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

Kalabox 2.1.3 on Windows 10 Pro

Have you previously installed Kalabox? If so, what version?

No, just this one

**Tell us about your bug**

I tried to add a Pantheon multidev environment, cloned from Test.

After a few seconds, it stops and the notifications show this error:

` VError: Failed after 5 retries. {"max":5,"backoff":500}:`

![image](https://user-images.githubusercontent.com/11964962/29047496-813565c0-7b91-11e7-8aa7-a92d9f0043d4.png)

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected my site
4. Chose my multidev environment and wanted to clone both files and db
5. See error above

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

Yes, what the error means and likely causes and fixes

Does this bug prevent you from using Kalabox?

Absolutely... can't get my site downloaded

**Comment by DontSeeSharp** [comment]
I have the same issue. Is a fix or a cause known?

**Comment by justanotheramateur** [comment]
I worked with both Kalabox and Pantheon for a few hours without success. Eventually just gave up and resorted to using Pantheon's multidev to preview.

Might have something to do with Windows. Had a little bit more success not updating Docker to the latest version, but still couldn't get it working all the way. Sorry.

**Comment by stevenkkim** [comment]
I have the same issue. (Kalabox 2.1.3 on Windows 10 Pro)

**Comment by pirog** [comment]
Def recommend people who are CLI friends try out our lando project at this point!
https://github.com/kalabox/lando

**Comment by stevenkkim** [comment]
@pirog I just downloaded lando to give it a whirl. Looking good so far. It was easy to install and get my Pantheon/Drupal site up. Thanks for all the great work!

**Comment by JeremyEnglert** [comment]
I'm getting the same error on MacOS. When I run the command from WP-CLI, it gives me warnings/errors about missing variables related to Pantheon - but Pantheon support wasn't able to help. 

`
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_BINDING variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_FRAMEWORK variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_PHP variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_AUTH_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_SITE variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CACHE_PORT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_AUTH_KEY variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_FILEMOUNT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_NONCE_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DRUPAL_HASH_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_SITE_NAME variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_LOGGED_IN_KEY variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_INDEX_PORT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_SECURE_AUTH_KEY variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CACHE_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DB_NAME variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_DOCROOT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_SECURE_AUTH_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PRESSFLOW_SETTINGS variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_INDEX_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_ACCOUNT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_PANTHEON_ENVIRONMENT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_LOGGED_IN_SALT variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CACHE_HOST variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_ENV variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_SITE variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_NAME variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_APP_PANTHEON_CONFIG_DRUSH variable is not set. Defaulting to a blank string.
Running post destroy tasks.
`

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

**Comment by vernontnh** [comment]
But Lando seems to be entirely command line requiring VERY advanced understanding of coding. Any plans to make this as easy to use as Kalabox? From my perspective, this new project has made it MUCH more difficult to get anywhere at all with setting up a local environment.

**Comment by pirog** [comment]
@vernontnh if you think that lando requires a "very advanced" understanding of coding then you probably would be better off not using any Docker based local dev solutions, eg MAMP might be more your speed.

That said there **is a high probability** that _someone_ will build a Kalabox-like GUI on top of Lando, still guessing you might be better off with MAMP though.
