### ISSUE TITLE
Wordpress Setup has no mysql, drush etc

### ISSUE THREAD

**Issue by Cuttsy27** [kalabox/kalabox#1827]
Bug Report
==========

**Tell us about your setup**

Kalabox version 2.1.3 on Windows 10 Pro 64bit

**Tell us about your bug**

I've having a problem with my WordPress setups (not pantheon).

* I've tried creating a new WP with kbox create wordpress and using the GUI. Both create fine and I can access site and wp-admin.

* When using command line, kbox -h only shows following services: 
- bower
- git
- grunt
- gulp
- node
- npm
- rsync

* As i need to import a previous WP database, I try to kbox mysql but receive following error:

Unhandled rejection VError: Failed after 5 retries. {"max":5,"backoff":500}: No such service: drush
    at C:\Program Files\Kalabox\bin\lib\promise.js.jx:70:17
    at process._tickCallback (node.js:917:13)

* I've tried destroying and re-creating, stopping kbox and docker, restarting PC. Nothing seems to work.

A pantheon setup via kbox create pantheon has services like mysql and they work.

**Comment by pirog** [comment]
@Cuttsy27 those things are not supported for non-pantheon apps. but if you are looking for that sort of thing i recommend you try out docs.lndo.io
