### ISSUE TITLE
Wordpress lost permission to files after files are modified outsider of Kalabox

### ISSUE THREAD

**Issue by fdsze** [kalabox/kalabox#1828]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?

> Kalabox 2.1.3 on Mac OS X Sierra 10.12.6

Have you previously installed Kalabox? If so, what version?

> No

**Tell us about your bug**

Give a brief description of what happened, including any error messages that appeared.

> It happens to a Pantheon Wordpress project. Whenever any Wordpress files, e.g. `~/Kalabox/my-project/code/wp-content/themes/my-theme/acf-json/group_5982e9cb2d729.json` is being touched outside of Kalabox, i.e. changed by a text editor or updated by Git, it is as if Kalabox Wordpress lost write permission and cannot change it anymore. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 
> 
> 1. Use Kalabox GUI to install a Pantheon Wordpress repo with any plugins that is able to write files to the Wordpress directories (e.g. Advanced Custom Fields and WP-CFM, both write a JSON file)
> 2. Going into the Wordpress admin, write some files with those plugins
> 3. On terminal, use `kbox . bash` and `cd` to the location of the files
> 4. Run `ls -l` and note down the owner and group of the files
> 5. Edit those same files on host machine with a text editor
> 6. Going into the Wordpress admin, try to write to the same files with those plugins
> 7. It fails
> 8. On terminal,  run `ls -l` and it shows the owner and group has changed
> 9. use `chown` to revert the owner and group back to previous
> 10. Going into the Wordpress admin, use the plugins to write to the same files
> 11. It works again

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

> More on file permission maybe?

Does this bug prevent you from using Kalabox?

> Not to the point of preventing but having to change back file ownership manually each time is time consuming

---

Sorry if any of my Kalabox usage is contrary to best practice (if there is any), since I am still new to Kalabox and Docker. I am open to suggestions about setup for dealing with Wordpress plugins that write to files.

I have looked into the issues list and the closest I can relate my problem to are #1741, #1253 and #1717, however I can't find a solution there yet.

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
