### ISSUE TITLE
This page isn’t working  .kbox.site redirected you too many times.

### ISSUE THREAD

**Issue by irixzafra** [kalabox/kalabox#1834]
When I push one of my sites of pantheon in kalabox and try to navigate I get this error:

**This page isn’t working  sitename.kbox.site redirected you too many times.**

I can do operations via kbox drush terminal, up and down from pantehon, but can not navigate beyond the home or login

In Pantheon this Looping issue does not occur.

**Comment by ccharlton** [comment]
+1 ditto.

**Comment by ozheller** [comment]
If you are using Drupal 8 and Nginx: you can edit ~/Kalabox/project/config/nginx/drupal8.conf and change the lines 73-79 to :
'location / {
      # auth_basic $auth_basic_realm;
      try_files $uri /index.php?$query_string;
      # Catch directory listing errors (i.e. no code)
      error_page 403 /403.html;
      # error_page 301 =301 $client_scheme://$host$uri/$is_args$args;
  }'
The main change is ln:75 from 'try_files $uri $uri/ @cleanurl;' to 'try_files $uri /index.php?$query_string;'

**Comment by chrisbohnsack** [comment]
I'm having the same problem on a Drupal 7 site. This issue occurs when I add the Pantheon code to redirect to SSL to the settings.php file. Can anyone help?

**Comment by chrisbohnsack** [comment]
An update on my comment above - my solution is to create a separate settings.local.php file for use when using local environment. Then add a query to settings.php to look for the local file and use it if it exists:

/**
 * If there is a local settings file, then include it
 */
$local_settings = "sites/default/settings.local.php";
if (file_exists($local_settings)) {
  include $local_settings;
}

Then add the settings.local.php to .gitignore file.

Not an easy fix but it does the trick.
