### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by wmcmillian-coalmarch** [kalabox/kalabox#1836]
I'm using Arch Linux so the deb/rpm options aren't available to me.

I tried following the steps found here:
http://docs.kalabox.io/en/stable/developers/contrib

But those don't install the Kalabox  engine

**Comment by pirog** [comment]
@wmcmillian-coalmarch kalabox is currently deprecated in favor of https://github.com/lando/lando so i would suggest you look over there
