### ISSUE TITLE
Kalabox still hijacking https://localhost after uninstall

### ISSUE THREAD

**Issue by d34dman** [kalabox/kalabox#1837]
1. I had an old instance of kalbox on my system.
2. I wanted to try Docker For Mac on new project, when it conflicted with port 443 on localhost
3. visiting the https://localhost on my machine presented with a page as shown in screenshot below
![Screenshot https://localhost](https://user-images.githubusercontent.com/1006481/37460486-5a1086fe-2871-11e8-8e6f-8c1b2ea5a58b.jpg)
4. Proceeded to uninstall kalabox by downloading the image for v2.1.3 and run uninstall.command
5. Didn't choose to uninstall Docker for mac though.
6. Restarted the machine couple of times and https://localhost is still showing same page as in the screenshot.

So how can i uninstall kalabox properly?

**Comment by pirog** [comment]
@d34dman the uninstall script should do it but if not run `docker ps` find the offending container (its likely called `kalabox_proxy_1` or similar) and then `docker rm -f CONTAINERID`
