### ISSUE TITLE
Document how to "SSH" into containers/vm

### ISSUE THREAD

**Issue by BevanR** [kalabox/kalabox#185]
I followed the instructions on the project homepage: https://github.com/kalabox/kalabox

How can I SSH into the booted machine?

**Comment by pirog** [comment]
so to ssh into the Kalabox 2 VM after you install/provision you can do

```
kbox up
boot2docker --vm="Kalabox2" ssh
```

When you are in the VM you can "ssh" into any of your containers with something like this
```
# List all my containers
docker ps --all
docker exec -it CONTAINERNAME bash
```

Will have a utility method to do this easily in subsquent releases.

**Comment by pirog** [comment]
I've added this to the following docs
https://github.com/kalabox/kalabox/wiki/FAQ#ssh-ing-into-the-kalabox-vm-and-specific-containers

**Comment by yumyo** [comment]
broken link. Took 20 minutes to find this but I am still unable to log in ssh as I miss boot2docker.

**Comment by pirog** [comment]
We don't use Boot2Docker any more. This workflow might be more helpful until we get better docs

```bash
# Drops you inside of the VM
~/.kalabox/bin/docker-machine ssh Kalabox2

# Attaches to a particular container, the container needs to be running)
docker exec -i -t CONTAINERNAME bash
```

**Comment by yumyo** [comment]
Hi @pirog, the above seems not to apply to kalabox 2.0 as there's no `/bin/docker-machine` folder inside `~/.kalabox/`

**Comment by pirog** [comment]
@yumyo 
http://docs.kalabox.io/en/stable/troubleshooting/ for future ref.
