### ISSUE TITLE
"403 Forbidden" error when I go to "pantheon.kbox"

### ISSUE THREAD

**Issue by texvetadmin** [kalabox/kalabox#190]
Howdy,

I followed the TL;DR instructions (Only one hitch: The rsync returned a "rsync: mkdir "/code/sites/default/files" failed: No such file or directory (2)" error until I manually created a local code/sites/default/files folder. The files are sitting in kalabox/www/texvet/ - not in kalabox/apps/pantheon.code – is that the right place for them to be?). 

I ran "kbox up" and "kbox start". Now I have two containers running:

leistiko-texvet-macbook-pro:code leistiko$ kbox containers
{
  "id": "b6f3e78a7aa9f88b6f51c7ad87eaa42621da763b77396729c745bdb21e5d81c0",
  "name": "kb_pantheon_db",
  "app": "pantheon",
  "ports": [
    "3306/tcp=>32770"
  ],
  "running": true
}
{
  "id": "c70fa3d63f6517fe7932d06691a2afd8b30f736ce1f5856312e2731e60ada4e7",
  "name": "kb_pantheon_appserver",
  "app": "pantheon",
  "ports": [
    "443/tcp=>32768",
    "80/tcp=>32769"
  ],
  "running": true

When I go to "http://pantheon.kbox" in a browser (tried in Safari and Chrome), I get a white page with black text and a "403 Forbidden" error.

My questions: Why am I getting a 403 error? What do I need to do to fix it?

Thoughts & recommendations welcome. If you need additional information, I'll happily provide it to the best of my ability.

**Comment by labboy0276** [comment]
Real quick Jonathan, I didnt know the files wer going into kalabox/www  

That is a KB1 setup.  Did you uninstall KB1 completely?  It shouldnt really matter, but curious as to why things ended up there, if they did. 

Also, may be best to start from scratch after you uninstall all the things.  Quick note, you dont need to name the app pantheon, I just did that in the TLDR instructions.  You can make it tesvet so it is easier to understand it.

Anywho, before @pirog chimes in, lets make sure you uninstall kb1 all the way.  I know it didnt work for you, so might as well 86 it.  There is a Uninstall.tool utility that comes with kb1, run that and it will nuke all things left.

Then lets, uninstall kalabox v2:
Run these commands:  
```
$ kbox config | grep srcRoot 
```
(grab the dir path)
```
$ bash path/from/above/scripts/uninstall-darwin.sh
```

Uninstall everything but virtualbox at the end.

Now, We are going to install a small program just to be safe:
```
$ sudo npm install -g npmdoctor
$ whoami
$ sudo npmdoctor -u {namefrom whoami command above}
```

OK, so then run through the TLDR commands again and let us know if the issues still persist.

This way we are all on the same page and if the issue persists, then it wasnt form a fail install, kb1 interfering (although I dont know how that is possible) or a npm issue.

**Comment by texvetadmin** [comment]
Will do.
(Apologies for the omitted information; it bugs me when I'm doing tech support and the client omits info, so I feel like a doofus for doing the same.)

**Comment by pirog** [comment]
Yes. By default you will want to put your code into `/path/to/my/app/code` although this is configurable and overridable if you need to have your webroot named something specific ie `docroot`

**Comment by texvetadmin** [comment]
Howdy. Can you point me at a DMG of Kalabox 1? The link I had for it on Kalamuna's site returns a 404 (http://www.kalamuna.com/products/kalabox-1.0), and my Google-fu didn't turn up any rogue links to it. Thanks!

**Comment by reynoldsalec** [comment]
Hey @texvetadmin, you can still access all the V1 builds on the V1 GitHub repo: https://github.com/kalamuna/kalaboxv1/releases

Hope that helps!

**Comment by texvetadmin** [comment]
@reynoldsalec – Perfect! Thanks. =)

**Comment by pirog** [comment]
You are def more than happy to use V1 but please note that we no longer provide support for it!
