### ISSUE TITLE
Documentation clarity suggestion: "files" vs "sites/default/files"

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#191]
The examples at https://github.com/kalabox/kalabox-plugin-rsync reference "sites/default/files" (D6/D7 convention), but the import files example at https://github.com/kalabox/kalabox/wiki/Drupal-Guide references "files" (D8 convention). It might be less confusing to readers if each example were on each of these pages along with the relevant Drupal core major versions.

Also:
https://github.com/kalabox/kalabox/wiki/QUICK-Start---TL;DR
https://github.com/kalabox/kalabox/wiki/Backdrop-Guide

**Comment by pirog** [comment]
Yeah no doubt the docs need to be improved in a lot of ways. Only so much time to go round :(

We are going to be rolling out a drupal/wp/backdrop site import plugin for 0.8.0 so hopefully that will allow us to simplify docs quite a bit.

In the meantime we can def try to clean some of them up.

**Comment by pirog** [comment]
i've gone in and clarified difference between D6/7 and D8 in some of these examples/docs
