### ISSUE TITLE
XDebug Support with kalabox PHP app server containers for PHP 5.5+

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#192]
I installed Kalabox and created an app per the wiki, but I couldn't get XDebug to work. I finally SSH'd into the app server. As you can see, the (edit: apc) extension file is missing.

```shell
docker@boot2docker:~$ docker exec -it kb_copperly_appserver bash
root@appserver:/# php --version
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/apc.so' - /root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.5.24 (cli) (built: May 21 2015 20:27:21) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by jdleonard** [comment]
Not sure how relevant this is, but there's no xdebug.ini.
```shell
root@appserver:~/.phpbrew/php/php-5.5.24/var/db# cd /root/.phpbrew/php/php-5.5.24/var/db
root@appserver:~/.phpbrew/php/php-5.5.24/var/db# ls
apc.ini  apcu.ini  gd.ini  opcache.ini	redis.ini
```

**Comment by pirog** [comment]
this needs to be documented better but currently we dont have xdebug running in 5.5 due to the :( documented here https://deekayen.net/drupal8-xdebug-installer-timeout

hopefully at some point drupal 8 can run with xdebug at a reasonable speed and we can reintroduce. its possible there are ways to tune xdebug to have this all work a lot better or to disable xdebug only on drupal 8 sites but we havent had time to look into this yet.

**Comment by jdleonard** [comment]
Hmm any idea if that is still a valid reason? The link mentions beta 3, which is quite a while ago. Also, I installed Drupal 7, not 8 so is no XDebug still expected? 



JD

**Comment by pirog** [comment]
It was as of beta10 which i tested maybe last week? there also seems to be
slim pickins on this specific issue on the googles.

As of right now we only have the granularity of php version not drupal
version. As soon as we get the drupal version into the config we can refuse
to load xdebug only in the D8 + 5.5 case. That will probably be in 0.8.0
release. Realize that is not ideal but the project is young!

On Sat, May 30, 2015 at 1:59 PM, JD Leonard <notifications@github.com>
wrote:

> Hmm any idea if that is still a valid reason? The link mentions beta 3,
> which is quite a while ago. Also, I installed Drupal 7, not 8 so is no
> XDebug still expected?
>
>
>
> JD
>
> On Sat, May 30, 2015 at 10:15 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > this needs to be documented better but currently we dont have xdebug
> running in 5.5 due to the :( documented here
> https://deekayen.net/drupal8-xdebug-installer-timeout
> > hopefully at some point drupal 8 can run with xdebug at a reasonable
> speed and we can reintroduce. its possible there are ways to tune xdebug to
> have this all work a lot better or to disable xdebug only on drupal 8 sites
> but we havent had time to look into this yet.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/kalabox/kalabox/issues/192#issuecomment-107081112
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/192#issuecomment-107085335>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@labboy0276 can you just investigate whether XDEBUG w/ D8 has been resolved yet? The issue was D8 going slow as hell. Just post back your findings.

**Comment by labboy0276** [comment]
@pirog there isnt too much on this issue still:

https://www.drupal.org/node/2488300
https://www.drupal.org/node/2222563

Most questions are around this:
http://drupal.stackexchange.com/questions/145687/maximum-function-nesting-level-of-100-reached-on-drupal-8

Should I try and put xdebug in php 5.5 and tweak the xdebug.ini settings as suggested?

**Comment by pirog** [comment]
Nah lets just back log this issue and wait on it for a bit.

On Sat, Jul 25, 2015 at 2:16 PM, John Ouellet <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> there isnt too much on this issue still:
>
> https://www.drupal.org/node/2488300
> https://www.drupal.org/node/2222563
>
> Most questions are around this:
>
> http://drupal.stackexchange.com/questions/145687/maximum-function-nesting-level-of-100-reached-on-drupal-8
>
> Should I try and put xdebug in php 5.5 and tweak the xdebug.ini settings
> as suggested?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/192#issuecomment-124868953>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by jamesrward** [comment]
Can we use this space to provide instructions for enabling xdebug on the box for those of us who are only running D7 sites but want the newer php version?

**Comment by pirog** [comment]
+1

Can someone change the name of this issue to xdebug support with kalabox
php app server containers php 5.5+?

On Tuesday, August 4, 2015, James Ward <notifications@github.com> wrote:

> Can we use this space to provide instructions for enabling xdebug on the
> box for those of us who are only running D7 sites but want the newer php
> version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/192#issuecomment-127642673>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
done @pirog on the title change.  I can write up instructions a little bit later on how to do so.

**Comment by pirog** [comment]
I'm not sure we can do this without changing the php app server around in
the kalabox.json so that it uses an appsetver with xdebug installed for 5.5+

On Tuesday, August 4, 2015, John Ouellet <notifications@github.com> wrote:

> done @pirog <https://github.com/pirog> on the title change. I can write
> up instructions a little bit later on how to do so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/192#issuecomment-127646332>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
All we have to do is throw xdebug.max_nesting_level = 256 in our php,ini to resolve this.  I tried brewing my own php here:  https://github.com/labboy0276/phpbrewer so I can make a php,tar.gz and use it but phpbrew isnt cooperating with my system right meow. I think I will go outside and see what people do normally do on a Sunday.

**Comment by labboy0276** [comment]
Also, tested this with the 0.2.0 tag of phpbrewer and it worked gloriously.

**Comment by labboy0276** [comment]
@pirog Can you add xdebug back into phpbrewer and then use this PR: https://github.com/kalabox/kalabox-app-pantheon/pull/31

This will get xdebug winning on D8

**Comment by pirog** [comment]
@labboy0276 did you run through the D8 installer with xdebug running? that is where we were having issues?

**Comment by pirog** [comment]
Note: We may need to roll 5.5 with a different xdebug version than 5.3

**Comment by Senpai** [comment]
Hooray for built-in xdebug support! Perhaps get this amazingly cool and valuable information into the wiki for people to find?

**Comment by pirog** [comment]
+1 

There is some rough docs in https://github.com/kalabox/kalabox-app-pantheon/

In the next few weeks we hope to get a more legit wiki system rolling so going to ping @reynoldsalec on this one.

**Comment by reynoldsalec** [comment]
RE: Legit wiki @Senpai, our legacy materials are being transferred over now and we're building up more documentation on a new knowledge base.

Here's our resource on xdebug:

https://kalabox.freshdesk.com/solution/articles/14000005912
