### ISSUE TITLE
Cannot get Drupal app up; 403 forbidden

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#195]
Tried to install kbox2 on another mac (never had kbox installed).
All the install steps seemed to go OK. Followed docs on github/kalabox. Our app is named sports. D7, PHP 5.5.
Cloned Drupal code from our github repo.
Added our database using mysql command (per doc). (Should that been kbox mysql …?)
Added sites/default/files from a backup copy.

Now need to include settings.php. This does not appear to be documented.
What we tried: driver=‘mysql’ database=‘kalabox’ username=‘kalabox’ password=‘’ and port=‘32770’ prefix=‘’ and host=‘sports.kbox’
[Should the host be localhost?]
Also tried adding $base_url=’sports.kbox’

We are getting:  403 forbidden Nginx/1.2.1, except if change host to localhost, the message is:  No application configured.

Kbox is started, up.  

Can anyone help?

**Comment by pirog** [comment]
So there are a bunch of things here. If you aren't using a pressflow variant of Drupal, which seems to be the case here, you will need to add the DB settings to your box. You can do this with something like 

```

/**
 * Kalabox 2 settings.php
 */
if (getenv('KALABOX') && getenv('KALABOX') === true) {

  // DB Array and some common conf
  $databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => 'kalabox',
    'username' => 'kalabox',
    'password' => '',
    'host' => 'myappname.kbox',
    'port' => '3306',
    'prefix' => '',
  );

  // Set some common desirable local vars
  // These are just examples you will want to replace with ones that make sense for you
  $conf['file_temporary_path'] = '/tmp';
  $conf['file_public_path'] = 'sites/default/files';
  $conf['file_private_path'] = 'sites/default/files/private';
  $conf['reroute_email_enable'] = 1;
  $conf['cache'] = 0;
  $conf['css_gzip_compression'] = FALSE;
  $conf['js_gzip_compression'] = FALSE;
}
```

Your site should be accessible at http://myappname.kbox. If you get a 403 it generally means you've imported your code into the wrong location. 

You will probably want to make sure your $baseurl makes your myappname.kbox. Usually you don't need to explicitly define $baseurl.

**Comment by donkoller** [comment]
Thanks for the quick reply. We'll try these and report back. Don

**Comment by pirog** [comment]
code should be stored in /path/to/my/app/code

**Comment by donkoller** [comment]
Summary of changes made to get site up in kalabox.
--Code was in a folder within /code, so by moving it up, was able to run index.php.
--Added the suggested changes to settings.php (placed private files dir in another place).
--Drupal then wanted to run install; so I ran the installer to the screen where database info is entered; after that the installer said I could visit the site. Then things were mostly OK. Still trying to figure out a few minor issues. If any are affected by kalabox, I'll report them here.

**Comment by pirog** [comment]
Great! Let us know

**Comment by donkoller** [comment]
Is number 3 normal? After install of code, database and files, Drupal then wanted to run install.php; so I ran the installer to the screen where database info is entered; after that the installer said I could visit the site.

**Comment by pirog** [comment]
If you imported the DB and edited your settings.php with correct DB then it should not run the installer.

**Comment by donkoller** [comment]
Will test again. DB for that site might not have been the correct version. Thanks
