### ISSUE TITLE
Put connection info in 'kbox config' results for cli.

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#197]
Ben Cauldwell: we should put that info in the ‘kbox config’ results if we can

Mike Pirog: maybe someone can post an issue

**Comment by bcauldwell** [comment]
There are plans to implement this in a future release that will include aggregating a lot of the informative commands into a smaller number possibly just one command.

**Comment by pirog** [comment]
It might be easiest to do this by just printing out the pressflow settings with part of kbox config or kbox containers? i actually think we might already be doing that in kbox config if you run inside an app?
