### ISSUE TITLE
Install fails at step 15/19: msg: /bin/sh: boot2docker: command not found

### ISSUE THREAD

**Issue by Tigeda** [kalabox/kalabox#199]
The install fails on my work computer, terminal output below.
```
info: -- Step 14/19 --
info: Running admin install commands...

Password:
installer: invalid option Roaming

Usage: installer [-help] [-dominfo] [-volinfo] [-pkginfo] [-allowUntrusted] [-dumplog]
                 [-verbose | -verboseR] [-vers] [-config] [-plist]
                 [-file <pathToFile>] [-lang <ISOLanguageCode>] [-listiso]
                 [-showChoicesXML] [-applyChoiceChangesXML <pathToFile>]
                 [-showChoicesAfterApplyingChangesXML <pathtoFile>]
                 -pkg <pathToPackage>
                 -target <[DomainKey|MountPoint]>

info: -- OK! 74% complete! --

info: -- Step 15/19 --
info: Setting up and activating the engine...
info: B2D => Starting up...
info: B2D => Error while starting up. code: 127, msg: /bin/sh: boot2docker: command not found

info: -- FAIL. --

code: 127, msg: /bin/sh: boot2docker: command not found

Roamings-iMac:Sites RoamingMac$
```

**Comment by Tigeda** [comment]
I get the feeling that this is due to my work imac having two drives, and my current user home folder being on the secondary drive, not the boot drive.

**Comment by pirog** [comment]
Yeah that could definitely do it. We've tested an OSX provision where the users directory is in an external drive with success but maybe your setup is a little different.

Can you give us a little more detail so we can try to replicate?

**Comment by Tigeda** [comment]
I just went ahead and got started moving my home directory to the boot drive, so I can't really give you any further details on it. 

Running kbox provision now, I'll let you know how that goes.

**Comment by pirog** [comment]
awesome!

On Mon, Jun 8, 2015 at 10:07 PM, Tigeda <notifications@github.com> wrote:

> I just went ahead and got started moving my home directory to the boot
> drive, so I can't really give you any further details on it.
>
> Running kbox provision now, I'll let you know how that goes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/199#issuecomment-110197948>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by Tigeda** [comment]
I'm at Step 15. It seems to be hanging here,
```
info: -- Step 15/19 --
info: Setting up and activating the engine...
info: B2D => Starting up...
```

BOOM

Past step 15.

**Comment by pirog** [comment]
BOOM!

On Mon, Jun 8, 2015 at 10:14 PM, Tigeda <notifications@github.com> wrote:

> I'm at Step 15. It seems to be hanging here,
>
> info: -- Step 15/19 --
> info: Setting up and activating the engine...
> info: B2D => Starting up...
>
> BOOM
>
> Past step 15.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/199#issuecomment-110198874>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by Tigeda** [comment]
Huzzah! Victory!

**Comment by Tigeda** [comment]
Ok, so I'm guessing this was due to the home directory on non-boot drive.  

I'm not sure if anyone else in the office has SSD's and a similar setup, but I'll cross that bridge when I get to it (got to convince them to adopt first).
