### ISSUE TITLE
Add additional projects / commands to the drush plugin, like registry_rebuild

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#200]
Can we add additional drush projects/commands to the drush plugin?

What would you like to see?

For me, number one is https://www.drupal.org/project/registry_rebuild

Then, https://www.drupal.org/project/pandarus all though the functionality of pandarus is probably going to be redundant once the push/pull from Pantheon feature is built into kalabox.

**Comment by pirog** [comment]
I think registry rebuild is def a good candidate. 

pandarus is probably not going to be needed for the reasons you detailed. we will be releasing the pantheon integration pretty soon.

**Comment by Tigeda** [comment]
Can't wait for that!

**Comment by labboy0276** [comment]
+1 for drush registry rebuild, I use it on every site when I import it for
safe measure.

On Mon, Jun 8, 2015 at 10:31 PM, Tigeda <notifications@github.com> wrote:

> Can't wait for that!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/200#issuecomment-110200547>.
>



-- 
*John Ouellet*
*Developer & Support Manager*
415-470-3076
www.kalamuna.com

**Comment by pirog** [comment]
We need to add drush 8 to the drush container also since that is now a thing i guess. Think you can def expect this and RR in 0.8.0

**Comment by pirog** [comment]
I am playing around with getting this into 0.8.0 right now but made a cool discovery. If you are using one of our app start states for drupal you can actually put custom drush extensions into `APPROOT/config/drush` on the host side.

**Comment by pirog** [comment]
ok `kbox drush rr` should be in the 0.8.0 release. you will need to update your pre-existing apps to 0.8.0 and then run `kbox update`. 

of course yuo need to wait for 0.8.0 to drop first too!

**Comment by pi-ron** [comment]
Thanks Mike!

On Wed, Jun 24, 2015 at 10:22 AM Mike Pirog <notifications@github.com>
wrote:

> ok kbox drush rr should be in the 0.8.0 release. you will need to update
> your pre-existing apps to 0.8.0 and then run kbox update.
>
> of course yuo need to wait for 0.8.0 to drop first too!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/200#issuecomment-114681324>.
>
-- 

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.

**Comment by pi-ron** [comment]
@pirog 

RE. 
> I am playing around with getting this into 0.8.0 right now but made a cool discovery. If you are using one of our app start states for drupal you can actually put custom drush extensions into APPROOT/config/drush on the host side. 

I tried adding a drush command to this directory within my app, ran `kbox drush cc drush` but the command is not being picked up, is there somewhere else I'm meant to put?

**Comment by pirog** [comment]
@pi-ron i think this only works in 0.9.0?

**Comment by pi-ron** [comment]
I haven't tried in 0.9.9 will do soon.

**Comment by pi-ron** [comment]
I might wiki it up if successfull.

**Comment by pirog** [comment]
that would be awesome!

thanks for all your help TD. You are awesome!

On Thu, Aug 13, 2015 at 12:50 PM, pi-ron <notifications@github.com> wrote:

> I might wiki it up if successfull.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/200#issuecomment-130535066>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
