### ISSUE TITLE
syncthing (Error: connect ECONNREFUSED)

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#201]
```
syncthing http://127.0.0.1:60008/rest/system/connections (Error: connect ECONNREFUSED)
```

Running kbox start in a freshly installed kbox drupal app, I get all the usual docker output, but then at the end get that error above.

I'm assuming that our network is blocking it?

**Comment by Tigeda** [comment]
Did a kbox stop, then kbox start, and the error didn't return...

**Comment by pirog** [comment]
Try doing a kbox restart here.

I think we've got this fixed in the next release.

On Monday, June 8, 2015, Tigeda <notifications@github.com> wrote:

> syncthing http://127.0.0.1:60008/rest/system/connections (Error: connect ECONNREFUSED)
>
> Running kbox start in a freshly installed kbox drupal app, I get all the
> usual docker output, but then at the end get that error above.
>
> I'm assuming that our network is blocking it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/201>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by Tigeda** [comment]
Yep, worked!

Just dropped a static site into /code.  This is brilliant.

The elephant is DEAD

**Comment by pirog** [comment]
haha. im glad you like it!

we still aren't even beta for the CLI yet. wouldn't say the elephant is dead until we get the GUI out but its definitely endangered now!

**Comment by bcauldwell** [comment]
I've taken steps in 0.8.0 to stop this error condition from happening, as far in my own personal use have not been able to recreate since the fix. Going to close the issue, and reopen if it happens again.
