### ISSUE TITLE
XDebug missing server name

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#202]
Perhaps I am encountering this because I don't fully understand the architecture of Kalabox or maybe I'm making a silly mistake, but I am unable to get PHPStorm to step through my local code when prompted by an XDebug connection from Kalabox. I have always been able to figure out such issues in the past, for example with Kalabox v1. Running Kalabox 0.7.9 with Drupal 7 & PHP 5.4.

I think the problem may be that Kalabox/XDebug is not passing a server name over the connection, which means that PHPStorm doesn't know which configured Server (and thus the path mappings) to use:
![screen shot 2015-06-13 at 18 43 47](https://cloud.githubusercontent.com/assets/2074112/8145149/30d7ac10-11fc-11e5-8752-0091d308f17d.png)

Any sage advice?

**Comment by pirog** [comment]
shouldn't the port be 9000 (or possibly 9001)?
not sure how storm works but might have to pass in the XDBEUG_START query
parameter as well?
i think you can also put in the "copperly2.kbox" as the server name?

the sublime config looks like (again not sure on port being 9000/9001)

```
"xdebug":
{
"max_children": 64,
"max_depth": 16,
"path_mapping":
{
"/code/": "/Users/mpirog/Desktop/apps/hsu/code/"
},
"port": 9000,
"pretty_output": true,
"url": "http://hsu.kbox/"
}
```


On Sat, Jun 13, 2015 at 12:14 PM, JD Leonard <notifications@github.com>
wrote:

> Perhaps I am encountering this because I don't fully understand the
> architecture of Kalabox or maybe I'm making a silly mistake, but I am
> unable to get PHPStorm to step through my local code when prompted by an
> XDebug connection from Kalabox. I have always been able to figure out such
> issues in the past, for example with Kalabox v1. Running Kalabox 0.7.9 with
> Drupal 7 & PHP 5.4.
>
> I think the problem may be that Kalabox/XDebug is not passing a server
> name over the connection, which means that PHPStorm doesn't know which
> configured Server (and thus the path mappings) to use:
> [image: screen shot 2015-06-13 at 18 43 47]
> <https://cloud.githubusercontent.com/assets/2074112/8145149/30d7ac10-11fc-11e5-8752-0091d308f17d.png>
>
> Any sage advice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/202>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by jdleonard** [comment]
While it looks like a form, the screenshot is actually showing fixed information about the incoming XDebug connection. The server name is missing and the HTTP port 80 is as expected. PHPStorm is receiving the XDebug request, but that request is missing the server name, which is preventing PHPStorm from mapping the connection to the server configured in PHPStorm, which contains the path mappings necessary for the debugger's step functionality. That's my theory anyway.

**Comment by pirog** [comment]
haha. what a ruse that "form" is!!!

given the sublime text conf im not sure *xdebug* needs the server name and port. i think it more likely phpstorm is using that info to make a request?

have you tried just pasting the XDEBUG_START query into the URL and see if that can trigger it?

**Comment by jdleonard** [comment]
I know!

PHPStorm isn’t making a request. It is merely responding to the incoming XDebug request. I think the server name should be passed in from the web server (not expecting it to be part of the Xdebug config).

Alas, I have tried XDEBUG_START.

Ah well. Maybe it’l work someday :)

On June 15, 2015 at 19:55:43, Mike Pirog (notifications@github.com) wrote:

haha. what a ruse that "form" is!!!

given the sublime text conf im not sure xdebug needs the server name and port. i think it more likely phpstorm is using that info to make a request?

have you tried just pasting the XDEBUG_START query into the URL and see if that can trigger it?

**Comment by pirog** [comment]
Don't have time right now but ill try to grab phpstorm at some point and
try this out. there is def a way to get it to work.

On Mon, Jun 15, 2015 at 3:26 PM, JD Leonard <notifications@github.com>
wrote:

> I know!
>
> PHPStorm isn’t making a request. It is merely responding to the incoming
> XDebug request. I think the server name should be passed in from the web
> server (not expecting it to be part of the Xdebug config).
>
> Alas, I have tried XDEBUG_START.
>
> Ah well. Maybe it’l work someday :)
>
> On June 15, 2015 at 19:55:43, Mike Pirog (notifications@github.com) wrote:
>
> haha. what a ruse that "form" is!!!
>
> given the sublime text conf im not sure xdebug needs the server name and
> port. i think it more likely phpstorm is using that info to make a request?
>
> have you tried just pasting the XDEBUG_START query into the URL and see if
> that can trigger it?
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/202#issuecomment-112228243>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by jdleonard** [comment]
FYI, I'm still having this issue on 0.9.x

**Comment by reynoldsalec** [comment]
Sadness @jdleonard, I know I've had good success using [Codebug](http://codebugapp.com/), one of us definitely needs to boot up PHPStorm and see what's not clicking there.

**Comment by leevh** [comment]
Just checking in, @jdleonard have you had any success getting phpstorm debugging working since August?

**Comment by jdleonard** [comment]
I haven't updated kbox in a while to try. I'll report back when I find the time.

**Comment by pirog** [comment]
@leevh @jdleonard i havent looked at this yet either but i would love to have some clarity on how to do this with phpstorm

**Comment by jdleonard** [comment]
I took another stab at this today using Kalabox 10.6 (PHP 5.5.24) and PhpStorm 10.0.1 on OS X 10.11.2. No dice. Actually, I was having trouble even getting as far as I did in my OP, but that's probably my fault.

I did some more research and found these, which suggest that indeed the server name is empty and needs to be set in the nginx config:
http://stackoverflow.com/questions/23344106/php-storm-debugging-creates-empty-server-definitions
http://stackoverflow.com/questions/32689554/xdebug-with-phpstorm-and-a-docker-container
http://stackoverflow.com/questions/32668258/xdebug-windows-docker-phpstorm?rq=1

Here's some info on using XDebug in PHPStorm: https://confluence.jetbrains.com/display/PhpStorm/Zero-configuration+Web+Application+Debugging+with+Xdebug+and+PhpStorm

**Comment by jdleonard** [comment]
Mostly success!

I added the `server_name` setting to config/drupal.conf like so:
```
server {
  listen 8888 default_server;
  server_name copperly.kbox;
```

Then ran `kbox restart`.

Here's my relevant PHPStorm configuration:

![image](https://cloud.githubusercontent.com/assets/2074112/12276291/09fef01e-b943-11e5-9c15-b0b681c16f31.png)

![image](https://cloud.githubusercontent.com/assets/2074112/12276374/669ab786-b943-11e5-88ca-7545aa43c602.png)

![image](https://cloud.githubusercontent.com/assets/2074112/12276397/8b6857da-b943-11e5-88e5-0d5ce3a5385d.png)

Breakpoints are now working in PHPStorm when appending ?XDEBUG_SESSION_START=1 to the end of the path in the browser!

I'd prefer to use my trusty "xdebug helper" Chrome extension rather than fiddle with ?XDEBUG_SESSION_START=1 (which doesn't allow debugging to continue after a redirect)

Of course after some php.ini fiddling and a `kbox restart`, I'm now getting 503 errors, but that's a different bug...

**Comment by ptmkenny** [comment]
Thanks for posting this.  I'm trying to get PhpStorm and Xdebug set up with Kalabox, but I'm new to this so it's pretty rough.

@jdleonard - You wrote you added the code to config/drupal.conf, but I don't have a drupal.conf in my kalabox config folder (I've got cron, drush, php, etc.)  Would you have any idea why I might not have the same file?

I'm on Drupal 7, kbox 1.10-alpha6, and OS X.

**Comment by jdleonard** [comment]
Sorry @ptmkenny I have no idea!

**Comment by reynoldsalec** [comment]
@ptmkenny you may need to look in config/nginx/drupal.conf to make those changes. Let me know if that works out for you, I know Codedebug works for me out of the box (with the caveat that you have to use XDEBUG_SESSION_START=1 and explicitly declare xdebug_break() statements, similar to what @jdleonard mentioned), so it's worth a try.

If server_name helps out we should add it in. Finding an nginx config file that has xdebug work seamlessly would be handy so we can see what settings we may be missing.

**Comment by jdleonard** [comment]
@reynoldsalec is right about config/nginx/drupal.conf. I got that path wrong.

**Comment by pirog** [comment]
Checking back in here. 

@jdleonard in your phpstorm settings why are you setting the server code path to `/` instead of `/code`? does it work with `/`?

**Comment by jdleonard** [comment]
Actually, the third screenshot I provided is probably irrelevant. I disabled a plugin and that settings pane is no longer available, but I can still debug. The server path of "/code" in the second screenshot is working.

When I find the time, I can look into wildcards, but that may not be soon.

**Comment by ptmkenny** [comment]
I'm happy to report I now have xdebug working with Drupal 8 in PhpStorm on Kalabox 0.11.1 with Chrome on OS X.  I tried to keep careful notes, so here's what I did from scratch.

0. The line suggested by @jdleonard must be added to config/nginx/drupal8.conf:
```
server {
  listen 8888 default_server;
  server_name copperly.kbox;

```
1. Create a new project with the box directory as a root (/mybox should be the root, not /mybox/code)
2. Tools -> Deployment -> Configuration, click +
Name: whatever
Type: In place
* Now configure "whatever":
Connection -> Web server root URL: http://mybox.kbox
Mappings -> Local path: /Users/.../mybox/code/
Mappings -> Web path: /
3. Under Run -> Edit Configurations, click +, create a new PHP Web Application.
Name: xdebug
Server: import the server we created from deployment in step 1
Change the following:
Port: 8888
Check the box for "Use path mappings"
Remap "mybox/code" folder to "/code" (absolute path)
Remap "mybox/config/php/prepend.php" to "/src/config/php/prepend.php" (absolute path)
Start URL: /
Browser: Chrome
4. Start listening for debug connections
5. Open Chrome and there it goes

**Comment by pirog** [comment]
@ptmkenny can you try to get it to work with the wildcards I discussed
above?

**Comment by ptmkenny** [comment]
@pirog I couldn't get it working with wildcards, but I did get it working with just "kbox".  Then there's no need for app specificity.

**Comment by pirog** [comment]
What about something more generic like appserver?

**Comment by ptmkenny** [comment]
Yep that works too.  PhpStorm will apparently take any arbitrary name, but it chokes with no name at all.

**Comment by ptmkenny** [comment]
Just wanted to note that this works with the `appserver` name added to 0.11.3.  Great work, thanks so much!

**Comment by pirog** [comment]
awesome! ill close this out then.
