### ISSUE TITLE
Git cannot run editor

### ISSUE THREAD

**Issue by digitalink** [kalabox/kalabox#203]
It seems that kbox git can't run vim or whatever it uses.  This was trying to merge a remote branch after they diverged. Supplying the message with -m flag worked fine.

```
Rs-iMac:site-name RsMac$ kbox git status
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
# On branch theming
# Your branch and 'origin/theming' have diverged,
# and have 1 and 1 different commit each, respectively.
#
nothing to commit (working directory clean)
info: DOCKER => RUN container shutting down.
Rs-iMac:site-name RsMac$ kbox git commit
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
error: cannot run editor: No such file or directory
error: There was a problem with the editor 'editor'.
Please supply the message using either -m or -F option.
info: DOCKER => RUN container shutting down.
```

**Comment by Tigeda** [comment]
This was me posting btw

**Comment by labboy0276** [comment]
Hey,

https://github.com/kalabox/kalabox-issues/issues/471

Already going to be fixed in the next version as a FYI.

**Comment by pirog** [comment]
Thanks for this here. And thanks for closing and duplicate identification @labboy0276

**Comment by Tigeda** [comment]
No worries, apologies for the dup. I only really scanned the issue titles
not the content.
On Tue, 16 Jun 2015 at 3:49 am Mike Pirog <notifications@github.com> wrote:

> Thanks for this here. And thanks for closing and duplicate identification
> @labboy0276 <https://github.com/labboy0276>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/203#issuecomment-112151739>.
>
-- 

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.

**Comment by pirog** [comment]
no worries. that is why we actively prune the queues :)
