### ISSUE TITLE
Windows 8.1 kbox provision fails on step 14

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#206]
The URL at github should probably say repositories rather than repos... see bottom of listing.
Here's the full copy of bash listing.
Prior to this, installed git for Windows and node.js.
npm install kalabox -g looks like it worked OK.
Error occurs on kbox provision.

@dkrockville, Don Koller
====================================================

SLX@ALIBABBA ~
$ pwd
/c/Users/SLX

SLX@ALIBABBA ~
$ npm install kalabox -g
C:\Users\SLX\AppData\Roaming\npm\kbox -> C:\Users\SLX\AppData\Roaming\npm\node_m
odules\kalabox\bin\kbox.js

> kalabox@0.7.9 postinstall C:\Users\SLX\AppData\Roaming\npm\node_modules\kalabo
x
> node ./scripts/postinstall.js

npm WARN package.json kalabox@0.7.9 No license field.
kalabox-services-kalabox@0.7.4 C:\Users\SLX\AppData\Roaming\npm\node_modules\kal
abox\node_modules\kalabox-services-kalabox
├── async@0.9.2
├── fileinput@0.2.0
├── redis@0.12.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── windosu@0.1.3 (tail@0.3.9, q@0.9.7, temp@0.6.0)
└── lodash@3.9.3

kalabox-app-backdrop@0.7.7 C:\Users\SLX\AppData\Roaming\npm\node_modules\kalabox
\node_modules\kalabox-app-backdrop
├── kalabox-plugin-dbenv@0.7.4
├── kalabox-plugin-php@0.7.4
├── kalabox-plugin-rsync@0.7.4
├── kalabox-plugin-drush@0.7.13
├── kalabox-plugin-git@0.7.7
└── lodash@3.9.3

kalabox-engine-docker@0.7.2 C:\Users\SLX\AppData\Roaming\npm\node_modules\kalabo
x\node_modules\kalabox-engine-docker
├── async@0.9.2
├── fileinput@0.2.0
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0
.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── dockerode@2.0.7 (underscore@1.5.2, docker-modem@0.1.23)
└── lodash@3.9.3

kalabox-app-drupal@0.7.11 C:\Users\SLX\AppData\Roaming\npm\node_modules\kalabox\
node_modules\kalabox-app-drupal
├── kalabox-plugin-dbenv@0.7.4
├── kalabox-plugin-php@0.7.4
├── kalabox-plugin-rsync@0.7.4
├── kalabox-plugin-drush@0.7.13
├── kalabox-plugin-git@0.7.7
└── lodash@3.9.3
Installed additional backends and plugins.
kalabox@0.7.9 C:\Users\SLX\AppData\Roaming\npm\node_modules\kalabox
├── tsort@0.0.1
├── download-progress@0.0.1
├── diskspace@0.1.7
├── progress@1.1.8
├── rimraf@2.2.8
├── minimist@1.1.1
├── node-getopt@0.2.3
├── tildify@1.0.0 (user-home@1.1.1)
├── fileinput@0.2.0
├── async@0.9.2
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── async-eventemitter@0.2.2 (async@0.2.10)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── download-status@2.1.1 (object-assign@2.1.1, lpad-align@1.0.3)
├── shelljs@0.3.0
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8)
├── vasync@1.6.3 (verror@1.6.0)
├── bluebird@2.9.30
├── yargs@3.11.0 (decamelize@1.0.0, camelcase@1.1.0, window-size@0.1.1, cliui@2.
1.0)
├── winston@0.9.0 (cycle@1.0.3, stack-trace@0.0.9, isstream@0.1.2, eyes@0.1.8, p
kginfo@0.3.0, colors@1.0.3)
├── restler@3.2.2 (qs@0.6.6, yaml@0.2.3, iconv-lite@0.2.11, xml2js@0.4.0)
├── download@3.3.0 (get-stdin@3.0.2, gulp-rename@1.2.2, each-async@1.1.1, url-re
gex@2.1.3, stream-combiner@0.2.2, vinyl@0.4.6, rc@0.5.5, ware@1.3.0, through2@0.
6.5, concat-stream@1.4.10, decompress-unzip@2.1.2, meow@2.1.0, decompress-targz@
2.1.0, decompress-tarbz2@2.0.2, decompress-tar@2.0.2, request@2.58.0, vinyl-fs@0
.3.13)
├── liftoff@0.13.6 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-s
ync@0.1.3)
├── lodash@3.6.0
├── inquirer@0.8.5 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.
3.7, readline2@0.1.1, chalk@1.0.0, rx@2.5.3)
├── decompress@2.3.0 (get-stdin@4.0.1, vinyl-assign@1.1.0, concat-stream@1.4.10,
 buffer-to-vinyl@1.0.0, decompress-unzip@3.2.2, meow@3.1.0, stream-combiner2@1.0
.2, decompress-tar@3.1.0, decompress-targz@3.1.0, decompress-tarbz2@3.1.0, vinyl
-fs@1.0.0)
└── npm@2.11.2

SLX@ALIBABBA ~
$ kbox status
code: 1, msg: The system cannot find the path specified.

SLX@ALIBABBA ~
$ kbox provision
info: -- Step 1/18 --
info: Authorizing install subroutines...
? Are you sure you want to install Kalabox? Yes
info: -- OK! 6% complete! --

info: -- Step 2/18 --
info: Making sure syncthing is not running...
info: -- OK! 11% complete! --

info: -- Step 3/18 --
info: Queuing up syncthing downloads...
info: -- OK! 17% complete! --

info: -- Step 4/18 --
info: Checking firewall settings...
info: -- OK! 22% complete! --

info: -- Step 5/18 --
info: Queuing provider admin commands...
info: -- OK! 28% complete! --

info: -- Step 6/18 --
info: Queuing up provider downloads...
info: -- OK! 33% complete! --

info: -- Step 7/18 --
info: Checking for Internet access...
info: -- OK! 39% complete! --

info: -- Step 8/18 --
info: Checking for available disk space...
info: -- OK! 44% complete! --

info: -- Step 9/18 --
info: Downloading files...
     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/maste
r/profile
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/maste
r/b2d.inf
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfile
s/syncthing/config.xml
  progress : [====================] 100% 0.0s

     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.0/sy
ncthing-windows-amd64-v0.11.0.zip
  progress : [                    ] 1% 1.8s     fetch : https://github.com/boot2
docker/windows-installer/releases/download/v1.6.0/docker-install.exe
  progress : [====================] 100% 0.0s

  progress : [====================] 100% 0.0s

info: -- OK! 50% complete! --

info: -- Step 10/18 --
info: Setting up syncthing...
info: -- OK! 56% complete! --

info: -- Step 11/18 --
info: Setting up the provider profile...
info: -- OK! 61% complete! --

info: -- Step 12/18 --
info: Running admin install commands...
info: -- OK! 67% complete! --

info: -- Step 13/18 --
info: Checking if dns is set...
info: -- OK! 72% complete! --

info: -- Step 14/18 --
info: Setting up and activating the engine...
info: B2D => Starting up...
info: B2D => Error while starting up. code: 1, msg: error in run: Failed to get
latest release: Get https://api.github.com/repos/kalabox/kalabox-boot2docker/rel
eases: dial tcp: GetAddrInfoW: No such host is known.

info: -- FAIL. --

code: 1, msg: error in run: Failed to get latest release: Get https://api.github
.com/repos/kalabox/kalabox-boot2docker/releases: dial tcp: GetAddrInfoW: No such
 host is known.

SLX@ALIBABBA ~
$

**Comment by bcauldwell** [comment]
I'm 100% sure repo is the correct URL, and repositories does not work. This looks like an Internet connectivity problem. The only thing I think we could do better is maybe make the error message more specific.

**Comment by donkoller** [comment]
Yes, I am sure your are correct about the URL. On Win kbox provision, now that I am watching it (previously left it unattended), I see:

4 requests for admin password (from Windows). Responded with passwd.
Then virus protection keeps detection a threat from 
C:\Users\SLX\AppData\Local\ProgramGit\bin\ssh.exe
After allowing this about 12 times, I gave up, and ignored it.

Also an error dialog box opened with message that ...\Local\Temp\.windosu....-elevate.bat request is  not supported.

Perhaps I should have done the Allow Threats thing in the virus checker. Guess I quit too soon as I got as far as 
info: -- OK! 89% complete! --
info: -- Step 17/18
info: Finalizing Services...

I plan to run the kbox provision again to see if I can improve the result.
Don

**Comment by donkoller** [comment]
The next kbox provision stopped after step 16 saying that skydns was already installed.
So, I created and cd into a place for the root (~/sites/slxdemo), and ran kbox install && kbox start
Install completed correctly -- no messages. The start ran as well. This time asked for admin permission to run syncthing. Left a window open for syncthing.exe.
The kbox containers shows db and appserver running.

In browser, tried to run slxdemo.kbox. Not found.
How can I check the DNS?

**Comment by pirog** [comment]
sounds like the install didnt complete correctly. it also sounds like we need to get a windows 8.1 machine in here soon so we can try to replicate this.

**Comment by pirog** [comment]
To check DNS though, if you go to your network adapters you should see (possibly more than) two adapters for VirtualBox. The second one should list 10.13.37.42/43 has its nameservers.

Can you confirm/deny?

**Comment by donkoller** [comment]
kbox ip returns:  10.13.37.42
However in ipconfig, the VB Host-only Network #2 is 10.13.37.42

**Comment by pirog** [comment]
yes that is the correct address of the host only network... but im asking for the DNS nameservers for that network. Can you see those?

**Comment by pirog** [comment]
hey @donkoller 

Hey @stela5, 

We just released 0.8.0 which may resolve this issue. I would try uninstalling (https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox) pulling in the new code and provisioning using 

```
npm install kalabox -g
kbox provision
```

If you did the developer install you should consult https://github.com/kalabox/kalabox/wiki/Updating-Kalabox

**Comment by pirog** [comment]
were you able to install on 8.1 with success with the new version?

**Comment by donkoller** [comment]
@pirog
Actually the install went fine.
Did not recognize the kbox start; but will take a look next week. Away for weekend...
