### ISSUE TITLE
Error during kbox create: "info: Event handler has not called done. function (component, done)"

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox#207]
While [trying to get bkox rsync to work on my Windows 7 machine](https://github.com/kalabox/kalabox/issues/205), I tried creating a new Drupal app to see if the problem was internal to my existing app or not.

Unfortunately, `kbox create` never finished. It's hanging in the command window after installing the app. The complete session is at http://pastebin.com/hsYNjaRJ ; here's an excerpt:

```
(...)
info: DOCKER => Pulling image complete. name=kalabox/rsync:v0.7.0, build=false, createOpts=undefined,
startOpts=undefined, postProviderOpts=undefined
App installed.
info: DOCKER => Starting container. 906a57bd0ee9848d24d320ffe916a4ca20101581549659e7c52f1482d5ddcbfb
info: DOCKER => Container started. 906a57bd0ee9848d24d320ffe916a4ca20101581549659e7c52f1482d5ddcbfb
info: DOCKER => Starting container. 0f4c8d065db4de474d2434a0dd33b227cf4867893e7aa735d2dd2238b0048aef
info: DOCKER => Container started. 0f4c8d065db4de474d2434a0dd33b227cf4867893e7aa735d2dd2238b0048aef
info: DOCKER => Starting container. f624475ed23e014641ca81d482b969243c8495107ca9b3b1c79957b83499e79c
info: DOCKER => Container started. f624475ed23e014641ca81d482b969243c8495107ca9b3b1c79957b83499e79c
info: Event handler has not called done. function (component, done) {
    if (component.proxy) {
      engine.inspect(component.containerId, function(err, data) {
        var redisHost = kbox.core.deps.lookup('engineConfig').host;
        async.map(component.proxy, function(proxy, next) {
          var client = redis.createClient(redisPort, redisHost);
(...)
```

What's wrong?

**Comment by pirog** [comment]
have you tried just doing a `kbox restart` here?

**Comment by UTANdev** [comment]
`kbox restart`
The dependency "engineConfig" was NOT found!

**Comment by labboy0276** [comment]
Hello,

Try kbox up first then kbox restart

**Comment by UTANdev** [comment]
Took kbox down, up, then restarted. After outputting the following, the console never returned to a command prompt.

```
C:\Users\UTAN\VirtualBox VMs\mtms>kbox restart
info: SERVICES => Startup services need to be started.
info: DOCKER => Stopping container. c8d466e245998b9aa24d68757601d32084c825c74e798ff27e16538095831004
info: DOCKER => Container already stopped. c8d466e245998b9aa24d68757601d32084c825c74e798ff27e16538095831004
info: DOCKER => Stopping container. bf7cd2e0f1b4f97793ac7869bc2594a0f5430f15171a85a641183dd258408e9e
info: DOCKER => Container already stopped. bf7cd2e0f1b4f97793ac7869bc2594a0f5430f15171a85a641183dd258408e9e
info: DOCKER => Stopping container. 90d7f2270fc8eace5183d86784ae7ba16d39c4f9c59d2655037c3f5ec76b5f1f
info: DOCKER => Container already stopped. 90d7f2270fc8eace5183d86784ae7ba16d39c4f9c59d2655037c3f5ec76b5f1f
info: DOCKER => Stopping container. da879dc7182f073bbae0ba110244bdfb66c9da6c8a82730495247c8e49b817b4
info: DOCKER => Container already stopped. da879dc7182f073bbae0ba110244bdfb66c9da6c8a82730495247c8e49b817b4
info: DOCKER => Starting container. c8d466e245998b9aa24d68757601d32084c825c74e798ff27e16538095831004
info: DOCKER => Container started. c8d466e245998b9aa24d68757601d32084c825c74e798ff27e16538095831004
info: DOCKER => Starting container. bf7cd2e0f1b4f97793ac7869bc2594a0f5430f15171a85a641183dd258408e9e
info: DOCKER => Container started. bf7cd2e0f1b4f97793ac7869bc2594a0f5430f15171a85a641183dd258408e9e
info: DOCKER => Starting container. 90d7f2270fc8eace5183d86784ae7ba16d39c4f9c59d2655037c3f5ec76b5f1f
info: DOCKER => Container started. 90d7f2270fc8eace5183d86784ae7ba16d39c4f9c59d2655037c3f5ec76b5f1f
info: DOCKER => Starting container. da879dc7182f073bbae0ba110244bdfb66c9da6c8a82730495247c8e49b817b4
info: DOCKER => Container started. da879dc7182f073bbae0ba110244bdfb66c9da6c8a82730495247c8e49b817b4
info: DOCKER => Stopping container. 2a40e1b2c400a33ab701ae1af1477fa67cedebe3437cd756ff7635e827281cad
info: DOCKER => Container already stopped. 2a40e1b2c400a33ab701ae1af1477fa67cedebe3437cd756ff7635e827281cad
info: DOCKER => Stopping container. 5bea9d25400f9edaff53f0384370376c5e9c5e1540f71a4fb0bafc4adf8eafd1
info: DOCKER => Container already stopped. 5bea9d25400f9edaff53f0384370376c5e9c5e1540f71a4fb0bafc4adf8eafd1
info: DOCKER => Removing container. kalabox_syncthing
info: DOCKER => Container removed. kalabox_syncthing
info: DOCKER => Creating container.
info: DOCKER => Container created. cid=91e4da1ca3816c6536ed7c978f4ea08125a0e60a6607b0f5a530911b3056d928, name=kalabox_syncthing
info: DOCKER => Starting container. kalabox_syncthing
info: DOCKER => Container started. kalabox_syncthing
info: DOCKER => Starting container. 2a40e1b2c400a33ab701ae1af1477fa67cedebe3437cd756ff7635e827281cad
info: DOCKER => Container started. 2a40e1b2c400a33ab701ae1af1477fa67cedebe3437cd756ff7635e827281cad
info: DOCKER => Starting container. 5bea9d25400f9edaff53f0384370376c5e9c5e1540f71a4fb0bafc4adf8eafd1
info: DOCKER => Container started. 5bea9d25400f9edaff53f0384370376c5e9c5e1540f71a4fb0bafc4adf8eafd1
```

I opened a second command window to check on containers and got:

```
C:\Users\UTAN\VirtualBox VMs>kbox containers
Provider boot2docker is NOT up!

C:\Users\UTAN\VirtualBox VMs>cd mtms

C:\Users\UTAN\VirtualBox VMs\mtms>kbox containers
Provider boot2docker is NOT up!
```

**Comment by labboy0276** [comment]
Hello again, 

can you run:
```
kbox config
```
Then find the directory path for .kalabox then run:
```
path/to/.kalabox/bin/syncthing
```

Then paste the output

**Comment by labboy0276** [comment]
Actually,

That is not going to solve your issue, so dont do that, it isnt necessary.

**Comment by pirog** [comment]
Yeah usually this error message happens when the Kalabox2 virtual machine is not on. You can turn it on with `kbox up`. I wonder if your VM is aborting during this command which would explain the hanging and also the error you are getting subsequently. 

What i would do is try to replicate this error and when it hangs open up VirtualBox and see what the status of the VM is. If my theory is right you should see its status as "aborted" with a little red icon thingy.

**Comment by pirog** [comment]
Hey @stela5, 

We just released 0.8.0 which may resolve this issue. I would try uninstalling (https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox) pulling in the new code and provisioning using 

```
npm install kalabox -g
kbox provision
```

If you did the developer install you should consult https://github.com/kalabox/kalabox/wiki/Updating-Kalabox

**Comment by UTANdev** [comment]
I can't seem to install without error. (Win 7, Console2 run as administrator)

1. Uninstall Kalabox using scripts\uninstall-win32.bat, run from the srcRoot directory
2. npm install kalabox -g
3. kbox provision -- -v

Step 3 ends with the following:
```
debug: Finished services-kalabox-install (72626)
info: -- OK! 89% complete! --

debug: [17:18] Starting services-kalabox-finalize
debug: description => Finalizing Services...
debug: dependencies => services-kalabox-install
info: -- Step 17/18 --
info: Finalizing Services...
Error running step: {"name":"services-kalabox-finalize","description":"Finalizing Services...","deps":["services-kalabox-install"],"subscribes":[],"all":{},"isStep":true}: code: 255, msg: The system cannot find the path specified.

Error: code: 255, msg: The system cannot find the path specified.

    at C:\Users\Charles\AppData\Roaming\npm\node_modules\kalabox\lib\util\shell.js:98:13
    at C:\Users\Charles\AppData\Roaming\npm\node_modules\kalabox\node_modules\shelljs\src\exec.js:107:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```
How can I debug this further? Thanks.

**Comment by pirog** [comment]
You should not run as an administrator. It will prompt you when it needs
admin perms.

Try uninstall and provision again but pass in the -- -v flag for more
verbose output

On Saturday, July 18, 2015, UTAN Dev <notifications@github.com> wrote:

> I can't seem to install without error. (Win 7, Console2 run as
> administrator)
>
>    1. Uninstall Kalabox using scripts\uninstall-win32.bat, run from the
>    srcRoot directory
>    2. npm install kalabox -g
>    3. kbox provision -- -v
>
> Step 3 ends with the following:
>
> debug: Finished services-kalabox-install (72626)
> info: -- OK! 89% complete! --
>
> debug: [17:18] Starting services-kalabox-finalize
> debug: description => Finalizing Services...
> debug: dependencies => services-kalabox-install
> info: -- Step 17/18 --
> info: Finalizing Services...
> Error running step: {"name":"services-kalabox-finalize","description":"Finalizing Services...","deps":["services-kalabox-install"],"subscribes":[],"all":{},"isStep":true}: code: 255, msg: The system cannot find the path specified.
>
> Error: code: 255, msg: The system cannot find the path specified.
>
>     at C:\Users\Charles\AppData\Roaming\npm\node_modules\kalabox\lib\util\shell.js:98:13
>     at C:\Users\Charles\AppData\Roaming\npm\node_modules\kalabox\node_modules\shelljs\src\exec.js:107:7
>     at ChildProcess.exithandler (child_process.js:758:5)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Socket.<anonymous> (child_process.js:1183:11)
>     at Socket.emit (events.js:107:17)
>     at Pipe.close (net.js:485:12)
>
> How can I debug this further? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/207#issuecomment-122587782>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by UTANdev** [comment]
That is the output from "kbox provision -- -v". (See step 2)

**Comment by pirog** [comment]
@UTANdev 

we recommend you uninstall and then install  the latest 0.10!
