### ISSUE TITLE
kbox 0.8 ! error on kbox start or on restart:  "undefined is not a function"

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#211]
Uninstalled 0.7. Kept virtual box. Shut down B2D.
Installed the new kalabox. npm install kalabox -g
All seemed to go well.
Ran kbox provision. Stalled fetching the Boot2Docker-1.7.0.pkg.
Ran provision again. Finished with info: Huzzah! Victory!
kbox up    brought up Boot2Docker.
In add dir, kbox start ended with error message. Tried kbox restart. Same error message.
Trying to view from browser gives 403 Forbidden.
============================================================
Dons-MacBook-Pro:sportslife-dev donkoller3$ kbox restart
info: DOCKER =>  Stopping container. c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
info: DOCKER =>  Container stopped. c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
info: DOCKER =>  Stopping container. 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
info: DOCKER =>  Container stopped. 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
info: DOCKER =>  Stopping container. kalabox_syncthing
info: DOCKER =>  Container stopped. kalabox_syncthing
info: DOCKER =>  Removing container kalabox_syncthing. v=true, kill=false
info: DOCKER =>  Container removed. kalabox_syncthing
info: DOCKER =>  Creating container. Image=kalabox/syncthing:v0.8.0, name=kalabox_syncthing, Binds=[], NetworkMode=bridge, 60008/tcp=[HostIp=, HostPort=60008], 22000/tcp=[HostIp=, HostPort=22000], 21025/udp=[HostIp=, HostPort=21025], 21026/udp=[HostIp=, HostPort=21026], Env=[KBOX_CODEDIR=code, KALABOX=true, APPNAME=sportslife-dev, APPDOMAIN=sportslife-dev.kbox, PHP_VERSION=5.5.24]
info: DOCKER =>  Container created. cid=828ffdfbc5cbc539ad04414e3b2eb7519ef637d0ac3b09afec9aeee0f095153b, name=kalabox_syncthing
info: DOCKER =>  Starting container kalabox_syncthing.
info: DOCKER =>  Container started. kalabox_syncthing
info: DOCKER =>  Creating ad hoc container "kalabox/debian:stable". name=kalabox_temp-2a38866d-c4c7-43ca-b7e5-0fa71a128371, Cmd=[bash], Tty=true, Image=kalabox/debian:stable, Env=[APPDOMAIN=sportslife-dev.kbox, KBOX_CODEDIR=code, KALABOX=true, APPNAME=sportslife-dev, PRESSFLOW_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}}, BACKDROP_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}}, KB_APP_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}}, PHP_VERSION=5.5.24], VolumesFrom=[kb_sportslife-dev_data]
info: DOCKER =>  Ad hoc container created. 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
info: DOCKER =>  Starting ad hoc container "4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae". Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
info: DOCKER =>  Ad hoc container started. 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
info: DOCKER =>  Removing ad hoc container. 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
info: DOCKER =>  Starting container c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
info: DOCKER =>  Container started. c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
info: DOCKER =>  Starting container 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
info: DOCKER =>  Container started. 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
undefined is not a function
Dons-MacBook-Pro:sportslife-dev donkoller3$

**Comment by pirog** [comment]
This is actually the expected output. Now you need to import a site.

On Wednesday, June 24, 2015, Don Koller <notifications@github.com> wrote:

> Uninstalled 0.7. Kept virtual box. Shut down B2D.
> Installed the new kalabox. npm install kalabox -g
> All seemed to go well.
> Ran kbox provision. Stalled fetching the Boot2Docker-1.7.0.pkg.
> Ran provision again. Finished with info: Huzzah! Victory!
> kbox up brought up Boot2Docker.
> In add dir, kbox start ended with error message. Tried kbox restart. Same
> error message.
> Trying to view from browser gives 403 Forbidden.
>
> Dons-MacBook-Pro:sportslife-dev donkoller3$ kbox restart
> info: DOCKER => Stopping container.
> c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
> info: DOCKER => Container stopped.
> c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
> info: DOCKER => Stopping container.
> 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
> info: DOCKER => Container stopped.
> 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
> info: DOCKER => Stopping container. kalabox_syncthing
> info: DOCKER => Container stopped. kalabox_syncthing
> info: DOCKER => Removing container kalabox_syncthing. v=true, kill=false
> info: DOCKER => Container removed. kalabox_syncthing
> info: DOCKER => Creating container. Image=kalabox/syncthing:v0.8.0,
> name=kalabox_syncthing, Binds=[], NetworkMode=bridge, 60008/tcp=[HostIp=,
> HostPort=60008], 22000/tcp=[HostIp=, HostPort=22000], 21025/udp=[HostIp=,
> HostPort=21025], 21026/udp=[HostIp=, HostPort=21026],
> Env=[KBOX_CODEDIR=code, KALABOX=true, APPNAME=sportslife-dev,
> APPDOMAIN=sportslife-dev.kbox, PHP_VERSION=5.5.24]
> info: DOCKER => Container created.
> cid=828ffdfbc5cbc539ad04414e3b2eb7519ef637d0ac3b09afec9aeee0f095153b,
> name=kalabox_syncthing
> info: DOCKER => Starting container kalabox_syncthing.
> info: DOCKER => Container started. kalabox_syncthing
> info: DOCKER => Creating ad hoc container "kalabox/debian:stable".
> name=kalabox_temp-2a38866d-c4c7-43ca-b7e5-0fa71a128371, Cmd=[bash],
> Tty=true, Image=kalabox/debian:stable, Env=[APPDOMAIN=sportslife-dev.kbox,
> KBOX_CODEDIR=code, KALABOX=true, APPNAME=sportslife-dev,
> PRESSFLOW_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}},
> BACKDROP_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}},
> KB_APP_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"kalabox","username":"kalabox","password":"","host":"sportslife-dev.kbox","port":3306}}},"conf":{"pressflow_smart_start":1}},
> PHP_VERSION=5.5.24], VolumesFrom=[kb_sportslife-dev_data]
> info: DOCKER => Ad hoc container created.
> 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
> info: DOCKER => Starting ad hoc container
> "4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae".
> Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
> info: DOCKER => Ad hoc container started.
> 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
> info: DOCKER => Removing ad hoc container.
> 4a21d9de83a93fe235c56fadbe867c43d723141398d56cbdbfe88d97df8e6fae
> info: DOCKER => Starting container
> c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e.
> PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
> info: DOCKER => Container started.
> c47fb0b2ca64e38dd441d98dc35e17a9d9d9bea2acb14d5d9635739aeff1f92e
> info: DOCKER => Starting container
> 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8.
> PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/sportslife-dev:/src:rw]
> info: DOCKER => Container started.
> 14225ef568a7f6224af0099cc0d1588d9eb496627eb7b2ad51de746265356eb8
> undefined is not a function
> Dons-MacBook-Pro:sportslife-dev donkoller3$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/211>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pi-ron** [comment]
I also got this `undefined is not a function` message when running `kbox start` on an existing app, after updating.

**Comment by labboy0276** [comment]
Hello,

@pi-ron run kbox update within the app and do the rebuild.  Should address your issue.

We wrote the update procedures here as well: https://github.com/kalabox/kalabox/wiki/Updating-Kalabox
