### ISSUE TITLE
Document how to remove orphan containers

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#238]
_From @zanami on May 26, 2015 8:23_

Another noob question, sorry.

I have deleted some test apps without uninstalling (just rm -rf ./appfolder) and now running 'kbox containers' shows me some containers that I don't need. I don't know how to get rid of them.

So far I'm going to do something like this

```
$ boot2docker  --vm="Kalabox2" ssh
docker@boot2docker:~$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                    PORTS
9bdc2d870283        4ebf8a077743                   "/root/start.sh"       7 weeks ago         Exited (0) 2 weeks ago    0.0.0.0:49157->443/tcp, 0.0.0.0:49158->80/tcp                                                            kb_drupal7_appserver
96c7ba894f67        46950aafbcba                   "mysqld_safe"          7 weeks ago         Exited (0) 2 weeks ago    0.0.0.0:49156->3306/tcp                                                                                  kb_drupal7_db
docker@boot2docker:~$ docker rm kb_drupal7_db kb_drupal7_appserver
```

Is it the safest/proper (or "kalaboxian") way to go?

_Copied from original issue: kalabox/kalabox-issues#450_

**Comment by pirog** [comment]
_From @bcauldwell on May 26, 2015 8:56_

The command to delete a container from docker is 'docker rm -f <containerId>'. The container id can either be the nickname like kb_test_db or the docker container is which will look like a random alpha numerical string. I hope this helps.

**Comment by pirog** [comment]
_From @bcauldwell on May 26, 2015 8:59_

Also if you'd like to create an issue for a command that will do this for you automatically, I can put it on my stack soonish. I have a few ideas on how to implement it.

**Comment by pirog** [comment]
_From @zanami on May 26, 2015 9:7_

Thank you!
I don't know if something like "kbox rm"  is really needed, assuming "kbox
uninstall" removes the apps' containers (I'm not sure about that).

**Comment by pirog** [comment]
_From @bcauldwell on May 26, 2015 9:14_

I was thinking more of something like 'kbox clean' to remove any orphan containers and possibly some other cleanup tasks.

**Comment by pirog** [comment]
_From @zanami on May 26, 2015 11:38_

Oh in this case it would be quite useful especially during active dev
stage. Kalabox change and sometimes it leaves unused legacy data, configs
etc. I'd be happy to be sure my setup is perfect in it's current state. It
requires some experience with node, docker, b2d etc which I personally
don't have, to be honest.

**Comment by pirog** [comment]
Should also point out that currently there is a soft uninstall and a full uninstall

```
# Removes all containers except data container and code directory
kbox uninstall

# Removes everything
kbox uninstall -- --purge 
```

The reason for this is we need a way to wipe infrastructure but preserve data for things like `kbox rebuild` which will "rebase" your app on the latest and greatest versions of your current containers or new containers if you change your kalabox.json around.

**Comment by pirog** [comment]
_From @zanami on May 27, 2015 4:45_

From my previous issue — I have a container that holds both 'code' and
'data' folders. It's the 'code' folder of an app, the former is current and
'data' isn't used or needed in current setup but I can't delete it
(resource busy).
Will 'kbox rebuild' help in this situation? I basically want to
remove/recreate/resync this container.
I could do uninstall --purge and then install, but it requires dump/restore
for the database I think.

**Comment by pirog** [comment]
Oh interesting!

are you using the latest 0.7.0 version here? Did you update from a previous version?

**Comment by pirog** [comment]
_From @zanami on May 28, 2015 3:34_

I'm using the latest kalabox from github and update it about once a week or
so. The app in question (initially drupal7 app from examples) has been
updated from pre-0.7.0 to pre-generator 0.7 and then to generator (kbox
create drupal). At this point I missed the folder name change and just
copied my slightly modified site.conf over. So syncthing created a new
folder, while nginx was working with the old one which is also there
because container is the same (reused kb_appname_appserver).

I don't mind running into problems like this when I'm using
unstable/unreleased software. It took me a long time to figure out what's
wrong because I'm really new to docker/b2d/etc. Good thing I know a lot
more about kalabox internals now (anything is infinitely more than
nothing!).

**Comment by pirog** [comment]
haha. glad to hear that since we are not even beta yet! really appreciate you helping to test stuff out though.

So did you just swap /data/ out for /code/ in nginx?

**Comment by pirog** [comment]
ive added some stuff to the docs about uninstalling apps and also removing orphaned containers manually
https://github.com/kalabox/kalabox/wiki/Drupal-Guide#uninstalling-your-app
https://github.com/kalabox/kalabox/wiki/Backdrop-Guide
https://github.com/kalabox/kalabox/wiki/FAQ#removing-orphaned-containers

**Comment by jserrao** [comment]
@pirog - Kalabox is throwing me this warning:

> WARNING: Found orphan containers (kalabox_syncthing_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.

This message appears when I run `kbox start` and I don't see a `kbox --remove-orphans` command available.

I was checking this thread for advice on removing orphaned containers but that link you posted - https://github.com/kalabox/kalabox/wiki/FAQ#removing-orphaned-containers - is dead now. Any new advice?

**Comment by pirog** [comment]
@jserrao since its just a warning you probably are ok to proceed with it. that said we haven't used `syncthing` in a LONG time so you probably want to uninstall and reinstall kalabox in general since lots of stuff has changed since then.

Other than that there are some docs about getting into the kalabox engine so you can directly use docker (which should allow you to force remove that container)
http://docs.kalabox.io/en/stable/troubleshooting/

**Comment by jserrao** [comment]
Hmmm, that's strange because I just did the RC1 install (btw, congrats on getting there) and this warning started to get thrown. 

Really what I'm trying to do is improve performance so I'm checking off boxes in terms of cleaning and optimizing. Maybe I should just delete everything and reinstall?

**Comment by pirog** [comment]
@jserrao, not sure if you read the release notes but yeah you definitely going to want to uninstall and reinstall esp if you are upgrading from a version that had syncthing. how to do this should be in the docs

**Comment by pirog** [comment]
@jserrao there are also various issues (and sections of the documentation) that deal with improving performance so i would check those out as well

**Comment by jserrao** [comment]
Thanks, will check all that out.
