### ISSUE TITLE
Arch linux will not provision

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#247]
_From @jeremyheslop on May 25, 2015 19:16_

installing kalabox on Arch linux is not possible without commenting out a few lines to essentially disable the checking of VirtualBox. Arch does not have an official VB download so it has to be installed and setup before hand.

Maybe there could be a way to disable VB checking for those with other linux distros?

_Copied from original issue: kalabox/kalabox-issues#449_

**Comment by pirog** [comment]
_From @jeremyheslop on May 25, 2015 19:50_

Looks like there are other issues with VB not getting the proper storage controllers when b2d is initializing. the Kalabox2 VM cannot boot without the iso and vmdk which somehow does not get connected.

**Comment by pirog** [comment]
bump!

On Mon, May 25, 2015 at 1:18 PM, Mike Pirog <mike@kalamuna.com> wrote:

> On the road today but would love to figure out how to get this to work on
> arch!
>
> Don't think it will be too hard just need to learn a little more about how
> arch does its stuff.
>
> What lines are you commenting out? Version of arch? Other things?
>
> On Monday, May 25, 2015, Jeremy Heslop <notifications@github.com> wrote:
>
>> Looks like there are other issues with VB not getting the proper storage
>> controllers when b2d is initializing. the Kalabox2 VM cannot boot without
>> the iso and vmdk which somehow does not get connected.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox-issues/issues/449#issuecomment-105299442>
>> .
>>
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
_From @richardcq on May 28, 2015 17:22_

Some more information, as I was with Jeremy trying to figure this out. This is what we did to almost get it working.
On step 6 of kbox provision:
>Cannot read property 'undefined' of undefined
>TypeError: Cannot read property 'undefined' of undefined
>    at step.all (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:91:56)

workaround: comment out line 90-92
then it fails on step 12:
>Cannot read property 'path' of undefined
>TypeError: Cannot read property 'path' of undefined
>    at Object.getLinuxDNSOptions (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-services-kalabox/lib/util.js:23:48)

workaround: change line 22 to
`var dis = (flavor === 'debian') ? flavor : 'other';`
then it fails on step 14:
>Cannot read property 'undefined' of undefined
>TypeError: Cannot read property 'undefined' of undefined
>    at step.all.linux (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:125:61

workaround: comment out lines 125-131
Then it hangs at
>debug: B2D => Executing command. boot2docker up

Sorry about the delayed response by the way, I didn't see his email.
Arch is a rolling release distro, so it doesn't have a version.

**Comment by pirog** [comment]
Nice. This is really helpful. Going to spin up an arch box sometime next week and see if we can add that in here as a support distro/flavor.

**Comment by pirog** [comment]
I dont think we are going to support arch until we have more energy around this distro

**Comment by process91** [comment]
Wondering if there is any possibility of supporting this on Arch. I'm happy to help, but right now I can't figure out how to even start installing Kalabox from source.
