### ISSUE TITLE
syncthing alternatives?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#248]
_From @zanami on May 25, 2015 8:50_

Syncthing is great but it's also the main source of my kbox (v2) related frustrations

Sometimes it says it's 100% synced but in fact it is not (I get 404 error trying to access some Drupal files, that are present locally).

Sometimes I have to restart an app to solve the above and after that some older files get pulled from "remote" and overwrite that local changes (even if the local files are newer).

Sometimes it doesnt work with *Folder "whatever" isn't making progress - check logs for possible root cause*. I wanted to remove a folder (sites/all/themes/sometheme) and it keeps reappearing every time I restart syncthing.

Two questions:

I believe syncthing runs inside the kalabox, right? So how do I access it's logs?

Is there an easy alternative to syncthing? Something like nfs?

_Copied from original issue: kalabox/kalabox-issues#448_

**Comment by pirog** [comment]
_From @bcauldwell on May 25, 2015 18:12_

As of right now we do not have a syncthing alternative, however I will be
spending a lot of time in the coming weeks to improve the reliability of
syncthing file sharing for kalabox.

I encourage you to keep giving me feedback about what trouble syncthing is
giving you, so I can track down what is causing it and put a fix in place.

To answer your questions.

There is an instance of syncthing that runs inside of kalabox, in the
container kalabox_syncthing. There is also an instance running on the host
machine.

The host machine logs are stored at
HOME/.kalabox/logs/syncthing-std(out|err).log.

For the remote instance inside of kalabox, you can remote in using 'docker
exec -it kalabox_syncthing bash' and then navigate to
'/var/log/supervisor/' and you will see a stdout and stderr log.

We tested NFS at the beginning of the project with poor results as NFS
really has to be tuned to the kind of files being used. Pirog will be able
to tell you more about these results.

- Benjamin

On Mon, May 25, 2015 at 1:50 AM, zanami <notifications@github.com> wrote:

> Syncthing is great but it's also the main source of my kbox (v2) related
> frustrations
>
> Sometimes it says it's 100% synced but in fact it is not (I get 404 error
> trying to access some Drupal files, that are present locally).
>
> Sometimes I have to restart an app to solve the above and after that some
> older files get pulled from "remote" and overwrite that local changes (even
> if the local files are newer).
>
> Sometimes it doesnt work with *Folder "whatever" isn't making progress -
> check logs for possible root cause*. I wanted to remove a folder
> (sites/all/themes/sometheme) and it keeps reappearing every time I restart
> syncthing.
>
> Two questions:
>
> I believe syncthing runs inside the kalabox, right? So how do I access
> it's logs?
>
> Is there an easy alternative to syncthing? Something like nfs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/448>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
_From @zanami on May 26, 2015 1:19_

Thank you!

I belive NFS is slow and I'm all for Syncthing but it really lacks
consistency in my experience so far. I can't rely on it so I keep typing
'kbox drush cc all' and 'kbox restart' if it doesn't help. It used to work
but now it doesn't and I'm not sure what to do.

I have moved a theme folder from /sites/all/themes/theme to
/sites/somesite/themes/theme on my local system. After starting the app
syncthing creates an empty /sites/all/themes/theme folder locally. Drupal
still loads the theme from this folder (so it's not empty on the other
side). If I'm trying to delete the folder again I get that 'Folder "ddd"
isn't making progress'.

I've checked the local syncthing-stderr.log and it's empty.

I couldn't check the one in container

```
# docker exec -it kalabox_syncthing bash
FATA[0000] Post
http:///var/run/docker.sock/v1.16/containers/kalabox_syncthing/exec:
dial unix /var/run/docker.sock: no such file or directory. Are you trying
to connect to a TLS-enabled daemon without TLS?
```

**EDIT** Sorry I'm er... slow, missed the first step. I'll leave it there for people like me.

```
MBP $ boot2docker  --vm="Kalabox2" ssh
docker@boot2docker:~$ docker exec -it kalabox_syncthing bash
root@190c1928a825:/# tail -f  /var/log/supervisor/*.log
==> /var/log/supervisor/syncthing-stdout---supervisor-1ay_xc.log <==
[IBDSK] 06:19:17 INFO: Puller (folder "drupalapp", dir "sites/all/themes/ddd"): delete: remove /drupalapp/sites/all/themes/ddd: directory not empty
[IBDSK] 06:19:17 WARNING: Folder "drupalapp" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
[IBDSK] 06:19:32 INFO: Connected to already connected device (WPZORIX-PX2AW3N-2BRUJ6L-LM2EUBU-7WJCSUR-VVUICH7-FFM4SHS-QNDSAQE)
```

Host mac to kalabox vm, then to syncthing container.

**removed** as it seems more or less obvious now. I just removed the offending folder from inside the kalabox_syncthing container. One error is gone (directory not empty), but the other is there  and my drupalapp still loads the theme from /sites/all/ddd

I've also checked the appserver container and there's ddd folder in /data/sites/all/themes (but not in /code/sites/all/themes). It's time to admit I'm ~~dumb~~ lost. But wait...

I think something went wrong during kalabox/app update/upgrade process. Looks like syncthing is now syncing the **code** folder while nginx still uses **data** folder for docroot (it's from app/config/nginx/site.conf). Totally my fault.

Sorry for wasting your time and thank you again!

**Comment by pirog** [comment]
We definitely feel your pain on this one. Getting sycnthing to work more reliably is still a major roadblock to heavier adoption. I wish their were better alternatives but NFS is REALLLLY slow in this kind of architecture esp since we can't really tune it since its a low level part of every user's machine.

One thing that we can do is update to the latest syncthing and see if that helps out at all. 

Both Kalabox2 and Syncthing are still in heavy dev and we are pretty sure at the end of the say we will end up with what we all want: fast and reliable but there is still work to be done.

We very much appreciate you trying things out and posting feedback though. It's very important at this stage in the game and we are working hard to get this thing awesome!

**Comment by jpmcneal** [comment]
I realize this is an old issue, but I have also noticed some lag between saving changes in my IDE (especically when compiling Sass) and the change being reflected in kbox. I recently came across [this project](https://github.com/brikis98/docker-osx-dev) which uses rsync. The project lead also has a lot of good information in [this blog post](http://www.ybrikman.com/writing/2015/05/19/docker-osx-dev/) explaining the benefits of using rsync.

I'm not sure if I have the ability on my own to try rsync with kbox but perhaps I can recruit one of my colleagues to help.

**Comment by pirog** [comment]
so rsync is going to give you basically the same performance as syncthing. The downside of rsync vs syncthing is that rsync only syncs in one direction whereas syncthing is bi-directional. 

if you want stuff to show up instantly something like NFS would probably be a better fit. That said NFS is going to make your webserver perform very very slowly. So slowly that you are going to lose whatever gains you made in code syncing.

**Comment by pirog** [comment]
Also, i dont think rsync is native on windows :(
