### ISSUE TITLE
Installing Kalabox in a training

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#253]
We'll be doing a training at Drupal Camp Costa Rica July 29th. I don't know how many people will be attending, but I want to get an idea of how long it'll take to install Kalabox for ~30 people and explore some ways to mitigate any issues we might have. Hack-ish solutions would be ok (USB drives, etc). We should also start documenting the best way to do this to help other people who will want to use Kalabox as a training tool.

**Comment by pirog** [comment]
I think given the timeline our best bet here is to try out some sort of wireless puck situation. We can benchmark in the office and see if we might need more than one.

**Comment by reynoldsalec** [comment]
For Costa Rica, I'm going to get a SIM card for my phone and hope that's enough to supplement WiFi. I've already reached out to the camp organizers to see if I can get in touch with the training participants to tell them to pre-install Kalabox.

I'm guessing this won't really be a problem (or as big of a problem) when we have more of the dependencies packaged for the GUI release.

**Comment by pirog** [comment]
Awesome! I'll close this issue and maybe after CR you can post another one with any relevant changes we need to make to this.
