### ISSUE TITLE
Improve kalabox update/provision

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#265]
When updating to a new minor version of Kalabox there are a few things we can do better

1. Rewrite apps package.json to bump the minor version
2. ~~Grab the new VM iso and overwrite~~
3. ~~Install the new b2d package.~~
4. ~~possibly grab the new Kalabox code via npm~~

**Comment by bcauldwell** [comment]
All of those sound like good idea, but need to be handled carefully in case
something goes wrong. I'd like to do this when we get to it, or at least be
involved with it so I can make sure we don't blow out any files and then
fail leaving things in a bad state.

On Tue, Jun 30, 2015 at 11:08 AM, Mike Pirog <notifications@github.com>
wrote:

> When updating to a new minor version of Kalabox there are a few things we
> can do better
>
>    1. Rewrite apps package.json to bump the minor version
>    2. Grab the new VM iso and overwrite
>    3. Install the new b2d package.
>    4. Possibly grab the new Kalabox code via npm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/265>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
That is fine with me. I think this func is pretty key to GUI success.

**Comment by pirog** [comment]
Since B2D is end of life i dont think we need to do all of this anymore. I think i'm going to close this since the remaining action items are handled by #218
