### ISSUE TITLE
Drupal cannot connect to database

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#266]
After an error free kbox creation of a cloned drupal site, mysql the existing database, and synced the files. Then, kbox drush cc all and cleared the caches.
Browser URL:  site.kbox, but immediately came back with site.kbox/install.php.
The database info apparently is missing. I entered: DatabaseName: kalabox; DatabaseUserName: kalabox; DatabasePassword: [blank]; DatabaseHost: localhost [which is default]; Port: 32770 [from kbox containers].
Submit of the form returned:
"Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] No such file or directory."

Can anyone tell me what I did wrong?

**Comment by pirog** [comment]
host needs to be appname.kbox not localhost

On Tue, Jun 30, 2015 at 2:00 PM, Don Koller <notifications@github.com>
wrote:

> After an error free kbox creation of a cloned drupal site, mysql the
> existing database, and synced the files. Browser URL: site.kbox and
> immediately came back with site.kbox/install.php.
> The database info apparently is missing. I entered: DatabaseName: kalabox;
> DatabaseUserName: kalabox; DatabasePassword: [blank]; DatabaseHost:
> localhost [which is default]; Port: 32770 [from kbox containers].
> Submit of the form returned:
> "Failed to connect to your database server. The server reports the
> following message: SQLSTATE[HY000] [2002] No such file or directory."
>
> Can anyone tell me what I did wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/266>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by donkoller** [comment]
I must still be off.
Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known.

Actual app is called:   slx-2, but slx-2.kbox gives the above error.
=====================================================
Dons-MacBook-Pro:slx-2 donkoller3$ kbox containers
{
  "id": "23828f7cc76c612a25b9c8d3941ddffa790230b7c31e8005eb89f2d7fd148e90",
  "name": "kb_slx-2_appserver",
  "app": "slx-2",
  "ports": [
    "443/tcp=>32768",
    "80/tcp=>32769"
  ],
  "running": true
}
{
  "id": "1298e688807ec4c382cc7908d8c020d93822d1b1b7a11e5d130ae9ceb587dd36",
  "name": "kb_slx-2_db",
  "app": "slx-2",
  "ports": [
    "3306/tcp=>32770"
  ],
  "running": true
}

**Comment by pirog** [comment]
try doing a `kbox restart` and try again

**Comment by donkoller** [comment]
kbox restart ran OK.
Same error message.

Why doesn’t the site creation process give the DB info to Drupal? Should it be in the settings.php that is created?

**Comment by pirog** [comment]
If you are using a pressflow variant of drupalcore, as in the case of a pantheon site, kalabox will automatically handle your database settings, no need to mess around with settings.php. 

if you aren't using a pressflow variant, as is the case with something like acquia then you will need to enter your settings manaully into settings.php for now in the case of importing an existing database.

**Comment by pirog** [comment]
also you will want to use port 3306 in your settings.php. the larger port number is only when you are making external connections.

**Comment by donkoller** [comment]
We never use Pantheon/pressflow for our Drupal apps. Never press flow. We have our own datacenter/hosting.
I did as you suggested: created my settings.php normally in sites/default, and it works fine. Thanks, Mike @pirog

**Comment by donkoller** [comment]
Do you want to add this to the docs? For the non-pressflow folks? If it's already there, I missed it.
I can add an FAQ if you like.

**Comment by pirog** [comment]
I think its already in there somewhere but obviously not clear enough :)

feel free to edit to make it more clear or direct us to where would make sense and we can do it!

**Comment by donkoller** [comment]
Couldn't find anything in current docs, so I edited the Drupal instructions in the wiki.
