### ISSUE TITLE
DB connection goes away "getaddrinfo failed..."

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#268]
This appears to happen often after waking the host computer from sleep or other disruptions that might disrupt the VM.

The database is still available from outside the VM and within the host VM. However, when inside the appserver container, attempting to ping the database server (or the app's main domain, for that matter) fails.

It appears there's an issue with skydns and/or skydock that is preventing resolution of these hostnames from the appserver container. Perhaps there's a setting for those services that will allow the hostnames to persist?

**Comment by pirog** [comment]
this is from the skydns docs

```
Heartbeat / Keep alive

SkyDNS requires that services submit an HTTP request to update their TTL within the TTL they last supplied. If the service fails to do so within this timeframe SkyDNS will expire the service automatically. This will allow for nodes to fail and DNS to reflect this quickly.

You can update your TTL by sending an HTTP request to SkyDNS with an updated TTL, it can be the same as before to allow it to live for another 10s, or it can be adjusted to a shorter or longer duration.

curl -X PATCH -L http://localhost:8080/skydns/services/1001 -d '{"TTL":10}'
```

**Comment by pirog** [comment]
@reynoldsalec something to try out here.

1. Replace the ISO with this new one https://github.com/kalabox/kalabox-boot2docker/releases/tag/v1.7.0-2
2. Update your kalabox to version 0.8.2 and run `kbox provision` to get all the new stuff.

**Comment by reynoldsalec** [comment]
Excellent, looks like install worked and put the new TTL in for SkyDNS, so those records should hopefully stick around.

I'll report back on whether that seems to solve the issue tomorrow. Typically after closing up my computer for a day the issue shows up, so if it doesn't we'll probably have a fix.

IF it does seem to work, I'll also try creating a new app to make sure that skydock is actually available after these failures to create new entries.

**Comment by labboy0276** [comment]
Hello!

Since I am the cool kid on Ubuntu 14.04, I shall assist as well.

I have downloaded the iso and replaced the iso in ~/.kalabox/.provider.  I then grabbed that branch, re-provisioned and started an app.  All seems well so far.  I will report back if need be.

**Comment by pirog** [comment]
@reynoldsalec this seemed to work for me after a night of having my computer closed. seems to be able to create a new app fine as well. 

please confirm or deny.

**Comment by reynoldsalec** [comment]
Same thing here @pirog (although I didn't get a timeout from the docker registry when creating a new app), looks like this is a potential fix!

**Comment by pirog** [comment]
Awesome! I'm going to merge this in then since it has no obvious negatives
and we can find out sooner whether the problem persists.

On Wednesday, July 1, 2015, reynoldsalec <notifications@github.com> wrote:

> Same thing here @pirog <https://github.com/pirog> (although I didn't get
> a timeout from the docker registry when creating a new app), looks like
> this is a potential fix!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/268#issuecomment-117732753>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
