### ISSUE TITLE
EVENTS =>  Error dispatching event listeners [post-start].

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#270]
Hello

For some reason this AM I got this error again:
```
EVENTS =>  Error dispatching event listeners [post-start].
```
I did my usual routine this AM, started the box started an app.  I then created a new app, did kbox install && kbox start and it appears at the end when trying to start up syncthing it appears as:
```
info: DOCKER =>  Starting container 1fb3955059f8ffe151bedfc213c9fe532846ebeab4adf3ee638fb56483ded768. PublishAllPorts=true, Binds=[/Users/john/kalabox/apps/twomil:/src:rw]
info: DOCKER =>  Container started. 1fb3955059f8ffe151bedfc213c9fe532846ebeab4adf3ee638fb56483ded768
info: DOCKER =>  Starting container b866fa0f7030d23e3aab984f0e72d1f84e53317b471616d434c247cd5b6bd6c7. PublishAllPorts=true, Binds=[/Users/john/kalabox/apps/twomil:/src:rw]
info: DOCKER =>  Container started. b866fa0f7030d23e3aab984f0e72d1f84e53317b471616d434c247cd5b6bd6c7
info: DOCKER =>  Removing container kalabox_syncthing. v=true, kill=false
EVENTS =>  Error dispatching event listeners [post-start].
```
Anywho I did kbox down, I then went and ran this:
```
john@kalamuna:~$ sudo chown john:john -R ~/.kalabox
```
This removed whatever lock it had placed on my ~.kalabox.  The app in question started back up no problem and all is well....

I wonder why this is happening.

**Comment by pirog** [comment]
I'm guessing the lock file isn't owned by you?

On Wednesday, July 1, 2015, John Ouellet <notifications@github.com> wrote:

> Hello
>
> For some reason this AM I got this error again:
>
> EVENTS =>  Error dispatching event listeners [post-start].
>
> I did my usual routine this AM, started the box started an app. I then
> created a new app, did kbox install && kbox start and it appears at the end
> when trying to start up syncthing it appears as:
>
> info: DOCKER =>  Starting container 1fb3955059f8ffe151bedfc213c9fe532846ebeab4adf3ee638fb56483ded768. PublishAllPorts=true, Binds=[/Users/john/kalabox/apps/twomil:/src:rw]
> info: DOCKER =>  Container started. 1fb3955059f8ffe151bedfc213c9fe532846ebeab4adf3ee638fb56483ded768
> info: DOCKER =>  Starting container b866fa0f7030d23e3aab984f0e72d1f84e53317b471616d434c247cd5b6bd6c7. PublishAllPorts=true, Binds=[/Users/john/kalabox/apps/twomil:/src:rw]
> info: DOCKER =>  Container started. b866fa0f7030d23e3aab984f0e72d1f84e53317b471616d434c247cd5b6bd6c7
> info: DOCKER =>  Removing container kalabox_syncthing. v=true, kill=false
> EVENTS =>  Error dispatching event listeners [post-start].
>
> Anywho I did kbox down, I then went and ran this:
>
> john@kalamuna:~$ sudo chown john:john -R ~/.kalabox
>
> This removed whatever lock it had placed on my ~.kalabox. The app in
> question started back up no problem and all is well....
>
> I wonder why this is happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
It would appear so.  I had this problem before, so the only user that can take it over is root.  Which doesn't make too much sense to me, but maybe you have more insight.

**Comment by pirog** [comment]
This hasn't happened to me on 14.04 so I'm not sure what to say beyond
there could be something wrong with how your permissions are set up.

I do know that we took fairly large pains to make sure kalabox doesn't run
anything as root except when needed in the initial install so you lock file
*should* be owned by you.



On Wednesday, July 1, 2015, John Ouellet <notifications@github.com> wrote:

> It would appear so. I had this problem before, so the only user that can
> take it over is root. Which doesn't make too much sense to me, but maybe
> you have more insight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-117687470>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Yes, i am not sure then. This is pretty much a fresh install of Xubuntu 14.04.  I posted this here so the people can try this if need be I suppose. I will close it out.

**Comment by clickbox** [comment]
I got this error after trying to pull an existing pantheon site down.

<img width="764" alt="screen shot 2015-07-29 at 10 50 41 am" src="https://cloud.githubusercontent.com/assets/6590017/8965392/09c100e2-35e0-11e5-8306-85a72454ae95.png">

**Comment by bcauldwell** [comment]
Can you try running the command again with `-- -v` added to the end of the
command, and then post the output here.

On Wed, Jul 29, 2015 at 10:54 AM, Ezenwa Isiogu <notifications@github.com>
wrote:

> I got this error after trying to pull an existing pantheon site down.
>
> [image: screen shot 2015-07-29 at 10 50 41 am]
> <https://cloud.githubusercontent.com/assets/6590017/8965392/09c100e2-35e0-11e5-8306-85a72454ae95.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-126037278>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
<img width="1040" alt="screen shot 2015-07-29 at 11 02 24 am" src="https://cloud.githubusercontent.com/assets/6590017/8965586/5ce1cc2e-35e1-11e5-90e8-e79bb100b89c.png">

<img width="1037" alt="screen shot 2015-07-29 at 11 03 25 am" src="https://cloud.githubusercontent.com/assets/6590017/8965615/7d8a2dd6-35e1-11e5-8622-aec1511bd1e9.png">

**Comment by bcauldwell** [comment]
Did you pull the app down, delete the folder, then pull it down again?

On Wed, Jul 29, 2015 at 11:04 AM, Ezenwa Isiogu <notifications@github.com>
wrote:

> [image: screen shot 2015-07-29 at 11 02 24 am]
> <https://cloud.githubusercontent.com/assets/6590017/8965586/5ce1cc2e-35e1-11e5-90e8-e79bb100b89c.png>
>
> [image: screen shot 2015-07-29 at 11 03 25 am]
> <https://cloud.githubusercontent.com/assets/6590017/8965615/7d8a2dd6-35e1-11e5-8622-aec1511bd1e9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-126042922>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
I just tried but seems like i'm missing the code directory.

**Comment by bcauldwell** [comment]
No I'm asking if you have done that? Because if you did that's likely what
caused this to happen. Try naming your app something slightly different and
see if that works. If you delete an app or try to overwrite an app without
first uninstalling it bad things will happen.

On Wed, Jul 29, 2015 at 4:56 PM, Ezenwa Isiogu <notifications@github.com>
wrote:

> I just tried but seems like i'm missing the code directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-126132023>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
ok thanks

**Comment by bcauldwell** [comment]
Let me know if using a different name for the app works. If it does it's
because you already have an app installed under the other name. Se e the
FAQ on the wiki for instructions on how to remove the orphaned containers
of the old app. https://github.com/kalabox/kalabox/wiki/FAQ

On Wed, Jul 29, 2015 at 5:00 PM, Ezenwa Isiogu <notifications@github.com>
wrote:

> ok thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-126132469>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
I tried doing kbox create pantheon with a couple different names and they do not have the code file.

**Comment by clickbox** [comment]
the kalabox/sycnthing container says exited not sure if that is a problem

**Comment by bcauldwell** [comment]
Are you talking about the app/code directory? Did you do a `kbox install`
and `kbox start` on the app?

On Wed, Jul 29, 2015 at 5:20 PM, Ezenwa Isiogu <notifications@github.com>
wrote:

> I tried doing kbox create pantheon with a couple different names and they
> do not have the code file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/270#issuecomment-126134703>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
i'm not sure i'm probably messed up a step
