### ISSUE TITLE
After your computer sleeps for awhile it loses a connection to the internet

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#271]
Had my laptop closed for the night. Returned and couldnt pull images from the docker registry. Timed out. Could not ping anything either. Possibly also skydock fail related?

**Comment by scottalan** [comment]
In relation to computer going to sleep...I was logged into the appserver...I walked away for 5 mins, computer went to sleep, when I returned: `Connection to localhost closed by remote host.` Not sure this is related but just wanted to note it in case. This may be common.

**Comment by pirog** [comment]
@scottalan when you mean "logged in" to the appserver... did you `docker exec` in? What did you do to "log in"?
