### ISSUE TITLE
'build' key doesn't seem to do anything on kbox install

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#272]
@bcauldwell, trying to work on deving some new containers for Pantheon support. In our code we support this 'build' key for the containers. I presumed this would mean that we build from local vs. pulling? If so, it still pulls. 

```
{
  "appName": "panth",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "shareIgnores": [
    "sites/default/files/*",
    ".git"
  ],
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "6"
    },
    "kalabox-plugin-php": {
      "php-version": "5.3.29"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "Mike Pirog",
      "git-email": "mike@kalamuna.com"
    }
  },
  "appComponents": {
    "appserver": {
      "image": {
        "name": "nginx",
        "srcRoot": ":appRoot:",
        "build": true
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ]
    }
  }
}
```

**Comment by bcauldwell** [comment]
Seems like a refactoring regression.

We should move to backlog, but not sure if we should fix this for current
or future sprint.

On Wed, Jul 1, 2015 at 10:36 AM, Mike Pirog <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell>, trying to work on deving
> some new containers for Pantheon support. In our code we support this
> 'build' key for the containers. I presumed this would mean that we build
> from local vs. pulling? If so, it still pulls.
>
> {
>   "appName": "panth",
>   "appPlugins": [
>     "kalabox-plugin-dbenv",
>     "kalabox-plugin-drush",
>     "kalabox-plugin-git",
>     "kalabox-plugin-php",
>     "kalabox-plugin-rsync"
>   ],
>   "shareIgnores": [
>     "sites/default/files/*",
>     ".git"
>   ],
>   "pluginConf": {
>     "kalabox-plugin-drush": {
>       "drush-version": "6"
>     },
>     "kalabox-plugin-php": {
>       "php-version": "5.3.29"
>     },
>     "kalabox-plugin-dbenv": {
>       "settings": {
>         "conf": {
>           "pressflow_smart_start": 1
>         }
>       }
>     },
>     "kalabox-plugin-git": {
>       "git-username": "Mike Pirog",
>       "git-email": "mike@kalamuna.com"
>     }
>   },
>   "appComponents": {
>     "appserver": {
>       "image": {
>         "name": "nginx",
>         "srcRoot": ":appRoot:",
>         "build": true
>       },
>       "proxy": [
>         {
>           "port": "80/tcp",
>           "default": true
>         }
>       ]
>     }
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/272>.
>



-- 
- Benjamin Cauldwell
