### ISSUE TITLE
Do docker file cleanup better

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#276]
dockerfiles should end with

```
  apt-get clean -y && \
  apt-get autoclean -y && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/* && rm -rf && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*
```

**Comment by pirog** [comment]
I think this mostly needs to get added to the kalabox-services-kalabox files

**Comment by bcauldwell** [comment]
+1

On Thu, Jul 2, 2015 at 12:59 PM, Mike Pirog <notifications@github.com>
wrote:

> I think this mostly needs to get added to the kalabox-services-kalabox
> files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/276#issuecomment-118150638>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
I ended up doing this as part of 0.9.0
