### ISSUE TITLE
Drush 5 non empty values

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#277]
Hello,

On a D6 site with PHP 5.3 && Drush 5.  I am seeing this error when I run any kbox drush commands:

```
The following restricted PHP modes have non-empty values:            [error]
disable_functions. This configuration is incompatible with drush. 
Please check your configuration settings in
/root/.phpbrew/php/php-5.3.29/etc/php.ini or in your drush.ini file;
```

I did not override my own php.ini, this is the default setup.

**Comment by pirog** [comment]
weird. have you done any research on this?

**Comment by labboy0276** [comment]
I have not, I was just reporting as ordered.  I shall research it more.

**Comment by pirog** [comment]
Yeah if you could do some research on it that would be helpful. I'm sure
someone else has gotten this at some point.

On Thu, Jul 2, 2015 at 1:10 PM, John Ouellet <notifications@github.com>
wrote:

> I have not, I was just reporting as ordered. I shall research it more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/277#issuecomment-118152531>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
i think these are just info logs? do they interfere with the functioning of D5?

**Comment by labboy0276** [comment]
Correct.  Similar type errors when you install drush on shared hosting and your php.ini isnt configured to drush's delight.

There is much discussion on it here:

https://www.drupal.org/node/1002698

Also the solution is just to comment out disable_functions as well.

**Comment by pirog** [comment]
Seems like an easy fix. Submit a PR.

On Tue, Jul 7, 2015 at 5:58 AM, John Ouellet <notifications@github.com>
wrote:

> Correct. Similar type errors when you install drush on shared hosting and
> your php.ini isnt configured to drush's delight.
>
> There is much discussion on it here:
>
> https://www.drupal.org/node/1002698
>
> Also the solution is just to comment out disable_functions as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/277#issuecomment-119196317>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
I branched elton-rocketman on the drush plugin, was not sure if I should do master or the future.

**Comment by labboy0276** [comment]
https://github.com/kalabox/kalabox-app-drupal/pull/5
