### ISSUE TITLE
Where do I place custom drush commands?

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#280]
I have code in file: MY_COMMAND.drush.inc
Does it go into ~/.drush or somewhere else?

@pirog commented:  
"I would drop it in APPDIR/conf/drush that should get auto synced into ~/.drush inside the container."

However this does not work. Even after **kbox drush cc drush**, still cannot recognize.

**Comment by pirog** [comment]
hmm weird. yeah that should work. let me look into this as it might just be a bug.

**Comment by donkoller** [comment]
It is possible that my code has errors, so I’ll try to remember to post it for you. In the meantime, if you have a custom drush command, go ahead and try it using your suggestion.

**Comment by pirog** [comment]
i can try our old terminatur code and see what happens
https://github.com/kalamuna/terminatur

if you have a simple custom command i can try out that might be easier though :)

**Comment by donkoller** [comment]
> On Jul 7, 2015, at 1:21 PM, Mike Pirog <notifications@github.com> wrote:
> 
> i can try our old terminatur code and see what happens
> https://github.com/kalamuna/terminatur <https://github.com/kalamuna/terminatur>
> if you have a simple custom command i can try out that might be easier though :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kalabox/kalabox/issues/280#issuecomment-119274358>.
> 


<?php
/**
 * Implementation of hook_drush_command().
 *
 * @return
 *   An associative array describing your command(s).
 */
function slx_drush_drush_command() {
  $items = array();
  // Name of the drush command:  list-site-users
  $items['list-site-users'] = array(
    'description' => 'Print the list of users in the site',
    'callback' => 'drush_get_site_users',
    'aliases' => array('lsu')
  );

  return $items;
}

function drush_get_site_users() {
  $query = db_select('users', 'u');
  $query->fields('u', array('name'));
  $result = $query->execute();
  while($record = $result->fetchAssoc()) {
       print_r($record['name'],TRUE);
  }
}

**Comment by pirog** [comment]
Make sure you try this out in the latest. @labboy0276

**Comment by donkoller** [comment]
Drush code (_newcommand.drush.inc_) added to _APPDIR/conf/drush_ works for me in the new release 0.9. 
Thanks!

**Comment by pirog** [comment]
awesome! ill close this out then!
