### ISSUE TITLE
Improvements to pantheon plugin

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#284]
Currently 

- [x] Wordpress/d6/d8/backdrop?
- [x] Provide `/srv/binding/` emulation
- [x] nginx conf for each framework   
- [ ] ~~More external libraries, tika, pdf, etc~~ #418
- [ ] ~~Cron?~~ #417 
- [ ] ~~`kbox push` imports start states.~~ #419 
- [x] update terminus

**Comment by clickbox** [comment]
would be cool if kbox install checked to make sure the directory was not a regular pantheon repository. If you run kbox install on a normal pantheon git repo bad things happen.

**Comment by pirog** [comment]
@clickbox what are these "bad things" to which you are referring?

**Comment by clickbox** [comment]
I get the same error "container already exist" that I got when I accidentally deleted my pantheon app before shutting down. This occurred after running kbox install on a regular pantheon repository.

**Comment by pirog** [comment]
Thats good to know. It's also important to note that running `kbox install` on a normal pantheon repository is not a supported use case so its not surprising that it doesn't work.

**Comment by clickbox** [comment]
was a mistake I got a little kbox install trigger happy.

**Comment by pirog** [comment]
word. i know the container exists error is being worked on so hopefully
there is a resolution to that soon.

On Thu, Aug 13, 2015 at 12:18 PM, Ezenwa Isiogu <notifications@github.com>
wrote:

> was a mistake I got a little kbox install trigger happy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/284#issuecomment-130527457>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
