### ISSUE TITLE
Better hipache static files?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#287]
now that we are using a fork of hipache maybe we should edit their static HTML files for "application not found" and the like to be KALABRANDED

**Comment by reynoldsalec** [comment]
:+1:

For some error codes, suggesting a "kbox restart" in the fine print, then referring people to a channel for help might be good as well.

**Comment by pirog** [comment]
im not sure i will be able to get to this before 0.9.0 but if you want to
add some content its over here
https://github.com/kalabox/hipache/tree/master/static

should def get some easter eggs and the like in there as well

On Tue, Jul 7, 2015 at 11:59 AM, reynoldsalec <notifications@github.com>
wrote:

> [image: :+1:]
>
> For some error codes, suggesting a "kbox restart" in the fine print, then
> referring people to a channel for help might be good as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/287#issuecomment-119303543>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@reynoldsalec maybe @andrewmallis @madeofpeople @soniktrooth could help get the moving clouds in here as a background?

**Comment by soniktrooth** [comment]
@pirog I did the clouds on Kalamuna.com. Maybe you can ping me tomorrow to tak about it cos I don't really know what this is.

**Comment by pirog** [comment]
@soniktrooth not a huge rush... basically just wanted to get some branded content for hte kalabox2 "404 pages" and things like that. @reynoldsalec will be the point on this issue.

also still love when both our current github profile pics are in a github issue. i feel like it brings a certain level of "realness" and "righteousness" to the conversation.

**Comment by soniktrooth** [comment]
Yes the redeckedness goes through the roof.

**Comment by pirog** [comment]
@reynoldsalec check comment in the PR ^^

**Comment by reynoldsalec** [comment]
Ok @pirog, updated that to delete everything that's not actually used to build the static pages.

**Comment by pirog** [comment]
@reynoldsalec assigned this to me just so i dont forget to do it for 0.10.0
