### ISSUE TITLE
Drush commands fail, "needs a copy of the PEAR Console_Table library"

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#299]
All drush commands are failing with the following error on one of my applications:

```console
The drush command '@dev uli' could not be found.  Run `drush         [error
cache-clear drush` to clear the commandfile cache if you have
installed new extensions.
Drush needs a copy of the PEAR Console_Table library in order to     [error]
function, and the attempt to download this file automatically failed.
To continue you will need to download the 1.1.3 package from
http://pear.php.net/package/Console_Table, extract it into
/usr/local/src/drush6/lib directory, such that Table.php exists at
/usr/local/src/drush6/lib/Console_Table-1.1.3/Table.php.
```

I'll need to test this further when I have better wi-fi, working off my phone right now, so treat this issue as **unconfirmed.**

**Comment by labboy0276** [comment]
I have seen this before, try running kbox rebuild and see if that helps.

**Comment by pirog** [comment]
WTF?

any ideas on how to replicate?

**Comment by pirog** [comment]
So i think this happens because php5-curl isnt installed

**Comment by donkoller** [comment]
How do we install php5-curl to test this? [This is the same problem I've been having, trying to add custom drush commands.]

**Comment by pirog** [comment]
To test this out you can go into your app. The drush plugin is in the
node_modules folder. Inside of that is the drush dockerfile. I would check
out
https://github.com/kalabox/kalabox-app-pantheon/blob/elton-rocketman/app/dockerfiles/terminus/Dockerfile
for inspiration.

Once you've made the changes you can rebuild your app from "source" with
'kbox rebuild -- --build-local' this will rebuild all your containers using
the local dockerfiles instead of the images from the docker hub.

On Tuesday, July 14, 2015, Don Koller <notifications@github.com> wrote:

> How do we install php5-curl to test this? [This is the same problem I've
> been having, trying to add custom drush commands.]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/299#issuecomment-121337813>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
I actually just added this to the new release so it should come out with
that.

On Tue, Jul 14, 2015 at 2:52 PM, Mike Pirog <mike@kalamuna.com> wrote:

> To test this out you can go into your app. The drush plugin is in the
> node_modules folder. Inside of that is the drush dockerfile. I would check
> out
> https://github.com/kalabox/kalabox-app-pantheon/blob/elton-rocketman/app/dockerfiles/terminus/Dockerfile
> for inspiration.
>
> Once you've made the changes you can rebuild your app from "source" with
> 'kbox rebuild -- --build-local' this will rebuild all your containers using
> the local dockerfiles instead of the images from the docker hub.
>
> On Tuesday, July 14, 2015, Don Koller <notifications@github.com> wrote:
>
>> How do we install php5-curl to test this? [This is the same problem I've
>> been having, trying to add custom drush commands.]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox/issues/299#issuecomment-121337813>.
>>
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@reynoldsalec if you could try this with the latest docker drush image that would be good.

@donkoller if you do a `kbox rebuild` in your app you'll get the `drush` container with `php5-curl` installed. Can you let me know if that helps out with #280
