### ISSUE TITLE
Civicrm.settings.php in Kalabox

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#301]
Civicrm not loading on kalabox, Getting a message that I need to define Civicrm DSN. 
I followed the instructions here: https://kalamuna.atlassian.net/wiki/pages/viewpage.action?pageId=42991622

@labboy0276

**Comment by labboy0276** [comment]
Hello

Is it still giving you it needs the DSN?  Are you using pressflow?

**Comment by yosefromano** [comment]
Yes and Yes

—
Rabbi Yosef Romano

On July 14, 2015 at 12:50:12 PM, John Ouellet (notifications@github.com) wrote:

Hello

Is it still giving you it needs the DSN? Are you using pressflow?

**Comment by labboy0276** [comment]
Can you post your civicrm.settings in here please

**Comment by yosefromano** [comment]
I updated the civicrm.settings.php with the elseif on the inside of the if pressflow.
got this error on the browser:
![untitled](https://cloud.githubusercontent.com/assets/10218159/8684035/085f3e0a-2a2b-11e5-96cd-18d8d2ac3c69.png)

I tried to clear caches
I got this error:

Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: require_once(): Failed opening required
'CRM/Core/ClassLoader.php'
(include_path='.:/code/sites/all/modules/civicrm/:/code/sites/all/modules/civicrm//packages:.:/root/.phpbrew/php/php-5.3.29/lib/php')
in /code/sites/default/civicrm.settings.php, line 389


My civicrm doesn’t live in /sites/all/modules/civicrm/ but rather in /profiles/civicrm_starterkit/modules/civicrm

**Comment by pirog** [comment]
It might be worth waiting on this until we have pantheon integration.
Presumably you created it there?

On Tuesday, July 14, 2015, yosefromano <notifications@github.com> wrote:

> I updated the civicrm.settings.php with the elseif on the inside of the if
> pressflow.
> got this error on the browser:
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/10218159/8684035/085f3e0a-2a2b-11e5-96cd-18d8d2ac3c69.png>
>
> I tried to clear caches
> I got this error:
>
> Drush command terminated abnormally due to an unrecoverable error. [error]
> Error: require_once(): Failed opening required
> 'CRM/Core/ClassLoader.php'
>
> (include_path='.:/code/sites/all/modules/civicrm/:/code/sites/all/modules/civicrm//packages:.:/root/.phpbrew/php/php-5.3.29/lib/php')
> in /code/sites/default/civicrm.settings.php, line 389
>
> My civicrm doesn’t live in /sites/all/modules/civicrm/ but rather in
> /profiles/civicrm_starterkit/modules/civicrm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/301#issuecomment-121370970>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
OK,

In your civicrm, change this to:
$civicrm_root = '/profiles/civicrm_starterkit/modules/civicrm';

See if that helps you.

**Comment by yosefromano** [comment]
same error when loading civicrm and when clearing cache

Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: require_once(): Failed opening required
'CRM/Core/ClassLoader.php'
(include_path='.:/profiles/civicrm_starterkit/modules/civicrm:/profiles/civicrm_starterkit/modules/civicrm/packages:.:/root/.phpbrew/php/php-5.3.29/lib/php')
in /code/sites/default/civicrm.settings.php, line 389

**Comment by labboy0276** [comment]
OK

Well that error is just saying it can't find this file: ClassLoader.php.  So you have to find where that file is and change the civicrm root to reflect that.

Also, you should put /code/ before the normal drupal path as well for kb2

**Comment by pirog** [comment]
Guys. Wait on this for a few days till we have pantheon integration

On Tuesday, July 14, 2015, John Ouellet <notifications@github.com> wrote:

> OK
>
> Well that error is just saying it can't find this file: ClassLoader.php.
> So you have to find where that file is and change the civicrm root to
> reflect that.
>
> Also, you should put /code/ before the normal drupal path as well for kb2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/301#issuecomment-121401846>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Roger that, I just wrote that civi wiki yesterday too.

**Comment by yosefromano** [comment]
Sounds good!

**Comment by pirog** [comment]
Pretty sure when we drop the pantheon integration this will be seamless or
very close

On Tuesday, July 14, 2015, yosefromano <notifications@github.com> wrote:

> Sounds good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/301#issuecomment-121406016>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@yosefromano we've released 0.9.0 which has the pantheon integration. I would try the CiviCRM starterkit again. I am pretty sure it is not going to work out of the box but we are in a much better place to get it working now. I don't think it will require that much more than making sure we set `pantheon_binding` in the drupal conf and symlinking `/srv/binding`/ to our app root

**Comment by pirog** [comment]
I think this will be fixed as soon as #284 is closed.

**Comment by reynoldsalec** [comment]
Note that @yosefromano's issues were resolved on #359, where you can see the edits to the Civi settings file required to make things work.

**Comment by pirog** [comment]
Yes we are going to want to figure out how the default pantheon civicrm settings can be used to get kalabox to work. 

So if these are the things that are different:

```
// Kalabox2 settings
elseif (strpos($_SERVER['HTTP_HOST'],'kbox') !== false) {
    // Set the DB connection string
    $db_string = $env['databases']['default']['default']['driver'] . '://' . $env['databases']['default']['default']['username'] . '@';
    $db_string .= $env['databases']['default']['default']['host'] .  '/' . $env['databases']['default']['default']['database'] . '?new_link=true';
    define( 'CIVICRM_UF_DSN'           , $db_string);
    define( 'CIVICRM_DSN'           , $db_string);
    global $civicrm_root;
    $civicrm_root = '/code/profiles/civicrm_starterkit/modules/civicrm/';
    define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/civicrm/templates_c/' );
    define( 'CIVICRM_UF_BASEURL'      , 'http://' . $_SERVER['HTTP_HOST'] . '/' );
}
```

And this is what they replace:
```
//user name and password
$db_string = $pantheon_db['driver'] . '://' . $pantheon_db['username'] . ':' . $pantheon_db['password'] . '@';
//host
$db_string .= 'dbserver.' . $pantheon_conf['pantheon_environment'] . '.' . $pantheon_conf['pantheon_site_uuid'] . '.drush.in' . ':' . $pantheon_db['port'];
// database
$db_string .= '/' . $pantheon_db['database'] . '?new_link=true';

...

$civicrm_root = '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/profiles/civicrm_starterkit/modules/civicrm';

...

define('CIVICRM_TEMPLATE_COMPILEDIR', '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/files/civicrm/templates_c/');
```

**Comment by pirog** [comment]
For those in the pantheon power users group there is an ongoing convo about civicrm support 
http://groups.google.com/a/pantheon.io/group/power-users/t/4840308f370c6071?utm_source=digest&utm_medium=email
