### ISSUE TITLE
kbox update fails on rebuild on app

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#302]
When I run kbox update on the app, the update portion works fine.  When I say yes to the rebuild, it spits out error messages.  The remedy is to do a kbox up and kbox down then the kbox rebuild itself.  Here is the messages I get (from 0.8 to 0.9 on my app):

```
john@kalamuna:~/kalabox/apps/fiksu$ kbox update
info: -- Step 1/7 --
info: Authorizing update subroutines...
? Are you sure you want to update this app? Yes
info: -- OK! 14% complete! --

info: -- Step 2/7 --
info: Checking firewall settings...
info: -- OK! 29% complete! --

info: -- Step 3/7 --
info: Checking for Internet access...
info: -- OK! 43% complete! --

info: -- Step 4/7 --
info: Checking for available disk space...
info: -- OK! 57% complete! --

info: -- Step 5/7 --
info: Downloading files...
info: -- OK! 71% complete! --

info: -- Step 6/7 --
info: Updating your app deps...
npm http request GET https://registry.npmjs.org/kalabox-plugin-php
npm http request GET https://registry.npmjs.org/kalabox-plugin-git
npm http request GET https://registry.npmjs.org/kalabox-plugin-rsync
npm http request GET https://registry.npmjs.org/kalabox-plugin-dbenv
npm http request GET https://registry.npmjs.org/kalabox-plugin-drush
npm http 304 https://registry.npmjs.org/kalabox-plugin-rsync
npm http 304 https://registry.npmjs.org/kalabox-plugin-git
npm http 304 https://registry.npmjs.org/kalabox-plugin-php
npm http 304 https://registry.npmjs.org/kalabox-plugin-dbenv
npm http 304 https://registry.npmjs.org/kalabox-plugin-drush
npm WARN package.json fiksu@ No description
npm WARN package.json fiksu@ No repository field.
npm WARN package.json fiksu@ No README data
npm WARN package.json fiksu@ No license field.
npm http request GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
kalabox-plugin-php@0.8.0 node_modules/kalabox-plugin-php
└── lodash@3.10.0

kalabox-plugin-drush@0.8.2 node_modules/kalabox-plugin-drush
└── lodash@3.10.0

kalabox-plugin-git@0.8.0 node_modules/kalabox-plugin-git
└── lodash@3.10.0

kalabox-plugin-dbenv@0.8.0 node_modules/kalabox-plugin-dbenv
└── lodash@3.10.0

kalabox-plugin-rsync@0.8.2 node_modules/kalabox-plugin-rsync
└── lodash@3.10.0
info: -- OK! 86% complete! --

info: -- Step 7/7 --
info: Rebuild?
? Download new containers and rebuild app? Yes
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Sharing folders [1].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Sharing folders [2].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Sharing folders [3].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error sharing folders.: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
```

**Comment by labboy0276** [comment]
Looks like maybe the apps are not ready for 0.9 yet?

**Comment by pirog** [comment]
They should be but you are loading in 0.8.0 apps here

On Wednesday, July 15, 2015, John Ouellet <notifications@github.com> wrote:

> Looks like maybe the apps are not ready for 0.9 yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/302#issuecomment-121616221>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
yes i noticed that too, hmmmmmm

Should I just manually edit my kalabox.json to set the plugin versions?

**Comment by pirog** [comment]
Yes and you need to load the branch since there is no 0.9.0 tag yet

On Wednesday, July 15, 2015, John Ouellet <notifications@github.com> wrote:

> yes i noticed that too, hmmmmmm
>
> Should I just manually edit my kalabox.json to set the plugin versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/302#issuecomment-121617497>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
is this correct:

{
  "name": "fiksu",
  "dependencies": {
    "kalabox-plugin-dbenv": "elton-rocketman",
    "kalabox-plugin-drush": "elton-rocketman",
    "kalabox-plugin-git": "elton-rocketman",
    "kalabox-plugin-php": "elton-rocketman",
    "kalabox-plugin-rsync": "elton-rocketman"
  }
}

**Comment by pirog** [comment]
No.

On Wednesday, July 15, 2015, John Ouellet <notifications@github.com> wrote:

> is this correct:
>
> {
> "name": "fiksu",
> "dependencies": {
> "kalabox-plugin-dbenv": "elton-rocketman",
> "kalabox-plugin-drush": "elton-rocketman",
> "kalabox-plugin-git": "elton-rocketman",
> "kalabox-plugin-php": "elton-rocketman",
> "kalabox-plugin-rsync": "elton-rocketman"
> }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/302#issuecomment-121620592>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
how about this
```
{
  "name": "fiksu",
  "dependencies": {
    "kalabox-plugin-dbenv": "git://github.com/kalabox/kalabox-plugin-dbenv.git#elton-rocketman",
    "kalabox-plugin-drush": "git://github.com/kalabox/kalabox-plugin-drush.git#elton-rocketman",
    "kalabox-plugin-git": "git://github.com/kalabox/kalabox-plugin-git.git#elton-rocketman",
    "kalabox-plugin-php": "git://github.com/kalabox/kalabox-plugin-php.git#elton-rocketman",
    "kalabox-plugin-rsync": "git://github.com/kalabox/kalabox-plugin-rsync.git#elton-rocketman"
  }
}
```

**Comment by labboy0276** [comment]
yes that was correct, still getting the error though, looks similar to the stdin issue?:

```
john@kalamuna:~/kalabox/apps/fiksu$ kbox update
info: -- Step 1/7 --
info: Authorizing update subroutines...
? Are you sure you want to update this app? Yes
info: -- OK! 14% complete! --

info: -- Step 2/7 --
info: Checking firewall settings...
info: -- OK! 29% complete! --

info: -- Step 3/7 --
info: Checking for Internet access...
info: -- OK! 43% complete! --

info: -- Step 4/7 --
info: Checking for available disk space...
info: -- OK! 57% complete! --

info: -- Step 5/7 --
info: Downloading files...
info: -- OK! 71% complete! --

info: -- Step 6/7 --
info: Updating your app deps...
npm http request GET https://registry.npmjs.org/kalabox-plugin-git
npm http request GET https://registry.npmjs.org/kalabox-plugin-php
npm http request GET https://registry.npmjs.org/kalabox-plugin-dbenv
npm http request GET https://registry.npmjs.org/kalabox-plugin-drush
npm http request GET https://registry.npmjs.org/kalabox-plugin-rsync
npm http 304 https://registry.npmjs.org/kalabox-plugin-php
npm http 304 https://registry.npmjs.org/kalabox-plugin-git
npm http 304 https://registry.npmjs.org/kalabox-plugin-dbenv
npm http 304 https://registry.npmjs.org/kalabox-plugin-rsync
npm http 304 https://registry.npmjs.org/kalabox-plugin-drush
npm WARN package.json fiksu@ No description
npm WARN package.json fiksu@ No repository field.
npm WARN package.json fiksu@ No README data
npm WARN package.json fiksu@ No license field.
npm http request GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
kalabox-plugin-drush@0.9.0 node_modules/kalabox-plugin-drush
└── lodash@3.10.0

kalabox-plugin-rsync@0.9.0 node_modules/kalabox-plugin-rsync
└── lodash@3.10.0

kalabox-plugin-git@0.9.0 node_modules/kalabox-plugin-git
└── lodash@3.10.0

kalabox-plugin-dbenv@0.9.0 node_modules/kalabox-plugin-dbenv
└── lodash@3.10.0

kalabox-plugin-php@0.9.0 node_modules/kalabox-plugin-php
└── lodash@3.10.0
info: -- OK! 86% complete! --

info: -- Step 7/7 --
info: Rebuild?
? Download new containers and rebuild app? Yes
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Sharing folders [1].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: BOOT2DOCKER =>  Sharing folders [2].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: BOOT2DOCKER =>  Sharing folders [3].
info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error sharing folders.: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

john@kalamuna:~/kalabox/apps/fiksu$ 
```

**Comment by pirog** [comment]
It's a virtualbox error so you'll have to check the VB docs. Don't see
anything to indicate stdin involvement.

On Wednesday, July 15, 2015, John Ouellet <notifications@github.com> wrote:

> yes that was correct, still getting the error though, looks similar to the
> stdin issue?:
>
> john@kalamuna:~/kalabox/apps/fiksu$ kbox update
> info: -- Step 1/7 --
> info: Authorizing update subroutines...
> ? Are you sure you want to update this app? Yes
> info: -- OK! 14% complete! --
>
> info: -- Step 2/7 --
> info: Checking firewall settings...
> info: -- OK! 29% complete! --
>
> info: -- Step 3/7 --
> info: Checking for Internet access...
> info: -- OK! 43% complete! --
>
> info: -- Step 4/7 --
> info: Checking for available disk space...
> info: -- OK! 57% complete! --
>
> info: -- Step 5/7 --
> info: Downloading files...
> info: -- OK! 71% complete! --
>
> info: -- Step 6/7 --
> info: Updating your app deps...
> npm http request GET https://registry.npmjs.org/kalabox-plugin-git
> npm http request GET https://registry.npmjs.org/kalabox-plugin-php
> npm http request GET https://registry.npmjs.org/kalabox-plugin-dbenv
> npm http request GET https://registry.npmjs.org/kalabox-plugin-drush
> npm http request GET https://registry.npmjs.org/kalabox-plugin-rsync
> npm http 304 https://registry.npmjs.org/kalabox-plugin-php
> npm http 304 https://registry.npmjs.org/kalabox-plugin-git
> npm http 304 https://registry.npmjs.org/kalabox-plugin-dbenv
> npm http 304 https://registry.npmjs.org/kalabox-plugin-rsync
> npm http 304 https://registry.npmjs.org/kalabox-plugin-drush
> npm WARN package.json fiksu@ No description
> npm WARN package.json fiksu@ No repository field.
> npm WARN package.json fiksu@ No README data
> npm WARN package.json fiksu@ No license field.
> npm http request GET https://registry.npmjs.org/lodash
> npm http 304 https://registry.npmjs.org/lodash
> kalabox-plugin-drush@0.9.0 <https://registry.npmjs.org/lodashkalabox-plugin-drush@0.9.0> node_modules/kalabox-plugin-drush
> └── lodash@3.10.0
>
> kalabox-plugin-rsync@0.9.0 node_modules/kalabox-plugin-rsync
> └── lodash@3.10.0
>
> kalabox-plugin-git@0.9.0 node_modules/kalabox-plugin-git
> └── lodash@3.10.0
>
> kalabox-plugin-dbenv@0.9.0 node_modules/kalabox-plugin-dbenv
> └── lodash@3.10.0
>
> kalabox-plugin-php@0.9.0 node_modules/kalabox-plugin-php
> └── lodash@3.10.0
> info: -- OK! 86% complete! --
>
> info: -- Step 7/7 --
> info: Rebuild?
> ? Download new containers and rebuild app? Yes
> info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
> info: BOOT2DOCKER =>  Initializing boot2docker [1].
> info: BOOT2DOCKER =>  Sharing folders [1].
> info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
> VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
> VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
>
>     at ChildProcess.exithandler (child_process.js:751:12)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Socket.<anonymous> (child_process.js:1183:11)
>     at Socket.emit (events.js:107:17)
>     at Pipe.close (net.js:485:12)
> info: BOOT2DOCKER =>  Sharing folders [2].
> info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
> VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
> VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
>
>     at ChildProcess.exithandler (child_process.js:751:12)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> info: BOOT2DOCKER =>  Sharing folders [3].
> info: BOOT2DOCKER =>  Sharing folder failed, retrying. Error: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
> VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
> VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
>
>     at ChildProcess.exithandler (child_process.js:751:12)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Socket.<anonymous> (child_process.js:1183:11)
>     at Socket.emit (events.js:107:17)
>     at Pipe.close (net.js:485:12)
> Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error sharing folders.: Command failed: /bin/sh -c VBoxManage sharedfolder add "Kalabox2" --name "Users" --hostpath "/home"
> VBoxManage: error: The machine 'Kalabox2' is already locked for a session (or being unlocked)
> VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
>
> john@kalamuna:~/kalabox/apps/fiksu$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/302#issuecomment-121623118>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
Alright, this has always happened for me as a FYI since we had kbox update implemented as a command.  kbox down and up removes the lock and then I run kbox rebuild, all is well after that.  Happened to me when I had 12.04 installed, happens now on 14.04.

I will investigate more and put my findings here.

**Comment by pirog** [comment]
thanks. good to know. probably will be deprecating the update functionality
for a more generic and holistic upgrade command soon.

On Wed, Jul 15, 2015 at 10:01 AM, John Ouellet <notifications@github.com>
wrote:

> Alright, this has always happened for me as a FYI since we had kbox update
> implemented as a command. kbox down and up removes the lock and then I run
> kbox rebuild, all is well after that. Happened to me when I had 12.04
> installed, happens now on 14.04.
>
> I will investigate more and put my findings here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/302#issuecomment-121624728>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
Going to mark this as duplicate and redirect to this: #218
