### ISSUE TITLE
BIOS setting "VT-X" on Windows could prevent VirtualBox

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#305]
BIOS setting "VT-X" on Windows could prevent VirtualBox

Windows 7 Home Premium

**Comment by pirog** [comment]
@bcauldwell did you get Karla's contact info at all? Would be great to get her involved in this issue if possible.

**Comment by pirog** [comment]
@bcauldwell bump

**Comment by bcauldwell** [comment]
Yes I have a way to get in contact with her through someone else, I'll try
to get an email.

On Thu, Jul 23, 2015 at 1:12 PM, Mike Pirog <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell> bump
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/305#issuecomment-124227036>.
>



-- 
- Benjamin Cauldwell

**Comment by reynoldsalec** [comment]
Note that we require VT-x be enabled, as should be the case on most modern Windows computers.

Numerous guides exist to enable this feature (which is required for VirtualBox to work properly); check out http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/ as an example.
