### ISSUE TITLE
Can't obtain images in sites/default/files/... but see them in sites/all/themes/...

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#306]
**Can't obtain images in sites/default/files/... but see them in sites/all/themes/...**
**Version of app on web server works fine.**
```html
     <img id="big-photo" class="our-big-photo" typeof="foaf:Image" src="http://myappslx.com/sites/default/files/styles/public/pictures/picture-1.jpg?itok=G89HGVZf" width="300" height="275" alt="">
```

**Kbox version of app cannot retrieve the image.**

```html
     <img id="big-photo" class="our-big-photo" typeof="foaf:Image" src="http://slx-local.kbox/sites/default/files/styles/public/pictures/picture-1.jpg?itok=dv6bAXbC" width="300" height="275" alt="">
```
Otherwise app is working OK.
Mac. Kalabox 0.81. Non-pressflow.
Kbox up and started.
Syncthing 127.0.0.1:60008 shows normal operation.

**Comment by pirog** [comment]
If this file was generated remotely you may need to sync your files back down again? If this is a Pantheon site the new 0.9.0 version has some automatic tools for you to do this.

**Comment by donkoller** [comment]
Not a pantheon site.
I'll try to sync the files again. That does not seem like the problem.

**Comment by donkoller** [comment]
Same result. Images (pix) are there in Mac. Syncthing seems to be running OK. Next I'll ssh into the VM and look at the files there.

**Comment by donkoller** [comment]
From ssh to the vm, I see that the image is there in directory:
docker@boot2docker:/Users/donkoller3/Sites/myslxlocal/code/sites/default/files$

[NOTE: This is a different clone of my dev site; it's called myslxlocal.kbox; the one in the first note in this thread was slx-local.kbox.]

**Comment by pirog** [comment]
So, by default these directories are not shared by syncthing. You need to remove the entry in the sharesIgnore in your app's kalabox.json and i *think* rebuild the app but possibly just restart.

**Comment by donkoller** [comment]
That change to kalabox.json had no effect.
Well, the particular images were already in the vm from when I synced the files over to build the site. 

I've ssh'd into the vm. [docker@boot2docker:/Users/donkoller3/Sites/myslxlocal/code/sites/default/files$ ]
The image file(s) is/are there. For each image, the HTTP is returning 404 not found. Yet via ssh, I can see the files in their proper location in the vm directories.

Here is the browser console:
GET picture-1-1434661366.jpg:1
http://myslxlocal.kbox/sites/default/files/styles/player_profile_photo/public/pictures/picture-1-1434661366.jpg?itok=cRnf0iQx 404 (Not Found)

**Comment by pirog** [comment]
Just because they are in the VM it doesnt mean they get all the way into
the webserver container. If you actually run something like `docker exec
-it kb_appname_appserver bash` in the vm you can get into your container
and i doubt you will see the files in there.

I definitely think this is an issue with syncthing not syncing over
sites/default/files when you remove it from sharesIgnore. This was a bug on
older versions of kalabox so you might need to upgrade to get the fix.

On Wed, Jul 22, 2015 at 4:54 PM, Don Koller <notifications@github.com>
wrote:

> That change to kalabox.json had no effect.
> Well, the particular images were already in the vm from when I synced the
> files over to build the site.
>
> I've ssh'd into the vm. [docker@boot2docker:/Users/donkoller3/Sites/myslxlocal/code/sites/default/files$
> ]
> The image file(s) is/are there. For each image, the HTTP is returning 404
> not found. Yet via ssh, I can see the files in their proper location in the
> vm directories.
>
> Here is the browser console:
> GET picture-1-1434661366.jpg:1
>
> http://myslxlocal.kbox/sites/default/files/styles/player_profile_photo/public/pictures/picture-1-1434661366.jpg?itok=cRnf0iQx
> 404 (Not Found)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/306#issuecomment-123859557>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by donkoller** [comment]
I've updated the kalabox.json to NOT ignore files (deleted that line). Ran kbox rebuild. Ran kbox start.
Now I'm going to look at the container.

**Comment by donkoller** [comment]
You are correct about the container hot having anything much in the files dir, per the sharesIgnore. here's my updated (removed the ignore of files line) kalabox.json:

```
{
  "appName": "myslxlocal",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "shareIgnores": [
    ".git"
  ],
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "6"
    },
    "kalabox-plugin-php": {
      "php-version": "5.5.24"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "donkoller",
      "git-email": "dkoller@eafoundation.com"
    }
  },
  "appComponents": {
    "appserver": {
      "image": {
        "name": "php-appserver",
        "srcRoot": ":appRoot:"
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ]
    },
    "db": {
      "image": {
        "name": "mariadb",
        "srcRoot": ":appRoot:"
      }
    }
  }
}
```

Will try to rebuild and start.

**Comment by donkoller** [comment]
Still no files there.

```
Dons-MacBook-Pro:code donkoller3$ boot2docker --vm="Kalabox2" ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.7.0, build master : c011a58 - Fri Jun 19 00:44:10 UTC 2015
Docker version 1.7.0, build 0baf609
docker@boot2docker:~$ docker exec -it kb_myslxlocal_appserver bash
root@appserver:/# cd code
root@appserver:/code# ls
CHANGELOG.txt	   INSTALL.pgsql.txt   KOZNQv8t.html	README.md    authorize.php  index.php	 modules     robots.txt standard file copy.txt	sportslifex.com  web.config
COPYRIGHT.txt	   INSTALL.sqlite.txt  LICENSE.txt	README.txt   cron.php	    install.php  profiles    scripts				themes		 xmlrpc.php
INSTALL.mysql.txt  INSTALL.txt	       MAINTAINERS.txt	UPGRADE.txt  includes	    misc	 robots.txt  sites				update.php
root@appserver:/code# cd sites/default/files
root@appserver:/code/sites/default/files# ls -a
.  ..  .htaccess  ctools  less
```

**Comment by pirog** [comment]
What version of Kalabox are you running? There was a bug here that was resolved fairly recently so its possible you dont have that fix in your version.

**Comment by donkoller** [comment]
0.8.1
But I'll be glad to rebuild everything. What steps should I take?

**Comment by donkoller** [comment]
Note in the kbox config that there is at least one ref to 0.8.0.
For services (just before shareIgnores):    __"services": "kalabox-services-kalabox@0.8.0",__

```
Dons-MacBook-Pro:code donkoller3$ kbox config
{
  "appCidsRoot": "/Users/donkoller3/Sites/myslxlocal/.cids",
  "appComponents": [
    {
      "image": {
        "name": "php-appserver",
        "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ],
      "name": "appserver",
      "hostname": "appserver.myslxlocal.kbox",
      "appDomain": "myslxlocal.kbox",
      "url": "http://appserver.myslxlocal.kbox",
      "dataContainerName": "kb_myslxlocal_data",
      "containerName": "kb_myslxlocal_appserver",
      "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/appserver",
      "containerId": "aecc69ce63ac106639b78588fe4046c55357797553a44a95abaede59da4178aa"
    },
    {
      "image": {
        "name": "mariadb",
        "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
      },
      "name": "db",
      "hostname": "db.myslxlocal.kbox",
      "appDomain": "myslxlocal.kbox",
      "url": "http://db.myslxlocal.kbox",
      "dataContainerName": "kb_myslxlocal_data",
      "containerName": "kb_myslxlocal_db",
      "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/db",
      "containerId": "af371ae33b9aec2f13ac9752b1f6d49f21a59c77e5550a212b71335213641a1e"
    }
  ],
  "appName": "myslxlocal",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "appRegistry": "/Users/donkoller3/.kalabox/appRegistry.json",
  "appRoot": "/Users/donkoller3/Sites/myslxlocal",
  "apps": [
    "kalabox-app-drupal@0.8.1",
    "kalabox-app-backdrop@0.8.1"
  ],
  "appsRoot": "/Users/donkoller3/kalabox/apps",
  "codeDir": "code",
  "configSources": [
    "DEFAULT_GLOBAL_CONFIG",
    "ENV_CONFIG"
  ],
  "domain": "kbox",
  "downloadsRoot": "/Users/donkoller3/.kalabox/downloads",
  "engine": "kalabox-engine-docker@0.8.1",
  "engineRepo": "kalabox",
  "globalPluginRoot": "/Users/donkoller3/kalabox/plugins",
  "globalPlugins": [
    "kalabox-core",
    "kalabox-syncthing",
    "kalabox-app-drupal",
    "kalabox-app-backdrop"
  ],
  "home": "/Users/donkoller3",
  "kalaboxRoot": "/Users/donkoller3/kalabox",
  "kboxRoot": "/Users/donkoller3/kalabox",
  "logLevel": "debug",
  "logLevelConsole": "info",
  "logRoot": "/Users/donkoller3/.kalabox/logs",
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "release": "14.4.0",
    "arch": "x64"
  },
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "6"
    },
    "kalabox-plugin-php": {
      "php-version": "5.5.24"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "donkoller",
      "git-email": "dkoller@eafoundation.com"
    }
  },
  "profile": "standard",
  "provisioned": true,
  "services": "kalabox-services-kalabox@0.8.0",
  "shareIgnores": [
    "*.7z",
    "*.bz2",
    "*.dmg",
    "*.gz",
    "*.iso",
    "*.jar",
    "*.rar",
    "*.tar",
    "*.tgz",
    "*.un~",
    "*.zip",
    ".*.swp",
    ".*DS_Store",
    ".DS_Store*",
    "._*",
    ".git",
    ".sass-cache",
    "Icon",
    "Thumbs.db",
    "ehthumbs.db",
    "sites/default/files/*"
  ],
  "sharing": true,
  "srcRoot": "/usr/local/lib/node_modules/kalabox",
  "stats": {
    "report": true,
    "url": "http://stats.kalabox.biz"
  },
  "sysConfRoot": "/Users/donkoller3/.kalabox",
  "sysProviderRoot": "/Users/donkoller3/.kalabox/.provider",
  "version": "0.8.1",
  "homeBind": "/Users/donkoller3",
  "codeRoot": "/Users/donkoller3/Sites/myslxlocal/code"
}
```

**Comment by donkoller** [comment]
I'm running npm install kalabox -g
Trying to update to 0.9.3.
Stopped:
```
info: -- Step 17/19 --
info: Restarting engine for updates...
info: DOCKER =>  Creating container. Image=kalabox/syncthing:v0.9.0, name=kalabox_syncthing, Binds=undefined, NetworkMode=bridge, 60008/tcp=[HostIp=, HostPort=60008], 22000/tcp=[HostIp=, HostPort=22000], 21025/udp=[HostIp=, HostPort=21025], 21026/udp=[HostIp=, HostPort=21026], VolumesFrom=[kalabox_data], Env=[KBOX_CODEDIR=code, KALABOX=true]
Error running step: {"name":"engine-docker-prepared","description":"Restarting engine for updates...","deps":["core-image-prepare"],"subscribes":[],"isStep":true}: Error while shutting down.: EVENTS =>  Error dispatching event listeners [pre-down].
```

**Comment by bcauldwell** [comment]
This is known bug discovered today. I'm currently working on a fix for it.
I will also try to respond soon with a work around to get you up and
running before the bug gets fixed.

On Thu, Jul 23, 2015 at 3:07 PM, Don Koller <notifications@github.com>
wrote:

> I'm running npm install kalabox -g
> Trying to update to 0.9.3.
> Stopped:
>
> info: -- Step 17/19 --
> info: Restarting engine for updates...
> info: DOCKER =>  Creating container. Image=kalabox/syncthing:v0.9.0, name=kalabox_syncthing, Binds=undefined, NetworkMode=bridge, 60008/tcp=[HostIp=, HostPort=60008], 22000/tcp=[HostIp=, HostPort=22000], 21025/udp=[HostIp=, HostPort=21025], 21026/udp=[HostIp=, HostPort=21026], VolumesFrom=[kalabox_data], Env=[KBOX_CODEDIR=code, KALABOX=true]
> Error running step: {"name":"engine-docker-prepared","description":"Restarting engine for updates...","deps":["core-image-prepare"],"subscribes":[],"isStep":true}: Error while shutting down.: EVENTS =>  Error dispatching event listeners [pre-down].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/306#issuecomment-124251666>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
@donkoller I have a fix for this. If you just update to kalabox 0.9.4 the issue should be resolved.

**Comment by donkoller** [comment]
Hey, Ben, Thanks! Trying it now.

**Comment by donkoller** [comment]
That solved it. Thanks.
Now my container has everything I need for my local site testing.
So, for the record, I am running Kalabox 0.9.4 on Mac/Yosemite.
The site code was cloned form its github repo.
Database was loaded from a backup_migrate download. (I had to change the file name extension from .mysql to .sql.)
Copied over the sites/default/files stuff I needed for local testing into code/sites/default/files. Syncthing did the rest: synched code and files into the app container.
Runs just like the dev site. Yay!

**Comment by bcauldwell** [comment]
Great to hear!

**Comment by donkoller** [comment]
Ben, I was reading issue #327 thread, and saw that you referenced an npm command as:

npm install kalabox@0.9.4 kbox provision

Did not know that you could specify the kalabox version (of course I should have known there is a way to do this). Assume default is latest version.

Also, should this be 2 concatenated commands?

npm install kalabox@0.9.4 && kbox provision

**Comment by bcauldwell** [comment]
Yup default is the latest version, so theres really no reason to add on the
version unless you want an older version, or you want to be very specific
about which version you want.

As far as concat'ing the commands together, yes you could certainly concat
them with '&&'.

On Thu, Jul 23, 2015 at 7:51 PM, Don Koller <notifications@github.com>
wrote:

> Ben, I was reading issue #327 thread, and saw that you referenced an npm
> command as:
>
> npm install kalabox@0.9.4 kbox provision
>
> Did not know that you could specify the kalabox version (of course I
> should have known there is a way to do this). Assume default is latest
> version.
>
> Also, should this be 2 concatenated commands?
>
> npm install kalabox@0.9.4 && kbox provision
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/306#issuecomment-124298249>.
>



-- 
- Benjamin Cauldwell
