### ISSUE TITLE
Bad link for Pantheon docs in README.md

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox#316]
`Or [Pantheon](https://github.com/kalabox/kalabox/wiki/Backdrop-Guide) guides.`

should be

`or [Pantheon](https://github.com/kalabox/kalabox/wiki/Pantheon-Guide) guides.`

*edit:* I was looking at 0.9.0 and didn't notice that Mike had already fixed that by now.

**Comment by reynoldsalec** [comment]
Hey @UTANdev, noticed you've been really helpful in reporting issues and wanted to invite you to our testing "Circle of Trust". We'll keep you updated on new Kalabox releases, alert you to potential bugs we're noticing, and may ask for your help testing different solutions. If you're interested, you can signup at http://bit.ly/kbox-trust

Thanks again for reporting on these issues!

**Comment by UTANdev** [comment]
Hi Alec,

Thanks! I would totally be a beta tester, but after experiencing way too many problems on my Windows setup and losing two months of time trying to get Kalabox to work reliably, I had to regretfully leave it aside for now and return to my trusty old Quickstart VirtualBox development environment. I wish you the best of luck with the project.

Enjoy your weekend,

MC
  ----- Original Message -----
