### ISSUE TITLE
Pantheon App: Nginx 413 Request Entity Too Large

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#320]
I am putting this here so I can do a PR.  The php.ini settings are good and are set to upload_max_filesize = 100M && post_max_size = 100M.  However Nginx is not obeying ( I tried to upload a 5MB image file and it said no way JOSE) and we need to set client_max_body_size 100M; in nginx.conf as well.

**Comment by pirog** [comment]
Don't need to post an issue to submit a PR but thanks for posting

On Sunday, July 19, 2015, John Ouellet <notifications@github.com> wrote:

> I am putting this here so I can do a PR. The php.ini settings are good and
> are set to upload_max_filesize = 100M && post_max_size = 100M. However
> Nginx is not obeying ( I tried to upload a 5MB image file and it said no
> way JOSE) and we need to set client_max_body_size 100M; in nginx.conf as
> well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/320>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
should i submit a PR against master for now? I dont think the new branches are up yet.

**Comment by pirog** [comment]
yeah against master should be good. might want to consider doing it for the
other apps as well

On Sun, Jul 19, 2015 at 1:50 PM, John Ouellet <notifications@github.com>
wrote:

> should i submit a PR against master for now? I dont think the new branches
> are up yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/320#issuecomment-122688588>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
OK I did PRs on each of the 3 apps.
