### ISSUE TITLE
Stub out GUI installer

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#321]
@reynoldsalec @bcauldwell 
 Opening this issue and assigning it to @reynoldsalec even though all of us are going to work on this.

since we will be remote i think it would be good to post any relevant or helpful information on this here as we work on this. such as how to get set up with development for the gui, etc.

**Comment by reynoldsalec** [comment]
Now
- figure out how to run all the bin/kbox.js initialization (loads dependencies) before running the main provision task
- use the function from kalabox-core/provision.js (util.createFrameworkFunc(task, kbox.install);) in the GUI code to start provisioning

Later
- Ben will be taking bin/kbox.js and make it more generic so the GUI can share basic provisioning tasks with the CLI

**Comment by pirog** [comment]
So here are some things we will probably need to do to start

1. Get the initialization stuff from bin/kbox.js into the GUI
2. Set the mode dep to GUI so that you get GUI auth prompts vs sudo
3. Try to run the function that `kbox provision` runs

**Comment by reynoldsalec** [comment]
More Later:
- Figure out how we'll allow plugins to add GUI elements.
- Refactor the installer to use this pattern.

**Comment by reynoldsalec** [comment]
Omnibus Install (Now)
- Use the current Travis build process to include dependencies like the boot2docker package (VirtualBox), syncthing, couple flat files.


Semi-related note: For a training version, looking at designating a directory to pull containers from my allow an omnibus version that includes ALL dependencies for building kbox and apps. @bcauldwell might have some ideas here, although this is a lower priority issue compared to the main installer.

**Comment by reynoldsalec** [comment]
Note stubbing out of various tasks in #366, #367, and #365.

**Comment by pirog** [comment]
If you think this meta issue had been sufficiently delegated and expressed
elsewhere remove its point total and close it.

On Sat, Aug 8, 2015 at 5:47 AM, reynoldsalec <notifications@github.com>
wrote:

> Note stubbing out of various tasks in #366
> <https://github.com/kalabox/kalabox/issues/366>, #367
> <https://github.com/kalabox/kalabox/issues/367>, and #365
> <https://github.com/kalabox/kalabox/issues/365>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/321#issuecomment-128840392>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by reynoldsalec** [comment]
For right now we're reducing the point totals on this issue as other issues get delegated.

**Comment by reynoldsalec** [comment]
Issues #378 and #400 cover pre-packaging Boot2Docker and Syncthing with the installer to have less dependencies installed from the internet.

Issue #379 covers having a basic dashboard with a start/stop button.

**Comment by reynoldsalec** [comment]
Leaving this task until we've completed all subtasks, then we should go back through and re-visit the "later" items we defined at the beginning to create followup tasks for next sprint.

**Comment by pirog** [comment]
sounds good
