### ISSUE TITLE
Symlinking the "code" directory or using subdirectories

### ISSUE THREAD

**Issue by quicksketch** [kalabox/kalabox#324]
A lot of my repositories have peripheral items in the root of the repository, with the PHP code in a `docroot` or `www` directory. For example, see the Lullabot Boilerplate for stubbing out a typical Drupal project: https://github.com/Lullabot/drupal-boilerplate

The trouble with this is that Kalabox assumes that the docroot is directly within the "code" directory of a Kalabox app. I tried symlinking from `myproject/docroot` to `code`, but apparently all syncing is immediately broken by this. Apparently syncthing supported symlinks once but then removed the option later. Now it doesn't support it at all: https://github.com/syncthing/syncthing/issues/92

The problem I'm encountering now is that without moving my code to the root of the repository, my sites all must be accessed in a sub directory when access through the web browser, e.g. `http://example.kbox/docroot`. With a good amount of code that assumes a top-level docroot, this breaks most sites.

I'm not familiar with syncthing or how we're using it. Is there any way we can make it sync a subdirectory or symlink instead of having this subdirectory?

**Comment by pirog** [comment]
I think there is an issue open about changing the name of the web root.

Also I don't know who Nate Haug is anymore. Is that an alias now? :)
congrats guys. Love how you did it.

On Tuesday, July 21, 2015, Nate Haug <notifications@github.com> wrote:

> A lot of my repositories have peripheral items in the root of the
> repository, with the PHP code in a docroot or www directory. For example,
> see the Lullabot Boilerplate for stubbing out a typical Drupal project:
> https://github.com/Lullabot/drupal-boilerplate
>
> The trouble with this is that Kalabox assumes that the docroot is directly
> within the "code" directory of a Kalabox app. I tried symlinking from
> myproject/docroot to code, but apparently all syncing is immediately
> broken by this. Apparently syncthing supported symlinks once but then
> removed the option later. Now it doesn't support it at all:
> syncthing/syncthing#92 <https://github.com/syncthing/syncthing/issues/92>
>
> The problem I'm encountering now is that without moving my code to the
> root of the repository, my sites all must be accessed in a sub directory
> when access through the web browser, e.g. http://example.kbox/docroot.
> With a good amount of code that assumes a top-level docroot, this breaks
> most sites.
>
> I'm not familiar with syncthing or how we're using it. Is there any way we
> can make it sync a subdirectory or symlink instead of having this
> subdirectory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/324>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by quicksketch** [comment]
Ha thanks Mike! :love_hotel: 

For now I'm trying to modify the `config/nginx/site.conf` to point at `code/docroot` to just make nginx point at the sub directory and have syncthing sync everything including what's not actually web-accessible. Should that work? I may have broke syncthing entirely as I can't get it syncing anything at all any more.

**Comment by pirog** [comment]
Yeah i think there is def a way to do this. I'm on the east coast right now
and it's getting late but let me check it out tomorrow and get back to you!

On Tuesday, July 21, 2015, Nate Haug <notifications@github.com> wrote:

> Ha thanks Mike! [image: :love_hotel:]
>
> For now I'm trying to modify the config/nginx/site.conf to point at
> code/docroot to just make nginx point at the sub directory and have
> syncthing sync everything including what's not actually web-accessible.
> Should that work? I may have broke syncthing entirely as I can't get it
> syncing anything at all any more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/324#issuecomment-123160233>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
so there are a bunch of things that assume the webroot location including syncthing, drush and probably some other plugins. that said we designed it with the idea that you could easily change the codeDir/codeRoot in your config and this would get used for all of that stuff. 

however i think there is a bug that doesnt let you do this right now. slated to be worked on this dev cycle though. being tracked over at #233. Im at GovCamp the next few days but maybe @bcauldwell has a sec to look at it.

**Comment by bcauldwell** [comment]
@quicksketch A fix for ability to change the codeRoot of an app has been made, it's just now waiting a test by one of our developers. Hope to have this fixed for you soon.

**Comment by quicksketch** [comment]
Thanks @bcauldwell. I borked my install yet again and settled for using a MAMP-like solution for the time being, so I'm afraid I won't be able to confirm. Still, it'll be great to have it working the next time I give Kalabox a spin.

**Comment by pirog** [comment]
@bcauldwell Let's leave this open until the @quicksketch or someone else tries this out

**Comment by pirog** [comment]
This should be resolved in the 0.11.0 release on Friday
