### ISSUE TITLE
kbox provision fails from within the node_module directory

### ISSUE THREAD

**Issue by andrewmallis** [kalabox/kalabox#326]
My version of kalabox2 is out of date and I seek to update it on OS 10.10.3
I am recommended to uninstall then re-install
Following the instructions at
https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox
 find myself at

    /usr/local/lib/node_modules/kalabox

once complete.

I then seek to install again, so run

```$ npm install kalabox -g```

which works, then

```$ kbox provision```

which errors out, returning

```
node.js:720
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Error (native)
    at Function.startup.resolveArgv0 (node.js:720:23)
    at startup (node.js:63:13)
    at node.js:814:3
````
```kbox provision``` works fine outside this directory.
if catching this error's rough, suggest updating documentation

**Comment by pirog** [comment]
This is a very helpful ticket with good steps to replicate. @bcauldwell i bet this is not super tough to solve so im going to move it into this sprint.

**Comment by bcauldwell** [comment]
@andrewmallis can you please provide me with the output for the following command?

`ls -l /usr/local/lib/node_modules/`

I was able to recreate on my side, did some research and the suggestion was to do a `sudo chmod 777 /usr/local/lib/node_modules/` which worked for me but isn't a great solution. I'm curious as to the actual permissions on that directory, which I can no longer recreate.

**Comment by andrewmallis** [comment]
@bcauldwell here we go:
```
$ ls -l /usr/local/lib/node_modules/
total 0
drwxr-xr-x   5 myuser  wheel   170 Jul 21 19:25 ./
drwxr-xr-x  66 myuser  wheel  2244 Feb  8 16:30 ../
drwxr-xr-x  13 myuser  staff   442 Jan 26 18:04 grunt-cli/
drwxr-xr-x  25 myuser  wheel   850 Jul 21 19:25 kalabox/
drwxr-xr-x  25 myuser  staff   850 Jul 16 10:30 npm/
```
which by extension means subdirectories of /usr/local/lib/node_modules/kalabox inherit these same directory permissions on subdirectories

777 is an underwhelming option indeed.

**Comment by pirog** [comment]
This is kind of puzzling to me given the permissions posted above. Interested in whether `process.cwd();` requires something special.

**Comment by bcauldwell** [comment]
@pirog I can no longer recreate this issue. Can you test it out and see if the problem still exists on your system?

**Comment by pirog** [comment]
With the binary in play as the preferred install method i am going to close this as something we dont plan to fix
