### ISSUE TITLE
What is ENV.SITEID referring to?

### ISSUE THREAD

**Issue by scottalan** [kalabox/kalabox#329]
I'm trying to rsync files, https://github.com/kalabox/kalabox/wiki/QUICK-Start---TL;DR

What does ENV.SITEID refer to? Is it the "id" listed from `kbox containers`?
```
{
  "id": "SITEID",
  "name": ""
  ...
}
```

Thanks.

**Comment by scottalan** [comment]
I've tried the "id", "name"...no go.

**Comment by labboy0276** [comment]
Hello,

In the TLDR doc it is the environment and ID you are trying to connect to on pantheon.  You can get this from your dashboare on the instance in question you are trying to rsync to.  IE codeserver.dev.bc01dee7-000c@codeserver.dev.000xx

I am mid flight, but if you need more help I can send you more instructions later on.

**Comment by pirog** [comment]
@scottalan the commands in the quickstart are specific to pantheon. Generally you will want to do something like this 

```
kbox rsync -rlvz --size-only --ipv4 -- progress SOURCEMACHINE:LOCATION/ sites/default/files/ # or /files for drupal8 backdrop
```

**Comment by scottalan** [comment]
Normally this wouldn't be an issue but still trying to wrap my head around Docker. What I can't seem to figure out is the ssh credentials. I normally just setup a 'config' file that contains something like:

```
Host kala
  HostName 10.13.37.42
  User kalabox
  Port 2222
  IdentityFile ~/.ssh/id_rsa
```

Then I can just `rsync -rlvzP sites/default/files/* -e ssh kala:/var/www/public/sites/default/files/`, for example.

**Comment by scottalan** [comment]
ok, I figured out how to get into the appserver but still can't figure out how to push anything to it via rsync :disappointed:

**Comment by pirog** [comment]
@scottalan so `boot2docker --vm="Kalabox2" ssh` actually just gets you inside the VM. To see all your containers you need to run `docker ps --all` inside of the VM. From there you can run `docker exec -it CONTAINER_NAME bash` to get inside the container.

We are planning on introducing a drupal site import function soon that we hope will help this issue.
