### ISSUE TITLE
Location of code folder??

### ISSUE THREAD

**Issue by adunk** [kalabox/kalabox#331]
Hey guys,

I've done my best to try and debug this myself, but I'm getting really confused about what kbox is doing when I clone my git repository. FYI, I'm following the [Quick Start guide here](https://github.com/kalabox/kalabox/wiki/QUICK-Start---TL;DR#pantheon-app).

At step 2 I run the following command to clone my site out of Pantheon:
kbox git clone ssh://codeserver.dev.bc01dee7-000c@codeserver.dev.000xx.drush.in:2222/~/repository.git ./

That runs without a hitch, however, the newly created /code directory by all appearances is completely empty. Now the weird thing is that I can still launch the site in my browser and it works fine... Seems like kbox is downloading the repository somewhere on my system and has access to it, but I'm at a loss as to where on my system the code is located.

Thoughts?

Andrew

PS. Some additional info:
- I'm definitely in ~/kalabox/apps/myapp when I'm running these commands.
- Here's a link to my [kbox config results](http://pastebin.com/rpKC0RqT)

**Comment by adunk** [comment]
Adding some additional flavor. If I skip the kbox git clone and just do a standard pull into a code directory I create myself, the site responds with a 403. According to #190 this error arrises when kbox can't find the code. Seems like the kbox git clone is required...?

**Comment by adunk** [comment]
Well, the issue seems to have resolved itself. I did a full reinstall of Kalabox and now everything seems to be working correctly. I'll close this ticket, but maybe this might help someone else down the line.

**Comment by pirog** [comment]
Thanks for all of this feedback @adunk! not sure what happened either but glad we have an issue to track it now.

**Comment by aaronlutze** [comment]
Hi adunk, I have almost the same problem, except my site is giving me a 500 server error. and my code folder is completely empty. I will try a reinstall and see if that fixes it.

Error below:

500 Internal Server Error

nginx
