### ISSUE TITLE
Kalabox Omnibus Training Version

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#332]
After we get an omnibus installer, it would be good to find a way to have ALL dependencies for building kbox and apps included in an omnibus intended for trainings that could be more easily distributed without relying on conference wifi. 

@bcauldwell might have some ideas on how to designate a directory to pull containers from locally.

**Comment by bcauldwell** [comment]
@pirog @reynoldsalec 

I checked the docker remote api, and it is possible to create an image by three methods.

#1 creating from a dockerfile
#2 pulling from a URL
#3 importing from the request body

I think we can use #3 to package images with kalabox on a memory stick.

I would like to have time at some point to test it out to see if the concept is doable. I'll wait for direction and priority before doing any testing.

**Comment by pirog** [comment]
This is great to know. I think we should wait till we are all back to assign a priority to this given that @reynoldsalec's thing is fairly soon. Does that sound good to everyone?

**Comment by bcauldwell** [comment]
Yup let's put this on ice until the reunion.

On Fri, Jul 24, 2015 at 5:35 PM, Mike Pirog <notifications@github.com>
wrote:

> This is great to know. I think we should wait till we are all back to
> assign a priority to this given that @reynoldsalec
> <https://github.com/reynoldsalec>'s thing is fairly soon. Does that sound
> good to everyone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/332#issuecomment-124777879>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
sounds good!

On Fri, Jul 24, 2015 at 8:36 PM, bcauldwell <notifications@github.com>
wrote:

> Yup let's put this on ice until the reunion.
>
> On Fri, Jul 24, 2015 at 5:35 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > This is great to know. I think we should wait till we are all back to
> > assign a priority to this given that @reynoldsalec
> > <https://github.com/reynoldsalec>'s thing is fairly soon. Does that
> sound
> > good to everyone?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/332#issuecomment-124777879>.
> >
>
>
>
> --
> - Benjamin Cauldwell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/332#issuecomment-124778250>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
this should become trivial once we have #385 done
