### ISSUE TITLE
Browser testing with Kalabox on Mac

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#334]
Hi Guys,

Just wondering if it's possible to access Kalabox sites from another VM.

For example I'm using an IE9 image from modern.ie – virtualbox on Mac Yosemite.

Cheers,
Tim

**Comment by pirog** [comment]
I *think* this is possible depending on your use case. Are both machines on your local network? can you describe the topology a bit?

**Comment by pi-ron** [comment]
They're both on my Mac.  I used to fire up an IE Vm to test sites running on mamp.

**Comment by pirog** [comment]
I think the best bet here is to probably use a service like browserstack.com. 

To do this locally you need to make sure VM1 and VM2 are on the same network ie they can communicate with one another. Then on the non-kb VM you will want to add a DNS entry for *.kbox domains by adding this entry 

`nameserver IP_ADDRESS_OF_KALABOX_FROM_OTHER_VM`

To a file at `/etc/resolver/kbox`

**Comment by pi-ron** [comment]
How would I find IP_ADDRESS_OF_KALABOX_FROM_OTHER_VM ?

>   --

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.

**Comment by pirog** [comment]
@pi-ron good question ... it really depends on how your other VM is set up and how it is networked to KB2. Can you provide more details on this?

**Comment by pi-ron** [comment]
@pirog

Within virtualbox:
- I've added a a 3rd network adapter to the kalabox VM: Internal network named vmtovm
- I've added the same network adapter to my Windows/IE VM: Internal network, vmtovm

I followed this guide: http://www.virtualbox.org/manual/ch06.html#network_internal

Tried to also add dhcp server http://www.virtualbox.org/manual/ch08.html#vboxmanage-dhcpserver

Basically I've got NFI what I'm doing...

**Comment by pi-ron** [comment]
Ok, believe I've found the IP of kalabox by running `VBoxManage guestproperty enumerate "Kalabox2"` which gives you a whole bunch of virtualbox config, then search for:

`Name: /VirtualBox/GuestInfo/Net/1/V4/IP, value:`

**Comment by pi-ron** [comment]
Can ping it.

**Comment by pi-ron** [comment]
No sorry, that last one was wrong, doesn't seem to output the IP for Kalabox2 VM, only Windows VM.

**Comment by pi-ron** [comment]
Ok, I've tried adding network adapters to each VM (kalabox & Windows) using bridged & internal network methods, no real luck with finding Kalabox IP though.

I've added additional network adapter to kalabox2 vm:  bridged, network name: bridge0
Added network adapter to Windows vm:  bridged, network name: bridge0

**Comment by pi-ron** [comment]
If I ping a site from my mac, would the IP returned be the IP to use in my VM's hosts file?

**Comment by pi-ron** [comment]
JOY

**Comment by pi-ron** [comment]
Okkkkkk... I went about this the entirely long, hard and wrong way.

All you have to do is modify the hosts file :100: 

1. Ping your appname.kbox from your Mac terminal, note the IP

2. For the Win7 IE9 VirtualBox available from modern.ie, go to Windows > system32 > drivers > etc > hosts

3. Right click and modify that files permissions to allow editing by users (or run command prompt as administrator and do the following via terminal).

4. Open it up and add  `IP appname.kbox`

5. Save it.

All good!

**Comment by pirog** [comment]
DAMNNNN @pi-ron 

Any chance you'd want to create a wiki article for this? :) 

Of course using something like browserstack.com might be easier for most as well :)

**Comment by pi-ron** [comment]
@pirog yeh no worries, what's the process there?

I find it a lot easier testing with a local vm because I'm constantly recompiling sass, but I haven't tried browser stack local (I think that's a thing?)

**Comment by pirog** [comment]
@pi-ron 
AFAIK the wiki is open so you can just go to https://github.com/kalabox/kalabox/wiki
and create a new page

I am *pretty* sure on using browser stack with a local site but its been awhile since i tried.

**Comment by pi-ron** [comment]
:+1:   https://github.com/kalabox/kalabox/wiki/VM-Based-Local-Browser-Testing-(Windows-7-IE9)

**Comment by pirog** [comment]
Oh very nice!!!

Loving that Bon Jovi video :)
