### ISSUE TITLE
kbox 0.9.4 Cannot access drush

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#338]
Dons-MacBook-Pro:code donkoller3$ __kbox drush__
HTTP code is 404 which indicates error: no such container - No such image: kalabox/drush:v0.9.0 (tag: v0.9.0)

**Comment by bcauldwell** [comment]
Can you try doing a 'kbox down && kbox up'? This sounds like the VM might
have lost internet connection, and restarting kbox should reset that. I
have confirmed that kalabox/drush:v0.9.0 does indeed exist on the docker
hug registry.

On Fri, Jul 24, 2015 at 1:52 PM, Don Koller <notifications@github.com>
wrote:

> Dons-MacBook-Pro:code donkoller3$ *kbox drush*
> HTTP code is 404 which indicates error: no such container - No such image:
> kalabox/drush:v0.9.0 (tag: v0.9.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
After kbox down && kbox up, same 404 error.

kalabox.json
```
{
  "appName": "myslxlocal",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "shareIgnores": [
    ".git"
  ],
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "6"
    },
    "kalabox-plugin-php": {
      "php-version": "5.5.24"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "donkoller",
      "git-email": "dkoller@eafoundation.com"
    }
  },
  "appComponents": {
    "appserver": {
      "image": {
        "name": "php-appserver",
        "srcRoot": ":appRoot:"
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ]
    },
    "db": {
      "image": {
        "name": "mariadb",
        "srcRoot": ":appRoot:"
      }
    }
  }
}
```

**Comment by donkoller** [comment]
```
Dons-MacBook-Pro:code donkoller3$ kbox config
{
  "appCidsRoot": "/Users/donkoller3/Sites/myslxlocal/.cids",
  "appComponents": [
    {
      "image": {
        "name": "php-appserver",
        "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
      },
      "proxy": [
        {
          "port": "80/tcp",
          "default": true
        }
      ],
      "name": "appserver",
      "hostname": "appserver.myslxlocal.kbox",
      "appDomain": "myslxlocal.kbox",
      "url": "http://appserver.myslxlocal.kbox",
      "dataContainerName": "kb_myslxlocal_data",
      "containerName": "kb_myslxlocal_appserver",
      "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/appserver",
      "containerId": "f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7"
    },
    {
      "image": {
        "name": "mariadb",
        "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
      },
      "name": "db",
      "hostname": "db.myslxlocal.kbox",
      "appDomain": "myslxlocal.kbox",
      "url": "http://db.myslxlocal.kbox",
      "dataContainerName": "kb_myslxlocal_data",
      "containerName": "kb_myslxlocal_db",
      "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/db",
      "containerId": "9144107ab8eeda6ae8e403186c06fcdc5280f95ac98a0ff6d918189b038cb158"
    }
  ],
  "appName": "myslxlocal",
  "appPlugins": [
    "kalabox-plugin-dbenv",
    "kalabox-plugin-drush",
    "kalabox-plugin-git",
    "kalabox-plugin-php",
    "kalabox-plugin-rsync"
  ],
  "appRegistry": "/Users/donkoller3/.kalabox/appRegistry.json",
  "appRoot": "/Users/donkoller3/Sites/myslxlocal",
  "apps": [
    "kalabox-app-backdrop@^0.9.0",
    "kalabox-app-drupal@^0.9.0",
    "kalabox-app-pantheon@^0.9.0"
  ],
  "appsRoot": "/Users/donkoller3/kalabox/apps",
  "codeDir": "code",
  "configSources": [
    "DEFAULT_GLOBAL_CONFIG",
    "ENV_CONFIG"
  ],
  "domain": "kbox",
  "downloadsRoot": "/Users/donkoller3/.kalabox/downloads",
  "engine": "kalabox-engine-docker@^0.9.0",
  "engineRepo": "kalabox",
  "globalPluginRoot": "/Users/donkoller3/kalabox/plugins",
  "globalPlugins": [
    "kalabox-core",
    "kalabox-syncthing",
    "kalabox-app-drupal",
    "kalabox-app-backdrop",
    "kalabox-app-pantheon"
  ],
  "home": "/Users/donkoller3",
  "kalaboxRoot": "/Users/donkoller3/kalabox",
  "kboxRoot": "/Users/donkoller3/kalabox",
  "logLevel": "debug",
  "logLevelConsole": "info",
  "logRoot": "/Users/donkoller3/.kalabox/logs",
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "release": "14.4.0",
    "arch": "x64"
  },
  "pluginConf": {
    "kalabox-plugin-drush": {
      "drush-version": "6"
    },
    "kalabox-plugin-php": {
      "php-version": "5.5.24"
    },
    "kalabox-plugin-dbenv": {
      "settings": {
        "conf": {
          "pressflow_smart_start": 1
        }
      }
    },
    "kalabox-plugin-git": {
      "git-username": "donkoller",
      "git-email": "dkoller@eafoundation.com"
    }
  },
  "profile": "standard",
  "provisioned": true,
  "services": "kalabox-services-kalabox@^0.9.0",
  "shareIgnores": [
    "*.7z",
    "*.bz2",
    "*.dmg",
    "*.gz",
    "*.iso",
    "*.jar",
    "*.rar",
    "*.tar",
    "*.tgz",
    "*.un~",
    "*.zip",
    ".*.swp",
    ".*DS_Store",
    ".DS_Store*",
    "._*",
    ".git",
    ".sass-cache",
    "Icon",
    "Thumbs.db",
    "ehthumbs.db"
  ],
  "sharing": true,
  "srcRoot": "/usr/local/lib/node_modules/kalabox",
  "stats": {
    "report": true,
    "url": "http://stats.kalabox.biz"
  },
  "sysConfRoot": "/Users/donkoller3/.kalabox",
  "sysProviderRoot": "/Users/donkoller3/.kalabox/.provider",
  "version": "0.9.4",
  "homeBind": "/Users/donkoller3",
  "codeRoot": "/Users/donkoller3/Sites/myslxlocal/code"
}
```

**Comment by bcauldwell** [comment]
What was the command that gave you the original error?

On Fri, Jul 24, 2015 at 1:59 PM, Don Koller <notifications@github.com>
wrote:

> Dons-MacBook-Pro:code donkoller3$ kbox config
> {
>   "appCidsRoot": "/Users/donkoller3/Sites/myslxlocal/.cids",
>   "appComponents": [
>     {
>       "image": {
>         "name": "php-appserver",
>         "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
>       },
>       "proxy": [
>         {
>           "port": "80/tcp",
>           "default": true
>         }
>       ],
>       "name": "appserver",
>       "hostname": "appserver.myslxlocal.kbox",
>       "appDomain": "myslxlocal.kbox",
>       "url": "http://appserver.myslxlocal.kbox",
>       "dataContainerName": "kb_myslxlocal_data",
>       "containerName": "kb_myslxlocal_appserver",
>       "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/appserver",
>       "containerId": "f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7"
>     },
>     {
>       "image": {
>         "name": "mariadb",
>         "srcRoot": "/Users/donkoller3/Sites/myslxlocal"
>       },
>       "name": "db",
>       "hostname": "db.myslxlocal.kbox",
>       "appDomain": "myslxlocal.kbox",
>       "url": "http://db.myslxlocal.kbox",
>       "dataContainerName": "kb_myslxlocal_data",
>       "containerName": "kb_myslxlocal_db",
>       "containerIdFile": "/Users/donkoller3/Sites/myslxlocal/.cids/db",
>       "containerId": "9144107ab8eeda6ae8e403186c06fcdc5280f95ac98a0ff6d918189b038cb158"
>     }
>   ],
>   "appName": "myslxlocal",
>   "appPlugins": [
>     "kalabox-plugin-dbenv",
>     "kalabox-plugin-drush",
>     "kalabox-plugin-git",
>     "kalabox-plugin-php",
>     "kalabox-plugin-rsync"
>   ],
>   "appRegistry": "/Users/donkoller3/.kalabox/appRegistry.json",
>   "appRoot": "/Users/donkoller3/Sites/myslxlocal",
>   "apps": [
>     "kalabox-app-backdrop@^0.9.0",
>     "kalabox-app-drupal@^0.9.0",
>     "kalabox-app-pantheon@^0.9.0"
>   ],
>   "appsRoot": "/Users/donkoller3/kalabox/apps",
>   "codeDir": "code",
>   "configSources": [
>     "DEFAULT_GLOBAL_CONFIG",
>     "ENV_CONFIG"
>   ],
>   "domain": "kbox",
>   "downloadsRoot": "/Users/donkoller3/.kalabox/downloads",
>   "engine": "kalabox-engine-docker@^0.9.0",
>   "engineRepo": "kalabox",
>   "globalPluginRoot": "/Users/donkoller3/kalabox/plugins",
>   "globalPlugins": [
>     "kalabox-core",
>     "kalabox-syncthing",
>     "kalabox-app-drupal",
>     "kalabox-app-backdrop",
>     "kalabox-app-pantheon"
>   ],
>   "home": "/Users/donkoller3",
>   "kalaboxRoot": "/Users/donkoller3/kalabox",
>   "kboxRoot": "/Users/donkoller3/kalabox",
>   "logLevel": "debug",
>   "logLevelConsole": "info",
>   "logRoot": "/Users/donkoller3/.kalabox/logs",
>   "os": {
>     "type": "Darwin",
>     "platform": "darwin",
>     "release": "14.4.0",
>     "arch": "x64"
>   },
>   "pluginConf": {
>     "kalabox-plugin-drush": {
>       "drush-version": "6"
>     },
>     "kalabox-plugin-php": {
>       "php-version": "5.5.24"
>     },
>     "kalabox-plugin-dbenv": {
>       "settings": {
>         "conf": {
>           "pressflow_smart_start": 1
>         }
>       }
>     },
>     "kalabox-plugin-git": {
>       "git-username": "donkoller",
>       "git-email": "dkoller@eafoundation.com"
>     }
>   },
>   "profile": "standard",
>   "provisioned": true,
>   "services": "kalabox-services-kalabox@^0.9.0",
>   "shareIgnores": [
>     "*.7z",
>     "*.bz2",
>     "*.dmg",
>     "*.gz",
>     "*.iso",
>     "*.jar",
>     "*.rar",
>     "*.tar",
>     "*.tgz",
>     "*.un~",
>     "*.zip",
>     ".*.swp",
>     ".*DS_Store",
>     ".DS_Store*",
>     "._*",
>     ".git",
>     ".sass-cache",
>     "Icon",
>     "Thumbs.db",
>     "ehthumbs.db"
>   ],
>   "sharing": true,
>   "srcRoot": "/usr/local/lib/node_modules/kalabox",
>   "stats": {
>     "report": true,
>     "url": "http://stats.kalabox.biz"
>   },
>   "sysConfRoot": "/Users/donkoller3/.kalabox",
>   "sysProviderRoot": "/Users/donkoller3/.kalabox/.provider",
>   "version": "0.9.4",
>   "homeBind": "/Users/donkoller3",
>   "codeRoot": "/Users/donkoller3/Sites/myslxlocal/code"
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124721661>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
kbox containers showed app/db not running. Did kbox start.
Now app/db containers running. Same 404 result.

Original command:
kbox drush up

**Comment by donkoller** [comment]
Anything else I can provide?
Since installing 0.9.4 yesterday, I don't think I have run drush, so this could have been there all the time in my 0.9.4 npm install.

**Comment by bcauldwell** [comment]
Ok let's try doing a `npm install` in your app's directory, then do a `kbox
uninstall && kbox install`. Let me know if that helps.

On Fri, Jul 24, 2015 at 2:09 PM, Don Koller <notifications@github.com>
wrote:

> Anything else I can provide?
> Since installing 0.9.4 yesterday, I don't think I have run drush, so this
> could have been there all the time in my 0.9.4 npm install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124724927>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
npm install -g
Correct?

**Comment by bcauldwell** [comment]
No just `npm install` but inside of your app's directory. You just want to
install the node modules local to that directory.

On Fri, Jul 24, 2015 at 2:16 PM, Don Koller <notifications@github.com>
wrote:

> npm install -g
> Correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124727041>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
```
Dons-MacBook-Pro:myslxlocal donkoller3$ npm install
npm WARN package.json myslxlocal@ No description
npm WARN package.json myslxlocal@ No repository field.
npm WARN package.json myslxlocal@ No README data
```

**Comment by bcauldwell** [comment]
That's just a warning and so should be ignored.

On Fri, Jul 24, 2015 at 2:18 PM, Don Koller <notifications@github.com>
wrote:

> Dons-MacBook-Pro:myslxlocal donkoller3$ npm install
> npm WARN package.json myslxlocal@ No description
> npm WARN package.json myslxlocal@ No repository field.
> npm WARN package.json myslxlocal@ No README data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124727641>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
```
Dons-MacBook-Pro:myslxlocal donkoller3$ kbox uninstall
info: DOCKER =>  Removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7. v=true, kill=false
info: DOCKER =>  Stopping container. f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7
Error removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7.: Cannot read property 'stop' of undefined
```

**Comment by bcauldwell** [comment]
Looks like the app might be in a bad state, try doing `kbox install` and
see if that fixes your problem.

On Fri, Jul 24, 2015 at 2:20 PM, Don Koller <notifications@github.com>
wrote:

> Dons-MacBook-Pro:myslxlocal donkoller3$ kbox uninstall
> info: DOCKER =>  Removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7. v=true, kill=false
> info: DOCKER =>  Stopping container. f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7
> Error removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7.: Cannot read property 'stop' of undefined
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124728284>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
```
Dons-MacBook-Pro:myslxlocal donkoller3$ kbox uninstall
info: DOCKER =>  Removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7. v=true, kill=false
info: DOCKER =>  Stopping container. f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7
Error removing container f65a343c97ef9dc3d9afb22168fdea53c28e934759fd70be5edcb930b0439ce7.: Cannot read property 'stop' of undefined
Dons-MacBook-Pro:myslxlocal donkoller3$ kbox install
info: SERVICES =>  Startup services need to be started.
info: DOCKER =>  Stopping container. f99db234b54addd7470055ec6ee960c74dcf0a8ceffc7d1410e7efb31d4c3d5e
info: DOCKER =>  Container stopped. f99db234b54addd7470055ec6ee960c74dcf0a8ceffc7d1410e7efb31d4c3d5e
info: DOCKER =>  Stopping container. 924b9723da6f2e2ad4ab4385f6bffaaf5c86ab5d8d58d3479c86b0c14f4a4663
info: DOCKER =>  Container already stopped. 924b9723da6f2e2ad4ab4385f6bffaaf5c86ab5d8d58d3479c86b0c14f4a4663
info: DOCKER =>  Stopping container. 3cad14e4580b59d8b80f80d9ec92bd57ff74d0d2136bd845ec5657152c748640
info: DOCKER =>  Container stopped. 3cad14e4580b59d8b80f80d9ec92bd57ff74d0d2136bd845ec5657152c748640
info: DOCKER =>  Stopping container. d6146c13b105cae8aeca72c3a7d1bb9f403922d6402cc25ca98b4e5c6f0e9677
info: DOCKER =>  Container stopped. d6146c13b105cae8aeca72c3a7d1bb9f403922d6402cc25ca98b4e5c6f0e9677
info: DOCKER =>  Stopping container. 8a0c5136ad4eb19533714b137760a48ad9d9eef0c7950899ed47b7097216ea14
info: DOCKER =>  Container stopped. 8a0c5136ad4eb19533714b137760a48ad9d9eef0c7950899ed47b7097216ea14
info: DOCKER =>  Starting container f99db234b54addd7470055ec6ee960c74dcf0a8ceffc7d1410e7efb31d4c3d5e.
info: DOCKER =>  Container started. f99db234b54addd7470055ec6ee960c74dcf0a8ceffc7d1410e7efb31d4c3d5e
info: DOCKER =>  Starting container 924b9723da6f2e2ad4ab4385f6bffaaf5c86ab5d8d58d3479c86b0c14f4a4663.
info: DOCKER =>  Container started. 924b9723da6f2e2ad4ab4385f6bffaaf5c86ab5d8d58d3479c86b0c14f4a4663
info: DOCKER =>  Starting container 3cad14e4580b59d8b80f80d9ec92bd57ff74d0d2136bd845ec5657152c748640.
info: DOCKER =>  Container started. 3cad14e4580b59d8b80f80d9ec92bd57ff74d0d2136bd845ec5657152c748640
info: DOCKER =>  Starting container d6146c13b105cae8aeca72c3a7d1bb9f403922d6402cc25ca98b4e5c6f0e9677.
info: DOCKER =>  Container started. d6146c13b105cae8aeca72c3a7d1bb9f403922d6402cc25ca98b4e5c6f0e9677
info: DOCKER =>  Starting container 8a0c5136ad4eb19533714b137760a48ad9d9eef0c7950899ed47b7097216ea14.
info: DOCKER =>  Container started. 8a0c5136ad4eb19533714b137760a48ad9d9eef0c7950899ed47b7097216ea14
Error while installing app: "myslxlocal": Container already exists: 9144107ab8eeda6ae8e403186c06fcdc5280f95ac98a0ff6d918189b038cb158
```

**Comment by donkoller** [comment]
Should I try to manually delete that container and then try install again?
What do you suggest?

**Comment by bcauldwell** [comment]
Yes manually delete that container and install again please.

On Fri, Jul 24, 2015 at 2:24 PM, Don Koller <notifications@github.com>
wrote:

> Should I try to manually delete that container and then try install again?
> What do you suggest?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124729371>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
From Docker, removed the container. Then did kbox install. This time it ran.
Did a lot of downloading.
Did kbox start.
Error message at end:   Cannot read property '3306/tcp' of null
Per kbox containers:  app is running but db is not.

Looking back at my terminal listing, I see that I by mistake deleted the married container! Yikes.
Deleted the bad container. kbox install.
I am going to load the db again and see if it will start.

**Comment by donkoller** [comment]
Ben, what's the right procedure here?

**Comment by bcauldwell** [comment]
I think you want to be able to do a successful `kbox uninstall` of the app,
then a successful `kbox install` while deleting containers manually if you
have to, to get `kbox uninstall` to complete successfully.

On Fri, Jul 24, 2015 at 2:46 PM, Don Koller <notifications@github.com>
wrote:

> Ben, what's the right procedure here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124736030>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
OK The kbox uninstall worked and removed those containers. Then kbox install ran with no errors.
Next ran kbox start.
Stopped with error
```
info: DOCKER =>  Ad hoc container created. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
info: DOCKER =>  Starting ad hoc container "8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b". Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
info: DOCKER =>  Ad hoc container started. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
info: DOCKER =>  Removing ad hoc container. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
info: DOCKER =>  Starting container b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
info: DOCKER =>  Container started. b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d
info: DOCKER =>  Starting container 824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
info: DOCKER =>  Container started. 824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d
Cannot read property '3306/tcp' of null
```
Database server (container) not running
```
Cannot read property '3306/tcp' of null
Dons-MacBook-Pro:myslxlocal donkoller3$ kbox containers
{
  "id": "b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d",
  "name": "kb_myslxlocal_appserver",
  "app": "myslxlocal",
  "ports": [
    "443/tcp=>32774",
    "80/tcp=>32775"
  ],
  "running": true
}
{
  "id": "824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d",
  "name": "kb_myslxlocal_db",
  "app": "myslxlocal",
  "ports": [],
  "running": false
}
```

**Comment by donkoller** [comment]
Stopping work on this for the evening... Tomorrow.

**Comment by bcauldwell** [comment]
I've seen this before when there is an error stopping a container from
starting.

On Fri, Jul 24, 2015 at 3:01 PM, Don Koller <notifications@github.com>
wrote:

> OK The kbox uninstall worked and removed those containers. Then kbox
> install ran with no errors.
> Next ran kbox start.
> Stopped with error
>
> info: DOCKER =>  Ad hoc container created. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
> info: DOCKER =>  Starting ad hoc container "8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b". Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
> info: DOCKER =>  Ad hoc container started. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
> info: DOCKER =>  Removing ad hoc container. 8cf339d69e6dd29025adadb772876761d347212c4925f5a6117f3676a247ac8b
> info: DOCKER =>  Starting container b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
> info: DOCKER =>  Container started. b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d
> info: DOCKER =>  Starting container 824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d. PublishAllPorts=true, Binds=[/Users/donkoller3/Sites/myslxlocal:/src:rw]
> info: DOCKER =>  Container started. 824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d
> Cannot read property '3306/tcp' of null
>
> Database server (container) not running
>
> Cannot read property '3306/tcp' of null
> Dons-MacBook-Pro:myslxlocal donkoller3$ kbox containers
> {
>   "id": "b085897837c647d9edcb1b6eaf370535db55a11d34158d72050191b2b616271d",
>   "name": "kb_myslxlocal_appserver",
>   "app": "myslxlocal",
>   "ports": [
>     "443/tcp=>32774",
>     "80/tcp=>32775"
>   ],
>   "running": true
> }
> {
>   "id": "824cacf358787b37bab81b443937c4ac71cecb74b301f00124929bb58be1720d",
>   "name": "kb_myslxlocal_db",
>   "app": "myslxlocal",
>   "ports": [],
>   "running": false
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124740159>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
I think one of your containers failed on start.

On Fri, Jul 24, 2015 at 3:02 PM, Don Koller <notifications@github.com>
wrote:

> Stopping work on this for the evening... Tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124740372>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell can you verify that a drupal app works as expected?

**Comment by donkoller** [comment]
Yes, the db container did not start. Not sure what to try next.

**Comment by bcauldwell** [comment]
boot2docker --vm=Kalabox2 ssh <--- this will get you into the docker
instance
docker logs <container name> <--- this will get you a print out of the logs
for that container

On Sat, Jul 25, 2015 at 7:11 AM, Don Koller <notifications@github.com>
wrote:

> Yes, the db container did not start. Not sure what to try next.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/338#issuecomment-124849433>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
When i get some better wifi ill test out the drush app. maybe we had some regressions? @labboy0276 have you seen any of these issues at all?

**Comment by labboy0276** [comment]
Negative @pirog 

I would try purging the system of kb2 + ~/.kalabox folder and see if you still get these odd issues @donkoller

**Comment by donkoller** [comment]
Following labboy's suggestion: totally purged all of kalabox from my Mac, deleted the kalabox VM from virtualBox, etc.
Reinstalled and recreated the app code/database/files and made a new settings.php for kalabox DB connection.
Site is running. Mainly, the DB is running OK.
Not sure where the problem arose, but local site now works.

Still interested in all things drush.

**Comment by donkoller** [comment]
Today, I was able to run the app with no problems. 
kbox drush commands working fine.
Note that in creating the app, it took syncthing a while to get all the files to the container since I've enabled syncing of sites/default/files.

**Comment by pirog** [comment]
@donkoller this is one of the reasons why we ignore s/d/f by default. Can take a long time to sync and for larger payloads can actually fail, although this last point may be resolved in newer version of syncthing.
