### ISSUE TITLE
Error on kbox start after update

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#341]
I got the error below at the end of kbox start output after updating to latest kbox:

```````
npm install kalabox -g
kbox provision
``````
Changed vesions in package.json
``````
cd /app/dir

kbox update

``````

``````
kbox start


...yada yada...

Cannot read property '3306/tcp' of null
TypeError: Cannot read property '3306/tcp' of null
    at /Users/timdaff/Sites/parcel-upstream/node_modules/kalabox-plugin-drush/index.js:49:49
From previous event:
    at /Users/timdaff/Sites/parcel-upstream/node_modules/kalabox-plugin-drush/index.js:47:10
    at /Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:131:9
    at /Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:128:20
From previous event:
    at EventEngine._dispatch (/Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:126:18)
    at /Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:106:19
From previous event:
    at EventEngine.emit (/Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:98:21)
From previous event:
    at Object.exports.emit (/Users/timdaff/.node/lib/node_modules/kalabox/lib/core/events.js:196:4)
    at /Users/timdaff/.node/lib/node_modules/kalabox/lib/app.js:472:24
From previous event:
    at startComponent (/Users/timdaff/.node/lib/node_modules/kalabox/lib/app.js:471:4)
    at services.verify.then.then.then.map.concurrency (/Users/timdaff/.node/lib/node_modules/kalabox/lib/app.js:514:12)
From previous event:
    at Object.exports.start (/Users/timdaff/.node/lib/node_modules/kalabox/lib/app.js:513:4)
    at Object.task.func (/Users/timdaff/.node/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
    at Object.exports.run (/Users/timdaff/.node/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/Users/timdaff/.node/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /Users/timdaff/.node/lib/node_modules/kalabox/bin/kbox.js:330:19
    at processImmediate [as _immediateCallback] (timers.js:358:17)

``````

**Comment by pi-ron** [comment]
I didn't have any data in the app I needed, but needed the namespace, so did `kbox uninstall` then manually removed the kb_name_data container that was leftover.

**Comment by bcauldwell** [comment]
When you experience the error you reported, do a `kbox containers` to see
the status of the containers in your app. My guess is that one of the
containers has failed starting up and that is causing your problem.

If you find that one of the containers has failed to start you can check
the containers logs with the following commands.
`boot2docker --vm=Kalabox2 ssh`
`docker logs <container name>`

The logs should give you an idea of why the container failed to start.

On Sat, Jul 25, 2015 at 10:59 PM, pi-ron <notifications@github.com> wrote:

> I didn't have any data in the app I needed, but needed the namespace, so
> did kbox uninstall then manually removed the kb_name_data container that
> was leftover.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/341#issuecomment-124949432>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell this might be related to the issue @donkoller was reporting on how the DB container for the drupal app was failing since this part of the drush plugin run on the DB container.

**Comment by bcauldwell** [comment]
@pirog Yosef also had a similar issue today.

@pi-ron if you can do the above commands and send me the log output of what is causing the DB container to fail, then I can confirm this and figure out a quick work around to get you running.

**Comment by pi-ron** [comment]
@bcauldwell @pirog Apologies for the lack of communication guys, this was on my home computer and have not had a chance to get back to it yet.

**Comment by donkoller** [comment]
Yes, @pirog sounds like the same as I was experiencing. I totally re-installed kalabox, and now it's running fine. I'll post if any problems arise.

**Comment by pi-ron** [comment]
I'm still running 0.8.x at work, just to be safe.

**Comment by pirog** [comment]
@bcauldwell here are teh changes to maria from 0.8.0 - 0.9.0 
https://github.com/kalabox/kalabox-dockerfiles/commit/6067e4515c5d2ca848e5b7c66c37b4f6e05b5ad2

Can you post the log errors you were getting?

**Comment by pi-ron** [comment]
Sorry guys, I've lost the pathway to this error... only have a few apps setup at home and can't reproduce this.

**Comment by bcauldwell** [comment]
Duplicate issue, moving everything over to #345.
