### ISSUE TITLE
Unable to Provision Kalabox because of Boot2Docker Authentication

### ISSUE THREAD

**Issue by bthompson-mindgrub** [kalabox/kalabox#342]
I'm trying to install Kalabox on a Windows 7 computer.  Every time I try and install, I get stuck with the installer asking me for a password to the boot2docker VM OR the password to the key file.

Steps:
1.  Install Kalabox via npm (npm install kalabox -g)
2.  Run `kbox provision`
3.  Press enter at the prompt to install (which accepts the default, Yes)
4.  Give Boot2Docker permission to complete administrative tasks when prompted by Window's UAC.
5.  Observe prompt for SSH Key password and user account password.

Kalabox Version:   0.9.7
VirtualBox Version:  4.3.30
npm version:  2.11.3
Node version:  0.12.7

![kalabox install password prompt](https://cloud.githubusercontent.com/assets/1789427/8913389/d96cfd80-3466-11e5-9213-bbe7f2b7b0ed.PNG)

**Comment by pirog** [comment]
@bthompson-mindgrub had you installed a previous version of Boot2Docker? or an SSH client like Putty?

**Comment by bthompson-mindgrub** [comment]
@pirog No previous version of Boot2Docker installed but I do have Putty installed.  I had perused the boot2docker issue queue but none of the tips there (such as boot2docker/boot2docker#405 helped).

**Comment by pirog** [comment]
@bcauldwell i have a suspicion that putty might be doing something here. Might be worth testing out a provision on Windows with putty installed. For this test you will want to make sure you remove the b2d keys as well during uninstall.

**Comment by pirog** [comment]
@bthompson-mindgrub did you see the part here https://docs.docker.com/installation/windows/ about converting the private key into the format that putty uses? Have you tried that?

@bcauldwell i think we can get around this by forcing the usage of the ssh.exe that ships with boot2docker vs the default (in this case putty).

**Comment by bthompson-mindgrub** [comment]
I agree that putty might be the culprit here.  I had previously installed Kalabox on a different computer without Putty and did not encounter this issue.

**Comment by bcauldwell** [comment]
I'm in the office today, but the test machine is not here right now. I'll
ask Andrew to bring the test machine in, but I won't be able to test then
until I get back from NY.

On Tue, Jul 28, 2015 at 7:34 AM, Mike Pirog <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell> i have a suspicion that putty
> might be doing something here. Might be worth testing out a provision on
> Windows with putty installed. For this test you will want to make sure you
> remove the b2d keys as well during uninstall.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/342#issuecomment-125628764>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell that's fair enough. Maybe @reynoldsalec could give it a go when he gets back just to confirm the issue arises when Putty is in place. We should def account for this since putty is a pretty normal thing for windows people.

**Comment by pirog** [comment]
@reynoldsalec if you could try this out on the test machine and do some research before i get back that would be great. If not i can give it a look when i get back. If you can't just assign it back to me.

**Comment by bthompson-mindgrub** [comment]
I worked around the problem by modifying my PATH variable to put C:\Program Files (x86)\Git\bin first in the list.  I'm guessing (untested) that modifying line 145 in kalabox-engine-docker\provider\b2d.js to put the Git\bin directory first instead of the existing format of current path + Git\bin will solve this particular problem.

**Comment by pirog** [comment]
Yes! I think this is spot on! Would accept PR on this if you are so willing.

**Comment by pirog** [comment]
I think this is needed for https://github.com/kalabox/kalabox-plugin-drush/issues/7 to be possible on windows

**Comment by pirog** [comment]
i've merged the fix for this into both 0.10.x and 0.9.x so it should be available in the next release(s).
https://github.com/kalabox/kalabox-engine-docker/commit/2b8abe336f8ccc769d1b67db6776708293d55f82
