### ISSUE TITLE
Kbox not responding, timing out...

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#343]
Ran kbox up and left it going for a while and stopped it after 10 minutes. 
Ran kbox status which seemed to show that kbox is up
but all kbox commands gave me errors.
See below.

![kbox](https://cloud.githubusercontent.com/assets/10218159/8914839/4ec1ee62-3456-11e5-9c61-fccdf4bcdf89.png)

**Comment by bcauldwell** [comment]
@yosefromano I have not seen this before but looks like the VM might have had some trouble starting up. Can you try doing a `kbox down` and if that works do a `kbox up` to see if that fixes it?

If that doesn't work can you open VirtualBox and tell me if anything with the Kalabox2 image looks odd or has any error messages?

**Comment by yosefromano** [comment]
kbox down runs for a while and I get this error 
Error while shutting down.: EVENTS =>  Error dispatching event listeners [pre-down].
kbox status shows 'up'

**Comment by bcauldwell** [comment]
Ok I suspect there is something fishy going on with the VM, can you open
VirtualBox and see if there are any errors for the Kalabox2 image?

On Mon, Jul 27, 2015 at 12:15 PM, yosefromano <notifications@github.com>
wrote:

> kbox down runs for a while and I get this error
> Error while shutting down.: EVENTS => Error dispatching event listeners
> [pre-down].
> kbox status shows 'up'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125311555>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
No obvious errors. Everything seems normal.

**Comment by bcauldwell** [comment]
Ok can you try restarting your computer, then running `kbox up -- -v` to
get the verbose output and then post the results here?

On Mon, Jul 27, 2015 at 3:35 PM, yosefromano <notifications@github.com>
wrote:

> No obvious errors. Everything seems normal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125367641>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
It's been running for 10 minutes. Stuck here: 

Last login: Mon Jul 27 15:38:33 on console
yosefs-mbp:~ yosefromano$ kbox up -- -v
debug: ENGINE =>  Initializing engine.
debug: ENGINE =>  Engine initialized.
debug: DISCO => AppsRegistry dirs. 0=fcbeta, 1=civiplay
debug: CONFIG => App config loaded. appCidsRoot=/Users/yosefromano/Sites/fcbeta/.cids, name=pantheon-appserver, srcRoot=/Users/yosefromano/Sites/fcbeta, proxy=[port=80/tcp, default=true, port=443/tcp, default=true, secure=true], name=pantheon-mariadb, srcRoot=/Users/yosefromano/Sites/fcbeta, name=pantheon-solr, srcRoot=/Users/yosefromano/Sites/fcbeta, name=pantheon-redis, srcRoot=/Users/yosefromano/Sites/fcbeta, appName=fcbeta, appPlugins=[kalabox-plugin-git, kalabox-plugin-rsync, kalabox-plugin-pantheon], appRegistry=/Users/yosefromano/.kalabox/appRegistry.json, appRoot=/Users/yosefromano/Sites/fcbeta, apps=[kalabox-app-backdrop@^0.9.0, kalabox-app-drupal@^0.9.0, kalabox-app-pantheon@^0.9.0], appsRoot=/Users/yosefromano/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/Users/yosefromano/.kalabox/downloads, engine=kalabox-engine-docker@^0.9.0, engineRepo=kalabox, globalPluginRoot=/Users/yosefromano/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop, kalabox-app-pantheon], home=/Users/yosefromano, kalaboxRoot=/Users/yosefromano/kalabox, kboxRoot=/Users/yosefromano/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/Users/yosefromano/.kalabox/logs, type=Darwin, platform=darwin, release=13.4.0, arch=x64, action=pull, drush-version=6, env=dev, framework=drupal, php=5.3.29, site=fcbeta2, url=https://github.com/kreynen/civicrm-starterkit-drops-7.git, product_id=3b754bc2-48f8-4388-b5b5-2631098d03de, branch=master, git-username=yosefromano, git-email=yosef@chabadsuite.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@^0.9.0, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, files, sites/default/files/*], sharing=true, srcRoot=/usr/local/lib/node_modules/kalabox, report=true, url=http://stats.kalabox.biz, sysConfRoot=/Users/yosefromano/.kalabox, sysProviderRoot=/Users/yosefromano/.kalabox/.provider, version=0.9.2
debug: CONFIG => App config loaded. appCidsRoot=/Users/yosefromano/Sites/civiplay/.cids, name=pantheon-appserver, srcRoot=/Users/yosefromano/Sites/civiplay, proxy=[port=80/tcp, default=true, port=443/tcp, default=true, secure=true], name=pantheon-mariadb, srcRoot=/Users/yosefromano/Sites/civiplay, name=pantheon-solr, srcRoot=/Users/yosefromano/Sites/civiplay, name=pantheon-redis, srcRoot=/Users/yosefromano/Sites/civiplay, appName=civiplay, appPlugins=[kalabox-plugin-git, kalabox-plugin-rsync, kalabox-plugin-pantheon], appRegistry=/Users/yosefromano/.kalabox/appRegistry.json, appRoot=/Users/yosefromano/Sites/civiplay, apps=[kalabox-app-backdrop@^0.9.0, kalabox-app-drupal@^0.9.0, kalabox-app-pantheon@^0.9.0], appsRoot=/Users/yosefromano/kalabox/apps, codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox, downloadsRoot=/Users/yosefromano/.kalabox/downloads, engine=kalabox-engine-docker@^0.9.0, engineRepo=kalabox, globalPluginRoot=/Users/yosefromano/kalabox/plugins, globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal, kalabox-app-backdrop, kalabox-app-pantheon], home=/Users/yosefromano, kalaboxRoot=/Users/yosefromano/kalabox, kboxRoot=/Users/yosefromano/kalabox, logLevel=debug, logLevelConsole=info, logRoot=/Users/yosefromano/.kalabox/logs, type=Darwin, platform=darwin, release=13.4.0, arch=x64, action=pull, drush-version=6, env=dev, framework=drupal, php=5.3.29, site=civip2, url=https://github.com/pantheon-systems/drops-7, branch=master, git-username=yosefromano, git-email=yosef@chabadsuite.com, profile=standard, provisioned=true, services=kalabox-services-kalabox@^0.9.0, shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, ._*, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, files, sites/default/files/*], sharing=true, srcRoot=/usr/local/lib/node_modules/kalabox, report=true, url=http://stats.kalabox.biz, sysConfRoot=/Users/yosefromano/.kalabox, sysProviderRoot=/Users/yosefromano/.kalabox/.provider, version=0.9.2
debug: DOCKER =>  Initializing provider.
debug: DOCKER =>  Provider initialized.
debug: BOOT2DOCKER =>  Executing command. 0=which, 1=boot2docker
debug: BOOT2DOCKER =>  Command results. /usr/local/bin/boot2docker

info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
debug: EVENTS =>  Emitting event [pre-up].
debug: EVENTS =>  No listeners [pre-up].
debug: EVENTS =>  Finished dispatching event listeners [pre-up].
info: BOOT2DOCKER =>  Initializing boot2docker [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=init
debug: BOOT2DOCKER =>  Command results. Virtual machine Kalabox2 already exists

info: BOOT2DOCKER =>  Bringing boot2docker up [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up

**Comment by bcauldwell** [comment]
@pirog any ideas on this issue?

On Mon, Jul 27, 2015 at 3:46 PM, yosefromano <notifications@github.com>
wrote:

> It's been running for 10 minutes. Stuck here:
>
> Last login: Mon Jul 27 15:38:33 on console
> yosefs-mbp:~ yosefromano$ kbox up -- -v
> debug: ENGINE => Initializing engine.
> debug: ENGINE => Engine initialized.
> debug: DISCO => AppsRegistry dirs. 0=fcbeta, 1=civiplay
> debug: CONFIG => App config loaded.
> appCidsRoot=/Users/yosefromano/Sites/fcbeta/.cids, name=pantheon-appserver,
> srcRoot=/Users/yosefromano/Sites/fcbeta, proxy=[port=80/tcp, default=true,
> port=443/tcp, default=true, secure=true], name=pantheon-mariadb,
> srcRoot=/Users/yosefromano/Sites/fcbeta, name=pantheon-solr,
> srcRoot=/Users/yosefromano/Sites/fcbeta, name=pantheon-redis,
> srcRoot=/Users/yosefromano/Sites/fcbeta, appName=fcbeta,
> appPlugins=[kalabox-plugin-git, kalabox-plugin-rsync,
> kalabox-plugin-pantheon],
> appRegistry=/Users/yosefromano/.kalabox/appRegistry.json,
> appRoot=/Users/yosefromano/Sites/fcbeta, apps=[kalabox-app-backdrop@^0.9.0,
> kalabox-app-drupal@^0.9.0, kalabox-app-pantheon@^0.9.0],
> appsRoot=/Users/yosefromano/kalabox/apps, codeDir=code,
> configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG], domain=kbox,
> downloadsRoot=/Users/yosefromano/.kalabox/downloads,
> engine=kalabox-engine-docker@^0.9.0, engineRepo=kalabox,
> globalPluginRoot=/Users/yosefromano/kalabox/plugins,
> globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal,
> kalabox-app-backdrop, kalabox-app-pantheon], home=/Users/yosefromano,
> kalaboxRoot=/Users/yosefromano/kalabox,
> kboxRoot=/Users/yosefromano/kalabox, logLevel=debug, logLevelConsole=info,
> logRoot=/Users/yosefromano/.kalabox/logs, type=Darwin, platform=darwin,
> release=13.4.0, arch=x64, action=pull, drush-version=6, env=dev,
> framework=drupal, php=5.3.29, site=fcbeta2, url=
> https://github.com/kreynen/civicrm-starterkit-drops-7.git,
> product_id=3b754bc2-48f8-4388-b5b5-2631098d03de, branch=master,
> git-username=yosefromano, git-email=yosef@chabadsuite.com,
> profile=standard, provisioned=true, services=kalabox-services-kalabox@^0.9.0,
> shareIgnores=[*.7z, *.bz2, *.dmg, *.gz, *.iso, *.jar, *.rar, *.tar,
> *.tgz, *.un~, *.zip, .*.swp, .*DS_Store, .DS_Store*, .
> *, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, files,
> sites/default/files/], sharing=true,
> srcRoot=/usr/local/lib/node_modules/kalabox, report=true,
> url=http://stats.kalabox.biz <http://stats.kalabox.biz>,
> sysConfRoot=/Users/yosefromano/.kalabox,
> sysProviderRoot=/Users/yosefromano/.kalabox/.provider, version=0.9.2 debug:
> CONFIG => App config loaded.
> appCidsRoot=/Users/yosefromano/Sites/civiplay/.cids,
> name=pantheon-appserver, srcRoot=/Users/yosefromano/Sites/civiplay,
> proxy=[port=80/tcp, default=true, port=443/tcp, default=true, secure=true],
> name=pantheon-mariadb, srcRoot=/Users/yosefromano/Sites/civiplay,
> name=pantheon-solr, srcRoot=/Users/yosefromano/Sites/civiplay,
> name=pantheon-redis, srcRoot=/Users/yosefromano/Sites/civiplay,
> appName=civiplay, appPlugins=[kalabox-plugin-git, kalabox-plugin-rsync,
> kalabox-plugin-pantheon],
> appRegistry=/Users/yosefromano/.kalabox/appRegistry.json,
> appRoot=/Users/yosefromano/Sites/civiplay,
> apps=[kalabox-app-backdrop@^0.9.0, kalabox-app-drupal@^0.9.0,
> kalabox-app-pantheon@^0.9.0], appsRoot=/Users/yosefromano/kalabox/apps,
> codeDir=code, configSources=[DEFAULT_GLOBAL_CONFIG, ENV_CONFIG],
> domain=kbox, downloadsRoot=/Users/yosefromano/.kalabox/downloads,
> engine=kalabox-engine-docker@^0.9.0, engineRepo=kalabox,
> globalPluginRoot=/Users/yosefromano/kalabox/plugins,
> globalPlugins=[kalabox-core, kalabox-syncthing, kalabox-app-drupal,
> kalabox-app-backdrop, kalabox-app-pantheon], home=/Users/yosefromano,
> kalaboxRoot=/Users/yosefromano/kalabox,
> kboxRoot=/Users/yosefromano/kalabox, logLevel=debug, logLevelConsole=info,
> logRoot=/Users/yosefromano/.kalabox/logs, type=Darwin, platform=darwin,
> release=13.4.0, arch=x64, action=pull, drush-version=6, env=dev,
> framework=drupal, php=5.3.29, site=civip2,
> url=https://github.com/pantheon-systems/drops-7
> <https://github.com/pantheon-systems/drops-7>, branch=master,
> git-username=yosefromano, git-email=yosef@chabadsuite.com
> <yosef@chabadsuite.com>, profile=standard, provisioned=true,
> services=kalabox-services-kalabox@^0.9.0, shareIgnores=[.7z, *.bz2, *.dmg,
> *.gz, *.iso, *.jar, *.rar, *.tar, *.tgz, *.un~, *.zip, ..swp, .DS_Store,
> .DS_Store, .**, .git, .sass-cache, Icon, Thumbs.db, ehthumbs.db, files,
> sites/default/files/*], sharing=true,
> srcRoot=/usr/local/lib/node_modules/kalabox, report=true, url=
> http://stats.kalabox.biz, sysConfRoot=/Users/yosefromano/.kalabox,
> sysProviderRoot=/Users/yosefromano/.kalabox/.provider, version=0.9.2
> debug: DOCKER => Initializing provider.
> debug: DOCKER => Provider initialized.
> debug: BOOT2DOCKER => Executing command. 0=which, 1=boot2docker
> debug: BOOT2DOCKER => Command results. /usr/local/bin/boot2docker
>
> info: BOOT2DOCKER => Starting up. maxRetries=3, max=3
> debug: EVENTS => Emitting event [pre-up].
> debug: EVENTS => No listeners [pre-up].
> debug: EVENTS => Finished dispatching event listeners [pre-up].
> info: BOOT2DOCKER => Initializing boot2docker [1].
> debug: BOOT2DOCKER => Executing command. 0=boot2docker, 1=init
> debug: BOOT2DOCKER => Command results. Virtual machine Kalabox2 already
> exists
>
> info: BOOT2DOCKER => Bringing boot2docker up [1].
> debug: BOOT2DOCKER => Executing command. 0=boot2docker, 1=up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125371693>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell isnt the isRunning issue the one that you resolved with 0.9.4? @yosefromano are you on the latest 0.9.x?

**Comment by yosefromano** [comment]
It seemed to be running 0.9.2, 
I tried updating to the latest version but the provision got stuck at step 14 I think when it was trying to bring the kbox up.

**Comment by bcauldwell** [comment]
This is a different issue now. This is the VM hanging indefinitely.

On Tue, Jul 28, 2015 at 6:44 AM, Mike Pirog <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell> isnt the isRunning issue the
> one that you resolved with 0.9.4? @yosefromano
> <https://github.com/yosefromano> are you on the latest 0.9.x?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125615455>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
@yosefromano Can you try a full uninstall and then reinstall, it's possible
something here has gotten corrupted and is causing this issue.

`npm uninstall kalabox`
`npm install kalabox -g`
`kbox provision`

On Tue, Jul 28, 2015 at 11:24 AM, yosefromano <notifications@github.com>
wrote:

> It seemed to be running 0.9.2,
> I tried updating to the latest version but the provision got stuck at step
> 14 I think when it was trying to bring the kbox up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125703508>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
npm uninstall kalabox gives this: npm WARN uninstall not installed in /Users/yosefromano/node_modules: "kalabox"

I looked again and my kalabox version is now at 0.9.7. 
I ran kbox up and it worked!!
I tried to start apps but I get this error:
 Cannot read property '3306/tcp' of null
TypeError: Cannot read property '3306/tcp' of null
    at /Users/yosefromano/Sites/fcvirg/node_modules/kalabox-plugin-drush/index.js:117:49
From previous event:
    at /Users/yosefromano/Sites/fcvirg/node_modules/kalabox-plugin-drush/index.js:115:10
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:131:9
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:128:20
From previous event:
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:126:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:106:19
From previous event:
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:98:21)
From previous event:
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:196:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:472:24
From previous event:
    at startComponent (/usr/local/lib/node_modules/kalabox/lib/app.js:471:4)
    at services.verify.then.then.then.map.concurrency (/usr/local/lib/node_modules/kalabox/lib/app.js:514:12)
From previous event:
    at Object.exports.start (/usr/local/lib/node_modules/kalabox/lib/app.js:513:4)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:330:19
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by bcauldwell** [comment]
Ok that most likely means that one of the containers for your app has not
started up correctly. This has popped up a couple of times now, and if you
can run some quick commands and give me to output I can try to get a fix
for it ASAP.

Can you please do the following.
`kbox containers` <--- this will tell you the state of the containers in
your app, look for the container that isn't running
`boot2docker --vm=Kalabox2 ssh`
`docker logs <container name that failed and isn't running>` <--- please
send me the output of this command

On Tue, Jul 28, 2015 at 12:24 PM, yosefromano <notifications@github.com>
wrote:

> npm uninstall kalabox gives this: npm WARN uninstall not installed in
> /Users/yosefromano/node_modules: "kalabox"
>
> I looked again and my kalabox version is now at 0.9.7.
> I ran kbox up and it worked!!
> I tried to start apps but I get this error:
> Cannot read property '3306/tcp' of null
> TypeError: Cannot read property '3306/tcp' of null
> at
> /Users/yosefromano/Sites/fcvirg/node_modules/kalabox-plugin-drush/index.js:117:49
> From previous event:
> at
> /Users/yosefromano/Sites/fcvirg/node_modules/kalabox-plugin-drush/index.js:115:10
> at /usr/local/lib/node_modules/kalabox/lib/core/events.js:131:9
> at /usr/local/lib/node_modules/kalabox/lib/core/events.js:128:20
> From previous event:
> at EventEngine._dispatch
> (/usr/local/lib/node_modules/kalabox/lib/core/events.js:126:18)
> at /usr/local/lib/node_modules/kalabox/lib/core/events.js:106:19
> From previous event:
> at EventEngine.emit
> (/usr/local/lib/node_modules/kalabox/lib/core/events.js:98:21)
> From previous event:
> at Object.exports.emit
> (/usr/local/lib/node_modules/kalabox/lib/core/events.js:196:4)
> at /usr/local/lib/node_modules/kalabox/lib/app.js:472:24
> From previous event:
> at startComponent (/usr/local/lib/node_modules/kalabox/lib/app.js:471:4)
> at services.verify.then.then.then.map.concurrency
> (/usr/local/lib/node_modules/kalabox/lib/app.js:514:12)
> From previous event:
> at Object.exports.start
> (/usr/local/lib/node_modules/kalabox/lib/app.js:513:4)
> at Object.task.func
> (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
> at Object.exports.run
> (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
> at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
> at /usr/local/lib/node_modules/kalabox/bin/kbox.js:330:19
> at processImmediate as _immediateCallback
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125727094>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
none of the containers are running. 
I have quite a few. Should I send the output for one?

**Comment by bcauldwell** [comment]
Make sure you are in your app's directory when you run `kbox containers` so
that it knows to only query those that belong to your app, and not other
apps or the services that ship with kbox.

On Tue, Jul 28, 2015 at 12:36 PM, yosefromano <notifications@github.com>
wrote:

> none of the containers are running.
> I have quite a few. Should I send the output for one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125730938>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
docker@boot2docker:~$ docker logs kb_fcvirg_db
Installing MariaDB/MySQL system tables in '/sql' ...
150728 19:20:51 [Note] /usr/sbin/mysqld (mysqld 5.5.44-MariaDB-1~wheezy) starting as process 35 ...
ERROR: 1136  Column count doesn't match value count at row 1
150728 19:20:51 [ERROR] Aborting

150728 19:20:51 [Note] /usr/sbin/mysqld: Shutdown complete


Installation of system tables failed!  Examine the logs in
/sql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /usr/bin/scripts/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /usr/sbin/mysqld --skip-grant --general-log &

and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /sql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
MariaDB is hosted on launchpad; You can find the latest source and
email lists at http://launchpad.net/maria

Please check all of the above before submitting a bug report
at http://mariadb.org/jira

150728 19:20:52 mysqld_safe Logging to '/sql/db.fcvirg.kbox.err'.
150728 19:20:52 mysqld_safe Starting mysqld daemon with databases from /sql
150728 19:20:52 mysqld_safe mysqld from pid file /sql/db.fcvirg.kbox.pid ended
Installing MariaDB/MySQL system tables in '/sql' ...
150728 19:38:48 [Note] /usr/sbin/mysqld (mysqld 5.5.44-MariaDB-1~wheezy) starting as process 35 ...
ERROR: 1136  Column count doesn't match value count at row 1
150728 19:38:48 [ERROR] Aborting

150728 19:38:48 [Note] /usr/sbin/mysqld: Shutdown complete


Installation of system tables failed!  Examine the logs in
/sql for more information.

The problem could be conflicting information in an external
my.cnf files. You can ignore these by doing:

    shell> /usr/bin/scripts/mysql_install_db --defaults-file=~/.my.cnf

You can also try to start the mysqld daemon with:

    shell> /usr/sbin/mysqld --skip-grant --general-log &

and use the command line tool /usr/bin/mysql
to connect to the mysql database and look at the grant tables:

    shell> /usr/bin/mysql -u root mysql
    mysql> show tables;

Try 'mysqld --help' if you have problems with paths.  Using
--general-log gives you a log in /sql that may be helpful.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
MariaDB is hosted on launchpad; You can find the latest source and
email lists at http://launchpad.net/maria

Please check all of the above before submitting a bug report
at http://mariadb.org/jira

150728 19:38:48 mysqld_safe Logging to '/sql/db.fcvirg.kbox.err'.
150728 19:38:48 mysqld_safe Starting mysqld daemon with databases from /sql
150728 19:38:48 mysqld_safe mysqld from pid file /sql/db.fcvirg.kbox.pid ended
docker@boot2docker:~$

**Comment by bcauldwell** [comment]
@yosefromano thanks so much!

@labboy0276 any idea what might be happening here? I think we've seen 2-3 users with this problem in the last few days.

**Comment by yosefromano** [comment]
@bcauldwell 
I can pass by Kalamuna with my laptop if it might help figure this out.

**Comment by bcauldwell** [comment]
Normally this would be great, but right now our drupal gurus are remote and
my knowledge of drupal is probably not sufficient to solve this particular
problem. Stop by though and I'll do everything I can to get this working.

On Tue, Jul 28, 2015 at 2:19 PM, yosefromano <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell>
> I can pass by Kalamuna with my laptop if it might help figure this out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125756954>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
Is now good?

**Comment by bcauldwell** [comment]
I'm working on another install of kalabox for someone right now, maybe in
45-60 minutes if you are available then?

On Tue, Jul 28, 2015 at 2:28 PM, yosefromano <notifications@github.com>
wrote:

> Is now good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125758546>.
>



-- 
- Benjamin Cauldwell

**Comment by yosefromano** [comment]
Should be good. See you then

**Comment by bcauldwell** [comment]
Great!

On Tue, Jul 28, 2015 at 2:30 PM, yosefromano <notifications@github.com>
wrote:

> Should be good. See you then
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125759098>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
Yosef stopped by the office.

His app's mariadb instance was complaining of a log file error where the
log file was expected to be a different size than it was. Don't know enough
about the problem space to troubleshoot that, however I did change the
mariadb image to v0.8.0 and reinstalled the app and that worked. Yosef is
able to get work done in the mean time using the v0.8.0 mariadb image.

Once we have the problem solved I will contact Yosef to switch his images
back to normal. He took notes when I showed him how to change it back.

On Tue, Jul 28, 2015 at 2:30 PM, Ben Cauldwell <ben@kalamuna.com> wrote:

> Great!
>
> On Tue, Jul 28, 2015 at 2:30 PM, yosefromano <notifications@github.com>
> wrote:
>
>> Should be good. See you then
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox/issues/343#issuecomment-125759098>.
>>
>
>
>
> --
> - Benjamin Cauldwell
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell posted about this in the other issue. Looks like this is the same thing @donkoller is getting? Might try to clean up the queues a bit so we can focus in one space.

**Comment by pirog** [comment]
@bcauldwell bleh i need to run. I think there are 2 or possibly 3 issues currently open regarding the failed DB container. Could you pick one of the issues as the canonical issue for this, close the other two and mark them as duplicates and post comments in each linking them to the canonical one? That way we can get everyone on the same page.

**Comment by bcauldwell** [comment]
Closing issue since second half of issue is different than original issue and issue title. See issue #345 for details.
