### ISSUE TITLE
Invalid or expired session header: X-Pantheon-Session on kbox create pantheon

### ISSUE THREAD

**Issue by jamesrward** [kalabox/kalabox#344]
Fresh install and provision of kbox 0.9.7 and trying to run pantheon create.  My credentials are definitely correct but I am receiving:
```Unhandled rejection Error: Error: Invalid or expired session header: X-Pantheon-Session```

![kbox-panteon-session-error](https://cloud.githubusercontent.com/assets/316094/8958499/1f4e6682-35d3-11e5-8c33-ba93b3c163a0.png)

**Comment by pirog** [comment]
Try deleting ~/.terminus and see if that helps

On Wednesday, July 29, 2015, James Ward <notifications@github.com> wrote:

> Fresh install and provision of kbox 0.9.7 and trying to run pantheon
> create. My credentials are definitely correct but I am receiving:
> Unhandled rejection Error: Error: Invalid or expired session header:
> X-Pantheon-Session
>
> [image: kbox-panteon-session-error]
> <https://cloud.githubusercontent.com/assets/316094/8958499/1f4e6682-35d3-11e5-8c33-ba93b3c163a0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/344>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by jamesrward** [comment]
Bingo.  Thanks!

I'll leave it to you to close this issue or leave it open as a reminder to check for the existing .terminus directory and handle it more gracefully.

**Comment by pirog** [comment]
Sure thing. Theoretically this is supposed to be handled but there must be
a bug in the expiration check. @bcauldwell.

On Wednesday, July 29, 2015, James Ward <notifications@github.com> wrote:

> Bingo. Thanks!
>
> I'll leave it to you to close this issue or leave it open as a reminder to
> check for the existing .terminus directory and handle it more gracefully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/344#issuecomment-125957867>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by clickbox** [comment]
deleting ~/.terminus worked for me too.

**Comment by bcauldwell** [comment]
There definitely are a few peculiarities with the expiration code, I'm
going to dig deeper and see if I can find the problem.

On Wed, Jul 29, 2015 at 7:02 AM, Mike Pirog <notifications@github.com>
wrote:

> Sure thing. Theoretically this is supposed to be handled but there must be
> a bug in the expiration check. @bcauldwell.
>
> On Wednesday, July 29, 2015, James Ward <notifications@github.com> wrote:
>
> > Bingo. Thanks!
> >
> > I'll leave it to you to close this issue or leave it open as a reminder
> to
> > check for the existing .terminus directory and handle it more gracefully.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/344#issuecomment-125957867>.
> >
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/344#issuecomment-125961538>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
@bcauldwell let me know if you have any questions about the session expiration check. It should be in `Client.prototype.__getSession` inside `lib/client.js` in the `kalabox-plugin-pantheon` which itself is inside of the `kalabox-app-pantheon`

```js

/*
 * Make sure we have a session token
 */
Client.prototype.__getSession = function() {

  // YOU WERE BORN WITH NOTHING!
  var session = {};

  // Grab the session if we already have it in run cache
  if (this.session !== undefined) {
    session = this.session;
  }
  // Try to grab from filecache
  else if (fs.existsSync(SESSIONFILE))  {
    session = JSON.parse(fs.readFileSync(SESSIONFILE, 'utf8'));
    // File is empty :()
    if (session === null) {
      session = undefined;
      return session;
    }
    else {
      this.__setSession(session);
    }
  }
  else {
    session = undefined;
    return session;
  }

  // Validate session hasn't expired yet
  if (Date.now() - session.session_expire_time < 0) {
    // invalidate cache
    this.session = undefined;
    session = undefined;
    // Destroy cached session file
    fs.unlinkSync(SESSIONFILE);
  }

  // Return whatever it is we are returning
  if (session === undefined) {
    // @todo: better debugging/logging
    console.log('You need to login first.');
  }

  // Return what we have left
  return session;

};```

**Comment by pirog** [comment]
Just on a first glance here i think 

```
  // Validate session hasn't expired yet
  if (Date.now() - session.session_expire_time < 0) {
    // invalidate cache
    this.session = undefined;
    session = undefined;
    // Destroy cached session file
    fs.unlinkSync(SESSIONFILE);
  }
};
```

Never runs when the session file exists because we are doing `this.__setSession(session);` when we check for the session file. Maybe we just want to do this at the end of `Client.prototype.__getSession()`? Also `Date.now() - session.session_expire_time < 0` seems wrong and awkward vs something like `Date.now() > session.session_expire_time`

```
  // Return what we have left
  this.__setSession(session);
  return session;
```

**Comment by bcauldwell** [comment]
I have a PR for this one. The logic was complex and whacky so I rewrote it. The main problem was the comparing of the two timestamps was bugged. The session expires timestamp is in seconds, while Date.now() is in milliseconds. I fixed it by converting session expires to milliseconds by multiplying by 1000, then doing the compare.

**Comment by pirog** [comment]
See comments in the PR as it introduces regressions namely around the handling of when the session file cache contains the literal string "null".

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/pull/7
