### ISSUE TITLE
Mariadb container sometimes not starting for kalabox version v0.9.x

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#345]
Mariadb container sometimes not starting for kalabox version v0.9.x.

The problem manifests itself with an error similar to the following.

`Cannot read property '3306/tcp' of null
TypeError: Cannot read property '3306/tcp' of null`

Performing the following commands inside of the affected app's directory will confirm the issue.
`kbox start` <--- will result in the error above
`kbox containers` <--- this will show you which container is not started
`boot2docker --vm=Kalabox2 ssh`
`docker logs <container name of container that didn't start>`

The docker logs command should give output with a mariadb error about log file size being different than expected.

QUICK WORK AROUND: setting the image name of the 'mariadb' container to 'mariadb:v0.8.0' followed by an app uninstall and app install will temporarily fix the problem.

**Comment by pirog** [comment]
@bcauldwell let me know how i can help with this but it seems like an important issue to resolve.
