### ISSUE TITLE
Removing orphaned containers

### ISSUE THREAD

**Issue by clickbox** [kalabox/kalabox#346]
Is there a way to know what containers related to a pantheon site pull are safe to remove.

**Comment by pirog** [comment]
What exactly are you trying to do? `kbox uninstall -- --purge` will remove the containers associated with a specific site pull.

**Comment by clickbox** [comment]
I'm trying to repent for my overzealous deleting of my site without shutting down first. When i tried to pull a site i already had it said the containers couldn't be created.

**Comment by pirog** [comment]
REPENT!!!!

On Sat, Aug 1, 2015 at 10:57 PM, Ezenwa Isiogu <notifications@github.com>
wrote:

> I'm trying to repent for my overzealous deleting of my site without
> shutting down first. When i tried to pull a site i already had it said the
> containers couldn't be created.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/346#issuecomment-126948931>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by clickbox** [comment]
I tried removing all the containers but still get an error when I try to pull a pantheon site.

<img width="708" alt="screen shot 2015-08-04 at 6 02 24 pm" src="https://cloud.githubusercontent.com/assets/6590017/9073948/46a523ba-3ad3-11e5-8bd0-3db21c2b4193.png">

**Comment by pirog** [comment]
are you 100% sure you removed all the containers? can you confirm this with
screenshot?

On Wed, Aug 5, 2015 at 1:04 AM, Ezenwa Isiogu <notifications@github.com>
wrote:

> I tried removing all the containers but still get an error when I try to
> pull a pantheon site.
>
> [image: screen shot 2015-08-04 at 6 02 24 pm]
> <https://cloud.githubusercontent.com/assets/6590017/9073948/46a523ba-3ad3-11e5-8bd0-3db21c2b4193.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/346#issuecomment-127775642>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by bcauldwell** [comment]
Can you do a `kbox containers` from within the app's directory and post the
results here?

On Tue, Aug 4, 2015 at 7:00 PM, Mike Pirog <notifications@github.com> wrote:

> are you 100% sure you removed all the containers? can you confirm this with
> screenshot?
>
> On Wed, Aug 5, 2015 at 1:04 AM, Ezenwa Isiogu <notifications@github.com>
> wrote:
>
> > I tried removing all the containers but still get an error when I try to
> > pull a pantheon site.
> >
> > [image: screen shot 2015-08-04 at 6 02 24 pm]
> > <
> https://cloud.githubusercontent.com/assets/6590017/9073948/46a523ba-3ad3-11e5-8bd0-3db21c2b4193.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/346#issuecomment-127775642>.
> >
>
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/346#issuecomment-127799802>.
>



-- 
- Benjamin Cauldwell

**Comment by clickbox** [comment]
I used the uninstall script and re installed and it works again

**Comment by pirog** [comment]
Ez, check over here #362 you guys might be having the same issue
