### ISSUE TITLE
On app uninstall and then reinstall, syncthing stays stopped.

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#347]
So,  

I had about 12 pantheon apps on my kb2 install.  I noticed syncthing just stopped working after powering my kb2 backup.  It would just show a status of stopped for he app I was trying to boot up.  the /code dir was empty.  When I went to the local IP (127.0.0.1:60008) it should it was trying to sync all sites in the bottom right portion of the screen (the disk icon with the long number like 6XJHHIQ-LNQMY4Y-MHHPABL-NYVDWDE-Z7LXVH2-FBRR5FS-GOXWQCR-2AMNHAN).  I left it on all night and it was still at about like 59%.  

I couldnt wait for it to finish, so I did a complete uninstall again and carried on thinking that syncthing imploded due to too many sites.  

However, I had an app (kfp) that I installed the multidev branch, then uninstalled that and installed the regular dev branch.  This effectively killed synthing, here is what it looks like:

![kb2sync](https://cloud.githubusercontent.com/assets/5560907/8991952/c607663a-36c9-11e5-89db-aedf813bf244.png)

I have tried kbox up / down, kbox rebuild, restarting my laptop, all to now avail.

**Comment by labboy0276** [comment]
To replicate:

kbox create pantheon
kbox start
kbox uninstall -- -p
kbox create pantheon (same app as above)
kbox start

You wont see the any code in the /code dir now.

**Comment by pirog** [comment]
@bcauldwell i thought we had some sort of check in place to look for the folder marker? We are removing the data container and volume on `kbox uninstall -- --purge`?

**Comment by pirog** [comment]
@bcauldwell @labboy0276 this seems particularly bad. Can you guys work together to figure out a resolution?

**Comment by labboy0276** [comment]
@pirog ok, @bcauldwell lets chat when you arrive.  It is quite an annoying problem.

**Comment by bcauldwell** [comment]
Working on this right now.

On Mon, Aug 3, 2015 at 8:07 AM, John Ouellet <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> ok, @bcauldwell
> <https://github.com/bcauldwell> lets chat when you arrive. It is quite an
> annoying problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/347#issuecomment-127272346>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
I think I have a solution for this, heading to bed, will do thorough
testing in the morning.

On Wed, Aug 5, 2015 at 12:54 PM, Ben Cauldwell <ben@kalamuna.com> wrote:

> Working on this right now.
>
> On Mon, Aug 3, 2015 at 8:07 AM, John Ouellet <notifications@github.com>
> wrote:
>
>> @pirog <https://github.com/pirog> ok, @bcauldwell
>> <https://github.com/bcauldwell> lets chat when you arrive. It is quite
>> an annoying problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox/issues/347#issuecomment-127272346>.
>>
>
>
>
> --
> - Benjamin Cauldwell
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
That's good to hear but please see forthcoming email about which issues on
which we need to be working.

On Thu, Aug 6, 2015 at 1:03 PM, bcauldwell <notifications@github.com> wrote:

> I think I have a solution for this, heading to bed, will do thorough
> testing in the morning.
>
> On Wed, Aug 5, 2015 at 12:54 PM, Ben Cauldwell <ben@kalamuna.com> wrote:
>
> > Working on this right now.
> >
> > On Mon, Aug 3, 2015 at 8:07 AM, John Ouellet <notifications@github.com>
> > wrote:
> >
> >> @pirog <https://github.com/pirog> ok, @bcauldwell
> >> <https://github.com/bcauldwell> lets chat when you arrive. It is quite
> >> an annoying problem.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/kalabox/kalabox/issues/347#issuecomment-127272346>.
> >>
> >
> >
> >
> > --
> > - Benjamin Cauldwell
> >
>
>
>
> --
> - Benjamin Cauldwell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/347#issuecomment-128242607>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@bcauldwell post whatever work you have done for this in a branch

**Comment by pirog** [comment]
@labboy0276 i can replicate this and can confirm it is an issue.

**Comment by pirog** [comment]
As a workaround for now you can do 

```
kbox uninstall -- --purge
```
 then manually go into both local and remote syncthings (`http://127.0.0.1:60008/` and `http://10.13.37.42:60008/`) and remove the appropriate folders. you may also have to purge the docker volumes.

**Comment by bcauldwell** [comment]
@pirog @labboy0276 I have a v0.9 derived branch pushed that has a fix for this. If someone could do a quick test to check my work that would be awesome!

**Comment by pirog** [comment]
I'm finishing up an issue right now and then can jump on this. dual testing
by @labboy0276 would be great also

On Mon, Aug 31, 2015 at 4:22 PM, bcauldwell <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> @labboy0276
> <https://github.com/labboy0276> I have a v0.9 derived branch pushed that
> has a fix for this. If someone could do a quick test to check my work that
> would be awesome!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/347#issuecomment-136526215>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
