### ISSUE TITLE
Kalabox provision unable to pull images

### ISSUE THREAD

**Issue by bthompson-mindgrub** [kalabox/kalabox#350]
While attempting a kbox provision, I receive the following error:

`Error running step: {"name":"syncthing-image","description":"Installing your Syn
cthing image...","deps":["engine-up"],"subscribes":[],"isStep":true}: Error pull
ing image "{ name: 'kalabox/syncthing:v0.9.0',
  build: false,
  createOpts: undefined,
  startOpts: undefined,
  postProviderOpts: undefined }".: getaddrinfo ENOTFOUND failed
VError: Error pulling image "{ name: 'kalabox/syncthing:v0.9.0',
  build: false,
  createOpts: undefined,
  startOpts: undefined,
  postProviderOpts: undefined }".: getaddrinfo ENOTFOUND failed
    at C:\Users\Brian Thompson\AppData\Roaming\npm\node_modules\kalabox\node_mod
ules\kalabox-engine-docker\docker.js:1037:13
    at processImmediate [as _immediateCallback] (timers.js:367:17)`

I troubleshot this for a bit and discovered that the installer had tried to NAT 127.0.0.1:2376 to the boot2docker machine.  However, after SSHing into the boot2docker machine I discovered that docker was listening on port 2375 and not port 2376.  I changed the NAT settings in Virtualbox and confirmed that command line commands such as docker images or docker pull <image name> function correctly.  However, I still get the same error from the kalabox installer.

(As a side note:  this is on a Windows machine

**Comment by pirog** [comment]
@bcauldwell i think we've seen this before, no?

I've noticed this port discrepancy before as well but i dont **think** this is the issue esp if the issue persists even if you changed the NAT settings. We also use port 2375 when we are making calls from Kalabox to the docker VM. It's possible that you have a different IP address of your VM and that is why it is failing. By default it should be 10.13.37.42 but in some circumstances it may be different. Can you post the VM IP?

**Comment by pirog** [comment]
I also got this error but in a different context. Had pulled a pantheon app and then computer went to sleep. Tried to start the app but got 

```
Error querying isRunning: "'90a91ba8f2f5551aa3a1e3b8a3eb2631ae643976036a716d93509cddffd3d9ce'".: Error inspecting container.: Error querying docker for list of containers.: getaddrinfo ENOTFOUND failed
```

`kbox down && kbox up && kbox start` resolved the issue

**Comment by bthompson-mindgrub** [comment]
So I did quite a bit more debugging on this issue.  You're on the right track with the VM not having the default IP.  In my case, it actually didn't have any IP address assigned to it on the Host-Only network (and SSHing into the box and assigning one didn't help anything even though I could talk back and forth between my host machine and my VM).  The actual issue was the host option in Modem (docker-modem\lib\modem.js) not being able to query VirtualBox for IP address which makes the actual host/hostname be something like "Failed%20to%20retrieve%20IP%20address... which then gets shortend to just "failed" in all of the requests.  I worked around it by hard coding it to be 127.0.0.1 but I don't think that is a distributable solution.  However, I would think it might be possible to check for a hostname == "failed" and fall back to 127.0.0.1 or somehow print a friendlier error message to the screen telling the user about the problem?  It took me quite a bit of digging to track this down so the least we could do would be to point the user in the right direction.

Unfortunately (or fortunately?) I'm no longer receiving the error message as I uninstalled everything and re-installed cleanly and did not encounter this a second time so I'm unable to try further troubleshooting or error handling without intentionally breaking my system (which I'm not keen on doing at the moment...at least, not on the system I use for 8+ hours out of the day).

**Comment by pirog** [comment]
This is awesome and super helpful. I've seen this `Failed%20to%20retrieve%20IP%20address` error before but on Linux. Strangely rebooting the computer and/or reinstalling seems to be the corrective action. 

I'm not exactly sure about the underlying system conditions that causes this to happen. Would be good to check what conditions causes B2D to spit this out. I also think its an error we can look for and potentially handle by trying to force the IP assignment. 

Glad you were able to provide a workaround and thanks for posting all this research. Great to have all this intel up in the queue before we get around to handling this!

**Comment by heddn** [comment]
Seeing this issue using a git clone of kalabox on Linux Mint. I don't have boot2docker, since I have docker directly. And I'm using virtualbox 5.0. What would help troubleshoot the problem? I can't get past `kbox provision`.

**Comment by pirog** [comment]
@heddn kalabox will install boot2docker for you. We haven't upgraded our B2D to support VB5 yet although there is an open issue for it now #364 and it should happen fairly soon.

**Comment by MichaelCalleia** [comment]
Had the same issue, repeatable. Was also running VVV (Varying-Vagrant-Vagrants https://github.com/Varying-Vagrant-Vagrants/VVV). Solution was likely overkill.

Destroyed VVV instance, removed all files, launched GUI of VirtualBox and closed, then removed environments from there (suspect that closing the environments in VirtualBox would have been enough). After this ran `kbox provision` again and it worked.

**Comment by macrocosm144** [comment]
I ran into this on windows as well. FYI it seems that virtualBox has issues on Windows 10, the latest vbox release 5.0.1 is starting to add fixes, but im not sure they're done yet.

**Comment by reynoldsalec** [comment]
Ah, good to know @macrocosm144, we'll have to keep an eye on that as we update.

**Comment by pirog** [comment]
I think we will be rolling out support for VB5 in the next release or two. Back from vacation and going to jump onto this soon.

**Comment by pirog** [comment]
So we've released a bunch of changes in the latest 0.10.x version that could impact this issue.

We still need to figure out a way to handle the "failed to retrieve" error but we now do a check to make sure the host-only adapter has the correct IP and if not we attempt to set it. 

I would def uninstall and try out the new version (only tested on Win7 for windows machines) and see what mileage you can get from it.

**Comment by macrocosm144** [comment]
Awesome, I'll check it out very soon, I'm on windows 10 tho, but that
shouldn't matter now, I believe virtualbox has sorted the initial win10
issues they had.

I'm stoked to use kalabox since it makes local Pantheon development super
slick, I'm currently using pantheons git setup plus Aquias devbox app,
which is cool, but kalabox takes the cake by far.

Thanks for creating something so useful and cool!  I'll try and help
contribute any related windows bugs I might find.  Honestly it worked fine
on my windows 8.5 until I upgraded & hit the virtualbox issue.

**Comment by pirog** [comment]
Thanks!

To be fair though i'd hold your breath re Windows 10 for now. You might want to make sure you are running the most up to date VB before you try installing kalabox. Right now we aren't officially supporting Window 10 but are looking to change that in the coming weeks as we build out better testing infrastructure.

**Comment by macrocosm144** [comment]
Ahh, ok thanks I'll keep this in mind. I will try it anyhow just to see,
supposedly anything made for win8 will work on win10. Virtualbox is running
great for me now, they had some minor networking bug that they sorted out
quickly.

**Comment by pirog** [comment]
Cool! I'm cautiously optimistic but having never run Win10 I can't really
say yet!!!

Def looking forward to getting out windows testing end up to snuff though.

Let us know how it goes and thanks for all your interest and support!

On Sunday, September 20, 2015, macrocosm144 <notifications@github.com>
wrote:

> Ahh, ok thanks I'll keep this in mind. I will try it anyhow just to see,
> supposedly anything made for win8 will work on win10. Virtualbox is running
> great for me now, they had some minor networking bug that they sorted out
> quickly.
> On Sep 20, 2015 6:35 PM, "Mike Pirog" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Thanks!
> >
> > To be fair though i'd hold your breath re Windows 10 for now. You might
> > want to make sure you are running the most up to date VB before you try
> > installing kalabox. Right now we aren't officially supporting Window 10
> but
> > are looking to change that in the coming weeks as we build out better
> > testing infrastructure.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/350#issuecomment-141842008>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/350#issuecomment-141842177>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
So i think i've got steps to replicate the failed ip address retrieval. Aka when provision fails and reports something like 

`"Failed%20to%20retrieve%20IP%20address..`

This is actually pretty easy. It happens when you go through the Kalabox install while already having the VirtualBox GUI open. 

I think there are two things we can and should do here

1. @bthompson-mindgrub's suggestion 
2. checking to see if the VB gui is open and failing the installer if it is with instructions to turn it off and reattempt the install.

**Comment by pirog** [comment]
Ick. I guess not. Automated about thirty runs of this and it seems to happen randomly regardless of whether the GUI is open or not but i think @bthompson-mindgrub's suggestion still might be the way to go here.

**Comment by pirog** [comment]
Ok so was on the right track but the replication steps are a little more convoluted. Some of these steps might not be needed.

1. Start with Kalabox already installed
2. Open up the VB gui
3. Run the windows uninstall script
4. Do not remove anything when prompted by Win UAC
5. Run through a provision again

**Comment by pirog** [comment]
So, can't do @bthompson-mindgrub's idea here because inside the VM we still have
 
```
eth1      Link encap:Ethernet  HWaddr 08:00:27:54:5E:29
          inet6 addr: fe80::a00:27ff:fe54:5e29/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:234 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:20694 (20.2 KiB)  TX bytes:31086 (30.3 KiB)
```

inside the VM and we need a line like

`inet addr: 10.13.37.42 Bcast: 10.13.37.255 Mask: 255.255.255.0` for eth1

**Comment by pirog** [comment]
Think i've got a treatment locked down here. When we run B2D up make sure we aren't getting the Failed IP rage. If we do we need to issue this command inside the VM

`sudo ifconfig eth1 10.13.37.42 netmask 255.255.255.0 broadcast 10.13.37.255 up`

**Comment by pirog** [comment]
so im pretty sure this has been resolved and will be in the new alpha4 release

**Comment by macrocosm144** [comment]
I tried over the weekend with the most recent release on Windows 10, I will test again soon and report back what I find, I didnt keep track but it was mostly networking issues. 
The host only network adapter needed the "virtualbox bridged driver" property enabled in ipv4, or the VM wouldn't turn on.
I was able to get kalabox2 vm to start up and setup a site once, but the .kbox domains weren't working so I couldn't test to see if the site was working.  I wiped it all out and will test again this week, seems like it was mostly there. :)

**Comment by reynoldsalec** [comment]
@macrocosm144 did you have any success with your reboot? We will have a 0.11.0 release coming out soon that will have some breaking changes, so if you haven't rebooted yet, you might want to make sure you're on our mailing list and try reinstalling once that's out: https://t.co/OYCq9WRhKq

**Comment by macronomicus** [comment]
@reynoldsalec Sorry Im only getting a notification on your comment today lol, just a little late, but you all definitely fixed the networking issues in the later releases. Cheers!
