### ISSUE TITLE
Pantheon app 503 -Forbidden

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#351]
Unable to view Pantheon Kbox app. 
I get a 503 -Forbidden. 
I checked the containers they are all =true. 
Tried to access the database via sequel pro with the usual kalabox configurations and got a message that permission is denied...
Any ideas?

**Comment by pirog** [comment]
@yosefromano are you sure that this is the error you are getting? 503 is usually "Service unavailable" and 403 is usually "Forbidden".

Can you provide some more details about what you are trying to do? Does this happen on all sites or one site in particular? Anything about that one site that is different than the others?

**Comment by labboy0276** [comment]
also @yosefromano to connect to the DB via a pantheon app is a little different then the straight kalabox app.
```
mysql -u pantheon -h {yourapp}.kbox -P {yourport} pantheon
```

**Comment by yosefromano** [comment]
your right it was a 403. 
That is the only app that gives me this error I get different errors for the other apps. 
I have 2 apps that work right now the rest don't and I get errors when trying to create new apps.

**Comment by yosefromano** [comment]
I get this error on another app after running kbox start
Unhandled rejection Error: App code root not found: fcdb
    at fn (/usr/local/lib/node_modules/kalabox/lib/share.js:154:15)
    at /usr/local/lib/node_modules/kalabox/lib/share.js:368:28
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/share.js:366:26
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/share.js:359:8
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/share.js:344:6
From previous event:
    at Object.exports.restart (/usr/local/lib/node_modules/kalabox/lib/share.js:335:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-syncthing/events.js:135:15
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:131:9
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:128:20
From previous event:
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:126:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:106:19
From previous event:
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:98:21)
From previous event:
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:196:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:518:24
From previous event:
    at Object.exports.start (/usr/local/lib/node_modules/kalabox/lib/app.js:517:4)
    at Object.task.func (/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/tasks/start.js:14:18)
    at Object.exports.run (/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:330:19
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by yosefromano** [comment]
Then I try to go to app.kbox and get the 403 forbidden

**Comment by pirog** [comment]
403 in the KB2 context for pantheon apps usually means you havent put any code in your code root. I would check to see if you are getting any issues when you are doing the initial site pull specifically when git is doing the clone. 

If you are not using an SSH key KB2 might time out and move on/silently fail if you don't manually enter your password.

**Comment by bcauldwell** [comment]
Issue solved and a possible bug discovered.

The name of the folder app did not match the name of the app. There are a
few places in the code where we assume those are going to be the same. I'll
make an issue for this and then we can decide if we think it's a bug or a
feature.

After solving this another issue popped up where there was no more storage
available on the boot2docker VM. I did a full uninstall and provision of
kalabox and now everything is fine. I suspect there were some orphan docker
volumes eating up that space.

On Tue, Aug 4, 2015 at 6:02 PM, Mike Pirog <notifications@github.com> wrote:

> 403 in the KB2 context for pantheon apps usually means you havent put any
> code in your code root. I would check to see if you are getting any issues
> when you are doing the initial site pull specifically when git is doing the
> clone.
>
> If you are not using an SSH key KB2 might time out and move on/silently
> fail if you don't manually enter your password.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/351#issuecomment-127808985>.
>



-- 
- Benjamin Cauldwell

**Comment by bcauldwell** [comment]
Closing issue, and created an issue for the possible underlying bug. #358
