### ISSUE TITLE
Document how to get multisite working with the stock apps

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#352]
I thought I would put this up there so that we won't forget about it.  

Can we add support for multisite / changing coderoot so we can use multisite, etc.  

UCSF is why I am putting this in.

**Comment by pirog** [comment]
There is already an issue and a branch with work in it to address this. In
fact I'm pretty sure there is a request for you to test changing the code
root in that issue.

Maybe test that code out and see if it works and rename this issue to
Drupal multi site support?

On Tuesday, August 4, 2015, John Ouellet <notifications@github.com> wrote:

> I thought I would put this up there so that we won't forget about it.
>
> Can we add support for multisite / changing coderoot so we can use
> multisite, etc.
>
> UCSF is why I am putting this in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/352>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
Correct, I should of referenced this, I had some ucsf tickets and i threw in a reminder.  #233 is where the code root issue is, i will close this out then.

**Comment by pirog** [comment]
I think a multi site site issue is worth having fwiw

On Tuesday, August 4, 2015, John Ouellet <notifications@github.com> wrote:

> Correct, I should of referenced this, I had some ucsf tickets and i threw
> in a reminder. #233 <https://github.com/kalabox/kalabox/issues/233> is
> where the code root issue is, i will close this out then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/352#issuecomment-127645881>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
then it shall remain open

**Comment by pirog** [comment]
It is so

On Tuesday, August 4, 2015, John Ouellet <notifications@github.com> wrote:

> then it shall remain open
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/352#issuecomment-127646550>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by reynoldsalec** [comment]
@pirog + @labboy0276 I'm going to re-open this issue as a reminder that we need to create documentation and work on any missing features to support work on large multi-site instances (such as the UCSF repo).

Relevant past issues:

- https://github.com/kalabox/kalabox/issues/233
- https://github.com/kalabox/kalabox/issues/377

**Issue Story**

As a Kalamuna developer, I want an easy pathway to download the UCSF multi-site architecture so I can begin working on an individual site within the architecture quickly and easily.

**Suggested Improvements**

- [ ] Create step-by-step documentation on how to import the multi-site, including details on any Kalabox config customizations required and common gotchas
- [ ] Modify Kalamuna's documentation on the UCSF infrastructure with a reference to the documentation
- [ ] Demo for a Kalamuna developer working on UCSF

**Comment by pirog** [comment]
@reynoldsalec this sounds good. I'm going to backlog this so we don't lose track of it.

@labboy0276 let's work on this together when we are in the same locale.

**Comment by labboy0276** [comment]
+47

**Comment by pirog** [comment]
**NOTES:**

```bash
# Spin up the appropriate php stock app ie drupal7
cd /path/to/apps/folder
kbox create drupal7
```

**Comment by labboy0276** [comment]
This is how I got a regular (non multisite) to work:

**Spin up the appropriate php stock app ie drupal7**
```
cd /path/to/apps/folder
kbox create drupal7
```
**Stop the site so we can make some changes**
```
cd appname
kbox stop
```
**Edit your kalabox.yml** file and add this:
```
    codeDir: code/docroot
```
To the sharing plugin in the pluginconfig section.

**Remove the generic code and clone your repo**
```
rm -rf code
git clone YOUR_ACQUIA_REPO_url code
```

Run:
```
kbox start
```
Grab your DB from the acquia dashboard
run:
```
kbox services
```
Grab the external DB config, then import the DB with the external config like this:
```
mysql -u drupal -pdrupal -h poets.kbox -P PORT# drupal < ~/path/to/db/file.sql
```
Then go into your settings.php and at this at the bottom:

```
if (isset($_ENV['KALABOX_UID'])) {
  $databases['default']['default'] = array(
    'driver' => 'mysql',
    'database' => 'drupal',
    'host' => 'database',
    'username' => 'drupal',
    'password' => 'drupal',
    'port' => '3306',
  );
}
```

Q'PLAH!

**Comment by labboy0276** [comment]
Side note, on beta4, I ran into some issues, I am posting this here in case I or anyone else needs to win this until it is resolved.

Use the same instructions above, but run these commands instead:

Instead of '''kbox stop''', run
```
sudo service kalabox restart
```

Instead of ```kalabox services``` run:
```
export DOCKER_HOST=tcp://10.13.37.100:2375
/usr/share/kalabox/bin/docker ps --all
```
Find the container for your app and grab the port. it should look something like ``` 0.0.0.0:32768->3306/tcp```

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
