### ISSUE TITLE
unable to uninstall

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#353]
$ kbox uninstall
info: DOCKER =>  Starting container kalabox_syncthing.
info: DOCKER =>  Container started. kalabox_syncthing
rm: cannot remove `/certs': Device or resource busy

**Comment by labboy0276** [comment]
@yosefromano is that the only output?

**Comment by pirog** [comment]
Despite the output this is not an error. If it's a big site it might take a
bit.

On Wednesday, August 5, 2015, John Ouellet <notifications@github.com> wrote:

> @yosefromano <https://github.com/yosefromano> is that the only output?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/353#issuecomment-127793027>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
