### ISSUE TITLE
Windows 8.1 Error at Step 15

### ISSUE THREAD

**Issue by macrocosm144** [kalabox/kalabox#355]
I've tried a several things & read thru related issues here with no luck getting past step 15 yet, I also did an uninstall/reinstall with same resulting error.  Much gratitude for any help! :)

Snipped output of  kbox provision -- --verbose
```
info: -- Step 15/18 --
info: Installing your Syncthing image...
debug: BOOT2DOCKER =>  Checking status [1].
debug: BOOT2DOCKER =>  Executing command. 0="C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --hostip="10.13.37.1", 1=status
debug: BOOT2DOCKER =>  Command results. running

info: DOCKER =>  Pulling image. name=kalabox/syncthing:v0.9.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined
debug: DOCKER =>  Initializing docker config.
debug: BOOT2DOCKER =>  Executing command. 0="C:\Program Files\Boot2Docker for Windows\boot2docker.exe" --hostip="10.13.37.1", 1=ip
debug: BOOT2DOCKER =>  Command results. 192.168.59.103

debug: DOCKER =>  Docker config initialized.
debug: DOCKER =>  Initializing docker. protocol=http, host=192.168.59.103, port=2375
debug: DOCKER =>  Docker initialized.
Error running step: {"name":"syncthing-image","description":"Installing your Syncthing image...","deps":["engine-up"],"subscribes":[],"isStep":true}: Error pulling image "{ name: 'kalabox/syncthing:v0.9.0',
  build: false,
  createOpts: undefined,
  startOpts: undefined,
  postProviderOpts: undefined }".: connect ECONNREFUSED
VError: Error pulling image "{ name: 'kalabox/syncthing:v0.9.0',
  build: false,
  createOpts: undefined,
  startOpts: undefined,
  postProviderOpts: undefined }".: connect ECONNREFUSED
    at c:\Users\Joshua\AppData\Roaming\npm\node_modules\kalabox\node_modules\kalabox-engine-docker\docker.js:1036:13
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by macrocosm144** [comment]
I fixed it, seems it was conflicting with my separate docker installation, once I removed that it installed cleanly.  I wasn't aware that kalabox has its own docker inside. 
Yarrrp that's user error :/ lol sorry!

**Comment by pirog** [comment]
Oh interesting. We actually should handle this better. Can you describe a little bit more about your previous set up? Were you using Boot2docker? Version? Any other details?

**Comment by macrocosm144** [comment]
This was my first install of either & I wasn't aware that I didn't need
docker installed first lol.

I was running the most recent standard release versions of all components,
as of two days ago.  I wish I had tried it with disabling the docker vm
installed from their windows package installer, instead of full uninstall
of docker.  I suspected the issue was having them both running, boot2docker
from the docker windows installer, and kalabox installed from within
dockers running boot2docker Linux cli.

Probably the easiest fix is to detect if docker is installed and/or running
already and adjust kalabox for ability to run along side, or just warn the
user to run one at a time, or install separately.  Or, i could be wrong and
messed something else entirely, is it ok to run them both simultaneously?

Sorry that's all a bit convoluted lol but you're expecting that on windows
installs I bet :)  I do everything to avoid Windows cli. For years I've run
my own local Ubuntu server with Aegir VM in virtualbox, so I stumbled a bit
discovering docker, and that it was safe from windows.  I still cringe when
i remember WAMP test installs long ago. lol

Sorry I didn't save version numbers and such, I was in a flow trying to
make it work & being uber rough, I knew it should work and I obviously did
something wrong. :)

Cheers!

**Comment by pirog** [comment]
so Kalabox uses the exact same installer as you are mentioning aka the Windows B2D installer. So it's likely we just upgraded your B2D docker stuff when you installed kalabox. The difference thereafter is Kalabox creates its own VM called Kalabox2 which SHOULD sit happily alongside the default B2D VM if it exists. 

I'll keep this issue open in case anyone else experiences this and we can try to track it down a little more.
