### ISSUE TITLE
Only install VB on linux if needed. Check for version higher than 4.3?

### ISSUE THREAD

**Issue by heddn** [kalabox/kalabox#356]
Docker supports the recent virtual box 5.0 release. So should kalabox. But it doesn't. I'm running on Linux Mint 17.

$ kbox provision
dpkg: regarding .../virtualbox-4.3_4.3.28-100309~Ubuntu~raring_amd64.deb containing virtualbox-4.3:
 virtualbox-4.3 conflicts with virtualbox
  virtualbox-5.0 provides virtualbox and is present and installed.

dpkg: error processing archive .kalabox/downloads/virtualbox-4.3_4.3.28-100309~Ubuntu~raring_amd64.deb (--install):
 conflicting packages - not installing virtualbox-4.3

Errors were encountered while processing:
.kalabox/downloads/virtualbox-4.3_4.3.28-100309~Ubuntu~raring_amd64.deb

info: -- OK! 75% complete! --

**Comment by heddn** [comment]
Never mind, it looks like the install continued, even though there was an error. It is a little confusing though that it tried to download the package in the first place.

**Comment by pirog** [comment]
Going to reopen this issue. We are upgrading to the latest B2D but we probably still want to do some VB version checking on Linux to allow for a pre-kb-installed VB5+

**Comment by eosrei** [comment]
Here's the error which made me ^C out of the install:
```
info: dpkg: warning: downgrading virtualbox-5.0 from 5.0.10-104061~Ubuntu~trusty to 5.0.2-102096~Ubuntu~trusty

info: (Reading database ... 327477 files and directories currently installed.)

info: Preparing to unpack .../virtualbox-5.0_5.0.2-102096~Ubuntu~trusty_amd64.deb ...
```

**Comment by pirog** [comment]
We are installing the latest and greatest now. 
https://github.com/kalabox/kalabox-engine-docker/pull/47

**Comment by eosrei** [comment]
Great! Thanks!
