### ISSUE TITLE
Critical PHP error on kbox pantheon create: Error dispatching event listeners [post-install]

### ISSUE THREAD

**Issue by dapperly** [kalabox/kalabox#357]
I've attempted a few times to create a kbox instance from Pantheon and it always fails at the same place. Here's the compact error:
```
Error while installing app: "uxm-kbox": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: PHP Warning:  Missing argument 3 for Terminus\Workflow::__construct(), called in phar:///usr/local/bin/terminus/php/Terminus/EnvironmentFactory.php on line 24 and defined in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 15
PHP Notice:  Undefined variable: object in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 18

    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
[Here is the complete, verbose output](http://it.ishe.re/code/0a3k1g3z3G46) following `kbox create pantheon -- -v`, and [general system/kbox/npm info is here](http://it.ishe.re/code/100m1d0r3s25). Some bits are redacted with asterisks, but if those are needed to resolve this I can send them privately.

There seems to be no such directory as /usr/local/bin/terminus, at least as far as the file system is concerned... no idea how to touch things via phar:// or even whether this sentence makes actual sense.

*[minor edit 080615]: fixed backward syntax in the create command, was ~~`kbox pantheon create -- -v`~~*

**Comment by pi-ron** [comment]
I got this error (or close to it) on a `kbox rebuild`, I then did `kbox start && kbox stop` then `kbox rebuild` again, and it rebuilt OK.

**Comment by pi-ron** [comment]
Update, got this on `kbox rebuild`, ran `kbox rebuild` again, and it worked OK.

**Comment by pirog** [comment]
thanks for posting @dapperly 

@pi-ron did you get the exact terminus error or something a little different?

**Comment by pirog** [comment]
@pi-ron @dapperly 

i think this might be caused when the appname is different from the pantheon sitename. Is the above true for either of you on sites that failed?

**Comment by pirog** [comment]
So i tried this out and having different names doesn't seem to matter.

@dapperly easiest way to investigate this deeper would be to add me to whatever the troubled site is on pantheon so i can try to debug. this might not be ideal for you guys though since security is important. hit me up on email if that is a viable option worth discussing.

**Comment by pi-ron** [comment]
Sorry @pirog I didn't log that error message, I'll let you know if it pops up again. From my vague and sleepless memory though, I think my errors may have been longer (more lines of red output)

**Comment by dapperly** [comment]
@pirog added you to the site on Pantheon via your Kalamuna address, site name beginning with "ux". Meanwhile, I tried kbox uninstall and rm the directory, then creating the app with the same name (the machine name instead of the friendly one, anyway) as Pantheon uses. I also cleared out a kbox app in a different directory created in a previous attempt (seen in the container inventory attached to my last post) that was causing container name conflicts. [Looks like the same result](http://it.ishe.re/code/1A0K3r0M2x09) to me.

**Comment by pirog** [comment]
@pi-ron no worries! thanks for the memories

@dapperly is this error happening on ALL the sites you try to pull down from pantheon or just the one?

i am actually traveling in Siberia right now (not a joke) and my internet is kind of sketchy but i will try to pull down the site you shared with me ASAP.

**Comment by dapperly** [comment]
@pirog I only have one site I'm interested in pulling down. I can try a different one as a test tomorrow though. And I'm in no hurry so no need to rush, can definitely wait till your internet connection is not sketchy.

**Comment by pirog** [comment]
Yeah i would def try another test site if you get the chance! I suspect the
same thing will happen but would be good to confirm.

On Fri, Aug 7, 2015 at 11:54 AM, Jonathan A. <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> I only have one site I'm interested in
> pulling down. I can try a different one as a test tomorrow though. And I'm
> in no hurry so no need to rush, can definitely wait till your internet
> connection is not sketchy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/357#issuecomment-128584482>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by dapperly** [comment]
@pirog I don't know whether this will be good news or bad but here's how that experiment went, including probably unnecessary details. New test site is also Drupal 7 but significantly less customized, far fewer modules.

1. Confirmed original and new test site PHP version is in fact 5.3.29
2. Had not uninstalled or rm'ed previous install attempts
3. `kbox create pantheon -- -v` on test site, same Pantheon account but different site, dev branch, using same name for the "monster" as the Pantheon site machine name
4. Fails with errors: `Error while installing app: "newSite": Provider  is NOT up!` etc. etc.
5. `kbox up`: success
6. `kbox apps` response: newSite not listed
7. `cd newSite && kbox uninstall`: success except `EVENTS =>  Error dispatching event listeners [pre-uninstall]. // Error: HTTP code is 404 which indicates error: no such container - no such id: kb_newSite_data`
8. `kbox containers`: no output, no error
9. `cd ..;rm -R newSite`: success
10. `kbox status`: up
11. Re-run `kbox create pantheon -- -v` same as before
12. Familiar output
13. Prompted twice for Pantheon drush password, provided it, success
14. More familiar output, then tons of files get pulled, but possibly no code (?)
15. Finishes without complaint

So yay... time to try the original site:

1. `cd lastAttempt && kbox uninstall`: success except `rm: cannot remove '/certs': Device or resource busy`
2. `cd .. && rm -R lastAttempt`: success
3. `kbox status`: up
4. `kbox containers`: cruft-free
5. `kbox create pantheon -- -v` same as original attempt on original site, using site's Pantheon machine name as the "monster" name
6. Fails again, seems to be for the same reason (below)

```
debug: EVENTS =>  Error dispatching event listeners [post-install]. VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: PHP Warning:  Missing argument 3 for Terminus\Workflow::__construct(), called in phar:///usr/local/bin/terminus/php/Terminus/EnvironmentFactory.php on line 24 and defined in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 15
PHP Notice:  Undefined variable: object in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 18

    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
Error while installing app: "retrySite": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: PHP Warning:  Missing argument 3 for Terminus\Workflow::__construct(), called in phar:///usr/local/bin/terminus/php/Terminus/EnvironmentFactory.php on line 24 and defined in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 15
PHP Notice:  Undefined variable: object in phar:///usr/local/bin/terminus/php/Terminus/Workflow.php on line 18

    at Object.<anonymous> (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
I preserved all the output. It's nearly 1 a.m. so I'm not in a redacting mood, and the successful attempt output is a lot, so I'm happy to share but please send your public key so I can email it encrypted. Mine is [here](http://first-day.com/jonathan_anderson-publickey-0xEBE75F6D.asc) and [here](http://pgp.mit.edu/pks/lookup?op=get&search=0x3EA204ECEBE75F6D).

**Comment by pirog** [comment]
@dapperly just got back from a nice vacation and going to check this out probably sometime next week after we wrap up our current sprint.

**Comment by reynoldsalec** [comment]
We may need to look out for the "undefined variable $framework" error from Terminus as well; saw that on Saturday when trying a kbox create pantheon.

**Comment by pirog** [comment]
We on it
#424

On Sun, Aug 30, 2015 at 4:44 PM, reynoldsalec <notifications@github.com>
wrote:

> We may need to look out for the "undefined variable $framework" error from
> Terminus as well; saw that on Saturday when trying a kbox create pantheon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/357#issuecomment-136217658>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@dapperly, trying the original site out on the new 0.10.1 version of kalabox and so far so good. Will report back after it finishes pulling the whole site.

**Comment by pirog** [comment]
@dapperly yup! this seems to be all cleared up now. Would recommend you uninstall and then reinstall the new 0.10.x binary version and give it a try.

It took a bit to pull the whole site down but after pulling it and doing a `kbox drush rr` it works pretty snappy after the first page load.

**Comment by dapperly** [comment]
@pirog Excellent, thanks!

**Comment by pirog** [comment]
Sure thing!

Feel free to reopen (or submit a fresh ticket) if you run into additional chaos!

**Comment by pirog** [comment]
Also, on a personal note i was expecting to get a bunch of errors after starting a site this big just because of the normal amount of noise these size sites can have. did not have a single issue so huge props to your dev team :)
