### ISSUE TITLE
when app folder name does not match app name, the code directory does not exist where we expect it to be

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#358]
When app folder name does not match app name, the code directory does not exist where we expect it to be. We assume in a few places in the code that the two names should be the same. We should either force the app name to match the folder name or handle the difference correctly in the code.

**Comment by pirog** [comment]
What circumstances lead to these things being different? Don't we create the folder name directly from the appname? Furthermore this might be related to #362
