### ISSUE TITLE
Civicrm on pantheon app

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#359]
I created a pantheon app in kalabox. 
It looks like I still need to disable civicrm in order for the site to work properly. 
How can I use civicrm in my kalabox app?

**Comment by labboy0276** [comment]
@yosefromano hello again, i wrote this a couple weeks ago:

https://kalamuna.atlassian.net/wiki/pages/viewpage.action?pageId=42991622

Should get you started.

**Comment by yosefromano** [comment]
Hey, I plugged in the code and now I get this error:

Parse error: syntax error, unexpected T_ELSEIF in /code/sites/default/civicrm.settings.php on line 104 Call Stack: 0.0050 646032 1. {main}() /code/index.php:0 0.1424 5458472 2. menu_execute_active_handler() /code/index.php:21 0.1431 5460496 3. call_user_func_array:{/code/includes/menu.inc:519}() /code/includes/menu.inc:519 0.1431 5460744 4. user_page() /code/includes/menu.inc:519 0.1432 5460824 5. drupal_get_form() /code/modules/user/user.pages.inc:562 0.1432 5461672 6. drupal_build_form() /code/includes/form.inc:130 0.1816 6239824 7. drupal_process_form() /code/includes/form.inc:385 0.6243 6895760 8. form_execute_handlers() /code/includes/form.inc:903 0.6243 6898912 9. user_login_submit() /code/includes/form.inc:1513 0.6244 6897840 10. user_login_finalize() /code/modules/user/user.module:2310 0.6397 6901576 11. user_module_invoke() /code/modules/user/user.module:2297 0.6453 7325688 12. rules_user_login() /code/modules/user/user.module:101 0.6453 7325768 13. rules_invoke_event() /code/sites/all/modules/rules/modules/events.inc:154 0.6901 8456112 14. RulesEventSet->executeByArgs() /code/sites/all/modules/rules/rules.module:973 0.6902 8456736 15. RulesPlugin->setUpState() /code/sites/all/modules/rules/includes/rules.plugins.inc:746 0.7203 9344800 16. RulesState->addVariable() /code/sites/all/modules/rules/includes/rules.core.inc:711 0.7203 9345600 17. rules_wrap_data() /code/sites/all/modules/rules/includes/rules.state.inc:64 0.7203 9346736 18. entity_metadata_wrapper() /code/sites/all/modules/rules/rules.module:486 0.7203 9351824 19. EntityDrupalWrapper->__construct() /code/sites/all/modules/entity/entity.module:1349 0.7204 9353488 20. EntityDrupalWrapper->setUp() /code/sites/all/modules/entity/includes/entity.wrapper.inc:584 0.7204 9353488 21. entity_get_property_info() /code/sites/all/modules/entity/includes/entity.wrapper.inc:588 0.7213 9354208 22. module_invoke_all() /code/sites/all/modules/entity/includes/entity.property.inc:37 0.7286 9370848 23. call_user_func_array:{/code/includes/module.inc:895}() /code/includes/module.inc:895 0.7287 9371096 24. entity_entity_property_info() /code/includes/module.inc:895 0.7604 11955936 25. EntityDefaultMetadataController->entityPropertyInfo() /code/sites/all/modules/entity/entity.info.inc:24 0.7605 11956088 26. CivicrmEntityMetadataController->convertSchema() /code/sites/all/modules/entity/entity.info.inc:72 0.7605 11956088 27. civicrm_entity_metadata_convert_schema() /code/sites/all/modules/civicrm_entity/civicrm_entity.info.inc:19 0.7605 11956088 28. civicrm_entity_get_schema() /code/sites/all/modules/civicrm_entity/civicrm_entity.info.inc:33 0.7605 11956136 29. civicrm_initialize() /code/sites/all/modules/civicrm_entity/civicrm_entity.module:131

**Comment by labboy0276** [comment]
well, it looks like you didn't put the else clause in the right place. So let's see whats up.

Can you paste your civicrm,settings.php here

**Comment by yosefromano** [comment]
if (!empty($_SERVER['PRESSFLOW_SETTINGS'])) {
  $env = json_decode($_SERVER['PRESSFLOW_SETTINGS'], TRUE);
  if (!empty($env['conf']['pantheon_binding'])) {
    $pantheon_db = $env['databases']['default']['default'];
    $pantheon_conf = $env['conf'];

    //user name and password
    $db_string = $pantheon_db['driver'] . '://' . $pantheon_db['username'] . ':' . $pantheon_db['password'] . '@';
    //host
    $db_string .= 'dbserver.' . $pantheon_conf['pantheon_environment'] . '.' . $pantheon_conf['pantheon_site_uuid'] . '.drush.in' . ':' . $pantheon_db['port'];
    // database
    $db_string .= '/' . $pantheon_db['database'] . '?new_link=true';

    // define the database strings
    define('CIVICRM_UF_DSN', $db_string);
    define('CIVICRM_DSN', $db_string);

    // define the file paths
    global $civicrm_root;

    $civicrm_root = '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/profiles/civicrm_starterkit/modules/civicrm';
    define('CIVICRM_TEMPLATE_COMPILEDIR', '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/files/civicrm/templates_c/');

    // Use Drupal base url and path
    global $base_url, $base_path;
    define( 'CIVICRM_UF_BASEURL', $base_url . '/');
    define( 'CIVICRM_SITE_KEY', 'a94ef7c7de538900b3e799e2bdba2a88' );
    
    if ( $pantheon_conf['pantheon_environment'] == 'dev' || $pantheon_conf['pantheon_environment'] == 'test' ){ 
      /**
      * This setting logs all emails to a file. Useful for debugging any mail (or civimail) issues.
      * This will not send any email, so ensure this is commented out in production
      */
     define( 'CIVICRM_MAIL_LOG', '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/sites/default/files/civicrm/templates_c/mail.log' );
    }
    
    // Add this line only once above any settings overrides
    global $civicrm_setting;
    $civicrm_setting['Directory Preferences']['extensionsDir'] = '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/sites/all/extensions/';
    $civicrm_setting['URL Preferences']['userFrameworkResourceURL'] = $base_url . '/sites/all/extensions';

	// Kalabox2 settings
	  elseif (strpos($_SERVER['APPDOMAIN'],'kbox') !== false) {
	    // Set the DB connection string
	    $db_string = $env['databases']['default']['default']['driver'] . '://' . $env['databases']['default']['default']['username'] . '@';
	    $db_string .= $env['databases']['default']['default']['host'] .  '/' . $env['databases']['default']['default']['database'] . '?new_link=true';
	    define( 'CIVICRM_UF_DSN'           , $db_string);
	    define( 'CIVICRM_DSN'           , $db_string);
	    global $civicrm_root;
	    $civicrm_root = '/code/profiless/civicrm_starterkit/modules/civicrm/';
	    define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/civicrm/templates_c/' );
	    define( 'CIVICRM_UF_BASEURL'      , 'http://' . $_SERVER['APPDOMAIN'] . '/' );
	  }
  }
} else {

/**
 * Content Management System (CMS) Datasource:

**Comment by yosefromano** [comment]
I changed the root to what it is in my directory. 
the other thing is the sites/default/files folder doesn't show up in kalabox... can that cause an issue for this line : define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/civicrm/templates_c/' );?

**Comment by labboy0276** [comment]
try this instead

```

if (!empty($_SERVER['PRESSFLOW_SETTINGS'])) {
$env = json_decode($_SERVER['PRESSFLOW_SETTINGS'], TRUE);
if (!empty($env['conf']['pantheon_binding'])) {
$pantheon_db = $env['databases']['default']['default'];
$pantheon_conf = $env['conf'];

//user name and password
$db_string = $pantheon_db['driver'] . '://' . $pantheon_db['username'] . ':' . $pantheon_db['password'] . '@';
//host
$db_string .= 'dbserver.' . $pantheon_conf['pantheon_environment'] . '.' . $pantheon_conf['pantheon_site_uuid'] . '.drush.in' . ':' . $pantheon_db['port'];
// database
$db_string .= '/' . $pantheon_db['database'] . '?new_link=true';

// define the database strings
define('CIVICRM_UF_DSN', $db_string);
define('CIVICRM_DSN', $db_string);

// define the file paths
global $civicrm_root;

$civicrm_root = '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/profiles/civicrm_starterkit/modules/civicrm';
define('CIVICRM_TEMPLATE_COMPILEDIR', '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/files/civicrm/templates_c/');

// Use Drupal base url and path
global $base_url, $base_path;
define( 'CIVICRM_UF_BASEURL', $base_url . '/');
define( 'CIVICRM_SITE_KEY', 'a94ef7c7de538900b3e799e2bdba2a88' );

if ( $pantheon_conf['pantheon_environment'] == 'dev' || $pantheon_conf['pantheon_environment'] == 'test' ){
  /**
  * This setting logs all emails to a file. Useful for debugging any mail (or civimail) issues.
  * This will not send any email, so ensure this is commented out in production
  */
 define( 'CIVICRM_MAIL_LOG', '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/sites/default/files/civicrm/templates_c/mail.log' );
}

// Add this line only once above any settings overrides
global $civicrm_setting;
$civicrm_setting['Directory Preferences']['extensionsDir'] = '/srv/bindings/' . $pantheon_conf['pantheon_binding'] . '/code/sites/all/extensions/';
$civicrm_setting['URL Preferences']['userFrameworkResourceURL'] = $base_url . '/sites/all/extensions';


}

// Kalabox2 settings
elseif (strpos($_SERVER['APPDOMAIN'],'kbox') !== false) {
  // Set the DB connection string
  $db_string = $env['databases']['default']['default']['driver'] . '://' . $env['databases']['default']['default']['username'] . '@';
  $db_string .= $env['databases']['default']['default']['host'] .  '/' . $env['databases']['default']['default']['database'] . '?new_link=true';
  define( 'CIVICRM_UF_DSN'           , $db_string);
  define( 'CIVICRM_DSN'           , $db_string);
  global $civicrm_root;
  $civicrm_root = '/code/profiless/civicrm_starterkit/modules/civicrm/';
  define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/civicrm/templates_c/' );
  define( 'CIVICRM_UF_BASEURL'      , 'http://' . $_SERVER['APPDOMAIN'] . '/' );
}

} else { .....
```

**Comment by yosefromano** [comment]
You need to define CIVICRM_DSN in civicrm.settings.php

**Comment by labboy0276** [comment]
You will need to use xdebug / an IDE to follow through the code to see where to put that conditional statement.  I have used those settings on 2 other sites with zero problems.  So it is just a matter of figuring out where your code breaks off within the first conditional and then putting in the kalabox code.

**Comment by yosefromano** [comment]
Ok @reynoldsalec found the fix 

	// Kalabox2 settings
	elseif (strpos($_SERVER['HTTP_HOST'],'kbox') !== false) {
		// Set the DB connection string
		$db_string = $env['databases']['default']['default']['driver'] . '://' . $env['databases']['default']['default']['username'] . '@';
		$db_string .= $env['databases']['default']['default']['host'] .  '/' . $env['databases']['default']['default']['database'] . '?new_link=true';
		define( 'CIVICRM_UF_DSN'           , $db_string);
		define( 'CIVICRM_DSN'           , $db_string);
		global $civicrm_root;
		$civicrm_root = '/code/profiles/civicrm_starterkit/modules/civicrm/';
		define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/civicrm/templates_c/' );
		define( 'CIVICRM_UF_BASEURL'      , 'http://' . $_SERVER['HTTP_HOST'] . '/' );
	}

He changed APPDOMAIN to HTTP_HOST

**Comment by labboy0276** [comment]
you win!

**Comment by pirog** [comment]
When we resolve #301 which will probably happen as part of #284
