### ISSUE TITLE
Upgrade to final B2D release

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#364]
Upgrade B2D to support VB5, use VB5? add VB version checks?

**Comment by idhard** [comment]
could you please tell me what is the resolution for this matter ? will kalabox switch to docker-machine  as boot2docker is deprecated ? thanks

**Comment by pirog** [comment]
Yes. At some point this will happen but its not mission critical.

**Comment by pirog** [comment]
There is a related issue over at #374
