### ISSUE TITLE
Create Framework for Installer Task Representation in GUI

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#365]
Stub out how the provisioner will pass information in the Angular code to represent the various installer steps in the GUI.

This should allow @bcauldwell to rewrite the logging code and implement it within the UI project.

**Comment by reynoldsalec** [comment]
Ok @bcauldwell, looked at this code and put in some todo comments for how I think this could work, we can chat tomorrow, don't think this is a blocker for you yet but definitely can adjust things to better accommodate: https://github.com/kalabox/kalabox-ui/commit/39944818fe18a235d0a91b78d32bb14ea7b85496

**Comment by bcauldwell** [comment]
@reynoldsalec The initialization simply get's the core Kalabox library ready to be used. I'll stick it in the initialization area you mentioned. Not blocked by this so no worries there.
