### ISSUE TITLE
"kbox pull" starts loop of "Enabling git push mode" on Pantheon

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#373]
When attempting "kbox pull" on a Pantheon app an (apparently infinite) loop of terminus containers gets created.

On the Pantheon dashboard, it appears the multiple "Enabling git push mode" commands are being issued to Pantheon; these will rack up if you let the process keep running.

Tried with kalabox-app-pantheon v.0.9.15.

Tried reverting #360 incase the new terminus.wakeSite was causing an issue, but that didn't make a difference.

Taking a look at the version of Terminus that we downgraded to (0.5.3), perhaps this is a known issue in that version?

**Comment by labboy0276** [comment]
As per our discussions via Slack, it seems that the docker hub is "messed" right now.

As a workaround for kbox pull / kbox push / kbox create, use the -- --build-local flag on these commands:

Example:
```
$ kbox create pantheon -- --build-local
$ kbox pull -- --build-local
$ kbox push -- --build-local
```

This will help you @pi-ron

**Comment by pi-ron** [comment]
Thanks guys, the command is running ok for `kbox create pantheon` but not for pull on existing; this was on existing site I pulled down earlier:

``````
$ kbox pull -- --build-local
Options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
  --database     Import latest database backup.                        [boolean]
  --files        Import latest files.                                  [boolean]

Unknown argument: build-local
``````

**Comment by pi-ron** [comment]
`kbox create pantheon -- --build-local` works

**Comment by labboy0276** [comment]
Sorry @pi-ron my mistake.

Nuke any app that tried to build from docker after the changes today.  Then use build local on kbox create.  Kbox push and pull should work after you build it locally.

**Comment by pi-ron** [comment]
Ok no worries, cheers.

**Comment by reynoldsalec** [comment]
FYI, we've found a workaround for the Docker Hub issues we mentioned, that image should now be available if you want to try a non --build-local kbox create pantheon @pi-ron.

**Comment by pi-ron** [comment]
@reynoldsalec would that require a new kbox npm install -g / kbox provision?

**Comment by pi-ron** [comment]
Hm guessing not as we're still at 0.9.9

**Comment by pi-ron** [comment]
Trying ` kbox create pantheon` without --build-local now

**Comment by pi-ron** [comment]
@reynoldsalec That worked :+1:

**Comment by pi-ron** [comment]
@labboy0276 If I need to do a rebuild (to remove .git from st ignores), do I need to add --build-local flag?

**Comment by pi-ron** [comment]
I'm back in business boys, time to do some billable work! :+1: :100:

**Comment by reynoldsalec** [comment]
Amen to that @pi-ron!
