### ISSUE TITLE
boot2docker is officially deprecated! immediate/long term plans?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#374]
Update to final B2D 1.8 for now
docker machine for laters? (post stable gui?)

**Comment by reynoldsalec** [comment]
It's what all the cool kids are using.

Docker Toolbox is their new bundle of love that combines Docker Machine with a VM and other goodies to get people started on Mac/Windows: https://blog.docker.com/2015/08/docker-toolbox/

**Comment by pirog** [comment]
i saw toolbox but not sure we want to install all that is offers? maybe you can select specific components?

**Comment by reynoldsalec** [comment]
Yeah, it does look too fat for our purposes, we kind of are a "Docker Toolbox" for Drupal in a way.

**Comment by pirog** [comment]
yeah agreed. luckily i think we can roll with B2D until we have a "clearer idea of future application of the underlying codebase."

**Comment by pirog** [comment]
going to close this meta issue in favor of #364

**Comment by zxaos** [comment]
FWIW, I'm hoping for sooner rather than later adoption of docker machine so that providers other than VirtualBox can be used as that can bring significant performance advantages in some scenarios.

**Comment by pirog** [comment]
@zxaos i assume you mean performance advantages re: file sharing?

**Comment by zxaos** [comment]
@pirog Primarily that, but also anything heavily CPU-bound that takes advantage of multiple cores:  ( http://www.tekrevue.com/2015-vm-benchmarks-parallels-11-vs-fusion-8/3/ ) such as solr.

**Comment by pirog** [comment]
Yeah for sure. We are def interested in taking advantage of all the
non-vbox VM magic. Our goal is to get the current product relatively stable
first and then we can start to play around with adding in different engine
backends ie docker-machine or rocket vs boot2docker.

On Fri, Sep 18, 2015 at 1:56 PM, Matt Bond <notifications@github.com> wrote:

> @pirog <https://github.com/pirog> Primarily that, but also anything
> heavily CPU-bound that takes advantage of multiple cores: (
> http://www.tekrevue.com/2015-vm-benchmarks-parallels-11-vs-fusion-8/3/ )
> such as solr.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/374#issuecomment-141567209>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by wizonesolutions** [comment]
Also, the boot2docker script itself doesn't support Parallels — it assumes VirtualBox. Kalabox shells out to it, so until Docker Machine lands or some other approach gets implemented that goes around that limitation, I won't use Kalabox. Play around, maybe...but I usually run PD VMs, and I don't want to kernel panic my laptop :)

**Comment by pirog** [comment]
One day we hope to earn the coveted Kevin Kaland endorsement. But it is not
this day.

On Fri, Sep 18, 2015 at 3:16 PM, Kevin Kaland <notifications@github.com>
wrote:

> Also, the boot2docker script itself doesn't support Parallels — it assumes
> VirtualBox. Kalabox shells out to it, so until Docker Machine lands or some
> other approach gets implemented that goes around that limitation, I won't
> use Kalabox. Play around, maybe...but I usually run PD VMs, and I don't
> want to kernel panic my laptop :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/374#issuecomment-141581983>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by wizonesolutions** [comment]
:D Move swiftly, my friends, lest Vlad win the war. For I have started
working on Pantheon site import for it :o

**Comment by labboy0276** [comment]
I checked out VLAD, it is equivocal to what was done on KB1.   KB2 isn't even a competitor.
