### ISSUE TITLE
Use local versions of boot2docker and syncthing in the installer.

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#380]
Any other services we could easily include?

Using local images will be a future task.

**Comment by pirog** [comment]
b2d/syncthing and the flat files are all we need for right now. on linux there is no b2d installer so we actually need to grab VB and the b2d-cli directly.

**Comment by bcauldwell** [comment]
I've added a registered dependency inside the core library, it's called 'prepackaged' and is a boolean value that can be set when initializing the core library (defaults to false if not specified).

The install code in a few places will check for this value and change behavior based on it.

Right now the behavior basically is don't download the syncthing and b2d install files, and just expect them to be where they are after a regular install. Once we have a better idea of where and how the files will be prepackaged with the GUI we change make this better.

Should I keep this issue in 'in progress' until we complete the prepackaging of files, or should I consider it closable for now?

**Comment by pirog** [comment]
Is there a use case where prepackaged will be true and mode will not be GUI?

On Monday, August 17, 2015, bcauldwell <notifications@github.com> wrote:

> I've added a registered dependency inside the core library, it's called
> 'prepackaged' and is a boolean value that can be set when initializing the
> core library (defaults to false if not specified).
>
> The install code in a few places will check for this value and change
> behavior based on it.
>
> Right now the behavior basically is don't download the syncthing and b2d
> install files, and just expect them to be where they are after a regular
> install. Once we have a better idea of where and how the files will be
> prepackaged with the GUI we change make this better.
>
> Should I keep this issue in 'in progress' until we complete the
> prepackaging of files, or should I consider it closable for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/380#issuecomment-132006206>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by bcauldwell** [comment]
I was also able to export all of our provision images debian/kalabox services/syncthing into a tar file of 295 MB, and wrote some test code that will use dockerode to load those images from the tar file into docker. They all have to be in one tar otherwise each one will be the full size of all the layers it takes to make the image.

**Comment by bcauldwell** [comment]
@pirog I can't think of a case right now where that would be true, but I don't think it's far fetched to think in the future there might be.

**Comment by reynoldsalec** [comment]
This task is basically done, but kalabox/kalabox#378 needs to be completed before we can have the finalized version, hence why it's not in QA.
