### ISSUE TITLE
Support for platform.sh environment

### ISSUE THREAD

**Issue by rcross** [kalabox/kalabox#381]
It would great to be able to mimic the platform.sh environment for local development.

**Comment by reynoldsalec** [comment]
Definitely @rcross! If you're interested in contributing a platform.sh app yourself, you should checkout how the Pantheon app is built: https://github.com/kalabox/kalabox-app-pantheon

Otherwise I'm sure this will happen sometime in the future, but our current focuses are on the GUI and locking down critical bugs in the main architecture for folks, so it might be a little way down the road.

**Comment by pirog** [comment]
Would love to see this as well. @reynoldsalec maybe we can ping the platform guys and see how they are feeling?

**Comment by pirog** [comment]
Due to some increased chatter about this feature and some personal client work that would benefit from this i'm going to reopen this for now.

**Comment by pirog** [comment]
For future documentation and/or integration here is a rough sketch of how i got a drupal platform.sh site up and running on Kalabox. Here are some deps you need for this

1. Most recent dev version of Kalabox, needs to have the `unison` `confimbigdel=false` "fix" in it.
2. Platform CLI installed locally 

We are basing a lot of this on 
https://docs.platform.sh/development/local.html

```bash
# 1. Pull down a Pantheon site that is close to what you need in terms of services ie a D7 site vs a D8 site
kbox create pantheon

# 2. Stop site and get platform git repo
cd /myapp
kbox stop
rm -rf code
platform get ID code
kbox start

# 3. Get Platform DB

```

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!

Also: https://docs.platform.sh/gettingstarted/local/lando.html
