### ISSUE TITLE
Site in another organization just wont create

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#382]
This is an odd one.  May be related to #357 , not sure.  I have checked the settings, I have checked many things.  If I try to download a multidev of the install (multidev is called zendesk), I get this:

```
info: DOCKER =>  Ad hoc container started. d80385b1edc1808d8a9e2f488dfe4217dd7806b04b8419f6c02f1ffb3cd81b48
info: DOCKER =>  Removing ad hoc container. d80385b1edc1808d8a9e2f488dfe4217dd7806b04b8419f6c02f1ffb3cd81b48
Error while installing app: "kettering": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: PHP Notice:  Undefined property: stdClass::$zendesk in phar:///usr/local/bin/terminus/php/Terminus/Site.php on line 96
PHP Fatal error:  Call to a member function onServerDev() on a non-object in phar:///usr/local/bin/terminus/php/commands/site.php on line 213
    at Object.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:696:13)
From previous event:
    at Object.use (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:695:11)
...
```
If I try to download the dev environment I get this:

```
info: DOCKER =>  Ad hoc container started. a52c9b6923e0c2a6e4cf44ef1aadd385a4d40c1a7a991b2254c91388427856af
info: DOCKER =>  Removing ad hoc container. a52c9b6923e0c2a6e4cf44ef1aadd385a4d40c1a7a991b2254c91388427856af
Error while installing app: "kettering": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: Error: Exception thrown - [curl] 6: Couldn't resolve host 'www.www-dev.kettering.edu' [url] http://www.www-dev.kettering.edu/pantheon_healthcheck

    at Object.<anonymous> (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:696:13)
From previous event:
    at Object.use (/home/john/kb2/node_modules/kalabox-engine-docker/docker.js:695:11)

```

That domain doesnt exist on the instance for dev environment anywhere.  This site downloaded fine via ```kbox create pantheon``` last week before we did all the changes we have now.  No other site does this, which is odd.  May be due to changes in org terminus type stuffs. Any insight?

**Comment by labboy0276** [comment]
This seems more like an issue with Pantheon and Enterprise accounts and DNS fails.  I am closing this out and will reopen if I am wring.

**Comment by mdyorke** [comment]
@labboy0276 I am also experiencing this problem only with sites that are Enterprise.  Were you able to find a work around?

**Comment by labboy0276** [comment]
@mdyorke can you post your error please.

**Comment by pirog** [comment]
@labboy0276 can you confirm this still happens even on the latest master?

**Comment by labboy0276** [comment]
I haven't seen it since 0.9.x

So the answer is no on 0.10.x

On Fri, Sep 18, 2015 at 4:41 PM, Mike Pirog <notifications@github.com>
wrote:

> @labboy0276 <https://github.com/labboy0276> can you confirm this still
> happens even on the latest master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/382#issuecomment-141562960>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
K, lets keep the issue closed then :)

On Fri, Sep 18, 2015 at 1:48 PM, John Ouellet <notifications@github.com>
wrote:

> I haven't seen it since 0.9.x
>
> So the answer is no on 0.10.x
>
> On Fri, Sep 18, 2015 at 4:41 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > @labboy0276 <https://github.com/labboy0276> can you confirm this still
> > happens even on the latest master?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/382#issuecomment-141562960>.
> >
>
>
>
> --
> *John Ouellet*
> *Sr Developer & Support Manager*
> 415-470-3076
> www.kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/382#issuecomment-141564666>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
