### ISSUE TITLE
DNS Failure

### ISSUE THREAD

**Issue by ellastelter** [kalabox/kalabox#383]
I am setting up a Pantheon Kalabox in Windows 7, and it works just great for a while.  However after a while (and it might be related to it going down when it goes to sleep, might not) it won't work anymore, giving me the following error in Chrome:

"The server at website.kbox can't be found, because the DNS lookup failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network."

I did have to make changes to prevent my ISP from hijacking requests.

The first time it happened I uninstalled and reinstalled everything, and it began working, but it has happened again.

**Comment by reynoldsalec** [comment]
Thanks for the bug report @ellastelter,

I take it running "kbox down" and then "kbox up" to restart Kalabox doesn't have any impact when you start seeing these issues? Networking issues definitely can happen when the computer goes asleep (although these have been mostly eliminated in my experience using Kalabox).

If you're still having problems maybe we can setup a diagnostic session sometime later this week, we don't have as much of an opportunity to see Windows issues "in the wild", so could be helpful.

**Comment by ellastelter** [comment]
Oddly, this seems to have gone away before I had a chance to troubleshoot.  Now I am getting the following error "PDOException: SQLSTATE[HY000] [2002] No route to host in lock_may_be_available() (line 167 of /code/includes/lock.inc)."  I tried going up, down, and provisioning again (which gave me errors this time at step 16), and pulling everything from the pantheon site again (also got errors), but no luck.

I can setup a dual boot if things are more likely to run smoothly in Linux.  

Thanks!!

**Comment by labboy0276** [comment]
Hello @ellastelter it seems your ~/.kalabox folder has been corrupted.

I would uninstall kalabox via the script and delete ~/.kalabox as well.  

Linux works well, but we would like to get more people on Windows reporting back bugs, etc.

**Comment by ellastelter** [comment]
How can I avoid it being corrupted in the future?  Thanks again!

**Comment by pirog** [comment]
hey @ellastelter when your computer "wakes up" are you doing 

```
kbox down && kbox up
kbox start #in the directory of the app you want to start
```

**Comment by pirog** [comment]
Hey @ellastelter we've got a new version out that we recommend updating to. I think this might resolve a lot of your issues.
