### ISSUE TITLE
load docker images from a prepackaged tar file

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#385]
Load docker images from a prepackaged tar file.

Images must be put into a single tar file. If you put the images in separate tar files then each containers every layer needed for that image to be built.

The tar file can be created using `docker save -o somefile.tar imageName imageName imageName imageName`.

All of our provision images take up 295 MB in a single tar file, so we'd have to choose what to load and what to download. We are looking at 170 MB - 295 MB depending on what we choose.

Most of this work and testing is done, I think it would take 1-2 hours to complete. I'm going to push what I have done so far to a branch and post the name of it here.

**Comment by pirog** [comment]
http://olavgg.com/post/89859509533/saving-and-loading-docker-images-to-a-compressed
