### ISSUE TITLE
Unable to allocate memory for pool. 

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#386]
I get these errors a fair bit on a pretty heavy site, but don't on Pantheon.  How can I increase memory available to Kalabox?  If I just change the memory settings in Virtualbox will that help? Or is this php memory limit?

**Comment by labboy0276** [comment]
Greetings @pi-ron 

You can tweak the php.ini in your /config/php folder of any app.  I usually put mine at 2048 for enterprise sites.  Then do a kbox rebuild and you should be good to go.

**Comment by pi-ron** [comment]
Fantastic thanks @labboy0276 Have you seen the swimming pool errors too?

**Comment by labboy0276** [comment]
Indeed, all the time.

**Comment by pi-ron** [comment]
Ok, that makes me feel better. Thanks John.

Havn't seen them since rebuild :+1:
