### ISSUE TITLE
Remove .git from .stignore

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#387]
Most users don't want to use "kbox git". We should remove .git from .stignore so the repository shows up on their host machine and they may use a tool like SourceTree to manage their version control.

**Comment by madeofpeople** [comment]
Unless theres a compelling reason as to why obscure the git directory, I plus one Alec on this one.

**Comment by labboy0276** [comment]
Large git repos can bog down syncthing, why this was done.  Mainly legacy sites that had their git history imported and have massive ~/.git directories and / or just old sites with lots of commits.

**Comment by pirog** [comment]
Yeah i'm not sure exactly how this will play but i think its worth trying again while we are still in dev.
