### ISSUE TITLE
Update Syncthing

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#388]
We're running 0.11.13, 0.11.20 is currently available. Hopefully some performance fixes and other goodies included...

**Comment by bcauldwell** [comment]
One thing that has changed is the need to restart the syncthing instance
after updating the config. So this will require a code change to take the
restarting out of the code. Shouldn't be a big deal though.

On Wed, Aug 19, 2015 at 11:10 AM, reynoldsalec <notifications@github.com>
wrote:

> We're running 0.11.13, 0.11.20 is currently available. Hopefully some
> performance fixes and other goodies included...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/388>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
nice!

i wonder if no restarts will make this more stable/faster/cleaner?

On Wed, Aug 19, 2015 at 11:24 AM, bcauldwell <notifications@github.com>
wrote:

> One thing that has changed is the need to restart the syncthing instance
> after updating the config. So this will require a code change to take the
> restarting out of the code. Shouldn't be a big deal though.
>
> On Wed, Aug 19, 2015 at 11:10 AM, reynoldsalec <notifications@github.com>
> wrote:
>
> > We're running 0.11.13, 0.11.20 is currently available. Hopefully some
> > performance fixes and other goodies included...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/388>.
> >
>
>
>
> --
> - Benjamin Cauldwell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/388#issuecomment-132732490>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by bcauldwell** [comment]
Restarts take less than a second, it's only the process that needs to
restart, not the container. No doubt it will buy us a little bit of speed
though, and it will reduce the complexity of the code for sure!

On Wed, Aug 19, 2015 at 11:31 AM, Mike Pirog <notifications@github.com>
wrote:

> nice!
>
> i wonder if no restarts will make this more stable/faster/cleaner?
>
> On Wed, Aug 19, 2015 at 11:24 AM, bcauldwell <notifications@github.com>
> wrote:
>
> > One thing that has changed is the need to restart the syncthing instance
> > after updating the config. So this will require a code change to take the
> > restarting out of the code. Shouldn't be a big deal though.
> >
> > On Wed, Aug 19, 2015 at 11:10 AM, reynoldsalec <notifications@github.com
> >
> > wrote:
> >
> > > We're running 0.11.13, 0.11.20 is currently available. Hopefully some
> > > performance fixes and other goodies included...
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kalabox/kalabox/issues/388>.
> > >
> >
> >
> >
> > --
> > - Benjamin Cauldwell
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/388#issuecomment-132732490>.
> >
>
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/388#issuecomment-132734248>.
>



-- 
- Benjamin Cauldwell
