### ISSUE TITLE
Trouble provisioning kalabox

### ISSUE THREAD

**Issue by uberhacker** [kalabox/kalabox#389]
Has anyone experienced the issue below?  I've encountered it in both Debian and Ubuntu.  Happens during kbox provision.

Error running step: {"name":"engine-up","description":"Setting up and activating the engine...","deps":["engine-docker-provider-profile"],"subscribes":[],"isStep":true}: Error bringing boot2docker up.: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying.

I should probably also mention my environment:
Debian (wheezy) / Ubuntu (trusty) in VirtualBox 4.3.30 on Windows 8.1

Thanks

**Comment by pirog** [comment]
Can you try running this again with `kbox provision -- -v` which is verbose mode and will give more debug output.

**Comment by uberhacker** [comment]
Hey Mike,
Thanks for the feedback.  Below is the output from my terminal:

info: BOOT2DOCKER =>  Bringing boot2docker up [2].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up
debug: BOOT2DOCKER =>  Error running command "boot2docker,up". Error: code:
1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

    at /usr/local/lib/node_modules/kalabox/lib/util/shell.js:98:13
    at
/usr/local/lib/node_modules/kalabox/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
info: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying. VError:
Error running command "boot2docker,up".: code: 1, msg: error in run: Failed
to start mac
hine "Kalabox2": exit status 1

    at
/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31
)
    at Promise._settlePromiseAt
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
info: BOOT2DOCKER =>  Bringing boot2docker up [3].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=up
debug: BOOT2DOCKER =>  Error running command "boot2docker,up". Error: code:
1, msg: error in run: Failed to start machine "Kalabox2": exit status 1

    at /usr/local/lib/node_modules/kalabox/lib/util/shell.js:98:13
    at
/usr/local/lib/node_modules/kalabox/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: BOOT2DOCKER =>  Bringing up boot2docker failed, retrying. VError:
Error running command "boot2docker,up".: code: 1, msg: error in run: Failed
to start mac
hine "Kalabox2": exit status 1

    at
/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:63:13
    at tryCatcher
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:503:31
)
    at Promise._settlePromiseAt
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
Error running step: {"name":"engine-up","description":"Setting up and
activating the
engine...","deps":["engine-docker-provider-profile"],"subscribes":[],"isSte
p":true}: Error bringing boot2docker up.: BOOT2DOCKER =>  Bringing up
boot2docker failed, retrying.
VError: Error bringing boot2docker up.: BOOT2DOCKER =>  Bringing up
boot2docker failed, retrying.
    at
/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/provider/b2d.js:218:17
From previous event:
    at step.all
(/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/lib/install.js:69:13)
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:414:17
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:412:30
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:404:29
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/install/framework.js:399:15
    at Object.exports.run
(/usr/local/lib/node_modules/kalabox/lib/install.js:20:3)
    at Object.<anonymous>
(/usr/local/lib/node_modules/kalabox/plugins/kalabox-core/util.js:217:23)
    at Object.exports.run
(/usr/local/lib/node_modules/kalabox/lib/core/tasks.js:773:15)
    at processTask (/usr/local/lib/node_modules/kalabox/bin/kbox.js:268:16)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:338:15
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:70:5
    at
/usr/local/lib/node_modules/kalabox/node_modules/async/lib/async.js:154:25
    at process._tickCallback (node.js:415:13)

More info about my environment:

Linux terra 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015
x86_64 x86_64 x86_64 GNU/Linux

Running in VirtualBox Version 4.3.30 r101610.

Host system:

Processor: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
Installed memory (RAM): 16.0 GB
System type: 64 bit Operating System, x64-based processor

Thanks

On Fri, Aug 21, 2015 at 3:21 PM, Mike Pirog <notifications@github.com>
wrote:

> Can you try running this again with kbox provision -- -v which is verbose
> mode and will give more debug output.
>
> —
> Reply to this email directly or view it on GitHub.
>



-- 
"God gave us two ears and one mouth to remind us we should listen twice as
much as we talk."

**Comment by ellastelter** [comment]
I am having similar issues, more similar to this than #396.  Also running Ubuntu.  Was able to install it just fine in Windows on same machine.

**Comment by ellastelter** [comment]
Unsure if it is related, but I (seemingly randomly as I wasn't working on anything related) received an error message with the following link to info about the error:  https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1457776

**Comment by pirog** [comment]
@labboy0276 may be helpful if you are having a kernel issue

**Comment by labboy0276** [comment]
Hello!

You can reference #288 for rebuilding your VB.  Usually does the trick after I update the kernel, etc.

**Comment by pirog** [comment]
Going to close this in favor of #640
