### ISSUE TITLE
General improvements for Pantheon app creation

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#391]
Walking through kbox create pantheon with @andrewmallis, here are a couple things we noticed that should be broken out into individual tasks as we can address them:

**On Running "kbox create pantheon"**
-- Exclude unnecessary directories from rsync
-- Remember pantheon creds (or find some way not to require them if you're creating a couple pantheon apps). Maybe consider a flag to use default creds so you could use multiple Pantheon accounts? May need more user info on that.
-- Password on id_rsa had to be entered in multiple times (ultimately solved by generating our own rsa key?)
-- Create an FAQ entry for people who don't remember their id_rsa key (use ssh-add on id_rsa to check passphrase, if you can't get it throw it away)

**On Running "kbox start"**
-- Once you've started, tell the user what the URL of the app is, maybe tell them the first request will take a little bit longer.

**Comment by reynoldsalec** [comment]
Being able to run "kbox create pantheon [name-of-site]" would be very convenient.

**Comment by reynoldsalec** [comment]
Improve command documentation to specify which context the command needs to be run within (either app context or global context).

Consider changing "kbox uninstall" to run within the global context (something like "kbox uninstall [appname]" better follows the structure of "rm" or other commands)

**Comment by reynoldsalec** [comment]
Add the TravisCI badge to the README so Kalabox can be certified fresh.

**Comment by pirog** [comment]
nice @reynoldsalec. thanks for the brain dump. as you mentioned we should sort through these and produce relevant issues for the items that would be obvious improvements.

**Comment by pirog** [comment]
So some of these things have been added into 0.10.x. Going to make a list of the rest of the stuff that we added to 0.10.x and wha else looks good to make it in at some point

**In 0.10.0-alpha1**
- [ ] Pantheon session are saved and you are only prompted for a password if your session is expired and needs to be re-authed
- [ ] keys are now handled automatically

**To be addressed later**
- [ ] Flag to select user account on `kbox create pantheon`
- [ ] Exclude unnecessary directories from rsync
- [ ] Better feedback to user on `kbox start/create` aka site is ready in DIR and at URL etc.
