### ISSUE TITLE
Running a global command inside of an app dir when that app has plugins that havent been installed via npm install aka dont exist in node_modules

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#394]
When the issues got to be too many, I tried uninstalling kalabox2.
npm uninstall kalabox   and then deleting the .kalabox dir in my user root.

After a new npm install kalabox -g, which appears to run OK and indicates kalabox 0.9.10, the kbox provision immediately stops with the error message: 

    Cannot find module kalabox-plugin-dbenv try an npm install first.

    Error: Cannot find module kalabox-plugin-dbenv try an npm install first.
    at /usr/local/lib/node_modules/kalabox/lib/require.js:205:13

    From previous event:
    at requireInternal (/usr/local/lib/node_modules/kalabox/lib/require.js:203:4)
    at /usr/local/lib/node_modules/kalabox/lib/require.js:295:14

    From previous event:
    at Object.exports.require (/usr/local/lib/node_modules/kalabox/lib/require.js:291:4)
    at /usr/local/lib/node_modules/kalabox/lib/kbox.js:59:28

    From previous event:
    at exports.require (/usr/local/lib/node_modules/kalabox/lib/kbox.js:52:21)
    at wrapper (/usr/local/lib/node_modules/kalabox/node_modules/lodash/index.js:3466:19)

    From previous event:
    at Object.exports.loadPlugins (/usr/local/lib/node_modules/kalabox/lib/app.js:127:18)
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:322:24
    at /usr/local/lib/node_modules/kalabox/bin/kbox.js:70:5
    at /usr/local/lib/node_modules/kalabox/node_modules/async/lib/async.js:154:25
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by labboy0276** [comment]
Hwy @donkoller 

There should be an uninstall scripts here:
```
/usr/local/lib/node_modules/kalabox/scripts
```
There are a couple in there and run the one for your OS (Darwin is Mac, Linux is all flavors of Linux etc)

I would also delete your ~/.kalabox and ~/.terminus after the fact as well.

**Comment by donkoller** [comment]
After running the uninstall script (OS X), deleted .kalabox. During script execution, chose to NOT delete virtual box. There is no .terminus. I do not run pantheon. Just Drupal.

Ran npm install kalabox -g [appeared to complete without errors]. and then kbox provision.
Still says:
    Cannot find module kalabox-plugin-dbenv try an npm install first.

**Comment by bcauldwell** [comment]
Don can you check a few things for me?

1 - what version of kalabox is installed? `kbox version`
2 - are you running the provision from inside an app's directory?

On Fri, Aug 21, 2015 at 9:58 AM, Don Koller <notifications@github.com>
wrote:

> After running the uninstall script (OS X), deleted .kalabox. During script
> execution, chose to NOT delete virtual box. There is no .terminus. I do not
> run pantheon. Just Drupal.
>
> Ran npm install kalabox -g [appeared to complete without errors]. and then
> kbox provision.
> Still says:
> Cannot find module kalabox-plugin-dbenv try an npm install first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/394#issuecomment-133494207>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
H, Ben,
1 - kbox version produces that same error message. Cannot find module kalabox-plugin-dbenv...
2 - I am running while in my sites directory where I keep the sites.

**Comment by bcauldwell** [comment]
Ok just a hunch as I'm not in the office right now so not easily able to
recreate, but try running `kbox provision` from another directory that
isn't within the directory where you keep your sites.

On Fri, Aug 21, 2015 at 10:20 AM, Don Koller <notifications@github.com>
wrote:

> H, Ben,
> 1 - kbox version produces that same error message. Cannot find module
> kalabox-plugin-dbenv...
> 2 - I am running while in my sites directory where I keep the sites.
>
>
>
> > On Aug 21, 2015, at 1:13 PM, bcauldwell <notifications@github.com>
> wrote:
> >
> > Don can you check a few things for me?
> >
> > 1 - what version of kalabox is installed? `kbox version`
> > 2 - are you running the provision from inside an app's directory?
> >
> > On Fri, Aug 21, 2015 at 9:58 AM, Don Koller <notifications@github.com>
> > wrote:
> >
> > > After running the uninstall script (OS X), deleted .kalabox. During
> script
> > > execution, chose to NOT delete virtual box. There is no .terminus. I
> do not
> > > run pantheon. Just Drupal.
> > >
> > > Ran npm install kalabox -g [appeared to complete without errors]. and
> then
> > > kbox provision.
> > > Still says:
> > > Cannot find module kalabox-plugin-dbenv try an npm install first.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kalabox/kalabox/issues/394#issuecomment-133494207
> >.
> > >
> >
> >
> >
> > --
> > - Benjamin Cauldwell
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/kalabox/kalabox/issues/394#issuecomment-133497573>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/394#issuecomment-133501565>.
>



-- 
- Benjamin Cauldwell

**Comment by donkoller** [comment]
Ben, that allowed provision to run to the Huzzah!
Thanks.

**Comment by bcauldwell** [comment]
@pirog @reynoldsalec kalabox will throw an error when trying to provision a uninstalled kalabox instance if done form inside an app's directory. Should we consider this a bug at this point?

**Comment by labboy0276** [comment]
Can we throw a message to tell humans not to do that when they try?

**Comment by pirog** [comment]
@bcauldwell maybe we can change the initialization so that it doesnt try to load the app plugins when you run a global command. Although i guess we don't know which commands are global commands until after app plugins are loaded?

We could also have this silently fail and get debug logged

**Comment by bcauldwell** [comment]
I am no longer able to recreate this bug. I suspect it is because of the rewrite I did of bin/kbox.js.

**Comment by pirog** [comment]
@bcauldwell so when you tried to recreate this issue i assume the app you tried it on had all its plugins installed? If you wipe the node_modules folder and then try you get this issue.

I named the title to more accurately reflect the issue. Going to move this back into the backlog for now.

**Comment by pirog** [comment]
With binary install this shouldnt happen anymore
