### ISSUE TITLE
kbox create pantheon hangs after asking for password when adding RSA to known hosts

### ISSUE THREAD

**Issue by johnbocalig** [kalabox/kalabox#402]
I ran kbox create pantheon and it seems to hang after it asks for a password. I wasn't sure what password I should be putting into here. I just pressed enter and left the password blank. After I realized that nothing was happening, I entered my Pantheon account's password and it continued to do nothing.
Here's the last few lines before it hung:

info: DOCKER =>  Ad hoc container created. c885f0544370f589cc6de539201547e0960cd646c580a7c335e0f68e4d15eabb
info: DOCKER =>  Starting ad hoc container "c885f0544370f589cc6de539201547e0960cd646c580a7c335e0f68e4d15eabb". Binds=[/Users/johnbocalig:/terminus, /Users/johnbocalig:/ssh, /Users/johnbocalig/Sites/kbox/johnbocalig:/src], VolumesFrom=[]
info: DOCKER =>  Ad hoc container started. c885f0544370f589cc6de539201547e0960cd646c580a7c335e0f68e4d15eabb
info: DOCKER =>  Removing ad hoc container. c885f0544370f589cc6de539201547e0960cd646c580a7c335e0f68e4d15eabb
info: DOCKER =>  Removing ad hoc container. 3288c3300dc512ce012f6e8663e14cc5c43f4a002a397ba6b5722a914721cb8b
/ssh/.ssh/id_rsa: No such file or directory
fatal: Not a git repository (or any parent up to mount point /code)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/ssh/.ssh/id_rsa: No such file or directory
Cloning into '.'...
Warning: Permanently added '[codeserver.dev.0d96a7c8-d539-40a8-a94f-bd15f33c0e1c.drush.in]:2222,[166.78.107.60]:2222' (RSA) to the list of known hosts.
codeserver.dev.0d96a7c8-d539-4@codeserver.dev.0d96a7c8-d539-40a8-a94f-bd15f33c0e1c.drush.in's password:

Please let me know if there's anymore info that you will need. Hope this helps!

**Comment by johnbocalig** [comment]
Nevermind, I answered my own question. I pulled the latest and I entered my Pantheon account password this time and it completed this time around. Carry on :+1:

**Comment by pirog** [comment]
perfect! we have an issue to make this work without having to enter your password. 
https://github.com/kalabox/kalabox-plugin-drush/issues/7
