### ISSUE TITLE
Kbox pull hanging indefinitely on existing site

### ISSUE THREAD

**Issue by jamesrward** [kalabox/kalabox#407]
I let it run for over an hour with no progress so ctrl-c'd my way out of it.  Here's screenshot of what I am seeing at the point that I shut it down.  I know this is short on information so let me know if there is anyway I can run this to provide more info.  The fact that I see ```Enter passphrase for /ssh/.ssh/id_rsa``` immediately after hitting ctrl-c leads me to believe that prompt is being passed an improper value without me seeing it, but that is pure speculation.
![screen shot 2015-08-25 at 1 13 52 pm](https://cloud.githubusercontent.com/assets/316094/9474193/201d77f0-4b2d-11e5-9689-a1fd6cdf89b3.png)

**Comment by pirog** [comment]
Did you try actually entering your ssh keyphrase?

eventually this will not be required if you have a passphrase protected key. see

**Comment by jamesrward** [comment]
Not an option.  The ```Enter passphrase for /ssh/.ssh/id_rsa``` only appears onscreen AFTER I hit ctrl-c.  A regular site-pull involve me entering my passphrase a couple of time which I have no problem with.  This prompt just never comes up.

**Comment by pirog** [comment]
Oh weird. i am getting prompted for it when i use a protected key. What os/shell are you using?

going to mark this as duplicate for now pending resolution of kalabox/kalabox-plugin-drush#7

**Comment by jamesrward** [comment]
OSX  10.10.5 zsh shell.  Just tried it again and it ran without error.  I ran kbox drush cc on the site per the duplicate issue and entered my password there as well.  No idea if that made any difference.   It sill paused briefly but didn't hang before the password request.  Here are the surrounding lines:
```
info: DOCKER =>  Ad hoc container created. de315c6bba73e71175a579331cd42a9146140f88396e25ba67349d9cc8b2408b
info: DOCKER =>  Starting ad hoc container "de315c6bba73e71175a579331cd42a9146140f88396e25ba67349d9cc8b2408b". Binds=[/Users/James:/terminus, /Users/James:/ssh, /Users/James/kalabox/pantheon/global-health-progress:/src], VolumesFrom=[]
info: DOCKER =>  Ad hoc container started. de315c6bba73e71175a579331cd42a9146140f88396e25ba67349d9cc8b2408b
info: DOCKER =>  Removing ad hoc container. de315c6bba73e71175a579331cd42a9146140f88396e25ba67349d9cc8b2408b
Enter passphrase for /ssh/.ssh/id_rsa: 
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
Warning: Permanently added '[codeserver.dev.55c42bce-8b06-48dc-904a-e82aa4df4556.drush.in]:2222,[192.237.160.107]:2222' (RSA) to the list of known hosts.
remote: Counting objects: 586, done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 180 (delta 144), reused 135 (delta 105)
Receiving objects: 100% (180/180), 31.34 KiB, done.
Resolving deltas: 100% (144/144), completed with 133 local objects.
```

I'll mark as closed and keep an eye if I can reproduce and resolve again.

**Comment by pirog** [comment]
We just released a maintenance fix for 0.9.x which does automatic key handling for pantheon. I would recommend upgrading to the latest version (0.9.18) and see if that resolves your issue.

See https://github.com/kalabox/kalabox/wiki/Updating-Kalabox . Docs are a bit out of date so YMMV but open up a ticket if you have issues and we will jump on it ASAP!

**Comment by jamesrward** [comment]
I think it's worse now :)
kbox version is showing 0.9.18 so update seems to have gone ok.
When I try to kbox pull a site I get the following errors:
```Error running ad hoc container with kalabox/terminus:v0.9.0.: Error: Please login first with `terminus auth login`

Error: Error: Please login first with `terminus auth login````

I ran terminus auth login a few times but while that seems to succeed it is having no effect on my ability to run kbox pull.

**Comment by pirog** [comment]
did you run `terminus auth login` of `kbox terminus auth login`?

On Mon, Aug 31, 2015 at 11:28 AM, James Ward <notifications@github.com>
wrote:

> I think it's worse now :)
> kbox version is showing 0.9.18 so update seems to have gone ok.
> When I try to kbox pull a site I get the following errors:
> ``Error running ad hoc container with kalabox/terminus:v0.9.0.: Error:
> Please login first withterminus auth login`
>
> Error: Error: Please login first with terminus auth login```
>
> I ran terminus auth login a few times but while that seems to succeed it
> is having no effect on my ability to run kbox pull.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/407#issuecomment-136454628>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
I presume you also updated your app?

On Mon, Aug 31, 2015 at 11:29 AM, Mike Pirog <mike@kalamuna.com> wrote:

> did you run `terminus auth login` of `kbox terminus auth login`?
>
> On Mon, Aug 31, 2015 at 11:28 AM, James Ward <notifications@github.com>
> wrote:
>
>> I think it's worse now :)
>> kbox version is showing 0.9.18 so update seems to have gone ok.
>> When I try to kbox pull a site I get the following errors:
>> ``Error running ad hoc container with kalabox/terminus:v0.9.0.: Error:
>> Please login first withterminus auth login`
>>
>> Error: Error: Please login first with terminus auth login```
>>
>> I ran terminus auth login a few times but while that seems to succeed it
>> is having no effect on my ability to run kbox pull.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox/issues/407#issuecomment-136454628>.
>>
>
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
> , Linkedin
> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
> and Facebook
> <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by jamesrward** [comment]
I've tried kbox terminus auth login which also seems to complete without issue.  kbox update within the app in questions errors out with:
```
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
    at /usr/local/lib/node_modules/kalabox/lib/app.js:432:11
From previous event:
    at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:431:9)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
From previous event:
    at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
    at process._tickCallback (node.js:419:13)
```

**Comment by pirog** [comment]
can you do the update in verbose mode `kbox update -- -v` so we can get the stack trace on the error?

**Comment by jamesrward** [comment]
```
info: DOCKER =>  Removing ad hoc container. 993b85e01aa8455506be6ab02fc002c62176f847be9e488fe32c7cd86a9e6193
debug: EVENTS =>  Error dispatching event listeners [post-install]. VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: Error: Please login first with `terminus auth login`

    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
From previous event:
    at Object.use (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:695:11)
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/engine.js:566:29
From previous event:
    at Object.exports.use (/usr/local/lib/node_modules/kalabox/lib/engine.js:565:4)
    at /Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:87:29
From previous event:
    at Terminus.__request (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:76:4)
    at Terminus.getSiteAliases (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:236:15)
    at engine.build.then.then.repo (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/pull.js:201:27)
From previous event:
    at /Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/pull.js:200:10
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:147:11
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:146:24
From previous event:
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:130:23
From previous event:
    at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:127:18)
    at /usr/local/lib/node_modules/kalabox/lib/core/events.js:107:19
From previous event:
    at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:99:21)
From previous event:
    at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:228:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:428:24
From previous event:
    at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:427:4)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
From previous event:
    at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
    at process._tickCallback (node.js:419:13)
Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
VError: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
    at /usr/local/lib/node_modules/kalabox/lib/app.js:432:11
From previous event:
    at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:431:9)
    at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
From previous event:
    at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
    at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
    at process._tickCallback (node.js:419:13)
```
ran kbox terminus auth login again but makes no difference.  Same error both times.

**Comment by pirog** [comment]
Ok i think i see what is happening here. kbox auth terminus sets the
session but kbox doesn't like the format it is in so it deletes it.

what i would do now for a workaround is just try to kbox create another
pantheon app... login and get the point where it lists your apps then you
can kill the process. I think this will log you back in.

let me know if that works and i can reformulate this issue to reflect our
research

On Mon, Aug 31, 2015 at 12:09 PM, James Ward <notifications@github.com>
wrote:

> info: DOCKER =>  Removing ad hoc container. 993b85e01aa8455506be6ab02fc002c62176f847be9e488fe32c7cd86a9e6193
> debug: EVENTS =>  Error dispatching event listeners [post-install]. VError: Error running ad hoc container with kalabox/terminus:v0.9.0.: Error: Please login first with `terminus auth login`
>
>     at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:696:13)
> From previous event:
>     at Object.use (/usr/local/lib/node_modules/kalabox/node_modules/kalabox-engine-docker/docker.js:695:11)
> From previous event:
>     at /usr/local/lib/node_modules/kalabox/lib/engine.js:566:29
> From previous event:
>     at Object.exports.use (/usr/local/lib/node_modules/kalabox/lib/engine.js:565:4)
>     at /Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:87:29
> From previous event:
>     at Terminus.__request (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:76:4)
>     at Terminus.getSiteAliases (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/terminus.js:236:15)
>     at engine.build.then.then.repo (/Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/pull.js:201:27)
> From previous event:
>     at /Users/James/kalabox/pantheon/global-health-progress/plugins/kalabox-plugin-pantheon/lib/pull.js:200:10
>     at /usr/local/lib/node_modules/kalabox/lib/core/events.js:147:11
>     at /usr/local/lib/node_modules/kalabox/lib/core/events.js:146:24
> From previous event:
>     at /usr/local/lib/node_modules/kalabox/lib/core/events.js:130:23
> From previous event:
>     at EventEngine._dispatch (/usr/local/lib/node_modules/kalabox/lib/core/events.js:127:18)
>     at /usr/local/lib/node_modules/kalabox/lib/core/events.js:107:19
> From previous event:
>     at EventEngine.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:99:21)
> From previous event:
>     at Object.exports.emit (/usr/local/lib/node_modules/kalabox/lib/core/events.js:228:4)
>     at /usr/local/lib/node_modules/kalabox/lib/app.js:428:24
> From previous event:
>     at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:427:4)
>     at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
> From previous event:
>     at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
>     at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
>     at process._tickCallback (node.js:419:13)
> Error running step: {"name":"core-rebuild","description":"Rebuild?","deps":["core-deps"],"subscribes":[],"isStep":true}: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
> VError: Error while installing app: "global-health-progress": EVENTS =>  Error dispatching event listeners [post-install].
>     at /usr/local/lib/node_modules/kalabox/lib/app.js:432:11
> From previous event:
>     at exports.install (/usr/local/lib/node_modules/kalabox/lib/app.js:431:9)
>     at /usr/local/lib/node_modules/kalabox/lib/app.js:718:12
> From previous event:
>     at Object.exports.rebuild (/usr/local/lib/node_modules/kalabox/lib/app.js:717:4)
>     at /usr/local/lib/node_modules/kalabox/plugins/kalabox-core/update.js:43:22
>     at process._tickCallback (node.js:419:13)
>
> ran kbox terminus auth login again but makes no difference. Same error
> both times.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/407#issuecomment-136470807>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
rather i can close this issue (if it eliminates the waiting) and open a new issue with the login problem.

**Comment by jamesrward** [comment]
Bingo on the work-around.  Your call if you want a new issue open.  This one can stay closed.

**Comment by pirog** [comment]
cool cool. and no prompts this time?

On Mon, Aug 31, 2015 at 12:35 PM, James Ward <notifications@github.com>
wrote:

> Bingo on the work-around. Your call if you want a new issue open. This one
> can stay closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/407#issuecomment-136477560>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
#432 for those keeping score at home

**Comment by francisco-cornejo** [comment]
Hey i may find out a work arround ... in pantheon switch to sftp and again to git . that would do the trick , after that try kbox push
