### ISSUE TITLE
Uninstall hangs with blinking cursor - Windows 8.1 64bit

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#410]
kalabox initially installed using windows "Command Prompt (Admin)" , 
then attempting "kbox create pantheon" without running "kbox provision"
ran kbox provision, process had errors and did not complete successfully 

received word that that this should not be run as admin

decided to remove installation and reinstall

in web browser entered http://127.0.0.1:60008, page was not available

from Command Prompt (Admin) ran
"kbox config", identified 
"srcRoot": C:\\Users\\bob\\AppData\\Roaming\\npm\\node_modules\\kalabox"
<code>
>cd C:\Users\bob\AppData\\Roaming\npm\node_modules\kalabox
>scripts\uninstall-win32.bat
</code>
uninstall process appears to have hung with blinking cursor after last line

in command prompt, went to 
cd c:\Users\bob\AppData\Roaming\npm\node_modules
kalabox directory there and populated

uninstall log follows:
<code>

Welcome to the Kalabox uninstaller script.

This script will destroy your current Kalabox build. If you want
to save your current build for later please either vagrant package
your existing build or export the relevant VirtualBox appliance.

MAKE SURE THAT YOU'VE EXITED THE KALABOX APP OR THIS WILL BLOW UP!!!

ALSO MAKE SURE YOU VISIT 127.0.0.1:60008 AND SHUTDOWN SYNCTHING

WHAT YOU WANT TO DO?

1. Remove all the things.
2. Forget this ever happened.

Choose your destiny:1
Stopping and removing Kalabox2
error in run: Machine "Kalabox2" does not exist.
DESTROYED!

Removing Kalabox directories
REMOVED!

</code>

**Comment by pirog** [comment]
@rgeleta this happens on windows sometimes. usually a key entry of any kind will cause it to resume.

**Comment by rgeleta** [comment]
@pirog already tried that, and did again, still stopped

**Comment by pirog** [comment]
got it. might be worth doing an in-person if you are around the next few
weeks.

On Tue, Aug 25, 2015 at 8:15 PM, rgeleta <notifications@github.com> wrote:

> @pirog <https://github.com/pirog> already tried that, and did again,
> still stopped
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/410#issuecomment-134806538>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by rgeleta** [comment]
@pirog found that there was a window open that initially appeared to be unrelated, something about a couple of windows file explorer windows open.  I closed them all then hit continue and it then proceeded to continue uninstallation - including my git that I had installed prior to this and did not want to be uninstalled - unpleasant surprise.  Anyway that process continued and ended with a warning that I would have to manually uninstall/delete some things.  Not sure which ones - any suggestions?

**Comment by pirog** [comment]
I think it asks you to manually uninstall virtualbox but its optional. 

I hear you on git maybe we can indicate that step is optional as well?

In the meantime we have a new BINARY INSTALLATION you can check out for windows which should help and is a more reliable install process.

**Comment by rgeleta** [comment]
Trying to move on
I've opened #541 
closing this one
thanks
