### ISSUE TITLE
Close VB on Provision

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#411]
As referenced in #396 we should close out VB when we start to provision.  The process will fail on step 14 and thus nuke the whole provision if VB is running.

**Comment by pirog** [comment]
im not sure if we can do this with vboxmanage but it would be good to try.

**Comment by pirog** [comment]
also, this is only an issue on LINUX which means we might be able to resolve this via

**Comment by labboy0276** [comment]
Does this help any @pirog 

http://askubuntu.com/questions/457329/shutting-down-all-virtualbox-vagrant-vms-in-one-easy-to-use-bash-command-that

**Comment by pirog** [comment]
i think its ok to have VB headless running? Only the GUI needs to be closed. Sounds like we def have to test this out more.

**Comment by labboy0276** [comment]
yeah, hmmmm...

i will ponder this with you.

**Comment by pirog** [comment]
as far as i can tell there is no way to do this safely and programmatically. the good news is the error is now thrown appropriately and stops the installer.
