### ISSUE TITLE
Acquia Cloud support

### ISSUE THREAD

**Issue by jamesrward** [kalabox/kalabox#414]
Are there any instructions / experience here for pulling an Acquia Cloud hosted site into kalabox?

**Comment by pirog** [comment]
I *think* there is an open issue that addresses multisite support which is probably a precursor to acquia integration.

We would love to have an officially supported acquia app a la our pantheon app. We've been in talks with them to do this but nothing to report as of yet. 

Feel free to bug them about helping to make it so!
