### ISSUE TITLE
SkyDNS Container Doesn't Start Correctly

### ISSUE THREAD

**Issue by bthompson-mindgrub** [kalabox/kalabox#415]
Environment:
Windows 7
Kalabox version 0.9.7

Repro:
1.  Attempt to clone Pantheon site using `kbox create pantheon`
2.  Observe error (I've stripped my client's name):
```
Error while installing app: "<project>": Error starting services.: Error startin
g service "{ name: 'dnsmasq',
  srcRoot: 'C:\\Users\\Brian Thompson\\AppData\\Roaming\\npm\\node_modules\\kala
box\\node_modules\\kalabox-services-kalabox',
  forcePull: true,
  createOpts:
   { name: 'kalabox_dnsmasq',
     ExposedPorts: { '53/tcp': {}, '53/udp': {} },
     HostConfig: { NetworkMode: 'bridge', PortBindings: [Object] },
     Image: 'dnsmasq',
     Env: [ 'KALABOX_IP=10.13.37.42', 'KALABOX_DOMAIN=.kbox' ] },
  postProviderOpts: 'getDnsmasqPostProviderOpts',
  startOpts: {} }".: Error starting container fb4eba702c1ee17a0763eb73748202ca7f
924c46132b5e26f61f058d5ca0a9ee.: HTTP code is 500 which indicates error: server
error - Cannot start container fb4eba702c1ee17a0763eb73748202ca7f924c46132b5e26f
61f058d5ca0a9ee: Error starting userland proxy: listen udp 10.13.37.43:53: bind:
 cannot assign requested address
```

When I connect to the Boot2Docker instance and run a `docker ps` I see that SkyDNS is running but seems to have bound itself to the wrong IP address:

```
docker@boot2docker:~$ docker ps
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS                              NAMES
b1a55912eed5        kalabox/skydns:v0.9.0   "/skydns -http 0.0.0   3 weeks ago         Up 16 minutes       172.17.42.1:53->53/udp, 8080/tcp   kalabox_skydns    
```

Attempting to stop the SkyDNS container via SSH and then reclone the Pantheon site did not resolve the issue.

Any thoughts on why SkyDNS is using this IP?  FWIW, the IP address listed is the one of the docker0 interface in B2D.

**Comment by pirog** [comment]
That actually is the correct IP for skydns

On Thursday, August 27, 2015, Brian <notifications@github.com> wrote:

> Environment:
> Windows 7
> Kalabox version 0.9.7
>
> Repro:
> 1. Attempt to clone Pantheon site using kbox create pantheon
> 2. Observe error (I've stripped my client's name):
>
> Error while installing app: "<project>": Error starting services.: Error startin
> g service "{ name: 'dnsmasq',
>   srcRoot: 'C:\\Users\\Brian Thompson\\AppData\\Roaming\\npm\\node_modules\\kala
> box\\node_modules\\kalabox-services-kalabox',
>   forcePull: true,
>   createOpts:
>    { name: 'kalabox_dnsmasq',
>      ExposedPorts: { '53/tcp': {}, '53/udp': {} },
>      HostConfig: { NetworkMode: 'bridge', PortBindings: [Object] },
>      Image: 'dnsmasq',
>      Env: [ 'KALABOX_IP=10.13.37.42', 'KALABOX_DOMAIN=.kbox' ] },
>   postProviderOpts: 'getDnsmasqPostProviderOpts',
>   startOpts: {} }".: Error starting container fb4eba702c1ee17a0763eb73748202ca7f
> 924c46132b5e26f61f058d5ca0a9ee.: HTTP code is 500 which indicates error: server
> error - Cannot start container fb4eba702c1ee17a0763eb73748202ca7f924c46132b5e26f
> 61f058d5ca0a9ee: Error starting userland proxy: listen udp 10.13.37.43:53: bind:
>  cannot assign requested address
>
> When I connect to the Boot2Docker instance and run a docker ps I see that
> SkyDNS is running but seems to have bound itself to the wrong IP address:
>
> docker@boot2docker:~$ docker ps
> CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS              PORTS                              NAMES
> b1a55912eed5        kalabox/skydns:v0.9.0   "/skydns -http 0.0.0   3 weeks ago         Up 16 minutes       172.17.42.1:53->53/udp, 8080/tcp   kalabox_skydns
>
> Attempting to stop the SkyDNS container via SSH and then reclone the
> Pantheon site did not resolve the issue.
>
> Any thoughts on why SkyDNS is using this IP? FWIW, the IP address listed
> is the one of the docker0 interface in B2D.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/415>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
I think the issue here is the mismatch between KALABOX_IP (reported as 10.13.37.42) and what DNSMasq is trying to bind to which is (10.13.37.43). 

If you run `kbox ip` what do you get?

There is a related issue over at #216

**Comment by bthompson-mindgrub** [comment]
```
>kbox ip
10.13.37.42
```

**Comment by pirog** [comment]
So i ran into a similar issue here. I think the problem is `kalabox-services-kalabox` is grabbing CIDs from older CIDFiles.
