### ISSUE TITLE
sometimes terminus fails with Undefined property: stdClass::$framework in phar:///usr/local/bin/terminus/php/Terminus/SitesCache.php on line 220

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#424]
uninstalling and reinstalling the app seems to resolve this most of the time

**Comment by pirog** [comment]
@labboy0276 do you think this is something you can look into?

**Comment by labboy0276** [comment]
@pirog indeed, I almost had it fixed when we started to roll back terminus

**Comment by labboy0276** [comment]
Just to replicate steps, I get this on ```kbox create pantheon```

I then run ```kbox stop && kbox uninstall && kbox install``` and it installs the app.

Maybe pass the org via terminus? Will investigate more tomorrow.

**Comment by pirog** [comment]
I don't think the org has anything to do with this. 

The issue is our php-appserver has PHP ERROR HANDLING to report basically anything so php notices from terminus are being sent to stderr which is then causing kbox to report an error in the run. 

This is partially handled by setting a separate php.ini which doesn't report notices as errors but it is only set for kterminus commands. I think the issue is that we have some commands that run terminus directly instead of the kterminus wrapper so they arent getting the new php.ini. Possible resolutions

1. Make sure client.js/terminus.js are running kterminus instead of terminus
2. Make sure we also set an appropriate php.ini in the dockerfile as well as in start.sh

I'm leaning towards 1. being cleaner here.

**Comment by pirog** [comment]
This has been fixed in terminus HEAD. Not sure if there is a new release yet and we should still try to do what we can on our end
https://github.com/pantheon-systems/cli/commit/235a18e1bf5d30f7290c8047dfa3f5691e195c6b

**Comment by pirog** [comment]
@labboy0276 for reasons yet unclear to me #1 in https://github.com/kalabox/kalabox/issues/424#issuecomment-136174705 doesn't seem to work. It throws an error right away.

**Comment by labboy0276** [comment]
@pirog I didnt mean the org, I meant to put framework, but that may be wrong anyway.   When I was going thru the codex, I tried what they did here:

https://github.com/pantheon-systems/cli/commit/235a18e1bf5d30f7290c8047dfa3f5691e195c6b#diff-def44a49e50036dc7f8dd5ed37fbf53dL218

But, It looks like they added in their changes:
https://github.com/pantheon-systems/cli/blob/master/php/Terminus/SitesCache.php

But havent released it yet as you said, they latest tag was 9 days ago, sadness....

Can we ping @TeslaDethray to possible roll out a 0.7.2 tag with the changes in it?

**Comment by pirog** [comment]
This is something that we should fix on our end too. We shouldn't be
reporting notices to stderr for terminus.

On Sun, Aug 30, 2015 at 5:53 PM, John Ouellet <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> I didnt mean the org, I meant to put
> framework, but that may be wrong anyway. When I was going thru the codex, I
> tried what they did here:
>
> pantheon-systems/cli@235a18e#diff-def44a49e50036dc7f8dd5ed37fbf53dL218
> <https://github.com/pantheon-systems/cli/commit/235a18e1bf5d30f7290c8047dfa3f5691e195c6b#diff-def44a49e50036dc7f8dd5ed37fbf53dL218>
>
> But, It looks like they added in their changes:
>
> https://github.com/pantheon-systems/cli/blob/master/php/Terminus/SitesCache.php
>
> But havent released it yet as you said, they latest tag was 9 days ago,
> sadness....
>
> Can we ping @TeslaDethray <https://github.com/TeslaDethray> to possible
> roll out a 0.7.2 tag with the changes in it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/424#issuecomment-136224848>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 this should be fixed in master. It will also be rolled into the latest 0.9.x maintenance release on friday.
