### ISSUE TITLE
A number in the app's title creates extraneous hyphens

### ISSUE THREAD

**Issue by robdecker** [kalabox/kalabox#434]
Not necessarily a bug, but a preference. When I create a new app, `kbox create drupal -- --name="my7test"`, extra hyphens get added around the `7`. 

The resulting folder name becomes `my-7-test` and domain of `my-7-test.kbox`. 
My expectations would be that the folder name is `my7test` and domain of `my7test.kbox`.

**Comment by labboy0276** [comment]
+1 on this issue.  It isn't a bug, but more or less aggravating as far as
name spacing goes.  @pirog thoughts?

On Wed, Sep 2, 2015 at 3:27 PM, Rob Decker <notifications@github.com> wrote:

> Not necessarily a bug, but a preference. When I create a new app, kbox
> create drupal -- --name="my7test", extra hyphens get added around the 7.
>
> The resulting folder name becomes my-7-test and domain of my-7-test.kbox.
> My expectations would be that the folder name is my7test and domain of
> my7test.kbox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/434>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@robdecker i think that is a pretty fair assumption. We are actually just using the kebabCase function from lodash (https://lodash.com/docs#kebabCase) on the user inputted name. Main rationale behind this:

1. it was easy
2. we dont have to write our own parsing func

That said. If this is what people want we can look into writing our own modified kebab case func. Can't say this is something we will get around to in the short term but definitely open to it.

**Comment by robdecker** [comment]
Makes sense. Is it possible to manually rename the app?

**Comment by pirog** [comment]
i *think* that would probably mess things up but you can give it a try!

**Comment by pirog** [comment]
@robdecker did you try renaming the app manually at all?

**Comment by robdecker** [comment]
@pirog I did, and it didn't work.

**Comment by pirog** [comment]
Good to know and not super surprising. 

This is something we can definitely fix in the future but i dont think we can get to it for a few more weeks.

**Comment by jdleonard** [comment]
This has also been bugging me.

**Comment by pirog** [comment]
I think we can probably get this in for the 0.10.1 release

On Wed, Sep 16, 2015 at 9:06 PM, JD Leonard <notifications@github.com>
wrote:

> This has also been bugging me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/434#issuecomment-140964782>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
Moving this into the current sprint!

**Comment by rgeleta** [comment]
+1
