### ISSUE TITLE
up and down option disappear

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#443]
Loving Kalabox, it's amazing, thanks!

For some reason kbox up and kbox down don't work. When I look at the help screen those options aren't there. If I try to start an application it complains that the provider isn't up. Any ideas?

**Comment by labboy0276** [comment]
+1 @pirog I saw this when I tried Master the other day.

@Mchampsee are you using the node or the dev versions?

**Comment by pirog** [comment]
@Mchampsee if you are using the master branch, which it sounds like you are, then that is the development branch and is not recommended for day to day usage.

**Comment by Mchampsee** [comment]
I'm using 0.10.0. I used npm command on the main page. Given that up didn't work on the command line and it didn't appear on the help screen, I assumed that this was somewhat by design in the same way that kalabox gives you limited options in directories it doesn't recognize.

**Comment by pirog** [comment]
We haven't released 0.10.0 yet. 

The latest package available from node is 0.9.18 (https://www.npmjs.com/package/kalabox) which is the currently support and "stable" version. 

Can you detail how you installed? `npm install -g kalabox` should be grabbing 0.9.18 not 0.10.0

**Comment by Mchampsee** [comment]
I'm on 0.9.18 now..user error I've been on 0.9.18 all along...sorry about that.

**Comment by pirog** [comment]
So you are on 0.9.18 and still dont see up and down?

**Comment by Mchampsee** [comment]
I've since reinstalled, but that was the case.

**Comment by pirog** [comment]
Post reinstall do the commands show as anticipated?

**Comment by Mchampsee** [comment]
Post install the commands come back, but the system is completely hosed. I was actually meaning to post a ticket to ask how to wipe all references to Kalabox from my machine so as to do a completely fresh install. :)

**Comment by pirog** [comment]
Have you checked out the uninstall guide in the wiki?
https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox

On Tue, Sep 8, 2015 at 1:05 PM, Mchampsee <notifications@github.com> wrote:

> Post install the commands come back, but the system is completely hosed. I
> was actually meaning to post a ticket to ask how to wipe all references to
> Kalabox from my machine so as to do a completely fresh install. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/443#issuecomment-138684600>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by Mchampsee** [comment]
Thanks! That helped me do a clean install and all is working again. I'll let you know if I see this issue again.

**Comment by pirog** [comment]
Awesome! thanks for responding to let us know.
