### ISSUE TITLE
Feature Request: Switch multidev on the fly

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#451]
So, @pi-ron talked about this in #376 and it may be a tall request, but here me out first.

So, as you know for our bigger clients, I usually create different multidev branches for various issues that dont block the dev workflow.  I would love to be able to just do something like ```kbox switch``` and it basically switches my git branch, re-downloads the database and files and rebuilds the instance.  

the commandz are already written, they would just need to be applied to said proposed command.

Thoughts?

**Comment by pi-ron** [comment]
I've tried setting up multiple kbox instances per multidev but the workflow isn't great and I ended up just checking out the multidev branches manually on one instance.  For my use case though I only needed to grab the dev database/files so didn't need the full 'switch' you are talking about, but I can see where it would be very useful.

**Comment by pirog** [comment]
I don't think its likely we will support something like this. The main reason for this is programmatically `kbox switch` is basically the same as another `kbox create`. The main difference is that for `kbox switch` there are way way more things that could go wrong vs a normal `kbox create`. The only real advantage i can see on the `switch` side is you'd not have to download your code again but that seems like a pretty trivial time save against all the extra stuff we'd have to do to get this to work right.

I think @pi-ron has the right idea where you just switch branches for light dev tasks.
