### ISSUE TITLE
Kalabox GUI Sketching

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#454]
It's becoming clearer that the old dashboard design isn't appropriate for Kalabox's new range of capabilities.

We need to sketch-out a process for creating and managing sites that allows for...
- creating both Wordpress/Drupal sites
- creating sites from multiple hosting services

Followup might include thinking about the technical requirements that may arise from our interface sketches and starting to investigate.

**Comment by pi-ron** [comment]
Would be keen to put some input in on this if you guys are open to it?
