### ISSUE TITLE
Dynamically allocate VM ram based on users total RAM

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#459]
Kalabox encounters significant rage on a machine that has only 4GB of ram. When you scale the VM ram back to 2GB it works much better.

**Comment by pirog** [comment]
I worked with @rgeleta on this and this is definitely worth doing for people who have 4GB or less of RAM on their machines.

**Comment by labboy0276** [comment]
+1 

I have seen this many times, I pushed mine down to 3GB of RAM (I have 8 GB of RAM, i5 cor, etc on this puter), so far so good.  If it goes bad again, I will push it down to 2GB.

**Comment by pirog** [comment]
Good to know. Wouldn't be hard to set the default to 2GB and just see how that goes for now. 

@labboy0276 do you remember what we had for memory for kalastack?

**Comment by labboy0276** [comment]
@pirog I believe it was 2GB, but i am not 100%

**Comment by pirog** [comment]
2GB seems completely sufficient for people so i think we just stay there vs doing anything fancy

**Comment by karimsmartica** [comment]
HI @pirog and @labboy0276, I have  8GB of RAM, but I always get 2GB allocated to the VM.  

How can I allocate 4GB to the VM manually?

Thanks again for the great job!

**Comment by pirog** [comment]
Right now the easiest way to do this is directly through virtual box. 2gb
seems to be pretty sufficient for most users. What is the reason for
wanting the 4?

**Comment by pirog** [comment]
Going to reopen this for further discussion

**Comment by karimsmartica** [comment]
Hi @pirog, when  power off the machine in virtual box and set System -> Base Memory to 4096 MB and relaunch KalaBox, the Base Memory automatically is decreasing to 2048.

It's not that a really need 4GB, but I'm working on a huge drupal site and I would like my VM to be faster having 8GB of ram available. 

Thanks again.

**Comment by pirog** [comment]
oh interesting!

i would check out  `~/.docker/machine/machines/Kalabox2` there might be a config file in there where you can edit the mem.

**Comment by karimsmartica** [comment]
Hi @pirog, I edited the file ~/.kalabox/kalastack/Vagrantfile 

Under the line: # Use VBoxManage to customize the VM. For example to change memory:
1.   comment (#) the line: 
vb.customize ["modifyvm", :id, "--memory", (hostem / conf["memory_divisor"].to_i)]
2. Add the line
vb.memory = 4096

That's all, and it's work.

Now we should take more time to analyze why with 8GB of RAM, the variable hostmem = Integer(conf["default_memory"]). In my case I'm with OS X Yosemite 10.10.5

Thanks again for the great job! Kalabox Rocks for Drupal !

Karim,

**Comment by pirog** [comment]
Hey @karimsmartica!

it looks like you are actually using a really old pre-cursor to kalabox called kalastack
https://github.com/kalamuna/kalastack

Is that what you are using?

**Comment by pirog** [comment]
2 GB seems to be pretty sufficient for this
