### ISSUE TITLE
Feature Request: own Git / kbox git - option

### ISSUE THREAD

**Issue by jpsalter** [kalabox/kalabox#465]
Could there be an option for `kbox create pantheon` that allows using your own git instead of kbox git as described here:
  https://github.com/kalabox/kalabox/wiki/FAQ#how-do-i-use-my-own-git-instead-of-kbox-git

Something like `kbox create pantheon -- --git-local`

**Comment by pirog** [comment]
I think this issue is already addressed in https://github.com/kalabox/kalabox/issues/387 which is also in the current sprint

**Comment by jpsalter** [comment]
Sorry - missed that one.
