### ISSUE TITLE
Report errors?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#470]
Since we have a common error pipeline and a decent metrics interface it would be great to start sending anonymous error reports to our metrics machine. It would also be awesome to count similar errors so we can see the biggest issues we have.

**Comment by pirog** [comment]
For this task it would be great for the following features

1. A way to opt out of anon-error reporting
2. Sending the kbox config up with the error
3. Reporting all errors to our metrics site
4. Identifying similar errors and counting the most frequent

**Comment by bcauldwell** [comment]
Most of this issue is done. Just having some issues getting some containers into production. Will probably finish up this weekend, and tackle other issues in the meantime that might be blocking for others.
