### ISSUE TITLE
No space left on device - kbox becomes unusable after

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#480]
0.10.0 - same issue before we had the disk size flag for provision.  Ran out of space around 20GB:

```
rsync: write failed on "/code/sites/default/files/assets/Facebook-And-Social-App-Marketing.pdf": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(322) [receiver=3.0.9]
rsync: connection unexpectedly closed (12820 bytes received so far) [generator]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [generator=3.0.9]
john@kalamuna:~/kalabox/apps/fiksu$
```

I tried to remove some apps:
```
john@kalamuna:~/kalabox/apps/cor-777$ kbox destroy
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Sharing folders [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  Boot2docker is up.
Kalabox engine has been activated.
EVENTS =>  Error dispatching event listeners [pre-uninstall].
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
john@kalamuna:~/kalabox/apps/cor-777$ kbox down
info: BOOT2DOCKER =>  Shutting down [1].
info: BOOT2DOCKER =>  Shut down successful.
Kalabox engine has been deactivated.
john@kalamuna:~/kalabox/apps/cor-777$ kbox destroy
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Sharing folders [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  Boot2docker is up.
Kalabox engine has been activated.
EVENTS =>  Error dispatching event listeners [pre-uninstall].
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

So I then went in and checked file space like before:
```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     2.6G    112.3M      2.5G   4% /
tmpfs                     1.4G         0      1.4G   0% /dev/shm
/dev/sda1                18.2G     18.2G         0 100% /mnt/sda1
cgroup                    1.4G         0      1.4G   0% /sys/fs/cgroup
none                    641.6G     95.4G    546.3G  15% /Users
docker@boot2docker:~$ 
```

Thoughts?

**Comment by pirog** [comment]
I think our best bet here is to dynamically set disksize during provision
based on the free space the user has.

On Wed, Sep 16, 2015 at 12:06 PM, John Ouellet <notifications@github.com>
wrote:

> 0.10.0 - same issue before we had the disk size flag for provision. Ran
> out of space around 20GB:
>
> rsync: write failed on "/code/sites/default/files/assets/Facebook-And-Social-App-Marketing.pdf": No space left on device (28)
> rsync error: error in file IO (code 11) at receiver.c(322) [receiver=3.0.9]
> rsync: connection unexpectedly closed (12820 bytes received so far) [generator]
> rsync error: error in rsync protocol data stream (code 12) at io.c(605) [generator=3.0.9]
> john@kalamuna:~/kalabox/apps/fiksu$
>
> I tried to remove some apps:
>
> john@kalamuna:~/kalabox/apps/cor-777$ kbox destroy
> info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
> info: BOOT2DOCKER =>  Initializing boot2docker [1].
> info: BOOT2DOCKER =>  Sharing folders [1].
> info: BOOT2DOCKER =>  Bringing boot2docker up [1].
> info: BOOT2DOCKER =>  Boot2docker is up.
> Kalabox engine has been activated.
> EVENTS =>  Error dispatching event listeners [pre-uninstall].
> Error: read ECONNRESET
>     at exports._errnoException (util.js:746:11)
>     at TCP.onread (net.js:559:26)
> john@kalamuna:~/kalabox/apps/cor-777$ kbox down
> info: BOOT2DOCKER =>  Shutting down [1].
> info: BOOT2DOCKER =>  Shut down successful.
> Kalabox engine has been deactivated.
> john@kalamuna:~/kalabox/apps/cor-777$ kbox destroy
> info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
> info: BOOT2DOCKER =>  Initializing boot2docker [1].
> info: BOOT2DOCKER =>  Sharing folders [1].
> info: BOOT2DOCKER =>  Bringing boot2docker up [1].
> info: BOOT2DOCKER =>  Boot2docker is up.
> Kalabox engine has been activated.
> EVENTS =>  Error dispatching event listeners [pre-uninstall].
> Error: connect ECONNREFUSED
>     at exports._errnoException (util.js:746:11)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
>
> So I then went in and checked file space like before:
>
> docker@boot2docker:~$ df -h
> Filesystem                Size      Used Available Use% Mounted on
> tmpfs                     2.6G    112.3M      2.5G   4% /
> tmpfs                     1.4G         0      1.4G   0% /dev/shm
> /dev/sda1                18.2G     18.2G         0 100% /mnt/sda1
> cgroup                    1.4G         0      1.4G   0% /sys/fs/cgroup
> none                    641.6G     95.4G    546.3G  15% /Users
> docker@boot2docker:~$
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/480>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
So im also going to add in some logic to check for a KALABOX_DISKSIZE env which you can set before you install to manually set the disk size
