### ISSUE TITLE
Git doesn't know that files have been deleted

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#482]
This may actually be a git issue...

I downloaded a contrib module that my project needs without committing it. I did a `kbox git pull` and apparently someone else had already committed that module to the repo. Git gives an error saying `error: The following untracked working tree files would be overwritten by merge`. So I then deleted the module, however, `git status` shows the module still there as an untracked file and `kbox git pull` gives the same error.

**Comment by pirog** [comment]
Yeah this sounds like a git issue. 

You probably just want to reset your working branch or roll your commits back and then pull down again.
