### ISSUE TITLE
Create a mailhog plugin

### ISSUE THREAD

**Issue by ivyguo518** [kalabox/kalabox#483]
Hello,
When we are developing email functions for Drupal sites, its difficult to test the results on local environment, does kalabox supports emails?

**Comment by Mchampsee** [comment]
+1 I've run into the same problem.

**Comment by pirog** [comment]
I would definitely like to get support for this into the product. 

What do you guys usually use? Have you looked at the drupal maillog module to use in the interim?

i feel like @andrewmallis might have some insight on the best things to use here as well.

**Comment by labboy0276** [comment]
reroute emails may work for this, not 100% sure though.

On Fri, Sep 18, 2015 at 5:15 PM, Mike Pirog <notifications@github.com>
wrote:

> I would definitely like to get support for this into the product.
>
> What do you guys usually use? Have you looked at the drupal maillog module
> to use in the interim?
>
> i feel like @andrewmallis <https://github.com/andrewmallis> might have
> some insight on the best things to use here as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-141570360>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
I was thinking maybe something more along the lines of
http://mailcatcher.me/

On Fri, Sep 18, 2015 at 2:34 PM, John Ouellet <notifications@github.com>
wrote:

> reroute emails may work for this, not 100% sure though.
>
> On Fri, Sep 18, 2015 at 5:15 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > I would definitely like to get support for this into the product.
> >
> > What do you guys usually use? Have you looked at the drupal maillog
> module
> > to use in the interim?
> >
> > i feel like @andrewmallis <https://github.com/andrewmallis> might have
> > some insight on the best things to use here as well.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/483#issuecomment-141570360>.
> >
>
>
>
> --
> *John Ouellet*
> *Sr Developer & Support Manager*
> 415-470-3076
> www.kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-141574529>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
that looks like it would work to me

On Fri, Sep 18, 2015 at 6:12 PM, Mike Pirog <notifications@github.com>
wrote:

> I was thinking maybe something more along the lines of
> http://mailcatcher.me/
>
> On Fri, Sep 18, 2015 at 2:34 PM, John Ouellet <notifications@github.com>
> wrote:
>
> > reroute emails may work for this, not 100% sure though.
> >
> > On Fri, Sep 18, 2015 at 5:15 PM, Mike Pirog <notifications@github.com>
> > wrote:
> >
> > > I would definitely like to get support for this into the product.
> > >
> > > What do you guys usually use? Have you looked at the drupal maillog
> > module
> > > to use in the interim?
> > >
> > > i feel like @andrewmallis <https://github.com/andrewmallis> might have
> > > some insight on the best things to use here as well.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kalabox/kalabox/issues/483#issuecomment-141570360
> >.
> > >
> >
> >
> >
> > --
> > *John Ouellet*
> > *Sr Developer & Support Manager*
> > 415-470-3076
> > www.kalamuna.com
> >
> > Stay connected with Kalamuna on: Twitter
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> > , Linkedin
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >,
> > and Facebook
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/483#issuecomment-141574529>.
> >
>
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-141581475>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by ivyguo518** [comment]
Hi all, I just got an idea, we could use external SMTP to send emails from kbox sites.
http://drupal.org/project/smtp

**Comment by labboy0276** [comment]
The SMTP module is standard to use for any site that does mailing.  We use
it all the time for our sites and I know it can't send emails out within
Kalabox that I have seen by itself.

What @pirog suggested will be able to add a mailservice to Kalabox, then
you can use the module on top of that.  That should do the trick.

Thanks for the suggestion though

On Sun, Sep 20, 2015 at 7:53 PM, ivyguo518 <notifications@github.com> wrote:

> Hi all, I just got an idea, we could use external SMTP to send emails from
> kbox sites.
> http://drupal.org/project/smtp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-141846015>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@ivyguo518 yeah there are definitely drupal-side solutions you can consider. Whether that is SMTP or maillog or something else.

**Comment by enfuse** [comment]
@pirog what about mailhog https://github.com/mailhog/MailHog rather than http://mailcatcher.me/?

**Comment by pirog** [comment]
yes!

i was trying to remember what that thing was called! totally!

On Mon, Sep 21, 2015 at 9:00 AM, Juanjo <notifications@github.com> wrote:

> @pirog <https://github.com/pirog> what about mailhog
> https://github.com/mailhog/MailHog rather than http://mailcatcher.me/?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-142026855>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by Mchampsee** [comment]
I'm finding that sending email won't work for me at all, even using the SMTP module. (I can send a test email through SMTP module fine, but it won't send anything else). I'm trying to isolate the problem and will update if I find out anything more specific.

**Comment by labboy0276** [comment]
Yes,

It is because you are sending it behind a proxy.

On Mon, Sep 21, 2015 at 3:08 PM, Mchampsee <notifications@github.com> wrote:

> I'm finding that sending email won't work for me at all, even using the
> SMTP module. (I can send a test email through SMTP module fine, but it
> won't send anything else). I'm trying to isolate the problem and will
> update if I find out anything more specific.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/483#issuecomment-142080265>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by ivyguo518** [comment]
@Mchampsee Did you check the settings on /admin/config/system/mailsystem?
I've changed "Delivery" to SmtpMailSystem, and it worked.

**Comment by Mchampsee** [comment]
@ivyguo518 - That was it..thanks!

**Comment by pirog** [comment]
@labboy0276, before we implement something like mailhog, can you confirm that this solution works for some of your sites?
