### ISSUE TITLE
Kbox git support for editors?

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#488]
Trying to squash a few commits together, I get the following error:

```
$ kbox git rebase -i
/usr/lib/git-core/git-rebase: 1: eval: editor: not found
```

**Comment by pirog** [comment]
oh weird... you should have `vim` in that container? Im *pretty sure* ive gotten vim to pop up for merges but maybe not. 

Anyway you can verify that `vim` or `nano` is not installed in the git container?

**Comment by labboy0276** [comment]
+1 still can't do kbox git --amend and thingz like that

**Comment by pirog** [comment]
For the same reason as @madeofpeople ?

**Comment by madeofpeople** [comment]
i tried terminalling in, set my default editor to pico, and still got that error from inside the container.

**Comment by pirog** [comment]
Ok good to know. It sounds like ill probably be able to replicate this so i
can slot it for our next release. Moving to a 1 or 2 week release cycle
after we drop the big 0.10.0 and of course if you are running off the git
branch you might be able to just pull the fix immediately.

On Fri, Sep 18, 2015 at 1:55 PM, Thiago de Mello Bueno <
notifications@github.com> wrote:

> i tried terminalling in, set my default editor to pico, and still got that
> error from inside the container.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/488#issuecomment-141567004>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
So i think the issue here was we just didnt properly update our base debian container to include an editor. We changed the code but never rolled a new image. Rolling a new image now but docker is taking 4eva. Hopefully that is all we need to do!

**Comment by pirog** [comment]
so i think new apps should have the editor in them, and on old apps a `kbox rebuild` will grab the new git container

**Comment by bradchesney79** [comment]
Sorry to hit on a closed bug-- but the linux container still doesn't have vi, vim, nano, or pico.

For Debian, main doesn't include the 3rd party editors like vim, nano, or pico-- and TIL it doesn't seem to include plain vi either.

We have options. Adding Debian backports allows for vim to be installed. Pico is not a thing anymore, but installing nano seems to give you access to opening nano by executing the pico alias.

```
cp /etc/apt/sources.list /etc/apt/sources.list.bak
echo "deb http://httpredir.debian.org/debian jessie main" > /etc/apt/sources.list
echo "deb http://httpredir.debian.org/debian jessie-updates main" >> /etc/apt/sources.list
echo "deb http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list
apt-get install vim
```
