### ISSUE TITLE
Figure out how to get windosu to be blocking without ending the process

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#490]
Currently if the user waits to long to accept the UAC prompt it can cause the installer to fail because the installer is still running onto things that require this be done first.

**Comment by pirog** [comment]
It also might be worth moving all windosu logic into core so all the things can use it and have it work reliably. Right now both `kalabox-engine-docker` and `kalabox-services-kalabox` implement it in basically the same way.

**Comment by bcauldwell** [comment]
+1 Great idea, I will make that happen!

On Tue, Sep 22, 2015 at 3:19 PM, Mike Pirog <notifications@github.com>
wrote:

> It also might be worth moving all windosu logic into core so all the
> things can use it and have it work reliably. Right now both
> kalabox-engine-docker and kalabox-services-kalabox implement it in
> basically the same way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/490#issuecomment-142438044>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
I can get you setup on this issue when you are back in the office tomorrow.

On Wednesday, September 23, 2015, bcauldwell <notifications@github.com>
wrote:

> +1 Great idea, I will make that happen!
>
> On Tue, Sep 22, 2015 at 3:19 PM, Mike Pirog <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > It also might be worth moving all windosu logic into core so all the
> > things can use it and have it work reliably. Right now both
> > kalabox-engine-docker and kalabox-services-kalabox implement it in
> > basically the same way.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/490#issuecomment-142438044>.
> >
>
>
>
> --
> - Benjamin Cauldwell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/490#issuecomment-142645263>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
