### ISSUE TITLE
Trusty install issue- weird error

### ISSUE THREAD

**Issue by devekko** [kalabox/kalabox#496]
sorry, have had a chance to search through issues, this might be a dupe

did this

  173  sudo apt-get install nodejs
  174  sudo apt-get install npm
  175  npm install kalabox -g
  176  sudo npm install kalabox -g

then 

npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-2.0.9.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-2.0.9.tgz

> kerberos@0.0.14 install /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-28-lowlatency
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
/usr/local/bin/kbox -> /usr/local/lib/node_modules/kalabox/bin/kbox.js

> kalabox@0.10.1 postinstall /usr/local/lib/node_modules/kalabox
> node ./scripts/postinstall.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127

niccolox@trustyinx:~/Projects|⇒  uname -a
Linux trustyinx.devekko.net 3.19.0-28-lowlatency #30~14.04.1-Ubuntu SMP PREEMPT Tue Sep 1 10:24:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by labboy0276** [comment]
Hello,

I would try installing the binary version.  Put it in the /usr/local/bin,
remove the old kalabox first if it is installed via the script.

Also you shouldn't use sudo to install kalabox.  I would run this:
https://github.com/mattgrill/NPM-Doctor

If you want to use the node version.

On Mon, Sep 21, 2015 at 12:02 AM, Nicholas Roberts <notifications@github.com
> wrote:

> sorry, have had a chance to search through issues, this might be a dupe
>
> did this
>
> 173 sudo apt-get install nodejs
> 174 sudo apt-get install npm
> 175 npm install kalabox -g
> 176 sudo npm install kalabox -g
>
> then
>
> npm http 200 https://registry.npmjs.org/nan
> npm http GET https://registry.npmjs.org/nan/-/nan-2.0.9.tgz
> npm http 200 https://registry.npmjs.org/nan/-/nan-2.0.9.tgz
>
> kerberos@0.0.14 install
> /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)
>
> /bin/sh: 1: node: not found
> gyp: Call to 'node -e "require('nan')"' returned exit status 127. while
> trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: gyp failed with exit code: 1
> gyp ERR! stack at ChildProcess.onCpExit
> (/usr/share/node-gyp/lib/configure.js:431:16)
> gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack at Process.ChildProcess._handle.onexit
> (child_process.js:797:12)
> gyp ERR! System Linux 3.19.0-28-lowlatency
> gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd
> /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> gyp ERR! node -v v0.10.25
> gyp ERR! node-gyp -v v0.10.10
> gyp ERR! not ok
> /usr/local/bin/kbox -> /usr/local/lib/node_modules/kalabox/bin/kbox.js
>
> kalabox@0.10.1 postinstall /usr/local/lib/node_modules/kalabox
> node ./scripts/postinstall.js
>
> sh: 1: node: not found
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>
> npm ERR! weird error 127
>
> niccolox@trustyinx:~/Projects|⇒ uname -a
> Linux trustyinx.devekko.net 3.19.0-28-lowlatency #30
> <https://github.com/kalabox/kalabox/pull/30>~14.04.1-Ubuntu SMP PREEMPT
> Tue Sep 1 10:24:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/496>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by devekko** [comment]
I tried to install kalabox without sudo and it gave errors much earlier in install process (sorry, rebooted), so I forced it with sudo and got a lot further but still errors

binary, yep, that worked

**Comment by devekko** [comment]
actually, ran npmdoctor as suggested, which didnt work

had to manually link nodejs to node 

http://stackoverflow.com/questions/20886217/browserify-error-usr-bin-env-node-no-such-file-or-directory

  195  sudo npmdoctor -u niccolox
  196  sudo ln -s /usr/bin/nodejs /usr/bin/node
  197  sudo npmdoctor -u niccolox
  
then ran with npm again and this time it got the precisely the same error as above

198  npm install kalabox -g


npm http 304 https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/nan

> kerberos@0.0.14 install /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-28-lowlatency
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! Error: EACCES, symlink '../lib/node_modules/kalabox/bin/kbox.js'
npm ERR!  { [Error: EACCES, symlink '../lib/node_modules/kalabox/bin/kbox.js']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '../lib/node_modules/kalabox/bin/kbox.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.19.0-28-lowlatency
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "kalabox" "-g"
npm ERR! cwd /home/niccolox
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../lib/node_modules/kalabox/bin/kbox.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../lib/node_modules/kalabox/bin/kbox.js'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/niccolox/npm-debug.log
npm ERR! not ok code 0


checked home/niccolox/npm-debug.log 
empty

closing

**Comment by pirog** [comment]
im not sure what trusty installs by default for node ... looks like 0.10.x which is technically supported but 0.12.x is preferred. 

Generally there can be a lot of noise installing node and npm especially if you are using `sudo` for global installation of packages. 

If you are having issues navigating this its probably best to just grab the debian kbox binary and putting it somewhere in your PATH. It's good to make sure you uninstall any previous kbox cruft you might have and to make the binary executable with `chmod +x`

**Comment by devekko** [comment]
sigh

this is what I did

173 sudo apt-get install nodejs
174 sudo apt-get install npm
175 npm install kalabox -g

FAILED

tried this

176 sudo npm install kalabox -g

FAILED

did symlink and it got the the same place and failed


I didnt install it with sudo at first, I followed your instructions, without sudo

I only tried sudo because it failed without sudo

shrugs, with or without sudo, after the manual links, it fails at the same place

the binary works but is too fat for my laptop 

I might try the binary on my dev server, probably not though, I hate Virtualbox and Vagrant

**Comment by pirog** [comment]
Yeah i dont know what to tell you. If you can't install the dependencies correctly its not going to work. It's the main reason we are shipping binaries now.

Honestly, you aren't really the target market for kalabox so im not sure how useful it will be to you.

**Comment by pirog** [comment]
And i'm with you on Vagrant. VB we don't have that much choice on.

**Comment by devekko** [comment]
ubuntu desktop is a tropical paradise very remote from the mainstream destinations
