### ISSUE TITLE
Doing a first `create` from inside of a previously installed app is BADDDDD

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#497]
Hi All,

I've tried using the binary and guide from @pirog in here: https://github.com/kalabox/kalabox/issues/495

What I get now is:

``````
$ kbox
-bash: /Users/timdaff/.node/bin/kbox: No such file or directory
``````

**Comment by pirog** [comment]
Tim you probably have another Kbox in your path, presumably from your npm
install that you'll want to get rid of first.

Where did you put the Kbox binary? If you run 'which kbox' what do you get?

On Sunday, September 20, 2015, pi-ron <notifications@github.com> wrote:

> Hi All,
>
> I've tried using the binary and guide from @pirog
> <https://github.com/pirog> in here: #495
> <https://github.com/kalabox/kalabox/issues/495>
>
> What I get now is:
>
> $ kbox
> -bash: /Users/timdaff/.node/bin/kbox: No such file or directory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/497>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
$ which kbox give me nothing

**Comment by pi-ron** [comment]
``````
$ echo $PATH
/Users/timdaff/.rvm/gems/ruby-2.0.0-p247/bin:/Users/timdaff/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/timdaff/.rvm/rubies/ruby-2.0.0-p247/bin:/Applications/MAMP/bin/php/php5.5.10/bin:/Users/timdaff/.node/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/timdaff/.rvm/bin
``````

**Comment by pirog** [comment]
Then that definitely explains your issue. Run 'env' and look for the path
variable. You will want to put the kbox binary in one of those locations.
You will also need to make sure it is executable.

On Sunday, September 20, 2015, pi-ron <notifications@github.com> wrote:

> $ which kbox give me nothing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/497#issuecomment-141881752>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
``````
$ which kbox
Tims-iMac:Sites timdaff$
``````

**Comment by pi-ron** [comment]
so `nano $PATH` ?

**Comment by pi-ron** [comment]
or `export $PATH=/user/local/bin/kbox` ?

**Comment by pi-ron** [comment]
*usr

**Comment by pi-ron** [comment]
``````
$ export PATH=/usr/local/bin/kbox
Tims-iMac:Sites timdaff$ kbox
-bash: kbox: command not found
``````

**Comment by pirog** [comment]
I'm not sure what you are asking.

Just download the kbox bin and move it into path that exists in the $PATH
environmental variable. Make sure you run chmod +x on it so it is
executable

On Sunday, September 20, 2015, pi-ron <notifications@github.com> wrote:

> *usr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/497#issuecomment-141882109>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
Got it :-)

**Comment by pi-ron** [comment]
Whoop!

**Comment by pi-ron** [comment]
Thanks Mike.

**Comment by pirog** [comment]
nice! success?

**Comment by pirog** [comment]
Also, generally it can be really bad to modify your PATH variable with `export` so you might want to kill whatever process you did that with and start anew.

**Comment by pi-ron** [comment]
Yeh I cooked it @pirog Managed to repair though, thanks.

**Comment by pi-ron** [comment]
Yep just running through the installer now.

**Comment by pirog** [comment]
awesome! by installer i mean you tried to create a pantheon app and it
prompted you to provision?

On Sun, Sep 20, 2015 at 11:12 PM, pi-ron <notifications@github.com> wrote:

> Yep just running through the installer now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/497#issuecomment-141884828>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
Yup, it prompted 'This is your first kalabox command' or similar.

**Comment by pirog** [comment]
sweet!

let us know how it goes!

On Sun, Sep 20, 2015 at 11:14 PM, pi-ron <notifications@github.com> wrote:

> Yup, it prompted 'This is your first kalabox command' or similar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/497#issuecomment-141885139>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
Roger

**Comment by pi-ron** [comment]
No fibre at home, things are a little slower installing!

**Comment by pirog** [comment]
first create can take a sec since it is doing the old `kbox provision` plus the actual installation of your app. That said this seemed like a better and less confusing user experience for people. One of the goals of 0.10.x was to get rid of as many "potentially confusing" commands as possible. 

When you have `kbox provision`, `kbox up`, `kbox down`, `kbox start` and `kbox stop` all in the same CLI it can be hard to manage the context. Hopefully now the context is generally the `app` context vs the `vm` context of the `global` context.

**Comment by pi-ron** [comment]
Hmmmmmmm Bugger!
Reached step 21/22 and got:

``````
info: -- Step 21/22 --
info: Creating services...
info: VError: Error rebuilding services.: Error rebuilding service "{"name":"skydns","srcRoot":"/usr/local/bin/node_modules/kalabox-services-kalabox","createOpts":{"name":"kalabox_skydns","HostConfig":{"NetworkMode":"bridge","PortBindings":{"53/udp":[{"HostIp":"172.17.42.1","HostPort":"53"}]}},"Image":"skydns","Cmd":["-nameserver","8.8.8.8:53","-domain","kbox"],"Env":["KBOX_CODEDIR=code","KALABOX=true","APPNAME=woolamai-beach-house","APPDOMAIN=woolamai-beach-house.kbox","FRAMEWORK=drupal","DOCROOT=/","FILEMOUNT=sites/default/files","DRUPAL_HASH_SALT=b21cfbfab3b77eb16d032038d2c8816d0038d2d6358690d8e414dffd1d5bcb81","DB_HOST=woolamai-beach-house.kbox","DB_PORT=3306","DB_USER=pantheon","DB_PASSWORD=","DB_NAME=pantheon","PANTHEON_SITE=UUID","PANTHEON_SITE_NAME=woolamai-beach-house","PANTHEON_ENVIRONMENT=kalabox","PANTHEON_INFRASTRUCTURE_ENVIRONMENT=kalabox","PRESSFLOW_SETTINGS={\"databases\":{\"default\":{\"default\":{\"driver\":\"mysql\",\"prefix\":\"\",\"database\":\"pantheon\",\"username\":\"pantheon\",\"password\":\"\",\"host\":\"woolamai-beach-house.kbox\",\"port\":3306}}},\"conf\":{\"pressflow_smart_start\":true,\"pantheon_binding\":\"kalabox\",\"pantheon_site_uuid\":\"kalabox\",\"pantheon_environment\":\"kalabox\",\"pantheon_tier\":\"kalabox\",\"pantheon_index_host\":\"solr.woolamai-beach-house.kbox\",\"pantheon_index_port\":449,\"redis_client_host\":\"redis.woolamai-beach-house.kbox\",\"redis_client_port\":8161,\"redis_client_password\":\"\",\"file_public_path\":\"sites/default/files\",\"file_private_path\":\"sites/default/files/private\",\"file_directory_path\":\"site/default/files\",\"file_temporary_path\":\"/tmp\",\"file_directory_temp\":\"/tmp\",\"css_gzip_compression\":false,\"js_gzip_compression\":false,\"page_compression\":false},\"drupal_hash_salt\":\"b21cfbfab3b77eb16d032038d2c8816d0038d2d6358690d8e414dffd1d5bcb81\",\"config_directory_name\":\"config\"}","CACHE_HOST=redis.woolamai-beach-house.kbox","CACHE_PORT=8161","CACHE_PASSWORD=","PANTHEON_INDEX_HOST=solr.woolamai-beach-house.kbox","PANTHEON_INDEX_PORT=449","PHP_VERSION=5.3.29","SSH_KEY=pantheon.kalabox.id_rsa"]},"postProviderOpts":"getSkydnsPostProviderOpts","startOpts":{}}".: Cannot read property 'email' of undefined
info: -- INSTALL FAILURE. --
``````

**Comment by pirog** [comment]
@pi-ron it looks to me like you didnt uninstall kalabox before trying out the new stuff?

**Comment by pi-ron** [comment]
I def. ran it earlier today

Should I try again?

**Comment by pirog** [comment]
If you ran it you should be good. Are you trying to install from a previously installed and created app?

**Comment by pi-ron** [comment]
Yeh I'm in the app's old folder
Should I try outside?

**Comment by pi-ron** [comment]
Trying...

**Comment by pirog** [comment]
Yeah i *think* that is your issue and is cause for us to reopen this.

**Comment by pi-ron** [comment]
Huzzah victory

**Comment by pirog** [comment]
HUZZAH!

**Comment by pi-ron** [comment]
I'll just delete that old app

Will `kbox destroy` do that magic or will that only work for 0.10.x created apps?

**Comment by pirog** [comment]
since you uninstalled everything you can just remove that entire directory normally.

**Comment by pirog** [comment]
by normally i mean delete it like you would delete anything else on your filesystem.

**Comment by pi-ron** [comment]
Ok done that, just trying to create under a new namespace anyway.

**Comment by pi-ron** [comment]
:-(

**Comment by pi-ron** [comment]
``````
Building your app...
info: BOOT2DOCKER =>  Starting up. maxRetries=3, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Bringing boot2docker up [1].
info: BOOT2DOCKER =>  Boot2docker is up.
Kalabox engine has been activated.
Tried to register a dependency "appConfig" that was already registered.
Error: Tried to register a dependency "appConfig" that was already registered.
    at Object.exports.register (/usr/local/bin/lib/core/deps.js.jx:96:11)
    at Object.<anonymous> (/usr/local/bin/lib/create.js.jx:361:26)
From previous event:
    at /usr/local/bin/lib/create.js.jx:359:8
    at process._tickCallback (node.js:812:13)
From previous event:
    at createApp (/usr/local/bin/lib/create.js.jx:349:6)
    at PromptUI.completed (/usr/local/bin/lib/create.js.jx:475:18)
    at PromptUI.onCompletion (/usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1792:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AnonymousObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at InnerObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:3424:65)
    at InnerObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at AutoDetachObserver.tryCatcher (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:566:29)
    at AutoDetachObserverPrototype.completed (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:5287:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/bin/node_modules/inquirer/node_modules/rx/dist/rx.js.jx:1729:14)
    at /usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:52:13
    at /usr/local/bin/node_modules/lodash/index.js.jx:7172:25
    at /usr/local/bin/node_modules/inquirer/lib/ui/prompt.js.jx:97:7
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
    at Prompt.done (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:71:10)
    at Prompt.<anonymous> (/usr/local/bin/node_modules/inquirer/lib/prompts/input.js.jx:89:10)
    at Object.utils.runAsync (/usr/local/bin/node_modules/inquirer/lib/utils/utils.js.jx:36:5)
    at Prompt.filter (/usr/local/bin/node_modules/inquirer/lib/prompts/base.js.jx:183:9)
``````

**Comment by pi-ron** [comment]
Should I ssh into docker to check for old containers?

**Comment by pi-ron** [comment]
Hm nothing there either

**Comment by pirog** [comment]
i think your safest bet is probably to just uninstall kalabox. remove any old apps you might have. then run `create` from a "clean" directory.

another alternative is to manually edit or delete the `~/.kalabox/appRegistry.json` file to clear out any lingering apps.

**Comment by pi-ron** [comment]
Nothing in ~/.kalabox/appRegistry.json

**Comment by pirog** [comment]
im on the IRC if you want to try that instead
