### ISSUE TITLE
Drop use of boot2docker

### ISSUE THREAD

**Issue by rcross** [kalabox/kalabox#499]
So, boot2docker is deprecated as of Docker v1.8 

I assume kalabox will also be dropping it?

**Comment by pirog** [comment]
eventually! the plan is to eventually switch stuff to docker-machine but for the immediate and medium term rolling with B2D is not a huge issue.

**Comment by skenley** [comment]
So, when running kbox update, and I get a handful of warnings and errors about B2D, I can just ignore those? Every time I pull down a site from Pantheon, I'm asked to update and then I get these errors and finally a message saying -- INSTALL FAILURE --

**Comment by pirog** [comment]
Can you post the errors you are getting during update? Run the update with `kbox update -- -v` so we can get verbose output.

**Comment by skenley** [comment]
Mike,

Here is the complete output after running kbox update — -v.

Steves-MacBook-Pro:Desktop stevekenley$ kbox update -- -v
debug: ENGINE =>  Initializing engine.
debug: ENGINE =>  Engine initialized.
debug: DISCO => App registry does NOT contain appDirs property!
debug: DISCO => AppsRegistry dirs.
debug: [1:19] Starting core-auth
debug: description => Authorizing trilling subroutines...
debug: dependencies => 
info: -- Step 1/19 --
info: Authorizing trilling subroutines...
info: Non-interactive mode.
debug: USER INPUT => {}
debug: Finished core-auth (10)
info: -- OK! 5% complete! --

debug: [2:19] Starting syncthing-image
debug: description => Adding syncthing image to build list...
debug: dependencies => 
info: -- Step 2/19 --
info: Adding syncthing image to build list...
debug: Finished syncthing-image (0)
info: -- OK! 11% complete! --

debug: [3:19] Starting syncthing-downloads
debug: description => Queuing up syncthing downloads...
debug: dependencies => 
info: -- Step 3/19 --
info: Queuing up syncthing downloads...
debug: Finished syncthing-downloads (4)
info: -- OK! 16% complete! --

debug: [4:19] Starting core-firewall
debug: description => Checking firewall settings...
debug: dependencies => 
info: -- Step 4/19 --
info: Checking firewall settings...
debug: Finished core-firewall (52)
info: -- OK! 21% complete! --

debug: [5:19] Starting services-kalabox-install
debug: description => Adding services images to build list...
debug: dependencies => 
info: -- Step 5/19 --
info: Adding services images to build list...
debug: Finished services-kalabox-install (2)
info: -- OK! 26% complete! --

debug: [6:19] Starting engine-docker-install-engine
debug: description => Queuing provider admin commands...
debug: dependencies => 
info: -- Step 6/19 --
info: Queuing provider admin commands...
debug: Finished engine-docker-install-engine (270)
info: -- OK! 32% complete! --

debug: [7:19] Starting engine-docker-downloads
debug: description => Queuing up provider downloads...
debug: dependencies => 
info: -- Step 7/19 --
info: Queuing up provider downloads...
debug: Finished engine-docker-downloads (4)
info: -- OK! 37% complete! --

debug: [8:19] Starting core-disk-space
debug: description => Checking for available disk space...
debug: dependencies => 
info: -- Step 8/19 --
info: Checking for available disk space...
debug: Finished core-disk-space (16)
info: -- OK! 42% complete! --

debug: [9:19] Starting core-internet
debug: description => Checking for Internet access...
debug: dependencies => core-firewall
info: -- Step 9/19 --
info: Checking for Internet access...
debug: Checking: www.google.com
debug: Finished core-internet (40)
info: -- OK! 47% complete! --

debug: [10:19] Starting core-downloads
debug: description => Downloading files...
debug: dependencies => core-internet, core-disk-space, engine-docker-downloads, syncthing-downloads
info: -- Step 10/19 --
info: Downloading files...
debug: Finished core-downloads (345)
info: -- OK! 53% complete! --

debug: [11:19] Starting core-run-admin-commands
debug: description => Running admin install commands...
debug: dependencies => core-downloads, engine-docker-install-engine
info: -- Step 11/19 --
info: Running admin install commands...
debug: Finished core-run-admin-commands (3)
info: -- OK! 58% complete! --

debug: [12:19] Starting engine-docker-verify-admin
debug: description => Updating install info...
debug: dependencies => core-run-admin-commands
info: -- Step 12/19 --
info: Updating install info...
debug: Finished engine-docker-verify-admin (7)
info: -- OK! 63% complete! --

debug: [13:19] Starting engine-up
debug: description => Setting up and activating the engine...
debug: dependencies => engine-docker-verify-admin, core-disk-space
info: -- Step 13/19 --
info: Setting up and activating the engine...
debug: DOCKER =>  Initializing provider.
debug: DOCKER =>  Provider initialized.
info: BOOT2DOCKER =>  Starting up. disksize=115670, max=3
debug: EVENTS =>  Emitting event [pre-up].
debug: EVENTS =>  No listeners [pre-up].
debug: EVENTS =>  Finished dispatching event listeners [pre-up].
info: BOOT2DOCKER =>  Initializing boot2docker [1].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=--disksize=115670, 2=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,--disksize=115670,init". Error: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/lib/util/shell.js.jx:105:13
    at /usr/local/bin/node_modules/shelljs/src/exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:15)
    at maybeClose (child_process.js:771:16)
    at Socket.<anonymous> (child_process.js:994:11)
    at Socket.emit (events.js:82:15)
    at Pipe.close (net.js:424:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,--disksize=115670,init".: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:189:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:187:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:284:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:316:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at module.exports (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
    at Promise.try.then.then.then.shareCmd (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:306:14)
From previous event:
    at Object.up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:305:6)
From previous event:
    at /usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:248:39
From previous event:
    at step.all (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:247:8)
    at /usr/local/bin/lib/install/framework.js.jx:452:17
    at /usr/local/bin/lib/install/framework.js.jx:450:30
From previous event:
    at Promise.each.then.events.emit.state (/usr/local/bin/lib/install/framework.js.jx:442:29)
From previous event:
    at /usr/local/bin/lib/install/framework.js.jx:432:22
    at Object.exports.run (/usr/local/bin/lib/install.js.jx:172:10)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/update.js.jx:16:24)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:173:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:236:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:235:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:244:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
info: BOOT2DOCKER =>  Initializing boot2docker [2].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=--disksize=115670, 2=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,--disksize=115670,init". Error: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/lib/util/shell.js.jx:105:13
    at /usr/local/bin/node_modules/shelljs/src/exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:15)
    at maybeClose (child_process.js:771:16)
    at Socket.<anonymous> (child_process.js:994:11)
    at Socket.emit (events.js:82:15)
    at Pipe.close (net.js:424:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,--disksize=115670,init".: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:189:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:187:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:284:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:316:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: BOOT2DOCKER =>  Initializing boot2docker [3].
debug: BOOT2DOCKER =>  Executing command. 0=boot2docker, 1=--disksize=115670, 2=init
debug: BOOT2DOCKER =>  Error running command "boot2docker,--disksize=115670,init". Error: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/lib/util/shell.js.jx:105:13
    at /usr/local/bin/node_modules/shelljs/src/exec.js.jx:106:7
    at ChildProcess.exithandler (child_process.js:669:7)
    at ChildProcess.emit (events.js:85:15)
    at maybeClose (child_process.js:771:16)
    at Socket.<anonymous> (child_process.js:994:11)
    at Socket.emit (events.js:82:15)
    at Pipe.close (net.js:424:12)
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "boot2docker,--disksize=115670,init".: code: 1, msg: 
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.

error in run: Failed to initialize machine "Kalabox2": exit status 1

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:189:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:187:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:284:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:316:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
info: -- INSTALL FAILURE. --
Steves-MacBook-Pro:Desktop stevekenley$ 


Thanks!

Steve Kenley | Developer/Support
tributemedia
 a web design & marketing agency

208.489.0062
136 East Idaho Avenue Ste. 100 Meridian, Idaho 83642
www.tributemedia.com

On Oct 5, 2015, at 12:48 PM, Mike Pirog <notifications@github.com> wrote:

Can you post the errors you are getting during update? Run the update with kbox update -- -v so we can get verbose output.

**Comment by pirog** [comment]
@skenley very helpful.

can you open up your virtualbox gui and report what you see in there? specifically is there a kalabox2 VM? does it show up as aborted/stopped? 

what version are you updating from? we currently only support updating from 0.10.x to another 0.10.y. If you are pre-0.10.x we recommend you [uninstall](https://github.com/kalabox/kalabox/wiki/Uninstalling-Kalabox) first and then following the install instruction on the readme.

**Comment by skenley** [comment]
Mike,

You’ll have to excuse my newbyness, I’ve not used VMs much, but here is what I found in the virtual box gui:

Runtime error opening '/Users/tmintern1/VirtualBox VMs/vagrant_vm_default_1389941954296_82141/vagrant_vm_default_1389941954296_82141.vbox' for reading: -102(File not found.).

/Users/vbox/tinderbox/mac-rel/src/VBox/Main/src-server/MachineImpl.cpp[736] (nsresult Machine::i_registeredInit()).

Result Code:
NS_ERROR_FAILURE (0x80004005)
Component:
MachineWrap
Interface:
IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}


Obviously, I’ve goofed something up.


Steve Kenley | Developer/Support
tributemedia
 a web design & marketing agency

208.489.0062
136 East Idaho Avenue Ste. 100 Meridian, Idaho 83642
www.tributemedia.com

On Oct 5, 2015, at 1:23 PM, Mike Pirog <notifications@github.com> wrote:

@skenley very helpful.

can you open up your virtualbox gui and report what you see in there? specifically is there a kalabox2 VM? does it show up as aborted/stopped?

what version are you updating from? we currently only support updating from 0.10.x to another 0.10.y. If you are pre-0.10.x we recommend you uninstall first and then following the install instruction on the readme.

**Comment by pirog** [comment]
Interesting. It looks like you might have a corrupted install from a previous non-Kalabox VM. Looks like something installed via vagrant?

**Comment by skenley** [comment]
Yeah, I actually noticed, right after I replied to you, that the path to the VB is from my old computer. I recently got a new computer and just copied everything over, so it must have gotten confused during the transfer. Any idea how to remove that and start over?

Thanks for your help!

Steve Kenley | Developer/Support
tributemedia
 a web design & marketing agency

208.489.0062
136 East Idaho Avenue Ste. 100 Meridian, Idaho 83642
www.tributemedia.com

On Oct 5, 2015, at 1:50 PM, Mike Pirog <notifications@github.com> wrote:

Interesting. It looks like you might have a corrupted install from a previous non-Kalabox VM. Looks like something installed via vagrant?

**Comment by pirog** [comment]
Hard to say for sure without knowing exactly what you did but i feel like uninstalling virtualbox is probably a good first step!

**Comment by skenley** [comment]
Ok, looks like I was able to uninstall it. So, do I need to just re-install virtualbox, or do I need to install something specific for kbox?


Steve Kenley | Developer/Support
tributemedia
 a web design & marketing agency

208.489.0062
136 East Idaho Avenue Ste. 100 Meridian, Idaho 83642
www.tributemedia.com

On Oct 5, 2015, at 2:04 PM, Mike Pirog <notifications@github.com> wrote:

Hard to say for sure without knowing exactly what you did but i feel like uninstalling virtualbox is probably a good first step!

**Comment by pirog** [comment]
You should just be able to install the normal kalabox install instructions,
we will install all the dependencies for you.

that said i would open up your VB gui again one more time to verify you've
cleared out that previous error.

On Mon, Oct 5, 2015 at 1:24 PM, Steve <notifications@github.com> wrote:

> Ok, looks like I was able to uninstall it. So, do I need to just
> re-install virtualbox, or do I need to install something specific for kbox?
>
>
> Steve Kenley | Developer/Support
> tributemedia
> a web design & marketing agency
>
> 208.489.0062
> 136 East Idaho Avenue Ste. 100 Meridian, Idaho 83642
> www.tributemedia.com
>
> On Oct 5, 2015, at 2:04 PM, Mike Pirog <notifications@github.com> wrote:
>
> Hard to say for sure without knowing exactly what you did but i feel like
> uninstalling virtualbox is probably a good first step!
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/499#issuecomment-145656854>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
