### ISSUE TITLE
Binary Install error on b2d step

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#500]
Hello,

It still installs, but I am seeing this on Ubuntu 14.04:

Looks like a perm issue, but that is odd since this never happened pre-0.10.x, pre-binary actually.

```
info: -- Step 18/24 --
info: Setting up and activating the engine...
info: BOOT2DOCKER =>  Starting up. max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/home/john/.kalabox/bin/boot2docker,init".: code: 126, msg: /bin/sh: 1: /home/john/.kalabox/bin/boot2docker: Permission denied

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:190:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:188:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:285:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:317:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at module.exports (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
    at Promise.try.then.then.then.shareCmd (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:307:14)
From previous event:
    at Object.up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:306:6)
From previous event:
    at step.all (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:221:30)
    at /usr/local/bin/lib/install/framework.js.jx:452:17
    at /usr/local/bin/lib/install/framework.js.jx:450:30
From previous event:
    at Promise.each.then.events.emit.state (/usr/local/bin/lib/install/framework.js.jx:442:29)
From previous event:
    at /usr/local/bin/lib/install/framework.js.jx:432:22
    at Object.exports.run (/usr/local/bin/lib/install.js.jx:172:10)
    at /usr/local/bin/lib/engine.js.jx:127:26
From previous event:
    at verifyProviderInstalled (/usr/local/bin/lib/engine.js.jx:123:6)
    at Object.exports.up (/usr/local/bin/lib/engine.js.jx:157:10)
    at Object.task.func (/usr/local/bin/node_modules/kalabox-engine-docker/lib/tasks.js.jx:23:14)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:229:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:228:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:237:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
info: BOOT2DOCKER =>  Initializing boot2docker [2].
```

**Comment by pirog** [comment]
This isn't an error

On Monday, September 21, 2015, John Ouellet <notifications@github.com>
wrote:

> Hello,
>
> It still installs, but I am seeing this on Ubuntu 14.04:
>
> Looks like a perm issue, but that is odd since this never happened
> pre-0.10.x, pre-binary actually.
>
> info: -- Step 18/24 --
> info: Setting up and activating the engine...
> info: BOOT2DOCKER =>  Starting up. max=3
> info: BOOT2DOCKER =>  Initializing boot2docker [1].
> info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/home/john/.kalabox/bin/boot2docker,init".: code: 126, msg: /bin/sh: 1: /home/john/.kalabox/bin/boot2docker: Permission denied
>
>     at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:190:13
> From previous event:
>     at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:188:11)
>     at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:285:12)
>     at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:317:16
>     at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
>     at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
>     at module.exports (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
>     at Promise.try.then.then.then.shareCmd (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:307:14)
> From previous event:
>     at Object.up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:306:6)
> From previous event:
>     at step.all (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:221:30)
>     at /usr/local/bin/lib/install/framework.js.jx:452:17
>     at /usr/local/bin/lib/install/framework.js.jx:450:30
> From previous event:
>     at Promise.each.then.events.emit.state (/usr/local/bin/lib/install/framework.js.jx:442:29)
> From previous event:
>     at /usr/local/bin/lib/install/framework.js.jx:432:22
>     at Object.exports.run (/usr/local/bin/lib/install.js.jx:172:10)
>     at /usr/local/bin/lib/engine.js.jx:127:26
> From previous event:
>     at verifyProviderInstalled (/usr/local/bin/lib/engine.js.jx:123:6)
>     at Object.exports.up (/usr/local/bin/lib/engine.js.jx:157:10)
>     at Object.task.func (/usr/local/bin/node_modules/kalabox-engine-docker/lib/tasks.js.jx:23:14)
>     at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
>     at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:229:12)
>     at process._tickCallback (node.js:812:13)
> From previous event:
>     at main (/usr/local/bin/bin/kbox.js.jx:228:4)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:237:1)
>     at Module._compile (module.js:518:26)
>     at readX (module.js:1284:5)
>     at Object.Module._extensions..jx (module.js:1711:10)
>     at Module.load (module.js:345:36)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:377:17)
>     at require (module.js:395:17)
>     at Object.<anonymous> (_jx_source:17:3)
>     at Module._compile (module.js:518:26)
>     at Module.load (module.js:353:12)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:733:12)
>     at startup (node.js:371:18)
>     at node.js:1464:3
> info: BOOT2DOCKER =>  Initializing boot2docker [2].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/500>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
what is it then?

On Mon, Sep 21, 2015 at 12:40 PM, Mike Pirog <notifications@github.com>
wrote:

> This isn't an error
>
> On Monday, September 21, 2015, John Ouellet <notifications@github.com>
> wrote:
>
> > Hello,
> >
> > It still installs, but I am seeing this on Ubuntu 14.04:
> >
> > Looks like a perm issue, but that is odd since this never happened
> > pre-0.10.x, pre-binary actually.
> >
> > info: -- Step 18/24 --
> > info: Setting up and activating the engine...
> > info: BOOT2DOCKER => Starting up. max=3
> > info: BOOT2DOCKER => Initializing boot2docker [1].
> > info: BOOT2DOCKER => Initializing boot2docker failed, retrying. VError:
> Error running command "/home/john/.kalabox/bin/boot2docker,init".: code:
> 126, msg: /bin/sh: 1: /home/john/.kalabox/bin/boot2docker: Permission denied
> >
> > at
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:190:13
> > From previous event:
> > at sh
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:188:11)
> > at shProvider
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:285:12)
> > at
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:317:16
> > at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
> > at rec
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
> > at module.exports
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
> > at Promise.try.then.then.then.shareCmd
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:307:14)
> > From previous event:
> > at Object.up
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:306:6)
> > From previous event:
> > at step.all
> (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:221:30)
> > at /usr/local/bin/lib/install/framework.js.jx:452:17
> > at /usr/local/bin/lib/install/framework.js.jx:450:30
> > From previous event:
> > at Promise.each.then.events.emit.state
> (/usr/local/bin/lib/install/framework.js.jx:442:29)
> > From previous event:
> > at /usr/local/bin/lib/install/framework.js.jx:432:22
> > at Object.exports.run (/usr/local/bin/lib/install.js.jx:172:10)
> > at /usr/local/bin/lib/engine.js.jx:127:26
> > From previous event:
> > at verifyProviderInstalled (/usr/local/bin/lib/engine.js.jx:123:6)
> > at Object.exports.up (/usr/local/bin/lib/engine.js.jx:157:10)
> > at Object.task.func
> (/usr/local/bin/node_modules/kalabox-engine-docker/lib/tasks.js.jx:23:14)
> > at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
> > at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
> > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:229:12)
> > at process._tickCallback (node.js:812:13)
> > From previous event:
> > at main (/usr/local/bin/bin/kbox.js.jx:228:4)
> > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:237:1)
> > at Module._compile (module.js:518:26)
> > at readX (module.js:1284:5)
> > at Object.Module._extensions..jx (module.js:1711:10)
> > at Module.load (module.js:345:36)
> > at Function.Module._load (module.js:312:12)
> > at Module.require (module.js:377:17)
> > at require (module.js:395:17)
> > at Object.<anonymous> (_jx_source:17:3)
> > at Module._compile (module.js:518:26)
> > at Module.load (module.js:353:12)
> > at Function.Module._load (module.js:312:12)
> > at Function.Module.runMain (module.js:733:12)
> > at startup (node.js:371:18)
> > at node.js:1464:3
> > info: BOOT2DOCKER => Initializing boot2docker [2].
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/500>.
> >
>
>
> --
>
> Mike
>
> --
> Mike Pirog
> Co-Founder, Products
> http://kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/500#issuecomment-142037710>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
retry events failing that show up in teh debug log because you are in
verbose mode

On Mon, Sep 21, 2015 at 9:45 AM, John Ouellet <notifications@github.com>
wrote:

> what is it then?
>
> On Mon, Sep 21, 2015 at 12:40 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > This isn't an error
> >
> > On Monday, September 21, 2015, John Ouellet <notifications@github.com>
> > wrote:
> >
> > > Hello,
> > >
> > > It still installs, but I am seeing this on Ubuntu 14.04:
> > >
> > > Looks like a perm issue, but that is odd since this never happened
> > > pre-0.10.x, pre-binary actually.
> > >
> > > info: -- Step 18/24 --
> > > info: Setting up and activating the engine...
> > > info: BOOT2DOCKER => Starting up. max=3
> > > info: BOOT2DOCKER => Initializing boot2docker [1].
> > > info: BOOT2DOCKER => Initializing boot2docker failed, retrying. VError:
> > Error running command "/home/john/.kalabox/bin/boot2docker,init".: code:
> > 126, msg: /bin/sh: 1: /home/john/.kalabox/bin/boot2docker: Permission
> denied
> > >
> > > at
> >
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:190:13
> > > From previous event:
> > > at sh
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:188:11)
> > > at shProvider
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:285:12)
> > > at
> >
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:317:16
> > > at
> >
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
> > > at rec
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
> > > at module.exports
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
> > > at Promise.try.then.then.then.shareCmd
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:307:14)
> > > From previous event:
> > > at Object.up
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:306:6)
> > > From previous event:
> > > at step.all
> >
> (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:221:30)
> > > at /usr/local/bin/lib/install/framework.js.jx:452:17
> > > at /usr/local/bin/lib/install/framework.js.jx:450:30
> > > From previous event:
> > > at Promise.each.then.events.emit.state
> > (/usr/local/bin/lib/install/framework.js.jx:442:29)
> > > From previous event:
> > > at /usr/local/bin/lib/install/framework.js.jx:432:22
> > > at Object.exports.run (/usr/local/bin/lib/install.js.jx:172:10)
> > > at /usr/local/bin/lib/engine.js.jx:127:26
> > > From previous event:
> > > at verifyProviderInstalled (/usr/local/bin/lib/engine.js.jx:123:6)
> > > at Object.exports.up (/usr/local/bin/lib/engine.js.jx:157:10)
> > > at Object.task.func
> > (/usr/local/bin/node_modules/kalabox-engine-docker/lib/tasks.js.jx:23:14)
> > > at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:857:15)
> > > at processTask (/usr/local/bin/bin/kbox.js.jx:166:16)
> > > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:229:12)
> > > at process._tickCallback (node.js:812:13)
> > > From previous event:
> > > at main (/usr/local/bin/bin/kbox.js.jx:228:4)
> > > at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:237:1)
> > > at Module._compile (module.js:518:26)
> > > at readX (module.js:1284:5)
> > > at Object.Module._extensions..jx (module.js:1711:10)
> > > at Module.load (module.js:345:36)
> > > at Function.Module._load (module.js:312:12)
> > > at Module.require (module.js:377:17)
> > > at require (module.js:395:17)
> > > at Object.<anonymous> (_jx_source:17:3)
> > > at Module._compile (module.js:518:26)
> > > at Module.load (module.js:353:12)
> > > at Function.Module._load (module.js:312:12)
> > > at Function.Module.runMain (module.js:733:12)
> > > at startup (node.js:371:18)
> > > at node.js:1464:3
> > > info: BOOT2DOCKER => Initializing boot2docker [2].
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kalabox/kalabox/issues/500>.
> > >
> >
> >
> > --
> >
> > Mike
> >
> > --
> > Mike Pirog
> > Co-Founder, Products
> > http://kalamuna.com
> >
> > Stay connected with Kalamuna on: Twitter
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> > , Linkedin
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >,
> > and Facebook
> > <
> >
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/500#issuecomment-142037710>.
> >
>
>
>
> --
> *John Ouellet*
> *Sr Developer & Support Manager*
> 415-470-3076
> www.kalamuna.com
>
> Stay connected with Kalamuna on: Twitter
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
> , Linkedin
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >,
> and Facebook
> <
> http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/500#issuecomment-142038853>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
if it doesnt show up red and kill the process its not an actual error

**Comment by labboy0276** [comment]
ok, closing it out, poof
