### ISSUE TITLE
Meta issue for post-"beta" new feature requests

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#511]
1. ~~Get syncthing to start up right after `pullCode` in `kbox create` so our code directory is primed when the app completes.~~
2. ~~Re-implement NFS to handle media files only aka `sites/default/files`~~
3. ~~Figure out a way to run tooling commands faster. Maybe have all tooling containers on when we start up an app?~~
4. ~~Get `kbox start` down to less than 10 seconds~~
5. Implement a `node\npm\grunt\gulp` plugin for front end stuff. 
6. Figure out a way to go through engine-up preflight faster. 
7. Bootstrap phases and performance improvements
8. Handle concurrency better 
9. Faster first load #655 
10. Minecraft support

**Comment by bcauldwell** [comment]
In reference to #4 - Get `kbox start` down to less than 10 seconds, I have a few ideas.
1 - Don't recreate syncthing container unless a new volume has to be added, or an old volume hasn't been needed for a long time.
2 - If we do recreate syncthing container, don't wait on the syncthing instance to become responsive before continuing on.
3 - Remove or reduce the 3 second delay between containers starting. Keep the delay for services, but not for app containers.
