### ISSUE TITLE
Get `kbox pull` to do more stuff for pantheon apps

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#516]
Pre-kalabox working with Pantheon site I consistently used https://www.drupal.org/project/pandarus for quickly pulling down a live database for testing code against.

I'm finding `kbox pull` a little frustrating as you have to pull the code changes, and only from dev.

It would be great to integrate Pandarus into kalabox to allow pulling / pushing databases from Pantheon environments.

I know you have to add a file to sites code for Pandarus to work but perhaps this could be an optional part of `kbox create` or at least some instruction could be added to the installer.

Same goes for rsyncing files between Pantheon environments and local kbox env.

---

If non of that's possible, it would be great to at least have the ability to run database or file push/pull commands instead of the kitchen sink `kbox pull`.  At the moment if I want the live database I've got to clone it from live to dev, create a backup, then do `kbox pull`.

Would be great to at least automate via `kbox pull --database` that:

1. Creates latest backup #choosing to clone from live first would be a bonus
2. Pulls it down

#thoughts

**Comment by pirog** [comment]
So i've got a few thoughts on this.

* `kbox pull` will pull from whatever environment you created from. So if you created from a multidev branch it will pull from that. I think this is probably the best practice and provides good isolation. Anything you want to do that is more advanced than this is what using git directly is for.
* I think adding some more options in for `--databases` / `--files` is doable. Presumably those would be
1. Pull DB/FILES from live
2. Create new DB backup and use that

Personally i think the best practice is for you to be automating the pull down of the live database to dev and then creating a periodic backup. If you are pulling from live all the time for local dev then your dev and test instances are kind of getting left behind which can cause issues down the road. 

That said i think having commands along the lines of the two bulleted points is a fair enough. 

Would that work better for you?

**Comment by pi-ron** [comment]
Yeh the git stuff is fine, I can switch between multidevs via git no worries.  It's just more often than not I want to test against the live database.   Having the ability to pull down the live database/files would be perfect.

If you could specifiy which environment to pull database/files from then that is all good, any multidev stuff can be just done by git.

I understand pushing back up would be only to the env you created from, but that's fine.

**Comment by pirog** [comment]
Going to kick this to next week's sprint but what we are thinking is to do something like

`kbox pull -- --database --files --db-from-live --files-from-live --db-new-backup`

**Comment by pirog** [comment]
We should also allow for `--no-db`, `--no-files` options to make this truly non-interactive

**Comment by pi-ron** [comment]
I'm not sure of the work / man hours involved in these commands, so feel free to shoot me here.

It would be great to specify the environment (for database and files, not git) in the same way Terminus does.  Quite often we will pull down a db from multidev environment that has reached some stable milestone in its development, to test with local code changes to that environment. ie. we don't always want to push our local code up to multidev for testing. 

Taking inspiration from the Terminus deploy command `terminus site deploy --site=mud-pies --env=test --from=dev` or `--from=a-multidev-env`, could we do something like:

`kbox pull -- --database --db-from=live #pull latest db backup from live` 
or 
`kbox pull -- --database --db-from=live --db-new-backup #create a new db backup and pull from live`
or
`kbox pull -- --database --db-from=mudpies --db-new-backup #create a new db backup in the mudpies multidev and pull that`

Same thing would be great for files ie. 

`kbox pull -- --files --files-from=mudpies --files-new-backup #pull latest files from mudpies multidev`

`kbox pull -- --files --files-from=mudpies --files-new-backup #create a new files backup in the mudpies multidev and pull that`

**Comment by pirog** [comment]
Adding this stuff is not that tough although we are prioritizing bugs and stability improvements over features until we get to beta. 

i think most of this is really good especially with the `--no-files` and `--no-database` flags. 

All that said i think its highly unlikely we are going to let you pull db/files from a different multidev environments at this point but it might be something we add in the future. Honestly we'd like to get more input on whether this is common use case and whether this is significantly easier than just creating a new kalabox site.

**Comment by pi-ron** [comment]
Yeh that's good, I'd be happier to see more stability and less errors than these commands anyway, but good to know it may be possible down the track.

I did a kbox push today too which seemed to stall at some point and didn't throw an error.  Had to head home (being a Sunday and all), so just left it running at the office.  Will see if it got through it's thoughts or hit the wall tomorrow morning.

Re. your last para; it's more the time it takes to setup a new kalabox app for each multidev, I find it heaps easier / quicker to just setup the one kbox app based on dev, and switch multidevs via git.  Even if having to manually go to a multidev to pull the db or rarely, files.

:+1:

**Comment by pi-ron** [comment]
I may also be getting taken away from 'the machines' ie. dev work soon too.  Not sure what the men upstairs have in store for me but hopefully I'll still be in a position to push kalabox for dev ops within our org. I may go quiet, but eyes will still be on the project.

**Comment by pi-ron** [comment]
Seems to have completed, no idea why it took so long..  The only file was a small png and the code changes were already comitted and pushed.

**Comment by pirog** [comment]
Could have been funk on the pantheon end? If it was hanging during the transmission of files the likely culprits are the network or the endpoint. 

Regarding everything else: it will be sad for you to leave since you've been such a huge help across the board as we work through the really early stages of everything. Pumped you'll still be watching and an advocate though. We think after a few months of doing bug fixes and stability improvements things will be in a really good spot. PLUS work on the GUI is happening in parallel and its moving fast thanks to all the CLI groundwork.

**Comment by pi-ron** [comment]
I'll probably still be hassling you for a little while yet :-)

**Comment by pirog** [comment]
Glad to hear it! You've helped us move a lot of issues forward.
