### ISSUE TITLE
Enabling older drupal/backdrop or custom kalabox apps

### ISSUE THREAD

**Issue by tallsam** [kalabox/kalabox#517]
Installed kalabox 0.10.1 via npm, seems to be working, but I can't see the drupal apps, and even after trying to install them using npm they will not appear in `kbox create`.

Also the Drupal-related documentation has been removed from the wiki?

**Comment by tallsam** [comment]
Found 8f556a4c where Drupal was removed, I added it back in and it's broken. Perhaps not the best time to start using Kalabox?

**Comment by labboy0276** [comment]
Hello,

Right now pantheon based sites is the main focus on Kalabox.  @pirog can comment on this more in regards to why the stand alone apps were removed.

**Comment by pirog** [comment]
We don't officially support the generic Drupal app right now so YMMV. We'd
rather focus on adding specific integrations with other hosting providers
than a one-size fits all app.

Kalabox is still technically "alpha" so there are risks involved in using
it at this point. If you want to play it safe is recommend waiting till we
are at least beta. If you want to live on the wild side then jump on in :)

On Friday, September 25, 2015, John Ouellet <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Hello,
>
> Right now pantheon based sites is the main focus on Kalabox. @pirog
> <https://github.com/pirog> can comment on this more in regards to why the
> stand alone apps were removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/517#issuecomment-143209336>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by tallsam** [comment]
OK thanks for clearing that up.

**Comment by warecorp-dev** [comment]
Seems like you can still make kalabox-app-drupal working on 0.10.x. I am probably posting obvious things, but couldn't find any documentation on how to enable kalabox plugins on 0.10.x

Here is what I did: 
npm install kalabox-app-drupal
npm install kalabox-plugin-dbenv
npm install kalabox-plugin-drush
npm install kalabox-plugin-git
npm install kalabox-plugin-php
npm install kalabox-plugin-rsync
npm install lodash

Then added kalabox.json file to ~/.kalabox/ with the following contents:
```javascript
{
  "apps": [
    "kalabox-app-pantheon@0.10.2",
    "kalabox-app-drupal@0.9.3"
  ],
  "globalPlugins": [
    "kalabox-core",
    "kalabox-dev",
    "kalabox-syncthing",
    "kalabox-app-pantheon",
    "kalabox-app-drupal"
  ]
}
```
Then I've got option to create drupal app back.

**Comment by pirog** [comment]
@warecorp-dev this is more or less what you would do to enable the older drupal and backdrop apps OR YOUR OWN CUSTOM APP IF YOU WANTED TO MAKE ONE!!!

**Again, these apps are no longer officially supported at this time** but i'll keep this issue open for the more adventurous amongst us

**Comment by jdleonard** [comment]
Is this not possible with the binary?

**Comment by pirog** [comment]
you might be able to trick it with a custom system `kalabox.json` file and placing the the older/custom apps in a node_modules folder that is lateral with the binary's dir. 

i think the best flow (as of now anyway) is something like

1. install kalabox in dev mode
2. customize code with your custom apps/plugins
3. compile a binary 
4. distribute to your team

**Comment by warecorp-dev** [comment]
Steps I have outlined worked for me with the binary a month or so ago.
However, since those apps are not part of official Kbox distro anymore,
following steps mentioned by Mike should be the right way to proceed.
