### ISSUE TITLE
Sometimes pulling from docker registry things just hang for a long time

### ISSUE THREAD

**Issue by seantwalsh3** [kalabox/kalabox#518]
Uninstalled my node version to use the binary provided by the latest release, however when running kbox update I keep getting stuck when pulling kalabox/syncthing. Here's the last thing it says before it hangs.

`info: DOCKER =>  Pulling image. name=kalabox/syncthing:v0.10.0, build=false, createOpts=undefined, startOpts=undefined, postProviderOpts=undefined`

**Comment by pirog** [comment]
I've seen this a few times. Generally this seems to happen when there are
issues with the docker registry. Eventually it fixes itself and the
downloads resume.

Long term, depending on adoption, we will move to our own hosted registry
so we have more control over things.

On Friday, September 25, 2015, Sean T Walsh <notifications@github.com>
wrote:

> Uninstalled my node version to use the binary provided by the latest
> release, however when running kbox update I keep getting stuck when pulling
> kalabox/syncthing. Here's the last thing it says before it hangs.
>
> info: DOCKER => Pulling image. name=kalabox/syncthing:v0.10.0,
> build=false, createOpts=undefined, startOpts=undefined,
> postProviderOpts=undefined
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/518>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by seantwalsh3** [comment]
Thanks for the quick feedback. Will try again. *fingers crossed*

**Comment by pirog** [comment]
Sure thing.

Resetting your wifi/restarting your computer might help as a workaround for
now as well.

Would be great to figure why this happens so we can try to run a check to
correct it beforehand

On Friday, September 25, 2015, Sean T Walsh <notifications@github.com>
wrote:

> Thanks for the quick feedback. Will try again. *fingers crossed*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/518#issuecomment-143244368>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
Going to move this into the backlog

**Comment by pirog** [comment]
@bcauldwell so sometimes restarting the engine after a hang resolves this

**Comment by pirog** [comment]
I can replicate this using a VPN. 

Try to rebuild an app in one country. Stop, switch VPN to another country. HANG
