### ISSUE TITLE
Exclude aggregated css/js files and imagestyles from file sync on pulling down a site

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#527]
This may be addressed in another issue, but just noticed this was happening.

This is not something to think about immediately, but for future consideration, it may be easier/quicker to serve files from Pantheon using the https://www.drupal.org/project/stage_file_proxy module.

**Comment by pirog** [comment]
Word. The style issue is addressed in #391 so im going to close this.

Serving directly from pantheon would be sweet but not sure how we could auto-implement this? If you've got a plan for how that would be possible def open another ticket
