### ISSUE TITLE
'Could not create backup' when creating a pantheon app 

### ISSUE THREAD

**Issue by upperrapids** [kalabox/kalabox#530]
When creating a Pantheon app using v0.10, after selecting one of my existing sites and choosing the environment (dev in these tests) I'm seeing this error. 

```
Error running ad hoc container with kalabox/terminus:v0.10.0.: Non-zero exit code: 1 [2015-09-29 00:21:31] [error] Could not create backup.

Error: Non-zero exit code: 1 [2015-09-29 00:21:31] [error] Could not create backup.

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:566:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:545:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:636:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:634:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:637:27)
    at /Users/adam/Dev/my-site/plugins/kalabox-plugin-pantheon/lib/terminus.js:121:31
```

On these dev environments there were no existing backups. If I manually created a backup on Pantheon, I could run 'kbox pull' and get through the process without error. Checking Terminus outside of Kalabox, I'm able to generate backups without error.

**Comment by labboy0276** [comment]
+1 on this, I saw it last week as well. Site had no backups, kb2 failed and I went in and made one myself and then all was well.

**Comment by pirog** [comment]
@upperrapids what version of terminus are you using externally? I'm seeing https://github.com/pantheon-systems/cli/pull/532 which seems to address this in the latest 0.8.1 version of terminus. Going to try that on the kbox side, can you corroborate on the local install side?

**Comment by pirog** [comment]
Moving to 0.8.1 fixes this but opens up a bunch of other api changes we need to account for and test. Bumping this to an 8.

**Comment by pirog** [comment]
doccker registry is having chaos so this currently works with `--build-local` but not without until we can generate new images without error
