### ISSUE TITLE
kbox git status != git status (local)

### ISSUE THREAD

**Issue by jpsalter** [kalabox/kalabox#533]
Immediately after using `kbox create pantheon` to pull down a site - changing to the `{sitename}/code` directory and running `git status` yields a different result than running `kbox git status`.

`kbox git status` shows:
>On branch master
>nothing to commit (working directory clean)

but...
`git status` shows
> deleted files (module/simpletest/files/...) and 
> modified module files (these do not seem to have visible changes).

**Comment by reynoldsalec** [comment]
Had the same issue @jpsalter, guessing it's an issue with Syncthing, but if you just reset to head (git reset --hard HEAD) when you have this issue on pulling down a site it should fix things.

@pirog, perhaps this has something to do with permissions on the files? I've noticed this with files that sound the same as what @jpsalter experienced.

**Comment by jpsalter** [comment]
`git reset --hard HEAD` worked for me. Thanks!

**Comment by pirog** [comment]
Ultimately it would be great to do something like this automatically so the user has a clean slate to run both `kbox git` and their local `git` but i think we need to do some better things with syncthing first beforehand.

**Comment by jdleonard** [comment]
I've also encountered this. Most of the changes are to the file modes.

Three examples:
```
diff --git a/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_Subaccount.html b/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_Subaccount.html
old mode 100755
new mode 100644
diff --git a/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_Template.html b/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_Template.html
old mode 100755
new mode 100644
diff --git a/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_TrackingDomain.html b/sites/all/libraries/mandrill/docs/class-Mandrill_Unknown_TrackingDomain.html
old mode 100755
```

**Comment by reynoldsalec** [comment]
Is it possible that the deleted files are due to old .stignores being committed? I'm seeing an entire /files directory gone from modules/simpletest, as well as files with various file endings that are disallowed in .stignores:

```
	deleted:    modules/simpletest/files/README.txt
	deleted:    modules/simpletest/files/css_test_files/comment_hacks.css
	deleted:    modules/simpletest/files/css_test_files/comment_hacks.css.optimized.css
	deleted:    modules/simpletest/files/css_test_files/comment_hacks.css.unoptimized.css
	deleted:    modules/simpletest/files/css_test_files/css_input_with_import.css
	deleted:    modules/simpletest/files/css_test_files/css_input_with_import.css.optimized.css
	deleted:    modules/simpletest/files/css_test_files/css_input_with_import.css.unoptimized.css
	deleted:    modules/simpletest/files/css_test_files/css_input_without_import.css
	deleted:    modules/simpletest/files/css_test_files/css_input_without_import.css.optimized.css
	deleted:    modules/simpletest/files/css_test_files/css_input_without_import.css.unoptimized.css
	deleted:    modules/simpletest/files/css_test_files/css_subfolder/css_input_with_import.css
	deleted:    modules/simpletest/files/css_test_files/css_subfolder/css_input_with_import.css.optimized.css
	deleted:    modules/simpletest/files/css_test_files/css_subfolder/css_input_with_import.css.unoptimized.css
	deleted:    modules/simpletest/files/css_test_files/import1.css
	deleted:    modules/simpletest/files/css_test_files/import2.css
	deleted:    modules/simpletest/files/html-1.txt
	deleted:    modules/simpletest/files/html-2.html
	deleted:    modules/simpletest/files/image-1.png
	deleted:    modules/simpletest/files/image-2.jpg
	deleted:    modules/simpletest/files/image-test.gif
	deleted:    modules/simpletest/files/image-test.jpg
	deleted:    modules/simpletest/files/image-test.png
	deleted:    modules/simpletest/files/javascript-1.txt
	deleted:    modules/simpletest/files/javascript-2.script
	deleted:    modules/simpletest/files/php-1.txt
	deleted:    modules/simpletest/files/php-2.php
	deleted:    modules/simpletest/files/sql-1.txt
	deleted:    modules/simpletest/files/sql-2.sql
	deleted:    modules/simpletest/tests/upgrade/drupal-7.bare.minimal.database.php.gz
	deleted:    modules/simpletest/tests/upgrade/drupal-7.bare.standard_all.database.php.gz
	deleted:    modules/simpletest/tests/upgrade/drupal-7.filled.minimal.database.php.gz
	deleted:    modules/simpletest/tests/upgrade/drupal-7.filled.standard_all.database.php.gz
	deleted:    modules/update/tests/aaa_update_test.tar.gz
```

**Comment by pirog** [comment]
oh nice catch @reynoldsalec! 

Here are the global/app default .stignore files

globals
```
    '*.7z',
    '*.bz2',
    '*.dmg',
    '*.gz',
    '*.iso',
    '*.jar',
    '*.rar',
    '*.tar',
    '*.tgz',
    '*.un~',
    '*.zip',
    '.*.swp',
    '.*DS_Store',
    '.DS_Store*',
    '._*',
    '.sass-cache',
    'Icon',
    'Thumbs.db',
    'ehthumbs.db'
```

app
```
    "sites/default/files/*",
    "files/*",
    "wp-content/uploads/*"
```

**Comment by pirog** [comment]
so this seems to fit the evidence but its weird `files/*` is also grabbing `*/files/*`. Maybe we just need to RTFM on .stignore better. 

We can remove the `.gz` but then we open ourselves up to the possibility of someone having a GIANT tar in their code (which we've definitely seen before) which would take a bit to sync but i guess that is the price you pay for committing a huge file like that. 

@reynoldsalec if you've got time to look at this really quick we could try to get it in before the release later today. You'd want to make changes in 

```
kalabox/kalabox/lib/core/config.js
kalabox/kalabox-app-pantheon/app/kalabox.json
```

**Comment by reynoldsalec** [comment]
After investigating with @pirog it seems like the best way to address this would be to "negate" certain specific paths in .stignore that are not syncing over currently and causing this Git issue. See the .stignore docs for more info.

**Comment by pirog** [comment]
So, going to go through D6-D8, Backdrop and WordPress to see what we would need to add to get this to work. 

For the thing @jdleonard brought up i think that might be because we have syncthing set up to "ignore permissions" which might not be the way we want to go. @bcauldwell, is it easy to change our set up to sync permissions as well? are their any significant performance implications of doing that?

**Comment by pirog** [comment]
D7
```
!modules/simpletest/*
!modules/update/tests/*
```

**Comment by pirog** [comment]
Yeah so making sure syncthing "honors" permissions, resolves the rage @jdleonard was having. @bcauldwell will have a PR for you to check in a sec.

**Comment by bcauldwell** [comment]
Merged.

On Fri, Oct 9, 2015 at 9:26 AM, Mike Pirog <notifications@github.com> wrote:

> Yeah so making sure syncthing "honors" permissions, resolves the rage
> @jdleonard <https://github.com/jdleonard> was having. @bcauldwell
> <https://github.com/bcauldwell> will have a PR for you to check in a sec.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/533#issuecomment-146919703>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
So  #576 resolves @jdleonard's issue and i think we actually might just be able to use 

```
  "shareIgnores": [
    "sites/default/files",
    "files",
    "wp-content/uploads"
  ],
```

for the others instead of needing a bunch of `!` lines

**Comment by pirog** [comment]
ok. this should be resolved in the next release!

**Comment by reynoldsalec** [comment]
Hey @jpsalter, noticed you've been really helpful in reporting issues and wanted to invite you to our testing "Circle of Trust". We'll keep you updated on new Kalabox releases, alert you to potential bugs we're noticing, and may ask for your help testing different solutions. If you're interested, you can signup at http://bit.ly/kbox-trust

Thanks again for reporting on these issues!
