### ISSUE TITLE
Kerberose rebuild

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#534]
I have a Windows 8.1 machine and use Virtual Box 5.0.5 running ubuntu 32-bit (my machine only has 4G RAM). I tried to use the linux amd64 binary but it didn't work (I guess because I am running 32-bit).  So I installed nodejs using instructuctions for nodesource given here: https://nodejs.org/en/download/package-manager/
	sudo apt-get install --yes build-essential
	curl --silent --location https://deb.nodesource.com/setup_4.x | sudo bash -
	sudo apt-get install --yes nodejs

I had the npm permissions problem and the npm doctor didn't solve it so I reinstalled and used the instructions here: https://docs.npmjs.com/getting-started/fixing-npm-permissions (used "option 2" because my default director is /lib).

mkdir ~/npm-global
npm config set prefix '~/npm-global'
add "export PATH=~/npm-global/bin:$PATH" to .profile
source ~/.profile

Now I am ready to install kalabox!! But I get an error related to kerberos build, and errors when I try "kbox version".

========
~$ npm install -g kalabox
-
> kerberos@0.0.14 install /home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-30-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/home/john/npm-global/bin/kbox -> /home/john/npm-global/lib/node_modules/kalabox/bin/kbox.js

> kalabox@0.10.2 postinstall /home/john/npm-global/lib/node_modules/kalabox
> node ./scripts/postinstall.js

kalabox-engine-docker@0.10.3
kalabox-services-kalabox@0.10.3
kalabox-app-pantheon@0.10.2
Additional apps and backends installed.
kalabox@0.10.2 /home/john/npm-global/lib/node_modules/kalabox
├── tsort@0.0.1
├── diskspace@0.1.6
├── async@0.9.2
├── rimraf@2.2.8
├── uuid@2.0.1
├── sha1@1.1.1 (crypt@0.0.1, charenc@0.0.1)
├── shelljs@0.3.0
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── fs-extra@0.18.4 (jsonfile@2.2.2, graceful-fs@3.0.8)
├── verror@1.6.0 (extsprintf@1.2.0)
├── bluebird@2.10.1
├── windosu@0.1.3 (tail@0.3.9, q@0.9.7, temp@0.6.0)
├── winston@0.9.0 (cycle@1.0.3, stack-trace@0.0.9, isstream@0.1.2, eyes@0.1.8, pkginfo@0.3.0, colors@1.0.3)
├── download-status@2.2.1 (object-assign@2.1.1, progress@1.1.8, lpad-align@1.1.0)
├── restler@3.4.0 (yaml@0.2.3, qs@1.2.0, iconv-lite@0.2.11, xml2js@0.4.0)
├── yargs@3.26.0 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.2, y18n@3.2.0, os-locale@1.4.0, cliui@2.1.0)
├── moment@2.10.6
├── regex@0.1.1 (lex@1.7.4, augment@3.2.1, statemachines@0.1.0, jison@0.4.4)
├── download@3.3.0 (gulp-rename@1.2.2, get-stdin@3.0.2, each-async@1.1.1, url-regex@2.1.3, vinyl@0.4.6, stream-combiner@0.2.2, ware@1.3.0, rc@0.5.5, through2@0.6.5, concat-stream@1.5.0, decompress-unzip@2.1.2, decompress-targz@2.1.0, meow@2.1.0, decompress-tar@2.0.2, decompress-tarbz2@2.0.2, vinyl-fs@0.3.14, request@2.64.0)
├── lodash@3.6.0
├── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.4.0, cli-width@1.0.1, through@2.3.8, readline2@0.1.1, chalk@1.1.1, rx@2.5.3)
└── kalabox-metrics-rest@0.1.0 (body-parser@1.14.1, retry-bluebird@0.1.1, express@4.13.3, lodash@3.10.1, mongodb@2.0.44)
=========
~$ kbox version
Cannot find module kalabox-engine-docker@0.10.3 try an npm install first.
Error: Cannot find module kalabox-engine-docker@0.10.3 try an npm install first.
    at /home/john/npm-global/lib/node_modules/kalabox/lib/require.js:206:13
From previous event:
    at requireInternal (/home/john/npm-global/lib/node_modules/kalabox/lib/require.js:204:4)
    at /home/john/npm-global/lib/node_modules/kalabox/lib/require.js:296:14
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.exports.require (/home/john/npm-global/lib/node_modules/kalabox/lib/require.js:292:4)
    at /home/john/npm-global/lib/node_modules/kalabox/lib/kbox.js:64:28
From previous event:
    at exports.require (/home/john/npm-global/lib/node_modules/kalabox/lib/kbox.js:57:21)
    at /home/john/npm-global/lib/node_modules/kalabox/lib/engine.js:51:12
From previous event:
    at /home/john/npm-global/lib/node_modules/kalabox/lib/engine.js:39:21
    at /home/john/npm-global/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25
    at Object.exports.init (/home/john/npm-global/lib/node_modules/kalabox/lib/engine.js:274:10)
    at Object.<anonymous> (/home/john/npm-global/lib/node_modules/kalabox/lib/init.js:93:24)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.<anonymous> (/home/john/npm-global/lib/node_modules/kalabox/lib/init.js:92:4)
    at Object.init (/home/john/npm-global/lib/node_modules/kalabox/node_modules/lodash/index.js:7173:25)
    at main (/home/john/npm-global/lib/node_modules/kalabox/bin/kbox.js:199:15)
    at Object.<anonymous> (/home/john/npm-global/lib/node_modules/kalabox/bin/kbox.js:244:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by escapesequence** [comment]
I tried installing npm and nodejs from ubuntu using "sudo apt-get install"
the npm prefix is the same: /usr/lib
"npm version" shows:
{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.10.0',
  uv: '0.10.23',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1f',
  npm: '1.3.10' }

The result of the install is similar - it fails on kerberos (which is needed by mongodb):
<snip>
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/strip-ansi/-/strip-ansi-2.0.1.tgz
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/strip-ansi

> kerberos@0.0.14 install /home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

npm http 304 https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/strip-ansi/-/strip-ansi-2.0.1.tgz
npm http GET https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/mute-stream/0.0.4
npm http GET https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.4.tgz
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.4.tgz
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/john/npm-global/lib/node_modules/kalabox/node_modules/kalabox-metrics-rest/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
/home/john/npm-global/bin/kbox -> /home/john/npm-global/lib/node_modules/kalabox/bin/kbox.js

> kalabox@0.10.2 postinstall /home/john/npm-global/lib/node_modules/kalabox
> node ./scripts/postinstall.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0

**Comment by escapesequence** [comment]
I've come across two clues (but no success) so far:

1) install nodejs-legacy instead of node

2) make sure that NODE_PATH is defined as described here: http://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module

Does anyone else have this working on Ubuntu?

**Comment by escapesequence** [comment]
PS By "working" I mean via installing npm and then using npm to install kalabox (that is, NOT using the kalabox binary)

**Comment by pirog** [comment]
@escapesequence so there are a couple things to clarify and point out here. 

Are you trying to install kalabox in a VirtualBox ubuntu VM? If so this use case is not supported since you cannot create a VirtualBox instance inside another VirtualBox instance. Running directly on Windows 8.1 is not "officially" supported at this time but we've gotten reports that it works decently. That would be the ideal installation pathway.

Installing with `npm` is a little more tricky since you may need to install a bunch of other deps to get everything to compile. You may need to install some kerberos specific dev libraries with `apt-get install` to get the compile to work correctly. Again if you doing this in an Ubuntu VB VM its going to ultimately not work either way. The binary is def the preferred and easiest way to install. 

We only support AMD64 architecture so that might be a no-go for you as well.

**Comment by escapesequence** [comment]
Thanks.

Is it possible to have a version of kbox  that can be used within a VirtualBox Ubuntu instance that I create? (Wouldn't there be others that would want the same?)

**Comment by pirog** [comment]
It's a limitation of VirtualBox so not much we can do about it. You could probably do it inside of VMWare which i think supports the VM inception scenario better. 

Honestly though, we put a lot of time into making this cross platform precisely so people wouldnt have to worry about running it inside of a VM which is not an ideal workflow for sure. 

What is the apprehension with installing the windows version?

**Comment by escapesequence** [comment]
I'm just not familiar with developing in Windows.

I set up the kbox in Windows.  It is working. I'll continue with that. Thanks for kalabox!

**Comment by pirog** [comment]
haha lol... well i can def hear that loud and clear @escapesequence.

the nice thing about the architecture we have is all the kbox tools you will be running are all native linux tools so basically the only difference is you are editing your code in  Windows and using cmd.exe instead of terminal.
