### ISSUE TITLE
kbox update Install failure

### ISSUE THREAD

**Issue by ivyguo518** [kalabox/kalabox#535]
Hello, my kalabox site was showing up some error message about db connections,  so I ran kbox restart, kbox rebuild command trying to fix it, but the kalabox site was not responding after that. 

I tried to update kalabox from v0.10.0 to v0.10.2, and I got the following error message:

```````
info: DOCKER =>  Starting container kalabox_syncthing.
info: DOCKER =>  Container started. kalabox_syncthing
info: VError: EVENTS =>  Error dispatching event listeners [post-uninstall].
info: -- INSTALL FAILURE. --
```````
"If you've already installed Kalabox and it's pre-version 0.10.0 you should uninstall first." I seen this on https://github.com/kalabox/kalabox, but I was on v.0.10 so I didn't run the uninstallation script before updating.

**Comment by pirog** [comment]
hey @ivyguo518 can you try doing a `kbox update -- -v` to get more verbose output on the error you are getting?

**Comment by ivyguo518** [comment]
@pirog Sorry Mike, I have uninstalled the kalabox 0.10.0 two days ago, so I can't get the error information now, but I'll post error log here if I see similar problems in future updates.

**Comment by pirog** [comment]
sounds good. going to close this out and feel free to open up a new one if you get other update issues for future releases.
