### ISSUE TITLE
fresh kbox install, and first site 'install' crashes after downloading everything.

### ISSUE THREAD

**Issue by alphex** [kalabox/kalabox#536]
I uninstalled my older 0.9.10 install, and installed the fresh binary "kbox-macosx-amd64-v0.10.2" 

Went through your normal process as documented here : https://github.com/kalabox/kalabox/wiki/Pantheon-Guide to try and snag a site.

Everything seemed to be chgging along, until I got to this part.

https://gist.github.com/alphex/d94d73a683735d0e09ac

I sanitized some things to protect the innocent. (my clients, innocent, HA).

Thoughts?

Let me know if you need more info, I can copy & paste out the whole CLI install log.

thanks.

**Comment by labboy0276** [comment]
Hello,

I would create a backup on dev (or multidev if that is what you are doing)
and that should resolve this issue.  It is a known issue as seen here #530

On Thu, Oct 1, 2015 at 12:25 PM, Duran Goodyear <notifications@github.com>
wrote:

> I uninstalled my older 0.9.10 install, and installed the fresh binary
> "kbox-macosx-amd64-v0.10.2"
>
> Went through your normal process as documented here :
> https://github.com/kalabox/kalabox/wiki/Pantheon-Guide to try and snag a
> site.
>
> Everything seemed to be chgging along, until I got to this part.
>
> https://gist.github.com/alphex/d94d73a683735d0e09ac
>
> I sanitized some things to protect the innocent. (my clients, innocent,
> HA).
>
> Thoughts?
>
> Let me know if you need more info, I can copy & paste out the whole CLI
> install log.
>
> thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/536>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@alphex as @labboy0276 indicated there was a breaking change when upgrading from terminus 0.7.x to 0.8.x which we missed. #530 has workarounds in it for now and we should have this fixed in the next release!

**Comment by alphex** [comment]
I love work arounds like that   "just make a backup, because -magic-"...
;)

Thanks.
ᐧ


] duran goodyear
] alphex information solutions, llc
] w: http://alphex.com // v: 267.225.7439 // e: duran@alphex.com

**Comment by pirog** [comment]
@alphex lol

going to close this as duplicate and reference #530 for people who find their way here.
