### ISSUE TITLE
Add drush8 and config-merge to terminus container

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#543]
Hello Again!

Downloaded a Drupal 8 site form Pantheon.  Run any drush command get this:

```
john@kalamuna:~/kalabox/apps/d8tester/code/modules$ kbox drush
Drush 6.6.0 does not support Drupal . See                            [error]
http://drupal.org/project/drush for more information.
john@kalamuna:~/kalabox/apps/d8tester/code/modules$ 
```

**Comment by labboy0276** [comment]
I was messing around with the kalabox-plugin-drush and I tried something to the affect of this in the dockeffiles/drush/Dockerfile but I cant get it to run off it even with the ```kbox rebuild -- --build-local``` flag on, anyway here is what I put: 

```
curl -sS https://getcomposer.org/installer | php && \
  mv composer.phar /usr/local/bin/composer && \
  ln -s /usr/local/bin/composer /usr/bin/composer && \
  git clone --depth 1 --branch 5.11.0 https://github.com/drush-ops/drush.git /usr/local/src/drush5 && \
  git clone --depth 1 --branch 6.6.0 https://github.com/drush-ops/drush.git /usr/local/src/drush6 && \
  git clone --depth 1 --branch 7.0.0-rc2 https://github.com/drush-ops/drush.git /usr/local/src/drush7 && \
  git clone --depth 1 --branch master https://github.com/drush-ops/drush.git /usr/local/src/drush8 && \
  git clone --depth 1 --branch backdrush https://github.com/pirog/drush.git /usr/local/src/backdrush && \
  ln -s /usr/local/src/drush5/drush /usr/bin/drush5 && \
  ln -s /usr/local/src/drush6/drush /usr/bin/drush6 && \
  ln -s /usr/local/src/drush7/drush /usr/bin/drush7 && \
  cd /usr/local/src/drush7 && composer install --no-dev && \
  ln -s /usr/local/src/drush8/drush /usr/bin/drush8 && \
  cd /usr/local/src/drush8 && composer install --no-dev && \
  ln -s /usr/local/src/backdrush/drush /usr/bin/backdrush && \
  cd /usr/local/src/backdrush && composer install --no-dev
```

**Comment by pirog** [comment]
So there are a couple of things here

1. The pantheon app just ships with drush 5 and 6 which are the current supported versions for pantheon. drush 5 and 6 do not work with drupal 8. so i wouldnt say this an error. its what we would expect.

2. the pantheon app doesnt use the drush plugin so what you are experiencing in the second comment is also what you would expect.

**Comment by labboy0276** [comment]
Indeed,

I was trying to add drush 8 support so we can start doing drupal 8 stuff.  But thanks for clarifying the drush + pantheon stuff, let me try and fix it in the actual app.

**Comment by pirog** [comment]
drush lives in the terminus dockerfile for a pantheon app so you would want to change it there.

**Comment by labboy0276** [comment]
OK

It is close, branch is here:
https://github.com/kalabox/kalabox-app-pantheon/tree/issue543

Side notes:
1. The @dev alias is nto getting set in drush 8, I added a little code to watchout for that (commands run fine if you remove the @dev).

2. I had to manually update my kalabox.json within the d8 app since it was showing drush 6 and php 5.3 on create:
```
      "drush-version": "8",
      "env": "dev",
      "framework": "drupal8",
      "php": "5.5.24",
```

3. Getting this error which is stopping me 
Undefined class constant MYSQL_ATTR_USE_BUFFERED_QUERY
Which is resolved by adding php-mysql per https://www.drupal.org/node/1016622

However, when I do this it causes the db not to connect...

So before I go on a wild goose hunt, should we merge in my drush 8 stuff and wait for pantheon to do beta16?  It is up to you...

**Comment by pirog** [comment]
@labboy0276 this is a good starting point but its going to need some work before we can merge it in. Here are current concerns:

1. We don't want to pull drush8 from master. It would be best to tag it to a specific version so the image is constant and stable and not pulling new code every time we reroll it. 

2. I'd like to see clearer reasoning around the dev alias situation. Specifically what the proper syntax is in D8 or whether there is a dev alias at all in D8 and the resource you are looking at to justify the change. Also see https://github.com/kalabox/kalabox-app-pantheon/commit/4ac119553c1b8eddc67cce2dc5361f0a6f176402#commitcomment-13581209

3. We should get more clarity on why MYSQL_ATTR_USE_BUFFERED_QUERY happens and why adding php-mysql causes the DB to not connect, which could be related to removing the dev alias. 

4. We also need to add in logic to make sure that if you spin up a D8 site that we set your drush version to 8 by default. This would happen in lib/events.js.

This all make sense?

**Comment by labboy0276** [comment]
Indeed, only thing with #1, drush8 is master it seems and from their on docs too.  I couldnt find a dev-master like composer uses.

**Comment by pirog** [comment]
It's just the git tag and there seems to be many of them for d8

On Sun, Oct 4, 2015 at 10:24 AM, John Ouellet <notifications@github.com>
wrote:

> Indeed, only thing with #1 <https://github.com/kalabox/kalabox/pull/1>,
> drush8 is master it seems and from their on docs too. I couldnt find a
> dev-master like composer uses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/543#issuecomment-145367743>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 we are also going to want to make sure we get https://github.com/drush-ops/config-extra in here for drush 8 as well. 

If you've got questions about how to do this let me know and i'll try to see if Greg Anderson is available to help.

**Comment by labboy0276** [comment]
OK @pirog 

- fixed issue 1, pulls in from a tag now, right now it is set to rc1.
- fixed issue 2 and used the codez you wanted.  I can;t find anything on why @dev doesnt work w/ drush8, but we have an easier way to address it now anyway.
- Issue 3, this has to do with PDO not being enabled?  I tried to enable it via installing php-mysql && then throwing in extension=pdo.so && extension=pdo_mysql.so in php.ini but that just causes so many issues as seen below"
```
john@kalamuna:~/kalabox/apps/d8tester$ kbox drush cc all
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo.so' - /root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo_mysql.so' - /root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo.so' - /root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo_mysql.so' - /root/.phpbrew/php/php-5.5.24/lib/php/extensions/no-debug-non-zts-20121212/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
```
I will do the last 2 issues once we figure out this mysql error

**Comment by labboy0276** [comment]
OK, So I thought this was due to the fact the @dev command wasnt being used.  I did a debig of the drush to see why this was failing.  It seems drush8 now looks in /drush folder in the D8 install (which is new).  I moved the aliases.drushrc.php into that folder and adding @dev did wotk on the command, but I am still getting the MYSQL_ATTR_USE_BUFFERED_QUERY error.  oy vay....

**Comment by labboy0276** [comment]
Also, I did add php5-mysql to in the dockerfile as many of the posts suggested and now I get this:

```
john@kalamuna:~/kalabox/apps/d8tester$ kbox drush cc all
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /code/core/lib/Drupal/Core/Entity/EntityManager.php on line 426
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: syntax error, unexpected 'class' (T_CLASS), expecting
identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/code/core/lib/Drupal/Core/Entity/EntityManager.php, line 426
Drush was not able to start (bootstrap) Drupal.                          [error]
Hint: This error can only occur once the database connection has
already been successfully initiated, therefore this error generally
points to a site configuration issue, and not a problem connecting to
the database.

Drush was attempting to connect to: 
 Drupal version                  :  8.0.0-rc1                       
 Site URI                        :  http://default                  
 Database driver                 :  mysql                           
 Database hostname               :  d8tester.kbox                   
 Database port                   :  3306                            
 Database username               :  pantheon                        
 Database name                   :  pantheon                        
 Default theme                   :  bartik                          
 Administration theme            :  seven                           
 PHP executable                  :  /usr/bin/php                    
 PHP configuration               :  /etc/php5/cli/php.ini           
 PHP OS                          :  Linux                           
 Drush script                    :  /usr/local/src/drush8/drush.php 
 Drush version                   :  8.0.0-rc1                       
 Drush temp directory            :  /tmp                            
 Drush configuration             :                                  
 Drush alias files               :  /code/drush/aliases.drushrc.php 
 Install profile                 :  standard                        
 Drupal root                     :  /code                           
 Site path                       :  sites/default                   
 File directory path             :  sites/default/files             
 Private file directory path     :  sites/default/files/private     
 Temporary file directory path   :  /tmp                            
 Sync config path                :  sites/default/config            


john@kalamuna:~/kalabox/apps/d8tester$ 
```

**Comment by labboy0276** [comment]
And more notes, I have tired so many things to no avail, such as:

- installing other packages such as: ```mysql-client mysql-client-5.5 mysql-common``` 
- Remove pressflow and manually entering our own settings in settings.php
- Read through many issues and tried various solutions as found in the queue that GA points out to check: http://drupal.stackexchange.com/questions/tagged/drush
- Cried

All in all, I believe thee may be a package missing for this to work with the Drupal 8 / Drush 8, I just can't find which one it is and my head hurts now.  

Also not sure why that PHP Parse error is happening, but I believe it related to the last statement.

**Comment by pirog** [comment]
``` 
PHP executable                  :  /usr/bin/php                    
PHP configuration               :  /etc/php5/cli/php.ini           
PHP OS                          :  Linux       
```

these dont look right to me. we should be making sure we use the bin and config set by phpbrew

**Comment by labboy0276** [comment]
- @pirog figured out the sadness above by adding magix to kdrush
- I fixeded the kalabox.json drush8 / drupal8 creation issue

Working on the config-extra now

**Comment by labboy0276** [comment]
config-extra said nothing to install as a FYI:

Tried this in terminus/Dockerfile right below where we install registry repair, didnt work:
```
git clone --depth 1 --branch 1.0.0 https://github.com/drush-ops/config-extra.git && \
cd config-extra && composer install --no-dev && \
drush cc drush
```

**Comment by labboy0276** [comment]
should also double check drupal 6 / 7 sites for what we did to get the d8 site to work.  Mainly at the drush level...
