### ISSUE TITLE
Fix imagemagick rage

### ISSUE THREAD

**Issue by RobLoach** [kalabox/kalabox#548]
http://imagemagick.org
http://php.net/manual/en/imagick.setup.php

```
sudo apt-get install php5-imagick
```

It's Magic! Pantheon ships it out of the box https://pantheon.io/docs/articles/sites/external-libraries/#imagemagick

**Comment by pirog** [comment]
+1

On Mon, Oct 5, 2015 at 10:22 AM, Rob Loach <notifications@github.com> wrote:

> http://imagemagick.org
> http://php.net/manual/en/imagick.setup.php
>
> sudo apt-get install php5-imagick
>
> It's Magic!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/548>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@RobLoach are you sure we arent including this in kalabox already? It looks like the php we are building includes the magic.
https://github.com/kalabox/phpbrewer/commit/5bd79f2b4f1b1aaf3d4dfa917d9c345a362db51e

**Comment by RobLoach** [comment]
@gremy Were you on an older version of KalaBox when you ran into this? Looks like phpbrewer rocks it for us.

**Comment by pirog** [comment]
@RobLoach @gremy this is what ive got in phpinfo() for a 5.3.29 site. @gremy are you on 5.5? Can you check out your phpinfo()?

![screen shot 2015-10-13 at 11 43 29 am](https://cloud.githubusercontent.com/assets/713424/10459909/ea094844-719f-11e5-93c4-27fea4d7bc67.png)

**Comment by pirog** [comment]
pretty sure this should be in alpha4. please reopen if not.

**Comment by RobLoach** [comment]
:+1:

**Comment by pirog** [comment]
@gremy took this one to :100:

**Comment by andrewmallis** [comment]
The imagemagick-dev package does not install the convert binary, which is necessary to complete successful operations in webdev.

**Comment by pirog** [comment]
thanks @andrewmallis this is really helpful feedback. Really weird that `imagemagick-dev` does not install `imagemagick` itself and its deps but this should be easy to fix (and test for).

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/pull/163
