### ISSUE TITLE
Front-end Mockup of Site Add Process

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#549]
**Goals**

- Create a walk-through flow taking the user from authenticating with providers and choosing a site to import
- Create $scope objects that represent the required data for the interface

**Notes**

Mostly these are extra-credit issues; @bcauldwell will most likely handle most of the deeper integration work here:

Listing of available sites
Model available sites after the Terminus available data. Check out the parse sites function in Terminus plugin; name/value. We never store site id, but exchange site name for the site id. This will impact assumptions around how the site add functionality will work.

Site Add
Take a look at https://github.com/kalabox/kalabox-app-pantheon/blob/v0.10/app/plugins/kalabox-plugin-pantheon/lib/pull.js for more info.

Authentication
Think a little bit about the authentication flow: https://github.com/kalabox/kalabox-app-pantheon/blob/v0.10/app/plugins/kalabox-plugin-pantheon/lib/client.js

Client.prototype.validateSession will show whether we need to re-authorize a service.

Client.prototype.auth will authorize when given username/pwd.

**Comment by reynoldsalec** [comment]
![1f5e2866-5ad5-11e5-8fdf-225a1062554f](https://cloud.githubusercontent.com/assets/1153738/10289340/b19bd40c-6b52-11e5-9ec5-e8afbc471c4b.JPG)

**Comment by pirog** [comment]
Delete once @bcauldwell has made a card for the "create site" task.

**Comment by bcauldwell** [comment]
Added "create site"/"add site" issue, closing this.
