### ISSUE TITLE
Setting PHP version

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox#556]
I am testing out kalabox and can't seem to find a way to easily use a higher php version with my Pantheon site. I am running 5.5 on the server and our codebase is making use of short array syntax, making my local copy on kbox throw a fit. How do I change this?

**Comment by pirog** [comment]
So good news here is automatically setting the correct php version is going to be in the next 0.10.3-alpha3 release
https://github.com/kalabox/kalabox-app-pantheon/commit/d4cf77352742861c6ff080ec5558dd7f7603cf50

In the meantime the easiest way to do this is the following:

1. Open up the folder that contains your app and find `plugins/kalabox-plugin-pantheon/lib/env.js`
2. In this file you will see something like

```js
 var frameworkSpec = {
      drupal: {
        php: '5.3.29',
        filemount: 'sites/default/files'
      },
      drupal8: {
        php: '5.5.24',
        filemount: 'sites/default/files'
      },
      wordpress: {
        php: '5.5.24',
        filemount: 'wp-content/uploads'
      },
      backdrop: {
        php: '5.3.29',
        filemount: 'files'
      }
    };
```

Identify the framework you are using and change the version to either `5.5.24` or `5.3.29` depending on what you need.

3. Save the file
4. run `kbox rebuild -- -v` from inside your app folder
5. run `kbox start` and it should have switched php versions for you.

**Comment by dustinleblanc** [comment]
Worked great, thanks!

**Comment by pirog** [comment]
Sweet!

**Comment by dustinleblanc** [comment]
Hey all, just wanted to chime in, since we filed this I've noticed the code has changed and this can now be set in the kalabox.json file in the root. After doing a strip and rebuild of all my kbox stuff this morning I have my app up and running on php5.5, pulling and syncing and happy as a clam. Just want to leave an additional comment here in case anyone comes across this later and gets confused that Mike's answer above is now out of date.

**Comment by pirog** [comment]
@dustinleblanc also worth adding that in 0.10.3+ the default php version for your app will be whatever php version you are using up on pantheon. 

that said, there seems to be some circumstances where pantheon doesnt to include the php info via terminus. in this case we use the defaults as indicated above and you can change those if you wish.

**Comment by pi-ron** [comment]
Can't seem to find how to set php version either of the above methods.

Have set it on Pantheon for an environment, deleted site and recreated but Kalabox is not using the version I've set in pantheon.

**Comment by pi-ron** [comment]
Found the setting in kalabox.yml `php:` and I've change to `55`, rebulding...

**Comment by pi-ron** [comment]
That's done it. :-)

**Comment by pirog** [comment]
I would open a ticket on the pantheon end of its not updating your php
version

**Comment by ccharlton** [comment]
Is there an official list or way to see which PHP versions my current Kalabox has avail?

**Comment by pirog** [comment]
There are a few places this is mentioned in the docs but i think this is probably the best spot
http://pantheon.kalabox.io/en/v2.1/users/config/#configuration
