### ISSUE TITLE
Syncthing config download causes engine installation to fail

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#557]
1. Run uninstall script from 0.9.x npm install
2. Fresh binary install of 0.10.2
3. kbox create pantheon
4. Install failure!
```
###############################################################
                                                               
                    Welcome to Kalabox 2!                      
                                                               
 We see this is your first time running a Kalabox command that 
 requires the use of the Kalabox engine. Before we can do this 
 We need to install some special things to make sure you are   
 good to go. Please agree to the prompt below to install all   
 the magic. (takes about 5 minutes with average download speed)
                                                               
###############################################################
info: -- Step 1/22 --
info: Authorizing trilling subroutines...
? Install all the magic and get this party started? Yes
info: -- OK! 5% complete! --

info: -- Step 2/22 --
info: Making sure syncthing is not running...
info: -- OK! 9% complete! --

info: -- Step 3/22 --
info: Adding syncthing image to build list...
info: -- OK! 14% complete! --

info: -- Step 4/22 --
info: Queuing up syncthing downloads...
info: -- OK! 18% complete! --

info: -- Step 5/22 --
info: Checking firewall settings...
info: -- OK! 23% complete! --

info: -- Step 6/22 --
info: Adding services images to build list...
info: -- OK! 27% complete! --

info: -- Step 7/22 --
info: Queuing provider admin commands...
info: -- OK! 32% complete! --

info: -- Step 8/22 --
info: Queuing up provider downloads...
info: -- OK! 36% complete! --

info: -- Step 9/22 --
info: Checking for available disk space...
info: -- OK! 41% complete! --

info: -- Step 10/22 --
info: Checking for Internet access...
info: -- OK! 45% complete! --

info: -- Step 11/22 --
info: Downloading files...
     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.25/syncthing-macosx-amd64-v0.11.25.tar.gz
     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile
  progress : [                    ] 1% 3.3sinfo: Error: Couldn't connect to https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml (404)
info: -- INSTALL FAILURE. --
```

**Comment by pirog** [comment]
awwww fuck. i know what this is. hold on a sec.

**Comment by pirog** [comment]
hey @jdleonard try running `kbox update -- -v` to resume the install part (you'll need to run the `kbox create pantheon` separately after this is complete)

**Comment by jdleonard** [comment]
I had already run the latest install script so I just repeated steps 1-3 and step 4 never happened :)

Thanks!

**Comment by jorap** [comment]
Same issue when installing in Windows for the first time.
https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml cannot be found.

info: Error: Couldn't connect to https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml (404)
info: -- INSTALL FAILURE. --

D:\>kbox update -- -v
debug: ENGINE =>  Initializing engine.
debug: ENGINE =>  Engine initialized.
debug: DISCO => App registry does NOT contain appDirs property!
debug: DISCO => AppsRegistry dirs.
debug: [1:23] Starting core-auth
debug: description => Authorizing trilling subroutines...
debug: dependencies =>
info: -- Step 1/23 --
info: Authorizing trilling subroutines...
info: Non-interactive mode.
debug: USER INPUT => {}
debug: Finished core-auth (16)
info: -- OK! 4% complete! --

debug: [2:23] Starting syncthing-off
debug: description => Making sure syncthing is not running...
debug: dependencies =>
info: -- Step 2/23 --
info: Making sure syncthing is not running...
debug: SYNC => PING http://127.0.0.1:60008
debug: SYNC-REST =>  get:http://127.0.0.1:60008/rest/system/ping {}
debug: SYNC-REST =>  get:http://127.0.0.1:60008/rest/system/ping {}
debug: Finished syncthing-off (5047)
info: -- OK! 9% complete! --

debug: [3:23] Starting syncthing-image
debug: description => Adding syncthing image to build list...
debug: dependencies =>
info: -- Step 3/23 --
info: Adding syncthing image to build list...
debug: Finished syncthing-image (16)
info: -- OK! 13% complete! --

debug: [4:23] Starting syncthing-downloads
debug: description => Queuing up syncthing downloads...
debug: dependencies =>
info: -- Step 4/23 --
info: Queuing up syncthing downloads...
debug: Finished syncthing-downloads (16)
info: -- OK! 17% complete! --

debug: [5:23] Starting core-downloads-win32
debug: description => Queuing up support files...
debug: dependencies =>
info: -- Step 5/23 --
info: Queuing up support files...
debug: Finished core-downloads-win32 (15)
info: -- OK! 22% complete! --

debug: [6:23] Starting core-firewall
debug: description => Checking firewall settings...
debug: dependencies =>
info: -- Step 6/23 --
info: Checking firewall settings...
debug: Finished core-firewall (0)
info: -- OK! 26% complete! --

debug: [7:23] Starting services-kalabox-install
debug: description => Adding services images to build list...
debug: dependencies =>
info: -- Step 7/23 --
info: Adding services images to build list...
debug: Finished services-kalabox-install (16)
info: -- OK! 30% complete! --

debug: [8:23] Starting engine-docker-install-engine
debug: description => Queuing provider admin commands...
debug: dependencies =>
info: -- Step 8/23 --
info: Queuing provider admin commands...
debug: Finished engine-docker-install-engine (15)
info: -- OK! 35% complete! --

debug: [9:23] Starting engine-docker-downloads
debug: description => Queuing up provider downloads...
debug: dependencies =>
info: -- Step 9/23 --
info: Queuing up provider downloads...
debug: Finished engine-docker-downloads (16)
info: -- OK! 39% complete! --

debug: [10:23] Starting core-internet
debug: description => Checking for Internet access...
debug: dependencies => core-firewall
info: -- Step 10/23 --
info: Checking for Internet access...
debug: Checking: www.google.com
debug: Finished core-internet (31)
info: -- OK! 43% complete! --

debug: [11:23] Starting core-downloads
debug: description => Downloading files...
debug: dependencies => core-internet, engine-docker-downloads, core-downloads-win32, syncthing-downloads
info: -- Step 11/23 --
info: Downloading files...
debug: https://github.com/syncthing/syncthing/releases/download/v0.11.25/syncthing-windows-amd64-v0.11.25.zip -> d:\kalabox\downloads
debug: https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml -> d:\kalabox\downloads
debug: https://raw.githubusercontent.com/kalabox/diskspace.js/master/drivespace.exe -> d:\kalabox\downloads
debug: https://raw.githubusercontent.com/kalabox/windosu/master/invisible.vbs -> d:\kalabox\downloads
debug: https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile -> d:\kalabox\downloads
debug: https://github.com/boot2docker/windows-installer/releases/download/v1.8.0/docker-install.exe -> d:\kalabox\downloads
debug: https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/b2d.inf -> d:\kalabox\downloads
     fetch : https://raw.githubusercontent.com/kalabox/windosu/master/invisible.vbs
  progress : [====================] 100% 0.0s

     fetch : https://raw.githubusercontent.com/kalabox/diskspace.js/master/drivespace.exe


     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile


     fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/b2d.inf


info: Error: Couldn't connect to https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml (404)
info: -- INSTALL FAILURE. --

**Comment by pirog** [comment]
@jorap. make sure you are using the latest binary. should be 0.10.3-alpha3.
I think this issue existed in previous versions.

On Wed, Oct 14, 2015 at 6:00 PM, jorap <notifications@github.com> wrote:

> Same issue when installing in Windows for the first time.
>
> https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
> cannot be found.
>
> info: Error: Couldn't connect to
> https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
> (404)
> info: -- INSTALL FAILURE. --
>
> D:>kbox update -- -v
> debug: ENGINE => Initializing engine.
> debug: ENGINE => Engine initialized.
> debug: DISCO => App registry does NOT contain appDirs property!
> debug: DISCO => AppsRegistry dirs.
> debug: [1:23] Starting core-auth
> debug: description => Authorizing trilling subroutines...
> debug: dependencies =>
> info: -- Step 1/23 --
> info: Authorizing trilling subroutines...
> info: Non-interactive mode.
> debug: USER INPUT => {}
> debug: Finished core-auth (16)
> info: -- OK! 4% complete! --
>
> debug: [2:23] Starting syncthing-off
> debug: description => Making sure syncthing is not running...
> debug: dependencies =>
> info: -- Step 2/23 --
> info: Making sure syncthing is not running...
> debug: SYNC => PING http://127.0.0.1:60008
> debug: SYNC-REST => get:http://127.0.0.1:60008/rest/system/ping {}
> debug: SYNC-REST => get:http://127.0.0.1:60008/rest/system/ping {}
> debug: Finished syncthing-off (5047)
> info: -- OK! 9% complete! --
>
> debug: [3:23] Starting syncthing-image
> debug: description => Adding syncthing image to build list...
> debug: dependencies =>
> info: -- Step 3/23 --
> info: Adding syncthing image to build list...
> debug: Finished syncthing-image (16)
> info: -- OK! 13% complete! --
>
> debug: [4:23] Starting syncthing-downloads
> debug: description => Queuing up syncthing downloads...
> debug: dependencies =>
> info: -- Step 4/23 --
> info: Queuing up syncthing downloads...
> debug: Finished syncthing-downloads (16)
> info: -- OK! 17% complete! --
>
> debug: [5:23] Starting core-downloads-win32
> debug: description => Queuing up support files...
> debug: dependencies =>
> info: -- Step 5/23 --
> info: Queuing up support files...
> debug: Finished core-downloads-win32 (15)
> info: -- OK! 22% complete! --
>
> debug: [6:23] Starting core-firewall
> debug: description => Checking firewall settings...
> debug: dependencies =>
> info: -- Step 6/23 --
> info: Checking firewall settings...
> debug: Finished core-firewall (0)
> info: -- OK! 26% complete! --
>
> debug: [7:23] Starting services-kalabox-install
> debug: description => Adding services images to build list...
> debug: dependencies =>
> info: -- Step 7/23 --
> info: Adding services images to build list...
> debug: Finished services-kalabox-install (16)
> info: -- OK! 30% complete! --
>
> debug: [8:23] Starting engine-docker-install-engine
> debug: description => Queuing provider admin commands...
> debug: dependencies =>
> info: -- Step 8/23 --
> info: Queuing provider admin commands...
> debug: Finished engine-docker-install-engine (15)
> info: -- OK! 35% complete! --
>
> debug: [9:23] Starting engine-docker-downloads
> debug: description => Queuing up provider downloads...
> debug: dependencies =>
> info: -- Step 9/23 --
> info: Queuing up provider downloads...
> debug: Finished engine-docker-downloads (16)
> info: -- OK! 39% complete! --
>
> debug: [10:23] Starting core-internet
> debug: description => Checking for Internet access...
> debug: dependencies => core-firewall
> info: -- Step 10/23 --
> info: Checking for Internet access...
> debug: Checking: www.google.com
> debug: Finished core-internet (31)
> info: -- OK! 43% complete! --
>
> debug: [11:23] Starting core-downloads
> debug: description => Downloading files...
> debug: dependencies => core-internet, engine-docker-downloads,
> core-downloads-win32, syncthing-downloads
> info: -- Step 11/23 --
> info: Downloading files...
> debug:
> https://github.com/syncthing/syncthing/releases/download/v0.11.25/syncthing-windows-amd64-v0.11.25.zip
> -> d:\kalabox\downloads
> debug:
> https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
> -> d:\kalabox\downloads
> debug:
> https://raw.githubusercontent.com/kalabox/diskspace.js/master/drivespace.exe
> -> d:\kalabox\downloads
> debug:
> https://raw.githubusercontent.com/kalabox/windosu/master/invisible.vbs ->
> d:\kalabox\downloads
> debug:
> https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile
> -> d:\kalabox\downloads
> debug:
> https://github.com/boot2docker/windows-installer/releases/download/v1.8.0/docker-install.exe
> -> d:\kalabox\downloads
> debug:
> https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/b2d.inf
> -> d:\kalabox\downloads
> fetch :
> https://raw.githubusercontent.com/kalabox/windosu/master/invisible.vbs
> progress : [====================] 100% 0.0s
>
>  fetch : https://raw.githubusercontent.com/kalabox/diskspace.js/master/drivespace.exe
>
>
>  fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/profile
>
>
>  fetch : https://raw.githubusercontent.com/kalabox/kalabox-boot2docker/master/b2d.inf
>
> info: Error: Couldn't connect to
> https://raw.githubusercontent.com/kalabox/kalabox/master/dockerfiles/syncthing/config.xml
> (404)
> info: -- INSTALL FAILURE. --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/557#issuecomment-148215467>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
