### ISSUE TITLE
Can't directly access database

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#562]
Maybe I'm going crazy, but I don't seem to be able to access Kalabox-based databases in 0.10.2 via Sequel Pro like I used to in 0.9.x.

![screen shot 2015-10-05 at 23 04 33](https://cloud.githubusercontent.com/assets/2074112/10299222/9ceaee22-6bb5-11e5-8046-92c53ca5d113.png)

Port is from kbox containers:
```
{
  "id": "1ff91f753c191d1f834513e4a7c0dc4391b86b7608dc08f5818d4c96faf6beb1",
  "name": "kb_copperly2_db",
  "app": "copperly2",
  "ports": [
    "3306/tcp=>32776"
  ],
  "running": true
}
```

Any tips?

**Comment by pirog** [comment]
holla holla,

if copperly2 is a pantheon app then you need to set the user and database
to pantheon and of course make sure your port is correct.

Let us know if that resolves your issue!

On Mon, Oct 5, 2015 at 8:07 PM, JD Leonard <notifications@github.com> wrote:

> Maybe I'm going crazy, but I don't seem to be able to access Kalabox-based
> databases in 0.10.2 via Sequel Pro like I used to in 0.9.x.
>
> [image: screen shot 2015-10-05 at 23 04 33]
> <https://cloud.githubusercontent.com/assets/2074112/10299222/9ceaee22-6bb5-11e5-8046-92c53ca5d113.png>
>
> Port is from kbox containers:
>
> {
>   "id": "1ff91f753c191d1f834513e4a7c0dc4391b86b7608dc08f5818d4c96faf6beb1",
>   "name": "kb_copperly2_db",
>   "app": "copperly2",
>   "ports": [
>     "3306/tcp=>32776"
>   ],
>   "running": true
> }
>
> Any tips?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/562>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by jdleonard** [comment]
That most certainly was the needed fix. Thanks much!
