### ISSUE TITLE
Sometimes when you reauth a session token your request hits the baddest of gateways

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#566]
Received following error on attempt kbox pull of a site that was asleep. I thought we had a method to wake up the site before pull, so thought I'd check to make sure that's working ok:

```
Error running ad hoc container with kalabox/terminus:dev.: Non-zero exit code: 1 [2015-10-06 20:03:40] [error] <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>


Error: Non-zero exit code: 1 [2015-10-06 20:03:40] [error] <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>


    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:566:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:545:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:636:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:634:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:637:27)
    at /Users/alec/kalabox/apps/cvt-working/plugins/kalabox-plugin-pantheon/lib/terminus.js:111:33
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:716:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:715:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:575:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:574:4)
    at /Users/alec/kalabox/apps/cvt-working/plugins/kalabox-plugin-pantheon/lib/terminus.js:110:31
    at process._tickCallback (node.js:812:13)
```

**Comment by pirog** [comment]
Yeah we definitely call terminus.wake. My guess here is you have a bad
session and its not asking you to reauth?

On Tue, Oct 6, 2015 at 1:24 PM, reynoldsalec <notifications@github.com>
wrote:

> Received following error on attempt kbox pull of a site that was asleep. I
> thought we had a method to wake up the site before pull, so thought I'd
> check to make sure that's working ok:
>
> Error running ad hoc container with kalabox/terminus:dev.: Non-zero exit code: 1 [2015-10-06 20:03:40] [error] <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
>
>
> Error: Non-zero exit code: 1 [2015-10-06 20:03:40] [error] <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
>
>
>     at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:566:28
> From previous event:
>     at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:545:20)
>     at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:636:18
> From previous event:
>     at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:634:6)
> From previous event:
>     at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:637:27)
>     at /Users/alec/kalabox/apps/cvt-working/plugins/kalabox-plugin-pantheon/lib/terminus.js:111:33
> From previous event:
>     at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:716:25)
> From previous event:
>     at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:715:6)
> From previous event:
>     at /usr/local/bin/lib/engine.js.jx:575:29
> From previous event:
>     at Object.exports.use (/usr/local/bin/lib/engine.js.jx:574:4)
>     at /Users/alec/kalabox/apps/cvt-working/plugins/kalabox-plugin-pantheon/lib/terminus.js:110:31
>     at process._tickCallback (node.js:812:13)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/566>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by reynoldsalec** [comment]
@pirog It did ask me to reauth and reauthed successfully; I was able to verify by checking out the session file (and using it to get around my problem in #565).

**Comment by pirog** [comment]
Hmm alright. Still don't think this is a wake thing.

can you run `kbox terminus cli version`? wondering if you somehow ended up with plugin code that is mismatched from your terminus container.

**Comment by reynoldsalec** [comment]
kbox terminus cli version returns 0.8.0 @pirog

**Comment by pirog** [comment]
@reynoldsalec 

So i was able to replicate this once but thereafter i could not so still not really sure what is going on. 

Replicate:

1. Open up your session file `~/.kalabox/terminus/session/YOUREMAIL`
2. Change the `session_expire_time` to something small like 100 and save the file
3. Run `kbox pull -- -v` on an app
4. Reauth when prompted
5. Sometimes Fail?

**Comment by pirog** [comment]
So if you purposefully trash your session token and try to make a request with it you get a 401: unauthorized `Error: Invalid or expired session header: X-Pantheon-Session` which is different than what we are getting.

I've tried about 20 different request combos and i can't get a 502. I'm going to assume that this is an sporadic infrastructure issue on the pantheon side. https://github.com/pantheon-systems/cli/issues/59

In the meantime i think a good resolution is to catch the error and do a few retries on the request after some delay? Going to move this back to alpha4 and backlog.

**Comment by reynoldsalec** [comment]
Sounds like we're narrowing it down to a Pantheon-side issue, so unless we have repeats I think that's the best solution @pirog.
