### ISSUE TITLE
Error or "kbox start" Error: ENOENT, open '/Users/xxx/Sites/other-app-name/code/.stfolder'

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#568]
Got this when trying to start an app.  The error references a different app directory, one that failed to `kbox create pantheon` due to 'could not create backup' error.

Will try kbox destory on the other app.

``````
EVENTS =>  Error dispatching event listeners [post-start].
Error: ENOENT, open '/Users/RoamingMac/Sites/other-app-name/code/.stfolder'
``````

**Comment by pirog** [comment]
Yoyo. 

So i think this error actually should be addressed by #326. We are rolling out alpha3 tomorrow (unless testing goes really badly). 

In the meantime the workaround should be to go into the failed app fir and run `kbox destroy` i that doesnt work or you can't do that for whatever reason then try doing something like this:

```
boot2docker --vm="Kalabox2" ssh (password: tcuser if needed)
docker ps --all | grep other-app-name
docker rm -f kb_other-app-name_data
docker rm -f kb_other-app-name_db
docker rm -f kb_other-app-name_appserver
docker rm -f kb_other-app-name_redis
docker rm -f kb_other-app-name_solr
```

I think you should be able to do a `kbox start` on your other app after that.

**Comment by pi-ron** [comment]
Yep, `kbox destroy` on the dodgy app did the trick.

**Comment by pirog** [comment]
Awesome awesome!

alpha3 does self-cleanup so a lot of these kinds of errors should go away. Will be pretty excited for that :)
