### ISSUE TITLE
GUI integration login

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#571]
The GUI needs login functionality for integrations.

**Comment by bcauldwell** [comment]
@reynoldsalec please add a visual component for the site login service in the GUI.

**Comment by reynoldsalec** [comment]
A good part of this should be #584, then I think auth-ing the provider integrations (right now just Pantheon) will be pretty easy. That's the focus of this task, correct @bcauldwell?

**Comment by bcauldwell** [comment]
@reynoldsalec I agree that's the focus of this task and most of this should be covered by #584.

**Comment by reynoldsalec** [comment]
@bcauldwell wrapped Client.prototype.validateSession and Client.prototype.auth so we can use those from the integrations.

**Comment by reynoldsalec** [comment]
For some reason the kbox promise wasn't resolving in my AuthModal controller; need to look at this tomorrow, perhaps with @bcauldwell.
