### ISSUE TITLE
Memory Issues on Alpha3

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#585]
Hello,

Every site I use after a few minutes I start to get this:

```
Warning: include_once(): Unable to allocate memory for pool. in drupal_load() (line 1145 of /code/includes/bootstrap.inc).
Warning: require_once(): Unable to allocate memory for pool. in _registry_check_code() (line 3202 of /code/includes/bootstrap.inc).
```

A ```kbos restart``` subsides the issue for a few more mins, then it comes back.

Thoughts?

**Comment by pirog** [comment]
I havent seen this but i would recommend reducing your php memory limit and
see if that resolves the issue as a workaround for now.

On Tue, Oct 13, 2015 at 5:45 PM, John Ouellet <notifications@github.com>
wrote:

> Hello,
>
> Every site I use after a few minutes I start to get this:
>
> Warning: include_once(): Unable to allocate memory for pool. in drupal_load() (line 1145 of /code/includes/bootstrap.inc).
> Warning: require_once(): Unable to allocate memory for pool. in _registry_check_code() (line 3202 of /code/includes/bootstrap.inc).
>
> A kbos restart subsides the issue for a few more mins, then it comes back.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/585>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 did reducing the mem limit resolve your issue?

**Comment by reynoldsalec** [comment]
@pirog + @labboy0276 

Kalabox 0.12.0-alpha3 on Mac OSX

I experienced this in getting a large site (Greenbiz) running on Kalabox and trying to reindex the Solr database.

1. Pull down site
2. Post 5.x schema (was required for this site...not sure why).
3. Try reindexing

I got a bunch of these two errors

```
Warning: require_once(): Unable to allocate memory for pool. in _registry_check_code() (line 3227 of /code/includes/bootstrap.inc).

Warning: require_once(): Unable to allocate memory for pool. in ctools_plugin_load_includes() (line 477 of /code/profiles/panopoly/modules/contrib/ctools/includes/plugins.inc).
```

**Proposed Solution**

I believe that following the suggestions of https://www.drupal.org/node/1154448#comment-8701087 and upping the apc.shm_size in config/php/apc.ini  to 256M solved the issue.

@pirog do you see downsides of increase the apc.shm_size? If this might present problems to users of "normal"-sized sites, perhaps we should make this available in the future as a feature for "large" Drupal sites but for now just provide documentation.

**Comment by labboy0276** [comment]
+1 i did notice this the other day with CSi, but thought it was the site itself.

**Comment by pirog** [comment]
@labboy0276 def let us know if you see it again and if bumping the `apc.shm_size` resolves the issue.

@reynoldsalec no, i don't. that said i think `96M-128M` is probably **MORE** than sufficient for a *normal* drupal site.

**Comment by labboy0276** [comment]
@pirog I saw this the other day with csi and bumping the apc.shm_size to 256M and it resolved said issue for right now.

**Comment by pirog** [comment]
Good to know. This is an easy fix so we will probably add it to the beta1 sprint.

**Comment by pirog** [comment]
PULL REQUEST: https://github.com/kalabox/kalabox-app-pantheon/pull/139
