### ISSUE TITLE
Getting error with npm install -g kalabox

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#590]
Getting this error when trying to upgrade.

1 warning generated.
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "kalabox"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path /usr/local/lib/node_modules/kalabox/bin/kbox.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/kalabox/bin/kbox.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by pirog** [comment]
@yosefromano try instaling using the binary and not with `npm`

**Comment by pirog** [comment]
@bcauldwell i think this probably wont be an issue as soon as we resolve #525 ?

**Comment by yosefromano** [comment]
Got it.
