### ISSUE TITLE
"kbox create pantheon" unnecessarily re-downloads kalabox-app-pantheon tarball

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#596]
I just did a fresh binary install of alpha3 then ran ```kbox create pantheon``` for one site and then for another site. The second time, I noticed the following, which implies that the command is downloading the kalabox-app-pantheon tarball a second time rather than using a locally cached version.
```
Building your app...
     fetch : https://github.com/kalabox/kalabox-app-pantheon/tarball/v0.10.3
```
Just pointing out a minor inefficiency.

**Comment by pirog** [comment]
+1 moving this into the alpha5 sprint. 

We are going to want to make sure that if the user is in "devMode" that we keep pulling the latest cod.

**Comment by pirog** [comment]
This probably should not be attempted until improvements in #1223

**Comment by pirog** [comment]
In the forthcoming `0.13.x` release we store the apps locally so this is now NA
