### ISSUE TITLE
Drush issues with features-revert all on aliases.

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#612]
```
$ kbox drush @pantheon.kalablog.dev features-revert-all -y
Warning: Permanently added '[appserver.dev.GOBLEDYGOOK.drush.in]:2222,[XX.XXX.XXX.XXXX]:2222' (RSA) to the list of known hosts.
The drush command 'features-revert-all' could not be found.  Run         [error]
`drush cache-clear drush` to clear the commandfile cache if you have
installed new extensions.
The directory /code does not contain a valid Drupal installation         [error]
```
runnning drush cache-clear drush on @pantheon.kalablog.dev works.

**Comment by pirog** [comment]
Actually just fixed this recently for alpha5.

You might want to try passing in --root=. As a short term workaround

On Thursday, October 22, 2015, Thiago de Mello Bueno <
notifications@github.com> wrote:

> $ kbox drush @pantheon.kalablog.dev features-revert-all -y
> Warning: Permanently added '[appserver.dev.GOBLEDYGOOK.drush.in]:2222,[XX.XXX.XXX.XXXX]:2222' (RSA) to the list of known hosts.
> The drush command 'features-revert-all' could not be found.  Run         [error]
> `drush cache-clear drush` to clear the commandfile cache if you have
> installed new extensions.
> The directory /code does not contain a valid Drupal installation         [error]
>
> runnning drush cache-clear drush on @pantheon
> <https://github.com/pantheon>.kalablog.dev works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/612>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
