### ISSUE TITLE
kbox update fails

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#613]
Hi there,

1) Ran the uninstall script (installed virtualbox too)
2) Downloaded latest binary, renamed it kbox, moved it to /usr/local/bin, set permission to execute
3) `kbox`
4) "Looks like there are updates required...)
5) `kbox update`
6) Installer fails at step 11/16:

``````
info: -- Step 11/16 --
info: Setting up and activating the engine...
info: TypeError: Object function lodash(value) {
      if (isObjectLike(value) && !isArray(value) && !(value instanceof LazyWrapper)) {
        if (value instanceof LodashWrapper) {
          return value;
        }
        if (hasOwnProperty.call(value, '__chain__') && hasOwnProperty.call(value, '__wrapped__')) {
          return wrapperClone(value);
        }
      }
      return new LodashWrapper(value);
    } has no method 'round'
info: -- INSTALL FAILURE. --
``````

**Comment by pirog** [comment]
If you ran the uninstall script it shouldn't tell you to update. Are you
sure you went through that?

On Thursday, October 22, 2015, pi-ron <notifications@github.com> wrote:

> Hi there,
>
> 1) Ran the uninstall script (installed virtualbox too)
> 2) Downloaded latest binary, renamed it kbox, moved it to /usr/local/bin,
> set permission to execute
> 3) kbox
> 4) "Looks like there are updates required...)
> 5) kbox update
> 6) Installer fails at step 11/16:
>
> info: -- Step 11/16 --
> info: Setting up and activating the engine...
> info: TypeError: Object function lodash(value) {
>       if (isObjectLike(value) && !isArray(value) && !(value instanceof LazyWrapper)) {
>         if (value instanceof LodashWrapper) {
>           return value;
>         }
>         if (hasOwnProperty.call(value, '__chain__') && hasOwnProperty.call(value, '__wrapped__')) {
>           return wrapperClone(value);
>         }
>       }
>       return new LodashWrapper(value);
>     } has no method 'round'
> info: -- INSTALL FAILURE. --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/613>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
Went through the uninstall script?

Yeh I did, it seems like it thinks kalabox is already installed and just needs to be updated.

**Comment by pi-ron** [comment]
But virtualbox is non-existent so it's always going to break.

**Comment by pi-ron** [comment]
I tried running the uninstall script again and re tried but got the same update message.  Can I manually uninstall any remaining kalabox stuff somehow?

**Comment by pirog** [comment]
I'm not exactly sure what you are describing to me here.

On Thursday, October 22, 2015, pi-ron <notifications@github.com> wrote:

> But virtualbox is non-existent so it's always going to break.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/613#issuecomment-150358162>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
Ok, I can't remember which version I was running previously, but I ran the uninstaller, then downloaded the latest release and ran the steps outlined on the wiki.

**Comment by pirog** [comment]
Can you paste in how you ran the uninstaller? Cause it seems like it is def
not uninstalling

On Thursday, October 22, 2015, pi-ron <notifications@github.com> wrote:

> Ok, I can't remember which version I was running previously, but I ran the
> uninstaller, then downloaded the latest release and ran the steps outlined
> on the wiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/613#issuecomment-150358779>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
``````
Roamings-iMac:Downloads RoamingMac$ ./uninstall-darwin.sh

Welcome to the Kalabox uninstaller script.

This script will destroy your current Kalabox build. If you want
to save your current build for later please either vagrant package
your existing build or export the relevant VirtualBox appliance.

MAKE SURE THAT YOU'VE EXITED THE KALABOX APP OR THIS WILL BLOW UP!!!
ALSO MAKE SURE YOU VISIT 127.0.0.1:60008 AND SHUTDOWN SYNCTHING

WHAT YOU WANT TO DO?

1. Remove all the things.
2. Forget this ever happened.

1
The uninstallation process requires administrative privileges
because some of the installed files cannot be removed by a
normal user. You may now be prompted for a password...
Let's get it started
The following files and directories will be removed:
    /Applications/boot2docker.app
    /Users/RoamingMac/.kalabox/.provider
    /Users/RoamingMac/.kalabox/provisioned
    /Users/RoamingMac/VirtualBox VMs/Kalabox2


    /Users/RoamingMac/.kalabox/.provider/profile
    /etc/resolver/kbox
    /Users/RoamingMac/.kalabox/syncthing
    /Users/RoamingMac/.kalabox/bin/syncthing
    /Users/RoamingMac/.kalabox/appRegistry.json
    /Users/RoamingMac/.kalabox/installed.json
    /Users/RoamingMac/.ssh/boot2docker.kalabox.id_rsa
    /Users/RoamingMac/.ssh/boot2docker.kalabox.id_rsa.pub
Kalabox2 has been successfully uninstalled!

We will now prompt you to uninstall VirtualBox.
THIS STEP IS OPTIONAL!

Preparing to uninstall VirtualBox

No VirtualBox files, directories, KEXTs or packages to uninstall.
Done.
``````

**Comment by pi-ron** [comment]
That was the latest attempt.  Previously I ran an uninstaller that was in the scripts directory of the old kalabox binary I had in Downloads folder.

**Comment by pi-ron** [comment]
Can I manually remove the ~/.kalabox directory?

**Comment by pi-ron** [comment]
...going to try that

**Comment by pi-ron** [comment]
Have had success, can create new apps again 
:+1:

**Comment by pirog** [comment]
Ohhh ok. So i'm going to try to reproduce this then

**Comment by pirog** [comment]
marking as duplicate and redirecting to #594
