### ISSUE TITLE
Validate push/pull database/files pantheon options before we kick off a push/pull

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#617]
Kbox pull fails on a Pantheon site.  The site starts and runs all good locally.

``````
###############################################################

                       HOLLA!!!!!!

  Your app has started up correctly. Here are some vitals:

  URL: http(s)://wool-beach-house.kbox
  LOCATION: /Users/RoamingMac/Sites/wool-beach-house

###############################################################
Roamings-iMac:wool-beach-house RoamingMac$ kbox pull -- --database
? Which files do you want to use? dev
info: DOCKER =>  Creating ad hoc container
``````

``````
From ssh://codeserver.dev.ea1411d9-a029-4367-acad-7be7eee1d08a.drush.in:2222/~/repository
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Not found.

Error: Not found.

    at Request.<anonymous> (/Users/RoamingMac/Sites/wool-beach-house/plugins/kalabox-plugin-pantheon/lib/client.js:386:21)
    at Request.emit (events.js:85:15)
    at Request.mixin._fireSuccess (/Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:223:12)
    at /Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:161:20
    at parsers.auto (/Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:402:7)
    at Request.mixin._encode (/Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:198:29)
    at /Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:157:16
    at Request.mixin._decode (/Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:173:7)
    at null.<anonymous> (/Users/RoamingMac/Sites/wool-beach-house/node_modules/restler/lib/restler.js:150:14)
    at emit (events.js:98:20)
    at _stream_readable.js:883:16
From previous event:
    at /Users/RoamingMac/Sites/wool-beach-house/plugins/kalabox-plugin-pantheon/lib/client.js:382:14
    at /Users/RoamingMac/Sites/wool-beach-house/node_modules/retry-bluebird/retry-bluebird.js:29:14
    at rec (/Users/RoamingMac/Sites/wool-beach-house/node_modules/retry-bluebird/retry-bluebird.js:28:23)
    at /Users/RoamingMac/Sites/wool-beach-house/node_modules/retry-bluebird/retry-bluebird.js:37:18
    at process._tickCallback (node.js:812:13)
``````

**Comment by pirog** [comment]
@pi-ron is this happening on all your sites or just specific ones?

**Comment by pi-ron** [comment]
@pirog I just tested on two sites and it worked well, only difference was I used `kbox pull` only without specifying database via `-- --database`.  It asked me which environment to pull database/files from (THIS IS AWESOME).

I'll try with `kbox pull -- --database`

**Comment by pirog** [comment]
ohhhh ok. so run `kbox pull -- -h` cause the `--database` flag is a little
different now!

On Mon, Oct 26, 2015 at 1:40 PM, pi-ron <notifications@github.com> wrote:

> @pirog <https://github.com/pirog> I just tested on two sites and it
> worked well, only difference was I used kbox pull only without specifying
> database via -- --database. It asked me which environment to pull
> database/files from (THIS IS AWESOME).
>
> I'll try with kbox pull -- --database
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/617#issuecomment-151277979>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pi-ron** [comment]
hmmm it fails when I use:

`kbox pull -- --database` which I'm probably not going to use anymore anyway thanks to the shiny new prompts!

**Comment by pi-ron** [comment]
Ok cool, what's the -h for?

**Comment by pirog** [comment]
it just shows you the available options for the `kbox pull` command
shorthand for `--help`

On Mon, Oct 26, 2015 at 1:43 PM, pi-ron <notifications@github.com> wrote:

> Ok cool, what's the -h for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/617#issuecomment-151278545>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
```
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
  --database     Pull DB from an env. Options are dev, test, live and none
                                                                        [string]
  --files        Pull files from an env. Options are dev, test, live and none
                                                                        [string]
  --newbackup    True to generate a new DB backup                      [boolean]
```

**Comment by pi-ron** [comment]
ahh... right

Thanks :+1:

**Comment by pirog** [comment]
Going to actually reopen this and change the title to say we should validate the options before before we kick off a build

**Comment by pirog** [comment]
ok, added some basic logic for this

if you use the older --database and --files without specifying an ENV it will just pull from the ENV In your kalabox.json 

will be in alphaFIVER
