### ISSUE TITLE
Adding required apps

### ISSUE THREAD

**Issue by geraldvillorente** [kalabox/kalabox#618]
Is there a documentation about provisioning needed application and its configuration like what Chef doing?

Regards

**Comment by pirog** [comment]
@geraldvillorente im not exactly sure what you are asking. by default kalabox uses docker containers that can live either on the docker hub or locally in dockerfiles. 

how you create these containers is up to you so you could use chef, puppet or the usual config management tools. as long as you end up with a docker container you should be good. 

i would check out https://github.com/kalabox/kalabox-app-pantheon as an example of how to create specific kinds of app start states.

**Comment by geraldvillorente** [comment]
thanks @pirog the example you posted is a good start. What I want is to have an environment where it matches my production setup like what `kalabox-app-pantheon` is trying to do. Where almost everything (configurations, versions, requirements) are identical (prod - stage - dev) with an ability to setup it easily as for newbie where they don't have enough knowledge in ops related matters.

**Comment by geraldvillorente** [comment]
Correct me if my understanding of Kalabox is wrong.

**Comment by pirog** [comment]
Yes that is more or less the understanding. Ideally you would be running docker containers in your prod environment and be spinning up a custom kalabox app using those same containers plus adding in easy to use "tasks" for push/pull and relevant tooling like drush/node/etc.

**Comment by geraldvillorente** [comment]
thank you so much @pirog.
