### ISSUE TITLE
Implement pantheon's varnish configuration when creating a pantheon app

### ISSUE THREAD

**Issue by jeffesquivels** [kalabox/kalabox#633]
I want to use kalabox to debug an issue we're having with pantheon but it seems to be non-reproducible (in kalabox as well as our local environments) and it may be because kalabox is still missing the varnish part of pantheon.

I think it would be useful to have varnish configured and deployed when creating a pantheon app.

Thanks,

**Comment by pirog** [comment]
+1 i think this would be a great feature!

**Comment by pirog** [comment]
@jeffesquivels im moving this into our alpha6 milestone and assigning it to me but just so i know to keep track of this issue not because im actually going to do it!

**Comment by jeffesquivels** [comment]
@pirog ok, got it!

Do we have a roadmap document (or something similar) with the deadlines for each milestone? (I checked the wiki but didn't find anything)

**Comment by pirog** [comment]
We are using the zenhub extension for github. this should give you access
to both the burndown chart and the kanban board for the current sprint from
https://github.com/kalabox/kalabox

On Thu, Oct 29, 2015 at 10:57 AM, Jeffrey Esquivel S. <
notifications@github.com> wrote:

> @pirog <https://github.com/pirog> ok, got it!
>
> Do we have a roadmap document (or something similar) with the deadlines
> for each milestone? (I checked the wiki but didn't find anything)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/633#issuecomment-152266088>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@jeffesquivels 
i think https://github.com/ManatiCR/kalabox-app-pantheon/pull/1 gets us pretty far once merged but we still need to address the following things

- [ ] why aren't external things like css being loaded when we go to https?
- [ ] remove ssl support from the appserver in favor of the edge
- [ ] move the appserver http requests to a different port than 80 and use that (cheap way to not expose our appserver without going through the edge)
