### ISSUE TITLE
On initial kbox pull for a pantheon site, grab a files archive, instead of rsync. 

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#635]
If you have a huge project with a lot of files, pulling files with rsync is very slow, no matter what internet connection you have.
It would be nice to be able to load a backup instead of using rsync.

maybe something like:
kbox backup load

and offer options to either pick a backup from a local location, or from pantheon

**Comment by pirog** [comment]
Ok, so having talked with @gremy and getting some of his great feedback i think the best way to go here might be

1. on initial site pull down the files via an archive and just extract them over, this should be significantly faster than an initial rsync
2. on subsequent pulls use rsync 

i think this would provide the optimal user experience and not clutter kbox with too many additional commands. does this sound about right @gremy?

**Comment by pirog** [comment]
So another potential concern here is if the user has no created a files backup yet. Presumably if they have not done this they have a relatively small files directory anyway and NBD. If for whatever reason they have Donald J. Trump HUGE files dir that is not backed up this could actually end up taking longer than rsync.
