### ISSUE TITLE
RSYNC from host machine to application

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#636]
Would like an option on kbox rsync to make it easy to rsync files from the host machine into the application container.

At the moment the only use for kbox rsync is to sync from a ssh source (most likely pantheon)

**Comment by pirog** [comment]
i think ultimately we are going to use NFS on the "media" mount, which in the drupal case would be your `sites/default/files` directory. This would allow you to just drop in some files on the host side and have those show up in the container.

See #511 for the meta issue about this.
