### ISSUE TITLE
Error 500 on AJAX requests

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#649]
On a project of mine I am getting "Error 500 - Internal Server Error" on AJAX requests.
For example I go into a Views configuration and want to choose a formatter for a field that makes an AJAX call for additional settings.
![screen shot 2015-10-30 at 14 36 28](https://cloud.githubusercontent.com/assets/1007285/10845797/ac053e64-7f13-11e5-92b7-24f67e27c22d.png)
![screen shot 2015-10-30 at 14 56 06](https://cloud.githubusercontent.com/assets/1007285/10846209/7640fcf2-7f16-11e5-8b2d-a7ebc69e7f6a.png)

**Comment by pirog** [comment]
What makes you think this is kalabox related?

On Friday, October 30, 2015, Emanuel Greucean <notifications@github.com>
wrote:

> On a project of mine I am getting "Error 500 - Internal Server Error" on
> AJAX requests.
> For example I go into a Views configuration and want to choose a formatter
> for a field that makes an AJAX call for additional settings.
> [image: screen shot 2015-10-30 at 14 36 28]
> <https://cloud.githubusercontent.com/assets/1007285/10845797/ac053e64-7f13-11e5-92b7-24f67e27c22d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/649>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by gremy** [comment]
Sorry. I thought it was a KBOX issue, it is a Views RSS issue. I tested on pantheon, and it crashes there as well.
