### ISSUE TITLE
DNS has trouble resolving in some circumstances

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#651]
https://github.com/kalabox/kalabox-app-pantheon/issues/44

**Comment by pirog** [comment]
So there are two variants to this issue that might be related.

1. lookup index.docker.io on 204.11.104.3:53: server misbehaving
2. lookup index.docker.io: no such host

We also have another one that is related to timing out but i think this should be separate since it is either 1.) bad internet connection, 2.) being behind a proxy/vpn and the error message indicates this fairly well.

**Comment by pirog** [comment]
`sudo /etc/init.d/docker restart` to restart the docker daemon in b2d

**Comment by pirog** [comment]
I was able to recreate server misbehaving by having VB on. closing the macbook, opening the macbook, closing it again and then trying.

**Comment by pirog** [comment]
So more details on server misbehaving: 

1. `sudo /etc/init.d/docker restart` does nothing.
2. Can't even ping google.com from the VM
3. https://github.com/boot2docker/boot2docker/issues/357#issuecomment-47621318 also doesnt work

**Comment by pirog** [comment]
I've applied `VBoxManage modifyvm boot2docker-vm --natdnshostresolver1 on` and going to see if i can recreate the issue

**Comment by pirog** [comment]
I tried to replicate any of these for quite awhile and was not able to do so reliably. I think the following things are significant factors though

1. Changing networks
2. Computer going to sleep
3. Kalabox2 VM being up

**Comment by pirog** [comment]
Tried more things to replicate including bouncing between different countries on the VPN and still no dice. As of now i think our best bets are 

1. Implement `VBoxManage modifyvm boot2docker-vm --natdnshostresolver1 on`
2. Do a `kbox down && kbox up` for certain kinds of fails

**Comment by jeffesquivels** [comment]
I can confirm that after suspending in Ubuntu 15.04 vboxnet0 won't come back (which means no communication is possible at all with the B2D VM, including DNS queries).

This may be related to an Ubuntu bug where the wifi is disabled after resuming from suspend (thus requiring the user to enable it again manually).

**Comment by pirog** [comment]
If you shutdown the KB2 VM in VB and then try again does it resolve correctly?

**Comment by jeffesquivels** [comment]
@pirog yes, but the VM needs to be shutdown directly from VirtualBox, kbox down will try to communicate with the VM first and fail because there's no network to communicate through.

This seems to be the Ubuntu bug I was referring to: https://bugs.launchpad.net/ubuntu/+source/wpa/+bug/1422143, I'll ask someone who's not having this specific issue with wifi to test and see if they have the same behaviour with vboxnet0 not coming back properly.

**Comment by jeffesquivels** [comment]
Ok, it seems the two issues are unrelated, as doing:

$ sudo /bin/systemctl restart network-manager.service

After resume solves the issue for wifi but not for vboxnet0, I think this may be the problem we're having:

https://www.virtualbox.org/ticket/13873

I can confirm that another way to enable networking back is to go to "VirtualBox -> File -> Preferences -> Network -> Host-only Networks -> vboxnet0 -> edit" not changing anything and then just clicking Ok and Ok again in the preferences window.
