### ISSUE TITLE
The Pantheon Apache Solr service in the kalabox environment did not respond: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#653]
Hello!

Seeing this error when I go here:

admin/config/search/pantheon in my site:

The Pantheon Apache Solr service in the kalabox environment did not respond: SSL certificate problem: self signed certificate

SolR won't work locally now cause of it.

Thoughts?

**Comment by pirog** [comment]
This is not an issue with kalabox. You just need to make sure you are whitelisting any self signed certs.

**Comment by labboy0276** [comment]
It seems they only way to remedy this is to destroy the app and recreate.  I tried clearing all my browser caches and that didnt help it either.

**Comment by pirog** [comment]
My guess here is we aren't clearing out old certs when we do a rebuild.

**Comment by pirog** [comment]
OK here are the steps to replicate

1. `kbox create pantheon` (make sure you have latest drops7)
2. Start up app and login to site
2. Post your schema
3. `kbox rebuild`
4. Restart site and check pantheon apache solr status

![screen shot 2015-11-04 at 12 20 41 pm](https://cloud.githubusercontent.com/assets/713424/10950800/89807c94-82ee-11e5-9834-3b05e2cab4ad.png)

**Comment by nikstoltzfus** [comment]
I see this was marked as closed. I'm using release 0.11.2 and ran into this issue having posted schema w/out rebuild. Is there something else I need to do to fix?

Here's the drush response:

`$ kbox drush solr-index`
`info: COMPOSE =>  0=--project-name, 1=site-name, 2=--file, 3=/path/to/kalabox-compose.yml, 4=--file, 5=/path/to/kalabox-cli.yml, 6=--file, 7=/path/to/kalabox-cli.yml, 8=run, 9=-d, 10=--entrypoint, 11=tail, 12=terminus, 13=-f, 14=/dev/null, mode=false`
`WD pantheon_apachesolr: Error SSL certificate problem: self signed   [error]
certificate connecting to
https://solr/sites/self/environments/kalabox/index/admin/ping on port
449`
`Creating default object from empty value                             [warning]`
`Pantheon_Apache_Solr_Service.php:514`
`WD Apache Solr: No Solr instance available during indexing.          [error]`

**Comment by pirog** [comment]
Definitely was fixed but we did change some stuff when we switched to docker compose that may have caused this to show up again. Reopening and will investigate.

**Comment by pirog** [comment]
We are going to look into this after we've rolled out our native installers in the 0.12.x milestone.

**Comment by pirog** [comment]
@nikstoltzfus we will be looking to get a fix in for this into the 0.12.0-alpha2 release
