### ISSUE TITLE
Unable to run civicrm in kalabox since upgrade

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#658]
Civcrm was working well in kalabox version 0.9
Now that I upgraded, the site breaks when civicrm is disabled.
I get this error when going to mysite.kbox

Initialization Error

Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => simpleHandler
        )

    [code] => -24
    [message] => DB Error: connect failed
    [mode] => 16
    [debug_info] =>  [nativecode=php_network_getaddresses: getaddrinfo failed: Name or service not known]
    [type] => DB_Error
    [user_info] =>  [nativecode=php_network_getaddresses: getaddrinfo failed: Name or service not known]
    [to_string] => [db_error: message="DB Error: connect failed" code=-24 mode=callback callback=CRM_Core_Error::simpleHandler prefix="" info=" [nativecode=php_network_getaddresses: getaddrinfo failed: Name or service not known]"]
)

**Comment by yosefromano** [comment]
This is the code I have in civicrm.settings.php


// Kalabox settings
 	elseif (strpos($_SERVER['HTTP_HOST'],'kbox') !== false) {
 		// Set the DB connection string
 		$db_string = $env['databases']['default']['default']['driver'] . '://' . $env['databases']['default']['default']['username'] . '@';
 		$db_string .= $env['databases']['default']['default']['host'] .  '/' . $env['databases']['default']['default']['database'] . '?new_link=true';
 		define( 'CIVICRM_UF_DSN'           , $db_string);
 		define( 'CIVICRM_DSN'           , $db_string);
 		global $civicrm_root;
 		$civicrm_root = '/code/profiles/civicrm_starterkit/modules/civicrm/';
 		define( 'CIVICRM_TEMPLATE_COMPILEDIR', '/code/sites/default/files/private/civicrm/templates_c/' );
 		define( 'CIVICRM_UF_BASEURL'      , 'http://' . $_SERVER['HTTP_HOST'] . '/' );
 	}

**Comment by pirog** [comment]
try  running a `kbox rebuild` inside of that app and then start the app up again.

**Comment by yosefromano** [comment]
Same error comes up

**Comment by pirog** [comment]
@yosefromano will spin up a civicrm site on pantheon and try to replicate this. Ideally we want to get a patch into civicrm-drops7 so this works out of the box. last time i checked they could benefit from using new pantheon env for database stuff.

**Comment by pirog** [comment]
@yosefromano this code seems to work for me both locally on kalabox and also on pantheon

```php
 /**
 * Pantheon Systems:
 *
 * Repopulate needed variables based on the Pantheon environment if applicable.
 * http://www.kalamuna.com/news/civicrm-pantheon
 *
 */
if (defined('PANTHEON_ENVIRONMENT')) {

    // Kick off dbsetup
    // Grab some ENV
    $user = getenv('DB_USER');
    $password = getenv('DB_PASSWORD');
    $host = getenv('DB_HOST');
    $port = getenv('DB_PORT');
    $database = getenv('DB_NAME');
    // Set driver
    // @todo: grab correct driver?
    $db_string = 'mysql://';
    // Add user name and password
    $db_string .= (!empty($password)) ? implode(':', [$user, $password]) : $user;
    // Add host
    // @todo: might not have a port?
    $db_string .= '@' . implode(':', [$host, $port]);
    // Add database
    $db_string .= '/' . $database;
    // Add query
    $db_string .= '?new_link=true';

    // define the database strings
    define('CIVICRM_UF_DSN', $db_string);
    define('CIVICRM_DSN', $db_string);

    // define the file paths
    global $civicrm_root;

    // Get the correct pantheon binding
    // @todo: better existence checks here?
    $env = json_decode($_SERVER['PRESSFLOW_SETTINGS'], TRUE);
    $binding = $env['conf']['pantheon_binding'];

    $civicrm_root = '/srv/bindings/' . $binding . '/code/profiles/civicrm_starterkit/modules/civicrm';
    define('CIVICRM_TEMPLATE_COMPILEDIR', '/srv/bindings/' . $binding . '/files/civicrm/templates_c/');

    // Use Drupal base url and path
    global $base_url, $base_path;
    define( 'CIVICRM_UF_BASEURL', $base_url . '/');
    define( 'CIVICRM_SITE_KEY', '55a5db24629af4702f338c0a203b6ce9' );

    /**
    * This setting logs all emails to a file. Useful for debugging any mail (or civimail) issues.
    * This will not send any email, so ensure this is commented out in production
    */
    $no_mail = ['kalabox', 'dev', 'test'];
    if ( in_array(PANTHEON_ENVIRONMENT, $no_mail) ){
     define( 'CIVICRM_MAIL_LOG', '/srv/bindings/' . $binding . '/code/sites/default/files/civicrm/templates_c/mail.log' );
    }

    // Add this line only once above any settings overrides
    global $civicrm_setting;
    $civicrm_setting['Directory Preferences']['extensionsDir'] = '/srv/bindings/' . $binding . '/code/sites/all/extensions/';
    $civicrm_setting['URL Preferences']['userFrameworkResourceURL'] = $base_url . 'sites/all/extensions';

} else {
```

You will want to replace the relevant section of your `civicrm.settings.php` with this

**Comment by pirog** [comment]
@yosefromano i've opened an "issue" over at the civicrm starter kit which is ultimately what we need to edit in order to get this to work out of the box. I'm going to close this so we can direct our efforts over there
https://github.com/kreynen/civicrm-starterkit-drops-7/pull/1

**Comment by pirog** [comment]
@yosefromano there is now an open pull request against the civicrm starterkit upstream for kalabox2 support
https://github.com/kreynen/civicrm-starterkit-drops-7/pull/2

**Comment by seanr** [comment]
Would it make more sense to place the Pantheon stuff in an extra civicrm.settings.pantheon.php the way they do with the Drupal settings file?

**Comment by pirog** [comment]
@seanr i suspect that could be an easy option.
