### ISSUE TITLE
See this at end of kbox create file downloads for 0.10.5

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#660]
I saw this the other day and ignored it, but the 3 sites I just created, it happens every time:

```
files_zendesk/apps/blackberry/cods/Storm/95nn/Huddle-3.cod
files_zendesk/apps/blackberry/cods/Curve/85nn/Huddle.jad
files_zendesk/apps/blackberry/cods/Pearl/91nn/Huddle-1.cod
files_zendesk/gartner.jpg
files_zendesk/.htaccess
files_zendesk/skipped.log
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.addListener (events.js:139:15)
    at ReadStream.Stream.pipe (stream.js:96:10)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:808:23
    at tryCatcher (/usr/local/bin/node_modules/bluebird/js/main/util.js.jx:25:23)
    at Promise._settlePromiseFromHandler (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:506:31)
    at Promise._settlePromiseAt (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:580:18)
    at Promise._settlePromises (/usr/local/bin/node_modules/bluebird/js/main/promise.js.jx:696:14)
    at Async._drainQueue (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:122:16)
    at Async._drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:132:10)
    at Async.drainQueues (/usr/local/bin/node_modules/bluebird/js/main/async.js.jx:14:14)
    at process._tickCallback (node.js:812:13)
```

Thoughts?

**Comment by pirog** [comment]
Which sites and what do they have in common?

**Comment by labboy0276** [comment]
huddle and cor, we didnt build them bla ha ha

On Tue, Nov 3, 2015 at 6:28 PM, Mike Pirog <notifications@github.com> wrote:

> Which sites and what do they have in common?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/660#issuecomment-153522828>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 does this actually prevent you from pulling down a site? I've grabbed both huddle and cor and not seen this.

**Comment by labboy0276** [comment]
I can pull it down, but not all the files are there.  I usually have to do
a kbox pull post fact when that happens.

On Wed, Nov 4, 2015 at 12:04 PM, Mike Pirog <notifications@github.com>
wrote:

> @labboy0276 <https://github.com/labboy0276> does this actually prevent
> you from pulling down a site? I've grabbed both huddle and cor and not seen
> this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/660#issuecomment-153793213>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@labboy0276 im going to close this in favor of the one @gremy opened since its got some more details in it 

#693
