### ISSUE TITLE
errors that occur in GUI can put GUI in an unusable state

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#666]
Errors that occur in GUI can put GUI in an unusable state. Instead they should be caught and reported in a standard way.

**Comment by pirog** [comment]
@bcauldwell this is what you wasted issue 666 for? :imp:

**Comment by bcauldwell** [comment]
Whoops!

On Wed, Nov 4, 2015 at 12:12 PM, Mike Pirog <notifications@github.com>
wrote:

> @bcauldwell <https://github.com/bcauldwell> this is what you wasted issue
> 666 for? [image: :imp:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/666#issuecomment-153849554>.
>



-- 
- Benjamin Cauldwell

**Comment by labboy0276** [comment]
way to ruin EVERYTHING

On Wed, Nov 4, 2015 at 4:04 PM, bcauldwell <notifications@github.com> wrote:

> Whoops!
>
> On Wed, Nov 4, 2015 at 12:12 PM, Mike Pirog <notifications@github.com>
> wrote:
>
> > @bcauldwell <https://github.com/bcauldwell> this is what you wasted
> issue
> > 666 for? [image: :imp:]
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox/issues/666#issuecomment-153849554>.
> >
>
>
>
> --
> - Benjamin Cauldwell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/666#issuecomment-153864989>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by bcauldwell** [comment]
GUI error handling and reporting upgraded +5.
