### ISSUE TITLE
Error while creating an app

### ISSUE THREAD

**Issue by imorale2** [kalabox/kalabox#667]
Hi, I get the following error while running kbox update. I tried fixing it using previous issues, but no luck. 

info: -- Step 1/19 --
info: Authorizing trilling subroutines...
info: Non-interactive mode.
info: -- OK! 5% complete! --

info: -- Step 2/19 --
info: Adding syncthing image to build list...
info: -- OK! 11% complete! --

info: -- Step 3/19 --
info: Queuing up syncthing downloads...
info: -- OK! 16% complete! --

info: -- Step 4/19 --
info: Checking firewall settings...
info: -- OK! 21% complete! --

info: -- Step 5/19 --
info: Adding services images to build list...
info: -- OK! 26% complete! --

info: -- Step 6/19 --
info: Queuing provider admin commands...
info: -- OK! 32% complete! --

info: -- Step 7/19 --
info: Queuing up provider downloads...
info: -- OK! 37% complete! --

info: -- Step 8/19 --
info: Checking for available disk space...
info: -- OK! 42% complete! --

info: -- Step 9/19 --
info: Checking for Internet access...
info: -- OK! 47% complete! --

info: -- Step 10/19 --
info: Downloading files...
info: -- OK! 53% complete! --

info: -- Step 11/19 --
info: Running admin install commands...
info: -- OK! 58% complete! --

info: -- Step 12/19 --
info: Updating install info...
info: -- OK! 63% complete! --

info: -- Step 13/19 --
info: Setting up and activating the engine...
info: COULD NOT FIND OLD B2D KEYS => /Users/imorale2/.ssh/id_boot2docker
info: BOOT2DOCKER =>  Starting up. disksize=124900, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa" --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh: /usr/local/bin/boot2docker: No such file or directory

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at module.exports (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
    at Promise.try.then.then.then.shareCmd (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:467:14)
From previous event:
    at Object.up (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:466:6)
From previous event:
    at /usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:253:39
From previous event:
    at step.all (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:252:8)
    at /usr/local/bin/lib/install/framework.js.jx:452:17
    at /usr/local/bin/lib/install/framework.js.jx:450:30
From previous event:
    at Promise.each.then.events.emit.state (/usr/local/bin/lib/install/framework.js.jx:442:29)
From previous event:
    at /usr/local/bin/lib/install/framework.js.jx:432:22
    at /usr/local/bin/lib/install.js.jx:178:5
    at Object.exports.run (/usr/local/bin/lib/install.js.jx:168:18)
    at Object.task.func (/usr/local/bin/plugins/kalabox-core/tasks/update.js.jx:21:24)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:173:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:236:12)
    at process._tickCallback (node.js:812:13)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:235:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:244:1)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
    at Object.Module._extensions..jx (module.js:1711:10)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (_jx_source:17:3)
    at Module._compile (module.js:518:26)
    at Module.load (module.js:353:12)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:733:12)
    at startup (node.js:371:18)
    at node.js:1464:3
info: BOOT2DOCKER =>  Initializing boot2docker [2].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa" --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh: /usr/local/bin/boot2docker: No such file or directory

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: BOOT2DOCKER =>  Initializing boot2docker [3].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa" --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh: /usr/local/bin/boot2docker: No such file or directory

    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
From previous event:
    at sh (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
    at shProvider (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
    at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
    at rec (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
    at /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
    at process._tickCallback (node.js:812:13)
info: VError: Error initializing boot2docker.: BOOT2DOCKER =>  Initializing boot2docker failed, retrying.
info: -- INSTALL FAILURE. --

**Comment by pirog** [comment]
Looks like you don't have boot2docker installed? Can you verify if you have
it installed or not?

On Wed, Nov 4, 2015 at 1:00 PM, imorale2 <notifications@github.com> wrote:

> Hi, I get the following error while running kbox update. I tried fixing it
> using previous issues, but no luck.
>
> info: -- Step 1/19 --
> info: Authorizing trilling subroutines...
> info: Non-interactive mode.
> info: -- OK! 5% complete! --
>
> info: -- Step 2/19 --
> info: Adding syncthing image to build list...
> info: -- OK! 11% complete! --
>
> info: -- Step 3/19 --
> info: Queuing up syncthing downloads...
> info: -- OK! 16% complete! --
>
> info: -- Step 4/19 --
> info: Checking firewall settings...
> info: -- OK! 21% complete! --
>
> info: -- Step 5/19 --
> info: Adding services images to build list...
> info: -- OK! 26% complete! --
>
> info: -- Step 6/19 --
> info: Queuing provider admin commands...
> info: -- OK! 32% complete! --
>
> info: -- Step 7/19 --
> info: Queuing up provider downloads...
> info: -- OK! 37% complete! --
>
> info: -- Step 8/19 --
> info: Checking for available disk space...
> info: -- OK! 42% complete! --
>
> info: -- Step 9/19 --
> info: Checking for Internet access...
> info: -- OK! 47% complete! --
>
> info: -- Step 10/19 --
> info: Downloading files...
> info: -- OK! 53% complete! --
>
> info: -- Step 11/19 --
> info: Running admin install commands...
> info: -- OK! 58% complete! --
>
> info: -- Step 12/19 --
> info: Updating install info...
> info: -- OK! 63% complete! --
>
> info: -- Step 13/19 --
> info: Setting up and activating the engine...
> info: COULD NOT FIND OLD B2D KEYS => /Users/imorale2/.ssh/id_boot2docker
> info: BOOT2DOCKER => Starting up. disksize=124900, max=3
> info: BOOT2DOCKER => Initializing boot2docker [1].
> info: BOOT2DOCKER => Initializing boot2docker failed, retrying. VError:
> Error running command
> "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa"
> --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh:
> /usr/local/bin/boot2docker: No such file or directory
>
> at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
>
> From previous event:
> at sh
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
> at shProvider
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
> at rec
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
> at module.exports
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:47:10)
> at Promise.try.then.then.then.shareCmd
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:467:14)
> From previous event:
> at Object.up
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:466:6)
> From previous event:
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:253:39
> From previous event:
> at step.all
> (/usr/local/bin/node_modules/kalabox-engine-docker/lib/install.js.jx:252:8)
> at /usr/local/bin/lib/install/framework.js.jx:452:17
> at /usr/local/bin/lib/install/framework.js.jx:450:30
> From previous event:
> at Promise.each.then.events.emit.state
> (/usr/local/bin/lib/install/framework.js.jx:442:29)
> From previous event:
> at /usr/local/bin/lib/install/framework.js.jx:432:22
> at /usr/local/bin/lib/install.js.jx:178:5
> at Object.exports.run (/usr/local/bin/lib/install.js.jx:168:18)
> at Object.task.func
> (/usr/local/bin/plugins/kalabox-core/tasks/update.js.jx:21:24)
> at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:876:15)
> at processTask (/usr/local/bin/bin/kbox.js.jx:173:16)
> at Object. (/usr/local/bin/bin/kbox.js.jx:236:12)
> at process._tickCallback (node.js:812:13)
> From previous event:
> at main (/usr/local/bin/bin/kbox.js.jx:235:4)
> at Object. (/usr/local/bin/bin/kbox.js.jx:244:1)
> at Module._compile (module.js:518:26)
> at readX (module.js:1284:5)
> at Object.Module._extensions..jx (module.js:1711:10)
> at Module.load (module.js:345:36)
> at Function.Module._load (module.js:312:12)
> at Module.require (module.js:377:17)
> at require (module.js:395:17)
> at Object. (_jx_source:17:3)
> at Module._compile (module.js:518:26)
> at Module.load (module.js:353:12)
> at Function.Module._load (module.js:312:12)
> at Function.Module.runMain (module.js:733:12)
> at startup (node.js:371:18)
> at node.js:1464:3
> info: BOOT2DOCKER => Initializing boot2docker [2].
> info: BOOT2DOCKER => Initializing boot2docker failed, retrying. VError:
> Error running command
> "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa"
> --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh:
> /usr/local/bin/boot2docker: No such file or directory
>
> at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
>
> From previous event:
> at sh
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
> at shProvider
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
> at rec
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
> at process._tickCallback (node.js:812:13)
> info: BOOT2DOCKER => Initializing boot2docker [3].
> info: BOOT2DOCKER => Initializing boot2docker failed, retrying. VError:
> Error running command
> "/usr/local/bin/boot2docker,--sshkey="/Users/imorale2/.ssh/boot2docker.kalabox.id_rsa"
> --retries=50,--disksize=124900,init".: code: 127, msg: /bin/sh:
> /usr/local/bin/boot2docker: No such file or directory
>
> at /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:275:13
>
> From previous event:
> at sh
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:273:11)
> at shProvider
> (/usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:391:12)
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/provider/b2d.js.jx:477:16
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:28:14
> at rec
> (/usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:27:23)
> at
> /usr/local/bin/node_modules/kalabox-engine-docker/node_modules/retry-bluebird/retry-bluebird.js.jx:36:18
> at process._tickCallback (node.js:812:13)
> info: VError: Error initializing boot2docker.: BOOT2DOCKER => Initializing
> boot2docker failed, retrying.
> info: -- INSTALL FAILURE. --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/667>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by imorale2** [comment]
No I don't.

**Comment by pirog** [comment]
Kalabox should have installed that for you the first time you created a
site but looks like somehow it was removed? You could try running the
boot2docker installer to get it back or uninstall/reinstall kalabox.

On Wed, Nov 4, 2015 at 1:09 PM, imorale2 <notifications@github.com> wrote:

> No I don't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/667#issuecomment-153866067>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by imorale2** [comment]
I did uninstall/reinstalled like 10 times already with no luck. The installed failed at that point, and then everytime I tried to round kbox again I get the kbox update.

**Comment by pirog** [comment]
I assume you ran the uninstall script?

It looks like your machine thinks that boot2docker is already installed and
that is why it isnt installing it again. What OS are you on?

On Wed, Nov 4, 2015 at 1:13 PM, imorale2 <notifications@github.com> wrote:

> I did uninstall/reinstalled like 10 times already with no luck. The
> installed failed at that point, and then everytime I tried to round kbox
> again I get the kbox update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/667#issuecomment-153867070>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by imorale2** [comment]
yes I did run the uninstall. I am in Yosemite.

**Comment by pirog** [comment]
hmmm this is very strange behavior then. 

@imorale2 you mentioned you were doing an update. can you give some more info about the upgrade. what version are you upgrading from?

**Comment by imorale2** [comment]
No, I was actually installing for the first time and then I got the error. I uninstalled and when I was trying to install again I get  the message about kbox update, before I can do anything.

**Comment by pirog** [comment]
If you are running the uninstall you should def not be getting a prompt to
update.

How are you running the uninstall?

On Thursday, November 5, 2015, imorale2 <notifications@github.com> wrote:

> No, I was actually installing for the first time and then I got the error.
> I uninstalled and when I was trying to install again I get the message
> about kbox update, before I can do anything.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/667#issuecomment-154091373>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by imorale2** [comment]
No I ran the uninstall and when I am trying to install again is when I get the kbox update. So basically I am assuming is not uninstalling, correct?

I downloaded the latest binary so I am running uninstall-darwin.sh

**Comment by pirog** [comment]
Yes. That is what i am saying. I don't think it is uninstalling correctly for you. What is the actual shell command you are runnning? it should look something like this

`./scripts/uninstall-darwin.sh` 

NOTE that you need to start with `./`

I assume you have admin permissions on this machine?

**Comment by pirog** [comment]
@imorale2 checking back in on this. were you able to uninstall correctly this time?
