### ISSUE TITLE
Get pantheon edge server to mimic actually pantheon varnish config for all frameworks

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#674]

**Comment by jeffesquivels** [comment]
Ok, reviewing pantheon's public docs I think this are the features/specs we need to support:

- [x] Allow a User to Bypass the Cache (by setting the NO_CACHE cookie)
- [ ] Ignoring GET Parameters (when prefixed with __ or utm__)
- [ ] External Authentication (e.g. Facebook login)
- [x] Using Your Own Session-Style Cookies (when prefixed with SESS)
- [ ] Using STYXKEY
- [ ] Varnish, Public Files, and Cookies (stripping cookies from sites/default/files)
- [ ] 404s & Varnish (do not cache by default)
- [ ] Basic Authentication & Varnish (do not cache)
- [ ] Pantheon's Varnish Cookie Handling (wee need to copy those patterns to our VCL)

BTW, we also need to test this for wordpress, I will see if I can find the correct VCLs for that one and start from there.

**Comment by pirog** [comment]
+1 that would be awesome
