### ISSUE TITLE
kbox push fails with terminus "There is no such field."

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#679]
Using alpha5, have succesfully created a new pantheon site locally, then tried to push my changes and get this error:

``````
Error running ad hoc container with kalabox/terminus:t0.9.1.: Non-zero exit code: 1 {"date":"2015-11-08 07:23:34","level":"INFO","message":"An update to Terminus is available. Please update to 0.9.2."}
{"date":"2015-11-08 07:23:39","level":"ERROR","message":"There is no such field."}

Error: Non-zero exit code: 1 {"date":"2015-11-08 07:23:34","level":"INFO","message":"An update to Terminus is available. Please update to 0.9.2."}
{"date":"2015-11-08 07:23:39","level":"ERROR","message":"There is no such field."}

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:586:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:546:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:655:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:653:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:671:27)
    at queryFunc (/Users/timdaff/Sites/manteau/plugins/kalabox-plugin-pantheon/lib/terminus.js:106:31)
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:731:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:730:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:579:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:576:4)
    at /Users/timdaff/Sites/manteau/plugins/kalabox-plugin-pantheon/lib/terminus.js:109:29
    at process._tickCallback (node.js:812:13)
``````

**Comment by pirog** [comment]
@pi-ron any idea to what "field" it is referring?

**Comment by pi-ron** [comment]
I've got no idea sorry @pirog

**Comment by pirog** [comment]
No worries. are you getting it every time or is it more isolated?

**Comment by pi-ron** [comment]
I tried it a few times and it happened all times, this was on my home computer sorry I can't replicate at the moment.  I'll try pushing a site on my work comp shortly.

**Comment by pirog** [comment]
thanks @pi-ron. ill try to replicate as well

**Comment by labboy0276** [comment]
I got this one as well +47

**Comment by pirog** [comment]
OTS for ths now

**Comment by pirog** [comment]
I can't seem to replicate this although i did find another bug. 

Going to assume this is resolved in terminus 0.9.2

**Comment by qcutter** [comment]
Im aslo getting this: 

Error running ad hoc container with kalabox/terminus:t0.9.3.: Non-zero exit code: 1 {"date":"2015-12-16 11:30:12","level":"ERROR","message":"There is no such field."}

Error: Non-zero exit code: 1 {"date":"2015-12-16 11:30:12","level":"ERROR","message":"There is no such field."}

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:609:28

Im getting this after doing a kbox push to Pantheon Multidev site. I uninstalled and reinstalled Kalabox from scratch. Im using the binary version. I get this error, but I dont have a /usr/local/bin/node_modules directory.

**Comment by nolfranklin** [comment]
Definitely seeing this error as well with Kbox 0.10.6 + Pantheon Multidev.

**Comment by pirog** [comment]
Think this should be resolved in v0.11.0 which we will release on thursday 1/21. going to close for now

**Comment by mojowill** [comment]
I'm running this on the latest 0.11.0 binary (Mac OSX) against MultiDev.
```
Failed after 5 retries. {"max":5,"backoff":500}: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
{"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
{"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}

Error: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
{"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
{"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}

    at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:128:17
From previous event:
    at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:125:13
    at /usr/local/bin/lib/promise.js.jx:46:16
From previous event:
    at rec (/usr/local/bin/lib/promise.js.jx:45:25)
    at /usr/local/bin/lib/promise.js.jx:57:20
    at process._tickCallback (node.js:917:1)
~/Sites/pantheon.io/titan-us
```

**Comment by pirog** [comment]
awesome! thanks!

**Comment by pirog** [comment]
Im able to replicate this now. fix pending.

**Comment by pirog** [comment]
So this seems to happen on multidev (and presumably dev) instances where you have never changed the connection mode before. A current workaround is to go into your sites pantheon dashboard and change the mode, then try pushing again.

**Comment by pirog** [comment]
Opened up a terminus issue for this
https://github.com/pantheon-systems/cli/issues/844

**Comment by pirog** [comment]
In the meantime there is now an open PR to fix this
https://github.com/kalabox/kalabox-app-pantheon/pull/82

If you don't want to wait for the new release you can fix this manually by patching with the above in your apps `plugins/kalabox-plugin-pantheon/lib`
