### ISSUE TITLE
 Connect ETIMEDOUT after auto-up and then kbox start

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#680]
After rebooting my Windows8.1 PC, I issued "kbox start" command.

I got the message: "Kalabox engine has been activated." then the error:
VError: Error inspecting container. Error querying docer for list of containers.: Connect ETIMEDOUT.

I then ran these commands and everything was fine:
kbox apps
kbox up
kbox start

**Comment by pirog** [comment]
@bcauldwell 

I think this might just be KBOX querying docker before its ready when you need to turn on the engine before you do a first start. A retry on query or delay could work. 

I also suspect this is only an issue for older machines.

**Comment by robertark** [comment]
I was able to resolve this issue by checking this box:

![image](https://user-images.githubusercontent.com/979864/27206101-1e12e646-5203-11e7-923d-e43280074deb.png)

(Docker Version: 17.03.1-ce-win12 (12058))
