### ISSUE TITLE
Kalabox error pages: no animated clouds on Firefox

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#681]
Guessing this extends to other non-Chrome browsers and that we used Chrome-specific CSS animation properties, need to extend.

**Comment by pirog** [comment]
the people demand the clouds

**Comment by reynoldsalec** [comment]
Actually, looking at this the animate properties are working fine, but there is some other strange cross-browser behavior going on. Might be related to the fact we aren't URL encoding of the SVGs, although from the test fiddle it looks like Firefox now supports non-encoded data:

- https://r.va.gg/2012/05/data-uri-svg.html
- Test Fiddle: http://jsfiddle.net/rvagg/exULa/

**Comment by reynoldsalec** [comment]
Further reading on the SVG issue:

http://codepen.io/Tigt/post/optimizing-svgs-in-data-uris

Now facing some problems just getting my sass to compile...grrrr.
