### ISSUE TITLE
Drush radix command needs a higher bootstrap level to run

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#690]
I put radix.drush.inc into the config\drush directory (as described in an earlier issue).

When I run it, I get the error:
"Command radix needs a higher bootstrap level to run - you will need to invoke drush froma more functional Drupal environment to run this command."

Do I need to download Drush for Windows (for certain drush commands)? That does not seem to be in keeping with what Kalabox is designed to do.

**Comment by pirog** [comment]
It should work out of the box and is fairly well tested. I would make sure you have your site set up correctly. For example, if you dont have a settings.php, as is the case for many pantheon sites, drush will fail. 

I would recommend running something like `kbox drush COMMAND --verbose --debug` to drill down into the problem a bit more

**Comment by escapesequence** [comment]
My site is a pantheon site.  There is no settings.php.  <b>Can I just copy over the default.settings.php?</b>

FWIW, here is the result of "kbox drush radix --verbose --debug":

Bootstrap to phase 0. [0 sec, 2.4 MB]                                [bootstrap]
Executing: wget --version
  sh: 1: wget: not found
Executing: curl --fail -s -L --connect-timeout 30 -o /tmp/download_fileeUcBUt http://download.pear.php.net/package/Console_Table-1.1
.3.tgz
Calling is_readable(/tmp/download_fileeUcBUt) [1.57 sec, 2.42 MB]        [debug]
Calling is_writable(/usr/local/src/drush6/lib) [1.57 sec, 2.42 MB]       [debug]
Calling rename(/tmp/download_fileeUcBUt,                                 [debug]
/usr/local/src/drush6/lib/drush-library-1690344084) [1.58 sec, 2.42
MB]
Mime type for /usr/local/src/drush6/lib/drush-library-1690344084 is     [notice]
application/x-gzip [1.58 sec, 2.42 MB]
Calling chdir(/usr/local/src/drush6/lib) [1.59 sec, 2.42 MB]             [debug]
Executing: tar  -C /usr/local/src/drush6/lib -xzf drush-library-1690344084
Calling chdir(/code) [1.6 sec, 2.42 MB]                                  [debug]
Calling unlink(/usr/local/src/drush6/lib/package.xml) [1.6 sec, 2.42     [debug]
MB]
Drush bootstrap phase : _drush_bootstrap_drush() [1.6 sec, 2.55 MB]  [bootstrap]
Loaded alias @kbox from file /root/.drush/aliases.drushrc.php [1.66     [notice]
sec, 2.57 MB]
Cache SET cid: 6.6.0-alias-path--62ae811b905700784d8a3594ede9dd4b        [debug]
[1.67 sec, 2.57 MB]
Cache HIT cid: 6.6.0-commandfiles-0-013dcf2232c725a90898012d363b2dfa     [debug]
[1.68 sec, 2.58 MB]
Bootstrap to phase 0. [1.77 sec, 6.79 MB]                            [bootstrap]
Bootstrap to phase 6. [1.82 sec, 6.8 MB]                             [bootstrap]
Drush bootstrap phase : _drush_bootstrap_drupal_root() [1.83 sec,    [bootstrap]
7.92 MB]
Initialized Drupal 7.41 root directory at . [1.84 sec, 7.92 MB]         [notice]
Bootstrap to phase 5. [1.84 sec, 7.93 MB]                            [bootstrap]
Command radix needs a higher bootstrap level to run - you will need  [error]
to invoke drush from a more functional Drupal environment to run this
command. [1.84 sec, 7.94 MB]
The drush command 'radix' could not be executed. [1.84 sec, 7.94 MB] [error]
Could not find a Drupal settings.php file at                         [error]
sites/default/settings.php. [1.84 sec, 7.94 MB]

**Comment by pirog** [comment]
@escapesequence yeah exactly. just copy default.settings.php to settings.php and you should be good. you dont need to add anything else in there since we manage the DB on our end.

**Comment by escapesequence** [comment]
That did the trick. Thanks!
