### ISSUE TITLE
DNS servers added to resolvconf make browsing unresponsive

### ISSUE THREAD

**Issue by esclapes** [kalabox/kalabox#692]
After installing kalabox yesteday, hostame solving was slow while browsing.

I spent some time debugging and tweaking my router configuration with no success. Finally found two IP addresses (10.13.37.42/43) in /etc/resolvconf/resolv.conf.d/head.

Removing them solved my problem, but not sure how that affects kbox operation.

**Comment by pirog** [comment]
Hey @esclapes, 

Short answer is yeah that is going to mess with resolution of *.kbox domains. 

Longer answer is we have an issue to address this over at #242 and its slated for the alpha7 release. 

Going to close this in favor of that issue.

**Comment by esclapes** [comment]
Thanks @pirog

**Comment by pirog** [comment]
sure thing!
