### ISSUE TITLE
SQLSTATE No route to host

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#694]
When I try to navigate my site I am getting:
<b>PDOException: SQLSTATE[HY000] [2002] No route to host in lock_may_be_available() (line 167 of /code/includes/lock.inc).</b>

umm... I haven't really done anything!?! I tried to change .stignore (but the changes - to ignore "icon*.png" - didn't 'take') and I changed Syncthings rescan interval on localhost and VM to 5s.  I've also rebooted.  No problems during "kbox start".

SQL "No route to host" sounds like a dns problem preventing access to DB.

**Comment by escapesequence** [comment]
Solved

Copying default.settings.php to settings.php allowed Drush to incorporate radix commands but messed up access to the DB.  I renamed setting.php and now the site is working.

**Comment by escapesequence** [comment]
Leaving this open because it seems that there should be a better way to allow for Drush command extensions (for Pantheon apps) than using the existence of "settings.php" like a switch.

**Comment by pirog** [comment]
A settings.php copied over from default.settings.php should not interfere with the DB settings. If it did then your drush also wouldnt work.

**Comment by pirog** [comment]
@escapesequence this is an issue that exists on the drush side of things so i would submit a ticket over there, not here.
