### ISSUE TITLE
http://sitename.kbox -> ISP site not found page (but https works fine)

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#696]
Windows 8.1

When I don't have an entry in the hosts file, my browser directs me to my ISP site not found page. I have run "kbox start" (no problems) an my VB HO Adapter appears to be fine (and site runs fine with hosts entry.)

**Comment by pirog** [comment]
Again, It's not recommended to add entries to the host file and is certainly not supported. 

If you are being directed to an ISP page then i would research ISP DNS opt out pages. Check out this article for more details on this problem
http://hackercodex.com/guide/how-to-stop-isp-dns-server-hijacking/
