### ISSUE TITLE
ERROR Pulling database - New terminus version

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#704]
Just got this error and I think from the messages that the error is because terminus was recently updated:

```
Error running ad hoc container with kalabox/terminus:t0.9.1.: Non-zero exit code: 1 {"date":"2015-11-12 16:00:21","level":"INFO","message":"An update to Terminus is available. Please update to 0.9.2."}
{"date":"2015-11-12 16:00:27","level":"INFO","message":"Downloading ... please wait ..."}
{"date":"2015-11-12 16:00:27","level":"ERROR","message":"Target file (\/src\/config\/terminus\/\/greenbiz_sprint_2015-11-11T19-00-00_UTC_database.sql.gz) already exists."}
{"date":"2015-11-12 16:00:27","level":"ERROR","message":"Could not download file"}

Error: Non-zero exit code: 1 {"date":"2015-11-12 16:00:21","level":"INFO","message":"An update to Terminus is available. Please update to 0.9.2."}
{"date":"2015-11-12 16:00:27","level":"INFO","message":"Downloading ... please wait ..."}
{"date":"2015-11-12 16:00:27","level":"ERROR","message":"Target file (\/src\/config\/terminus\/\/greenbiz_sprint_2015-11-11T19-00-00_UTC_database.sql.gz) already exists."}
{"date":"2015-11-12 16:00:27","level":"ERROR","message":"Could not download file"}

    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:586:28
From previous event:
    at Object.result.wait (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:546:20)
    at /usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:655:18
From previous event:
    at Object.queryData (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:653:6)
From previous event:
    at Object.exports.queryData (/usr/local/bin/lib/engine.js.jx:671:27)
    at queryFunc (/Users/gremy/kalabox/apps/greenbiz/plugins/kalabox-plugin-pantheon/lib/terminus.js:106:31)
From previous event:
    at Object.dockerInstance.then.bind.then.then.then.catch.finally.self (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:731:25)
From previous event:
    at Object.use (/usr/local/bin/node_modules/kalabox-engine-docker/docker.js.jx:730:6)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:579:29
From previous event:
    at Object.exports.use (/usr/local/bin/lib/engine.js.jx:576:4)
    at /Users/gremy/kalabox/apps/greenbiz/plugins/kalabox-plugin-pantheon/lib/terminus.js:109:29
    at process._tickCallback (node.js:812:13)
```

**Comment by gremy** [comment]
Problem got solved by changing terminus version from 0.9.1 to 0.9.2.

**Comment by pi-ron** [comment]
@gremy Where did you change the terminus version?

**Comment by gremy** [comment]
@pi-ron nevermind, just pulled the latest kalabox-app-pantheon and on Nov 3 the follwing commit got published: https://github.com/kalabox/kalabox-app-pantheon/commit/b3dce4550e9f2834e6c104a37e1985a0daf08485

Fixed. We just need to wait for the release.

As a temporary fix just search in your app for all instances of 0.9.1 and replace with 0.9.2 ;)

**Comment by pi-ron** [comment]
Thanks I did so and worked well :-)
On Sat, 14 Nov 2015 at 5:49 AM, Emanuel Greucean <notifications@github.com>
wrote:

> @pi-ron <https://github.com/pi-ron> nevermind, just pulled the latest
> kalabox-app-pantheon and on Nov 3 the follwing commit got published:
> kalabox/kalabox-app-pantheon@b3dce45
> <https://github.com/kalabox/kalabox-app-pantheon/commit/b3dce4550e9f2834e6c104a37e1985a0daf08485>
>
> Fixed. We just need to wait for the release.
>
> As a temporary fix just search in your app for all instances of 0.9.1 and
> replace with 0.9.2 ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/704#issuecomment-156520252>.
>
-- 

Cheers,

Tim Daff
*Director*

nextentity
*websites & design *

MOBILE0437 988 399EMAILtim@nextentity.com.au
<https://mail.google.com/mail/ca/u/0/tim@nextentity.com.au>POST5 Anderson
Street
Newhaven, VIC 3925

STATEMENT OF CONFIDENTIALITY: The information contained in this e-mail
(including any attachments) contains information that may be confidential
or may constitute non-public information and may be legally privileged and
confidential. It is intended only for the use of the individual(s) or
entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copy of this e-mail is strictly prohibited and may be unlawful. If you have
received this email in error, please immediately notify the sender and
destroy all hard copies and any copies that may be on your computer. Thank
you.
