### ISSUE TITLE
Concurrency issue with running multiple commands at once

### ISSUE THREAD

**Issue by bthompson-mindgrub** [kalabox/kalabox#709]
Use case:

I have a large site I need to clone from Pantheon.  While it clones, I want to work on another site.  Attempting to run a `kbox start` or a `kbox <app> start` on the existing site I have while trying to clone a new one results in the error "Error dispatching event listeners [post-stop]: ENOENT, open <site I'm trying to clone>\code\.stfolder"

Not sure of the best solution to this problem.  Possibly just a disclaimer about it somewhere?  Or we have to figure out how to namespace all the containers and commands being run so they stay app specific.  But that sounds like a fairly big task...

**Comment by bthompson-mindgrub** [comment]
Attempting to run `kbox start` after the `kbox create pantheon` command finished (in another window) did work successfully so this is definitely a concurrency issue.

**Comment by pirog** [comment]
So we've got a bunch of post-MVP nice-to-haves and i've added concurrency to that 
Its over at #511 

@bthompson-mindgrub i *think* this might just be happening during syncthing operations but it would be nice to drill down and figure out exactly when this is happening and why

**Comment by pirog** [comment]
@bthompson-mindgrub going to close this in favor of the meta issue over at #511
