### ISSUE TITLE
kbox git is slow

### ISSUE THREAD

**Issue by geraldvillorente** [kalabox/kalabox#724]
Is there any reason(s) behind using `kbox` in git commands?

**Comment by pirog** [comment]
The reasons are

1. We can't guarantee that the user has git installed locally
2. We need our own internal method to pull down sites and do things like that
3. We want to provide an experience where all needed dev tools are packaged with the apps that need them

That said you can use your own local git. 

We know that right now the `kbox` variants of these commands are slower than their native counterpoints but this is an issue we have a plan to resolve post-beta. It is expressed over at #511
