### ISSUE TITLE
Newer Redis version

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#731]
I am getting this error on one project:
```EVAL failed: ERR unknown command 'EVAL' PhpRedis.php:128```

Researched it a bit and found this:
https://www.drupal.org/node/2482263

It basically says that 3.x redis module requires Redis server >= 2.6 and recommands Redis server >= 2.8

At the moment we have Redis server version 2.4.14

**Comment by pirog** [comment]
@gremy can you update the hipache image to run redis >= 2.8?

**Comment by gremy** [comment]
OK

**Comment by gremy** [comment]
I am looking at this repository trying to figure out which version to pick:
https://github.com/NodeRedis/node_redis/tree/v.2.3.1

In hipache packages.json we have the 0.10.0 dependency which is way old.
But the node_redis versions don't match with the actual redis version, so I am post a PR with 2.3.x dependency.

**Comment by gremy** [comment]
https://github.com/kalabox/hipache/pull/3

**Comment by gremy** [comment]
@pirog I see references in https://github.com/kalabox/kalabox-app-pantheon/tree/v0.10/app/dockerfiles/pantheon-redis to pulling kalabox/hipache:v0.10.0 but on kalabox/hipache there is no 0.10.0 tag. Maybe it's refering to something different, or the dockerhub version.

**Comment by gremy** [comment]
Since on the pantheon-redis container I am seeing that the latest redis version is 2.4, so we might need to add a ppa or something to install the newer version.

**Comment by pirog** [comment]
What version of redis does pantheon run?

On Thursday, November 19, 2015, Emanuel Greucean <notifications@github.com>
wrote:

> Since on the pantheon-redis container I am seeing that the latest redis
> version is 2.4, so we might need to add a ppa or something to install the
> newer version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/731#issuecomment-158114978>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@gremy this might be close to what we want
https://www.devops.zone/ha-performance-caching/installing-redis-2-8-masterslave-on-debian-wheezy/

**Comment by gremy** [comment]
@pirog Tried this in kbox terminal redis and I got redis v3.0.5.

**Comment by pirog** [comment]
@gremy i think that is the cli version not the server version? im seeing a
server version of 2.8.18. maybe different on different sites?

On Thu, Nov 19, 2015 at 10:39 AM, Emanuel Greucean <notifications@github.com
> wrote:

> @pirog <https://github.com/pirog> Tried this in kbox terminal redis and I
> got redis v3.0.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/731#issuecomment-158150432>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by gremy** [comment]
@pirog When I checked the version I checked it for redis server.
```
# kbox terminal redis
# redis-server --version
```
I am sure that the redis server was 2.4.

**Comment by pirog** [comment]
good to know. redis should be at 2.8.18 for the alpah6 release.

On Thu, Nov 19, 2015 at 2:30 PM, Emanuel Greucean <notifications@github.com>
wrote:

> @pirog <https://github.com/pirog> When I checked the version I checked it
> for redis server.
>
> # kbox terminal redis
> # redis-server --version
>
> I am sure that the redis server was 2.4.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/731#issuecomment-158220942>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by gremy** [comment]
Awesome. Thank you.
