### ISSUE TITLE
Error upgrading to kbox 10.5

### ISSUE THREAD

**Issue by yosefromano** [kalabox/kalabox#738]
Tried upgrading from 10.4 to 10.5 with binary installation. I ran kbox update and got this: 
info: -- Step 15/19 --
info: Updating apps...
info: TypeError: Cannot call method 'split' of undefined
info: -- INSTALL FAILURE. --

**Comment by pirog** [comment]
hey @yosefromano alpha6 release is imminent so i'd wait for that to drop in the next few days and then try again.
