### ISSUE TITLE
error updating to 10.5

### ISSUE THREAD

**Issue by alphex** [kalabox/kalabox#739]
I was running 10.2.

Ran the uninstall script "kbox config | grep srcRoot"
and running "./scripts/uninstall-darwin.sh" in the directory it pointed me at.
Uninstaller ran properly.

Downloaded the latest binary "kbox-macosx-amd64-v0.10.5-alpha5".
Renamed to "kbox"
Moved it to /usr/local/bin

typed kbox, and it asked me to run kbox upgrade...

which based on your documentation is wrong.

I went through it... 

and gave me this error 

info: -- Step 13/19 --
info: Setting up and activating the engine...
info: BOOT2DOCKER =>  Starting up. disksize=25819, max=3
info: BOOT2DOCKER =>  Initializing boot2docker [1].
info: BOOT2DOCKER =>  Initializing boot2docker failed, retrying. VError: Error running command "/usr/local/bin/boot2docker,--sshkey="/Users/duran/.ssh/boot2docker.kalabox.id_rsa" --retries=50,--disksize=25819,init".: code: 127, msg: /bin/sh: /usr/local/bin/boot2docker: No such file or directory

Thanks!

**Comment by pirog** [comment]
@alphex hmmm looks like the uninstall script didnt run or compete properly. Might be worth grabbing the latest script from the releases page and then trying that. 

Al that said ALPHA6 is imminent so you might just want to wait for that before you retry!

**Comment by pirog** [comment]
@alphex alpha6 is out so i would try that! make sure you run the latest uninstall script first

**Comment by alphex** [comment]
Thank you!
Happy thanksgiving !

---
] duran goodyear
] sent from my phone
] please excuse any brevity

**Comment by pirog** [comment]
you too! def try the new uninstall script and 0.10.6 and let us know how it goes!
