### ISSUE TITLE
provider's looking up of IP address should be memoized

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#744]
provider's looking up of IP address should be memoized

**Comment by pirog** [comment]
@bcauldwell i also think at this point we can assume the IP will be 10.13.37.42 so we might be able to just hardcode this in there

**Comment by pirog** [comment]
So with the new machine provider we are using the following for `getIp` and `getServerIps`

```js
  /*
   * Return machine's IP address.
   */
  var getIp = function() {
    return Promise.resolve(MACHINE_IP);
  };
```

```
  /*
   * Get list of server IP addresses.
   */
  var getServerIps = function() {
    return [MACHINE_IP];
  };
```

I feel like this effectively solves the point of this issue so im closing
