### ISSUE TITLE
STATS- Create a dashboard for our stats info 

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#759]

**Comment by reynoldsalec** [comment]
@bcauldwell maybe you can show me the easiest way to develop with the stats server, looking at writing an elasticsearch adapter so we can switch over to that and do our dashboard in Kibana.

**Comment by pirog** [comment]
@reynoldsalec 
so having done some research here we might have an easier pathway to victory here if we 

1. Get the actual stats usage into something like statuspage.io which handles custom metrics (this might actually be a wash in ease with kibani but we'd be using one system for status and metrics instead of two). Also depends on whether we want that info to be public or not

2. Get our error reporting into something like bugsnag

**Comment by reynoldsalec** [comment]
@pirog 

I was assuming mostly an internal use for stats (to show to partners and for our evaluation), but the custom metrics handling on statuspage.io is interesting.

Looking at it, saving custom metrics seems like it'd basically be a new form of reporting. Whether we're going from ElasticSearch or Mongo, we'd need to have a reporting layer that created certain metrics (# of errors seems like one we might want to report) and sends those to statuspage.

**Comment by pirog** [comment]
I think you can do "private" statuspage.io pages. Down with whatever you
want to do, just offering some suggestions on possibly easier routes.

**Comment by reynoldsalec** [comment]
This will be blocked temporarily by @rileysaurus working on converting over stats to send to elasticsearch. In the meantime, I'll take a look at the Kibana docs and how that'll work on Qbox (I think they give you hosted Kibana for free) or another provider.

**Comment by reynoldsalec** [comment]
Ok, starting to look at sample datasets and at the data we're starting to have come in from @rileysaurus's new integration.

**Reports We Need**
- # of users who have made a Pantheon action in the past calendar months (Metric)
- # of Pantheon Agency users who have made a Pantheon action in the past calendar months
- #'s of users on various OS's (pie chart) for last month/all time
- % of errors vs. all other actions for last 7 days/last month
- Most active Pantheon Agency organizations

**Date We'll Need Added to Metrics**
- Pantheon organization associated with Pantheon actions (necessary for partnership report)

**Comment by rileysaurus** [comment]
I can convert the old dataset over tomorrow so you'll have enough sample data to go off of. I'll flag them all with a v1 tag.

**Comment by reynoldsalec** [comment]
Nice @rileysaurus, as long as it's not a big distraction from GUI-reboot, now that we have @pirog's work in.

**Comment by reynoldsalec** [comment]
Hmm, from looking at the format of the data presented in Kibana, it looks like we'll want to flatten out the records if possible as well, unless I'm misunderstanding and Elasticsearch just handles data this way:

```
{
  "_index": "metrics",
  "_type": "v2",
  "_id": "AVJI3XOUsQdX1viSLZ3V",
  "_score": null,
  "_source": {
    "instance": "SOME INSTANCE",
    "data": {
      "created": "2016-01-16T05:16:57.584Z",
      "data": {
        "action": "start",
        "os": {
          "type": "Darwin",
          "platform": "darwin",
          "release": "15.2.0",
          "arch": "x64"
        },
        "version": "0.11.0-dev",
        "nodeVersion": "v0.10.40"
      }
    }
  },
  "fields": {
    "data.created": [
      1452921417584
    ]
  },
  "sort": [
    1452921417584
  ]
}

**Comment by rileysaurus** [comment]
I'm not fully understanding what you mean but everything in the _source field is what is the document we are adding and the rest is elastic data about that document.

**Comment by rileysaurus** [comment]
I got 31,739 docs migrated over to the elasticsearch cluster to give you a
good sample of data. We could flatten things a little if that will help,
would be nice to simplify things.

**Comment by reynoldsalec** [comment]
Agreed @rileysaurus, flattening out the source is worthwhile before we start collecting new data. Seems like we should have something like:

```
"_source": {
  "instance": "SOME INSTANCE",
  "created": "2016-01-16T05:16:57.584Z",
  "action": "start",
  "os": {
    "type": "Darwin",
    "platform": "darwin",
    "release": "15.2.0",
    "arch": "x64"
  },
  "version": "0.11.0-dev",
  "nodeVersion": "v0.10.40"
}

**Comment by reynoldsalec** [comment]
[] # of users who have made a Pantheon action in the past calendar months (Metric)
[] # of Pantheon Agency users who have made a Pantheon action in the past calendar months
[x] #'s of users on various OS's (pie chart) for last month/all time
[] % of errors vs. all other actions for last 7 days/last month
[] Most active Pantheon Agency organizations

**Comment by reynoldsalec** [comment]
I'm changing the name of the document type over to "event" from "v2" (since it makes more sense to version the indices with the model @rileysaurus and I discussed).

Steps forward:

- [x] Commit change to kalabox-stats-server
- [ ] Deploy change to stats server (@rileysaurus will help out with tomorrow)
- [ ] Delete metrics index and create alias "metrics" to link with metrics_v3

**Comment by reynoldsalec** [comment]
We need to replace error reporting in part on the dashboard.
