### ISSUE TITLE
Trusty install?

### ISSUE THREAD

**Issue by niccolox** [kalabox/kalabox#76]
any clues on installing this on Trusty?

**Comment by pirog** [comment]
NR! 

we are still a few weeks away from linux/windows versions so i would check back in then... or i can ping you on the emails when its ready for some testing if you want!

**Comment by niccolox** [comment]
I will eat the dogfood

**Comment by pirog** [comment]
i've been eating it for the past 2 weeks :)

On Mon, Feb 2, 2015 at 3:31 PM, Nicholas Roberts <notifications@github.com>
wrote:

> I will eat the dogfood
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/76#issuecomment-72561682>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by niccolox** [comment]
this thread could get weird, real quick

give me .deb !

**Comment by niccolox** [comment]
and I must add, please never mention Windows and Linux as equivalent priorities, they are alternatives

besides MS Windows has Acquia Dev Desktop, there is no good tooling in the Linux space

**Comment by pirog** [comment]
There is a *very* prelim debian based install that ill be merging in later

**Comment by pirog** [comment]
the docs are a little out of date but you should be able to do this now
