### ISSUE TITLE
Add ability to type in branch name for "kbox create pantheon"

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#767]
Enhancement Request
Kalabox 10.0.6
OS X 10.9.5
Background: Initial box creation attempted from a non-admin user required downloading and installing additional components for Kalabox.  Attempt failed when sudo password failed.

Problem statement
Log into account with admin privileges
```bash
mkdir ~/Desktop/Apps
cd ~/Desktop/Apps
```
Create script
```bash 
kbox create Pantheon -- -v 2>&1 | tee somename.log
```

Run script
entered Pantheon credentials
when process got to
```
? Choose a Pantheon account. (Use arrow keys)
```
using arrow keys showed echo of arrow key values instead of name of selected branch that would be shown if process was being run interactively instead of in a script.

Request is to add option to type in name of branch to be selected (in addition to selecting branch name with arrow keys).

**Comment by pirog** [comment]
@rgeleta i think im a little confused about this ticket. 

we list your multidev environments... how is that different then what you are proposing?

**Comment by rgeleta** [comment]
yes multidev environments are listed.  
I am proposing to be able to enter name of environment with keyboard
However selection is only available using up/down arrows
When using a script to provision a machine, pressing up/down arrows shows characters (ascii?) of the up/down arrows, and there is no way to confirm which environment has been selected.

**Comment by pirog** [comment]
I dont think that is something we will support, at least not interactively. Im also not 100% clear on the use case here so maybe im just missing something obvious here. I'd also guess that combining stdout and stderr might have something to do with the weird output you are getting on after some stdin. 

that said you should be able to pass in `--env=MULTIDEV` to grab a multidev site if you are scripting which seems like a better flow for scripting. You could even have the script itself accept arguments if you wanted to make it a little more dynamic. 

`kbox create pantheon -- --email=mike@kalamuna.com --password=**** --site=playbox --env=dev --name=mylocalsite`

Above will let you pull down a site without needing any interaction from the user.

**Comment by rgeleta** [comment]
uh, I must have missed reading about those arguments in the documentation, and it seems the version I downloaded didn't include them in the command help text.
:-)

**Comment by pirog** [comment]
Are you sure? This is what i see for 0.10.6

```
PIROBOOK2:biryanikabox pirog$ kbox create pantheon -- -h
Options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
  --email        Pantheon dashboard email.                              [string]
  --password     Pantheon dashboard password.                           [string]
  --site         Pantheon site machine name.                            [string]
  --env          Pantheon site environment.                             [string]
  --name         The name of your app.                                  [string]
  --build-local  Build images locally instead of pulling them remotely.[boolean]
  --dir          Creates the app in this directory. Defaults to CWD.    [string]
```

**Comment by rgeleta** [comment]
ok, clarification
```bash
kbox -- -h
```
does not show ```--env``` argument, but
```bash
kbox create pantheon -- -h
```
does show the ```-env``` argument
calling it a draw and closing

**Comment by pirog** [comment]
`kbox -- -h` should definitely not show `--env` as an option. so that is correct. each command has potentially different arguments and options so i dont think we want to have that there. 

A small change that could help would be describing the options listed in `kbox -- -h` as global options instead of just options

```
Usage: kbox <command> [-- <options>]

Global commands that can be run from anywhere
  apps             Display list of apps.
  config           Display the kbox configuration.
  containers       Display list of all installed kbox containers.
  create       
      pantheon     Creates a Pantheon app.
  update           Run this after you update your Kalabox code.
  version          Display the kbox version.

Global options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
```

**Comment by rgeleta** [comment]
Perhaps also revising earlier example's output would help after seeing it a few times:
```
PIROBOOK2:biryanikabox pirog$ kbox create pantheon -- -h
Command options for create command:
  --email        Pantheon dashboard email.                              [string]
  --password     Pantheon dashboard password.                           [string]
  --site         Pantheon site machine name.                            [string]
  --env          Pantheon site environment.                             [string]
  --name         The name of your app.                                  [string]
  --build-local  Build images locally instead of pulling them remotely.[boolean]
  --dir          Creates the app in this directory. Defaults to CWD.    [string]

Global options:
  -h, --help     Display help message.                                 [boolean]
  -v, --verbose  Use verbose output.                                   [boolean]
```
