### ISSUE TITLE
Change "kbox destroy" confirmation default to "no"

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#768]
When running a "kbox destroy" command, there is a confirmation question asking if you want to destroy the box.  The default for the answer is "Yes".

Request is to make the default "No" to force an explicit entry of "Y" (or "Yes") in order to destroy the box.  Reason is to add an additional safety level prior to destroying work.  The additional work required to rerun a destroy if nothing happens is smaller than the additional work required to recreate a box if the box is destroyed by accident.

Also, if possible, add the name of the box to be destroyed to the confirmation message.

**Comment by pirog** [comment]
+1 

@rgeleta i think this makes a lot of sense and definitely will help anyone with an itchy trigger finger.
