### ISSUE TITLE
Consolidate some kbox commands like kbox containers and kbox apps into some sort of info command tbd

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#770]
Enhancement request:
Add "status" option to kbox command to show active machines/components and how to access them.  Suggest wording that shows up after issuing command ```kbox start```

Example:
~~~bash
$ kbox status
kalabox engine is not active 

$ kbox start example1
...
$ kbox start example2
...
$ kbox status
kalabox engine is active, version: 0.10.6

example1.kbox is active
URL: http(s)://example1.kbox
LOCATION: /Users/bob/Desktop/Apps/example1
==========
example2.kbox is active
URL: http(s)://example2.kbox
LOCATION: /Users/bob/Desktop/Apps/example2
==========
$ kbox status -- -v
example1.kbox is active
example1 URL: http(s)://example1.kbox
example1 LOCATION:/Users/bob/Desktop/Apps/example1
example1 Boot2docker is up
example1 Supporting services
example1 Container a1b2c3...ff is up - syncthing
example1 Container b1c2d3...ff is up - anotherservice
==========
example2.kbox is active
example2 URL: http(s)://example2.kbox
example2 LOCATION:/Users/bob/Desktop/Apps/example2
example2 Boot2docker is up
example2 Supporting services
example2 Container a1b2c3...ff is up - syncthing
example2 Container b1c2d3...ff is up - anotherservice
==========
$
```

**Comment by pirog** [comment]
So i think `kbox apps` and `kbox containers` deos some of this already. Maybe we can combine those two commands and add in some options to get more meta data about things. 

@rgeleta how does that sound?

**Comment by rgeleta** [comment]
Yes, agree about ```kbox apps``` and ```kbox containers```, perhaps the -v option is overkill.

Intent is to identify whether kbox is running, and if so which apps are active.

**Comment by pirog** [comment]
Ok awesome. In that case i propose either a `kbox status` or `kbox info` command that could also take various options to drill down or get more specific information. 

I'm thinking `info` might be a little better semantically since we could do something like this

```
kbox info -- --engine
kbox info -- --app=name
kbox info --version
```

whereas `status` kind of implies a singular response like `up|down|off`

**Comment by rgeleta** [comment]
actually, a singular response was what I was looking for when I returned to my computer after a while.
an answer to the question "now what was I working on and where did I leave off?"

**Comment by pirog** [comment]
Got it! I think we can probably get something like that in there.

**Comment by pirog** [comment]
Ok. I think we are finally at the point where we can address this reliably. Right now we have two commands that return some info 

```
kbox apps
kbox containers
```

I think we should remove both and offer `kbox list` and `kbox info` instead.

### `kbox list`

Globally available command that gives you a list of your apps with some basic info 

```
kbox list
{
  myApp: {
    running: true
    url: myapp.kbox
    type: pantheon
    location: ~/.kalabox/apps/myapp
  },
  myApp2: {
    running: false
    url: myapp2.kbox
    type: laravel
    location: ~/.kalabox/apps/myapp2
  }
}

**Comment by labboy0276** [comment]
the kbox info stuff looks good +47 @pirog
