### ISSUE TITLE
Add reference to additional local commands to kbox help text

### ISSUE THREAD

**Issue by rgeleta** [kalabox/kalabox#771]
Enhancement request
Add language to kbox help text when outside app directory

When current working directory is outside an app directory, typing
```kbox -- -h``` or ```kbox [someinvalidcommand]``` 
help text starts with 
```Global commands that can be run from anywhere```
and global commands are shown

When current working directory is inside an app directory, the additional commands available on that app are also shown.

Request is to add language to kbox help when it is run outside an app dir.
Some ideas for wording:
```Additional app actions are available when kbox is run from within a specific app directory```
or
```Navigate to an app directory for additional app specific options```

**Comment by pirog** [comment]
@rgeleta can you mock up how you envision this looking on the cli?

**Comment by rgeleta** [comment]
Ok, how about
```
$ cd /somewhere_not_in_kbox
$ kbox
Usage: kbox <command> [-- <options>]

Global commands that can be run from anywhere
  apps             Display list of apps.
  config           Display the kbox configuration.
  containers       Display list of all installed kbox containers.
  create       
      pantheon     Creates a Pantheon app.
  update           Run this after you update your Kalabox code.
  version          Display the kbox version.

Options:
  -h, --help     Display help message.  [boolean]
  -v, --verbose  Use verbose output.  [boolean]

Additional app actions are available when kbox is run from within a specific app directory
```
or
```
$ cd /somewhere_not_in_kbox
$ kbox
Usage: kbox <command> [-- <options>]

Global commands that can be run from anywhere
  apps             Display list of apps.
  config           Display the kbox configuration.
  containers       Display list of all installed kbox containers.
  create       
      pantheon     Creates a Pantheon app.
  update           Run this after you update your Kalabox code.
  version          Display the kbox version.

Options:
  -h, --help     Display help message.  [boolean]
  -v, --verbose  Use verbose output.  [boolean]

Change to app directory for additional app specific commands
```

**Comment by pirog** [comment]
i think this would work pretty well. only concern would be 
```
Change directory to [srcRoot]/[appname] for additional app specific commands
```
since the user can presumably have more than one app installed.

**Comment by rgeleta** [comment]
therefor the reason for 
in second example [srcRoot] should be replaced by value of srcRoot
so if srcRoot is ~/Desktop/Apps
text would read
```
Change directory to ~/Desktop/Apps/[appname] for additional app specific commands
```

**Comment by pirog** [comment]
So you can actually put apps in any directory you want. So i think it might make more sense to do something like 

```
Change to an app directory for additional app specific commands. Run `kbox apps` to get a list of your apps. 
```

We might eventually want ot replace apps with this `status` command we've been riffing on in the other issue.

**Comment by rgeleta** [comment]
Excellent wording!  I want that!

**Comment by pirog** [comment]
The time has come for this as well!
