### ISSUE TITLE
Support for Deploy module

### ISSUE THREAD

**Issue by mmenavas** [kalabox/kalabox#777]
The deploy module allows content to be migrated between different site environments (i.e. local to pantheon dev). Unfortunately I failed to push content changes from my kalabox site as the deploy module  did not recognize my source (see screenshot). Has anyone had any luck with the deploy module and kalabox?
![deploy](https://cloud.githubusercontent.com/assets/770699/11490404/afe563de-9795-11e5-9ccf-e04ea7278bbf.png)

**Comment by labboy0276** [comment]
Hey Maximo,

The settings are wrong on your localhost settings.  You are looking at
using the kbox host itself.

Also I dont think there is no need to use the deploy module.  KB2 comes
with Drush Config Extras now: https://github.com/drush-ops/config-extra

Here is a sample workflow to get stuff from KB2 to Pantheon Dev:

```
kbox git add -A
kbox drush config-export --commit --message="Awesome commit message"
kbox git push origin master
drush @pantheon.YOURSITE.dev config-import
```

You can also just use the kbox push command to get your DB up to dev.
Which in D8, is pretty much just the content after you merge in the CMI
stuff.

Let me know if this doesn't seem happy to you.



On Mon, Nov 30, 2015 at 9:03 PM, Maximo Mena <notifications@github.com>
wrote:

> The deploy module allows content to be migrated between different site
> environments (i.e. local to pantheon dev). Unfortunately I failed to push
> content changes from my kalabox site as the deploy module did not recognize
> my source (see screenshot). Has anyone had any luck with the deploy module
> and kalabox?
>
> [image: deploy_module]
> <https://cloud.githubusercontent.com/assets/770699/11490337/0e7fa0c2-9795-11e5-8d3b-82b18588dd97.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/777>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by mmenavas** [comment]
Hi John! What's the kbox host itself? How do I figure out what that value is?

I agree that I can push configuration to other environments, but I want to push block content entities and they're not stored as configuration (they're content).

I think I could push the DB to Pantheon, but I'd prefer to just push new content.

Thank you guys for your great work building kalabox!

**Comment by labboy0276** [comment]
Hello again:

so here is your typical mysql string to win into the DB:

mysql -u pantheon -h yoursite.kbox -P 32777 pantheon

so the localhost = yoursite.kbox

Let me know if that helps, etc

On Tue, Dec 1, 2015 at 10:06 AM, Maximo Mena <notifications@github.com>
wrote:

> Hi John! What's the kbox host itself? How do I figure out what that value
> is?
>
> I agree that I can push configuration to other environments, but I want to
> push block content entities and they're not stored as configuration
> (they're content).
>
> I think I could push the DB to Pantheon, but I'd prefer to just push new
> content.
>
> Thank you guys for your great work building kalabox!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/777#issuecomment-160994675>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by mmenavas** [comment]
Thanks again @labboy0276! The db credentials you supplied work if I want to use Sequel Pro to connect to my db. However, I get "source not reachable" even when I use mysite.kbox as the localhost.

I entered 172.17.0.6 as my domain (see hostname in screenshot below), and that took care of the "source not reachable" error. Unfortunately now I'm getting "Target database does not exist".

![log](https://cloud.githubusercontent.com/assets/770699/11506925/f5bdf942-980e-11e5-9602-75645475f209.png)

I think I'm getting closer to a solution, but now I have no idea what's wrong with my target credentials (I'm using a Pantheon site as a target). Is my kbox webserver unable to reach the world wide web? I doubt that. Perhaps I need to learn more about how docker works.

**Comment by labboy0276** [comment]
I am not sure then.  I would just use kbox push instead, much less hassle
and same result.

On Tue, Dec 1, 2015 at 11:43 AM, Maximo Mena <notifications@github.com>
wrote:

> Thanks again @labboy0276 <https://github.com/labboy0276>! The db
> credentials you supplied work if I want to use Sequel Pro to connect to my
> db. However, I get "source not reachable" even when I use mysite.kbox as
> the localhost.
>
> I entered 172.17.0.6 as my domain (see hostname in screenshot below), and
> that took care of the "source not reachable" error. Unfortunately now I'm
> getting "Target database does not exist".
>
> [image: log]
> <https://cloud.githubusercontent.com/assets/770699/11506925/f5bdf942-980e-11e5-9602-75645475f209.png>
>
> I think I'm getting closer to a solution, but now I have no idea what's
> wrong with my target credentials (I'm using a Pantheon site as a target).
> Is my kbox webserver unable to reach the world wide web? I doubt that.
> Perhaps I need to learn more about how docker works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/777#issuecomment-161026579>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by mmenavas** [comment]
I hear you! I'll let it go for now, but if I find I way to make it work in the future, I'll make sure to post the solution here =)

**Comment by pirog** [comment]
Im not super familiar with deploy but ill pull this down and try to replicate as soon as we bang out some more critical issues.

@mmenavas can you post steps to replicate this on kbox. assume (accurately) that i have never used deploy before :)

**Comment by mmenavas** [comment]
@pirog I'm more than happy to help. Here's the steps to replicate the issue:

**A. Install Deploy module**
1. Install a Drupal 8 site in pantheon. Make sure you complete the installation all the way until you see the admin interface.
2. Clone site locally using kalabox. `kbox create pantheon`
3. Install the Composer Manager module, and make sure to thoroughly follow instructions provided on the README file. `kbox drush en composer_manager`.
4. Install Deploy module and its dependencies. `kbox drush en deploy`.
5. Push code changes to Pantheon and make sure to enable the deploy.

**B. Push content changes**
6. On your local site, go to /admin/structure/block/block-content.
7. Add Custom Block.
8. Go to /admin/structure/deploy/push and enter the relaxed database endpoint (url) for your local site and for the pantheon site along with admin credentials (see screenshot above).

I've tested this module by cloning my site on Acquia Dev Desktop, and I was able to push content to the Pantheon site, so I know the module works.

Let me know how I can help =)

**Comment by pirog** [comment]
@mmenavas great write up here. Won't have a chance to look at this for a bit however...

Another thing that you could check in the interim would be to spin up you kalabox site and go to the php info page. At the bottom in the "ENVIRONMENT" section you should see some info about your DB connection that might be helpful
