### ISSUE TITLE
Pantheon release 8.0.0p2 renders tmp directory useless in KBOX2 

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#786]
Hello!

GA release a fix to the tmp problem that was making D8 sites sad on Pantheon as seen here:
https://github.com/pantheon-systems/drops-8/issues/114

It adds this code to the pantheon.settings.php:
```
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  $config['system.file']['path']['temporary'] = $_SERVER['HOME'] .'/tmp';
}
```

This in turn made KB2 sites sad.   $_SERVER['HOME'] = /root in KB2 which does not have a tmp folder in it.  

Solution, add /root/tmp on install

Workaround for now, go in and add ti manually like this:
```
boot2docker --vm="Kalabox2" ssh
docker exec -i -t kb_YOURAPP_appserver bash
mkdir /root/tmp
chmod 775 /root/tmp
```

**Comment by pirog** [comment]
@labboy0276 check out https://github.com/kalabox/kalabox-app-pantheon/blob/v0.10/app/plugins/kalabox-plugin-pantheon/lib/env.js#L373

You can probably easily add in a mkdir $HOME/tmp for this. 

Give it a whirl and submit a PR if you can

**Comment by pirog** [comment]
@labboy0276 is this still true on v0.11?

**Comment by labboy0276** [comment]
I will test this weekend and report back

**Comment by pirog** [comment]
thx. close it out if it seems moot.

**Comment by labboy0276** [comment]
I am not seeing this again, closing.
