### ISSUE TITLE
INSTALl FAILURE - Step 17: "Cannot read property 'ID' of null" (new install of 10.6)

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#800]
info: -- Step 17/23 --
info: Setting up and activating the engine...
info: COULD NOT FIND OLD B2D KEYS => C:Users\John\.ssh\id_boot2docker
info:BOOT2DOCKER => Staring up. disksize=231179, max=3.
info:BOOT2DOCKER => Initializing boot2docker [1].
info:BOOT2DOCKER => Bring boot2docker up [1].
info:BOOT2DOCKER => Bring boot2docker up [2].
info:BOOT2DOCKER => Bring boot2docker up [3].
info: TypeError: Cannot read property 'ID' of null
<b>info: --INSTALL FAILURE. --</b>

**Comment by pirog** [comment]
Looks like your boot2docker is not getting installed correctly.

**Comment by escapesequence** [comment]
The problem appears to be the VB HO Adapter (see below).  I will try to fix it and report back.

=======
Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_SUPDRV_COMPONENT_NOT_FOUND).
Failed to attach the network LUN (VERR_SUPDRV_COMPONENT_NOT_FOUND).

Result Code: 
E_FAIL (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by pirog** [comment]
Are you on Windows 10?

**Comment by escapesequence** [comment]
I have Windows 8.1

**Comment by escapesequence** [comment]
A reinstall of VB fixed the problem.

**Comment by pirog** [comment]
Good to know. Do you know what version you upgraded from and what version
you upgraded to?

On Thu, Dec 10, 2015 at 2:35 PM, escapesequence <notifications@github.com>
wrote:

> A reinstall of VB fixed the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/800#issuecomment-163772437>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by escapesequence** [comment]
I upgraded to 10.6 from 10.5

FYI: I tried to uninstall the VB Ethernet Adapter #2 but still had trouble.  So I uninstalled it and choose the option for deleting code as well.  That made things worse - forced a reinstall, which fixed everything.

**Comment by pirog** [comment]
Sorry... i meant which versions for VirtualBox?


On Thu, Dec 10, 2015 at 5:34 PM, escapesequence <notifications@github.com>
wrote:

> Closed #800 <https://github.com/kalabox/kalabox/issues/800>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/800#event-488888534>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by escapesequence** [comment]
5.0.10

**Comment by pirog** [comment]
Do you know what version of VB you had before the upgrade?

On Fri, Dec 11, 2015 at 12:23 PM, escapesequence <notifications@github.com>
wrote:

> 5.0.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/800#issuecomment-164039460>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by escapesequence** [comment]
same: 5.0.10
