### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by soniktrooth** [kalabox/kalabox#81]
```
TEP [8] -- Checking disk free space....
 --- 29461 MB free of the required 30000 MB
 *** Not enough disk space for install! ***
```

I was a little shocked at first that Kalabox needed 30gb of free space to install but after talking to @pirog I understand that the VM needs to reserve disk space for itself. 

This seems a little problematic to me in this day of still relatively small SSDs. I have a rMBP with 256gb SSD and have to juggle my space a lot but there's a lot of people out there using MacBook Airs are stuck with 128gb drives.

Obviously I know nothing about what you've had to do to achieve what you have and I'm sure you didn't choose the 30gb arbitrarily but for me it's a bit of a show stopper. If a colleage said to me "Check it this rad new Drupal thing/MAMP replacement/whatever I came across today" and when I looked it said 'Requires at least 30gb' I wouldn't have even bothered because of how little wiggle room I have on my SSD.

**Comment by pirog** [comment]
yoyo, can you post this over on https://github.com/kalabox/kalabox-issues
instead?

On Thu, Feb 12, 2015 at 10:01 AM, Josh <notifications@github.com> wrote:

> TEP [8] -- Checking disk free space....
>  --- 29461 MB free of the required 30000 MB
>  *** Not enough disk space for install! ***
>
> I was a little shocked at first that Kalabox needed 30gb of free space to
> install but after talking to @pirog <https://github.com/pirog> I
> understand that the VM needs to reserve disk space for itself.
>
> This seems a little problematic to me in this day of still relatively
> small SSDs. I have a rMBP with 256gb SSD and have to juggle my space a lot
> but there's a lot of people out there using MacBook Airs are stuck with
> 128gb drives.
>
> Obviously I know nothing about what you've had to do to achieve what you
> have and I'm sure you didn't choose the 30gb arbitrarily but for me it's a
> bit of a show stopper. If a colleage said to me "Check it this rad new
> Drupal thing/MAMP replacement/whatever I came across today" and when I
> looked it said 'Requires at least 30gb' I wouldn't have even bothered
> because of how little wiggle room I have on my SSD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/81>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
Sorry!

**Comment by soniktrooth** [comment]
Closing in favour of https://github.com/kalabox/kalabox-issues/issues/226
