### ISSUE TITLE
kbox update: error pulling image

### ISSUE THREAD

**Issue by madeofpeople** [kalabox/kalabox#812]
Installed the latest binary, then I try and ```kbox update```

Fails for most images (debian, syncthing, skydns, getSkydockPostProviderOpts, getHipachePostProviderOpts, getDnsmasqPostProviderOpts) 

```Error while pulling image: Get https://index.docker.io/v1/repositories/kalabox/syncthing/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects```

**Comment by pirog** [comment]
http://stackoverflow.com/questions/30990522/docker-push-fails-too-many-redirects

**Comment by madeofpeople** [comment]
Sadly no dice (assuming in the example ```"boot2docker-vm"``` is ```"Kalabox2"```

**Comment by pirog** [comment]
I assume you tried restarting?

**Comment by madeofpeople** [comment]
Indeed.

**Comment by pirog** [comment]
@madeofpeople this should be fixed in forthcoming v0.11.0 release
