### ISSUE TITLE
Access Files Directory

### ISSUE THREAD

**Issue by Mchampsee** [kalabox/kalabox#816]
Is there a way to access the files directory? I'm some how not figuring it out.

Also, as a feature request, it might be nice to have the option to point to the files directory on Pantheon (or where-ever), and not download the files at all.

**Comment by pirog** [comment]
@Mchampsee there is not currently a way to directly access the files directory although that is slated for change in #511 

i doubt we will support a "direct on pantheon" feature however this is certainly something you can get your site set up to do using the relevant drupal modules and then you can tell kalabox to not pull your file with the `--files=none` flag.

**Comment by ehausen** [comment]
#822

**Comment by reynoldsalec** [comment]
@Mchampsee 

This issue will be much easier for us to resolve once we release 0.11.0, which should be out in the next couple weeks. Will leave this open until @pirog can give us word on an easier way to access files.

We'll also discuss remote file handling on #822, although at this point @pirog's advice to simply not pull files (and use Stage File Proxy to point to a remote files directory) is a great solution that's pretty easy.

**Comment by pirog** [comment]
There is a meta issue at #511 that puts this on the post-beta roadmap. i would def +1 that

**Comment by pirog** [comment]
There is an open issue for this and it should be in v0.11.2 

#922
