### ISSUE TITLE
Implement an option to use the Stage File Proxy module

### ISSUE THREAD

**Issue by ehausen** [kalabox/kalabox#822]
# Feature Request
### Problem:
The files directory of an Drupal install might be huge and you might have several sites on your laptop...

### Solution:
[Stage File Proxy Module]
(https://www.drupal.org/project/stage_file_proxy)
>Stage File Proxy saves you time and disk space by sending requests to your development environment's files directory to the production environment and making a copy of the production file in your development site.

>When developing Drupal sites locally, you often face a choice between broken images and taking the time to copy a snapshot of the remote files directory, which might be several gigabytes large, depending on the site. Stage File Proxy lets you update the database of your local development instance without having to update your files directory.
...
>Stage File Proxy has an additional mode in which it can serve a 301 redirect to files on the server, so it's possible to see all your images without having a local files directory at all.

**Comment by jdleonard** [comment]
+1 :)

**Comment by reynoldsalec** [comment]
Good idea @ehausen; I know a couple users (including @Patrick-123 and @labboy0276) have used Stage File Proxy in the past with Kalabox; have you or @jdleonard got it to work successfully?

As for making this a feature of Kalabox, I guess we'd just download the module for users and enable the correct URL in their settings? I'm a little nervous about us making these types of changes for users and think it may be better to solve this issue with documentation on how to use Stage File Proxy, but definitely interested if you think there's a good way to have Kalabox help folks out with the "shload of files" problem ;)

**Comment by jdleonard** [comment]
I haven't tried it with Kalabox.

**Comment by pirog** [comment]
I don't think we intend to implement features like this since you run into all sorts of meta and real issues when attempting to modify people's codebases.

that said if there is a specific issue you are having that is kalabox related getting this to work please open another ticket!
