### ISSUE TITLE
STATS - look into replacing custom stats collection with stats collection service

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#826]
elastic search
logstash
statuspage.io

**Comment by reynoldsalec** [comment]
*General Requirements*

- Evaluate performance
- Consider performance at scale (would we have a roadmap to making it scale? Don't need to figure out everything now)
- Can we export the data successfully?
- Security of posting data to the stats server (will it keep those damn kids from throwing our stats off?)

Bugsnag: this would replace our "error report" on the current stats reports, but we'd need another system to collect stats and deliver intelligence on non-error reports.

**Comment by reynoldsalec** [comment]
Elasticsearch does seem to be the best option.

Hosting on Qbox appears to be cost-effective for what we need to do.

Todo:
- Choose an elasticsearch NPM library; consider ease of use first, then size (elastical looked possible)
- Figure out how the permissioning will work to limit posting to valid users

For future:
- Backups for data
