### ISSUE TITLE
TED - purchase a vmware fusion license

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#840]

**Comment by pirog** [comment]
We need one for @rileysaurus and ted. the $79 version seems to be sufficient. adding this to the current sprint.

@rileysaurus, when do you need this by?

**Comment by rileysaurus** [comment]
I think we just need the one for ted right now. Our trial license runs out
in 7 days, so before then would be good, otherwise I can just reset the
trail again.

**Comment by pirog** [comment]
@rileysaurus should be in lastpass now
