### ISSUE TITLE
Pantheon Multidev install.php?

### ISSUE THREAD

**Issue by mojowill** [kalabox/kalabox#852]
When creating kbox instance from pantheon selecting a multidev env everything runs fine and it successfully completes all the commands, however when I go to the URL I get the drupal install page? If I try to run the install I get an error as the tables already exist?

**Comment by labboy0276** [comment]
This does happen to me as well.  Usually I have to destroy and rebuild.

Albeit it is resolved in 0.11.0 which is being released today / tomorrow
from what I am told.

On Thu, Jan 21, 2016 at 7:12 AM, Will Wilson <notifications@github.com>
wrote:

> When creating kbox instance from pantheon selecting a multidev env
> everything runs fine and it successfully completes all the commands,
> however when I go to the URL I get the drupal install page? If I try to run
> the install I get an error as the tables already exist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/852>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by labboy0276** [comment]
I can confirm this works happily now on 0.11.0, closing it out.
