### ISSUE TITLE
kbox git log output looks odd in 0.11.0

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#855]
Hello!

Check out the image below, seems the vi or nano output is a little off on kbox git log:

![gitlog](https://cloud.githubusercontent.com/assets/5560907/12520979/b6679da4-c115-11e5-8b8a-905ce99977ba.png)

**Comment by pirog** [comment]
This is just because the git container doesn't know about colors. Not
really an error.

**Comment by labboy0276** [comment]
yes, colors are good

**Comment by pirog** [comment]
Do you get the same thing with `git log --decorate`? 
http://stackoverflow.com/questions/5889878/color-in-git-log

Would def take a PR for the cli container that adds in better color support. My guess is that alpine just doesnt have as many colors to work with so we need to set more base colors.

**Comment by labboy0276** [comment]
negative ghost rider, that command makes it worse:

![woahhhhhh](https://cloud.githubusercontent.com/assets/5560907/12532322/42861e4a-c1df-11e5-9ca6-b3331bea42f2.png)

**Comment by pirog** [comment]
might be worth playing around with
http://wiki.alpinelinux.org/wiki/Development_using_git

**Comment by pirog** [comment]
The conf you want to do this is

```
[core]
  pager = more
[color]
  ui = true
[color "branch"]
  current = yellow reverse
  local = yellow
  remote = green
[color "diff"]
  meta = yellow bold
  frag = magenta bold
  old = red bold
  new = green bold
[color "status"]
  added = yellow
  changed = green
  untracked = cyan
[push]
  default = simple
```

Will be in 0.11.1

**Comment by labboy0276** [comment]
fantastical
