### ISSUE TITLE
Set default git push config to simple?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#861]
Hello!

Now when you do a git push on 0.11.0, you get the message as to which git push default to use.  Should we stick it to simple as it has been by default?  This way humans don;t get said message....
```
john@kalamuna:~/kalabox/apps/mrpc/code$ kbox git push
info: COMPOSE =>  0=--project-name, 1=mrpc, 2=--file, 3=/home/john/kalabox/apps/mrpc/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/mrpc/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/mrpc/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=kgit, 11=--rm, 12=cli, 13=push, mode=attach
Starting mrpc_data_1
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Warning: Permanently added '[codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803.drush.in]:2222,[166.78.112.79]:2222' (RSA) to the list of known hosts.
Counting objects: 136, done.
Compressing objects: 100% (135/135), done.
Writing objects: 100% (136/136), 88.00 KiB | 0 bytes/s, done.
Total 136 (delta 71), reused 0 (delta 0)
To ssh://codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803@codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803.drush.in:2222/~/repository.git
   6edabac..072d877  master -> master
info: DOCKER-COMPOSE =>  Run exited with code: 0
```

**Comment by pirog** [comment]
It's best practice to specify the remote and branch so going to go with no
here

On Saturday, January 23, 2016, John Ouellet <notifications@github.com>
wrote:

> Hello!
>
> Now when you do a git push on 0.11.0, you get the message as to which git
> push default to use. Should we stick it to simple as it has been by
> default? This way humans don;t get said message....
>
> john@kalamuna:~/kalabox/apps/mrpc/code$ kbox git push
> info: COMPOSE =>  0=--project-name, 1=mrpc, 2=--file, 3=/home/john/kalabox/apps/mrpc/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/mrpc/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/mrpc/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=kgit, 11=--rm, 12=cli, 13=push, mode=attach
> Starting mrpc_data_1
> warning: push.default is unset; its implicit value has changed in
> Git 2.0 from 'matching' to 'simple'. To squelch this message
> and maintain the traditional behavior, use:
>
>   git config --global push.default matching
>
> To squelch this message and adopt the new behavior now, use:
>
>   git config --global push.default simple
>
> When push.default is set to 'matching', git will push local branches
> to the remote branches that already exist with the same name.
>
> Since Git 2.0, Git defaults to the more conservative 'simple'
> behavior, which only pushes the current branch to the corresponding
> remote branch that 'git pull' uses to update the current branch.
>
> See 'git help config' and search for 'push.default' for further information.
> (the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
> 'current' instead of 'simple' if you sometimes use older versions of Git)
>
> Warning: Permanently added '[codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803.drush.in]:2222,[166.78.112.79]:2222' (RSA) to the list of known hosts.
> Counting objects: 136, done.
> Compressing objects: 100% (135/135), done.
> Writing objects: 100% (136/136), 88.00 KiB | 0 bytes/s, done.
> Total 136 (delta 71), reused 0 (delta 0)
> To ssh://codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803@codeserver.dev.e223517f-5fc3-45b0-be1d-355ff157c803.drush.in:2222/~/repository.git
>    6edabac..072d877  master -> master
> info: DOCKER-COMPOSE =>  Run exited with code: 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/861>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by pirog** [comment]
Actually probably less support tickets if we implement this but going to roll this into issue #855
