### ISSUE TITLE
 Suggestion: put the name of the site in the warning when running `kbox destroy`

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#864]
I suggest adding the name of the site when running kbox destroy. This is similar to how Pantheon does it (actually, Pantheon asks you to type the site name instead of "y" to delete it, which might be too much here, since the app can be restored, but just to prevented unintended Godzilla actions it would be great to have the site name printed in the error message, maybe something like this:

 WARNING! APP  _SITENAME_ DESTRUCTION IMMINENT

  Before you continue please be aware that after you destroy
  an app there will be nothing left. That means yours app's
  codes, files, databases, indeces, caches, containers and
  EVERYTHING ELSE that has to do with your app SITENAME WILL BE GONE.
  
  ###############################################################
  ? So, are you still prepared to DESTROY SITENAME? Yes

**Comment by pirog** [comment]
@ptmkenny thanks for moving this over. def will try to give it a look-see in the upcoming weeks. seems like a completely reasonable proposal.

**Comment by pirog** [comment]
@ptmkenny i think we should also inform the user that their app directory is now safe to remove after this.
