### ISSUE TITLE
Drupal 8 errors in 0.11.0

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#865]
Hello!

So this Drupal 8 site i ran the other day on 0.10.6 with no problems at all.  I created it in 0.11.0 And I am just failing at every level:

Here is a config-extras command right after I started the app:
```
john@kalamuna:~/kalabox/apps/bakers-mission$ kbox drush config-import
info: COMPOSE =>  0=--project-name, 1=bakers-mission, 2=--file, 3=/home/john/kalabox/apps/bakers-mission/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=drush8, 11=--rm, 12=terminus, 13=config-import, 14=--strict=0, mode=attach
Starting bakersmission_data_1
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /code/core/lib/Drupal/Core/Entity/ContentEntityType.php on line 43
Drush command terminated abnormally due to an unrecoverable error.                                                                   [error]
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/code/core/lib/Drupal/Core/Entity/ContentEntityType.php, line 43
Drush was not able to start (bootstrap) Drupal.                                                                                      [error]
Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally
points to a site configuration issue, and not a problem connecting to the database.

Drush was attempting to connect to: 
 Drupal version                  :  8.0.2                                                                      
 Site URI                        :  http://default                                                             
 Database driver                 :  mysql                                                                      
 Database hostname               :  database                                                                   
 Database port                   :  3306                                                                       
 Database username               :  pantheon                                                                   
 Database name                   :  pantheon                                                                   
 Default theme                   :  bakers                                                                     
 Administration theme            :  seven                                                                      
 PHP executable                  :  /usr/bin/php                                                               
 PHP configuration               :  /etc/php5/cli/php.ini                                                      
 PHP OS                          :  Linux                                                                      
 Drush script                    :  /usr/local/src/drush8/drush.php                                            
 Drush version                   :  8.0.0                                                                      
 Drush temp directory            :  /tmp                                                                       
 Drush configuration             :                                                                             
 Drush alias files               :  /root/.drush/aliases.drushrc.php /root/.drush/pantheon.aliases.drushrc.php 
 Install profile                 :  standard                                                                   
 Drupal root                     :  /code                                                                      
 Site path                       :  sites/default                                                              
 File directory path             :  sites/default/files                                                        
 Private file directory path     :  sites/default/files/private                                                
 Temporary file directory path   :  sites/default/files/tmp                                                    
 Sync config path                :  sites/default/config                                                       


info: DOCKER-COMPOSE =>  Run exited with code: 255
Unhandled rejection VError: code255err:more:
    at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
    at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
From previous event:
    at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:341:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
    at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
    at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:471:29
From previous event:
    at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
    at process._tickCallback (node.js:803:1)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:230:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:595:24)
    at Module.load (module.js:425:6)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:813:8)
    at startup (node.js:374:8)
    at node.js:1461:1
```

Here is a normal cache clear request:

```
john@kalamuna:~/kalabox/apps/bakers-mission$ kbox drush cr
info: COMPOSE =>  0=--project-name, 1=bakers-mission, 2=--file, 3=/home/john/kalabox/apps/bakers-mission/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=drush8, 11=--rm, 12=terminus, 13=cr, 14=--strict=0, mode=attach
Starting bakersmission_data_1
exception 'RuntimeException' with message 'Missing $settings['hash_salt'] in settings.php.' in                                       [error]
/code/core/lib/Drupal/Core/Site/Settings.php:145
Stack trace:
#0 /code/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47): Drupal\Core\Site\Settings::getHashSalt()
#1 /code/core/includes/utility.inc(32): Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
#2 /usr/local/src/drush8/commands/core/cache.drush.inc(290): drupal_rebuild(Object(Composer\Autoload\ClassLoader),
Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: drush_cache_rebuild()
#4 /usr/local/src/drush8/includes/command.inc(364): call_user_func_array('drush_cache_reb...', Array)
#5 /usr/local/src/drush8/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 /usr/local/src/drush8/includes/command.inc(183): call_user_func_array('drush_command', Array)
#8 /usr/local/src/drush8/lib/Drush/Boot/BaseBoot.php(65): drush_dispatch(Array)
#9 /usr/local/src/drush8/includes/preflight.inc(64): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /usr/local/src/drush8/drush.php(12): drush_main()
#11 {main}
info: DOCKER-COMPOSE =>  Run exited with code: 1
Unhandled rejection VError: code1err:more:
    at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
    at ChildProcess.emit (events.js:85:9)
    at maybeClose (child_process.js:773:12)
    at Process.ChildProcess._handle.onexit (child_process.js:839:1)
From previous event:
    at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
    at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
    at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
From previous event:
    at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:341:12)
    at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
    at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
    at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
    at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
From previous event:
    at /usr/local/bin/lib/engine.js.jx:471:29
From previous event:
    at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
    at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
    at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
    at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
    at process._tickCallback (node.js:803:1)
From previous event:
    at main (/usr/local/bin/bin/kbox.js.jx:230:4)
    at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
    at Module._compile (module.js:595:24)
    at readX (module.js:1488:3)
    at Object.Module._extensions..jx (module.js:1921:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (_jx_source:17:1)
    at Module._compile (module.js:595:24)
    at Module.load (module.js:425:6)
    at Function.Module._load (module.js:380:8)
    at Function.Module.runMain (module.js:813:8)
    at startup (node.js:374:8)
    at node.js:1461:1
john@kalamuna:~/kalabox/apps/bakers-mission$ 
```

When I go in the browser to the app.kbox, I see this:
```
Parse error: syntax error, unexpected '[', expecting ')' in /code/vendor/guzzlehttp/promises/src/functions.php on line 41 Call Stack: 0.0069 652184 1. {main}() /code/index.php:0 0.0070 652576 2. require_once('/code/autoload.php') /code/index.php:14 0.0070 653008 3. require('/code/vendor/autoload.php') /code/autoload.php:14 0.0070 655440 4. ComposerAutoloaderInitDrupal8::getLoader() /code/vendor/autoload.php:7 0.0080 848920 5. composerRequireDrupal8() /code/vendor/composer/autoload_real.php:45 0.0080 849752 6. require('/code/vendor/guzzlehttp/promises/src/functions_include.php') /code/vendor/composer/autoload_real.php:55
```

This output almost looks like a php 5.3 to php 5.5 error.  However when I check the kalabox.yml, it shows this:

```
name: bakers-mission
type: pantheon
plugins:
  - kalabox-plugin-pantheon
pluginconfig:
  cli: 'on'
  syncthing:
    share: 'data:/code'
    ignore:
      - sites/default/files
      - files
      - wp-content/uploads
      - '!*modules*'
  services:
    appserver:
      - port: 8888/tcp
        hostname: appserver
    edge:
      - port: 80/tcp
        default: true
      - port: 443/tcp
        default: true
        secure: true
  pantheon:
    email: john@kalamuna.com
    site: bakers-mission
    env: dev
    framework: drupal8
    php: 55
    upstream:
      url: 'git://github.com/pantheon-systems/drops-8.git'
      product_id: 8a129104-9d37-4082-aaf8-e6f31154644e
      branch: master
    name: John Ouellet
```

Thoughts?

**Comment by pirog** [comment]
Drop a phpinfo() file in your web root to help see what's going on

On Sunday, January 24, 2016, John Ouellet <notifications@github.com> wrote:

> Hello!
>
> So this Drupal 8 site i ran the other day on 0.10.6 with no problems at
> all. I created it in 0.11.0 And I am just failing at every level:
>
> Here is a config-extras command right after I started the app:
>
> john@kalamuna:~/kalabox/apps/bakers-mission$ kbox drush config-import
> info: COMPOSE =>  0=--project-name, 1=bakers-mission, 2=--file, 3=/home/john/kalabox/apps/bakers-mission/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=drush8, 11=--rm, 12=terminus, 13=config-import, 14=--strict=0, mode=attach
> Starting bakersmission_data_1
> PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /code/core/lib/Drupal/Core/Entity/ContentEntityType.php on line 43
> Drush command terminated abnormally due to an unrecoverable error.                                                                   [error]
> Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
> /code/core/lib/Drupal/Core/Entity/ContentEntityType.php, line 43
> Drush was not able to start (bootstrap) Drupal.                                                                                      [error]
> Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally
> points to a site configuration issue, and not a problem connecting to the database.
>
> Drush was attempting to connect to:
>  Drupal version                  :  8.0.2
>  Site URI                        :  http://default
>  Database driver                 :  mysql
>  Database hostname               :  database
>  Database port                   :  3306
>  Database username               :  pantheon
>  Database name                   :  pantheon
>  Default theme                   :  bakers
>  Administration theme            :  seven
>  PHP executable                  :  /usr/bin/php
>  PHP configuration               :  /etc/php5/cli/php.ini
>  PHP OS                          :  Linux
>  Drush script                    :  /usr/local/src/drush8/drush.php
>  Drush version                   :  8.0.0
>  Drush temp directory            :  /tmp
>  Drush configuration             :
>  Drush alias files               :  /root/.drush/aliases.drushrc.php /root/.drush/pantheon.aliases.drushrc.php
>  Install profile                 :  standard
>  Drupal root                     :  /code
>  Site path                       :  sites/default
>  File directory path             :  sites/default/files
>  Private file directory path     :  sites/default/files/private
>  Temporary file directory path   :  sites/default/files/tmp
>  Sync config path                :  sites/default/config
>
>
> info: DOCKER-COMPOSE =>  Run exited with code: 255
> Unhandled rejection VError: code255err:more:
>     at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
>     at ChildProcess.emit (events.js:85:9)
>     at maybeClose (child_process.js:773:12)
>     at Process.ChildProcess._handle.onexit (child_process.js:839:1)
> From previous event:
>     at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
>     at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
>     at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
> From previous event:
>     at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:341:12)
>     at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
>     at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
>     at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
> From previous event:
>     at /usr/local/bin/lib/engine.js.jx:471:29
> From previous event:
>     at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
>     at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
>     at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
>     at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
>     at process._tickCallback (node.js:803:1)
> From previous event:
>     at main (/usr/local/bin/bin/kbox.js.jx:230:4)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
>     at Module._compile (module.js:595:24)
>     at readX (module.js:1488:3)
>     at Object.Module._extensions..jx (module.js:1921:8)
>     at Module.load (module.js:416:30)
>     at Function.Module._load (module.js:380:8)
>     at Module.require (module.js:451:15)
>     at require (module.js:469:13)
>     at Object.<anonymous> (_jx_source:17:1)
>     at Module._compile (module.js:595:24)
>     at Module.load (module.js:425:6)
>     at Function.Module._load (module.js:380:8)
>     at Function.Module.runMain (module.js:813:8)
>     at startup (node.js:374:8)
>     at node.js:1461:1
>
> Here is a normal cache clear request:
>
> john@kalamuna:~/kalabox/apps/bakers-mission$ kbox drush cr
> info: COMPOSE =>  0=--project-name, 1=bakers-mission, 2=--file, 3=/home/john/kalabox/apps/bakers-mission/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=drush8, 11=--rm, 12=terminus, 13=cr, 14=--strict=0, mode=attach
> Starting bakersmission_data_1
> exception 'RuntimeException' with message 'Missing $settings['hash_salt'] in settings.php.' in                                       [error]
> /code/core/lib/Drupal/Core/Site/Settings.php:145
> Stack trace:
> #0 /code/core/lib/Drupal/Core/PhpStorage/PhpStorageFactory.php(47): Drupal\Core\Site\Settings::getHashSalt()
> #1 /code/core/includes/utility.inc(32): Drupal\Core\PhpStorage\PhpStorageFactory::get('twig')
> #2 /usr/local/src/drush8/commands/core/cache.drush.inc(290): drupal_rebuild(Object(Composer\Autoload\ClassLoader),
> Object(Symfony\Component\HttpFoundation\Request))
> #3 [internal function]: drush_cache_rebuild()
> #4 /usr/local/src/drush8/includes/command.inc(364): call_user_func_array('drush_cache_reb...', Array)
> #5 /usr/local/src/drush8/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
> #6 [internal function]: drush_command()
> #7 /usr/local/src/drush8/includes/command.inc(183): call_user_func_array('drush_command', Array)
> #8 /usr/local/src/drush8/lib/Drush/Boot/BaseBoot.php(65): drush_dispatch(Array)
> #9 /usr/local/src/drush8/includes/preflight.inc(64): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #10 /usr/local/src/drush8/drush.php(12): drush_main()
> #11 {main}
> info: DOCKER-COMPOSE =>  Run exited with code: 1
> Unhandled rejection VError: code1err:more:
>     at ChildProcess.<anonymous> (/usr/local/bin/lib/util/shell.js.jx:247:16)
>     at ChildProcess.emit (events.js:85:9)
>     at maybeClose (child_process.js:773:12)
>     at Process.ChildProcess._handle.onexit (child_process.js:839:1)
> From previous event:
>     at Object.exports.spawn (/usr/local/bin/lib/util/shell.js.jx:211:10)
>     at Object.sh (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/lib/bin.js.jx:92:20)
>     at /usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:60:18
> From previous event:
>     at shCompose (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:42:6)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/provider/docker/compose.js.jx:341:12)
>     at /usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:260:24
>     at arrayMap (/usr/local/bin/node_modules/lodash/index.js.jx:1405:25)
>     at Function.map (/usr/local/bin/node_modules/lodash/index.js.jx:6709:14)
>     at Object.run (/usr/local/bin/plugins/kalabox-engine-docker/index.js.jx:177:26)
> From previous event:
>     at /usr/local/bin/lib/engine.js.jx:471:29
> From previous event:
>     at Object.exports.run (/usr/local/bin/lib/engine.js.jx:470:4)
>     at Object.task.func (/usr/local/bin/plugins/kalabox-cli/lib/tasks.js.jx:100:34)
>     at Object.exports.run (/usr/local/bin/lib/core/tasks.js.jx:884:15)
>     at processTask (/usr/local/bin/bin/kbox.js.jx:168:16)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:231:12)
>     at process._tickCallback (node.js:803:1)
> From previous event:
>     at main (/usr/local/bin/bin/kbox.js.jx:230:4)
>     at Object.<anonymous> (/usr/local/bin/bin/kbox.js.jx:239:1)
>     at Module._compile (module.js:595:24)
>     at readX (module.js:1488:3)
>     at Object.Module._extensions..jx (module.js:1921:8)
>     at Module.load (module.js:416:30)
>     at Function.Module._load (module.js:380:8)
>     at Module.require (module.js:451:15)
>     at require (module.js:469:13)
>     at Object.<anonymous> (_jx_source:17:1)
>     at Module._compile (module.js:595:24)
>     at Module.load (module.js:425:6)
>     at Function.Module._load (module.js:380:8)
>     at Function.Module.runMain (module.js:813:8)
>     at startup (node.js:374:8)
>     at node.js:1461:1
> john@kalamuna:~/kalabox/apps/bakers-mission$
>
> When I go in the browser to the app.kbox, I see this:
>
> Parse error: syntax error, unexpected '[', expecting ')' in /code/vendor/guzzlehttp/promises/src/functions.php on line 41 Call Stack: 0.0069 652184 1. {main}() /code/index.php:0 0.0070 652576 2. require_once('/code/autoload.php') /code/index.php:14 0.0070 653008 3. require('/code/vendor/autoload.php') /code/autoload.php:14 0.0070 655440 4. ComposerAutoloaderInitDrupal8::getLoader() /code/vendor/autoload.php:7 0.0080 848920 5. composerRequireDrupal8() /code/vendor/composer/autoload_real.php:45 0.0080 849752 6. require('/code/vendor/guzzlehttp/promises/src/functions_include.php') /code/vendor/composer/autoload_real.php:55
>
> This output almost looks like a php 5.3 to php 5.5 error. However when I
> check the kalabox.yml, it shows this:
>
> name: bakers-mission
> type: pantheon
> plugins:
>   - kalabox-plugin-pantheon
> pluginconfig:
>   cli: 'on'
>   syncthing:
>     share: 'data:/code'
>     ignore:
>       - sites/default/files
>       - files
>       - wp-content/uploads
>       - '!*modules*'
>   services:
>     appserver:
>       - port: 8888/tcp
>         hostname: appserver
>     edge:
>       - port: 80/tcp
>         default: true
>       - port: 443/tcp
>         default: true
>         secure: true
>   pantheon:
>     email: john@kalamuna.com <javascript:_e(%7B%7D,'cvml','john@kalamuna.com');>
>     site: bakers-mission
>     env: dev
>     framework: drupal8
>     php: 55
>     upstream:
>       url: 'git://github.com/pantheon-systems/drops-8.git'
>       product_id: 8a129104-9d37-4082-aaf8-e6f31154644e
>       branch: master
>     name: John Ouellet
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/865>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by labboy0276** [comment]
Houston, we have a problem:

PHP Version 5.3.29

Thoughts?

**Comment by pirog** [comment]
There you go

**Comment by pirog** [comment]
Looks like the Kalabox compose yml still has pho version hard coded. Change
that to '55' rebuild and report back.

Long term that needs to be set to the correct env variable. Run kbox env to
find it and submit a pr

**Comment by labboy0276** [comment]
The YML file already has 55 in it:

```
  pantheon:
    email: john@kalamuna.com
    site: bakers-mission
    env: dev
    framework: drupal8
    php: 55
    upstream:
      url: 'git://github.com/pantheon-systems/drops-8.git'
      product_id: 8a129104-9d37-4082-aaf8-e6f31154644e
      branch: master
    name: John Ouellet
```

thoughts?

**Comment by pirog** [comment]
Kalabox compose yml not Kalabox yml

**Comment by labboy0276** [comment]
Corrected PHP_VERSION to 55 kalabox-compose.yml

rebuilt = success

**Comment by pirog** [comment]
Run Kbox env inside your app and find the environmental variable that has
the php version and then submit a pr against the pantheon app and link to
it here

**Comment by labboy0276** [comment]
All set, there was also a weird drush sadness happening due to the fact we need to be on the latest and greatest version of drush (8.0.2), otherwise you get things like this:

```
john@kalamuna:~/kalabox/apps/bakers-mission/code$ kbox drush up
info: COMPOSE =>  0=--project-name, 1=bakers-mission, 2=--file, 3=/home/john/kalabox/apps/bakers-mission/kalabox-compose.yml, 4=--file, 5=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 6=--file, 7=/home/john/kalabox/apps/bakers-mission/kalabox-cli.yml, 8=run, 9=--entrypoint, 10=drush8, 11=--rm, 12=terminus, 13=up, 14=--strict=0, mode=attach
Starting bakersmission_data_1
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /code/core/lib/Drupal/Core/Entity/ContentEntityType.php on line 43
Drush command terminated abnormally due to an unrecoverable error.                                                                   [error]
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in
/code/core/lib/Drupal/Core/Entity/ContentEntityType.php, line 43
Drush was not able to start (bootstrap) Drupal.                                                                                      [error]
Hint: This error can only occur once the database connection has already been successfully initiated, therefore this error generally
points to a site configuration issue, and not a problem connecting to the database.
```

https://github.com/kalabox/kalabox-app-pantheon/pull/78

**Comment by pirog** [comment]
This looks the same version error that you reported above?

**Comment by labboy0276** [comment]
I separated out the PRs, one for PHP on fer drush

**Comment by pirog** [comment]
Can you link to both PRs here so we can track them?

**Comment by labboy0276** [comment]
https://github.com/kalabox/kalabox-app-pantheon/pull/78

https://github.com/kalabox/kalabox-app-pantheon/pull/79
