### ISSUE TITLE
Error on kbox push

### ISSUE THREAD

**Issue by mojowill** [kalabox/kalabox#868]
Built a local environment all good. Did a bit of development, happy days. 

kbox push makes me sad:
```
Failed after 5 retries. {"max":5,"backoff":500}: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
{"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
{"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}

Error: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
{"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
{"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}

    at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:128:17
From previous event:
    at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:125:13
    at /usr/local/bin/lib/promise.js.jx:46:16
From previous event:
    at rec (/usr/local/bin/lib/promise.js.jx:45:25)
    at /usr/local/bin/lib/promise.js.jx:57:20
    at process._tickCallback (node.js:917:1)
~/Sites/pantheon.io/titan-us$
```

**Comment by labboy0276** [comment]
Hi Will

What binary version are you using right now?

On Mon, Jan 25, 2016 at 10:52 AM, Will Wilson <notifications@github.com>
wrote:

> Built a local environment all good. Did a bit of development, happy days.
>
> kbox push makes me sad:
>
> Failed after 5 retries. {"max":5,"backoff":500}: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
> {"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
> {"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}
>
> Error: VError: code1err:more:{"date":"2016-01-25 15:47:45","level":"INFO","message":"API Request Error: {msg}"}
> {"date":"2016-01-25 15:47:45","level":"INFO","message":"Cannot retrieve current Terminus version."}
> {"date":"2016-01-25 15:47:49","level":"ERROR","message":"There is no such field."}
>
>     at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:128:17
> From previous event:
>     at /Users/mojowill/Sites/pantheon.io/titan-us/plugins/kalabox-plugin-pantheon/lib/terminus.js:125:13
>     at /usr/local/bin/lib/promise.js.jx:46:16
> From previous event:
>     at rec (/usr/local/bin/lib/promise.js.jx:45:25)
>     at /usr/local/bin/lib/promise.js.jx:57:20
>     at process._tickCallback (node.js:917:1)
> ~/Sites/pantheon.io/titan-us$
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/868>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
Going to close this in favor of reopening #679

@mojowill are you getting this on multdev?

**Comment by pirog** [comment]
@mojowill, also, what version are you using?
