### ISSUE TITLE
Use Pantheon or Local dashboard images

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#874]
Sad to see the cats go, but they aren't very meaningful.

Would be good to download these so we don't have to show them.

**Comment by reynoldsalec** [comment]
Best-case functionality: every time you start the site, once it's started a screenshot is taken that updates the Dashboard.

A simpler approach would be grabbing the existing screenshots from Pantheon.

@rileysaurus I was going to insert this functionality in the Angular code that starts the site (Site.prototype.start in installedSites.js). However, I was wondering if there was a way I could respond to the same events that kbox emits to the plugins. Perhaps even making this functionality into a plugin would be best, although I don't think there's any easy way of inserting a new core plugin from the GUI (@pirog I'm sure has thoughts there).

**Comment by pirog** [comment]
@reynoldsalec we can def make some changes to kalabox so that it looks in the gui for plugins as well
