### ISSUE TITLE
Initialization Page

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#876]
Our install/initialization page needs some stylistic updates. This is a good place to add some fun messages and other things.

**Comment by reynoldsalec** [comment]
Styled this bad boy up, also have a dark background version I might consider depending on eventual direction with the whole app design.

**Comment by pirog** [comment]
Nice!!!

On Thursday, January 28, 2016, Alec Reynolds <notifications@github.com>
wrote:

> Styled this bad boy up, also have a dark background version I might
> consider depending on eventual direction with the whole app design.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/876#issuecomment-176600257>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc
