### ISSUE TITLE
Uninstall of 0.10.6 left hosts file entries that resulted in timeouts when visiting 0.11 sites

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#877]
This problem might be reproducible as follows:
1. Install 0.10.6 on yo Macintosh
2. Create a site and spin it up
3. kbox destory it
4. kbox down
5. Run 0.10.6 uninstall script
6. Install 0.11
7. Create a site with the same name as the one in step 2 and spin it up
8. View site in browser

Expected: viewing the site
Actual: connection times out due to old hosts file entry for that site from 10.6

To resolve the problem, I deleted the hosts file lines for old kalabox sites and recreated the site (nothing less severe seemed to be working).

**Comment by pirog** [comment]
What did you have in the old file? and what file was it?

**Comment by jdleonard** [comment]
/etc/hosts had an entry for my site "copperly.kbox" pointing to some Kalabox-sounding IP address (I don't have the address handy). Not 100% sure it came from 0.10.6.

**Comment by pirog** [comment]
oh wow. yeah we haven't edited /etc/hosts for a long time so its possible
that is from v1?

the uninstall script should remove /etc/resolver/kbox which is what we use
instead of direct /etc/hosts manipulation.

**Comment by jdleonard** [comment]
Ok, it must have been real old!
