### ISSUE TITLE
Kalabox 0.11 VM configured to use just one processor

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#878]
Not sure whether this is expected, but I cracked open VirtualBox and noticed that Kalabox's VM was configured to use just one processor. IIRC, 0.10 used multiple.

**Comment by pirog** [comment]
yeah that should be correct. im not sure if multiple processors is needed?
thinking lowest common denominator here.

**Comment by jdleonard** [comment]
My understanding is that the VM shares however many processors it is allocated with the host system so I would expect things would run faster overall if it had access to all the processors to get its work done more quickly, but this isn't really my area of expertise...

**Comment by pirog** [comment]
yeah im honestly not completely sure either. i'll keep this issue open.
definitely let us know if it seems significantly slower to you.

**Comment by jdleonard** [comment]
As a datapoint, for me there was zero difference in the time to "kbox start && kbox down" from within my app's directory in a down state for 1 vs 8 processors configured on the VM. I suppose there would only be a difference if those commands cause any multithreaded stuff to happen.

**Comment by pirog** [comment]
Yeah i get the same when i do that. I'm pretty sure this doesnt make a difference either way but ill keep this issue open in the icebox.
