### ISSUE TITLE
Install fails when extracting virtualbox .kalabox/downloads/vbox on windows

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#887]
![kbox-11-install-error](https://cloud.githubusercontent.com/assets/22901/12583175/6873712a-c40f-11e5-8bc5-4d1c8cac042f.jpg)

**Comment by pirog** [comment]
@shaal can you give any more detail about your previous virtualbox install?

had you installed kalabox previously before trying this install?
did you have an older version of virtualbox?
was virtualbox running when you attempted the first intall?

**Comment by shaal** [comment]
I had Kalabox v.10, but installation was not possible.
so i ran the special kalabox uninstall batch file, that says at the end 'uninstalling virtual box is optional'.
virtualbox was not running while i installed kalabox.
after manually uninstalling virtualbox - i ran the command 'kbox update', and it was a success.

**Comment by pirog** [comment]
Awesome. Very helpful. 

Guessing this failed the first time because of vestigial kalabox host-adapters from the attempted v0.10 install.

**Comment by pirog** [comment]
So i ran into this on one test as well and running

```
kbox update
kbox create pantheon
```

Seemed to resolve it for me.

**Comment by pirog** [comment]
Option here would be to retry the admin install commands if they fail

**Comment by pirog** [comment]
Going to wait for more feedback on this one before we do anything.

**Comment by pirog** [comment]
@shaal we are going to be releasing a native windows installer for 0.12.x (sometime next week) which should definitely resolve this particular issue.
