### ISSUE TITLE
Errors when updating kalabox

### ISSUE THREAD

**Issue by rjbain** [kalabox/kalabox#890]
Hey guys,

After replacing the kbox file on my OSX machine and running `kbox` as described in the installation instructions: https://github.com/kalabox/kalabox/wiki/Normal-Installation

Here's what happened:

````
###############################################################

               Hi there! Updates are required!

 We see you just updated your kalabox code! That means that
 you should run our updater before you proceed.

          Please run `kbox update` before you proceed!

###############################################################
rjbain at ML-ITS-402152 in ~/kalabox/apps
$ kbox update
expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

TypeError: expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

    at process._tickCallback (node.js:917:1)
````

Thanks!
Rob

**Comment by pirog** [comment]
@rjbain there is no update pathway from v0.10.x to v0.11.x so you'll need to do an uninstall and then reinstall. This is indicated on the readme.

**Comment by rjbain** [comment]
@pirog that worked, thanks! Do I have to recreate my pantheon apps now? When I run `kbox apps` I get `{}`, but I see the folders still there for the apps I had before the update. If I need to recreate them, should I remove these folders under `/kalabox/apps/*` first?

**Comment by pirog** [comment]
awesome! yeah you'll need to recreate them. probably would be best to remove the old ones since a lot of things changed. 

probably going to drop the first bugfix release 0.11.1 in a day or so ... so look out for that since it cleared up a lot of the low hanging fruit errors that are typical of a first version
