### ISSUE TITLE
Parse error after updating to v0.11

### ISSUE THREAD

**Issue by jpmcneal** [kalabox/kalabox#893]
First, thanks for all of your work on this project.

My Drupal 8 Pantheon app isn't loading after I updated to v0.11 today. Sometimes I get a 502 error, but I eventually got the following error after visiting http://appserver.my-app.kbox/ :
```Parse error: syntax error, unexpected '[', expecting ')' in /code/vendor/guzzlehttp/promises/src/functions.php on line 41 Call Stack: 0.0031 650528 1. {main}() /code/index.php:0 0.0032 650920 2. require_once('/code/autoload.php') /code/index.php:14 0.0032 651352 3. require('/code/vendor/autoload.php') /code/autoload.php:14 0.0033 653784 4. ComposerAutoloaderInitDrupal8::getLoader() /code/vendor/autoload.php:7 0.0044 859824 5. composerRequireDrupal8() /code/vendor/composer/autoload_real.php:45 0.0044 860656 6. require('/code/vendor/guzzlehttp/promises/src/functions_include.php') /code/vendor/composer/autoload_real.php:55 ```

A [quick Google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=drupal+Parse+error%3A+syntax+error%2C+unexpected+'%5B'%2C+expecting+'\)'+in) reveals that the error appears to be a PHP issue.

**Comment by pirog** [comment]
Hey JP, 

Check out https://github.com/kalabox/kalabox/issues/865 as this might have a good workaround for you until we release 0.11.1. 

If that seems to work close this out!

**Comment by jpmcneal** [comment]
Thanks for the quick reply, Mike!

Sorry, I missed #865 , which solved my parse error. I also see that I need to update Drush...  how do I do that?

**Comment by pirog** [comment]
@jpmcneal we just rolled the 0.11.1 release which should resolve these issues. I would upgrade and then recreate your site.

**Comment by jpmcneal** [comment]
Thanks, @pirog I'm up and running!

**Comment by pirog** [comment]
@jpmcneal awesome! def post any issues you come across.
