### ISSUE TITLE
'kbox destroy' keep all the files as is

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#897]
on Windows 10 -
(running version 0.11.1)
After running 'kbox destroy' and receiving confirmation message about its success, - all files are still in the same place as if nothing was deleted.

```
kbox destroy
###############################################################

             WARNING! APP DESTRUCTION IMMINENT

  Before you continue please be aware that after you destroy
  an app there will be nothing left. That means yours app's
  codes, files, databases, indeces, caches, containers and
  EVERYTHING ELSE that has to do with your app WILL BE GONE.

###############################################################
? So, are you still prepared to DESTROY? Yes
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=stop, mode=collect
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=rm, 7=--force, 8=-v, mode=collect
info: DOCKER-COMPOSE.EXE =>  No stopped containers
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=run, 5=-d, 6=--entrypoint, 7=rm, 8=--rm, 9=syncthing, 10=-rf, 11=/code/3paces, mode=false
###############################################################

                 DESTRUCTION COMPLETE

###############################################################
```

**Comment by pirog** [comment]
Destroy won't remove your code it just removes the containers and other
infrastructure your site needs

On Wednesday, January 27, 2016, shaal <notifications@github.com> wrote:

> on Windows 10 -
> (running version 0.11.1)
> After running 'kbox destroy' and receiving confirmation message about its
> success, - all files are still in the same place as if nothing was deleted.
>
> kbox destroy
> ###############################################################
>
>              WARNING! APP DESTRUCTION IMMINENT
>
>   Before you continue please be aware that after you destroy
>   an app there will be nothing left. That means yours app's
>   codes, files, databases, indeces, caches, containers and
>   EVERYTHING ELSE that has to do with your app WILL BE GONE.
>
> ###############################################################
> ? So, are you still prepared to DESTROY? Yes
> info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
> info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=stop, mode=collect
> info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
> info: COMPOSE =>  0=--project-name, 1=3paces, 2=--file, 3=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-compose.yml, 4=--file, 5=C:\Users\shaal\Documents\kbox-pantheon\3paces\kalabox-cli.yml, 6=rm, 7=--force, 8=-v, mode=collect
> info: DOCKER-COMPOSE.EXE =>  No stopped containers
> info: DOCKER-COMPOSE.EXE =>  Run exited with code: 0
> info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=run, 5=-d, 6=--entrypoint, 7=rm, 8=--rm, 9=syncthing, 10=-rf, 11=/code/3paces, mode=false
> ###############################################################
>
>                  DESTRUCTION COMPLETE
>
> ###############################################################
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/897>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc
