### ISSUE TITLE
How do we connect to the DB in 0.11.x?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#899]
Hello

Prior to 0.11.x we could easily connect to the DB by running ```kbox containers``` and grabbing the port then using our mysql commands as so: mysql -u pantheon -h k2m.kbox -P 32799 pantheon

Now when you print out kbox containers, its just a giant array and it seems the DB connection string above is no longer valid.  The host seems to be database now, but when I run: 

```
john@kalamuna:~/kalabox/apps/k2m/code$ mysql -u pantheon -h k2m.kbox
ERROR 2003 (HY000): Can't connect to MySQL server on 'k2m.kbox' (111)
```

That happens, thoughts?

**Comment by labboy0276** [comment]
Workaround for now using the services container:

in kalabox-compose.yml add this to the db service (about line 134):
```
  ports:
    - "3306"
```
do a kbox rebuild

in kalabox.yml add this in the services portion below the appserver config (about line 18):
```
    db:
      - port: 3306/tcp
      - hostname: db.YOURAPNAME.kbox
```

do a kbox rebuild && kbox start

Then you can do one of 2 things to get the port number again:

Either run:
kbox containers > afilename,txt
Open up afilename.txt search for 3306/tcp and grab the HostPort

OR Run
kbox containers | grep "HostPort"
Should be the last port number.

Then you can connect again to mysql as so:
```
mysql -u pantheon -h db.YOURAPP.kbox -P THEPORT# pantheon
```

**Comment by WidgetsBurritos** [comment]
That workaround works for me.

**Comment by pirog** [comment]
Going to close this in favor of #770 

in 0.11.3 you'll be able to run `kbox info` inside your app to get relevant connection info
