### ISSUE TITLE
Incorrect link to Pantheon Starter Guide on Error 400 page (minor issue)

### ISSUE THREAD

**Issue by WidgetsBurritos** [kalabox/kalabox#903]
It's a minor issue but just wanted to make you aware of it.  On the Error 400 page, if you click on the Pantheon Starter Guide button it takes you to
https://github.com/kalabox/kalabox/wiki/Pantheon-Guide
![screenshot](https://cloud.githubusercontent.com/assets/5263371/12652472/92d43b50-c5b0-11e5-9686-e1764738698e.png)

But that wiki page doesn't appear to exist.

![screenshot 2](https://cloud.githubusercontent.com/assets/5263371/12652599/232dc8e2-c5b1-11e5-9660-8a154d12c41c.png)

I would assume it's supposed to link to this URL instead:
https://github.com/kalabox/kalabox-app-pantheon#kalabox-pantheon-app

**Comment by pirog** [comment]
So looks like this has been resolved already
https://github.com/kalabox/hipache/commit/28348cc12d9138a0a2975cfb525bf7b99bef8c92

But we need to roll a new hipache release over here https://github.com/kalabox/hipache

and then upgrade the proxy container here
https://github.com/kalabox/kalabox/blob/v0.11/plugins/kalabox-services-kalabox/dockerfiles/proxy/Dockerfile 

If you are interested in helping out on a PR for this let me know!

**Comment by WidgetsBurritos** [comment]
What all would be involved?

**Comment by pirog** [comment]
Big thing would be for me to roll a new release of hipache. After that we just need to upgrade the download version over at this dockerfile https://github.com/kalabox/kalabox/blob/v0.11/plugins/kalabox-services-kalabox/dockerfiles/proxy/Dockerfile

**Comment by WidgetsBurritos** [comment]
Okay.  Just let me know what you need me to do.

**Comment by pirog** [comment]
Will do! Going to move this into the 0.11.3 milestone so its something we will look at next week.

**Comment by pirog** [comment]
@WidgetsBurritos this was actually really easy so i went ahead and did it right and quick
