### ISSUE TITLE
Machine token Auth with Pantheon: Milestone this and break it up into issues

### ISSUE THREAD

**Issue by dustinleblanc** [kalabox/kalabox#905]
Dropping this here because I know it will become a thing. Pantheon just released token based auth for terminus and have plans to sunset the password auth in the future. It might be a good idea to get machine token auth into kbox before that happens

**Comment by pirog** [comment]
It's on the roadmap!

**Comment by pirog** [comment]
Let's ping the Pantheon people on the status here! @pirog

**Comment by dustinleblanc** [comment]
Hey @pirog Im checking on this, I'll see if there is an official timeline and let you know if there is anything to share.

**Comment by pirog** [comment]
@joshkoenig had mentioned the Pantheon team trying to take a pass on it so you might want to ping him. 

I'll def ask him as well because it might be easier for them to just sponsor the feature and have us do it?

**Comment by dustinleblanc** [comment]
@pirog it looks like we will be targeting this for the 1.0 release for this summer according to Josh. We will likely sunset email/pass auth within a reasonable time frame after that. What kind of work do you foresee being needed to refactor the authentication in Kalabox?

**Comment by joshkoenig** [comment]
I am intrigued by this "sponsor the feature" proposition, and would like to subscribe to your newsletter.

Let's discuss next week in NOLA!

**Comment by pirog** [comment]
![image](https://cloud.githubusercontent.com/assets/713424/15087251/3bb79b2a-13b5-11e6-93d2-66d2a14ba14f.png)

Sounds good. If chaos at DC is too intense, as can happen, i'll make a note for @reynoldsalec and i to ping you all on the flip side.

**Comment by pirog** [comment]
I've broken this issue into smaller pieces and create a milestone to track it. 
https://github.com/kalabox/kalabox#burndown?milestoneId=23
