### ISSUE TITLE
 VError: code3010err when installing kbox 11.1 from scratch

### ISSUE THREAD

**Issue by shaal** [kalabox/kalabox#906]
I uninstalled kbox using the batch file provided on github.
I manually uninstalled virtualbox.

i deleted all directories and files that had kbox containers before.

I run the command 'kbox create pantheon', 
and it exit in the middle of installation with an error

```
###############################################################

                    Welcome to Kalabox 2!

 We see this is your first time running a Kalabox command that
 requires the use of the Kalabox engine. Before we can do this
 We need to install some special things to make sure you are
 good to go. Please agree to the prompt below to install all
 the magic. (takes about 5 minutes with average download speed)

###############################################################
info: INSTALL =>  -- Step 1/22 --
info: INSTALL =>  Authorizing trilling subroutines...
? Install all the magic and get this party started? Yes
info: INSTALL =>  -- OK! 5% complete! --

info: INSTALL =>  -- Step 2/22 --
info: INSTALL =>  Making sure syncthing is not running...
info: INSTALL =>  -- OK! 9% complete! --

info: INSTALL =>  -- Step 3/22 --
info: INSTALL =>  Adding services images to build list...
info: INSTALL =>  -- OK! 14% complete! --

info: INSTALL =>  -- Step 4/22 --
info: INSTALL =>  Adding syncthing image to build list...
info: INSTALL =>  -- OK! 18% complete! --

info: INSTALL =>  -- Step 5/22 --
info: INSTALL =>  Queuing up syncthing downloads...
info: INSTALL =>  -- OK! 23% complete! --

info: INSTALL =>  -- Step 6/22 --
info: INSTALL =>  Checking firewall settings...
info: INSTALL =>  -- OK! 27% complete! --

info: INSTALL =>  -- Step 7/22 --
info: INSTALL =>  Checking for available disk space...
info: INSTALL =>  -- OK! 32% complete! --

info: INSTALL =>  -- Step 8/22 --
info: INSTALL =>  Updating Kalabox ISO if needed...
info: INSTALL =>  -- OK! 36% complete! --

info: INSTALL =>  -- Step 9/22 --
info: INSTALL =>  Queuing provider admin commands...
info: INSTALL =>  -- OK! 41% complete! --

info: INSTALL =>  -- Step 10/22 --
info: INSTALL =>  Queuing up provider downloads...
info: INSTALL =>  -- OK! 45% complete! --

info: INSTALL =>  -- Step 11/22 --
info: INSTALL =>  Checking for Internet access...
info: INSTALL =>  -- OK! 50% complete! --

info: INSTALL =>  -- Step 12/22 --
info: INSTALL =>  Downloading files...
     fetch : http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Win.exe
     fetch : https://raw.githubusercontent.com/kalabox/kalabox/v0.10/dockerfiles/syncthing/config.xml
     fetch : https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Windows-x86_64.exe
     fetch : https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/Git-1.9.5-preview20150319.exe
     fetch : https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_windows-amd64.exe
     fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.26/syncthing-windows-amd64-v0.11.26.zip
  progress : [====================] 100% 0.0s

info: INSTALL =>  -- OK! 55% complete! --

info: INSTALL =>  -- Step 13/22 --
info: INSTALL =>  Setting up syncthing...
info: INSTALL =>  -- OK! 59% complete! --

info: INSTALL =>  -- Step 14/22 --
info: INSTALL =>  Running admin install commands...
info: UTIL EXEC ADMIN =>  Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox
info: INSTALL =>  VError: code3010err:more:Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox

info: INSTALL =>  -- INSTALL FAILURE. --
```

**Comment by pirog** [comment]
Run 'kbox update'. Does it error at the same point?

I'm also pretty sure you already posted this exact error

On Thursday, January 28, 2016, shaal <notifications@github.com> wrote:

> I uninstalled kbox using the batch file provided on github.
> I manually uninstalled virtualbox.
>
> i deleted all directories and files that had kbox containers before.
>
> I run the command 'kbox create pantheon',
> and it exit in the middle of installation with an error
>
> ###############################################################
>
>                     Welcome to Kalabox 2!
>
>  We see this is your first time running a Kalabox command that
>  requires the use of the Kalabox engine. Before we can do this
>  We need to install some special things to make sure you are
>  good to go. Please agree to the prompt below to install all
>  the magic. (takes about 5 minutes with average download speed)
>
> ###############################################################
> info: INSTALL =>  -- Step 1/22 --
> info: INSTALL =>  Authorizing trilling subroutines...
> ? Install all the magic and get this party started? Yes
> info: INSTALL =>  -- OK! 5% complete! --
>
> info: INSTALL =>  -- Step 2/22 --
> info: INSTALL =>  Making sure syncthing is not running...
> info: INSTALL =>  -- OK! 9% complete! --
>
> info: INSTALL =>  -- Step 3/22 --
> info: INSTALL =>  Adding services images to build list...
> info: INSTALL =>  -- OK! 14% complete! --
>
> info: INSTALL =>  -- Step 4/22 --
> info: INSTALL =>  Adding syncthing image to build list...
> info: INSTALL =>  -- OK! 18% complete! --
>
> info: INSTALL =>  -- Step 5/22 --
> info: INSTALL =>  Queuing up syncthing downloads...
> info: INSTALL =>  -- OK! 23% complete! --
>
> info: INSTALL =>  -- Step 6/22 --
> info: INSTALL =>  Checking firewall settings...
> info: INSTALL =>  -- OK! 27% complete! --
>
> info: INSTALL =>  -- Step 7/22 --
> info: INSTALL =>  Checking for available disk space...
> info: INSTALL =>  -- OK! 32% complete! --
>
> info: INSTALL =>  -- Step 8/22 --
> info: INSTALL =>  Updating Kalabox ISO if needed...
> info: INSTALL =>  -- OK! 36% complete! --
>
> info: INSTALL =>  -- Step 9/22 --
> info: INSTALL =>  Queuing provider admin commands...
> info: INSTALL =>  -- OK! 41% complete! --
>
> info: INSTALL =>  -- Step 10/22 --
> info: INSTALL =>  Queuing up provider downloads...
> info: INSTALL =>  -- OK! 45% complete! --
>
> info: INSTALL =>  -- Step 11/22 --
> info: INSTALL =>  Checking for Internet access...
> info: INSTALL =>  -- OK! 50% complete! --
>
> info: INSTALL =>  -- Step 12/22 --
> info: INSTALL =>  Downloading files...
>      fetch : http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Win.exe
>      fetch : https://raw.githubusercontent.com/kalabox/kalabox/v0.10/dockerfiles/syncthing/config.xml
>      fetch : https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Windows-x86_64.exe
>      fetch : https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/Git-1.9.5-preview20150319.exe
>      fetch : https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_windows-amd64.exe
>      fetch : https://github.com/syncthing/syncthing/releases/download/v0.11.26/syncthing-windows-amd64-v0.11.26.zip
>   progress : [====================] 100% 0.0s
>
> info: INSTALL =>  -- OK! 55% complete! --
>
> info: INSTALL =>  -- Step 13/22 --
> info: INSTALL =>  Setting up syncthing...
> info: INSTALL =>  -- OK! 59% complete! --
>
> info: INSTALL =>  -- Step 14/22 --
> info: INSTALL =>  Running admin install commands...
> info: UTIL EXEC ADMIN =>  Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox
> info: INSTALL =>  VError: code3010err:more:Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox
>
> info: INSTALL =>  -- INSTALL FAILURE. --
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/906>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc

**Comment by shaal** [comment]
```
kbox update
info: INSTALL =>  -- Step 1/20 --
info: INSTALL =>  Authorizing trilling subroutines...
info: INSTALL =>  Non-interactive mode.
info: INSTALL =>  -- OK! 5% complete! --

info: INSTALL =>  -- Step 2/20 --
info: INSTALL =>  Adding services images to build list...
info: INSTALL =>  -- OK! 10% complete! --

info: INSTALL =>  -- Step 3/20 --
info: INSTALL =>  Adding syncthing image to build list...
info: INSTALL =>  -- OK! 15% complete! --

info: INSTALL =>  -- Step 4/20 --
info: INSTALL =>  Queuing up syncthing downloads...
info: INSTALL =>  -- OK! 20% complete! --

info: INSTALL =>  -- Step 5/20 --
info: INSTALL =>  Checking firewall settings...
info: INSTALL =>  -- OK! 25% complete! --

info: INSTALL =>  -- Step 6/20 --
info: INSTALL =>  Checking for available disk space...
info: INSTALL =>  -- OK! 30% complete! --

info: INSTALL =>  -- Step 7/20 --
info: INSTALL =>  Updating Kalabox ISO if needed...
info: INSTALL =>  -- OK! 35% complete! --

info: INSTALL =>  -- Step 8/20 --
info: INSTALL =>  Queuing provider admin commands...
info: INSTALL =>  -- OK! 40% complete! --

info: INSTALL =>  -- Step 9/20 --
info: INSTALL =>  Queuing up provider downloads...
info: INSTALL =>  -- OK! 45% complete! --

info: INSTALL =>  -- Step 10/20 --
info: INSTALL =>  Checking for Internet access...
info: INSTALL =>  -- OK! 50% complete! --

info: INSTALL =>  -- Step 11/20 --
info: INSTALL =>  Downloading files...
     fetch : http://download.virtualbox.org/virtualbox/5.0.12/VirtualBox-5.0.12-104815-Win.exe
     fetch : https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_windows-amd64.exe
     fetch : https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Windows-x86_64.exe
     fetch : https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20150319/Git-1.9.5-preview20150319.exe
  progress : [====================] 100% 0.0s

info: INSTALL =>  -- OK! 55% complete! --

info: INSTALL =>  -- Step 12/20 --
info: INSTALL =>  Running admin install commands...
info: UTIL EXEC ADMIN =>  Files were extracted to: C:\Users\shaal\.kalabox\downloads\vbox
info: INSTALL =>  -- OK! 60% complete! --

info: INSTALL =>  -- Step 13/20 --
info: INSTALL =>  Setting up the docker machine...
info: INSTALL =>  -- OK! 65% complete! --

info: INSTALL =>  -- Step 14/20 --
info: INSTALL =>  Updating install info...
info: INSTALL =>  -- OK! 70% complete! --

info: INSTALL =>  -- Step 15/20 --
info: INSTALL =>  Setting up and activating the engine...
info: INSTALL =>  -- OK! 75% complete! --

info: INSTALL =>  -- Step 16/20 --
info: INSTALL =>  Pulling images...
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-1.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
[31mERROR[0m: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-2.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
[31mERROR[0m: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-3.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
[31mERROR[0m: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-4.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
[31mERROR[0m: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=C:\Users\shaal\.kalabox\downloads\kalabox\kalabox-5.yml, 4=pull, mode=collect
Pulling proxy (kalabox/proxy:v0.11.1)...
[31mERROR[0m: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.
info: DOCKER-COMPOSE.EXE =>  Run exited with code: 1
info: INSTALL =>  VError: Failed after 5 retries. {"max":5,"backoff":500}: code1err:more:
info: INSTALL =>  -- INSTALL FAILURE. --
```

**Comment by pirog** [comment]
Is virtual box installed now? Looks like it's not spinning up the docker
machine correctly.

**Comment by pirog** [comment]
If you've got time tomorrow I'd love to do a screen share. These error you
are getting are really strange and I'd def like to investigate deeper if
possible.

**Comment by shaal** [comment]
Sure. Let me know when.

**Comment by pirog** [comment]
Actually. Let's try to shoot for Monday if you are free. That way i can investigate the #891 beforehand. Also going to close this a a dup of #887

**Comment by shaal** [comment]
great, thank u
