### ISSUE TITLE
Where are instruction for cloning a non-Pantheon site?

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#913]
I installed Kalabox 0.11.1 latest. Huzzah! success. (Mac OS X environment El Capitan)

Cannot figure out how to create a new app, or clone from my github repo. The kbox wiki really doesn’t say. Is there doc somewhere?
We do _not_ use Pantheon. Self hosted or on AWS.

Is Kalabox ready to create my local environment? I know, … alpha1.

Regards,
Don Koller

**Comment by labboy0276** [comment]
Hello Don

https://github.com/kalabox/kalabox/wiki/Creating-custom-apps

That will get you started on your journey.

On Sat, Jan 30, 2016 at 11:54 PM, Don Koller <notifications@github.com>
wrote:

> I installed Kalabox 0.11.1 latest. Huzzah! success. (Mac OS X environment
> El Capitan)
>
> Cannot figure out how to create a new app, or clone from my github repo.
> The kbox wiki really doesn’t say. Is there doc somewhere?
> We do *not* use Pantheon. Self hosted or on AWS.
>
> Is Kalabox ready to create my local environment? I know, … alpha1.
>
> Regards,
> Don Koller
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/913>.
>



-- 
*John Ouellet*
*Sr Developer & Support Manager*
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@donkoller, 

Right now we are only shipping with official support for pantheon. Keep things focused until we can get more stable with both GUI and CLI. 

That said, the documentation pointed out by @labboy0276 does give you some pointers on spinning up your own app. Additionally, with the docker-compose rebase done in 0.11.x you can now actually get pretty far with a custom set up just using 2-4 yaml files.

**Comment by donkoller** [comment]
Mike and  @labboy0276 <https://github.com/labboy0276> ,
Thanks for the info and suggestions.
Is the GUI version at a testable level yet?

Don
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by pirog** [comment]
@donkoller we are going to be releasing new generic apps for D7, D8 and Wordpress in our next release. By default we will spin up stock d7, d8 and wordpress sites so you will need to manually import your site specific stuff for now.

that said we will likely be launching a service soon to automatically do this for you.

**Comment by donkoller** [comment]
Mike that sounds terrific. I look forward to it.
I was asking Alec if 0.11 CLI is stable enough to use at a conference in about 8 weeks. On Windows 10 machine.

Regards,
Don
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by pirog** [comment]
It should be. It's probably stable enough now. 

That said, how are you planning to use it?

**Comment by donkoller** [comment]
Mike,

Demo is for a small 2 day industry conference the first week of May. (These are small business owners; not techie users.)  
Kalabox to run our web app on dedicated Win10 laptop as server. With 3 client PCs accessing the app for our demos.

I’ll give it a try. The CLI version will be fine. Don’t need the GUI for this set up. 
Need to run Ubuntu 14.04 LTS with LAMP and a few other standard Linux things. Drupal 7.

Any comments or suggestions?

I’ll report my progress on this on github.

Thanks,
Don
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>
