### ISSUE TITLE
Redo start page on GUI

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#925]
vagrant??!!?!?!

**Comment by reynoldsalec** [comment]
![screen shot 2016-02-01 at 5 39 55 pm](https://cloud.githubusercontent.com/assets/1153738/12737114/d64eb57e-c90a-11e5-97ef-c063facee9a1.png)

**Comment by pirog** [comment]
@reynoldsalec swap boot2docker for just "docker"?

**Comment by reynoldsalec** [comment]
Sure thing @pirog, I pushed that directly to v0.11 since it's an itsy-bitsy thing.
