### ISSUE TITLE
Get `grunt pkg` to run with "production" settings ie no navbar, icons

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#929]
I think this also implies we need a production package.json

**Comment by pirog** [comment]
https://github.com/nwjs/grunt-nw-builder

**Comment by reynoldsalec** [comment]
Modified nw.js to include

```
        window: {
          toolbar: false,
          icon: './build/src/images/kalaboxv2-ico.png',
          frame: false
        }
```

Complete list of options: http://docs.nwjs.io/en/v0.13.0-beta5/References/Manifest%20Format/#width

This works for getting the icon in mac in the sidebar, but not on the actual application icon in the browser.

**Comment by reynoldsalec** [comment]
Copying icns file into the Mac app after its been built (but before compression).

For Windows and LInux, I'm afraid we'll have to do some additional work to get the icon files embedded.

See https://github.com/nwjs/nw.js/wiki/Icons and https://github.com/nwjs/nw-builder#optionswinico

**Comment by reynoldsalec** [comment]
Windows icon doesn't work without Wine when packaging on Mac, tried installing Wine and it doesn't seem to help.

This seems to be a recurring issue in various versions of nw-builder:

- https://github.com/nwjs/nw-builder/issues/179

Commenting out the windows icon for now.

**Comment by pirog** [comment]
@reynoldsalec does the windows icon break the whole build?

**Comment by reynoldsalec** [comment]
Yeah @pirog, if you build on Mac it stops the build with an error regarding Wine. There's even an issue on github someone made complaining about the behavior.

**Comment by reynoldsalec** [comment]
I was hoping that you could override values from the "manifest" (package.json) in the Grunt tasks of nw-builder, but it looks like the window values (things like toolbar, size of the app frame, etc.) have to be specified in that manifest. Right now I have a different version of package.json that'll get used for grunt pkg, but I think it'd be better to modify one package.json with the appropriate production values so we don't have to make changes two places.

**Comment by reynoldsalec** [comment]
Ok, figured out the mystery here:

- manifest = package.json. It describes the nw.js application settings (stuff like including the toolbar, position of the window, size of window, etc.), ie: http://docs.nwjs.io/en/v0.13.0-beta5/References/Manifest%20Format/#manifest-format

- nw-builder settings are distinct; they go in the Gruntfile and just tell nw-builder how to create things. The [Manifest Options](https://github.com/nwjs/nw-builder#manifest-options) described on the nw-builder readme are options that nw-builder will use if they are found *in your manifest*.

So, to solve our problem, I added in the platformOverrides to package.json (our manifest) and nw-builder uses those when packaging the app, but on a normal grunt build, they will be ignored, thus achieving the goal of having a production and dev build of the app (albeit in a kind of weird way).

@pirog, that is a silly thing but the truth. Should be ready to merge, we'll have to tackle the size of the window issue via application CSS, created #954 for that.
