### ISSUE TITLE
0.11.0 Big ol' data loss on kbox restart

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#933]
I did a `kbox start`, was getting 500 internal service errors in the browser so ran `kbox restart`. Then I got a notification in PHPStorm that files on disk had changed. Took a look and the vast majority of my code directory had been wiped out. There were just some seemingly random files remaining, including a partial/corrupted .git directory. Other folders (e.g. config) appeared to be unaffected. Please let me know if I should email the logs somewhere (I don't want to upload them here).

**Comment by pirog** [comment]
@jdleonard this was a known issue with 0.11.0 that was resolved in 0.11.1
https://github.com/kalabox/kalabox/issues/884 for reference 

if its still a problem for you there are a couple of things we can do to make sure all your containers are up to date
