### ISSUE TITLE
GUI Improvements ROUND1

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#941]
- [x] Get initialize screen to light up
- [x] Get close out screen to mimic initialize screen
- [x] Better pantheon login (no modal, login confirmation, actual link cursor)
- [x] Visualize progress of site create

**Comment by reynoldsalec** [comment]
@rileysaurus is completing the "Visualize progress of site create" in #963

**Comment by reynoldsalec** [comment]
Smaller tasks in the sidebar:

- [ ] Change waiting notification on loading sites in sidebar
- [ ] Make sites under an account a dropdown

On the dashboard:

- [ ] Fix pull/push state animations to show action name

-
