### ISSUE TITLE
Error: "The provided host name is not valid for this server."

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#950]
I just uninstalled 0.10.something following the instructions on the site, including removing VirtualBox, then installed v0.11.1-alpha1 via the OS X binary.

I proceeded to create a pantheon app for the dev server of my site.  Everything got pulled down properly, but after running "kbox start", I'm now getting this error when I go to http://mysite.kbox:

> The provided host name is not valid for this server.

When I try https://mysite.kbox, I get the "Error 400, Lost in the clouds?" page.

Any ideas about what I should do?

```
17:code pk$ kbox start
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/pk/.kalabox/downloads/kalabox/kalabox-1.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/pk/.kalabox/downloads/kalabox/kalabox-2.yml, 4=run, 5=--entrypoint, 6=/bin/mkdir, 7=--rm, 8=syncthing, 9=-p, 10=/code/hjs, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/pk/.kalabox/downloads/kalabox/kalabox-3.yml, 4=run, 5=--entrypoint, 6=touch, 7=--rm, 8=syncthing, 9=/code/hjs/.stfolder, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/pk/.kalabox/downloads/kalabox/kalabox-4.yml, 4=run, 5=--entrypoint, 6=/bin/cp, 7=--rm, 8=syncthing, 9=/src/dev/hjs/code/.stignore, 10=/code/hjs/.stignore, mode=false
info: COMPOSE =>  0=--project-name, 1=kalabox, 2=--file, 3=/Users/pk/.kalabox/downloads/kalabox/kalabox-5.yml, 4=ps, 5=-q, 6=syncthing, 7=undefined
info: COMPOSE =>  0=--project-name, 1=hjs, 2=--file, 3=/Users/pk/dev/hjs/kalabox-compose.yml, 4=--file, 5=/Users/pk/dev/hjs/kalabox-cli.yml, 6=--file, 7=/Users/pk/.kalabox/downloads/hjs/hjs-6.yml, 8=up, 9=-d, mode=collect
Starting hjs_redis_1
Starting hjs_data_1
Starting hjs_solr_1
Starting hjs_db_1
Starting hjs_appserver_1
Starting hjs_edge_1
Starting hjs_cli_1
Starting hjs_terminus_1
info: DOCKER-COMPOSE =>  Run exited with code: 0
###############################################################

                       HOLLA!!!!!!

  Your app has started up correctly. Here are some vitals:

  URL: http(s)://hjs.kbox
  LOCATION: /Users/pk/dev/hjs

###############################################################
info: COMPOSE =>  0=--project-name, 1=hjs, 2=--file, 3=/Users/pk/dev/hjs/kalabox-compose.yml, 4=--file, 5=/Users/pk/dev/hjs/kalabox-cli.yml, 6=--file, 7=/Users/pk/.kalabox/downloads/hjs/hjs-6.yml, 8=ps, 9=-q, 10=appserver, 11=undefined
info: COMPOSE =>  0=--project-name, 1=hjs, 2=--file, 3=/Users/pk/dev/hjs/kalabox-compose.yml, 4=--file, 5=/Users/pk/dev/hjs/kalabox-cli.yml, 6=--file, 7=/Users/pk/.kalabox/downloads/hjs/hjs-6.yml, 8=ps, 9=-q, 10=edge, 11=undefined

```

**Comment by ptmkenny** [comment]
It's a Drupal 8 site if that matters.

**Comment by labboy0276** [comment]
Hello

This happened to me when I first went up to 0.11.x.

What I would do is download the 0.11.x uninstaller, run that, delete all the things.  Then manually remove ~/.kalabox && ~/.docker 

Then restart your laptop and reinstall kalabox and your app and try again.

**Comment by ptmkenny** [comment]
Thanks for the suggestion.

I just did what you said-- ran the 0.11.x installer, chose "remove all the things," deleted ~/.kalabox and ~/.docker, and rebooted.

Then I reinstalled the app from Kalabox, but I'm getting the exact same error message.

**Comment by ptmkenny** [comment]
Additional info:
From the same installation, which gives me the following error for a Drupal 8 site:

> The provided host name is not valid for this server.

I just tried to install a Drupal 7 site with kbox create pantheon.  This worked fine, and I now can access it through kbox with no problem.

The (broken kbox) Drupal 8 site is basically vanilla D8 (it only has a couple modules enabled, like Google Analytics, nothing that seems like it would break the site).

**Comment by labboy0276** [comment]
By chance did you use another VM to install the same site?  I doubt it would interfere, but is there anything in your /etc/hosts (this is a wild guess).

Also when it is installing, did you try and rename it to see if it works then?

**Comment by ptmkenny** [comment]
I did try installing it under a different name, but that produces the exact same error.

Here is the content of /etc/hosts:  (I'm pretty sure I haven't modified this, it's just stock 10.11.3.)

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcast host
::1             localhost 

```

**Comment by pirog** [comment]
http://drupal.stackexchange.com/questions/145286/what-does-the-provided-host-name-is-not-valid-for-this-server-mean

**Comment by ptmkenny** [comment]
Ok, yeah, that's it.  I did enabled the trusted hosts setting.

How do I find the server name to add to the trusted hosts list for kalabox?

Based on this:
http://drupal.stackexchange.com/questions/145690/untrusted-host-localhost-in/145994#145994

I tried adding a settings.local.php file with the following code:

```
<?php
$settings['trusted_host_patterns'][] = '^localhost$';

```

But after restarting the box and rebuilding the cache, I'm still getting the same error.

**Comment by pirog** [comment]
should just be appname.kbox

**Comment by ptmkenny** [comment]
Awesome, that worked-- but it only worked in settings.php, not settings.local.php.  This is the necessary line:

`$settings['trusted_host_patterns'][] = '^appname.kbox$';
`

**Comment by ptmkenny** [comment]
Closing this now.  It seems that because Kalabox very closely mimics Pantheon, it is detected as a Pantheon environment (Pantheon server environment variables are set), so settings.local.php is ignored.  So the code I use looks like this in settings.php:

```
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  // Trusted host settings
  switch ($_SERVER['PANTHEON_ENVIRONMENT']) {
    case 'live':
      $settings['trusted_host_patterns'] = array(
        '^example\.com$',
        '^.+\.example\.com$',
      );
    break;
    case 'test':
    case 'dev':
    default: // Multidev branches
      $settings['trusted_host_patterns'] = array(
        '^pantheon\.io$',
        '^.+\.pantheon\.io$',
        '\.kbox$',
      );
    break;
  }
```

**Comment by pirog** [comment]
Let's keep this open since there is stuff we can do on the Kalabox side to resolve this

**Comment by pirog** [comment]
@ptmkenny you also should be able to use `case 'kalabox':` if you wanted to target kalabox specifically. 

I'm going to move this into the 0.11.3 milestone. I think we can probably add this to our pressflow_settings so it works out of the box

**Comment by pirog** [comment]
@ptmkenny so it looks like this works "fine" on kalabox with a default drupal8 install. it only seems to fail if you've gone in and manually added things. 

I'm going to close this with a ref to this. if this is not something to worry about on pantheon we should not worry about it here either.
https://github.com/pantheon-systems/drops-8/issues/79
