### ISSUE TITLE
"kbox apps" command does not actually indicate running status

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#951]
When I run the "kbox apps" command, I get a list of my sites.  One of the data points is "running", but the value stays at zero whether the app is started or stopped.

```
  "mysite": {
    "running": 0,
    "total": 6
  },
```

**Comment by pirog** [comment]
Good catch. Should definitely fix this.

**Comment by pirog** [comment]
Going to merge this in with #770
