### ISSUE TITLE
Kbox start can be used on a machine that is already started with no warning

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#955]
I noticed that I can use "kbox start" on a machine that has already started, and instead of getting a message like "This kbox has already running," I instead get the startup output and the welcome message:

```

###############################################################

                       HOLLA!!!!!!

  Your app has started up correctly. Here are some vitals:

  URL: http(s)://d8vanilla.kbox
  LOCATION: /Users/pk/dev/d8vanilla

###############################################################
```

**Comment by pirog** [comment]
What output would you prefer?

**Comment by ptmkenny** [comment]
I'm confused about why I can start a machine that has already started.  When I start a machine that has already been started, I expect one of three things to happen:

* Get an error that says "You can't start this because it's already running."
* The machine restarts automatically, and I get a message that says "Since the machine was already running, it's been restarted."
* I get a prompt asking me "The machine is already running. Do you want to restart it? Y/n"

**Comment by pirog** [comment]
my guess is that it running `kbox start` on a machine that has already started actually doesnt do much of anything.

I think your first suggestion here makes the most sense.

**Comment by pirog** [comment]
@ptmkenny we are going to backlog this one until we have a better handle on #1027

**Comment by pirog** [comment]
@ptmkenny this should be easy to do now that we have a better way to do warnings. going to add to the alpha3 sprint
