### ISSUE TITLE
How do I access my site's files?

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#970]
Where are the files (not the code, but the user-uploaded files in Drupal like /sites/default/files) stored in v2? I just used `grep` to search the directory I installed the box into but I can't find them anywhere; still, I see them when I view the box in my web browser.

**Comment by pirog** [comment]
Not currently accessible unless you terminal into the appserver but this will change in the next version.

**Comment by pirog** [comment]
Also there are a few other issues about this. Def please try to search
those before opening up another ticket.

On Thursday, February 4, 2016, ptmkenny <notifications@github.com> wrote:

> Where are the files (not the code, but the user-uploaded files in Drupal
> like /sites/default/files) stored in v2? I just used grep to search the
> directory I installed the box into but I can't find them anywhere; still, I
> see them when I view the box in my web browser
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/970>.
>


-- 
Mike Pirog
Co-Founder, Kalabox Inc
