### ISSUE TITLE
GUI - Remove all the polling in favor of a docker event stream wrapper

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#971]
GUI - watch docker events stream to make gui site states more immediate

**Comment by pirog** [comment]
Let's try to remove polling for 

1. engine status
2. poll sites (appRegistry)
3. site states
4. add/remove sites?

We want to create an event wrapper around the docker event stream that emits the following

1. A site has been created
2. A site has been destroyed
3. A site has started
4. A site has stopped

And for now it is sufficient to wait for one app container to enter one of the above states. It might make the most sense to use docker tags to indicate app containers from service or run containers.
