### ISSUE TITLE
GUI - push and pull animation doesn't seem to be working

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#973]
GUI - push and pull animation doesn't seem to be working.

The pull animation ends early, the push animation doesn't seem to show up.

**Comment by rileysaurus** [comment]
Added $scope.ui.currentJob, which is either null when no job is running or an object with the following properties.

`{
  title: string,
  message: string || null,
  fn: function (for later troubleshooting we might have to do)
}`

**Comment by rileysaurus** [comment]
Current job should also have a string property for action (add, start, stop, pull, push, delete).

**Comment by reynoldsalec** [comment]
@rileysaurus added a basic overlay that should be a placeholder as you get those actions in place. If it gives you any trouble in testing, just remove the element from the dashboard template.
