### ISSUE TITLE
Better messaging on system request for user credentials

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#991]
On Mac OSX, we currently have references to OAScript. Not sure what this looks like on other systems, but we should see if we can get "Kalabox" in the dialogue as the application requesting permission.

**Comment by pirog** [comment]
+1 

we also probably want to see if we can do this for the password dialog on linux

**Comment by reynoldsalec** [comment]
Ok, after talking with @pirog and doing some research, I think this may not be worthwhile to pursue right now.

- You can specify a name/icon for an applescript that has been saved as an application in Script Editor: http://stackoverflow.com/questions/24382950/mac-applescript-ask-for-administrator-privileges-prompt
- However, you can't pass variables to an applescript saved as an application, so if you wanted a generic wrapper, you'd have to dynamically create the applescript application, inserting the command you want run inside of it.

I tried using osascript to run an applescript, passing in a command; this works but still shows osascript as the executing application.

Tried doing the same thing (and using the "open" command with the "--args" variable) in hopes of being able to run an Applescript application from the command line. No dice (can't pass in the variables).
