### ISSUE TITLE
List of environments for a site install shows wrong environments

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#992]
Came across this in user testing today; user saw a list of enviros unrelated to the site they had selected in the list of available sites.

I should check this out, seems like it could be a basic Angular issue.

Interestingly, they claimed that the environments were related to a site they had recently been working on...just noting it, guessing there's not a connection.

**Comment by pirog** [comment]
I actually was experiencing this before as well.

**Comment by rileysaurus** [comment]
This was a somewhat obscure bug. The pantheon integration was getting the environments for each site in parallel causing all of the sites to have the same environment for a provider. Easily fixed by mapping with a concurrency of 1.
