### ISSUE TITLE
GUI - when removing two apps, the second on fails with a syncthing error.

### ISSUE THREAD

**Issue by rileysaurus** [kalabox/kalabox#998]
Error dispatching event listeners [post-app-uninstall]: Unexpected error while waiting for syncthing http://127.0.0.1:60008 to start.: operation timed out

**Comment by pirog** [comment]
Can you consistently replicate this?

**Comment by pirog** [comment]
@rileysaurus does this seem to be the same thing as #1149?

**Comment by reynoldsalec** [comment]
Experienced the same issue when removing two apps at the same time.

**Comment by pirog** [comment]
Going to close this as duplicate of #1228
